### ISSUE TITLE
Treemacs throws errors without hl-line colour definition

### ISSUE THREAD

**Issue by technician77** [Alexander-Miller/treemacs#100]
I need to configure
`(set-face-attribute 'hl-line nil :foreground "black" :background "yellow")`
otherwise I get:
```
Unable to load color "unspecified-bg"
Unable to load color "unspecified-fg"
```
I also got something like hl-line background is not defined falling back to unspecified-bg. I haven't saved that error, but I think that error handling in in your code.

**Comment by Alexander-Miller** [comment]
Short answer: I need those colors for my icons.

Long answer, copy pasted from the code:

```
;; An explanation for the what and why of the icon highlighting code below:
;; Using png images in treemacs has one annoying visual flaw: they overwrite the overlay
;; used by hl-line, such that the line marked by hl-line will always show a 22x22 pixel
;; gap wherever treemacs places an icon, regardessof transparency.
;; Using xpm instead of png images is one way to work around this, but it degrades icon
;; quality to an unacceptable degree. Another way is to directly change images' :background
;; property. The backgrounds colors are derived from the current theme with `treemacs--setup-icon-highlight'
;; and saved in `treemacs--selected-icon-background' and `treemacs--not-selected-icon-background'.
;; Every icon string stores two images with the proper :background values in its properties
;; 'img-selected and 'img-unselected. The 'display property of the icon in the current line
;; is then highlighted, and the previously highlighted icon unhighlighted, by advising
;; `hl-line-highlight'. The last displayed icon is saved as a button marker in `treemacs--last-highlight'.
;; Since it is a marker in the treemacs buffer it is important for it to be reset whenever it might
;; become invalid.
```

> I also got something like hl-line background is not defined falling back to unspecified-bg. 

That means treemacs couldn't find the background of the `hl-line` face and will fall back to the same value as default background. Not sure why it says unspecifed for you. The color is queried with `(face-attribute 'default :background nil t)`. When emacs cannot find it it should return `'unspecified`, in which case treemacs falls back on #2d2d31.

I've been thinking about adding something to define a custom hl-line highlight color in treemacs, but I'm not sure it'll solve your issue since it looks like treemacs cannot find your theme's default background color.

**Comment by dakra** [comment]
jFYI: I got the same error `[Treemacs] Warning: couldn’t find hl-line-mode’s background color, falling back on unspecified-bg.`

Using `moe-dark` theme if that matters.

**Comment by Alexander-Miller** [comment]
Did some research. Looks like the issue is that you're using emacs in a terminal where no background color is defined and is instead derived from your terminal settings.
I'll try to come up with something.

**Comment by dakra** [comment]
I start emacs with `--fg-daemon` from systemd.

I just tested it and when starting directly from
a shell, with `-nw` option or without, it doesn't
show the message.

**Comment by Alexander-Miller** [comment]
I have a fix for setting a fallback at load time. Now I need to know how this works at runtime, since the icon colors are also updated whenever you enable or disable a theme. What's the output of each of the following two lines for you?
 * `(face-attribute 'default :background nil t)`
 * `(face-attribute 'hl-line :background nil t)`

**Comment by dakra** [comment]
When I do it after emacs is loaded I get `face attribute default/hl-line: #303030/#3a3a3a`
So I put `  (message (format "face attribute default/hl-line: %s/%s" (face-attribute 'default :background nil t) (face-attribute 'hl-line :background nil t)))` to see what it is when the treemacs shows the warning and there I get:
`face attribute default/hl-line: unspecified-bg/unspecified`.

Also not sure about @technician77 but for me it's only about getting that warning displayed. Nothing is broken and treemacs (with icons etc) works just fine. I just don't like warnings in my startup messages ;)

So don't spent too much time trying to fix it :)

**Comment by Alexander-Miller** [comment]
@dakra https://github.com/Alexander-Miller/treemacs/commit/f62a946f0fc5db79d37fb748ab49334c4e3cbbfd should cover your use-case then.

@technician77 What about you? Do you just want the warnings gone, or do you need to be able to set the fallback colors before treemacs is loaded?

**Comment by technician77** [comment]
Well, I can live with the situation. I defined the colours in my hl-line package using use-package. I use the tango-dark theme which is integrated in emacs.

This is my default face, background and foreground are defined.
`(set-face-attribute 'default nil :family "Source Code Pro" :background "black" :foreground "white" :foundry "outline" :slant 'normal :weight 'normal :height 143 :width 'normal)`

**Comment by rileyrg** [comment]
("treemacs" . "e63fc3873da685768d9a6ba0dd85842b730a8d1e")


just an fyi:-

[Treemacs] Warning: couldn’t find hl-line-mode’s background color for icons, falling back on unspecified-bg.

```
    (use-package helm-themes
      :config
      (load-theme 'tsdh-dark))

```

**Comment by Alexander-Miller** [comment]
Oh hell no! If it can't find hl-line's color it falls back to
`treemacs--not-selected-icon-background`. And that one is defined as

```Elisp
(pcase (face-attribute 'default :background nil t)
    ('unspecified
     (prog1 "#2d2d31"
       (unless (boundp 'treemacs-no-load-time-warnings)
         (message "[Treemacs] Warning: coudn't find default background color for icons, falling back on #2d2d31."))))
    ('unspecified-bg
     (prog1 "#2d2d31"
       (unless (boundp 'treemacs-no-load-time-warnings)
         (message "[Treemacs] Warning: background color is unspecified, icons will likely look wrong. Falling back on #2d2d31."))))
    (other other))
```

`'unspecified-bg` is clearly caught in its own branch, so how the hell
did it get there?

What does `(type-of treemacs--not-selected-icon-background)` output?
