### ISSUE TITLE
Extra blue bar in Treemacs sidebar

### ISSUE THREAD

**Issue by anildigital** [Alexander-Miller/treemacs#1000]
Started seeing this extra blue bar in Treemacs sidebar

<img width="376" alt="image" src="https://user-images.githubusercontent.com/266/210712575-f3ad7dad-501e-4ce6-95b3-3e436c503e18.png">

It's annoying, I have to close sidebar and open it again to remove it.

I also saw it appearing more than 2 times in sidebar.

Build:
[Treemacs] v3.0 (installed 2023.01.05) @ Emacs 30.0.50

**Comment by Alexander-Miller** [comment]
That's ... a modeline?

Can you interact with it, move the cursor on top and call something like `describe-char`?

What happens if you do this?
`(with-current-buffer (treemacs-get-local-buffer)  (setf mode-line-format "FOO"))`

**Comment by anildigital** [comment]
@Alexander-Miller 

For `describe-char` 
```
             position: 150 of 4197 (4%), column: 0
            character: SPC (displayed as SPC) (codepoint 32, #o40, #x20)
              charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x20
               script: latin
               syntax:   	which means: whitespace
             category: .:Base, a:ASCII, l:Latin
             to input: type "C-x 8 RET 20" or "C-x 8 RET SPACE"
          buffer code: #x20
            file code: #x20 (encoded by coding system utf-8-unix)
              display: by this font (glyph code):
    mac-ct:-*-MonoLisa-regular-normal-normal-*-16-*-*-*-m-0-iso10646-1 (#x01)

Character code properties: customize what to show
  name: SPACE
  general-category: Zs (Separator, Space)
  decomposition: (32) (' ')

There are 2 overlays here:
 From 150 to 151
  before-string        [Show]
 From 150 to 165
  face                 hl-line
  priority             -50
  window               nil
```

For 

`(with-current-buffer (treemacs-get-local-buffer)  (setf mode-line-format "FOO"))`

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/266/210937416-92c178e5-154e-4020-be94-4fb831654ceb.png">

**Comment by anildigital** [comment]
I am using same Emacs version. This bug only recently started occurring after some package updates (probably treemacs). When these multiple blue mode line bars appear, let's say 3 times, I have to hit keybinding for (Cmd+Shift+1 in my case) `(treemacs &optional ARG)` 3 times, so seems multiple instances of treemacs sidebar are getting created somehow.

**Comment by anildigital** [comment]
@Alexander-Miller Extra blue bar appears when I hit keybinding for `(treemacs-delete-other-windows)`. I guess there is some change around this function recently.

**Comment by Alexander-Miller** [comment]
What's the value when of `treemacs--scope-storage` before and after you run `treemacs-delete-other-windows`?

**Comment by Alexander-Miller** [comment]
Closing on account of inactivity. Feel free to reopen if the issue is still relevant.
