### ISSUE TITLE
Is there a way to disable drag-n-drop in treemacs?

### ISSUE THREAD

**Issue by zoechi** [Alexander-Miller/treemacs#1008]
I often use the mouse to navigate (scroll, expand/collaps folders, ...) and often when I click the treemacs window scrolls a bit or I accidentally move the mouse a bit, suddenly files or folders are moved. Restoring that is quite cumbersome.

I never use the mouse to move files or folders intentionally and it would be great if I could just disable drag-n-drop.

**Comment by ignamartinoli** [comment]
I'm having the same problem!

**Comment by ignamartinoli** [comment]
@zoechi I just found the solution

```elisp
(use-package treemacs
  :bind
  (:map global-map
        ([f2] . treemacs)
   :map treemacs-mode-map       ;; THE SOLUTION
        ([drag-mouse-1] . nil)) ;; IS RIGHT HERE
  :init (setq treemacs-show-hidden-files nil))
```

**Comment by zoechi** [comment]
@ignamartinoli thanks a lot🚀. I guess this can be closed then.

**Comment by Alexander-Miller** [comment]
> @zoechi I just found the solution

This is the correct approach. 
That or overriding the behavior of `treemacs-dragleftclick-action` with `fset` or advice.
