### ISSUE TITLE
ace-window integration seems broken

### ISSUE THREAD

**Issue by matthemsteger** [Alexander-Miller/treemacs#1009]
When using `o-a-a`

Error in minibuffer and messages buffer:
`treemacs-visit-node-ace: Wrong number of arguments: #<subr ace-select-window>, 1`

```
Debugger entered--Lisp error: (wrong-number-of-arguments #<subr ace-select-window> 1)
  ace-select-window("Select window")
  treemacs-visit-node-ace(nil)
  funcall-interactively(treemacs-visit-node-ace nil)
  command-execute(treemacs-visit-node-ace)
```

```
[Treemacs] v3.0 (installed 2023.03.09) @ Emacs 28.2
```

`ace-window` hasn't been updated in a while, so I assume its a treemacs change https://github.com/Alexander-Miller/treemacs/commit/dfc3affacf5281e9c13f3d370650789ef98614f5

**Comment by LevPetrovitch** [comment]
The following is a workaround, waiting for the bug to be fixed:
```
(defun -ignore-arguments (orig &rest args) (funcall orig))
(add-function :around (symbol-function 'ace-select-window) #'-ignore-arguments)
```

**Comment by wxyucs** [comment]
Encountered the same bug, the #1010 patch can fix this issue.

Error msg: `Wrong number of arguments: (0 . 1), 1`

**Comment by LevPetrovitch** [comment]
ups, sorry :) This should be done after loading `ace-window`. I put the call to `add-function` in the `:init` section of the `use-package` block for `ace-window`. Something like
```
(defun -ignore-arguments (orig &rest args) (funcall orig))

(use-package ace-window
  :config
	(add-function :around (symbol-function 'ace-select-window) #'-ignore-arguments)
	(customize-set-variable 'aw-background t)
	(customize-set-variable 'aw-scope 'frame)
	(customize-set-variable 'aw-dispatch-always t)
    :bind ("C-c w" . ace-window))
```

**Comment by Alexander-Miller** [comment]
Bad refactor, sorry about that. The fix has been pushed now.
