### ISSUE TITLE
Allow `COMMENT` for disabling workspaces similar to projects

### ISSUE THREAD

**Issue by david-alvarez-rosa** [Alexander-Miller/treemacs#1012]
Similarly to [disabling projects](https://github.com/david-alvarez-rosa/treemacs#disabling-projects) it would be nice to be able to disable full workspace using the same `COMMENT` keyword.

**Comment by Alexander-Miller** [comment]
Feature's implemented now. To simplify implementation disabled workspaces are moved to the bottom of the list.

Let me know if anything is missing.

**Comment by david-alvarez-rosa** [comment]
That's awesome @Alexander-Miller! Appreciate it, thank you much 😊 

(btw, you should consider opening some kind of sponsorship options ;))

**Comment by Alexander-Miller** [comment]
> (btw, you should consider opening some kind of sponsorship options ;))

(Bit of a late reply, but I just cleaned the email from my backlog.)

I have a stable day job I like, and am just fine with treemacs being a side-hobby and nothing more. If you feel like being generous then there are plenty of better options to donate to than any potential coffee fund of mine.
