### ISSUE TITLE
Change background color with a face

### ISSUE THREAD

**Issue by tralph3** [Alexander-Miller/treemacs#1014]
I would like it if treemacs allowed you to change the background color of its buffer with a face. I know it can be done with `treemacs-window-background-color`, but once this is changed, the treemacs buffer needs to be killed (not even re-opened, entirely killed) for it to take effect.

This is troublesome to me since I like to switch colorschemes on the fly by setting faces with `set-face-attribute` and I can't do this with treemacs. Why it uses such a weird method, I don't know. Maybe it's a technical limitation, but it would be great if this customization could be done with a face instead, so it's better integrated with emacs and it could be updated instantly.

**Comment by Alexander-Miller** [comment]
Makes sense, I'll start working on it now.

> Why it uses such a weird method, I don't know. Maybe it's a technical limitation

Best I remember: path of least resistance and me not being very familiar with the face remapping api :man_shrugging:.

**Comment by Alexander-Miller** [comment]
> This is troublesome to me since I like to switch colorschemes on the fly by setting faces with set-face-attribute

That still won't be doable. When these faces change treemacs needs to adjust its icons' background colors so they're aligned with current (hl-line) background. That step will stay necessary until I migrate all my icons to svgs.

It's automated when you load a new theme, but for changing faces on the fly you'll need a callback (either that or you kill the treemacs buffer).

**Comment by tralph3** [comment]
> That still won't be doable

Thing is, it kind of already works. By default, treemacs sets its background color to the `default` face background color. If I change the background color of the `default` face, treemacs does update instantly. It's true that the background for the icons remains the same, but that could be updated with a hook, right? I assume you must have a function somewhere to update them. Can't that be easily automated?

**Comment by Alexander-Miller** [comment]
> It's true that the background for the icons remains the same, but that could be updated with a hook, right? I assume you must have a function somewhere to update them. Can't that be easily automated?

Yes, and yes. Treemacs can do and will do that on its own when there is somewhere to hook into, like loading a new theme. You said you were using `set-face-attribute`. There are no hooks for me in there, meaning it will be up to you to call into treemacs' color correction.

Anyway , the new api looks like this:

`treemacs-window-background-color` is now deprecated and no longer in use. Instead I've added the 2 faces `treemacs-window-background-face` and `treemacs-hl-line-face`. You can correct icons' backgrounds by calling `treemacs-realign-icon-colors`.

**Comment by tralph3** [comment]
Thank you! It works perfectly :)
