### ISSUE TITLE
treemacs-change-root keypress on first line, shows wrong type argument

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#102]
With the first line in the Treemacs window selected, ex: `*.emacs.d*`
Pressing `l` (lowercase L), which calls `(treemacs-change-root)`
Shows: `button-get: Wrong type argument: integer-or-marker-p, nil` in the `*Messages*` buffer.

Changing to the current root doesn't make sense, but if `l` is pressed there by accident, then maybe the error message should be the same as when `l` is pressed on a file:
`[Treemacs] Button in current line is not a directory.`

And maybe `in` should be changed to `on`, resulting in:
`[Treemacs] Button on current line is not a directory.`

Or it could just say:
`[Treemacs] Current selection is not a directory.`

Windows 10 1607 (OS Build 14393.1884)
GNU Emacs 26.0.50 (build 4, x86_64-w64-mingw32) of 2017-08-07
treemacs-20171116.1011

**Comment by Alexander-Miller** [comment]
> With the first line in the Treemacs window selected, ex: *.emacs.d*

In  treemacs-lingo it's called the header.

> button-get: Wrong type argument: integer-or-marker-p, nil in the *Messages* buffer.

Thanks for the report. https://github.com/Alexander-Miller/treemacs/commit/4106ee068b81d5cc6c3f518d09daff6f05e7f2f9 will take care of this.
