### ISSUE TITLE
Setting background color

### ISSUE THREAD

**Issue by sethen** [Alexander-Miller/treemacs#1022]
I saw that the previous API was deprecated in favor of 	`treemacs-window-background-face` but it's not working when I am setting it.  I am setting it like `(setq treemacs-window-background-face "#ffffff")`... Am I missing something?

**Comment by Alexander-Miller** [comment]
What you're setting is a face, not a normal variable. Faces are more or less Emacs' version of css styles, you can do a lot more with them than set a single color. There's foreground, background, slant, weight, font, underline settings and a few others. 

There are many ways to manipulate faces, but for treemacs you only need the background, which can be changed like this:

```Elisp
(set-face-background 'treemacs-window-background-face "#ff0000")
(set-face-background 'treemacs-hl-line-face "#00ff00")
```

If you notice icons' background colors not fitting in with the rest of the buffer you also need to add `(treemacs-realign-icon-colors)`.
