### ISSUE TITLE
Invalid image type 'svg' after updated to the 20230424.2017 version

### ISSUE THREAD

**Issue by binbowang1987** [Alexander-Miller/treemacs#1025]
![图片](https://user-images.githubusercontent.com/8586061/236686880-8ba0bfa5-30a8-4ff3-89b5-81ad7ea5c259.png)

**Comment by reinout** [comment]
There's a quick workaround: https://github.com/Alexander-Miller/treemacs/issues/1017#issuecomment-1515602288

**Comment by Alexander-Miller** [comment]
Treemacs should no longer try and create svg files if sees that your Emacs does not support them. Do you still see this error with the latest version?
