### ISSUE TITLE
Folder icons are missing

### ISSUE THREAD

**Issue by refaelsh** [Alexander-Miller/treemacs#1029]
Here is a screenshot:
![no_icon](https://github.com/Alexander-Miller/treemacs/assets/2750775/00d3f179-11f9-4aea-ad2c-e29c1cf106b8)
If I open for example the Core folder, the icon appears:
![yes_icon](https://github.com/Alexander-Miller/treemacs/assets/2750775/e2cd5296-8dd4-476e-9962-2feb257cc634)

Please help :-)

**Comment by Alexander-Miller** [comment]
Do you see the right icons if you call `treemacs-icon-catalogue`?

Is this problem consistent, or do you see it only sometimes? For some directories, or all?

What's inserted into treemacs if you run this?

```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (treemacs-with-writable-buffer
   (insert
    (format "%s\n%s"
            (treemacs-icon-for-file "Core")
            (treemacs-icon-for-dir "Core" 'closed)))))
```

**Comment by refaelsh** [comment]
> Do you see the right icons if you call treemacs-icon-catalogue?

No. I see a big org file with a bunch of tables. No icons anywhere.
![2023-05-30_22-41](https://github.com/Alexander-Miller/treemacs/assets/2750775/6b5bc477-596b-42af-93c5-0723d016f310)

> Is this problem consistent

Yes.

> For some directories, or all?

For all.

> What's inserted into treemacs if you run this?

I am not sure if I understand what you want me to do. I am still an Emacs newbie, transitioning from Neovim.
I pasted your code into *scracth* bufer and did M-x eval-buffer and got `Wrong type argument: stringp, nil`.

**Comment by refaelsh** [comment]
> What does the content of the treemacs--themes variable look like?

![bla](https://github.com/Alexander-Miller/treemacs/assets/2750775/807dacbc-414f-425f-8c32-1d29701a7f39)

> What's inserted into treemacs if you run this?

![arrow](https://github.com/Alexander-Miller/treemacs/assets/2750775/bfba7b78-20a9-4380-9a60-6cc3aea962a8)

**Comment by Alexander-Miller** [comment]
Those are all-the-icons in the first image. Do you mean to use the all-the-icons theme, or is it just loaded incidentally? Do you have your own config or do you use a distro like doom emacs? What's the value of `treemacs--current-theme`?

**Comment by refaelsh** [comment]
> Do you mean to use the all-the-icons theme, or is it just loaded incidentally?

I dont know how to answer that, but here is the relevant part of my config:
```elisp
* Treemacs
#+begin_src emacs-lisp
  (use-package treemacs)
  (treemacs-follow-mode t)
  (treemacs-filewatch-mode t)
  (treemacs-fringe-indicator-mode 'always)
  (setq treemacs-width 27)

  (when treemacs-python-executable
    (treemacs-git-commit-diff-mode t))

  (pcase (cons (not (null (executable-find "git")))
               (not (null treemacs-python-executable)))
    (`(t . t)
     (treemacs-git-mode 'deferred))
    (`(t . _)
     (treemacs-git-mode 'simple)))

  (treemacs-hide-gitignored-files-mode nil)

  (use-package treemacs-evil)
  (use-package treemacs-projectile)
  (use-package treemacs-magit)
  (use-package treemacs-icons-dired)
  (use-package treemacs-persp)
  (use-package treemacs-perspective)
  (use-package treemacs-tab-bar)
  (use-package treemacs-all-the-icons)
#+end_src
```

> Do you have your own config or do you use a distro like doom emacs?

I have my own config.

> What's the value of treemacs--current-theme?

![theme](https://github.com/Alexander-Miller/treemacs/assets/2750775/807047ae-c97a-43dd-86e7-78a204bcd7d5)

**Comment by Alexander-Miller** [comment]
> I dont know how to answer that, but here is the relevant part of my config:

For someone new to Emacs that's a solid looking config. Lots of rookie mistakes you could've made here.

You're using the all-the-icons package, so that explains things. Nothing wrong on that end, it's not our culprit (though you can drop the package if you're not using the theme).

The current theme also looks right, so it's not some miscompilation or bad load.

Next step: tracing what's actually called. I've used a bunch of inlined functions in the render loop so I can't just give you some functions to evaluate, we'll have to change the code on your end. Start by going into the treemacs package installation directory (normally it's ~/.emacs.d/elpa/treemacs-$some-version) and delete all the .elc files. That way we won't have to deal with all the inlined byte code.

Then apply the following changes:

```Diff
modified   src/elisp/treemacs-icons.el
@@ -503,6 +503,14 @@ Uses `treemacs-icon-fallback' as fallback."
   (inline-letevals (file)
     (inline-quote
      (let ((file-downcased (-> ,file (treemacs--filename) (downcase))))
+       (treemacs-log "Get Icon for file %s %s" ,file file-downcased)
+       (treemacs-log "Icon = %s"
+         (get-text-property
+          0 'display
+          (or (ht-get treemacs-icons file-downcased)
+              (ht-get treemacs-icons
+                      (treemacs--file-extension file-downcased)
+                      (with-no-warnings treemacs-icon-fallback)))) )
        (or (ht-get treemacs-icons file-downcased)
            (ht-get treemacs-icons
                    (treemacs--file-extension file-downcased)
@@ -520,6 +528,19 @@ Uses the `dir-open' and `dir-closed' icons as fallback."
      (let ((name-downcased (-> ,dir (treemacs--filename) (downcase))))
        (when (eq ?. (aref name-downcased 0))
          (setf name-downcased (substring name-downcased 1)))
+       (treemacs-log "Get Icon for dir %s %s %s" ,dir name-downcased ,state)
+       (treemacs-log "Icon = %s"
+         (get-text-property
+          0 'display
+          (pcase-exhaustive ,state
+            (`open
+             (let ((name (format "%s-%s" name-downcased "open")))
+               (or (ht-get treemacs-icons name)
+                   (ht-get treemacs-icons 'dir-open))))
+            (`closed
+             (let ((name (format "%s-%s" name-downcased "closed")))
+               (or (ht-get treemacs-icons name)
+                   (ht-get treemacs-icons 'dir-closed)))))))
        (pcase-exhaustive ,state
          (`open
           (let ((name (format "%s-%s" name-downcased "open")))
modified   src/elisp/treemacs-rendering.el
@@ -206,6 +206,7 @@ DEPTH indicates how deep in the filetree the current button is."
   (inline-letevals (path prefix parent depth)
     (inline-quote
      (let ((path (file-name-nondirectory ,path)))
+       (treemacs-log "Create dir line for path %s" path)
        (list
         ,prefix
         (treemacs-icon-for-dir path 'closed)
@@ -229,20 +230,22 @@ PARENT is the (optional) button under which this one is inserted.
 DEPTH indicates how deep in the filetree the current button is."
   (inline-letevals (path prefix parent depth)
     (inline-quote
-     (list
-      ,prefix
-      (treemacs-icon-for-file ,path)
-      (propertize (->> ,path file-name-nondirectory (funcall treemacs-file-name-transformer))
-                  'button '(t)
-                  'category 'default-button
-                  'help-echo nil
-                  'keymap nil
-                  :default-face 'treemacs-git-unmodified-face
-                  :state 'file-node-closed
-                  :path ,path
-                  :key ,path
-                  :parent ,parent
-                  :depth ,depth)))))
+     (progn
+       (treemacs-log "Create file line for path %s" ,path)
+       (list
+        ,prefix
+        (treemacs-icon-for-file ,path)
+        (propertize (->> ,path file-name-nondirectory (funcall treemacs-file-name-transformer))
+                    'button '(t)
+                    'category 'default-button
+                    'help-echo nil
+                    'keymap nil
+                    :default-face 'treemacs-git-unmodified-face
+                    :state 'file-node-closed
+                    :path ,path
+                    :key ,path
+                    :parent ,parent
+                    :depth ,depth))))))
```

Then restart Emacs to apply the changes. The output will look like this:
![out](https://github.com/Alexander-Miller/treemacs/assets/5951157/25159cf4-ed1d-4081-8a9c-6423d9dfee12)

I need to see this output for the render of a branch with  broken icons to trace which icons are looked up from where.

**Comment by refaelsh** [comment]
Sorry, I will get back to you asap. I somehow managed to screw up my config and restoring from backup does not help.

**Comment by refaelsh** [comment]
I restored my config from a backup. The problem no longer occurs.
I did many things while trying to restore me config. Many things.
Solved many errors. I dont sure what I did to make the problem go away,

Thank you for all the help :-)
