### ISSUE TITLE
Treemacs help hydra changes selected window away from Treemacs window

### ISSUE THREAD

**Issue by rswgnu** [Alexander-Miller/treemacs#103]
With point in a Treemacs window you can use {n} and {p} to move among entries.  But if you do a {? n} or {? ? n}, the selected window changes away from the Treemacs window.  Having this fixed would be very handy.

Treemacs looks great, by the way.

One feature request, make it easy to set an option that displays a function/variable/other-item at the top of the window rather than in the middle.

**Comment by Alexander-Miller** [comment]
>  Having this fixed would be very handy.

Pushed a fix. Let me know if it works on your end.

> One feature request, make it easy to set an option that displays a function/variable/other-item at the top of the window rather than in the middle.

Are you referring to some specific function or minor mode in treemacs? Do you mean something like an extra option for https://github.com/Alexander-Miller/treemacs/issues/84?

**Comment by rswgnu** [comment]
On Sat, Nov 18, 2017 at 5:38 AM, Alexander-Miller <notifications@github.com>
wrote:

> Having this fixed would be very handy.
>
> Pushed a fix. Let me know if it works on your end.
>

Unfortunately no, the selected-window still changes to something other than
the treemacs browser window in both the cases I listed.
I am using the latest treemacs melpa release from today​ and essentially
Emacs 26 (though the Emacs says 27 because I use the master branch):

"GNU Emacs 27.0.50, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version
10.12.6 (Build 16G29))
 of 2017-10-04"

​​
> One feature request, make it easy to set an option that displays a
> function/variable/other-item at the top of the window rather than in the
> middle.
>
> Ar
> ​​
> e yo
> ​​
> u referring to some specific function or minor mode in treemacs? Do you
> mean something like an extra option for #84
> <https://github.com/Alexander-Miller/treemacs/issues/84>?
>
> ​I think that is a similar request though to make it easy to use I would
envision a customizable option that if a non-negative integer would call
recenter with that value and if a function would call the function with
point on the item to display.  That way beginner and more advanced users
could customize it.​

Bob

**Comment by rswgnu** [comment]
I also tested the fix running from only treemacs .el files in Emacs 25.3
and had the same issue.

Bob

**Comment by Alexander-Miller** [comment]
> a customizable option that if a non-negative integer would call recenter with that value and if a function would call the function with point on the item to display.

Yeah, that's what I had in mind as well, I'll put it on my todo list.

> Unfortunately no, the selected-window still changes to something other than the treemacs browser window in both the cases I listed.

Just to be clear: what exactly is the issue? The patch I pushed changed the hydra to stick around when you navigate in treemacs. That works on my end, except when I use tab. And it looks like there is nothing I can do about tab, since the hydra disappears even when tab is bound to `ignore`.

**Comment by rswgnu** [comment]
On Sat, Nov 18, 2017 at 11:02 AM, Alexander-Miller <notifications@github.com
> wrote:

> a customizable option that if a non-negative integer would call recenter
> with that value and if a function would call the function with point on the
> item to display.
>
> Yeah, that's what I had in mind as well, I'll put it on my todo list.
>

​Great.​

> Unfortunately no, the selected-window still changes to something other
> than the treemacs browser window in both the cases I listed.
>
> Just to be clear: what exactly is the issue? The patch I pushed changed
> the hydra to stick around when you navigate in treemacs. That works on my
> end, except when I use tab. And it looks like there is nothing I can do
> about tab, since the hydra disappears even when tab is bound to ignore.
>
​If I press n or p once the help hydra is displayed, the help hydra
disappears and point is left in a window other than the treemacs listing
window.  So I am not seeing the hydra stay up.  If I press something like
C-n or C-p, keys not in the hydra, I still want point to stay in the
treemacs listing window.

​Maybe I'll look at what is going on.

Bob

**Comment by Alexander-Miller** [comment]
Let's try it without treemacs then. Whats's the staying behaviour of the following hydra?

```
(defhydra test-hydra (:exit nil :hint nil :columns 1)
  "
_n_: next line
_p_: previous line"
  ("n" #'next-line)
  ("p" #'previous-line)
  ("?" nil "Exit"))
```

**Comment by rswgnu** [comment]
That works fine.  As long as I press n or p, the hydra help stays up and it exits on ? or a non-hydra character.

**Comment by Alexander-Miller** [comment]
More tests it is then:
 * Does the helpful hydra always disappear, or are there keys when it stays?
 * What are n and p bound to in the treemacs window
 * Do you use evil-mode without treemacs-evil?
 * What does the output look like if you add the following advice and try to use the hydra?
``` 
(defun window-debug (&rest _)
  (treemacs--log "Selected Window %s" (selected-window)))
(advice-add 'select-window :after #'window-debug)
```

**Comment by rswgnu** [comment]
> More tests it is then:
> Does the helpful hydra always disappear, or are there keys when it stays?

Using the hydra that comes with treemacs.
Yes, it stays open after issuing any of the movement commands in the left column.

> What are n and p bound to in the treemacs window

treemacs-next/previous-line

> Do you use evil-mode without treemacs-evil?

No.

> What does the output look like if you add the following advice and try to use the hydra?

I had the treemacs window on the left and the *scratch* buffer in a window on the right.  I issued {n}, {M-p} and {?} one or two times in the treemacs window and got this long result:

[Treemacs] Selected Window #<window 3 on *scratch*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*> [6 times]
[Treemacs] Selected Window #<window 22 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 22 on  *LV*> [3 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 22 on  *LV*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 22 on  *LV*> [3 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*> [3 times]
[Treemacs] Selected Window #<window 22 on  *LV*>
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 3 on *scratch*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 3 on *scratch*> [2 times]
[Treemacs] Selected Window #<window 24 on *scratch*>
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 24 on  *LV*> [3 times]
[Treemacs] Selected Window #<window 3 on *scratch*>
[Treemacs] Selected Window #<window 24 on  *LV*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 24 on  *LV*> [3 times]
[Treemacs] Selected Window #<window 3 on *scratch*> [3 times]
[Treemacs] Selected Window #<window 24 on  *LV*>
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 3 on *scratch*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*> [6 times]
[Treemacs] Selected Window #<window 26 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 26 on  *LV*> [3 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 26 on  *LV*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 26 on  *LV*> [3 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*> [3 times]
[Treemacs] Selected Window #<window 26 on  *LV*>
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 3 on *scratch*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 3 on *scratch*> [2 times]
[Treemacs] Selected Window #<window 28 on *scratch*>
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 28 on  *LV*> [3 times]
[Treemacs] Selected Window #<window 3 on *scratch*>
[Treemacs] Selected Window #<window 28 on  *LV*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 28 on  *LV*> [3 times]
[Treemacs] Selected Window #<window 3 on *scratch*> [3 times]
[Treemacs] Selected Window #<window 28 on  *LV*>
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 3 on *scratch*> [2 times]
[Treemacs] Selected Window #<window 4 on  *Minibuf-1*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 3 on *scratch*> [2 times]
Quit
[Treemacs] Selected Window #<window 3 on *scratch*> [2 times]
[Treemacs] Selected Window #<window 4 on  *Minibuf-1*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 3 on *scratch*> [2 times]
[Treemacs] Selected Window #<window 4 on  *Minibuf-1*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 3 on *scratch*> [2 times]
Quit
[Treemacs] Selected Window #<window 3 on *scratch*> [3 times]
[Treemacs] Selected Window #<window 4 on  *Minibuf-1*> [2 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 3 on *scratch*> [3 times]
[Treemacs] Selected Window #<window 4 on  *Minibuf-1*> [4 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>
[Treemacs] Selected Window #<window 3 on *scratch*> [3 times]
[Treemacs] Selected Window #<window 6 on  *Treemacs-Framebuffer-1*>

**Comment by Alexander-Miller** [comment]
Nothing that looks out of the ordinary.

Let's try a very simple hydra for treemacs then:
```
(defhydra treemacs--test-hydra (:exit nil :hint nil :columns 1)
  "
_n_: next line
_p_: previous line"
  ("n" #'treemacs-next-line)
  ("p" #'treemacs-previous-line)
  ("?" nil "Exit"))
```
Does that work?

What does the following code output when called in a frame where a treemacs buffer exists?
```
(with-current-buffer (treemacs--buffer-exists?)
  (treemacs--find-keybind #'treemacs-next-line))
```

The output is supposed to look like `("_n_:    " . "n")`.

If none of these give any clues try installing evil-mode and treemacs-evil and testing the hydra with j/k. treemacs-evil needs to be explicitly required (:demand t in use-package) for it to work. If you see a cursor in treemacs it's not working.

**Comment by rswgnu** [comment]
> Let's try a very simple hydra for treemacs then:

No.  Pressing n or p immediately selects another window; the hydra help does stay displayed.

> What does the following code output when called in a frame where a treemacs buffer exists?

> (with-current-buffer (treemacs--buffer-exists?)
>   (treemacs--find-keybind #'treemacs-next-line))
> The output is supposed to look like ("_n_: " . "n").
("_n_:    " . "n")

> If none of these give any clues try installing evil-mode and treemacs-evil and testing the hydra with j/k. treemacs-evil needs to be explicitly required (:demand t in use-package) for it to work. If you see a cursor in treemacs it's not working.

I see a cursor and j and k select another window when the hydra help is displayed; they stay in the treemacs window if the hydra help is not displayed.

There must be a simpler way to simply trace a single command call to see where the window selection change is occurring.  I can use edebug if that would work.

**Comment by Alexander-Miller** [comment]
> I can use edebug if that would work.

Please do, though I don't think you'll be able to see very much. The code the defhydra macro expands to is all sorts of non-trivial. You can see for yourself with `cl-prettyexpand` and the simple test hydra from above.

There is another thing we've forgotten so far: we need to see if there is something in you config that's causing the issue. Start `emacs -q`, run `(setq package-user-dir "~/.emacs.d/elpa/")` and `package-initialize`, add the treemacs dir to the load-path if you're installing locally, and then see if the problem persists.

**Comment by rswgnu** [comment]
> There is another thing we've forgotten so far: we need to see if there is something in you config that's causing the issue. Start emacs -q, run (setq package-user-dir "~/.emacs.d/elpa/") and package-initialize, add the treemacs dir to the load-path if you're installing locally, and then see if the problem persists.

That does solve the problem, so it is something in my init.  So far I have tried testing all the window-related packages I could find that I use and none of them triggers the problem, so I'll have to search further.  It is strange that I have never seen another package trigger this problem before treemacs.

Thanks for your help with this.

**Comment by Alexander-Miller** [comment]
Any news, especially with the newest treemacs vesion?

**Comment by Alexander-Miller** [comment]
Bump?

**Comment by Alexander-Miller** [comment]
Closing on account of inactivity. Feel free to reopen if the issue persists with the latest treemacs.
