### ISSUE TITLE
Error "Can’t find define-package" when updating treemacs

### ISSUE THREAD

**Issue by thermopyle** [Alexander-Miller/treemacs#1036]
I'm trying to update my Emacs (using paradox-list-packages). I get an error message saying `Can’t find define-package` in the elpa/treemacs directory. Deleting treemacs entirely and reinstallaling does not work either.

**Comment by Alexander-Miller** [comment]
No such thing in treemacs:

![dp](https://github.com/Alexander-Miller/treemacs/assets/5951157/1bbca5b0-9e5f-43d8-8fbd-cfb56b1fe1d7)

So it must be something else. Run `toggle-debug-on-error`. If the error happens at startup start Emacs with `--debug-init`. What does the full stack trace look like?

**Comment by thermopyle** [comment]
I did a complete reinstall, deleted my .emacs.d and downloaded all packages again, the error did not appear again. My config must have been corrupt in some way, I don't know how. Sorry for the false alarm, you can close this.

**Comment by Alexander-Miller** [comment]
:man_shrugging:
