### ISSUE TITLE
[feature request] Add {v} key to a view an item

### ISSUE THREAD

**Issue by rswgnu** [Alexander-Miller/treemacs#104]
{v} in most modes let's you view an item in a read-only form where SPC and DEL page forward and backward through the buffer; with treemacs, the selected window should stay as the treemacs listing window.  I think this would be a good addition.

**Comment by Alexander-Miller** [comment]
I am not going to implement a full featured view mode - doing it right and doing it well would be a lot of work, but the payoff very small. It's almost the same as RET to open a file, scroll as you please, kill it or get back to treemacs with `treemacs-select-window` or winum. I don't see how a dedicated view mode would improve this workflow.

Only the switching between treemacs and the code window is in the way. Here I propose the following: new functions bound to e.g. C-n/C-p & C-j/C-k that scroll `other-window`, with a configurable scroll step.

This way you can scroll a file that you've opened while staying in treemacs with C-u RET. It'd be 90% of a view mode for only 10% of the work.

**Comment by rswgnu** [comment]
I am asking for something simpler, equivalent to the command to edit a file.  There would be a view action bound to {v} that would display a file or tag with view-file and select the file's window, allowing the user to scroll through it with {SPC} and {DEL} and then a {q} would return to the Treemacs buffer.  So everything would work just like an edit command except using view commands and no need to change many things inside Treemacs.  Is that something you would implement?

**Comment by Alexander-Miller** [comment]
All right, that appproach sounds much less fragile than I initially expected. Results should be about the same as my own proposal. I'll experiment and see what's more robust and a better fit.

I see one open end either way: what decides where the view window is? Just using `other-window` is easiest, but I could expand the ace.window api here as well. Just need a good idea as to when that selection should invalidated and reset.

**Comment by rswgnu** [comment]
On Wed, Nov 22, 2017 at 3:51 PM, Alexander-Miller <notifications@github.com>
wrote:

> All right, that appproach sounds much less fragile than I initially
> expected. Results should be about the same as my own proposal. I'll
> experiment and see what's more robust and a better fit.
>
> I see one open end either way: what decides where the view window is?
>
​Just do whatever you do to display an item for viewing when RET is pressed
on an editable item.​  All you are doing is changing the mode used when the
item is displayed.
​​

> Just using other-window is easiest, but I could expand the ace.window api
> here as well.
>
​Yes, ace-window is great.  I just looked at the Treemacs interface to it.
It is good but quite a few keys to type, maybe 5 in total to do one command.
I have interfaced Hyperbole to ace-window by adding a command to
aw-dispatch-alist for a total of 3 keys.  So now if the ace-window command
is globally
bound to {M-o} and the Hyperbole item drag command is set to {i} and you
want to display the current Treemacs tag in window 'a', you can just press
{M-o i a}.
Works quite well and is in the next release of Hyperbole.

> Ju
> ​​
> st need a good idea as to when that selection should invalidated and res
> ​​
> et.
>
> ​I have no input on that.
​

**Comment by Alexander-Miller** [comment]
> It is good but quite a few keys to type, maybe 5 in total to do one command.

It's 3, same as yours, unless you count something else as part of the command. The keys are oaa, oav & oah respectively. I've many ways to open a file and this was the best way to get them all under one roof that I could think of.
If you've other preferences you can set a default for RET for all the node types with `treemacs-default-actions`.

**Comment by rswgnu** [comment]
On Wed, Nov 22, 2017 at 4:14 PM, Alexander-Miller <notifications@github.com>
wrote:

> It is good but quite a few keys to type, maybe 5 in total to do one
> command.
>
> It's 3, same as yours, unless you count something else as part of the
> command. The keys are oaa, oav & oah respectively. I've many ways to open a
> file and this was the best way to get them all under one roof that I could
> think of.
>
​I guess it is just one more (because I include the letter of the window
chosen).  But I like the way you included different commands for where to
display the item and I
think the bindings are fine.

I think of this as 'throwing' an item to a window for display (rather than
the traditional drag and drop).  Hyperbole has a generalized technique that
allows both throws and drags in Treemacs, Dired and Buffer Menu using the
same mouse/key bindings regardless of mode.  I think this is a powerful
concept that people will enjoy.

> If you've other preferences you can set a default for RET for all the node
> types with treemacs-default-actions.
>
​Nice​
.
​
​
​

**Comment by Alexander-Miller** [comment]
Pushed this to master now. I went for a simple implementation here - no modes, just M-N & M-P to scroll ~next-window~. Take a look and let me know if anything is missing.

**Comment by Alexander-Miller** [comment]
Closing this issue since I consider the request done.

Feel free to reopen if you think something's missing.
