### ISSUE TITLE
vscode SVGs not parsing, but emacs SVGs do

### ISSUE THREAD

**Issue by dmvianna** [Alexander-Miller/treemacs#1041]
I'm noticing a really weird issue where I can see `splash.svg` fine, which is part of emacs, but cannot see any of the SVG files in `icons/default/vsc`.
 
My config:

GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) of 2023-07-27
Tested with the below config (nothing else):

```elisp
;; Packages
(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)

;; Treemacs
(use-package treemacs
  :init (treemacs))
```

I'm on Fedora 38, Gnome 44.3, Wayland

**Comment by Alexander-Miller** [comment]
There's been a lot of movement on the icon front recenty, and many things were changed and fixed. Can you try again with the latest treemacs?

**Comment by dmvianna** [comment]
Yeah, I can see all the icons now, thanks!
