### ISSUE TITLE
Treemacs + Doom Modeline on emacs 29.1

### ISSUE THREAD

**Issue by gmemstr** [Alexander-Miller/treemacs#1047]
After updating past commit aa0944a29eee48302fd76b6c3a59c5aece114fa6, I encountered the same error describe here: https://github.com/Alexander-Miller/treemacs/issues/1046. Interestingly, despite [a patch being pushed][1] and confirming I am using the latest commit, I still encounter the error. Rolling back to before the doom modeline patches resolves the issue.

I am using https://github.com/hlissner/emacs-hide-mode-line, which is maybe the only "special" bit of my setup in regards to the modeline, with the relevant `init.el` config:

```elisp
(use-package hide-mode-line :straight t)

(add-hook 'treemacs-mode-hook #'hide-mode-line-mode)
(use-package treemacs
  :straight t
  :init (with-eval-after-load 'winum
		  (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
  :bind
  (:map global-map
		("M-0" . treemacs-select-window)
		("C-x t t" . treemacs)
		("C-x t C-t" . treemacs-find-file)))
(use-package treemacs-projectile
  :straight t
  :after (treemacs projectile))
(use-package treemacs-magit
  :straight t
  :after (treemacs magit)
  :ensure t)
(use-package treemacs-icons-dired
  :straight t
  :hook (dired-mode . treemacs-icons-dired-enable-once)
  :ensure t)
```

However removing the hook doesn't have any impact.

I do plan to dig into this more after work but wanted to file an issue so I don't forget.

[1]: https://github.com/Alexander-Miller/treemacs/pull/1044

**Comment by gmemstr** [comment]
@sebastiaanspeck I do indeed have a workspace set 

![image](https://github.com/Alexander-Miller/treemacs/assets/1878840/8d80315a-a1fa-4429-83a9-0f97ddd5b1cb)

**Comment by gmemstr** [comment]
(To aide in replication if needed my entire init.el is here: https://git.gmem.ca/arch/dotfiles/src/branch/master/.emacs.d/init.el)

**Comment by sebastiaanspeck** [comment]
Maybe a backtrace could help to investigate this further? Other people reported that Treemacs is fixed with the latest patch

**Comment by gmemstr** [comment]
```
Debugger entered--Lisp error: (void-variable treemacs)
  treemacs--setup-mode-line()
  #<subr treemacs-mode>()
  treemacs--mode-check-advice(#<subr treemacs-mode>)
  apply(treemacs--mode-check-advice #<subr treemacs-mode> nil)
  treemacs-mode()
  treemacs--init()
  treemacs(nil)
  funcall-interactively(treemacs nil)
  command-execute(treemacs)
```

I'm not sure if I can get more granular than that unfortunately.

**Comment by sebastiaanspeck** [comment]
<img width="831" alt="Treemacs" src="https://github.com/Alexander-Miller/treemacs/assets/12570668/6735ab2d-5d46-4968-bdbc-f27540971f43">

This is the issue... maybe need some help from the author of doom-modeline how to fix this?

**Comment by sebastiaanspeck** [comment]
<img width="748" alt="image" src="https://github.com/Alexander-Miller/treemacs/assets/12570668/185e4140-413a-40d3-800e-a520ae000900">
This is a way without errors/warnings. Not sure if this is the nicest way..

**Comment by shakor0** [comment]
Yeah my treemacs broke when adding:
`(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 15)))
`

**Comment by Dawnblaze** [comment]
I had the same problem, but i run treemacs first, and then run doom-modeline, then this problem was solved.

**Comment by jtl5770** [comment]
> I had the same problem, but i run treemacs first, and then run doom-modeline, then this problem was solved.

I actually have no idea how to do that with using use-package in my init.el. I tried switching the order of the respective calls around, but to no big surprise, it didn't change anything

**Comment by sebastiaanspeck** [comment]
"Fix" is merged (reverted the breaking change). Please test the latest version

**Comment by sebastiaanspeck** [comment]
![IMG_1083](https://github.com/Alexander-Miller/treemacs/assets/12570668/bf86ea45-d397-46ff-882b-bc8abdf9113e)

right now, the rhs shows *invalid*. That’s because the rhs is an empty list. This looks like the perfect place to show the current workspace name. Please take a look at https://github.com/Alexander-Miller/treemacs/pull/1049 to see if this works for you!
