### ISSUE TITLE
treemacs-create-icon - use regexp for :extensions

### ISSUE THREAD

**Issue by sebastiaanspeck** [Alexander-Miller/treemacs#1051]
```
(treemacs-create-icon :icon (format "  %s%s" (nerd-icons-sucicon "nf-seti-docker" :face 'nerd-icons-cyan) treemacs-nerd-icons-tab)
		      :extensions ("^Dockerfile.*$")
		      :fallback 'same-as-icon)
```

Would be great if the above would work. I do have some Dockerfiles that are called:
- Dockerfile-backend
- Dockerfile-frontend

I could add `(add-to-list 'nerd-icons-regexp-icon-alist '("^Dockerfile.*$" nerd-icons-sucicon "nf-seti-docker" :face nerd-icons-cyan))` to the regexp for nerd-icons, but the regexp-icon-alist can't be used for treemacs-create-icon.

Besides this issue, is the function `treemacs-get-icon-value` case-sensitive?
`(treemacs-get-icon-value "dockerfile" nil "nerd-icons")` --> results in a icon
`(treemacs-get-icon-value "Dockerfile" nil "nerd-icons")` --> nil

It does display the icon for dockerfile when having a Dockerfile in treemacs, so thats no issue.

**Comment by Alexander-Miller** [comment]
For performance reasons treemacs uses hash tables for its icon matching, so regexes are are no-go. You can at most change what treemacs considers a file's extension, that part is handled via regex. Look at `treemacs-file-extension-regex`. The default choices are about matching things after the first or last period, but maybe you can change it to something that suits you.

> Besides this issue, is the function treemacs-get-icon-value case-sensitive?

Yes. Internally treemacs will downcase everything, so you should do the same.

**Comment by Alexander-Miller** [comment]
Get the latest version of treemacs and you'll be able to create an override to check for the dockerfile prefix like this:

```Elisp
(advice-add
 #'treemacs--file-extension
 :around
 (defun treemacs-override (original-fn filename)
   (if (string-prefix-p "dockerfile" (downcase filename))
       "dockerfile"
     (funcall original-fn filename))))
```

Then make sure to create an icon for a lowercase "dockerfile" extension and you should be good to go.
