### ISSUE TITLE
MacOS: Inconsistent Icon Sizes

### ISSUE THREAD

**Issue by zeim839** [Alexander-Miller/treemacs#1053]
System: GNU Emacs 28.2 (build 1, x86_64-apple-darwin22.5.0, NS appkit-2299.60 Version 13.4 (Build 22F66)) of 2023-07-25

Icon sizes/dimensions are inconsistent, probably because of image dimension differences across icons (i.e some are larger/smaller than others). This causes certain icons to appear over-sized. Haven't tested this on Linux but I'm assuming this is a MacOS-specific issue because I was unable to replicate it on my Windows environment. 

`treemacs--icon-size` and `treemacs-resize-icons` only seem to affect png files. The screenshots below are with the extra-wide option turned on. 

![Screenshot 2023-08-17 at 15 41 32](https://github.com/Alexander-Miller/treemacs/assets/50573884/aa4a4350-0bc2-4a09-94d3-f3f751374a24)

![Screenshot 2023-08-17 at 15 41 44](https://github.com/Alexander-Miller/treemacs/assets/50573884/7733b021-6084-4cc8-942d-1ded614f0d21)

**Comment by Velnbur** [comment]
Is there any fix to, at least, fix this locally?

**Comment by Alexander-Miller** [comment]
This might be down to new svg icons I had introduced. They've now been removed due to trouble elsewhere. Does this problem still happen?

**Comment by zeim839** [comment]
> Does this problem still happen?

Nope, seems to be working now. Thank you!
