### ISSUE TITLE
:after-collapse and :after-expand in treelib

### ISSUE THREAD

**Issue by kurnevsky** [Alexander-Miller/treemacs#1054]
I'm trying to migrate `lsp-metals` from `treemacs-extensions` to `treemacs-treelib`. In order to do that I need `:after-expand` and `:after-collapse` properties - lsp server needs to know when nodes are expanded/collapsed. It seems there is no such thing in `treelib`, or is there a workaround?

**Comment by Alexander-Miller** [comment]
Not possible yet. I'll start working on it now.

**Comment by Alexander-Miller** [comment]
Pushed a first version. Let me now if it works for you.

**Comment by kurnevsky** [comment]
It works fine, thanks. One unrelated thing I wanted to ask - why does treemacs sets background explicitly for icons? It seems it can just specify `:mask 'heuristic` to be transparent, see https://www.gnu.org/software/emacs/manual/html_node/elisp/Image-Descriptors.html

**Comment by Alexander-Miller** [comment]
Maybe the feature wasn't around when I was looking for it back then, or maybe my google-fu is bad. Either way handling the background via this property saves me a few hundred lines of code, so thanks for the tip!
