### ISSUE TITLE
treemacs--post-command: wrong-type-argument number-or-marker-p nil

### ISSUE THREAD

**Issue by ahopkins** [Alexander-Miller/treemacs#1056]
![image](https://github.com/Alexander-Miller/treemacs/assets/166269/19e3156c-babc-45e4-8dd6-3b8c28bb346e)

I am getting a similar error as seen here: https://github.com/Alexander-Miller/treemacs/issues/948

```
Symbol’s value as variable is void: treemacs-workspace-name
Error in post-command-hook (treemacs--post-command): (wrong-type-argument number-or-marker-p nil)
```

I am getting this with a basic setup:

```lisp
(use-package treemacs
  :ensure t
  :defer t
  )
```

**Comment by ahopkins** [comment]
I see #1047 now. Seems like it is still an issue. I also narrowed the issue to doom-modeline

**Comment by sethen** [comment]
Same issue for me

**Comment by Alexander-Miller** [comment]
There has been a bit of a back and forth on the latest doom modeline change. Can you confirm that you still see the problem with the latest treemacs?

If yes, provide a stack trace via `toggle-debug-on-error`.

**Comment by Alexander-Miller** [comment]
I just uploaded a new version where the whole doom modeline part is no longer compiled. That should fix your problem.

**Comment by ahopkins** [comment]
I can confirm that reinstalling seems to be working for me :sunglasses: 

Thanks @Alexander-Miller for the work on this.
