### ISSUE TITLE
Directories created in shell corrupt treemacs display

### ISSUE THREAD

**Issue by jtl5770** [Alexander-Miller/treemacs#1057]
Hi,

when I create a new directory for my project in the shell, treemacs realizes that there is a new folder (good) but unfortunately corrupts the display - see image for the "AAA" folder (bad)

![image](https://github.com/Alexander-Miller/treemacs/assets/24967370/d9dca559-145e-433f-87f3-03b96ac565b4)

removing the folder again in the shell gives an error in treemacs-process-file-events: (Wrong type argument interger-or-marker-p nil)

creating and deleting from treemacs ("c d" & "d") works flawlessly, as does removing a folder in the shell. Only creating in the shell seems to corrupt the data structure. The only way to recover is killing the treemacs buffer.

**Comment by Alexander-Miller** [comment]
Looking into it.

**Comment by Alexander-Miller** [comment]
Problem was  a leftover from when treemacs learned about directory-specific icons. Should be fixed now.

>The only way to recover is killing the treemacs buffer.

Most of the time it should be possible to fix these kinds of issues via `treemacs-refresh` (not that I encourage that instead or reporting bugs, but it's easier in the meantime).

**Comment by jtl5770** [comment]
Now it seems that it works for creating, but if I then delete the dir again, treemacs reacts with

Error running timer ‘treemacs--process-file-events’: (wrong-type-argument integer-or-marker-p nil)

**Comment by Alexander-Miller** [comment]
> Error running timer ‘treemacs--process-file-events’: (wrong-type-argument integer-or-marker-p nil)

Confirmed. Going back to digging. 

> Ah yes, and by the way: treemacs-refresh didn't work in this case (it said "nothing to refresh")

That message only happens when your cursor is on a line between projects. Definitely a symptom of a deeper issue.

**Comment by Alexander-Miller** [comment]
This time it was some code that acted different when compiled.
Try again now.

**Comment by jtl5770** [comment]
Seems to work now. 

Thanks
