### ISSUE TITLE
Some directory icons not rendering properly

### ISSUE THREAD

**Issue by Pacane** [Alexander-Miller/treemacs#1058]
Hi, I'm using doom emacs, I've tried unpinning (therefore using latest versions of)

```
treemacs
treemacs-all-the-icons
all-the-icons
```

and I've getting this behaviour:

![image](https://github.com/Alexander-Miller/treemacs/assets/2762440/95fa0318-9890-4a26-8ca9-897d0568da9c)

If you look at the `bin/` `docs/` and `.github/` directories, the icons are not rendering properly.

Is there a specific package I should install?

Note: I've looked at [this issue](https://github.com/Alexander-Miller/treemacs/issues/1018), and I figured it could be useful to mention,

I'm using emacs 29 on MacOS M1. Using emacsplus from brew.

I don't know if it's the same issue, because my icons don't render at all, but in the referenced issue, there's a white background. Feel free to mark this as dupe if it's the same issue.

**Comment by kidpollo** [comment]
Interesting Its like the icons that got fixed for the default theme now are MIA for other themes

**Comment by Alexander-Miller** [comment]
I haven't had much luck with introducing svg icons, and have recently converted them back to pngs. Can you try again with the latest version of treemacs?

**Comment by Alexander-Miller** [comment]
Also what other themes - official all-the-icons or something else?

**Comment by Pacane** [comment]
I've upgraded (unpinned treemacs in doom + doom upgrade) and I've got the same thing.

**Comment by Alexander-Miller** [comment]
The icons missing are those that treemacs now supports custom icons for. I checked both the default and treemacs' own all-the-icons themes, and didn't have this problem. It's very likely that there is something wrong with the theme you are using.

**Comment by m-delfino** [comment]
Indeed this seems to be a problem with the theme defined in the **treemacs-nerd-icons** package, as outlined and addressed in this pull request: https://github.com/rainstormstudio/treemacs-nerd-icons/pull/6

**Comment by djelic** [comment]
Hi all, I have very similar if not same issue, however, icons are rendered properly until I open file that uses lsp-mode. As you can see in video, opening files without lsp-mode does not affect the icons, but once I open .js file and refresh treemacs, certain icons are gone.
![output](https://github.com/Alexander-Miller/treemacs/assets/33350/178a8b61-ad54-4ffa-9e10-165b75329fff)

**Comment by Alexander-Miller** [comment]
lsp is its own package, and I don't know exactly which customizations it applies to treemacs. If the problem happens with lsp then that's where you should raise your issue.

**Comment by djelic** [comment]
> lsp is its own package, and I don't know exactly which customizations it applies to treemacs. If the problem happens with lsp then that's where you should raise your issue.

@Alexander-Miller thanks! Found the issue on [emacs-lsp/lsp-treemacs](https://github.com/emacs-lsp/lsp-treemacs/issues/89).

**Comment by tmonck** [comment]
I'm pretty sure doomemacs switched to nerd-icons instead. I am facing the same issue but it's related to nerd-icons and not all-the-icons.

**Comment by rytswd** [comment]
I'm not using Doom Emacs but was hit by the exact behaviour around LSP mode and `lsp-treemacs` @djelic highlighted above. It turned out that, for my setup, I just needed to ensure that package load orders are in place for `lsp-treemacs` explicitly:

```elisp
(use-package lsp-treemacs :after treemacs)
```

I didn't even have the use-package setup because I had it pulled in as a dependency from `dap-mode`. I had a trouble with both all-the-icons and nerd-icons, but the above dependency setup seemed to have helped for both cases. Not sure if it is the same for other folks, but just sharing in case it may be helpful for some.

**Comment by kriku** [comment]
> Hi all, I have very similar if not same issue, however, icons are rendered properly until I open file that uses lsp-mode. As you can see in video, opening files without lsp-mode does not affect the icons, but once I open .js file and refresh treemacs, certain icons are gone. 

(actually it's looks like alignment is broken also)

I have exact same issue, but I have all-the-icons installed, and it seems that some icons loaded from other icon set.. I'm not sure which one is which, but it's clearly messed up.
![Screenshot 2023-11-14 at 07 56 56](https://github.com/Alexander-Miller/treemacs/assets/6429161/a512ab0d-32b6-47ea-85f8-695fcaad5a65)

But if I load theme Idea for treemacs - all alignments looks right, and `src`, `docs` icons (also `test`, `.github`, etc) - looks like from this set
![Screenshot 2023-11-14 at 07 58 56](https://github.com/Alexander-Miller/treemacs/assets/6429161/b2c9952e-be2d-46ad-9b2a-e84930392003)

**Comment by Alexander-Miller** [comment]
> I have exact same issue, but I have all-the-icons installed, and it seems that some icons loaded from other icon set.. I'm not sure which one is which, but it's clearly messed up.

I guess that the all-the-icons theme you use is built to extend the default theme, so if the default theme adds new icons they are shown because the all-the-icons theme does not override them. Which implementation of all-the-icons do you use, treemacs' own or something else? If it's the former I can fix it, if it's the latter then it's up to the theme's maintainer.

**Comment by kriku** [comment]
> > I have exact same issue, but I have all-the-icons installed, and it seems that some icons loaded from other icon set.. I'm not sure which one is which, but it's clearly messed up.
> 
> I guess that the all-the-icons theme you use is built to extend the default theme, so if the default theme adds new icons they are shown because the all-the-icons theme does not override them. Which implementation of all-the-icons do you use, treemacs' own or something else? If it's the former I can fix it, if it's the latter then it's up to the theme's maintainer.

I think I was wrong about all-the-icons.

At some point, I've noticed `[Treemacs] Cannot find theme 'nerd-icons'.` message.

I tried install related packages, and disable all-the-icons:
```emacs-lisp
;; packages.el
(package! treemacs-nerd-icons)
(package! nerd-icons)
(package! all-the-icons :disable t)
```
But still have this message, after `doom sync`.
After manual `package-install` - it goes away and in `treemacs-load-theme` - appears `nerd-icons` theme. 
But after `doom sync` it again goes away and message still appearing.

Then I found this issue https://github.com/Alexander-Miller/treemacs/issues/1018.

And in particular this solution https://github.com/Alexander-Miller/treemacs/issues/1018#issuecomment-1599599392.

After I put part
```emacs-lisp
(use-package treemacs
;; ...
  (use-package treemacs-nerd-icons
  ;; ...
```
Message `Cannot find theme 'nerd-icons'` - not appears any more and icons renders correctly.

I don't know why it doesn't work from the box.

**Comment by kriku** [comment]
> > I have exact same issue, but I have all-the-icons installed, and it seems that some icons loaded from other icon set.. I'm not sure which one is which, but it's clearly messed up.
> 
> I guess that the all-the-icons theme you use is built to extend the default theme, so if the default theme adds new icons they are shown because the all-the-icons theme does not override them. Which implementation of all-the-icons do you use, treemacs' own or something else? If it's the former I can fix it, if it's the latter then it's up to the theme's maintainer.

I use box version of doomemacs, I mean I only uncomments modules at `.doom.d/init.el` - I don't know which implementation or theme is loaded by doom configuration. But I almost every week use `doom upgrade` to get newest updates.

I even tried to reinstall doom by removing configuration and initialising again. But still probably have some differences:

<img width="317" alt="image" src="https://github.com/Alexander-Miller/treemacs/assets/6429161/32d85859-6215-433e-a3dd-3a3aa4319892">

vs screenshot from doomemacs home page: 

<img width="192" alt="image" src="https://github.com/Alexander-Miller/treemacs/assets/6429161/72bb800e-0d98-4bba-a014-d9369f52745e">

**Comment by Alexander-Miller** [comment]
> I even tried to reinstall doom by removing configuration and initialising again. But still probably have some differences:

This is the reason why I have never liked using iconic fonts, and opted for png icons way back when - because they do *this*.

Maybe `treemacs-load-all-the-icons-with-workaround-font` can help you. Otherwise, if your problem is with the icon selection of the doom theme you should try raising the issue there.

**Comment by Alexander-Miller** [comment]
It looks like the discussion here has run its course, so I'll close on account of inactivity. Feel free to re-open if this issue is still relevant.
