### ISSUE TITLE
[feature request] Pass more information to functions in treemacs-ignored-file-predicates

### ISSUE THREAD

**Issue by mkcms** [Alexander-Miller/treemacs#106]
I'd like to ignore files that are in my .gitignore, so I add a filter to `treemacs-ignored-file-predicates`.
Unfortunately the filters are not given a lot of information about git status or even the file's full path so I have to use ugly hacks:
```
(use-package treemacs-projectile
    :config
    (defvar my--treemacs-project-files nil)
    (defvar my--treemacs-root nil)
    (defun my--split-path (path)
      (let ((tmp "") result)
	(dolist (comp (f-split path))
	  (setq tmp (f-join tmp comp))
	  (push tmp result))
	result))
    (defun my--treemacs-create-branch (root &rest args)
      (setq my--treemacs-root root)
      (let ((default-directory root)
	    (buffer-file-name nil)
	    (projectile-cached-project-root nil))
	(setq my--treemacs-project-files
	      (and (projectile-project-p)
		   (let ((hash (make-hash-table :test 'equal))
			 (paths (projectile-expand-paths
				 (append (projectile-current-project-files)
					 (-flatten
					  (mapcar 'my--split-path
						  (projectile-current-project-dirs)))))))
		     (--each paths (puthash (f-canonical it) t hash))
		     hash)))))
    (defun my--treemacs-gitignored-file-filter (f)
      (let ((default-directory my--treemacs-root))
	(when my--treemacs-project-files
	  (let ((abs (f-canonical (f-expand f my--treemacs-root))))
	    (not (gethash abs my--treemacs-project-files))))))
    (advice-add #'treemacs--create-branch :before
		#'my--treemacs-create-branch)
    (add-to-list 'treemacs-ignored-file-predicates
		 #'my--treemacs-gitignored-file-filter))
```
I propose that the filters in `treemacs-ignored-file-predicates` should be passed additional arguments or that a global variable should be bound when the filters are called. The arguments/variable should hold additional information about the file, like it's full path and optionally git status information that is calculated before.

**Comment by Alexander-Miller** [comment]
I can change the API to instead give you the files' full paths, or whatever other info you find useful, but adding git info is a bit more complicated. The git status process is run asynchronously, its results are fetched and parsed as late as possible (after the directories have already been inserted), while the ignored predicates do the filtering right at the start.

What I can do is offer a second filter pass where you can inject your own predicate, that takes a file's full path and the current git-info. As of now the git-info is an alist of git-state -> file path tuples. Look up `treemacs--get-face` to see how it's used. It's essentially the parsed output of `git status --porcelain --ignored .`.

I've a patch in the making that'll change the alist to a hash table, so the code will look like this:
```
(-pcase (gethash path git-info)
    [?M 'treemacs-git-modified-face]
    [?U 'treemacs-git-conflict-face]
    [?? 'treemacs-git-untracked-face]
    [?! 'treemacs-git-ignored-face]
    [?A 'treemacs-git-added-face]
    [_  'treemacs-git-unmodified-face])
```

It'll be released eventually, unless I do find a way to make parsing with an asynchronous script faster than synchronous elisp.

**Comment by mkcms** [comment]
Providing full file paths and a refresh hook as well (so that a user can start his own git process or lookup projectile files just once) would suffice for now I suppose. The root of treemacs tree should be known and provided when the hook fires. Although there would still be redundant computation since treemacs runs the git process in parallel.

The second pass idea seems like it's the best, would it be just deleting nodes after they're inserted if they don't satisfy a predicate?

**Comment by Alexander-Miller** [comment]
Refresh hooks are up, with all the info there is, and passing full path is next.

> would it be just deleting nodes after they're inserted if they don't satisfy a predicate?

Way too inefficient. It'd be another filter before insertion starts.

**Comment by Alexander-Miller** [comment]
Just pushed the ignore function api change. The predicate functions now take 2 arguments: just a file's name and its absolute path. I went with the 2 args solution so a filename needn't be computed more than once.

Just the second filter pass left.

**Comment by mkcms** [comment]
Awesome, thanks

**Comment by Alexander-Miller** [comment]
Got a second filter pass going. See `treemacs-pre-file-insert-predicates`.

**Comment by mkcms** [comment]
It works how I want, except for directories.

I modified the code in `treemacs-create-branch` to this:
```
diff --git a/treemacs-branch-creation.el b/treemacs-branch-creation.el
index a187edb..2a39d86 100644
--- a/treemacs-branch-creation.el
+++ b/treemacs-branch-creation.el
@@ -202,17 +202,18 @@ to PARENT."
            (dirs (cl-first dirs-and-files))
            (files (cl-second dirs-and-files))
            (git-info))
+      (setq git-info (treemacs--parse-git-status git-process))
+      (when treemacs-pre-file-insert-predicates
+        (let ((test
+	       (lambda (path) (--any? (funcall it path git-info) treemacs-pre-file-insert-predicates))))
+	  (setq files (-reject test files))
+	  (setq dirs (-reject test dirs))))
       (treemacs--create-buttons
        :nodes dirs
        :extra-vars ((dir-prefix (concat prefix (with-no-warnings treemacs-icon-closed))))
        :depth depth
        :node-name node
        :node-action (treemacs--insert-dir-node node dir-prefix parent depth))
-      (setq git-info (treemacs--parse-git-status git-process))
-      (when treemacs-pre-file-insert-predicates
-        (setq files (-reject
-                     (lambda (file) (--any? (funcall it file git-info) treemacs-pre-file-insert-predicates))
-                     files)))
       (treemacs--create-buttons
        :nodes files
        :depth depth
```

This makes it work how I want. Is there a reason why the git process output is parsed before inserting files and not directories?

**Comment by Alexander-Miller** [comment]
It's just a simple micro optimization - the later it's done the more likely it is that the git process is finished and treemacs needn't do any blocking waiting.

I might as well look into finally extending git status highlighting to directories.

One big issue with directories is that naturally you'd also want to see highlight directories whose contents have been changed. AFAIK there's no way to ask git for just that, at least in a way that easily maps to a key-value structure as `git status --porcelain .` does for files.
I'm all ears for ideas, as I'd prefer not to introduce additional expensive parsing steps.

**Comment by mkcms** [comment]
Closing this issue, feature was added. Thanks.
