### ISSUE TITLE
Icons suddenly have black background

### ISSUE THREAD

**Issue by jtatarik** [Alexander-Miller/treemacs#1067]
Hi,

upgraded to latest `treemacs` version today and all of a sudden all  treemacs icons show with black background despite the frame having white background. Could it be related to f4795c7 ?

![image](https://github.com/Alexander-Miller/treemacs/assets/1110142/03d11f26-f20c-4139-94d7-9e64cfb7a8e6)

**Comment by kurnevsky** [comment]
What is your emacs version?

**Comment by kurnevsky** [comment]
Just tested with `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)` - works fine for me.

**Comment by jtatarik** [comment]
Deleted treemacs, installed again and the issue is gone.
