### ISSUE TITLE
[Feature] Allow disabling Emacs fringe for `treemacs` window

### ISSUE THREAD

**Issue by david-alvarez-rosa** [Alexander-Miller/treemacs#1071]
Truncation, and continuation indicators shown in the fringe do not look nice IMO for `treemacs` window. 

Would be great if the fringe could be customized just for the tree window!

**Comment by Alexander-Miller** [comment]
No need for treemacs do get involved, you can already do that in plain Emacs. The variable controlling fringe indicators is `fringe-indicator-alist`, you can change it around as you please. If you want a different look there's packages like [this one](https://github.com/SpecialBomb/emacs-modern-fringes/tree/master).
