### ISSUE TITLE
Is there a way to open treemacs and not focus it?

### ISSUE THREAD

**Issue by paulrouget** [Alexander-Miller/treemacs#1072]
I'd like to toggle it, but without focusing frame.

**Comment by Alexander-Miller** [comment]
Not doable with pure treemacs, but you can trivially create your own command by summoning treemacs wrapped in `save-selected-window`.

**Comment by Alexander-Miller** [comment]
I'll close this ticket because I assume your question has been answered. Feel free to re-open if this is not the case.
