### ISSUE TITLE
List functions without signatures

### ISSUE THREAD

**Issue by spacekookie** [Alexander-Miller/treemacs#1085]
Hey there,

sorry if this is already implemented or was discussed elsewhere; I had a search around the docs and issue tracker and didn't find anything.

I love being able to get a list of functions and types in a particular type. Unfortunately the list is kinda noisy because after every function name it also includes the function signature.

It would be nice to make this output configurable, or at least just hide the function signature. Is this something treemacs can do? Or does it depend on the output of a language server and so I'd have to configure this elsewhere?

Thanks!

**Comment by Alexander-Miller** [comment]
> Or does it depend on the output of a language server and so I'd have to configure this elsewhere?

Correct. Treemacs is just the frontend with a small bit of pre-processing to shove tags into a tree structure. The source of its data is `imenu`, which by itself is a generic feature that can provide info from various sources, from language servers and ctags down to the default of dumb regex scanning. If you want to change the look of your tags you'll have to take it up with your imenu implementation.

Btw, by default imenu must be manually told to re-scan your buffer. `imenu-auto-rescan` controls that behavior.
