### ISSUE TITLE
Customizing actions

### ISSUE THREAD

**Issue by AndreasMatthias** [Alexander-Miller/treemacs#1086]
How do i customize the action for opening certain file types?

Suppose that beside opening an HTML file for editing I'd also want to open this file with `eaf-open` (from Emacs Application Framework).

**Comment by Alexander-Miller** [comment]
Not possible without some legwork. You can either use `treemacs-after-visit-functions` that I have recently added. If that's not a good fit write your own simple ret-action that does something like 
```
(-let [btn (treemacs-current-button)]
  (treemacs-visit-node-no-split)
  (eaf-open (treemacs-button-get btn :path)))
```

**Comment by Alexander-Miller** [comment]
I'll close here on account of inactivity. Feel free to re-open if this issue is still relevant.
