### ISSUE TITLE
Question: Keep icon properties for opened collapsed directories 

### ISSUE THREAD

**Issue by luiznux** [Alexander-Miller/treemacs#1092]
Hi! First of all thanks for the amazing package!

Recently I'm trying to create a new theme for treemacs and I noticed that even
with the default theme, when collapsed directories are opened the color/icon
loses its properties :

**Closed**
![image](https://github.com/Alexander-Miller/treemacs/assets/48339190/a7b7c372-1e36-4069-a2dc-1b03e0f5a287)

**Opened**
![image](https://github.com/Alexander-Miller/treemacs/assets/48339190/edfe63bd-c747-4d58-9b89-34b9067dd37e)

I know if set `treemacs-collapse-dirs` with different values, the problem will be
solved, but my idea is to keep the folder color/icon even when its directories
are collapsed.

Is there a way to keep its color/icon even when collapsed?

Like passing a regex on extension definition but **only for folders**, example:

```elisp 
(treemacs-create-icon :extensions ("^src.*-open" .........)
```

Thanks! :)

**Comment by Alexander-Miller** [comment]
Pushed a new version, try now.

**Comment by luiznux** [comment]
Thank you very much! Works perfectly.
![image](https://github.com/Alexander-Miller/treemacs/assets/48339190/3c110f7f-01bd-4fdd-9312-bf58dcc2db0a)

**Comment by Alexander-Miller** [comment]
:+1:
