### ISSUE TITLE
[Suggestion] Add support for switch/change project

### ISSUE THREAD

**Issue by MirageTurtle** [Alexander-Miller/treemacs#1098]
I sincerely suggest to add some support for switch/change a project.

When I have only one project in a workspace, and I want to split it to some subfolders (actually, I want to remove the un-related subfolders), I need to add another temp project (which is not a subfolder for the existed folder), remove the older one, add the expected subfolders, remove the temp project, and then done.

I know this is not a common need, so I just suggest it. And I'd like to help to implement it :)

**Comment by Alexander-Miller** [comment]
You do have a few options.

You can make all changes at once with `treemacs-edit-workspaces`.

Another option is to move into one subfolder with `treemacs-root-down`, then add the other subfolders as needed.

**Comment by MirageTurtle** [comment]
> Another option is to move into one subfolder with `treemacs-root-down`, then add the other subfolders as needed.

I like this option, it's like that I still have more commands of treemacs to explore :)
