### ISSUE TITLE
Hide emacs temporary files?

### ISSUE THREAD

**Issue by nickelas** [Alexander-Miller/treemacs#11]
Is it possible to hide the temporary files that emacs creates? I guess they start with # or end with ~?

**Comment by Alexander-Miller** [comment]
You can change `treemacs-dotfiles-regex` to also catch files starting with #. `treemacs-show-dotfiles`, toggled with th, then controls whether files fitting this regex are shown.

**Comment by Alexander-Miller** [comment]
Assuming the files you want gone start with a # you can use `(rx bol (or "." "#") (1+ any))` to catch them plus the usual dotfiles.

**Comment by Alexander-Miller** [comment]
I'll eventually add a new var for completely ignored files which will include emacs' temp files, since these files will need to be ignored when I make treemacs automatically refresh on file system changes.

**Comment by Alexander-Miller** [comment]
Temp file hinding is in master, too, now. See `treemacs-ignored-file-predicates` https://github.com/Alexander-Miller/treemacs/commit/f05bf6163b2f4f091014f4940f230637a329dd78
