### ISSUE TITLE
Order workspaces according to `treemacs-persist`

### ISSUE THREAD

**Issue by sebastiaanspeck** [Alexander-Miller/treemacs#1108]
I would love to see that treemacs respects the order of my workspaces that are being listed in the `treemacs-persist` file. Right now if I want to switch to another workspace, the order seems random to me.

**Comment by Alexander-Miller** [comment]
This ticket made me go on a deep dive about sort order for `completing-read`. Treemacs does keep its workspaces in the order it encounters them in the persist file, you can look at `treemacs--workspaces` yourself.

However the order that Emacs shows you in completing-read depends on [collection metadata](https://emacs.stackexchange.com/questions/8115/make-completing-read-respect-sorting-order-of-a-collection) that you can pass on as well. Selection packages also have their own settings, like `vertico-sort-function` for my own config.

I should be able to use the first method to enforce that order - at least in this workspace selection, so let me know if it should be applied elsewhere as well.

**Comment by Alexander-Miller** [comment]
Change is pushed now, let me know if anything is missing.
