### ISSUE TITLE
bug(): pfuture-new: Wrong type argument

### ISSUE THREAD

**Issue by donjuanplatinum** [Alexander-Miller/treemacs#1110]
```
pfuture-new: Wrong type argument: stringp, ("/path/heap.rs" "Macro")
```
when i use treemacs to expand the tags of a rust file like this:
![Screenshot_20240609_083857](https://github.com/Alexander-Miller/treemacs/assets/113148619/7d9f2b0f-7fec-42ef-9592-4614624e8054)

then i press 'tab' on the root tree tag 'algori', like this:
![Screenshot_20240609_083935](https://github.com/Alexander-Miller/treemacs/assets/113148619/b450ddf2-58b7-44d2-87a2-b925b8f08542)

and then the bug appeared, i cant expand the algori tree, and the message is
```
pfuture-new: Wrong type argument: stringp, ("/path/algori/src/structure/heap.rs" "Macro") [6 times]
```

**Comment by donjuanplatinum** [comment]
and if i press the tag on algori 
```
Error running timer ‘treemacs--apply-annotations-deferred’: (wrong-type-argument number-or-marker-p nil) [4 times]
```

**Comment by Alexander-Miller** [comment]
Reproduced and locally and working on a fix.

**Comment by Alexander-Miller** [comment]
Pushed a fix, but there might be more. Let me know if it works for you now.

**Comment by donjuanplatinum** [comment]
> Pushed a fix, but there might be more. Let me know if it works for you now.

hi , i redownload the treemacs on elpa, now i can expand the tag
but still occur error
```
Error running timer ‘treemacs--apply-annotations-deferred’: (wrong-type-argument number-or-marker-p nil) [4 times]
```

**Comment by Alexander-Miller** [comment]
It seems to work on my end now. Did you also restart Emacs? If yes, can you give me a step by step reproduction recipe?
