### ISSUE TITLE
treemacs follow mode is inconsistent, doesn't respect nil on follow mode vars, breaks workspaces

### ISSUE THREAD

**Issue by embeddedpenguin** [Alexander-Miller/treemacs#1120]
![image](https://github.com/user-attachments/assets/c127b871-dc3f-456e-8c06-e5320759794f)
I've tried everything, but no matter what, every time treemacs detects a new project, it changes the tree to that project.

Here's an example.
I have cleared all my workspaces and opened a new project:
![image](https://github.com/user-attachments/assets/d40faaac-4e95-41e5-b0f9-9b18cfaf947f)
![image](https://github.com/user-attachments/assets/39f7b84a-a651-4072-98c3-f177432fa5ed)
Now when I save this, close it and reopen it, theres a new workspace:
![image](https://github.com/user-attachments/assets/baa15f82-087a-4332-be87-56ae22aa80a8)
I've added alacritty as a submodule to minicom for the following example.
Now if I perform:
```
<open file in a submodule>
(+treemacs-toggle)
(+treemacs-toggle)
```
Minicom is no longer in the tree, and it has automatically rooted down into alacritty.
![image](https://github.com/user-attachments/assets/3106e14b-ced9-4709-9718-05b970492e38)

It gets worse when I try to add a project to a workspace and save that workspace. Here's what I did next:
- Added a project to the workspace:
- Renamed the project to "Multiple Projects"
- Saved the workspace, keeping other perspectives
This resulted (correctly) in the following setup:
![image](https://github.com/user-attachments/assets/0748ad98-df8e-469a-a066-412973583aec)

The idea of a workspace (I think) is to group multiple projects and have them not go anywhere. Now I will perform the steps stated earlier:
```
<open file in a submodule>
(+treemacs-toggle)
(+treemacs-toggle)
```
Again, the workspace gone:
![image](https://github.com/user-attachments/assets/34863636-76cf-4ad6-89e9-623616dad9c3)
![image](https://github.com/user-attachments/assets/208ccc50-2869-4449-8ee2-c1cae6f65e2c)

Currently, I can't use workspaces. As far as I know I don't have _anything_ set for treemacs in my config other than
```
(require 'projectile)
(setq lsp-treemacs-sync-mode 1)
(setq projectile-project-search-path '("~/Projects/"))
(setq treemacs-hide-dot-git-directory nil)
(setq treemacs-project-follow-into-home nil)
(setf treemacs-follow-mode nil)
(setq treemacs-project-follow-mode nil)
(after! projectile
  (add-to-list 'projectile-globally-ignored-directories "^.cache$")
  (setq projectile-ignored-projects '("~/"
                                      "~/Projects/")))
```

**Comment by Alexander-Miller** [comment]
I see you're using doom syntax. Doom makes custom changes to treemacs, and integrates it with other packages.

Last I heard - which is admittedly a long time ago - doom actually forces a single-tree-only kind of workflow. Either based on its own means, or activating `treemacs-project-follow-mode`.

The new workspaces being created being called "Perspective X" also means that treemacs' persp-/perspective-mode integration is enabled, which syncs workspaces to your perspectives and ensures every perspective gets its own unique treemacs buffer (the default is for treemacs buffer to be unique for every graphical frame).

So it sounds like you might be clashing with Doom's treemacs defaults and additions. You might have better luck if you don't use the treemacs module, but install treemacs and its addons as normal packages instead.

> (setq treemacs-project-follow-mode nil)

These lines are also wrong. Variables like `treemacs-project-follow-mode` *describe* if a mode is on, they do not *decide* it. To turn off a minor mode you need to use `(treemacs-project-follow-mode -1)`.

**Comment by embeddedpenguin** [comment]
Properly setting `treemacs-project-follow-mode` to -1 seems to have worked just like you said. Thank you! I also will try using treemacs on its own instead of with the doom module just to see what the difference looks like, but my issue was solved with your solution as far as I can tell.
