### ISSUE TITLE
[feature request] Handle all kinds of Lisp 'def' constructs as Treemacs tags

### ISSUE THREAD

**Issue by rswgnu** [Alexander-Miller/treemacs#115]
There are defstructs and defmacros.  Hyperbole has its own defactype and defibtype.  Why not handle every kind of def that starts with a '(def<non-blank-chars>' at the beginning of a line, plus cl-def constructs, as a tag in Treemacs?

Then just name the category to which each tag belongs based on the type given by the car of the def itself, e.g. defmacro becomes 'Macros'.  For more flexibility, you could allow for an alist of (def-symbol . tag-category-string) pairs and if a definition symbol matched an entry, the string would be used for its category name.  So for a Hyperbole definition I might add an entry: (defactype . "Hyperbole Action Types") whereas the default string would just be: "Actypes" if I didn't add that entry.

To get you started in matching defs, Hyperbole actually provides this function that tries to distinguish definitions from things that look similar:

```
(defun smart-lisp-at-definition-p ()
    "Returns t when point is in a non-help buffer on the first line of a non-alias Lisp definition, else nil."
    (unless (derived-mode-p 'help-mode)
      (save-excursion
	(beginning-of-line)
	;; Exclude any define- lines.
	(and (looking-at "\\(;*[ \t]*\\)?(def[[:alnum:]]*[[:space:]]")
	     ;; Ignore alias definitions since those typically have symbol tags to lookup.
	     (not (looking-at "\\(;*[ \t]*\\)?(def[^ \t\n\r]*alias"))
	     ;; Ignore lines that start with (default
	     (not (looking-at "\\(;*[ \t]*\\)?(default"))))))
```

**Comment by Alexander-Miller** [comment]
Treemacs does not do any parsing on its own, [it's all done via imenu](https://github.com/Alexander-Miller/treemacs/blob/master/treemacs-tags.el#L133). This is not something where I want to do too much digging around the defaults, but `imenu-generic-expression` looks very promising.

**Comment by rswgnu** [comment]
On Mon, Dec 4, 2017 at 2:46 PM, Alexander-Miller <notifications@github.com>
wrote:

> ​​
> Treemacs does not do any parsing on its own, it's all done via imenu
> <https://github.com/Alexander-Miller/treemacs/blob/master/treemacs-tags.el#L133>.
> This is not something where I want to do too much digging around the
> defaults, but imenu-generic-expression looks very promising.
>
>
​Yes, it looks like imenu handles all the interesting defs, though I'd like
to see more categories for grouping different constructs.
If we add Hyperbole's defib and defact to that expression, things should be
good.  I'll see if I can interface with the imenu maintainer(s).
For that, though in the interim, I wouldn't be averse to tweaking its use
in Treemacs.

>

**Comment by rswgnu** [comment]
Actually, I should say tweaking its use in Hyperbole since that is where we
would do anything locally, I imagine.

**Comment by Alexander-Miller** [comment]
The generic-expression a list of conses so ideally it should be possible to push your own regexes on top so they are the first ones to match. For whatever reason that's not how it works - I've added a regex for finding macros and the entries are matched twice, first as a macro, and then, as would be default, as a top level item.

Adding a tweaked treemacs generic-expression that's let-bound before letting imenu parse should do the trick. Hyperbole could then add its own matches there when both are loaded.

**Comment by rswgnu** [comment]
Sounds good.  Let me know when it is there and I'll try it out.  Hyperbole, Treemacs and Ace-Window make an awesome combo now.

-- Bob
> Adding a tweaked treemacs generic-expression that's let-bound before letting imenu parse should do the trick. Hyperbole could then add its own matches there when both are loaded.
>

**Comment by Alexander-Miller** [comment]
I've built a reasonably complete set of match expressions, and will now work on integrating them in treemacs. Please try and them out and make sure I didn't miss anything:

```
(setq-local
 imenu-generic-expression
 (-let- [(name (rx (1+ whitespace) (group-n 2 symbol-start (1+ (or (syntax word) (syntax symbol))) symbol-end)))
         (prefix (rx bol (0+ (syntax whitespace)) "("))]
   `(("Functions"
      ,(concat prefix (rx (? "cl-") (or "defgeneric" "defmethod" "defun" "defadvice")) name)
      2)
     ("Inline Functions"
      ,(concat prefix (rx (? "cl-") "defsubst") name)
      2)
     ("Customizations"
      ,(concat prefix "defcustom" name)
      2)
     ("Types"
      ,(concat
        prefix
        (rx (group-n
             1 (or (seq (? "cl-") "defstruct")
                   "defclass"
                   "deftype"
                   "defgroup"
                   "define-widget"
                   "deferror")))
        name)
      2)
     ("Variables"
      ,(concat prefix (rx (or "defvar" "defvar-local" "defconst" "defconst-mode-local")) name)
      2)
     ("Macros"
      ,(concat prefix (rx (? "cl-") (or "define-compiler-macro" "defmacro")) name)
      2)
     ("Faces"
      ,(concat prefix (rx "defface") name)
      2))))
```

**Comment by Alexander-Miller** [comment]
I've pushed that imenu list to master now. It's a simple list, so you can easily push your own match expression into it.
