### ISSUE TITLE
messy in terminal

### ISSUE THREAD

**Issue by seagle0128** [Alexander-Miller/treemacs#119]
The line of `treemacs` shows messy in terminal. I am running GNU Emacs 25.3 on Ubuntu 16.04 LTS.
Please refer to the screenshot. I highlighted with red.

![treemacs](https://user-images.githubusercontent.com/140797/33929982-5a98572a-e026-11e7-8505-7cd6f3fa8aaa.png)

**Comment by Alexander-Miller** [comment]
Looks like a severe case of the UNICODEWTF.
I hope I can find a good replacement, instead of having to switch back to spaces. In the meantime you can change the value of `treemacs-icon-fallback-text`.

**Comment by seagle0128** [comment]
It works if I set the fallback text as blank. Thanks!

```elisp
(setq treemacs-icon-fallback-text "")
```
