### ISSUE TITLE
Update using g?

### ISSUE THREAD

**Issue by nickelas** [Alexander-Miller/treemacs#12]
My fingers want to update the list of files in treemacs using g, like in dired. I know its possible to tab the folder to update, but it'd be a nice feature

**Comment by Alexander-Miller** [comment]
This used to be possible, but was removed when I realized that g is a prefix for a lot of stuff in evil, so the simple bind I used didn't work. If you don't use evil something like `(define-key treemacs-mode-map (kbd "g") #'treemacs-refresh)` shoud do the trick.

I'll also try to put it back as a default.

**Comment by nickelas** [comment]
`(define-key treemacs-mode-map (kbd "g") #'treemacs-refresh)` works, thanks

**Comment by Alexander-Miller** [comment]
Refresh now works on g and r by default.

**Comment by nickelas** [comment]
Refreshing closes expanded folders. Would be cool if they remained open

**Comment by Alexander-Miller** [comment]
> Would be cool if they remained open

That should be the default behaviour. I can't reproduce it, so let's do some bug hunting:

1. Make sure you've pulled the lastest master. IIRC that bug might've existed for a short time, but should be fixed now.
2. Make sure the lastest master is loaded. Quickest way to do so is just restart emacs.
3. Assuming the issue still persists I'll need reproduction steps and some debug data.
4. Completely kill the treemacs buffer. Hitting Q in treemacs will do that, as will `kill-buffer`.
5. Verify the value of `treemacs--open-dirs-cache` is nil.
6. Switch to the treemacs buffer.
7. What is the value of `default-directory`?
8. What is the output of `(with-current-buffer (get-buffer treemacs--buffer-name) (treemacs--current-root))`?
9. Expand a directory. What's the value of `treemacs--open-dirs-cache` now?
10. Hit refresh. Again, what the value of `treemacs--open-dirs-cache`?

**Comment by nickelas** [comment]
Is the bug-hunting still interesting? Might have some time to do it

**Comment by Alexander-Miller** [comment]
Of course, that list was meant for you to go through, I've just been waiting for feedback.

Except as of now it's the *dev* branch you need to be checking out, it's where I'm pushing all new changes while treemacs is being reviewed for getting published on MELPA.

**Comment by nickelas** [comment]
Yes, I saw the branch and thought maybe it changed things. But here are the answer for dev-branch
5. Yes
7. "/home/user/"
8. "/home/user"
9. (("/home/user" "/home/user/.adobe"))
10. (("/home/user" "/home/user/.adobe"))

**Comment by Alexander-Miller** [comment]
Everything looks in order. Since .adobe is in the cache under user it should have been reopened after the refresh.

Can you reproduce the bug consistently, in all directories, or is it limited somehow?

**Comment by Alexander-Miller** [comment]
Random idea: do you have old treemacs byte code lying around that's getting loaded somehow? Check if there are any .elc files in the repo.

**Comment by nickelas** [comment]
Only .el files in .emacs/elpa/treemacs/. I am getting this message quite often
`treemacs--reopen: Symbol's value as variable is void: inhibit-message`

**Comment by Alexander-Miller** [comment]
Now that's a breakthtough. You aren't running emacs 25, right?

**Comment by nickelas** [comment]
Nope `GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)`

**Comment by Alexander-Miller** [comment]
Yeah, turns out inhibit-message was only introduced in emacs 25 and the whole reopen bit was failing without it. Officially treemacs needs emacs 24.4, so the fix is on me. Try the `messages` branch, the fix should work for you.

**Comment by nickelas** [comment]
Works!
