### ISSUE TITLE
treemacs-toggle, doesn't close treemacs after deleting a frame

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#126]
### Description
`treemacs-toggle` doesn't close treemacs, when the cursor is in a non-treemacs window, after having deleted a frame that had a treemacs window open.

### Steps to reproduce

1. Start Emacs
2. Open a treemacs window `M-x treemacs-toggle`
3. Open a new frame `C-x 5 2`
4. Open a treemacs window in the new frame `M-x treemacs-toggle`
5. Delete the other frame `C-x 5 1`
6. Select the non-treemacs window `C-x o`
7. Try to close the treemacs window `M-x treemacs-toggle`

#### Observed
The selected windows buffer changes.

#### Expected
The treemacs window should close.

### Possible cause
The `treemacs--buffer-access` variable has the value `nil`, after the frame with a treemacs window has been deleted.

This seems to be where the variable is used:
The `toggle-treemacs` function calls: `(treemacs--current-visibility)` which returns `visible`.
https://github.com/Alexander-Miller/treemacs/blob/4397c144c5bbff91f86101397cc10855be3aa8d5/src/elisp/treemacs.el#L61-L66

Then the `(treemacs--select-visible)` function, tries to switch to the treemacs buffer, using the 
`treemacs--buffer-access` variable. But it's value is `nil`, so the cursor remains in the current window.
https://github.com/Alexander-Miller/treemacs/blob/4397c144c5bbff91f86101397cc10855be3aa8d5/src/elisp/treemacs-impl.el#L195-L201

Then `(one-window-p)` returns `nil`, and the `(bury-buffer)` function gets called.

The `treemacs--buffer-access` variable seems to be set in the `treemacs--remove-framelocal-buffer` function.
https://github.com/Alexander-Miller/treemacs/blob/4397c144c5bbff91f86101397cc10855be3aa8d5/src/elisp/treemacs-impl.el#L683-L687

### Additional notes
In step 6 (after deleting the other frame and selecting the non-treemacs window), if one calls `M-x treemacs` instead of `M-x treemacs-toggle`, then another instance of treemacs opens in the current window.

Maybe it also is caused by the `treemacs--buffer-access` variable returning `nil`.

#### System Info
Windows 10 Version 1709 (OS Build 16299.125)
GNU Emacs 26.0.50 (build 4, x86_64-w64-mingw32) of 2017-08-07
Treemacs 1.15.2

**Comment by Alexander-Miller** [comment]
> treemacs--buffer-access

Yeah, it's all down to this one. Ìt's quite a hairy piece of logic where killing other frames leads to running the remove framelocal buffer function (with the deleted frame) which leads to killing their treemacs buffers which leads to running that function (without the deleted frame) which means we're just killing treemacs locally (as Q does), so the association for the *selected* frame is deleted. Easy and straightforward, right?

I've separated the buffer/frame kill logic now, so it should work and be quite a bit less complex.
