### ISSUE TITLE
Does treemacs work with global/gtags?

### ISSUE THREAD

**Issue by randre03** [Alexander-Miller/treemacs#127]
If I generate a tags file with `ctags -eR`, then I can view the tags from treemacs. 

However, if I generate the tags files with `gtags` (creating GPATH, GRTAGS and GTAGS) this functionality does not work. When I have the 'cursor' on a file in treemacs and press `tab` to view the tags, an error message shows in the minibuffer: `[Treemacs] No tags found for <Filename>`

**Comment by Alexander-Miller** [comment]
Treemacs sources the tags it shows from imenu. I assume the difference between your ctags and gtags result is that the ctags package you use includes imenu integration.

So, easiest solution: a package that pipes gtags into imenu. If we can't have that I'll need to interface with gtags myself, so I need to know if you use any additional packages to interface with gtags.

**Comment by randre03** [comment]
Thanks. Your comment got me thinking  there must be a way to integrate gtags with imenu. I found that [here](https://tuhdo.github.io/c-ide.html#orgheadline5). All I needed to do was add the following to my .init file:

`(setq-local imenu-create-index-function #'ggtags-build-imenu-index)`

Just to answer the other item you raised - I use [ggtags-mode](https://github.com/leoliu/ggtags).

**Comment by Alexander-Miller** [comment]
That'll work if you're looking at the tags of files that are already open in emacs. Other files will still use the default imenu function. Getting that to work will need some non-trivial changes, and I'll open a separate issue for it in the future.
