### ISSUE TITLE
Sort?

### ISSUE THREAD

**Issue by nickelas** [Alexander-Miller/treemacs#13]
Sorting files would be useful. Maybe I am just blind and its implemented?

**Comment by Alexander-Miller** [comment]
As of now sorting is basically hardcoded. It's always first directories, then files, both in the alphabetical order that f.el will give me?

What sorting options do you have in mind?

**Comment by nickelas** [comment]
Modified, size, alphabetical

**Comment by Alexander-Miller** [comment]
This is teetering awfully close to what I'd consider a task for a file manager - like dired, and not a file explorer - like treemacs. I probably would have refused here, however reworking the file fetching to do filtering and sorting on my own is something I wanted to do for a while anyway, so a bit of custom filtering isn't too large a detour.

On the plus side I now need a way I to get rid of those pesky . and .. directories, so a way to ignore those and emacs lock files will come early.

**Comment by Alexander-Miller** [comment]
Sorting's in master now. See `treemacs-sorting` https://github.com/Alexander-Miller/treemacs/commit/f05bf6163b2f4f091014f4940f230637a329dd78
