### ISSUE TITLE
Better persistent mode

### ISSUE THREAD

**Issue by seagle0128** [Alexander-Miller/treemacs#131]
I notice `treemacs` doesn't save `visible` in `desktop-mode`. Every time I use `treemacs-toggle` to open and make it invisible, then restart Emacs, the `treemacs` buffer is visible again. Is it the proper behavior?

**Comment by Alexander-Miller** [comment]
That's the intended behaviour so far, yes. I figured if you're saving treemacs you'll probably want to see it. Went through a bit of trouble to keep treemacs visible even.

Saving the visibility is a good idea, so I'll put it on my todo list.

**Comment by Alexander-Miller** [comment]
Visibility is now saved in treemacs v1.16. 
Let me know if it works fo you.

**Comment by Alexander-Miller** [comment]
I assume no complaints means everything's working out.

**Comment by seagle0128** [comment]
Yes. It's working. Sorry for forgetting to close it.
