### ISSUE TITLE
Follow Mode unresponsive on new install

### ISSUE THREAD

**Issue by jeregrine** [Alexander-Miller/treemacs#132]
New Install of Spacemacs,

Running on develop of spacemacs.
Installed treemacs layer.

1) Open a project SPC p p
2) Open treemacs SPC f P -> File is not highlighted, just top level dir is shown
3) Change file in project SPC p f -> File is not highlighted 

I have tried doing t f to verify its enabled. And I've set it in my config as well.

`
  (with-eval-after-load "treemacs"
    (treemacs-tag-follow-mode 1)
    (treemacs-git-mode 'extended))
`

Just never follows.

**Comment by Alexander-Miller** [comment]
You're using tag-follow-mode, which specifically follows tags, not files. It's also triggered by an idle timer, so not following after `SPC f P` is correct. Nothing happening after `SPC p f` is not.

Let's investigate: 
* Do you see any treemacs-related output in the messages buffer?
* Are both follow-mode and tag-follow-mode equally unresponsive?
* Does the issue still occur when treemacs is showing a simple minimal-case directory with only 2 files in it?
* What happens when you manually call `treemacs-find-file/tag`?

**Comment by jeregrine** [comment]
Doh I changed it to use treemacs-follow-mode 1 and same result.


- Yes `[Treemacs] Encountered error while following tag at point: (wrong-type-argument markerp 93) [10 times]`

- I don't know how to use tag mode
- well I'm not sure. I made an empty dir with two ruby files and a .projectfile, I opened the ruby file and did SPC f P and it says `[Treemacs] You are not in a project`
- If treemacs isn't opened it toggles it. But it doesn't open the directories. It just opens the root.

**Comment by jeregrine** [comment]
I tried disabling tag mode and the error remained.

I should also mention git-mode doesn't work

**Comment by Alexander-Miller** [comment]
Ok, first of all, which treemacs version are you on? You can check the value of `treemacs-version`.

>  I made an empty dir with two ruby files and a .projectfile, I opened the ruby file and did SPC f P and it says [Treemacs] You are not in a project

It's projectile that didn't know you're in a project, I guess you need to invalidate its cache. `SPC f T` will do as well.

> [Treemacs] Encountered error while following tag at point: (wrong-type-argument markerp 93) [10 times]

That's good. It means we have a stacktrace to follow. To produce the stacktrace first kill the treemacs buffer, then enable debug-on-error with `SPC t D`, then find `treemacs-impl.el`, `-async.el` and `-follow-mode.el` with `SPC f e l`, visit each of them and evalaute them with `, e b` (I make very heavy use of inlined functions, and loading their uninlined elisp forms will make the stacktrace more readable). Then call `treemacs-find-file`. That should produce the needed stacktrace.

> I don't know how to use tag mode

It's the same as follow-mode, just with tags instead of files.

For git mode : are you on windows? Git mode not working made me think of https://github.com/Alexander-Miller/treemacs/issues/125. What about the simple variant, does that work? You should also try the debugging questions I asked in #125.

**Comment by jeregrine** [comment]
- "1.15.2"
- I tried that and got similar errors :-/
- I did all that you described and I no longer get that error message. But I do get
```
Entering debugger...
```

But I don't know where thats happening. I'm pretty new on my emacs journey here. 

-re-git mode OSX. The version-control/git layers seem to work as I have the errors in the buffer.

**Comment by Alexander-Miller** [comment]
> Entering debugger...  But I don't know where thats happening.

Usually a stacktrace window should pop up. Look in your buffer list for a buffer called `*Backtrace*`.

**Comment by jeregrine** [comment]
I have python 2.7, the posixpath seems to work.

**Comment by Alexander-Miller** [comment]
> I have python 2.7

Then we have one problem less. Extended git-mode requires python3 (but not as the default, you can set `treemacs-python-executable`).

**Comment by jeregrine** [comment]
I removed my `extended` mode to reduce errors and git still doesnt work :/

**Comment by Alexander-Miller** [comment]
How did you remove it?

**Comment by jeregrine** [comment]
the configuration I set in my .spacemacs

**Comment by jeregrine** [comment]
Is there gitter or irc or somewhere we can chat more synchronously?  I had to reboot emacs cause I accidentally closed the whole thing.

And now the error is not happening, and the debug is not showing up. But its still not finding the file :-/

**Comment by Alexander-Miller** [comment]
I've contacted you in the spacemacs gitter.

**Comment by Alexander-Miller** [comment]
I've prepated some debug code now. Here's what you do:
 * Start emacs and treemacs
 * Kill that treemacs buffer again, we just want treemacs to be loaded.
 * Copy below code into scratch and evaluate it
 * Open treemacs with its root in some project
* Disable `treemacs-follow-mode`
* Switch to some file in the project
* Delete the messages buffer
* Call `treemacs-find-file`
* Switch to the messages buffer and grab all the treemacs debug output

```

(cl-defun treemacs-find-file (&optional (path (buffer-file-name (current-buffer))))
  "Find and focus PATH (or the current file) in the treemacs view.
Most likley to be useful when `treemacs-follow-mode' is not active.

Expand folders if needed. If PATH is not under the current root ask to change
the root. If no treemacs buffer exists create it. Do nothing if PATH is not
given and the current buffer is not editing a file."
  (interactive)
  (treemacs--log "treemacs-find-file : %s" path)
  (when (and path (f-exists? path))
    (save-selected-window
      (treemacs--without-following
       (let* ((visibility (treemacs--current-visibility))
              (path       (f-long path))
              (is-dir?    (f-directory? path)))
         (treemacs--log "Start visibility switch")
         (treemacs--log "Visibility: %s Path: %s is-dir: %s" visibility path is-dir?)
         ;; get up a visible treemacs buffer, regardless of its current state
         (if (eq visibility 'none)
             ;; TODO follow after init?
             ;; finding a file without an existing treemacs is just an init
             ;; nothing else to do here
             (progn
               (treemacs--log "No buffer exists, simply init")
               (treemacs--init (if is-dir? path (f-dirname path))))
           (progn
             (cl-case visibility
               (exists  (treemacs-toggle))
               (visible (treemacs--select-visible))
               (t       (error "Unkown treemacs buffer visibility '%s'" visibility)))
             ;; find the file given whether is a directory and if it can be found below
             ;; the current root or not
             (treemacs--log "Start find-file logic")
             (let ((root (treemacs--current-root)))
               (treemacs--log "Current Root: %s" root)
               (if (treemacs--is-path-in-dir? path root)
                   (progn
                     (treemacs--log "Path %s is below Root %s, start follow" path root)
                     (treemacs--do-follow path root))
                 (when (or treemacs-change-root-without-asking
                           (y-or-n-p "Change the treemacs root to find the file? "))
                   (treemacs--log "Path %s not under Root %s, Reinit" path root)
                   (if is-dir?
                       (treemacs--init path)
                     (progn
                       (treemacs--init (f-dirname path))
                       (treemacs--log "Error likely to be here, if this part is called")
                       (treemacs--log "Should probably be `treemacs--do-follow'")
                       (treemacs--goto-button-at path)
                       (hl-line-mode -1)
                       (hl-line-mode t)))))))))))))

(cl-defun treemacs--do-follow (followed-file &optional (root (treemacs--current-root)))
  "In the treemacs buffer move point to FOLLOWED-FILE given current ROOT.
The followed file MUST be under root or the search will break."
  (treemacs--log "treemacs--do-follow : %s %s" followed-file root)
  (let* ((start         (point))
         (dir-parts     (->> (length root) (substring followed-file) (f-split) (cdr)))
         (search-result (treemacs--follow-each-dir dir-parts root)))
    (treemacs--log "Start %s dir-parts %s search-result : %s" start dir-parts search-result)
    (when (eq search-result 'follow-failed)
      (treemacs--log "Search failed, back to start")
      (goto-char start))
    ;; hl-line *needs* to be toggled here otherwise it won't appear to
    ;; move until the treemacs buffer is selected again and follow must
    ;; work when called from outside the treemacs buffer with treemacs-follow-mode
    (treemacs--evade-image)
    (hl-line-highlight)
    (set-window-point (get-buffer-window) (point))
    (when treemacs-recenter-after-file-follow
      (treemacs--without-following
        (with-selected-window (get-buffer-window)
         (recenter))))))

(defsubst treemacs--follow-each-dir (dir-parts root)
  "Follow (goto and open) every single dir in DIR-PARTS, starting at ROOT."
  (treemacs--log "treemacs--follow-each-dir: %s %s" dir-parts root)
  (save-match-data
    (catch 'follow-failed
      (let ((last-index (- (length dir-parts) 1))
            (search-start (point-min)))
        (treemacs--log "last-index: %s search-start: %s" last-index search-start)
        (treemacs--log "Start dir-part loop")
        (--each dir-parts
          (setq root (f-join root it))
          (treemacs--log "Current dir-part: %s" it)
          (treemacs--log "Current root %s" root)
          (let ((btn (treemacs--goto-button-at root search-start)))
            (treemacs--log "Moved to button %s with label %s" btn (if btn (treemacs--get-label-of btn) "NIL"))
            (if (null btn)
                (progn
                  (treemacs--log "Goto button at %s failed" root)
                  (throw 'follow-failed 'follow-failed)))
            ;; don't open dir at the very end of the list since we only want to put
            ;; point in its line
            (when (and (eq 'dir-node-closed (button-get btn 'state))
                       (< it-index last-index))
              (treemacs--log "Expand the button")
              (treemacs--open-dir-node btn)))
          (setq search-start (point)))
        (treemacs--log "Finish dir-part loop")
        t))))

(cl-defun treemacs--goto-button-at (abs-path &optional (start-from (point-min)))
  "Move point to button identified by ABS-PATH, starting search at START.
Also return that button.
Callers must make sure to save match data"
  (treemacs--log "treemacs--goto-button at %s %s" abs-path start-from)
  (let ((keep-looking t)
        (filename (f-filename abs-path))
        (start (point))
        (ret))
    (goto-char start-from)
    (treemacs--log "filename: %s start: %s" filename start)
    (treemacs--log "Enter search loop")
    (while (and keep-looking
                (search-forward filename nil t))
      (treemacs--log "Search loop")
      (beginning-of-line)
      (treemacs--log "Button is %s with path %s"
                     (-if-let- [btn (next-button (point) t)] (treemacs--get-label-of btn) "NIL")
                     (-if-let- [btn (next-button (point) t)] (button-get btn 'abs-path) "NIL") )
      (let* ((btn (next-button (point) t))
             (btn-path (button-get btn 'abs-path)))
        (if (or (s-equals? abs-path btn-path)
                ;; loosen matching for collapsed paths
                (and (button-get btn 'parent-path)
                     (treemacs--is-path-in-dir? btn-path abs-path)))
            (progn (treemacs--evade-image)
                   (treemacs--log "Button found")
                   (setq keep-looking nil
                         ret btn))
          (beginning-of-line 2))))
    (unless ret (goto-char start))
    (treemacs--log "Return %s" (treemacs--get-label-of ret))
    ret))
```

**Comment by Alexander-Miller** [comment]
Oh  and one more thing: also add a screenshot of the project's file structure in treemacs, with the file you want followed visible. Knowing the file layout will make it easier to see what went wrong.

**Comment by Alexander-Miller** [comment]
I think I know what's going on thanks to #134. There's been an update in f.el that treemacs cannot deal with.

**Comment by Alexander-Miller** [comment]
Pushed a bunch of fixes. Try again with the new version. You know you've the newest treemacs when the value of `treemacs-version` is 1.15.3.

**Comment by jeregrine** [comment]
That appears to have fixed follow mode!

Git mode appears to not be working.

**Comment by Alexander-Miller** [comment]
Let's keep debugging then. I'll need 2 things:

 1) The output of running `git status --porcelain --ignored .` in a repository of yours.
 2) The output of the following code, executed using the path to the same repo.

```
(progn
  (treemacs-git-mode 'simple)
  (cl-assert (eq #'treemacs--git-status-process-simple (symbol-function 'treemacs--git-status-process-function)))
  (cl-assert (eq #'treemacs--parse-git-status-simple (symbol-function 'treemacs--git-status-parse-function)))
  (maphash
   (lambda (k v)
     (message "%s -> %s" k (char-to-string v)))
   (-> "REPO"
       (treemacs--git-status-process-function)
       (treemacs--git-status-parse-function))))
```

**Comment by Alexander-Miller** [comment]
Bump?

I can't quite remember where we stopped, but I've pushed a couple new versions in the meantime, so you should see if you're still having trouble there,

**Comment by Alexander-Miller** [comment]
I'll close here on account of inactivity. If you still have problems with the newest treemacs version feel free to reopen.
