### ISSUE TITLE
xref requires Emacs 25...?

### ISSUE THREAD

**Issue by egarson** [Alexander-Miller/treemacs#133]
Hello,
Thanks for this great work which makes my life better.
I believe you have a documentation defect in that Emacs 25 is required (not 24 as stipulated). If I'm not mistaken, xref was released as part of the enhancements to Emacs 25 (it effectively deprecates etags). When using Emacs 24, treemacs fails with a "can't load xref".
Cheers

**Comment by Alexander-Miller** [comment]
Ah, I didn't know xref is this young.

It's not a very hard dependency, and loaded only in the code providing a bridge for GNU hyperbole. I'll just remove the error on load until emacs26 is released (which should be soon), and make the switch then. This way I'll keep supporting the current and previous emacs version.

**Comment by egarson** [comment]
Sounds good, thanks!
