### ISSUE TITLE
el-mock seems to be mocking

### ISSUE THREAD

**Issue by technician77** [Alexander-Miller/treemacs#135]
When installing current melpa package I get:
Compiling z:/home/jlange/.emacs.d/elpa/treemacs-20180106.1402/treemacs-tests.el...
apply: Cannot open load file: No such file or directory, el-mock

When I install el-mock manually everything is fine. It seems el-mock is not loaded as dependency automatically like pfuture.

Using GNU Emacs 26.0.90 (build 1, x86_64-w64-mingw32) of 2017-11-30

Kind regards,
tech77

**Comment by Alexander-Miller** [comment]
Those tests shouldn't even be in the package. https://github.com/Alexander-Miller/treemacs/commit/108678058e1f3f951937caec2667fd8a4f9702b1 will fix that while I'm cleaning this up in #134.

**Comment by Alexander-Miller** [comment]
This should now be fixed in version 1.15.3.

**Comment by technician77** [comment]
It is.
