### ISSUE TITLE
Less aggressive recentering

### ISSUE THREAD

**Issue by quicknir** [Alexander-Miller/treemacs#136]
Right now, as far as centering goes, you basically have two options: either recenter on every file/tag follow, or don't at all. I use tag follow mode. If tag recenter is on, then the window is jumping around a lot and it's very distracting. If tag recenter is off, then things eventually make there way to the very edge of the screen and e.g. I cannot see their children. It would be really nice if there was some kind of less aggressive recenter that simply kept the active node in follow mode (file or tag), in say, the middle half, or middle 2/3 of the screen. This would mean that on the one hand, I almost never get sudden movement simply by moving my cursor from one function to the next, and on the other hand, would ensure that things are never at the edge of the screen either.

**Comment by Alexander-Miller** [comment]
Good idea. I'll put it on my todo list.

**Comment by Alexander-Miller** [comment]
Starting to look into this now. Ideally I'd make a check based on point being on line x out of y in the treemacs window. I can get y with `window-screen-lines`, but I'm struggling with x. You wouldn't happen to know an easy option to get the current window line? I'd rather avoid hacking something together with `count-screen-lines`.

**Comment by quicknir** [comment]
@Alexander-Miller I thought a bit about this and poked around. I just stumbled across something that seems pretty useful: `move-to-window-line-top-bottom`. With sequential calls, this function moves the point to the middle, bottom, then top of the visible buffer, without moving the buffer at all. Basically, you can move the point to the element you want reasonably-centered (folder/tag/whatever), record line number, call this a few times, record line number at top and bottom of the screen. And this gives you all the information you need. Probably even better is to look inside the implementation of `move-to-window-line-top-bottom` and do the adjustments yourself.

Let me know whether or not this helps!

**Comment by Alexander-Miller** [comment]
> move-to-window-line-top-bottom

**Comment by Alexander-Miller** [comment]
I was reluctant to rely on line numbers, since getting a line number involves counting them quite literally (as in searching the buffer for `\n`), but looking into your tip gave me an idea: all I need to do is just count the number of lines between `window-start` and `point`, which won't impact performance.

I have all the necessary tools now, so this should be done soon.

**Comment by Alexander-Miller** [comment]
Patch has been pushed, you can now set the distance from window top/bottom with `treemacs-follow-recenter-distance`.

**Comment by Alexander-Miller** [comment]
I think we are done here.
