### ISSUE TITLE
Native line number in treemacs

### ISSUE THREAD

**Issue by jbharat** [Alexander-Miller/treemacs#137]
Emacs 27.0.50, spacemacs develop 

If native line numbering is enabled, treemacs has line numbers. Is there a way to stop native line numbers getting shown on treemacs

I am using code shown below
```
    (setq display-line-numbers (quote relative))
    (global-display-line-numbers-mode t)
```

**Comment by jbharat** [comment]
`(add-hook 'treemacs-mode-hook (lambda() (display-line-numbers-mode -1)))` fixed it

**Comment by Alexander-Miller** [comment]
Nitpick: hooks should be named functions, makes it easier to change/remove them.

You may also want to consider turning on line numbers only in prog/text mode or turning them off for special-mode, since you probably don't want line numbers in special-mode-derived buffers like treemacs and magit.

**Comment by jbharat** [comment]
Oh right that makes sense. I am using global-display-line-numbers-mode. Thanks I will change it

**Comment by jbharat** [comment]
Oh right that makes sense. I am using global-display-line-numbers-mode. Thanks I will change it
