### ISSUE TITLE
There has no responding when typing "w" to change width

### ISSUE THREAD

**Issue by LuhengStat** [Alexander-Miller/treemacs#142]
When I want to change width using command "w", there has no responding. However,
when i first randomly type a number (e.g. 1, 2), then the command "w" works. is it a bug?

**Comment by Alexander-Miller** [comment]
Just `w` will reset the width to its default value, It's a very old function, from a time when I did not have as solid a grasp of the treemacs window as I do now, and when resetting the width was sometimes necessary. To change the width you'd need to press `C-u w`, but numbers work, too.

In the future I'll change `w` so it'll work as a width toggle like TAB does in neotree.

**Comment by LuhengStat** [comment]
Thanks. I see.
