### ISSUE TITLE
Question: Two treemacs buffers side-by-side

### ISSUE THREAD

**Issue by mpfeifer** [Alexander-Miller/treemacs#147]
Using treemacs can I put two treemacs buffers side-by-side and have them show different directories?

**Comment by Alexander-Miller** [comment]
With a small detour, yes. As far multiple buffers are concerned treemacs has one simple rule: Every frame has its own unique treemacs buffer. So you can spawn another frame, with another treemacs buffer, and put them side by side, like this:

https://i.imgur.com/rJFV0IW.png
