### ISSUE TITLE
Cannot install treemacs package from melpa-stable

### ISSUE THREAD

**Issue by dragano** [Alexander-Miller/treemacs#150]
Hey there,

I'm using Emacs 24.5.1 and cannot install the treemacs package from melpa-stable. The issue seems to be the `ht` dependency. The treemacs package requires version 2.3, but only 2.2 is available in melpa-stable.

Trying to install the package produces the following error response:

> Need package `ht-2.3', but only 2.2 is available

**Comment by Alexander-Miller** [comment]
Fixed in v1.18.1 with https://github.com/Alexander-Miller/treemacs/commit/e8be02971ad6c7a9c33ec544fa41b4b2f6827a35.

**Comment by dragano** [comment]
Tried it again and installation works now. Thanks!
