### ISSUE TITLE
ht orphaned 

### ISSUE THREAD

**Issue by vakosel** [Alexander-Miller/treemacs#153]
Hi there , impressed by your work. Well done.
I installed treemacs with the help of your example (use-package etc etc) as i use the community and not the develpment version of spacemacs. 
I am very happy with treemacs but whenever emacs starts complains about 5 orphaned packages that deletes them and have to do with ht package. Is there a way to fix that without breaking spacemacs functionality. I have to clarify  that i can live without neotree.

Thanks in advance
Kostas

**Comment by vakosel** [comment]
it must have to do with the version . In your 1.18.1 fix  2.2 version is needed instead of 2.3 which is the latest. For some reason i have 2.3 version  of ht and 1.18.1 of treemacs . Any idea ?

**Comment by Alexander-Miller** [comment]
I don't think ht's version has to do with this. 2.2 is the latest version published to melpa stable, I need to use it or treemacs stable cannot be installed at all.

I assume the issue is that for whatever reason there's an old version 2.0 of ht included with spacemacs in core/libs, though why spacemacs would think that it's orphaned I cannot say.

As a stopgap you can try adding ht to `dotspacemacs-additional-packages`. I'll put looking into this on my todo list.

**Comment by vakosel** [comment]
No i checked my version is 2.3 simply because spacemacs uses volatile bleeding edge melpa. Not stable. I tried 
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
(add-to-list 'package-pinned-packages '(ht . "melpa-stable") t)
but it doesnt seem to work after version  spacemacs 200 which is my case . So i deleted it and 
i started emacs --debug-init and the relevant code - having to do with ht and treemacs packages - is the following . Deletes in every startup everyrhing and downlaods it again : 

(Spacemacs) Loading auto-layer file...
Loading /home/vakosel/.emacs.d/layers/auto-layer.el (source)...done
(Spacemacs) --> deleting treemacs-projectile... [1/5]
Package ‘treemacs-projectile-20180203.416’ deleted.
(Spacemacs) --> deleting treemacs-evil... [2/5]
Package ‘treemacs-evil-20180203.416’ deleted.
(Spacemacs) --> deleting treemacs... [3/5]
Package ‘treemacs-20180221.1229’ deleted.
(Spacemacs) --> deleting pfuture... [4/5]
Package ‘pfuture-20171116.812’ deleted.

and then :
Spacemacs is ready.
(Spacemacs) Calling dotfile user config...
Contacting host: melpa.org:443 [2 times]
Making version-control local to ht-autoloads.el while let-bound!
Configuring package recentf...done
Loading /home/vakosel/.emacs.d/.cache/recentf...done
Generating autoloads for ht.el...done
Wrote /home/vakosel/.emacs.d/elpa/ht-20180129.1434/ht-autoloads.el
Checking /home/vakosel/.emacs.d/elpa/ht-20180129.1434... [3 times]
Compiling /home/vakosel/.emacs.d/elpa/ht-20180129.1434/ht.el...done
Wrote /home/vakosel/.emacs.d/elpa/ht-20180129.1434/ht.elc
Checking /home/vakosel/.emacs.d/elpa/ht-20180129.1434...
Done (Total of 1 file compiled, 2 skipped)
Contacting host: melpa.org:443
Generating autoloads for pfuture.el...done
Wrote /home/vakosel/.emacs.d/elpa/pfuture-20171116.812/pfuture-autoloads.el
Checking /home/vakosel/.emacs.d/elpa/pfuture-20171116.812... [3 times]
Compiling /home/vakosel/.emacs.d/elpa/pfuture-20171116.812/pfuture.el...done
Wrote /home/vakosel/.emacs.d/elpa/pfuture-20171116.812/pfuture.elc
Checking /home/vakosel/.emacs.d/elpa/pfuture-20171116.812...
Done (Total of 1 file compiled, 2 skipped)
Contacting host: melpa.org:443
Auto-evilification could not remap these functions in map ‘tar-mode-map’:
   - ‘tar-chgrp-entry’ originally mapped on ‘G’
Parsing tar file...done
Extracting treemacs-20180221.1229/
Extracting treemacs-20180221.1229/treemacs-impl.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-impl.el
Extracting treemacs-20180221.1229/treemacs-mode.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-mode.el
Extracting treemacs-20180221.1229/treemacs-persist.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-persist.el
Extracting treemacs-20180221.1229/treemacs.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs.el
Extracting treemacs-20180221.1229/treemacs-faces.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-faces.el
Extracting treemacs-20180221.1229/treemacs-customization.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-customization.el
Extracting treemacs-20180221.1229/treemacs-interface.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-interface.el
Extracting treemacs-20180221.1229/icons/
Extracting treemacs-20180221.1229/icons/json.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/json.png
Extracting treemacs-20180221.1229/icons/hy.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/hy.png
Extracting treemacs-20180221.1229/icons/pdf.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/pdf.png
Extracting treemacs-20180221.1229/icons/dir_closed.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/dir_closed.png
Extracting treemacs-20180221.1229/icons/go.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/go.png
Extracting treemacs-20180221.1229/icons/clojure.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/clojure.png
Extracting treemacs-20180221.1229/icons/dart.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/dart.png
Extracting treemacs-20180221.1229/icons/emacs.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/emacs.png
Extracting treemacs-20180221.1229/icons/tags-open.xpm
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/tags-open.xpm
Extracting treemacs-20180221.1229/icons/shell.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/shell.png
Extracting treemacs-20180221.1229/icons/conf.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/conf.png
Extracting treemacs-20180221.1229/icons/yaml.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/yaml.png
Extracting treemacs-20180221.1229/icons/cpp.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/cpp.png
Extracting treemacs-20180221.1229/icons/markdown.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/markdown.png
Extracting treemacs-20180221.1229/icons/python.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/python.png
Extracting treemacs-20180221.1229/icons/typescript.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/typescript.pngConfiguring package yasnippet...done
[yas] Check your `yas-snippet-dirs': /home/vakosel/.emacs.d/elpa/yasnippet-20180304.1607/snippets is not a directory
[yas] Check your `yas-snippet-dirs': ~/snippets is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
Configuring package highlight-parentheses...done
Configuring package auto-highlight-symbol...done
Configuring package elisp-slime-nav...done
Configuring package auto-compile...done
Configuring package company...done
Generating autoloads for treemacs-async.el...done
Generating autoloads for treemacs-branch-creation.el...done
Generating autoloads for treemacs-compatibility.el...done
Generating autoloads for treemacs-customization.el...done
Generating autoloads for treemacs-faces.el...done
Generating autoloads for treemacs-filewatch-mode.el...done
Generating autoloads for treemacs-follow-mode.el...done
Generating autoloads for treemacs-impl.el...done
Generating autoloads for treemacs-interface.el...done
Generating autoloads for treemacs-macros.el...done
Generating autoloads for treemacs-mode.el...done
Generating autoloads for treemacs-mouse-interface.el...done
Generating autoloads for treemacs-persist.el...done
Generating autoloads for treemacs-pkg.el...done
Generating autoloads for treemacs-structure.el...done
Generating autoloads for treemacs-tag-follow-mode.el...done
Generating autoloads for treemacs-tags.el...done
Generating autoloads for treemacs-visuals.el...done
Generating autoloads for treemacs.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-autoloads.el
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-async.el...
Configuring package avy...done
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-async.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-async.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229... [2 times]
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-branch-creation.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-branch-creation.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-compatibility.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-compatibility.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-customization.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-customization.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-faces.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-faces.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-filewatch-mode.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-filewatch-mode.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-follow-mode.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-follow-mode.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-impl.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-impl.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-interface.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-interface.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-macros.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-macros.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-mode.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-mode.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-mouse-interface.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-mouse-interface.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-persist.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-persist.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229... [2 times]
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-structure.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-structure.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-tag-follow-mode.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-tag-follow-mode.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-tags.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-tags.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-visuals.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-visuals.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons...
Done (Total of 18 files compiled, 2 skipped)
Contacting host: melpa.org:443 [2 times]
Generating autoloads for treemacs-projectile.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416/treemacs-projectile-autoloads.el
Checking /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416... [3 times]
Compiling /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416/treemacs-projectile.el...
Configuring package treemacs...
Generating autoloads for treemacs-evil.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-evil-20180203.416/treemacs-evil-autoloads.el
Checking /home/vakosel/.emacs.d/elpa/treemacs-evil-20180203.416... [3 times]
Compiling /home/vakosel/.emacs.d/elpa/treemacs-evil-20180203.416/treemacs-evil.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-evil-20180203.416/treemacs-evil.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-evil-20180203.416...
Done (Total of 1 file compiled, 2 skipped)
Loading package treemacs-evil...done
Configuring package treemacs...done (0.498s)
Configuring package projectile...done
Compiling /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416/treemacs-projectile.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416/treemacs-projectile.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416...
Done (Total of 1 file compiled, 2 skipped)
Open the quickhelp.
Skipping check for new version (reason: dotfile)
Configuring package helm...done (0.142s)
mwheel-scroll: Beginning of buffer [15 times]
mwheel-scroll: End of buffer [2 times]
mwheel-scroll: Beginning of buffer
Mark set [4 times]

Extracting treemacs-20180221.1229/icons/rust.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/rust.png
Extracting treemacs-20180221.1229/icons/tags-leaf.xpm
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/tags-leaf.xpm
Extracting treemacs-20180221.1229/icons/image.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/image.png
Extracting treemacs-20180221.1229/icons/txt.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/txt.png
Extracting treemacs-20180221.1229/icons/c.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/c.png
Extracting treemacs-20180221.1229/icons/js.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/js.png
Extracting treemacs-20180221.1229/icons/dir_open.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/dir_open.png
Extracting treemacs-20180221.1229/icons/tags-closed.xpm
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/tags-closed.xpm
Extracting treemacs-20180221.1229/icons/haskell.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/haskell.png
Extracting treemacs-20180221.1229/icons/html.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/html.png
Extracting treemacs-20180221.1229/icons/css.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/css.png
Extracting treemacs-20180221.1229/icons/git.png
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons/git.png
Extracting treemacs-20180221.1229/treemacs-filewatch-mode.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-filewatch-mode.el
Extracting treemacs-20180221.1229/treemacs-visuals.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-visuals.el
Extracting treemacs-20180221.1229/treemacs-tags.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-tags.el
Extracting treemacs-20180221.1229/treemacs-async.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-async.el
Extracting treemacs-20180221.1229/treemacs-dirs-to-collapse.py
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-dirs-to-collapse.py
Extracting treemacs-20180221.1229/treemacs-macros.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-macros.el
Extracting treemacs-20180221.1229/treemacs-branch-creation.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-branch-creation.el
Extracting treemacs-20180221.1229/treemacs-tag-follow-mode.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-tag-follow-mode.el
Extracting treemacs-20180221.1229/treemacs-compatibility.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-compatibility.el
Extracting treemacs-20180221.1229/treemacs-mouse-interface.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-mouse-interface.el
Extracting treemacs-20180221.1229/treemacs-pkg.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-pkg.el
Extracting treemacs-20180221.1229/treemacs-follow-mode.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-follow-mode.el
Extracting treemacs-20180221.1229/treemacs-git-status.py
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-git-status.py
Extracting treemacs-20180221.1229/treemacs-structure.el
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-structure.el
Configuring package yasnippet...done
[yas] Check your `yas-snippet-dirs': /home/vakosel/.emacs.d/elpa/yasnippet-20180304.1607/snippets is not a directory
[yas] Check your `yas-snippet-dirs': ~/snippets is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
Configuring package highlight-parentheses...done
Configuring package auto-highlight-symbol...done
Configuring package elisp-slime-nav...done
Configuring package auto-compile...done
Configuring package company...done
Generating autoloads for treemacs-async.el...done
Generating autoloads for treemacs-branch-creation.el...done
Generating autoloads for treemacs-compatibility.el...done
Generating autoloads for treemacs-customization.el...done
Generating autoloads for treemacs-faces.el...done
Generating autoloads for treemacs-filewatch-mode.el...done
Generating autoloads for treemacs-follow-mode.el...done
Generating autoloads for treemacs-impl.el...done
Generating autoloads for treemacs-interface.el...done
Generating autoloads for treemacs-macros.el...done
Generating autoloads for treemacs-mode.el...done
Generating autoloads for treemacs-mouse-interface.el...done
Generating autoloads for treemacs-persist.el...done
Generating autoloads for treemacs-pkg.el...done
Generating autoloads for treemacs-structure.el...done
Generating autoloads for treemacs-tag-follow-mode.el...done
Generating autoloads for treemacs-tags.el...done
Generating autoloads for treemacs-visuals.el...done
Generating autoloads for treemacs.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-autoloads.el
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-async.el...
Configuring package avy...done
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-async.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-async.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229... [2 times]
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-branch-creation.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-branch-creation.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-compatibility.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-compatibility.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-customization.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-customization.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-faces.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-faces.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-filewatch-mode.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-filewatch-mode.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-follow-mode.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-follow-mode.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-impl.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-impl.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-interface.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-interface.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-macros.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-macros.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-mode.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-mode.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-mouse-interface.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-mouse-interface.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-persist.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-persist.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229... [2 times]
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-structure.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-structure.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-tag-follow-mode.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-tag-follow-mode.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-tags.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-tags.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-visuals.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs-visuals.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Compiling /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/treemacs.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229...
Checking /home/vakosel/.emacs.d/elpa/treemacs-20180221.1229/icons...
Done (Total of 18 files compiled, 2 skipped)
Contacting host: melpa.org:443 [2 times]
Generating autoloads for treemacs-projectile.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416/treemacs-projectile-autoloads.el
Checking /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416... [3 times]
Compiling /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416/treemacs-projectile.el...
Configuring package treemacs...
Generating autoloads for treemacs-evil.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-evil-20180203.416/treemacs-evil-autoloads.el
Checking /home/vakosel/.emacs.d/elpa/treemacs-evil-20180203.416... [3 times]
Compiling /home/vakosel/.emacs.d/elpa/treemacs-evil-20180203.416/treemacs-evil.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-evil-20180203.416/treemacs-evil.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-evil-20180203.416...
Done (Total of 1 file compiled, 2 skipped)
Loading package treemacs-evil...done
Configuring package treemacs...done (0.498s)
Configuring package projectile...done
Compiling /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416/treemacs-projectile.el...done
Wrote /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416/treemacs-projectile.elc
Checking /home/vakosel/.emacs.d/elpa/treemacs-projectile-20180203.416...
Done (Total of 1 file compiled, 2 skipped)
Open the quickhelp.
Skipping check for new version (reason: dotfile)
Configuring package helm...done (0.142s)
mwheel-scroll: Beginning of buffer [15 times]
mwheel-scroll: End of buffer [2 times]
mwheel-scroll: Beginning of buffer
Mark set [4 times]

So ? How can i download the 2.2. version from stable ??

**Comment by Alexander-Miller** [comment]
Never mind the version difference. Melpa stable is simply where explicitly tagged verions of packages are released - as opposed to the more common practice of being built straight from master. ht's 2.3 tag has not yet been released, so I need to say that treemacs needs 2.2, otherwise people who do use melpa stable cannot install treemacs. It's not relevant to you case.

At any rate I think I know what's wrong. You need to actually tell spacemacs that you want to use treemacs by adding it to `dotspacemacs-additional-packages`. The `use-package` is still needed, since that's where all the config is.

**Comment by vakosel** [comment]
Excellent . That did the trick. 
Keep up your good work and thank you.
