### ISSUE TITLE
treemacs--build-tree: Wrong type argument: listp, Traceback

### ISSUE THREAD

**Issue by iromise** [Alexander-Miller/treemacs#154]
environment:
- MAC OS 
- spacemacs

When I press `u` in the dir
```
shared
iromise
```

the above message appears.

**Comment by Alexander-Miller** [comment]
I need more details. Toggle the error after `M-x toggle-debug-on-error` and then post the entire stacktrace that shows up.

**Comment by iromise** [comment]
here is the detail

> Debugger entered--Lisp error: (wrong-type-argument listp Traceback)
  treemacs--create-branch("" 0 nil #<process Process Future>)
  treemacs--build-tree("")
  treemacs-uproot()
  funcall-interactively(treemacs-uproot)
  call-interactively(treemacs-uproot nil nil)
  command-execute(treemacs-uproot)

**Comment by Alexander-Miller** [comment]
Did some digging and probably found the issue. Should be fixed with the latest update.

**Comment by iromise** [comment]
Ok, Thanks a lot.

**Comment by iromise** [comment]
Already fixed.
