### ISSUE TITLE
Make current selection more visible

### ISSUE THREAD

**Issue by axelson** [Alexander-Miller/treemacs#156]
Is there a way to make the current selection more visible? I know I could probably change something globally on my theme but ideally I'd be able to change the selected row behavior for just treemacs. I mostly want to change the background color of the selected row. Currently there's very little contrast so it can be difficult to tell what node I'm currently on.

This is how it currently looks with the `.projectile` file selected (I'm using Spacemacs dev branch):

![screenshot 2018-03-08 09 27 37](https://user-images.githubusercontent.com/9973/37171998-ab15f502-22b3-11e8-8c7e-150648b09c19.png)

By the way thanks for Treemacs, I've been really enjoying it!

**Comment by Alexander-Miller** [comment]
The selected row is just hl-line-mode. If you can't see it in treemacs you cannot use hl-line-mode either - if that's something you care about.

As a solution for right now you can do this with a face of your choice:
`(add-hook 'treemacs-mode-hook (lambda () (setq-local hl-line-face 'region)))`

I will also put adding a proper treemacs face for it on my todo list. (That face will of course inherit from hl-line, so your theme needs to deal with it anway.)

**Comment by axelson** [comment]
I may be misunderstanding something but it looks like while that snippet does change the value of `hl-line-face` it doesn't appear that the face used for the highlighted line is `'region`. It still appears to be `'hl-line`.

I currently have this in my spacemacs `dotspacemacs/user-config`:

    (set-face-background 'hl-line "gray15")
    (add-hook 'treemacs-mode-hook (lambda () (setq-local hl-line-face 'region)))

But in the treemacs buffer when I run `M-x describe-face` the default is still set to `hl-line`. Am I missing something obvious?

**Comment by Alexander-Miller** [comment]
Ah, I tried the setq-local part in scratch, where it did work, but it looks like activation order matters. Setting the face does nothing if hl-line-mode has already created its overlay, which is what happens if you use a mode hook. 
Try this as a hook instead (with the right values for you):
```
(overlay-put hl-line-overlay 'face 'region)
(setq treemacs--selected-icon-background "#ff0000")
(--each treemacs--icons
  (progn
    (treemacs--set-img-property
     (get-text-property 0 'img-selected it)
     :background treemacs--selected-icon-background)
    (treemacs--set-img-property
     (get-text-property 0 'img-unselected it)
     :background treemacs--not-selected-icon-background)))
```

**Comment by Alexander-Miller** [comment]
A new feature is coming for a position indicator in the fringe over at https://github.com/Alexander-Miller/treemacs/issues/172.

**Comment by Alexander-Miller** [comment]
The fringe-indicator-mode has now landed in master https://github.com/Alexander-Miller/treemacs#fringe-indicator-mode. That should fix your visibility issue.

**Comment by axelson** [comment]
Thanks!
