### ISSUE TITLE
Redisplay ERROR

### ISSUE THREAD

**Issue by c0001** [Alexander-Miller/treemacs#157]
Hi maintainer:
 
I've found the *Message* buffer error information:
````
Error during redisplay: (jit-lock-function 25) signaled (wrong-type-argument number-or-marker-p nil) [2 times]
````
just  while I open treemacs during `M-x: treemacs` and without any other config for treemacs!

I test it on `emacs  -Q (or -q)` , this error still appear !

So I thought about it's the bug of treemacs with hoping your reply or fixing :)

Plattform:  
-  emacs: 25.2 & 25.3 & 27.0.050 
-  Operation system: win10 latest version for now.

**Comment by Alexander-Miller** [comment]
What `treemacs-version` are you on? I explicitly disabled `jit-lock-mode` back in january. 

If the issue persists with an updated treemacs you need to

 1)  `toggle-debug-on-error`
 2) reproduce the error
 3) provide the entire stacktrace that will hopefully show up

**Comment by c0001** [comment]
@Alexander-Miller 

I use the latest version of treemacs which is out of date in 2018/03/09 and the debug buffer doesn't appear to be shown up immediately with just *Message* buffer's error showing.

And be strange that emacs 27.0.50 be without this error again when I upgrade treemacs version.
Just in emacs 25 whole versions.

**Comment by c0001** [comment]
For upgrade this issue:

when the treemacs package installed from emacs 25.3 both 25 and 27 emacs shown this errror.

The state of none error of emacs 27 just when I install treemacs from emacs27 package manager.

Strange a lot :!

**Comment by Alexander-Miller** [comment]
> the debug buffer doesn't appear to be shown

Try again after enabling `jit-lock-debug-mode`.

**Comment by aaron0browne** [comment]
I'm having the same error show up and here is the output I get with `jit-lock-debug-mode` on:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  jit-lock--run-functions(1 245)
  jit-lock-fontify-now(1 245)
  jit-lock--debug-fontify()
  apply(jit-lock--debug-fontify nil)
  timer-event-handler([t 0 0 0 t jit-lock--debug-fontify nil idle 0])
```

Platform:
- Emacs 25.3
- macOS 10.8

**Comment by Alexander-Miller** [comment]
Looks like jit-lock-mode is different than other minor modes, and needs to be turned off with nil instead of -1. https://github.com/Alexander-Miller/treemacs/commit/cb40d3fe1a8f75567b47fb0597cda26937fbf06d should fix this issue.

**Comment by aaron0browne** [comment]
Aha! How annoying. Thanks for the fix!

**Comment by Alexander-Miller** [comment]
Is the error gone now?

**Comment by aaron0browne** [comment]
Yes, feel free to close.

**Comment by Alexander-Miller** [comment]
:+1:
