### ISSUE TITLE
Multiple Treemacs buffer and Eyebrowse switching window configs behaviour

### ISSUE THREAD

**Issue by xdl** [Alexander-Miller/treemacs#161]
I was wondering if it was possible for the following behaviour to be enabled/exposed as an option. If I have the following eyebrowse window configs open:

* treemacs buffer for project 1 | project 1 buffer
* treemacs buffer for project 2 | project 2 buffer

Switching between them will switch the buffers from project 1 to project 2, but whatever treemacs buffer is visible at the time stays the same. Is there any way for treemacs to detect that the window config has changed, and update its visible buffer to the one corresponding to that window config?

PS great package by the way, loving all the features you're putting out!

**Comment by Alexander-Miller** [comment]
No, that is currently not possible. Treemacs buffers are local to frames, so if you want 2 file trees for 2 projects you need to spawn a second frame. Additionally I am working on adding the option to display multiple projects at once - see #159. Coupled with `treemacs-follow-mode` that should be enough to cover your use-case.

If I do get around to implementing a different option for "scopes" it will be persp.el perspectives.

**Comment by xdl** [comment]
Just had a look at the screenshot for that feature and it looks awesome! That's great to hear, I'll be looking forward for its release :D

**Comment by Alexander-Miller** [comment]
The multiroot feature is done, I hope you have what you need now.
