### ISSUE TITLE
Trouble with installing

### ISSUE THREAD

**Issue by luciferasm** [Alexander-Miller/treemacs#162]
On GNU Emacs 25.3.1 I get the error message `package-install-from-archive: https://melpa.org/packages/treemacs-20180309.942.tar: Not found` when trying to install.

**Comment by luciferasm** [comment]
Thanks - `package-refresh-contents` did the trick! Sorry for taking up your time and not investigating it further myself, but I was under the impression that package management in Emacs had reached a level of maturity that it always 'just works' without the need of manual actions in order to ensure new versions etc. I therefore incorrectly suspected that there was an issue. Now I'll try out treemacs - it looks really promising!

**Comment by Alexander-Miller** [comment]
Unfortunately we're not there yet. 
You can try https://github.com/Malabarba/paradox, I think it updates the package list whenever you display the menu.
