### ISSUE TITLE
Ignore files in treemacs

### ISSUE THREAD

**Issue by jbharat** [Alexander-Miller/treemacs#164]
Can you please add .DS_Store to ignored files list. It is added to gitignore but treemacs does not seem to use gitignore.

**Comment by Alexander-Miller** [comment]
I don't think ignoring OS-specific files is something I should be doing by default. However you can easily tell treemacs to ignore specific files yourself, for example like this:
```
(with-eval-after-load 'treemacs
  (defun treemacs-ignore-gitignore (file _)
    (string= file ".gitignore"))
  (push #'treemacs-ignore-gitignore treemacs-ignored-file-predicates))
```

For details see docs of `treemacs-ignored-file-predicates`.

> It is added to gitignore but treemacs does not seem to use gitignore.

This is a necessary optimization. Asking files' git status runs asynchronously in a separate process while emacs itself is busy gathering, sorting and filtering the files it'll display. If you really want to hide all git-ignored files you can use `treemacs-pre-file-insert-predicates`.

**Comment by jbharat** [comment]
Thanks. The snippet worked. I dont want to hide all that is in .gitignore like build folder or node_modules as I might traverse it in treemacs, but showing .DS_Store is of no use. With the snippet provided I can hide specific files which should be good enough. Thanks again.

**Comment by ffffwh** [comment]
IMHO, .DS_Store somehow belongs to 'std-ignore-file'.

Different from other dotfile, it is of absolute no use, and deleting it makes no sense since it will be recreated by OS.

Yes it is OS-specific, but there seems to be only one such file for macOS.
