### ISSUE TITLE
Icons are too large

### ISSUE THREAD

**Issue by pangwa** [Alexander-Miller/treemacs#165]
It doesn't look quite good on my mbp..
![image](https://user-images.githubusercontent.com/927678/37860004-14483ae8-2f58-11e8-8ee3-99473261cd22.png)

**Comment by Alexander-Miller** [comment]
You'll need to wait for https://github.com/Alexander-Miller/treemacs/pull/163

**Comment by Alexander-Miller** [comment]
#163 is done and its kinks have been worked out. You can now interactively and instantly resize icons by calling `treemacs-resize-icons`.
