### ISSUE TITLE
Follow mode doesn't follow when file is in singly nested folder

### ISSUE THREAD

**Issue by troglotit** [Alexander-Miller/treemacs#166]
Should be like this: 
<img width="743" alt="image" src="https://user-images.githubusercontent.com/10955264/38424175-dfe16eda-39b8-11e8-82ee-27f2fe68e3bd.png">
but it is like this:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/10955264/38424189-ec8f28de-39b8-11e8-970d-1fd67c614002.png">

Adding empty file helps:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/10955264/38424212-fd11002e-39b8-11e8-9000-d775589b9bf4.png">

**Comment by Alexander-Miller** [comment]
I have good news and bad news. Good news is I've found cause of the bug and will have the fix soon enough. Bad news is that part of the code underwent some heavy refactoring on the dev branch as part of the multiroot effort and I don't think I've the time for such a non-trivial backport, so you'll need to wait until the multiroot feature is done.

Until that happens you have two options: install locally and use the multiroot branch. By now it is usable and stable. Or you can set `treemacs-collapse-dirs` to zero to disable the nesting feature.

**Comment by troglotit** [comment]
Awesome! I think I'll just wait. 🙂

**Comment by Alexander-Miller** [comment]
The multiroot branch is now integrated in master and should be on melpa soon. The bug should no longer occur then.

Another thing I noticed is that it looks like there's a cursor in the treemacs buffer in your screenshots. That should not happen, the cursor is supposed to be invisible. Are you running evil without treemacs-evil?

**Comment by troglotit** [comment]
I'm using treemacs layer in spacemacs. And it comes with treemacs-evil. And this thin line doesn't work or interfere like a cursor, so it doesn't bother me.

**Comment by troglotit** [comment]
Works as expected! 👏
