### ISSUE TITLE
How to expand and collapse all dirs / dir recursively?

### ISSUE THREAD

**Issue by yltozh** [Alexander-Miller/treemacs#167]
Do you know how to expand/collapse all dirs in a level? and also expand/collapse a dir recursively till its child?

**Comment by Alexander-Miller** [comment]
Recursive closing opening is done with the prefix arg, so C-u + TAB.

Not sure what you mean by your second question though. Can you give an example?

**Comment by Alexander-Miller** [comment]
Bump?

**Comment by Alexander-Miller** [comment]
Closing on account of inactivity. Feel free to reopen if you question isn't resolved.

**Comment by bk322** [comment]
`C-u Tab` was what I was looking for too, thanks.

**Comment by ludwignagelhus** [comment]
What is the name of the function?

**Comment by Alexander-Miller** [comment]
@ludwignagelhus Which function do you mean? If you want to know what's bound to a key you can always check with `C-h k`.

**Comment by ludwignagelhus** [comment]
The functions to recursively open/close. I guess I can just unbind my shadowing binding and then use `inspect-binding`.

**Comment by Alexander-Miller** [comment]
There is no dedicated function for recursive open/close. That behavior is triggered by a prefix arg, that's what the `C-u` is for. But the function is the usual `treemacs-TAB-action`.

**Comment by introom** [comment]
I am doing C-u treemacs-Tab-action.  But it is not opening recursively.

**Comment by introom** [comment]
Beside, it would be more friendly if C-u <num> treemacs-Tab-action controls the level of expansion based on the <num>

**Comment by Alexander-Miller** [comment]
> I am doing C-u treemacs-Tab-action. But it is not opening recursively.

Working as expected on my end. You can try using `trace-function` on `treemacs-TAB-action` to see if the prefix arg is passed properly. The output should look like this:

> ======================================================================
>1 -> (treemacs-TAB-action (4))
>1 <- treemacs-TAB-action: nil

> Beside, it would be more friendly if C-u treemacs-Tab-action controls the level of expansion based on the 

There's an issue for it in #441. I intend to implement this feature as part of #677

**Comment by introom** [comment]
Is this output expected?
![image](https://user-images.githubusercontent.com/669045/119261344-8e1e2580-bc09-11eb-9279-9f7ee247b892.png)

I'd anticipate subdirs such as android/ is also expanded.

**Comment by Alexander-Miller** [comment]
Recursive expansion was missing for projects. It's fixed now.

**Comment by lerouxrgd** [comment]
Is it actually possible to expand all root nodes ?

That would be particularly interesting for `lsp-treeemacs`  where you can have functions defined under "interface" nodes, such as in this screenshot:

![image](https://github.com/Alexander-Miller/treemacs/assets/6103291/2359a15f-4d58-4b04-8032-923ecc97ce34)
