### ISSUE TITLE
Add peek option 

### ISSUE THREAD

**Issue by fiveNinePlusR** [Alexander-Miller/treemacs#173]
When using helm there is a peek option using the `tab` key that lets you open up a buffer in the first window without losing focus in the helm buffer. It would be awesome to have this feature available in treemacs. the helm method leaves the buffer open in the background so it's an effective way to open up a bunch of buffers quickly. 

extending this to allow for treemacs to open the file in a buffer and also close that buffer if it hadn't been opened before would be an awesome option too. Pressing `p` could behave like `tab` in helm and `P` could automatically close the buffer if you do a different action like move the cursor or open up another file. Just copying the helm functionality would be great though.

**Comment by Alexander-Miller** [comment]
> lets you open up a buffer in the first window without losing focus in the helm buffer.

That should already be covered. The various opener functions will keep focus in treemacs when run with `C-u`. You can also scroll a window while staying in treemacs with `M-S-n/p` (or j/k).

The helm-like peeking sounds like a good idea. I'll put it on my todo list, though publishing and stabilizing the multiroot feature comes first.

**Comment by Alexander-Miller** [comment]
Just pushed the peek command, you can find it bound to P. Let me know if it covers your use case.

**Comment by fiveNinePlusR** [comment]
For anyone that want's that kind of behavior you can use this snippet unless @Alexander-Miller changes the api of the peek command. (evil mode, on a mac so the bindings might be a little off)

``` elisp
(defun my/treemacs-move-half-page-down ()
  "Scroll forward half a page in `next-window'."
  (interactive)
  (treemacs-without-following
   (with-selected-window (next-window)
     (evil-scroll-down 0))))

(defun my/treemacs-move-half-page-up ()
  "Scroll forward half a page in `next-window'."
  (interactive)
  (treemacs-without-following
   (with-selected-window (next-window)
     (evil-scroll-up 0))))
(define-key treemacs-mode-map (kbd "<s-down>")       #'my/treemacs-move-half-page-down)
(define-key treemacs-mode-map (kbd "<s-up>")       #'my/treemacs-move-half-page-up)

(defun treemacs--restore-peeked-window-advice-before ()
  "Advice to not call the peek cleanup unless it's needed"
  (memq this-command '(my/treemacs-move-half-page-up my/treemacs-move-half-page-down)))

(advice-add 'treemacs--restore-peeked-window :before-until 'treemacs--restore-peeked-window-advice-before)
```

**Comment by Alexander-Miller** [comment]
There's really no such thing as a reusable buffer. Every time you open a file you get a new buffer, so your first proposal really amounts to killing the previously opened buffer if you peek again.

I'd rather go with the pagewise scrolling. I'll add two more commands that scroll other-window by the page, in line with the current line-wise scrolling.

**Comment by fiveNinePlusR** [comment]
sounds like a plan. thanks!

**Comment by Alexander-Miller** [comment]
Pagewise scrolling is on master now.
