### ISSUE TITLE
cannot exit emacs

### ISSUE THREAD

**Issue by hyOzd** [Alexander-Miller/treemacs#177]
I cannot exit emacs. I get an error about treemacs persistence file. I can only exit emacs with `kill -9`.

```
f-write-bytes: Opening output file: No such file or directory, /home/user/.emacs.d/.cache/treemacs-persist
```

This is my treemacs configuration:
```
(use-package treemacs
  :config
  (use-package treemacs-projectile)
  (setq treemacs-show-hidden-files nil)
  (global-set-key (kbd "C-c C-t") 'treemacs))
```

I've tried isolating this configuration and issue still happens. Emacs 25.3.2.

**Comment by Alexander-Miller** [comment]
Found the problem, `f-write` will error when a directory, like .cache in your case, does not exist. I've fixed this in https://github.com/Alexander-Miller/treemacs/commit/52159c270092649d9ae4421e5c82afa30ffe23e2, just need to wait for melpa to build.

**Comment by Alexander-Miller** [comment]
I hope this issue is fixed now?

**Comment by hyOzd** [comment]
@Alexander-Miller Just tested. it's fixed.

**Comment by Alexander-Miller** [comment]
Great.
