### ISSUE TITLE
Python function tag nodes should be openable

### ISSUE THREAD

**Issue by WJCFerguson** [Alexander-Miller/treemacs#179]
When a python function contains other nested functions, it should be possible to open the tag directly, rather than having to expand it and then move to "*function definition*".

Thanks.

**Comment by Alexander-Miller** [comment]
I can try to make this work, but reliability may be dodgy. Internally a nested function in imenu looks like this:
```
("foo (def)"
   ("*function definition*" . #<marker at 2463 in treemacs-git-status.py>)
   ("bar (def)" . #<marker at 2463 in treemacs-git-status.py>))
```
I'll only know I'm looking at something I can move to when the first child element is the definition. That format might change when imenu gets its tags from somewhere else (like ggtags).

**Comment by Alexander-Miller** [comment]
I have now introduced 2 cases where RET's (but not TAB's) default config will visit a tag section node instead of expanding it:
 * It's a .py file and the tag section's first child's text ends in " definition*"
 * .org files in general since headlines usually have sub-headlines below them.
