### ISSUE TITLE
file quick look

### ISSUE THREAD

**Issue by xin-jin** [Alexander-Miller/treemacs#181]
Is there a feature like neotree's `neotree-quick-look`? That is, view a file without moving focus to that file (focus is still on treemacs).

Thanks.

**Comment by Alexander-Miller** [comment]
Yes, treemacs can do that. If you run any of the file opening commands with a prefix argument the focus will remain in treemacs. You can also scroll the window next to treemacs without losing focus with M-S-n/p or M-S-j/k with evil.
