### ISSUE TITLE
Treemacs is not working?

### ISSUE THREAD

**Issue by SharryXu** [Alexander-Miller/treemacs#182]
Hello, everyone and I am sorry to disturb you guys but I've encounter a very urgent issue that I need to fix. When I try to open the treemacs by typing `SPC f T` in my spacemacs, I got message like this **command-execute: Wrong type argument: commandp, treemacs-toggle** and an empty buffer was created on the original position. By the way, I was using the latest package which I updated in this morning. [Here](https://gist.github.com/SharryXu/e834a2490a2e829350b9109a874eb662) is my configuration. I will be very grateful if someone can help me to figure this out. 😄

**Comment by Alexander-Miller** [comment]
The short version is that treemacs had a major update and that command simple no longer exists. The long version [you can read here](https://github.com/syl20bnr/spacemacs/issues/10432). 

Updating the layer is on my current todo list.

**Comment by SharryXu** [comment]
@Alexander-Miller Thank you so much 👍 and I am very appreciate your hard work. 😄
