### ISSUE TITLE
`treemacs` command clarification - should it toggle?

### ISSUE THREAD

**Issue by xdl** [Alexander-Miller/treemacs#183]
When trying to use`treemacs` as the new replacement for `treemacs-toggle` (as its description is `Show/Hide/Initialize treemacs`), I noticed it doesn't hide the treemacs pane, only shows or initialises it - is this a bug or does the readme need to be updated? Either way, it would be nice to have some sort of toggling command exposed again!

**Comment by Alexander-Miller** [comment]
That's a bug, looks like I misused `bury-buffer`. Patch is pushed now.

**Comment by xdl** [comment]
Nice one!

**Comment by Alexander-Miller** [comment]
Pushed another small fix. Toggling behaviour should now work correctly in all cases.
