### ISSUE TITLE
treemacs-select-window bug

### ISSUE THREAD

**Issue by mpanarin** [Alexander-Miller/treemacs#185]
if run before regular `treemacs` function during the session it bugs out and doesn't open the treemacs window.
If you use `treemacs` first then select window will work as expected. Missed some kind of initialization?

**Comment by Alexander-Miller** [comment]
That's a bug. It'll be fixed with https://github.com/Alexander-Miller/treemacs/commit/b671bc6adb023ea0a82b44cdea66261b56161367, just need to wait for melpa.

**Comment by mpanarin** [comment]
resolved in latest update
