### ISSUE TITLE
does treemacs support file locate？

### ISSUE THREAD

**Issue by lianzisong** [Alexander-Miller/treemacs#187]
it's frustrating to find a wanted file in a huge file count .
but I can not find a easy way to do it .
Can treemacs support it?
or at least , can treemacs unpack all the folded folder then list all files in the root dir , and I can use the build-in search function.

**Comment by Alexander-Miller** [comment]
> can treemacs unpack all the folded folder

Closing/opening files recursively is done with the prefix arg.

> Can treemacs support it?

Do you mean something like selecting a file you want to see in treemacs with your standard selection framework like helm/ivy/ido?

**Comment by lianzisong** [comment]
almost .

here is the example:
I have the 100 files in my treemacs list.
then I want to find a file whose name is so long that i can't remember the whole filename ,like abcdefg .eg.
and  I want to open it by type some command then type <cdef> then it show the "abcdefg" to me by some way.

it's that possible for treemacs?

**Comment by Alexander-Miller** [comment]
Not possible yet, but I'll make the necessary changes.

**Comment by Alexander-Miller** [comment]
I have now updated `treemcs-find-file` so that it will ask for the file you want to find when you call it with a prefix argument or if the buffer it's called from - like the treemacs buffer - does not visit any file.
