### ISSUE TITLE
Follow mode breaks if you open file that is ignored via treemacs-ignored-file-predicates

### ISSUE THREAD

**Issue by yyoncho** [Alexander-Miller/treemacs#191]
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  #f(compiled-function (btn dir-parts) "BTN Follow (goto and open) every single dir in DIR-PARTS under ROOT.\nReturn the button that is found or the symbol 'follow-failed' if the search\nfailed." #<bytecode 0x49c12d5>)(#<marker at 17 in  *Treemacs-Framebuffer-1*> (".gitignore"))
  treemacs-goto-button("{filepath}/.gitignore" #s(treemacs-project :name "clojure-app-config" :path "/home/kyoncho/.clojure/clojure-app-config"))
  treemacs--follow()
  treemacs--select-window-advice(#<window 6 on .gitignore> norecord)
  apply(treemacs--select-window-advice (#<window 6 on .gitignore> norecord))
  select-window(#<window 6 on .gitignore> norecord)
  which-func-update-1(#<window 6 on .gitignore>)
  which-func-update()
  apply(which-func-update nil)
  timer-event-handler([t 0 0 500000 t which-func-update nil idle 0])

**Comment by Alexander-Miller** [comment]
https://github.com/Alexander-Miller/treemacs/commit/727c9a92a0a49d5676a8fbc981744a82297c1a1a should take care of that. Please verify on your end.

**Comment by yyoncho** [comment]
Synched to the latest melpa version(20180508.512) and I am receiving the following error:

Debugger entered--Lisp error: (error "‘recenter’ing a window that does not display current-buffer.")
  recenter()
  treemacs--maybe-recenter()
  treemacs--follow()
  treemacs--select-window-advice(#<window 6 on description> norecord)
  apply(treemacs--select-window-advice (#<window 6 on description> norecord))
  select-window(#<window 6 on description> norecord)
  internal--after-save-selected-window((#<window 6 on description> (#<frame emacs 0x13056f0> . #<window 6 on description>)))
  #f(compiled-function () #<bytecode 0x20ca32d>)()
  walk-windows(#f(compiled-function (window) #<bytecode 0x20ca2fd>) 1 t)
  window--process-window-list()
  window--adjust-process-windows()
  #<subr set-window-buffer>(#<window 6 on description> #<buffer description> nil)
  ad-Advice-set-window-buffer(#<subr set-window-buffer> #<window 6 on description> #<buffer description>)
  apply(ad-Advice-set-window-buffer #<subr set-window-buffer> (#<window 6 on description> #<buffer description>))
  set-window-buffer(#<window 6 on description> #<buffer description>)
  (while (consp --cl-var--) (setq buffer (car --cl-var--)) (if (>= num-buffers-placed num-windows) (progn cl-return)) (set-window-buffer (winum-get-window-by-number cur-win) buffer) (setq cur-win (+ 1 (mod cur-win num-windows))) (setq num-buffers-placed (1+ num-buffers-placed)) (setq --cl-var-- (cdr --cl-var--)))
  (let* ((--cl-var-- buffers) (buffer nil)) (while (consp --cl-var--) (setq buffer (car --cl-var--)) (if (>= num-buffers-placed num-windows) (progn cl-return)) (set-window-buffer (winum-get-window-by-number cur-win) buffer) (setq cur-win (+ 1 (mod cur-win num-windows))) (setq num-buffers-placed (1+ num-buffers-placed)) (setq --cl-var-- (cdr --cl-var--))) nil)
  (let ((num-buffers (length buffers)) (num-windows (length (winum--window-list))) (cur-win (winum-get-number)) (num-buffers-placed 0)) (let* ((--cl-var-- buffers) (buffer nil)) (while (consp --cl-var--) (setq buffer (car --cl-var--)) (if (>= num-buffers-placed num-windows) (progn cl-return)) (set-window-buffer (winum-get-window-by-number cur-win) buffer) (setq cur-win (+ 1 (mod cur-win num-windows))) (setq num-buffers-placed (1+ num-buffers-placed)) (setq --cl-var-- (cdr --cl-var--))) nil))
  spacemacs//helm-open-buffers-in-windows((#<buffer description>))
  (let* ((files (helm-marked-candidates)) (buffers (mapcar 'find-file-noselect files))) (spacemacs//helm-open-buffers-in-windows buffers))
  (lambda (candidate) (let* ((files (helm-marked-candidates)) (buffers (mapcar 'find-file-noselect files))) (spacemacs//helm-open-buffers-in-windows buffers)))("/home/kyoncho/Sources/tick42-gds/.git/description")
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal(helm-source-find-files "/home/kyoncho/Sources/tick42-gds/.git/" "Find files or url: " nil nil "*helm find files*" nil "/home/kyoncho/Sources/tick42-gds/.git/description" nil)
  apply(helm-internal (helm-source-find-files "/home/kyoncho/Sources/tick42-gds/.git/" "Find files or url: " nil nil "*helm find files*" nil "/home/kyoncho/Sources/tick42-gds/.git/description" nil))
  helm(helm-source-find-files "/home/kyoncho/Sources/tick42-gds/.git/" "Find files or url: " nil nil "*helm find files*" nil "/home/kyoncho/Sources/tick42-gds/.git/description" nil)
  apply(helm (helm-source-find-files "/home/kyoncho/Sources/tick42-gds/.git/" "Find files or url: " nil nil "*helm find files*" nil "/home/kyoncho/Sources/tick42-gds/.git/description" nil))
  helm(:sources helm-source-find-files :input "/home/kyoncho/Sources/tick42-gds/.git/" :case-fold-search smart :preselect nil :ff-transformer-show-only-basename t :default "/home/kyoncho/Sources/tick42-gds/.git/description" :prompt "Find files or url: " :buffer "*helm find files*")
  helm-find-files-1("/home/kyoncho/Sources/tick42-gds/.git/")
  (let* ((hist (and arg helm-ff-history (helm-find-files-history))) (default-input hist) (input (cond ((and (eq major-mode 'dired-mode) default-input) (file-name-directory default-input)) ((and (not (string= default-input "")) default-input)) (t (expand-file-name (helm-current-directory)))))) (set-text-properties 0 (length input) nil input) (helm-find-files-1 input))
  spacemacs/helm-find-files(nil)
  funcall-interactively(spacemacs/helm-find-files nil)
  call-interactively(spacemacs/helm-find-files nil nil)
  command-execute(spacemacs/helm-find-files)

**Comment by Alexander-Miller** [comment]
Should be taken care of.
