### ISSUE TITLE
treemacs window is sometimes deleted by delete-other-windows

### ISSUE THREAD

**Issue by perweij** [Alexander-Miller/treemacs#195]
treemacs-multiroot 7ed48f0547f1e7d252b1f992539d39e5d0af1c86

After having used the new multiroot branch a few hours, I noticed that the treemacs window sometimes gets deleted by delete-other-windows. I have yet to find a way to reliably recreate it.

**Comment by Alexander-Miller** [comment]
It shouldn't be sometimes, but always. Treemacs has no special protection against being deleted in this manner. I don't know why it appears inconsistent for you. 

You'll probably want to use `treemacs-delete-other-windows` instead, which works the same as `delete-other-windows`, except that it makes sure treemacs sticks around. You should also update to https://github.com/Alexander-Miller/treemacs/commit/ab8dbe8a84dfbaaae9c4057b3ae9c9dbe94a84e3 to it'll properly handle the case of being called when treemacs is selected.

**Comment by perweij** [comment]
Thanks - I had a broken display-buffer-alist which was interfering. Closing.
