### ISSUE TITLE
treemacs-no-png-images doesnt work after upgrade

### ISSUE THREAD

**Issue by matthemsteger** [Alexander-Miller/treemacs#200]
I upgraded to the latest treemacs and I can't seem to get treemacs-no-png-images to work. I liked the scaled back no images look and prefer that to the large icons.

Maybe I am just misconfigured? I could not see how.

Install version ..

```
treemacs           20180522.1231 installed             A tree style file explorer package
treemacs-projec... 20180508.112  installed             Projectile integration for treemacs
```

.emacs

```elisp
(use-package treemacs
  :ensure t
  :defer t
  :config
  (progn
	(setq treemacs-no-png-images t)
	(setq treemacs-icon-fallback-text (propertize "> " 'face 'font-lock-keyword-face)))
  :bind
  (:map global-map
		([f8] . treemacs)))
(use-package treemacs-projectile
  :after treemacs projectile
  :defer t
  :ensure t)
```

describe-variable
```
treemacs-no-png-images is a variable defined in ‘treemacs-customization.el’.
Its value is t
Original value was nil

Documentation:
When non-nil treemacs will use TUI string icons even when running in a GUI.

You can customize this variable.
```

**Comment by Alexander-Miller** [comment]
Nope, that's definitely a bug. Looks like I mistakenly removed this variable's use during the version2 transition.

I'll put this on the top of my todo list.

**Comment by Alexander-Miller** [comment]
Just pushed the fix. Changes to `no-png-images` will now correctly apply when a treemacs buffer is created.

**Comment by gavocanov** [comment]
Project icons are still visible, the rest seems fine to me.

**Comment by Alexander-Miller** [comment]
My bad, I forgot to include the new project icons in the no-png feature. This should be fixed with today's updates.
