### ISSUE TITLE
How to inform treemacs about .gitignore?

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#202]

**Comment by Alexander-Miller** [comment]
I assume you don't want to see gitignored files. If so take a look at the docs of `treemacs-pre-file-insert-predicates`.

**Comment by Alexander-Miller** [comment]
I've now added an FAQ entry about hiding gitignored files.

I hope that answers your question.

**Comment by Compro-Prasad** [comment]
Thanks a lot. The documentation of treemacs is pretty comprehensive. Thought I will need to look at it some other day carefully. Haven't checked documentation of every function and variable . But I have seen many undocumented variables and functions. The package authors might think it is an internal variable or self explanatory. What I believe is that they should change their thinking.

**Comment by Alexander-Miller** [comment]
> But I have seen many undocumented variables and functions.

Such as?

**Comment by Compro-Prasad** [comment]
treemacs-current-workspace
