### ISSUE TITLE
wrong emacs dependencies in Melpa and Melpa stable

### ISSUE THREAD

**Issue by PeterChristoph** [Alexander-Miller/treemacs#208]
The current melpa version 20180607.1141 and melpa-stable version 2.1 has emacs 24.4 as a dependency even though support is dropped for 24.4 in these versions of treemacs.

As a result, package managers can update treemacs on 24.4 to versions that do not work there due to changes in pcase.

**Comment by Alexander-Miller** [comment]
Thanks for the heads up.
