### ISSUE TITLE
treemacs-git-mode does not work with symbolic links

### ISSUE THREAD

**Issue by iboyperson** [Alexander-Miller/treemacs#210]
Example:
I have my .emacs.d in a directory for dotfiles and it is linked to my home directory. When I open the symbolic link it does not show the git status and does not hide gitignored items (I configured it to do so).
However, when I go to the actual directory the link points to this all works.

**Comment by Alexander-Miller** [comment]
Today I learned that symlinks and git make for a really annoying 
combination ...

Complaints aside I should be able to make this work soon enough.

**Comment by Alexander-Miller** [comment]
Patch is pushed. You should also read the fine print in the patch notes.
