### ISSUE TITLE
Manage multiple workspaces

### ISSUE THREAD

**Issue by nlamirault** [Alexander-Miller/treemacs#213]
I try the new feature of workspaces and multiple projects : congrats :+1: 
But even more interesting would be to be able to manage several workspaces and to be able to choose among them. (Like in vscode)
Do you plan to add this feature ?

**Comment by Alexander-Miller** [comment]
Yes, doing something with workspaces is a longer-term goal of mine.

**Comment by Alexander-Miller** [comment]
I've created a proper epic to discuss the future of workspaces at https://github.com/Alexander-Miller/treemacs/issues/247, this conversation should continue over there.

@dakra That is a good idea, I'll make it part of the implementation.
