### ISSUE TITLE
Treemacs don't show anything after type "h" couple of times

### ISSUE THREAD

**Issue by metinUr** [Alexander-Miller/treemacs#219]
I type 'h' couple of times (and maybe type enter I don't remember well) than every folders and files gone.

it looks like this now
![deepinscreenshot_select-area_20180620171719](https://user-images.githubusercontent.com/17551688/41664223-e4344a68-74ad-11e8-93dd-5a444d733609.png)

I tried to delete project then it return this.
`[Treemacs] There is no project here.`

I tried to add new projects then it return this.
`[Treemacs] Project for /home/m1311/Projects/Project already exists.`

Then remove treemacs and install again and result is same. Is there a config file that hold some changes and not deleting when remove treemacs.

How can I fix this or delete entirily and install like first time.

**Comment by Alexander-Miller** [comment]
There was a bug in how the project's name is determined when moving the project. It should be fixed now.
