### ISSUE TITLE
Scrolling up and down with visual-line-mode disabled

### ISSUE THREAD

**Issue by jojojames** [Alexander-Miller/treemacs#22]
Since the cursor is popping to the end when you scroll up or down, if there are long lines bigger than the window, the UI will pop back and forth making it hard to read the text. It might be more better to have the cursor go to the beginning of the text (after the image but on the text).

**Comment by Alexander-Miller** [comment]
That one's already fixed as of https://github.com/Alexander-Miller/treemacs/commit/535ea5afa118b8d378c1d464803f668cd24211d6
You only need to update.

**Comment by jojojames** [comment]
Oh, cheers! I thought I was already on the latest. Guess there's been a few updates since then.

Thanks!
