### ISSUE TITLE
Integration with magit

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#223]
`filewatch-mode` is currently blind to events that do not produce any changes on the file system level, but should be picked up anyway. Namely commit and staging commands in conjunction with git-mode.

There's not much I can do when this is done from the command line, however magit, as discussed in https://github.com/magit/magit/issues/3496, offers an interface for treemacs to hook into, so it can be made aware of these operations.

The hooks will require a few bits of non-trivial code, so it would be best to publish them in a specialized treemacs-magit package which has a hard dependency on magit and with-editor.

Implementation details: The magit hooks should make use of the existing filewatch-mode callback mechanisms and act as if they were producing events in the same form as a genuine filesystem change. That will ensure a seamless integration with the already present filewatch setup and settings.

**Comment by Juan-Cortez3** [comment]
Hi, Alex
I just copied the configuration in the **Installation** section of your README.md. But got the message like:
> Warning (bytecomp): reference to free variable ‘treemacs--collapsed-filewatch-index’
Warning (bytecomp): reference to free variable ‘treemacs--filewatch-index’
Warning (bytecomp): reference to free variable ‘treemacs--refresh-timer’
Warning (bytecomp): assignment to free variable ‘treemacs--refresh-timer’
Error (bytecomp): Cannot open load file: No such file or directory, magit
after a `emacs --debug-init`


I noticed that in the file `treemacs/src/elisp/treemacs-magit.el`, there is a `(require 'magit)`.
I think maybe it is better if you add `magit` to the **Dependencies** section of your README.md file

**Comment by Alexander-Miller** [comment]
> Warning (bytecomp)

I don't know where these come from. Both local flycheck and the CI build are clean on my end.

> I think maybe it is better if you add magit to the Dependencies section of your README.md file

That'll happen once treemacs-magit is out of the unfinished prototype phase and properly published on melpa. That'll happen soon enough, but for now it's not a module that you're supposed to load and use.

**Comment by Juan-Cortez3** [comment]
OK, looking forward to the coming release &#128515;

**Comment by Alexander-Miller** [comment]
Looks like I forgot to close here.

**Comment by Juan-Cortez3** [comment]
:-)
