### ISSUE TITLE
Hardcoded icon length in treemacs--button-symbol-switch

### ISSUE THREAD

**Issue by hlissner** [Alexander-Miller/treemacs#229]
I'd like to set `treemacs-icon-open` to a string longer than 2 characters, however, `treemacs--button-symbol-switch` hardcodes the expected length of icon strings to 2:

```elisp
;; treemacs-impl.el -- line 223
(defsubst treemacs--button-symbol-switch (new-sym)
  "Replace icon in current line with NEW-SYM."
  (save-excursion
    (goto-char (- (button-start (next-button (point-at-bol) t)) 2))
    (insert new-sym)
    (delete-char 2)))
```

Causing extra, leading characters to remain on consecutive expansion/collapsing of nodes:

![image](https://user-images.githubusercontent.com/510883/42387604-129acbc4-8143-11e8-82a7-03850018b22f.png)

And because `treemacs--button-symbol-switch` is inlined _and_ is used in macros that are expanded during byte-compile, it cannot be easily advised.

Is there any reason the length isn't determined dynamically?

```elisp
  (defsubst treemacs--button-symbol-switch (new-sym)
    "Replace icon in current line with NEW-SYM."
    (save-excursion
      (let ((len (length new-sym)))
        (goto-char (- (button-start (next-button (point-at-bol) t)) len))
        (insert new-sym)
        (delete-char len))))
```

**Comment by Alexander-Miller** [comment]
> Is there any reason the length isn't determined dynamically?

Haven't had a reason yet, that's about it. I had a great idea once to determine the icon's position by means of text properties, but then I remembered that I won't have a `'display` property in the terminal, so I gave that up.

Your proposal will also blow up when the old and the new icon have a different length, but I doubt that's a likely scenario, so I'll push your change now.

Also you shouldn't have to resort to using advice to adapt treemacs to your needs. I am quite open to changes and enhancements like this (unless they touch performance, then I get paranoid).
