### ISSUE TITLE
Why depend on ace-window?

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#231]

**Comment by Compro-Prasad** [comment]
Oh, I get it now. I don't understand why you want to depend on other packages. Because treemacs breaks if ace-window breaks. More importantly it would be better for an user like me to just use a sidebar, because I use switch-window and not ace-window.

**Comment by Compro-Prasad** [comment]
Its not good to invent the wheel when we have cars. But it would be nice if there was both a switch-window and ace-window integration.

**Comment by Alexander-Miller** [comment]
ace-window is one of the oldest dependencies, back then I figured it's 
not worth it extracting it into its own package. I still don't think it 
is. The `visit-ace` functions are probably used quite rarely, if I make 
them an optional dependency they'll probably go unused.

As for `switch-window`, IIRC there was something I didn't like about it 
back then, so I went with just ace.

I understand where you're coming from wanting to use your favored 
package, but I am not sure about the right way to make that change. 
Maybe a `treemacs-select-window-for-visit` variable that you can set to 
#'switch-window?
