### ISSUE TITLE
RET action not used when cursor is on node text

### ISSUE THREAD

**Issue by sdwolfz** [Alexander-Miller/treemacs#232]
Running emacs (with spacemacs) in a terminal, when on the treemacs window, if I have the cursor at the beginning of the line and press `RET` then `treemacs-RET-action` gets executed. But if I move the cursor on the node text, then `RET` is bound to `push-button` and pressing it does not result in any action (can not expand directories or open files).

The cursor ends up on the text when navigating with `M-j`/`M-k` or when searching with `evil-ex-search-forward` (pressing `/` in evil).

What I would expect is that `treemacs-RET-action` to be bound to `RET` in that case as well.

![push-button](https://user-images.githubusercontent.com/3746963/42539476-e1d07764-84a3-11e8-8f2f-28d2e05598bb.png)

**Comment by Alexander-Miller** [comment]
Looks like keymaps may even be stored in text properties. Disabling those should be easy enough, a patch will come soon.

**Comment by Alexander-Miller** [comment]
Fix is pushed. You may also want to have a look at the new `deferred` git-mode variant.

**Comment by sdwolfz** [comment]
The fix works perfectly, thanks!
