### ISSUE TITLE
Deferred git updates

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#233]
The next attempt at improving the performance of git-mode by deferring the fontification, except this time it's going to work. I know that because by now the biggest part that's left for me to do is to write the docs and update the spacemacs layer.

The secret to success is putting the fontification on an idle timer. That guarantees fast rendering and gives the git process even more time to finish. Splitting the work also makes is less perceptible to the user.

The issue of deferred fontification causing an ugly blink effect can be solved by caching the previous git state results and using that cache in the first render run.

**Comment by sdwolfz** [comment]
I tried out the deferred git mode from 6c9d35b58d7f08ff38b953eb21f59b544d885e0b a bit. It changes the color of the file node when I modify a line, but it does not change the color back when I undo. Also, only the file node's color gets changed, and the parent nodes stay the same, until I do a `gr` or open/close the root node.

**Comment by Alexander-Miller** [comment]
First of all thanks for taking the time to test the new stuff. Looks like you've run into 2 separate issues.

> it does not change the color back when I undo

That's on git-mode. Unsurprisingly enough asynchronising the git highlighting process has introduced a synchronisation issue w.r.t the re-use of the git process results. Should be a quick fix.

> the parent nodes stay the same, until I do a gr or open/close the root node

That's not a problem with git-mode as such, but an older filewatch-mode limitation. The short story is that it always updates the deepest directory with changes, to do as little work as possible. (The long story with all the nuts and bolts is described in #226.) This has the unfortunate side-effect of leaving wrong colors around when an edit would change the state of its parent nodes. I'll get to fixing this when [this pfuture expansion](https://github.com/Alexander-Miller/pfuture#callback-version) is done.

**Comment by Alexander-Miller** [comment]
I'll opened a dedicated issue to track that update issue in #385.
