### ISSUE TITLE
visual-line-mode conflict

### ISSUE THREAD

**Issue by ambihelical** [Alexander-Miller/treemacs#24]
If visual-line-mode is on, wrapped lines have an additional icon and look bad.  This is easily fixed outside the package by turning off visual-line-mode via treemacs-mode-hook, but perhaps treemacs should handle this mode better, or at least turn it off itself.

**Comment by Alexander-Miller** [comment]
Oh wow, emacs' text properties can get really funky.

Should be fixed in https://github.com/Alexander-Miller/treemacs/commit/bbff57809095f4fb8578ca9ee28a3bac81f203b0. Let me know if it works for you.

**Comment by ambihelical** [comment]
Works great.
