### ISSUE TITLE
follow-mode no longer works if I open the file under a symlink to the real project

### ISSUE THREAD

**Issue by andrmuel** [Alexander-Miller/treemacs#240]
E.g. I have a project
`/path/to/project` (known to treemacs under this path)
with files
`/path/to/project/foo`
`/path/to/project/bar`

And a symlink `/alternate/path/to/project` to `/path/to/project` (symlink also resides on a different partition). When I open `/alternate/path/to/project/foo` and go to `/alternate/path/to/project/bar`, follow-mode will not update treemacs.

Admittedly a rare use case and easy to work around by just opening via the real path (once I realized what the problem is), but I think some strategically placed uses of `file-truename` might fix it.

**Comment by andrmuel** [comment]
Hello Alexander

Sorry for the lack of clarity, but no, actually I only have the real path without symlink as project in treemacs (so I guess the same situation you would get from following the symlink on project creation). I guess treemacs currently considers the symlink to the project dir as separate project. Not too surprising now that I think about it ...

I'm not sure if that fully makes sense, but if you're going to implement following symlinks on project creation, maybe you could also resolve symlinks for follow-mode.

**Comment by Alexander-Miller** [comment]
Are your files under version control? `vc-follow-symlinks` should solve your problems in that case. It's also why I never noticed this issue - 99% of my own symlinks I ever open lead to my dotfiles.

At any rate I've made sure that symlinks will be resolved before following.

**Comment by andrmuel** [comment]
The symlink is in this case not under version control or to a file under version control, but rather to the directory containing the .git directory; I think in that case, `vc-follow-symlinks` has no effect. I have enabled it anyway just to be sure.

Thanks a lot for your quick reaction and improvements (and for treemacs in general)!
