### ISSUE TITLE
Feature request expand all nodes in project tree

### ISSUE THREAD

**Issue by larebsyed** [Alexander-Miller/treemacs#243]
A feature request to expand all node under a node. In order to search in tree all nodes should be visible

**Comment by Alexander-Miller** [comment]
That's already possible. You can expand everything - or forget everything expanded - under a node by opening or closing it with a prefix argument.

This isn't the first time I've had this question, so I'll add it to the FAQ.

**Comment by larebsyed** [comment]
Sorry for asking this again, thank you for your help. You should add that to docs
