### ISSUE TITLE
Each "h" key press moves project root directory up one level

### ISSUE THREAD

**Issue by lustrousgorilla** [Alexander-Miller/treemacs#248]
<img width="265" alt="screen shot 2018-07-28 at 2 27 38 pm" src="https://user-images.githubusercontent.com/8507140/43360776-767fce24-9272-11e8-9d34-eb55e60615ae.png">

<img width="264" alt="screen shot 2018-07-28 at 2 27 45 pm" src="https://user-images.githubusercontent.com/8507140/43360778-7a311c1c-9272-11e8-8335-ba0ee7538257.png">

<img width="242" alt="screen shot 2018-07-28 at 2 27 51 pm" src="https://user-images.githubusercontent.com/8507140/43360779-7d43cad0-9272-11e8-8fd3-d5d01d3e16fb.png">

... and so on until the root of the filesystem is reached.

This seems like it might be related to #219 (?). I'm running the most current releases as of today 7/28: Emacs 26.1, Spacemacs 0.200.13.x (in `holy-mode`, not `evil-mode`), and Treemacs 20180724.537 on macOS.

**Comment by Alexander-Miller** [comment]
This is actually working as intended, see https://github.com/Alexander-Miller/treemacs/issues/176. I just need to finally document it.

What's your reason for wanting to press h anyway? Does it have something to do with the cursor being visible (I guess that blue square is your cursor), which is very much a bug? The only way I know how to get a visible cursor in treemacs is to use evil without loading treemacs-evil.

**Comment by lustrousgorilla** [comment]
Oh, fantastic! Now that I know I can reverse it with "l" all is good. I think I fat-fingered the "h" while doing an incremental search (to jump down to a file inside a large directory), noticed and subsequently reproduced the behavior, and then since I didn't see "h" documented and found #219 I assumed the behavior was unintentional.

Hm, my cursor has been visible the whole time - maybe it's because I'm using `holy-mode`?

**Comment by Alexander-Miller** [comment]
Treemacs' stance on the cursor issue is [pretty clear](https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-mode.el#L277). Holy-mode shouldn't be overwriting it either. If you're fine with it being visible that's ok too, but I'd appreciate it if you could do some debugging, try evil, or a default config and see where that goes. I'd rather not keep such bugs around.

**Comment by Alexander-Miller** [comment]
:man_shrugging:
