### ISSUE TITLE
some requests :D

### ISSUE THREAD

**Issue by nasoundead** [Alexander-Miller/treemacs#25]
1.  Can provide an function like neotree-quick-look? When browsing the file tree, just keep in treemacs you can quick look the file.
2.  Support all-the-icon, it looks beautiful.

**Comment by Alexander-Miller** [comment]
> Can provide an function like neotree-quick-look? 

It'll be a while until I get around to it - I'm currently working on showing imenu tags, which is quite a piece of work - but this is on my TODO list.

> Support all-the-icon, it looks beautiful.

The lack of proper monospacing makes it a no-go for me: http://imgur.com/a/jeRZt
There will however be an upcoming simplification in icon handling that'll make it trivial for users to pick their own icons, so if all-the-icons works for you, you'll be able to feed it to treeemacs' icon store.

**Comment by Alexander-Miller** [comment]
Support for custom icons is pushed now. See the section about custom icons in the readme.

**Comment by Alexander-Miller** [comment]
> When browsing the file tree, just keep in treemacs you can quick look the file.

This is also now possible with the newest version of treemacs. Press C-u before calling one of treemacs' visit-node functions and point will stay in the treemacs window.
