### ISSUE TITLE
How to use treemacs-persist-file?

### ISSUE THREAD

**Issue by Ndot** [Alexander-Miller/treemacs#257]
Maybe its just me but persist-file doesn't seem to work as it should. Following the follow work flow:

1 - open emacs call treemacs type project folder and project name
2 - add more projects with "C-p a" (treemacs-add-project PATH)
3 - everything works
4 - close emacs look at persist file seems ok (an org file like with titles and paths)
6 - open emacs call treemacs and it asks for project folder and project name again

Is it supposed to work like this? Do I have to add all the projects every time I open emacs?
Maybe I'm missing something do I have to do something to load the file? I've look in the documentation and the issues but couldn't find anything about this.

**Comment by Alexander-Miller** [comment]
> Is it supposed to work like this?

No, something is wrong. Saving and loading your loadout should be fully automatic. This is probably some minor hiccup, since the change to use the org-mode format is literally only 2 days old.

Let's see:

 * Is it possible that you somehow load treemacs while`noninteractive` is t (maybe as a daemon)? Loading of your persisted state is guarded by `unless noninteractive`.
 * What does your persist file look like?
 * What's the output of the following code?

```
(-let [str-list (--reject (or (string= it "")
                              (s-starts-with? "#+STARTUP:" it))
                          (-> treemacs-persist-file (f-read) (s-lines)))]
  (if (--any? (s-matches? treemacs--persist-kv-regex it) str-list)
      (treemacs--read-workspaces
       (make-treemacs-iter :list str-list))))
```

**Comment by Ndot** [comment]
>Is it possible that you somehow load treemacs whilenoninteractive is t (maybe as a daemon)?
It seems I'm not in noninteractive. So unless noninteractive shout run.
```elisp
(if noninteractive t) 
nil
```
>What does your persist file look like?
```
* Default Workspace
** projectName
 - path :: /path/to/project
** otherProjectName
 - path :: /path/to/other/project
```
>What's the output of the following code?
```elisp
(-let [str-list (--reject (or (string= it "")
                              (s-starts-with? "#+STARTUP:" it))
                          (-> treemacs-persist-file (f-read) (s-lines)))]
  (if (--any? (s-matches? treemacs--persist-kv-regex it) str-list)
      (treemacs--read-workspaces
       (make-treemacs-iter :list str-list))))
nil
```
I see you guard with `unless noninteractive` `treemacs--persist` and `treemacs--restore` they both run. When I load emacs `treemacs--restore` logs the following error:
```
[Treemacs] Error '(wrong-type-argument listp *)' when loading the persisted workspace.
```

**Comment by Ndot** [comment]
I tried to debug this, but my elisp is week...

I did find a couple of things. I had a version with the `cl-assert` error in `treemacs-persistence.el`. It was missing the argument SHOW-ARGS between kv-lines and the string. I've updated now.

The second thing I've found was that if you look at `kv-lines` right before trowing the error it's value is nil when emacs starts. Although after everything has loaded if you run `treemacs--restore` everything is ok.

So for now as a workaround I advised a function to `treemacs` that calls `treemacs--restore` and then removes the advice function. And for now things work.

By the way I'm running GNU Emacs 25.3.1 don't know if this makes any difference.

**Comment by Alexander-Miller** [comment]
> don't know if this makes any difference.

Well I did run into the thing with cl-assert, which apparently cannot deal with asserting plain variables in Emacs 25. Maybe there's something similar going on.

Here's an idea: do you have any kind of special characters in your project paths, something that isn't alphanumeric and `/`? If so I might need to loosen my regex for those lines. Try defining the following variable before loading treemacs:

`(defvar treemacs--persist-kv-regex (rx bol " - " (1+ any) " :: " (1+ any) eol))`

 I'll also include tests for saving and restoring workspaces in the CI build, since I also build for Emacs25.

**Comment by Ndot** [comment]
>do you have any kind of special characters in your project paths

No special characters.
I don't think this has anything to do with the regex. On my last comment I stated that if a run the function after everything has load it works so it can't be the regex, or else it would never work.

I've been testing and by luck I've found when the function doesn't trow an error, it's after a buffer has been opened. Don't ask me why, cause I don't know.

I've created a video were you can see the behavior as follow:
- calling treemacs (failing - confirms that it did NOT loaded the file)
- calling treemacs--restore (failing)
- switch to buffer \*scratch\* (this is the key after this all works)
- calling treemacs--restore (working)
- calling treemacs (working)
- open \*Messages\* buffer (so you can see the error logs)

Note this is a completely clean emacs config the only thing installed is treemacs, plus whatever dependencies it installed, this way we know there is no package conflicts.

https://github.com/Ndot/test_error_vid

So, to solve the problem at the beginning of my emacs config I added `(switch-to-buffer "*scratch*")` by the time treemacs starts emacs has already opened a buffer and everything works as expected. I know it's not the root of the problem but it's a working solution.

**Comment by Alexander-Miller** [comment]
Well now it's getting weird. I've run [a test on the CI environment](https://travis-ci.org/Alexander-Miller/treemacs/jobs/412316387) and it passed, so it's not a general Emacs25 problem, at least not with the part of the code that does the parsing.

If this is about buffers then I guess you can try wrapping the entire restore function with `with-temp-buffer`, recompile, and see how that goes. If that doesn't change things I've uploaded a branch with [a whole lot of logging you can try next](https://github.com/Alexander-Miller/treemacs/commit/3a70215b5e7368ef83e3ed4aa9a34d1a235ea0db).

**Comment by Ndot** [comment]
Have you watched the video I posted? The error that happened on the video also shows up on you tests. Note line 796 of the travis-ci page you've linked. 

![error_line_796](https://user-images.githubusercontent.com/22114856/43736140-7de871cc-99b4-11e8-8b9d-c7f0121f7cc0.png)

>If this is about buffers then I guess you can try wrapping the entire restore function with with-temp-buffer

Tried that and with everything wrapped with `with-temp-buffer` it's worst I still get the error even after switching buffers.

Heres the logs from new file with a bunch of logs. 

Before switching buffer.
```
[Treemacs] Start log
[Treemacs] Running interactively
[Treemacs] Running in buffer *GNU Emacs*
[Treemacs] Persist file '/home/me/.emacs.d/.cache/treemacs-persist' exists.
[Treemacs] Start logging read lines
[Treemacs] * Default Workspace
[Treemacs] ** .emacs.d
[Treemacs]  - path :: /home/me/.emacs.d
[Treemacs] Stop logging read lines
[Treemacs] Error '(wrong-type-argument listp *)' when loading the persisted workspace.
[Treemacs] End log
```

After switching buffer.
```
[Treemacs] Start log
[Treemacs] Running interactively
[Treemacs] Running in buffer *scratch*
[Treemacs] Persist file '/home/me/.emacs.d/.cache/treemacs-persist' exists.
[Treemacs] Start logging read lines
[Treemacs] * Default Workspace
[Treemacs] ** .emacs.d
[Treemacs]  - path :: /home/me/.emacs.d
[Treemacs] Stop logging read lines
[Treemacs] Org-mode format is detected.
[Treemacs] Begin reading workspaces
[Treemacs] Head is at '* Default Workspace'
[Treemacs] Head '* Default Workspace' matches workspace regex
[Treemacs] Reading workspace name 'Default Workspace' from '* Default Workspace'
[Treemacs] Begin reading projects
[Treemacs] Head is at '** .emacs.d'
[Treemacs] Head '** .emacs.d' matches workspace regex
[Treemacs] Reading project name '.emacs.d' from '** .emacs.d'
[Treemacs] Line ' - path :: /home/me/.emacs.d' matches kv regex
[Treemacs] Found kv lines: '( - path :: /home/me/.emacs.d)'
[Treemacs] Kv iteration with ' - path :: /home/me/.emacs.d'
[Treemacs] Split line into key ' - path' value '/home/me/.emacs.d'
[Treemacs] Read project [cl-struct-treemacs-project .emacs.d /home/me/.emacs.d]
[Treemacs] Read projects ([cl-struct-treemacs-project .emacs.d /home/me/.emacs.d])
[Treemacs] Read workspace [cl-struct-treemacs-workspace Default Workspace ([cl-struct-treemacs-project .emacs.d /home/me/.emacs.d])]
[Treemacs] Finish reading: ([cl-struct-treemacs-workspace Default Workspace ([cl-struct-treemacs-project .emacs.d /home/me/.emacs.d])])
[Treemacs] End log
#("[Treemacs] End log" 0 10 (face font-lock-keyword-face))
```

Note if this is something that only affects me I'm happy using the solutions of switch-to-buffer I proposed on my last comment.

**Comment by Alexander-Miller** [comment]
> Have you watched the video I posted? The error that happened on the video also shows up on you tests. Note line 796 of the travis-ci page you've linked.

Watched the video, but missed that line. I assumed that with the test green the error didn't happen. Good thing it did, now I can use travis for my debugging instead of asking you for every little thing I want to try.

> Note if this is something that only affects me I'm happy using the solutions of switch-to-buffer I proposed on my last comment.

I doubt you'll be the only one. It looks like the code doesn't like running in certain buffers, be it temp buffers  or *GNU Emacs*, so there's bound to be other people affected by this. I'll keep investigating this. If nothing else helps I'll just summon a fitting buffer myself.

**Comment by Ndot** [comment]
Ok. If by mistake I happen to stumble upon something useful I'll let you know.

**Comment by Alexander-Miller** [comment]
Did some more logging on travis. Looks like it cannot properly read the persist file, all it sees is the first line if I call `insert-file-contents` in a temp buffer. I don't think that this is also your issue. The CI environment can be weird in hard drive matters - I had to dummy out some filewatch-mode functions because there was no space left for their file descriptors.

So now there's another change you need to try: [in this commit](https://github.com/Alexander-Miller/treemacs/commit/8b7090df17da47b849548af69ba1c1eea37855bf) I'm reading the file myself and logging what Emacs sees. I also removed the try catch, so if you run this code with `debug-on-error` enabled it'll produce a proper stacktrace.

**Comment by Alexander-Miller** [comment]
You can also try to `edebug-on-entry` the restore function, just to see where that takes you.

**Comment by Ndot** [comment]
>You can also try to edebug-on-entry the restore function, just to see where that takes you.

I couldn't find a definition for `edebug-on-entry`. I also only found about edebug two days ago (lol total newb here).

Here are the logs you asked, from the commit.
```[Treemacs] Start log
[Treemacs] Running interactively
[Treemacs] Running in buffer *GNU Emacs*
[Treemacs] Persist file '/home/me/.emacs.d/.cache/treemacs-persist' exists.
[Treemacs] Reading persist file in buffer  *temp*
[Treemacs] Inserted file content * Default Workspace
** .emacs.d
 - path :: /home/me/.emacs.d

[Treemacs] Will Return lines:
[Treemacs] * Default Workspace
[Treemacs] ** .emacs.d
[Treemacs]  - path :: /home/me/.emacs.d
[Treemacs] 
[Treemacs] Start logging read lines
[Treemacs] * Default Workspace
[Treemacs] ** .emacs.d
[Treemacs]  - path :: /home/me/.emacs.d
[Treemacs] Stop logging read lines
[Treemacs] No line matches kv regex, using old restore method.
let: Wrong type argument: listp, *
```

While running through the debugger I notice the file is read always, independently of the new function `treemacs--read-persist-file`. I've found that the error is on the following line:
```
(if (--any? (s-matches? treemacs--persist-kv-regex it) str-list)
```
The function `s-matches?` is a wrapper for `string-matches-p` which uses `string-matches` which is a C source function and that's where I stopped. But I've found that `string-matches-p` when running from a buffer that has it's major-mode set to something like fundamental-mode will always return nill (other modes like org-mode or text-mode will produce the same behavior).

Used the old **treemacs-persistence.el** file and added the following messages:
```
(message "[NDOT] Current major-mode is: %s" major-mode)
(message "[NDOT] Variable str-list is: %s" str-list)
(if (--any? (s-matches? treemacs--persist-kv-regex it) str-list)
    (progn
      (message "[NDOT] s-matches? WORKED")
      (setq treemacs-current-workspace
            (car (treemacs--read-workspaces
                  (make-treemacs-iter :list str-list)))))
  (message "[NDOT] s-matches? FAILED")
```

Which produced these logs:
```
[NDOT] Current major-mode is: fundamental-mode
[NDOT] Variable str-list is: (* Default Workspace ** .emacs.d  - path :: /home/me/.emacs.d)
[NDOT] s-matches? FAILED
[Treemacs] Error '(wrong-type-argument listp *)' when loading the persisted workspace.
Quit
[NDOT] Current major-mode is: emacs-lisp-mode
[NDOT] Variable str-list is: (* Default Workspace ** .emacs.d  - path :: /home/me/.emacs.d)
[NDOT] s-matches? WORKED
[cl-struct-treemacs-workspace "Default Workspace" ([cl-struct-treemacs-project ".emacs.d" "/home/me/.emacs.d"])]
```

After all it's not about switching buffers, like I though, but more about the major-mode being used. That's why using `with-temp-buffer` was always falling because it was always in `fundamental-mode`.  Knowing this I think we can just wrap `treemacs--restore` function with `with-temp-buffer` and call `lisp-mode` for example. Or wrap just the if statement if you prefer.

I tried this and it works.
```
(defun treemacs--restore ()
  "Restore treemacs' state from `treemacs-persist-file'."
  (with-temp-buffer
    (lisp-mode)
    ;; Rest of the function ...
)
```

The only thing bothering me is that I've created a function that uses a line like `if (--any? (s-matches?...` and called it in fundamental-mode and `s-matches?` worked properly, so I couldn't reproduce the error in a clean environment.

Sorry if my debugging is all over the place, anyway if you need me to test something else let me know.

**Comment by Alexander-Miller** [comment]
> [Treemacs] No line matches kv regex, using old restore method.

Aha! I should've included that line from the start. As you said it's all about the mode, more specifically about the syntax table. In fundamental-mode a period has punctuation syntax, while I only match word and symbol syntax, so your path containing `.emacs.d` could not be matched.

I'll expand the regex accordingly and we can shut this down.

**Comment by Ndot** [comment]
You are totally correct. I did not know about those syntax table differences. I just tried the regex and it works perfectly. That was totally my fault sorry about that.

I was mislead because when one path fails all paths fail.  So I thought it was failing for the other ones too (maybe if one path fails you could log it but still load the other ones). Now I see the error:
```
[Treemacs] Error '(error Found project without properties)' when loading the persisted workspace.
```
But after I close emacs the file is re-written and it gets back to:
```
[Treemacs] Error '(wrong-type-argument listp *)' when loading the persisted workspace.
```
And I was only seeing this last message. Anyway, yes you can shut this down. Thanks for your help.

**Comment by Alexander-Miller** [comment]
> Found project without properties

Hold up, you mean you're now seeing this if your use the looser regex from above? That's not supposed to happen either. If I understand you correctly we'll need to go analysing logs once more.

> maybe if one path fails you could log it but still load the other ones

That'll be included in the next batch of commits.

**Comment by Ndot** [comment]
No, when I said "Now I see the error" I meant when NOT using the looser regex, I was just explaining why I was mislead.

Just to be clear the looser regex works perfectly. Once  again sorry I didn't catch that sooner and thanks for you help.

**Comment by Alexander-Miller** [comment]
I used to. In earlier versions I just dumped the string representation onto the hard drive. Then emacs 26 was released and that representation changed, so your state was lost when upgrading. I also wanted to make that representation not just simpe to read and write, but also *nice and easy* to edit, without writing parsers for both a persist and edit format. Org-mode neatly fulfills all criteria.

It is not all done yet, but you can see the results of that choice when you call `treemacs-edit-workspaces` on an up-to-date treemacs.

**Comment by sergeyklay** [comment]
@Alexander-Miller Just faced with this issue. Treemacs suddenly lost lost all my projects and workspaces. I guess it happened after I started the emacsclient.

> Is it possible that you somehow load treemacs whilenoninteractive is t (maybe as a daemon)? Loading of your persisted state is guarded by unless noninteractive.

I didn’t make any additional settings and just start an emacsclient instance and probably I was wrong. Could you tell me how to prevent this behavior in the future.

**Comment by Alexander-Miller** [comment]
> Could you tell me how to prevent this behavior in the future.

First I need to know how and why this happens. Restoring and persisting state is already guarded by a check for `noninteractive`, so there must be more to it than just that. Can you give me steps to consistently reproduce how this happened?

It may help if you edit `treemacs--persist` and `treemacs--restore` to call something like `(shell-command "notify-send 'RESTORE'")` when they pass the `(treemacs--should-not-run-persistence?)` check.

**Comment by sergeyklay** [comment]
Ok, I'll try to deal with steps to reproduce.
