### ISSUE TITLE
Running treemacs on emacs init

### ISSUE THREAD

**Issue by cprussin** [Alexander-Miller/treemacs#258]
Maybe I'm missing something, but I don't see any way to run treemacs on emacs init, focused on the current file.  Ideally, I'd like the current project to be loaded with the tree expanded down to the current file, and if not in a project, then just the parent directory of the current file.  I've tried a few different things, including:

```elisp
(use-package treemacs
  :init (setq treemacs-show-hidden-files nil)
  :hook (after-init . #'treemacs-find-file)
  :config (treemacs-git-mode 'extended))
```

This opens treemacs, but it does not navigate the tree to the current file--it only loads the list of projects.  Also, oddly enough, it triggers a scratch buffer to open, I have no clue why.

```elisp
(use-package treemacs
  :init (setq treemacs-show-hidden-files nil)
  :config
  (treemacs-git-mode 'extended)
  (treemacs-find-file))
```

This loads a file selector at boot.  Not what I want.

```elisp
(use-package treemacs
  :init (setq treemacs-show-hidden-files nil)
  :config (treemacs-git-mode 'extended))

(use-package treemacs-projectile
  :after (treemacs projectile)
  :config
  (treemacs-add-project-at (treemacs--canonical-path (projectile-project-root)) (projectile-project-name)))
```

This gives me an error `treemacs-projectile/:config: You're not in a project`.  I then tried doing `treemacs-add-project-at` in a `proectile-after-switch-project-hook`, and at the very least, that causes new projects to be automatically added to treemacs.  But it still doesn't show the treemacs buffer, and it doesn't do anything for files that aren't in projects.

I'm sure what I'm looking for is fairly simple, is there something I'm missing or is this a new feature request?

**Comment by Alexander-Miller** [comment]
It's not quite *that* simple - if I understand you correctly you are asking to basically bypass treemacs' entire project management facilities and just pop in a single project/file tree for wherever you are. It does sound like a natural extension and starting point for the [ad hoc navigation](https://github.com/Alexander-Miller/treemacs#navigation-without-projects-and-workspaces), so I'll add something like that.

Until I'm done you'll basically need something like this before launching treemacs:
```
(let* ((path (or (buffer-file-name) "~/"))
       (name (f-filename path))
       (root (condition-case _
                 (projectile-project-root) 
               (error (f-parent path))))
       (project (make-treemacs-project :name name :path root)))
  (setf (treemacs-workspace->projects (treemacs-current-workspace))
        (list project)))
```

**Comment by vsemyonoff** [comment]
I did such thing:
``` emacs-lisp
(use-package treemacs
  :config
  (progn
    (defun vs//treemacs-add-project (&optional path)
      "Add project from `PATH' to `treemacs'."
      (let ((path (or path user-home-dir)))
        (unless (treemacs-current-workspace)
          (treemacs--find-workspace))
        (let ((name (file-name-nondirectory (directory-file-name (if (file-remote-p path)
                                                                     (car (last (split-string path ":")))
                                                                   path)))))
          (treemacs-do-add-project-to-workspace path name))))))

(use-package treemacs-projectile
  :after projectile
  :bind (:map global-map ([C-tab] . vs/treemacs-open))
  :config
  (progn
    (defun vs/treemacs-open ()
      "Setup project for current file and open `treemacs' buffer."
      (interactive)
      (vs//treemacs-add-project (condition-case _
                                    (expand-file-name (projectile-project-root))
                                  (error (expand-file-name default-directory))))
      (treemacs-select-window))))

```

**Comment by Alexander-Miller** [comment]
Revisiting the old and forgotten - `treemacs-add-and-display-current-project` some time ago which I think should also fit your requirements.

**Comment by liar666** [comment]
Hi,

Thanks for the great tool, I'm also trying to (mis)use Treemacs in a similar way as cprussin  (replacement/improvment of dired).

`treemacs-add-and-display-current-project` is almost what I need. Unfortunately I still face the problem of the *Scratch* buffer being opened. See attached pic.

When I try the `let *...` code, and open a `.cpp` then my hook to start lsp on such files in not run anymore :{
![screenshot_2021-04-28-12 20](https://user-images.githubusercontent.com/3216927/116389482-45976600-a81d-11eb-8bdb-41d0a8e44d2a.png)

Unfortunately, I'm far from lisp/emacs-fluent, so I'm not sure what too change here...

**Comment by Alexander-Miller** [comment]
>   (setq treemacs-use-follow-mode t)

These lines are wrong. Minor modes must be enabled with `(treemacs-follow-mode t)`. Treemacs enables these minor modes by default, so you didn't miss anything.

> It's quite strange as doc says treemacs-default-visit-action is set to treemacs-visit-node-no-split by default...

That's unrelated. The default visit action just decides how RET opens files. (It's also a bit obsolete now that I think about it, since nowadays you'd use `treemacs-define-RET-action`  to change that behavior.)

> Unfortunately I still face the problem of the Scratch buffer being opened, when I run something like emacs test.cpp

My guess is that Emacs will run your config first, so open treemacs in the current working directory, and only then load the file you're opening. You can work around that by explicitly calling treemacs later with a timer: `(run-with-timer 1 nil (lambda () (save-selected-window (treemacs))))` 

If you want to only work with a single project `treemacs-display-current-project-exclusively` may be useful for you as well.
