### ISSUE TITLE
Error: button-get: Wrong type argument: integer-or-marker-p, nil after creating a directory or a file

### ISSUE THREAD

**Issue by x-ji** [Alexander-Miller/treemacs#259]
After I create a file or a directory in a subdirectory of the project, I get the error `button-get: Wrong type argument: integer-or-marker-p, nil`, and the Treemacs tree automatically collapses to only show the top level directories in the project. I'm not sure why that's happening. The file/directory is successfully created though.

- [Treemacs] v2.2-2018-08-07
- GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05

**Comment by Alexander-Miller** [comment]
I'll need a stacktrace. Run `toggle-debug-on-error` and then reproduce the bug.

Also how do you create your files - with treemacs or externally?

**Comment by x-ji** [comment]
Sure.

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  get-text-property(nil :state)
  button-get(nil :state)
  treemacs--reopen-node(nil #<process Process Future>)
  treemacs--reopen-at("/home/jx/Dropbox/Tuebingen17SS/RA/woq_webapp" #<process Process Future>)
  treemacs--create-branch("/home/jx/Dropbox/Tuebingen17SS/RA/woq_webapp" 1 #<process Process Future> #<process Process Future<1>> #<marker at 3 in  *Treemacs-Framebuffer-1*>)
  treemacs--expand-root-node(#<marker at 3 in  *Treemacs-Framebuffer-1*>)
  treemacs-project->refresh!(#s(treemacs-project :name "woq_webapp" :path "/home/jx/Dropbox/Tuebingen17SS/RA/woq_webapp"))
  treemacs--do-refresh(#<buffer  *Treemacs-Framebuffer-1*> #s(treemacs-project :name "woq_webapp" :path "/home/jx/Dropbox/Tuebingen17SS/RA/woq_webapp"))
  treemacs--create-file/dir(t)
  treemacs-create-file()
  funcall-interactively(treemacs-create-file)
  call-interactively(treemacs-create-file nil nil)
  command-execute(treemacs-create-file)
```

Strangely it seems to be only happening with this project so far. I'm not sure what the problem is.

**Comment by x-ji** [comment]
Created it with treemacs

**Comment by Alexander-Miller** [comment]
I cannot reproduce it on my end, so it may be something specific to your setup. First let's make sure it's not due to some corrupted state in treemacs: kill its buffer (Q, not q) and then try again. If the issue persists then show me a screenshot of what your project layout looks like before you create the file so I can reproduce the exact details.

>  treemacs--reopen-node(nil #<process Process Future>)
>  treemacs--reopen-at("/home/jx/Dropbox/Tuebingen17SS/RA/woq_webapp" #<process Process Future>)

These lines say that treemacs was reopening everything below woq_webapp, but ran into some previously opened directory that it couldn't move to, which is why the 2nd call is made with nil.

**Comment by x-ji** [comment]
Also I get `Error '(wrong-type-argument listp *)' when loading the persisted workspace.` when I first try to relaunch treemacs each time after starting Emacs. They are probably related.

**Comment by Alexander-Miller** [comment]
No, that's on https://github.com/Alexander-Miller/treemacs/issues/257, and I'll push the patch for it later today.

**Comment by x-ji** [comment]
:ok_hand: I see

**Comment by Alexander-Miller** [comment]
This entire process has long since been rebuilt, so I assume this issue is obsolete.
