### ISSUE TITLE
Making use of the vs-code icons

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#262]
https://github.com/jojojames/vscode-icon-emacs

I should be able to make use of most what's in there. Since the number of icons is about to explode I should also look into pushing my icons to be compile-time constants.

**Comment by seagle0128** [comment]
I vote this feature.

**Comment by da-edra** [comment]
Hello.

How can I use vscode-icon in treemacs?

**Comment by Alexander-Miller** [comment]
You don't have to do anything. This ticket is just for my adding vscode icons to treemacs, see https://github.com/Alexander-Miller/treemacs/tree/master/icons/vsc.

After https://github.com/Alexander-Miller/treemacs/issues/287 you might eventually get a proper vscode theme, but we're not there yet.
