### ISSUE TITLE
[discussion] provide extension API

### ISSUE THREAD

**Issue by yyoncho** [Alexander-Miller/treemacs#263]
I am working on [lsp-java](https://github.com/emacs-lsp/lsp-java) and I am looking for a way to create a project deps explorer similar to [eclipse project explorer](https://help.eclipse.org/mars/topic/org.eclipse.platform.doc.user/images/Image275_project_explorer.png) . In order to accomplish that the following extension points will be needed:

1. Ability to plug children(e. g. when you open project the extension will be able to plug a node `Maven Dependecies`). 
2. Ability to specify a expand function for the inserted item.

Can you share your thoughts on that?

PS: At this point library information is specific to [lsp-java](https://github.com/emacs-lsp/lsp-java) but afte r https://github.com/Microsoft/language-server-protocol/issues/472 is resolved functionallity would become common for all lsp enabled languages.

**Comment by Alexander-Miller** [comment]
Sounds doable, but there is some work to be done, just providing the right hooks won't do it.

In fact it'd be even possible right now, but you would need 1) a bit of boiler plate and 2) some understanding of treemacs' internals.

 As an example you can look at `treemacs--expand-file-node`, which is called when you expand a file's tags. Some building blocks are already properly defined, like the `treemacs--button-open` macro, but you also need functions like `treemacs--insert-tag-node` (which is named incorrectly now that I look at it, there no more direct insertion here). 

Then there's the whole `:post-open-action` part and especially `treemacs-on-expand`, which integrates the whole thing into what you could treemacs' dom (you can find a good explanation of the whole thing in https://github.com/Alexander-Miller/treemacs/issues/226).

So making all the pieces fit together is a somewhat involved process that needs some streamlining before your part can go ahead smoothly, but I'm all for it.

**Comment by Alexander-Miller** [comment]
I've now started working on getting an extension API going, though it'll be a while until I've something workable. You can go ahead and look at how the tags code works, the plan is just to wrap all these parts into a single nice macro or two, but you will still need most of the single nuts and bolts like open/close icons and a function that decides what to show on expanding a node and a function that produces those strings etc.works

**Comment by yyoncho** [comment]
That's great, I am spending some time these days reviewing the code. I have one question though. Given the fact that extension API is in place, does this mean that you will be able to use `threemacs` engine to build whatever tree you want? You might know that I am working on `dap-mode` which displays trees(threads, locals, etc) and I am using `tree-widget` but I am a bit concerned about the performance of the widgets library. For example, if I just want to expand/collapse a node with 100+ elements it takes 1sec+ and 95% of the time is in the widgets library.

**Comment by Alexander-Miller** [comment]
Got some good work done today and got a major hurdle down with figuring out how to nicely wrap up stuff like those properties in `treemacs--insert-tag-node` (macros, yay). Thought of one thing you need to solve on your end: nodes need unique keys, at least those that you can expand. An expanded node lands in the shadow tree and is then addressable by its key from the index (a hash table). Without that treemacs won't know what you've expanded, wont be able to keep it expanded when you refresh the project, and won't be able to navigate there (at least not very well).

For file nodes I use their absolute path, hence the restriction on adding subdirectories, for tags I use their  breadcrumb path in the tag tree. Since you're dealing with debug items I guess you'll need to get creative.

>  if I just want to expand/collapse a node with 100+ elements it takes 1sec+ and 95% of the time is in the widgets library.

Expanding my performance test directory with an uncompiled code base and with over 2800 entries takes about 150 to 300 ms, depending on garbage collection and waiting for python with `treemacs-collapse-dirs` > 0, so that base will be covered.

**Comment by Alexander-Miller** [comment]
[Happy little accidents](https://i.imgur.com/rNkGx5u.png)

**Comment by Alexander-Miller** [comment]
[Basic show case is up on the dev branch](https://github.com/Alexander-Miller/treemacs/commit/7ad3772332a9922b550b56cfa2e7df28c91b6640). Just start treemacs and you should the list of buffers at the top of the buffer, except this time there's no borked recursion.

**Comment by yyoncho** [comment]
Thanks, I will do some testing and I will let you know. I am currently working on multiple folders workspace support in the `lsp-mode` which is directly related to the `treemacs` integration. Just to give you a heads up - I am planning to provide the following integration in `spacemacs` - when you add a folder to lsp it will automatically added to `treemacs`. Also, where do you think this integration should happen? In separate package or in `treemacs`?

**Comment by yyoncho** [comment]
Ignore previous comment, it works with `TAB`

**Comment by Alexander-Miller** [comment]
Those kind of details aren't all there yet. TAB, RET and mouse1 are not problem, I just need to add a call to `treemacs-define-RET-action` etc. Making it work with the other visit-node functions will need some more infrastructure.

The big parts that still need to go through are 1) providing node keys, and 2) extension points in the actual render process, but I would like to first hear from you whether there are any large issues that may require a larger change before getting to that.

**Comment by yyoncho** [comment]
I am on a vacation 4 days. I will ping you with more details when I am back. One of the things that has to have recipe is refreshing. Also, an extension point for follow mode will be needed too.

**Comment by Alexander-Miller** [comment]
> How should I plug the node under the project?

TBA. I've nothing concrete yet, but the idea is to create an extension point that you can just `push` to so your tree is rendered as the first, or maybe last, element of a project. There must also be a way to decide which projects to render for at all.

> Need one more extension point to provide follow mode.

Be great if it was just one. I'll need to make changes to some core code, or maybe provide a follow interface for the more generic extension nodes. I don't know yet. The first part of that is done, I've added the option to provide unique keys for your nodes (it was a force push, so you'll have conflicts). The handling of the special root node is a bit awkward, since I've stuffed all the extra info into the `:root` key, so that part is likely to change.

Next up is an expansion of the generated code, it looks like I'll need to create 2 functions for every operation, one that's public and interactive that you can bind, and one to do the work that assumes you pass it the node at point. I need both to make sure nodes can be reopened so they can survive a parent's refresh. 

> Since the java backend provides information for the project source folders I would like to set different icon for these folders(similar to what eclipse do).

There's a couple issues here:

 * So far directories don't receive different icons at all, so that should be included first.
 * The matching of icon to file is done by its name, see also `treemacs--file-extension`. I assume we can't do that here?.
 * I guess your extension could tell which directory names should be given special icons for a specific project, but this too is not possible right now, I've no concept of how to effectively and efficiently provide project local properties, other than the general idea that it'd be a useful thing to have.
 * As for the choice of icons see https://github.com/Alexander-Miller/treemacs/issues/262, and pick whatever you'd like to be included.

**Comment by yyoncho** [comment]
If https://github.com/Alexander-Miller/treemacs/issues/180 provides an extensible mechanism for altering nodes style the source folder markup could reuse the extension point. 

> As for the choice of icons see #262, and pick whatever you'd like to be included.

Are you going to include the icons as part of your repo?

**Comment by yyoncho** [comment]
Yep, I guess it should be either full path or list of node IDs. 

> Not all at once, I need to migrate the icon files to my own system, but yes, I have already started adding some, see c5be3b4

Hm, AFAIK MIT License is not compatible with GPL, how are you going to handle that? I am having this dilemma for `dap-mode`.

**Comment by Alexander-Miller** [comment]
It's the vs code package that's MIT licensed, the images themselves are under creative commons. AFAIU that means I'm free to use them, so long as I make that license, which I do [here](https://github.com/Alexander-Miller/treemacs/blob/master/icons/vsc/README.txt).

**Comment by Alexander-Miller** [comment]
I've added some extensions point basics, you can now plug your custom nodes either as the first or the last element in a project. The api will very likely change in the future, at the very least we need a predicate to decide which project to become active for. Adding custom properties to projects should be the way to go, so you can just ask `(treemacs-project->has-property? 'lsp-java)` or something like that.

I've begun work on making features like follow-mode possible, but here it gets complicated. Again. Long story short: you cannot just identify, query and move to custom nodes by their unique key alone. Using an absolute filepath has the advantage that I know how to get to a parent, so treemacs can move to a deeply nested file node even if the search starts at a closed root. Can't do that with extensions, if you want to go somewhere in your debugger you'll have to specify the full path as Local Values -> Stack Variables -> xyz.

That's one part. Another thing you need, especially for follow-mode, is determining which project to go to. That's the zero-value, if treemacs cannot get anywhere closer to a node it'll start at the project root. So if you have the info that emacs has opened some .class file somewhere in your gradle cache you must be able to say that the file should be followed at project X at path Y. It needs to be fast, too, follow-mode's entry point is advising `select-window`.

**Comment by yyoncho** [comment]
Thanks for the update, I believe that I will be able to put some effort on my side these days.

> the very least we need a predicate to decide which project to become active for. 

In `lsp-java` I have a list of paths which are the project roots. In case of multi-module project they might not be treemacs projects but simple folders. 

I believe that follow mode is nice to have feature and it might not be part of the initial integration and if it is hard to do we might skip it at all.

Providing full path will be easy(or at least not that hard) and I believe it is the way to go - nodes must be identified by the path to the node(by path to the node I mean the ids of the parents).

To make one clarification: the initial integration will be only with `lsp-java` project explorer, so basically, I will show project dependencies and it will allow browsing through dependency namespaces and eventually, I will migrate the rest of the stuff (variables, locals, etc) to treemacs to provide better experience.

**Comment by Alexander-Miller** [comment]
> nodes must be identified by the path to the node

Sounds like what I've pulled with tags. I needed that info to navigate anyway, so my tags are identified by the path of their names, e.g. File X -> Class Y -> Method Z.

> the initial integration will be only with lsp-java project explorer, so basically, I will show project dependencies

That's what I'm aiming at, too, though I'm trying to keep the big picture in mind as well. So far all development went into adding new nodes into existing projects. Creating independent trees in independent buffers will have its own challenges, mostly dealing with the correct initialization and invalidation of all the background variables.

I think this is a good spot to make a clean cut and consolidate before master and dev diverge too far. I'll clean up the code and the api, fill minor gaps, write proper eldoc and get merge on master. The extensions module will be on the load-path, but not loaded by default, so you'll be able to use treemacs as it comes from melpa, you'll just need to require the extensions part manually.

Then I'll handle addressing custom nodes. That part is mandatory, or they'll be closed again after every project refresh.

**Comment by Alexander-Miller** [comment]
First version of the extension api has made it to master (I needed to load it as well, so you needn't worry about that). Now it is your turn to tell me what's missing.

**Comment by yyoncho** [comment]
I had a chance to play with the API, here it is my initial set of questions/comments:

1. Since some of the project roots might not be java project root of the current workspace how do I create my root optionally?
2. On a similar note, in multi module project, some of the maven project roots might not be roots in treemacs. So how do I plug an extension in non-root folder? On a similar note, I believe that  the extension interface must be (folder-path, extension) which will provide the option to insert extension in any folder. 
3. At some point I will need a function to refresh a node + its children, I suspect that treemacs already have that function.

**Comment by Alexander-Miller** [comment]
> Since some of the project roots might not be java project root of the current workspace how do I create my root optionally?

By reminding me that I forgot about that part.

> So how do I plug an extension in non-root folder?

I'll come up with something similar to whatwe already have. Change the extension functions to `treemacs-define-project-extension` and add `treemacs-define-directory-extension`. Technically a project is also a directory, but I'd rather keep things separate and clean.

> At some point I will need a function to refresh a node + its children

The way this works is basically goto node and press TAB twice. Won't work for nodes yet because the goto node part isn't there yet, but it's high up on the todo list.

**Comment by yyoncho** [comment]
> The way this works is basically goto node and press TAB twice. Won't work for nodes yet because the goto node part isn't there yet, but it's high up on the todo list.

I would need to invoke that non-interactively, e. g. the user adds a new jar dependency, the language server sends classpath updates, and `lsp-java` refreshes the jar node in treemacs. It is not something that is required for the initial version though.

**Comment by yyoncho** [comment]
Here it is what I have:
![Latest](https://user-images.githubusercontent.com/13259670/45587957-cf68be00-b915-11e8-8ea6-9baca46b86c5.png)
I am using the following icons from vscode-icons, if you plan to put them in treemacs core I will reuse them:

file_type_jar.png folder_type_package.png folder_type_package_opened.png folder_type_component.png folder_type_component_opened.png folder_type_library.png folder_type_library_opened.png file_type_class.png

**Comment by Alexander-Miller** [comment]
> Currently when I hit enter on the root node I am getting an error

Working as expected. I think I've only added `:on-tab` so far, so I need to add ret and mouse1 and make sure to show an appropriate error when nothing is defined.

> I have used the following code for files:

That's the right spot. I'll expose is as a proper function and document it.

> I am using the following icons from vscode-icons

Ok, I'll add them.

**Comment by yyoncho** [comment]
As a side note, I found the following repo: git://git.eclipse.org/gitroot/platform/eclipse.platform.images.git - it might be used for `eclipse` treemacs theme

**Comment by Alexander-Miller** [comment]
Options for defining tab, ret and doubleclick actions are now in, and will be caught gracefully if nothing's defined. 
Icons for files can be retrieved with `treemacs-icon-for-file`.
Render predicates are included as well. Extension definition now looks like this:
```
(treemacs-define-project-extension
 :extension #'treemacs-BUFFERS-ROOT-extension
 :predicate #'predicate
 :position 'project-start)
```

**Comment by Alexander-Miller** [comment]
Custom node navigation is in. The api is slightly inconsistent, depending on whether you move to a file node or custom node, but I hope the eldoc makes clear what this is about. Basically you can move by calling something like

```
(treemacs-goto-button
 (list (-> (treemacs-current-workspace) (treemacs-workspace->projects) (cl-third))
       'Buffers
       'messages-buffer-mode
       (get-buffer "*Messages*")))
```

I just noticed it's still buggy, bust for the most part this is how it's supposed to work.

**Comment by yyoncho** [comment]
Hi, I might be missing something but is 
``` emacs-lisp
(treemacs--build-extension-addition "directory")
(treemacs--build-extension-removal "directory")
(treemacs--build-extension-application "directory")
```
supposed to work?

**Comment by Alexander-Miller** [comment]
Nope, those are a bunch of internal helpers. I figured I'll probably have a bunch of uniform code for project/dir/file/top/whatever extensions, so I've added some of these builders. I'm trying hard for my code to have a proper public and internal functions, so if there's a double dash there you either don't need it or I should change it.

The api is basically the same as I've left, [here's my own current test code](https://gist.github.com/Alexander-Miller/8e78426278a421c8fbcd9e579ee1ce0f). I've spent the last days chasing various bugs, so directory extensions aren't there yet, but I don't think they'll pose a challenge now that most of the infrastructure is in place.

After that, and after ironing out the kinks you'll probably find, I'll put take that code and put it into a nice and literate step-by-step tutorial.

**Comment by Alexander-Miller** [comment]
Hm, it looks like I lost a comment from yesterday that should be here. Basically: fixed some bugs, added `treemacs-update-node` and renamed button -> node on a bunch of functions.

**Comment by yyoncho** [comment]
What is the expected way to add project folders when treemacs is not active? I was unable to find a hook suitable for doing that on startup either.

**Comment by yyoncho** [comment]
For now everything is looking good, I didn't hit any issues related to the extension API.

Can you advide on how to create treemacs icon with image. Your example is using treemacs-as-icon.

Here it is the code that I am using but generates a byte compilation error:

```emacs-lisp
(defun lsp-java-treemacs--icon-path (rel-path)
  "Get fullpath to `lsp-java-treemacs' icon.
REL-PATH rel path to the icon."
  (f-join (f-dirname (or load-file-name buffer-file-name)) rel-path))

(treemacs--setup-icon lsp-java-treemacs-jar
                      (lsp-java-treemacs--icon-path "icons/vscode/file_type_jar.png"))
```

**Comment by Alexander-Miller** [comment]
> What is the expected way to add project folders when treemacs is not active?

Do you mean that when treemacs has not been loaded yet? In that case a with-eval-after-load will do.

> I didn't hit any issues related to the extension API.

There are still some minor points with e.g. refresh complaining about unknown node types when you refresh with point on a custom node. I'll be fixing that next.

> Here it is the code that I am using but generates a byte compilation error:

Yeah, compile-time evaluation makes things like that difficult. Do you even need those bits of path joininig? `treemacs--setup-icon` will concat things with `treemacs-dir`/icons, so all you should need is `(treemacs--setup-icon lsp-java-treemacs-jar "vscode/file_type_jar.png")`. Either way I'll look at the api and add the necessary bits to the tutorial.

**Comment by yyoncho** [comment]
> Do you mean that when treemacs has not been loaded yet? In that case a with-eval-after-load will do.

I want to add all of the java projects that are loaded in lsp-java to treemacs but in case treemacs is not active(never started) I got an error for missing workspace. I changed my code to force loading of treemacs before that and after that do the project loading as a workaroud. I guess it would be better to have a hook (treemacs loaded) on which I will put the register extension code + adding the lsp-java projects.

Here it is what I have now: https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java-treemacs.el#L227 

> Yeah, compile-time evaluation makes things like that difficult. Do you even need those bits of path joininig? treemacs--setup-icon will concat things with treemacs-dir/icons, so all you should need is (treemacs--setup-icon lsp-java-treemacs-jar "vscode/file_type_jar.png"). Either way I'll look at the api and add the necessary bits to the tutorial.

The icons are located in `lsp-java` package since they are used for other stuff. 

> There are still some minor points with e.g. refresh complaining about unknown node types when you refresh with point on a custom node. I'll be fixing that next.

I saw these but they are not major issues.

**Comment by Alexander-Miller** [comment]
> but in case treemacs is not active(never started) I got an error for missing workspace

Ah, right. The current workspace is first set when treemacs is actually used. The idea is that when multiple workspaces are in treemacs would load the workspace that contains the current project. I'll put handling this on my todo list.

> The icons are located in lsp-java package since they are used for other stuff.

As far as icons are concerned, I don't think they should be in lsp-java. The extension api is for everyone, so unless it's a very specialized icon that nobody else can use I think the icons should be put into treemacs to make them widely available.

**Comment by yyoncho** [comment]
I believe that the code should be designed in a way that it does not matter where the icons are located. See:  https://github.com/Alexander-Miller/treemacs/issues/287#issuecomment-431097139

**Comment by Alexander-Miller** [comment]
That is the plan. The problem with your code was only that it doesn't work with compile-time evaluation.

Looks like `eval-when-compile` cannot call other functions unless they are inlined, so `defsubst` would work. The next problem would be that `(or load-file-name buffer-file-name)` evaluates to nil at compile time, so I guess you need to define something like `treemacs-dir`.

**Comment by Alexander-Miller** [comment]
https://github.com/Alexander-Miller/treemacs/commit/7aa0828ae6d56681f2583b8f5b02d5fe72a8d19a should give you the hook you need. Keep in mind that workspaces are local to frames, so that hook can run multiple times. In the future, when workspaces are more fleshed out, it could also load the same or a different workspace.

**Comment by Alexander-Miller** [comment]
More patches pushed. Refresh and follow-mode should now have no problems with point being on custom nodes. I've also added a list of property names already used by treemacs.

Next up is custom top-level nodes/projects.

**Comment by yyoncho** [comment]
Sounds great! This step will bring `treemacs` closer to being able to have standalone tree renderer, right?

**Comment by Alexander-Miller** [comment]
Yes. The is he final necessary step before I can begin making things work outside of the actual treemacs buffer.

**Comment by Alexander-Miller** [comment]
Pushed a first version for top level extensions in https://github.com/Alexander-Miller/treemacs/commit/f00fbf657f4e52027ba9ae5f0cee3687236b44d9. That should at least give you enough material to start experimenting with porting your rendering to treemacs. Mind the readme, not everything is done yet.

https://github.com/Alexander-Miller/treemacs/commit/26aeab6802493c59ab8b1dffbe004274f2cb70dd could also be interesting for you.

Finally I've slightly changed the api: position arguments for an extension are now just `'top` or `'bottom` instead of depending on the extension type.

**Comment by yyoncho** [comment]
Thanks for the update!

> Pushed a first version for top level extensions in f00fbf6. That should at least give you enough material to start experimenting with porting your rendering to treemacs. Mind the readme, not everything is done yet.
 As a side note, do you have plans to create a separate package for the "tree component"? I am a in the middle of hude lsp-mode restructoring and when I finish with it I will try it for some of the new components that I am going to implement in `lsp-java` - class hierarchy and Errors view. 

> Finally I've slightly changed the api: position arguments for an extension are now just `'top` or `'bottom` instead of depending on the extension type.

Will this break existing code in `lsp-java-treemacs.el` or this is only for top level extensions?

**Comment by Alexander-Miller** [comment]
> As a side note, do you have plans to create a separate package for the "tree component"?

No. The extensions make use of treemacs' internals, so any extra package I extract would just have treemacs as a transitive dependency. To make such a package worthwhile I'd have to revert that dependency, and extract a general library that both treemacs and its extensions depend on. That would keep me busy for months, make the code a lot more complex and brittle, make the handling of dependencies and api versions more complex and brittle and the only advantage I see is that some people who want a nice and fast call hierarchy rendered by treemacs might want the project explorer it's started as. So yeah, lots of work for hardly any gain.

> Edit: I saw that it will break it.

To be fair: the feature isn't exactly done yet. As far as I'm concerned we are still in the development feedback loop where things can quickly change based on your feedback and my own ideas.

I'll solidify and finish up the current state of extensions and then close this ticket. That's when the api will be frozen I won't change things unless I have to. Building extensions outside of treemacs proper will be continued in another issue.

**Comment by yyoncho** [comment]
It's fine. Just ping when there are breaking changes if it is not a problem.

**Comment by Alexander-Miller** [comment]
First big part is done, finish up is in #309. 

So far it doesn't look like I'll have to change much to make things work in others' buffer, so I should have something quite soon.

**Comment by yyoncho** [comment]
@Alexander-Miller - quick question - how do I create a list of nodes on the top level, e. g. I want to put the major-modes on top level if we are talking about the buffers example from your extension API demo?

**Comment by Alexander-Miller** [comment]
Right now there's no good way to do it. You'd have to define its own top-level extension for every major mode you want to see, [like so](https://github.com/Alexander-Miller/treemacs/blob/master/Extensions.org#extensions-at-the-top-level).

What's your use-case? Maybe I can come up with some kind of repeating extension type.

**Comment by yyoncho** [comment]
The usecase is about the standalone usage. Every view that I want to implement using treemacs has multiple top level elements, e. g. Debug sessions, locals, and so on.
