### ISSUE TITLE
Is there a way to configure treemacs to open files in the buffer currently in focus?

### ISSUE THREAD

**Issue by narendasan** [Alexander-Miller/treemacs#266]
When opening a file in treemacs when I have two side by side buffers, treemacs will always open the file in one regardless of which buffer is in focus. Is there away to modify this behavior?

**Comment by Alexander-Miller** [comment]
The thing with the focus does not work the way you think it does. When you open something in treemacs it means treemacs is focused. That applies even to the mouse since the first click will set the focus.

However there are plenty of ways to tell treemacs what to do.There's half a dozen ways to open files, all under the `o` prefix. Best consult the helpful hydra on that. TAB, RET and mouse1 have special configurations in `treemacs-TAB-actions-config`, `treemacs-RET-actions-config` and `treemacs-doubleclick-actions-config`.

**Comment by narendasan** [comment]
Cool, thanks for the info

**Comment by alexryndin** [comment]
@sdwolfz  lol oaa -> asdf onstead of simple RET, as it works in neotree....

**Comment by Alexander-Miller** [comment]
Did you jump into this old issue just to make catty comments, or do you have something constructive to contribute?

**Comment by alexryndin** [comment]
@Alexander-Miller I think neotree behavior would be better as it replace last active buffer, not the first one, which is more intuinive and natural: I did this in my dotfile:
```
  (treemacs-define-RET-action 'file-node-closed #'treemacs-visit-node-ace)
  (treemacs-define-RET-action 'file-node-open #'treemacs-visit-node-ace)
```
Not quite neotree behavior, but now it requires only two key presses -> `RET` and then windows number, and provides better windows control.

**Comment by Alexander-Miller** [comment]
Ok, this I can work with. 
I disagree with neotree's behavior being more intuitive - it's just what you are used to, but that's not the point. I can create another visit function to use the most recently used window like neotree does. Defaults will stay as they are and it'll be bound to `o r`, as in open-recent, and you'll be able to bind it to RET if you want.

**Comment by alexryndin** [comment]
@Alexander-Miller It seems I do something wrong, but `r o` is not available as a default for me, it is not defined at all.

**Comment by Alexander-Miller** [comment]
It's `o r`, and I haven't done anything yet, I just agreed with the idea. The implementation should be easy enough, so you can expect am update in a day or two.

**Comment by alexryndin** [comment]
@Alexander-Miller That's would be great, thanks!

**Comment by Alexander-Miller** [comment]
https://github.com/Alexander-Miller/treemacs/issues/414

**Comment by alexryndin** [comment]
@Alexander-Miller Thank you much!

**Comment by x-ji** [comment]
With @sdwolfz and @alexryndin 's configs I was able to configure it to act similarly to NeoTree. Thanks.
