### ISSUE TITLE
treemacs-refresh gives error: wrong type argument: listp, 112

### ISSUE THREAD

**Issue by rbhicks** [Alexander-Miller/treemacs#269]
config:
OS X High Sierra 10.13.6
emacs 26.1
helm
helm-swoop
helm-projectile
projectile
treemacs-projectile
ace-window

Treemacs is open displaying a Phoenix (elixir) project. The focus is on the treemacs window. Pressing ‘g’ or M-x treemacs-refresh gives “Wrong type argument: listp, 112”.

**Comment by Alexander-Miller** [comment]
That one will need a stacktrace.

**Comment by rbhicks** [comment]
Here it is:

Debugger entered--Lisp error: (wrong-type-argument listp 112)
  treemacs-refresh()
  funcall-interactively(treemacs-refresh)
  call-interactively(treemacs-refresh nil nil)
  command-execute(treemacs-refresh)

**Comment by Alexander-Miller** [comment]
On the one hand: that stack trace is useless.
On the other hand: looks like I've reproduced the problem anyway. At least it's the exact same error, but it happens right as I load treemacs. Interestingly enough emacs is telling me that the current treemacs workspace is an "Unprintable entity" (but it's type is string, and calling `length` on it returns 112 ...). 

Let's see where this goes.

**Comment by Alexander-Miller** [comment]
> and calling length on it returns 112

Ok, that part isn't quite right, but the workspace is definitely up to no good.

**Comment by Alexander-Miller** [comment]
Found the problem: The current workspace is local to a frame, so it's saved as a frame parameter. desktop-save-mode is saving that param, but cannot restore it properly, since the workspace type is loaded only lazily with treemacs.

Now I just need to tell desktop-save-mode not to save that param, or just reset it when treemacs is first loaded. Patch should come tomorrow.

**Comment by Alexander-Miller** [comment]
Patch is pushed, both your bugs should be fixed now.

**Comment by rbhicks** [comment]
cool, thanks!
