### ISSUE TITLE
treemacs  20170802.5  and 

### ISSUE THREAD

**Issue by avkoval** [Alexander-Miller/treemacs#27]
Hi Alexander!

With the latest version installed I get errors like:

"find-file-noselect: Wrong type argument: stringp, nil" everywhere where I try to open file

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  find-file-noselect(nil nil nil nil)
  find-file(nil)
  treemacs-visit-node-no-split()
  funcall-interactively(treemacs-visit-node-no-split)
  call-interactively(treemacs-visit-node-no-split nil nil)
  command-execute(treemacs-visit-node-no-split)
```

**Comment by Alexander-Miller** [comment]
My bad, in recent weeks I went all in with features and refactoring, but neglected to make sure everything's wired correctly by the compiler :(

I've a pretty good idea what's causing this bug, so I'll have this fixed in a day or two.

**Comment by avkoval** [comment]
OK, personally I've reverted to 1.7.6 locally (just removed package from melpa and got it from git). But I worry other users might have similar problems and won't do such long fix. I also have a feature request, will post in different ticket

**Comment by Alexander-Miller** [comment]
Have a look at version 1.8.3, it's up on melpa. All the open actions should work now. Directories will also be opened with dired.

**Comment by avkoval** [comment]
Hi!
I am looking at Version: 1.8.4.
This bug is fixed. Btw, to look at actual version (in terms of treemacs) I had to look at source. Is that possible to make some interactive function to check it? Like 'treemacs-version' ? It can be useful for bugs reporting

**Comment by Alexander-Miller** [comment]
It's not a function, but there is a variable called `treemacs-version` that you can look up.
