### ISSUE TITLE
Error running timer `treemacs-follow`

### ISSUE THREAD

**Issue by rbhicks** [Alexander-Miller/treemacs#270]
config:
OS X High Sierra 10.13.6
emacs 26.1
helm
helm-swoop
helm-projectile
projectile
treemacs-projectile
ace-window

The following error occurs periodally (when switching window focus or without input at various times): “Error running timer `treemacs—follow`: (wrong-type-argument treemacs-workspace “Unprintable entity”)

**Comment by Alexander-Miller** [comment]
For both your bug reports:

 * Make sure your treemacs is up-to-date.
 * Set `debug-on-error` to t and show me the stacktace.

For this bug: what's the output of `(treemacs-current-workspace)`?

**Comment by rbhicks** [comment]
Debugger entered--Lisp error: (wrong-type-argument treemacs-workspace "Unprintable entity")
  signal(wrong-type-argument (treemacs-workspace "Unprintable entity"))
  treemacs--find-project-for-buffer()
  treemacs--follow()
  apply(treemacs--follow nil)
  timer-event-handler([t 0 0 200000 nil treemacs--follow nil idle 0])

Both errors occur with the current version in Melpa:  20180826.1501

I don't have a function (via M-x) nor a variable (via eval-expression) of (treemacs-current-workspace).

**Comment by Alexander-Miller** [comment]
> "Unprintable entity"

At least we know it's the same issue.

> I don't have a function (via M-x)

It is not interactive, but you can evaluate it in the scratch buffer.

**Comment by rbhicks** [comment]
thanks for the fix!
