### ISSUE TITLE
M-j/M-k behavior on empty lines is annoying

### ISSUE THREAD

**Issue by TimoFreiberg** [Alexander-Miller/treemacs#271]
Because it doesn't move the cursor (and blinks red!)

**Comment by Alexander-Miller** [comment]
Remind me what this was about again :thinking:

**Comment by Compro-Prasad** [comment]
There are no more empty lines in treemacs. So, this issue is no more relevant.

**Comment by Alexander-Miller** [comment]
:man_shrugging:
