### ISSUE TITLE
Any way to copy/move directories/files?

### ISSUE THREAD

**Issue by HaoZeke** [Alexander-Miller/treemacs#273]
Pretty much as per the title.

The hydra lists `c d` and `c f` to make directories and files respectively but are there any commands to move and copy files/folders?

**Comment by Alexander-Miller** [comment]
The hydra should include renaming as well, but no, copying or movement is not there yet. For now you should fall back to dired or your shell, but I'll but this on my todo list.

**Comment by TinySong** [comment]
is there any progress ?

**Comment by Alexander-Miller** [comment]
Sorry about the wait. I got distracted with new issues and my own grand ambitions. I'll put this issue on top of my list.

**Comment by HaoZeke** [comment]
@Alexander-Miller Thanks! You do great work, no need to apologiz, it's FOSS :grin:

**Comment by TinySong** [comment]
very thank you hard work !!! no need to apologize

**Comment by Alexander-Miller** [comment]
copy-file command is done. Keybind is `yf` and it's smart enough to rename a file to "foo (Copy 123).el" like thunar does.

**Comment by HaoZeke** [comment]
Thanks a ton!

**Comment by Alexander-Miller** [comment]
Hold up, I'm not done. I'll do moving as well.

**Comment by HaoZeke** [comment]
Yikes, my bad, sorry 


________________________________

**Comment by antonalekseev** [comment]
@Alexander-Miller, thanks a lot for copy/move, those was the last things that holds me from switching to treemacs. Also have a minor suggestion. Wouldn't it be more sensible to use `cp` or `c` key for `treemacs-copy-file`? `y` in `yf` stands for "yank" which usually denotes operation of fetching object in order to store it somewhere awaiting for following (optional) operation, while "copy" is atomic operation and it's exactly what `treemacs-copy-file` does.

`yf` and `pf` would be useful (if implemented) for the following scenario: yank file `yf`, navigate to another subtree, paste file `pf`.

**Comment by Alexander-Miller** [comment]
> y in yf stands for "yank" which usually denotes operation of fetching object

I think I used evil's meaning of the word yank here. I know it is inconvenient for people used to the emacs way of doing things, but if I start running different key map setups for both worlds I'll never see the end of it (also c is already the prefix foe create file/dir - should those really be mixed?).

So if the default setup isn't to your taste you can trivially change it with `(define-key treemacs-mode-map (kbd "cf") #'treemacs-copy-file)`.

**Comment by antonalekseev** [comment]
> So if the default setup isn't to your taste you can trivially change it

Sure, fair enough. Just wanted to make suggestion and hear rationale behind your choice.

Also while trying to copy (the same happens with a move operation) file from `/Users/redacted/d.sh` to `/Users/redacted/d1.sh` file has been actually copied but in the minibuffer appeared following error: `Node at path /Users/redacted/d1.sh cannot be found`. You can find system info and backtrace below.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e8a6bc2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ansible
 (auto-completion :variables spacemacs-default-company-backends
                  '((company-gtags company-etags company-keywords)
                    company-files company-dabbrev)
                  auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip 'manual auto-completion-enable-sort-by-usage t)
 emacs-lisp git github
 (go :variables go-tab-width 4 godoc-at-point-function 'godoc-gogetdoc go-use-gometalinter t)
 html ivy
 (lsp :variables lsp-ui-sideline-enable nil lsp-ui-doc-include-signature t lsp-ui-doc-position 'bottom lsp-ui-flycheck-enable nil)
 (javascript :variables javascript-fmt-tool 'prettier javascript-backend 'lsp js2-basic-offset 2 js-indent-level 2)
 (python :variables python-backend 'lsp python-test-runner 'pytest)
 racket restclient
 (shell :variables shell-default-shell 'eshell shell-default-term-shell "zsh")
 (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
 (treemacs :variables treemacs-no-png-images t)
 theming
 (version-control :variables version-control-diff-tool 'diff-hl)
 yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2


#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (error "Node at path /Users/redacted/d1.sh cannot be found")
  signal(error ("Node at path /Users/redacted/d1.sh cannot be found"))
  error("Node at path %s cannot be found" "/Users/redacted/d1.sh")
  treemacs-update-node("/Users/redacted/d1.sh")
  treemacs--copy-or-move(:copy)
  treemacs-copy-file()
  funcall-interactively(treemacs-copy-file)
  call-interactively(treemacs-copy-file nil nil)
  command-execute(treemacs-copy-file)
```

**Comment by Alexander-Miller** [comment]
> Also while trying to copy (the same happens with a move operation) file from /Users/redacted/d.sh to /Users/redacted/d1.sh

That is actually unsupported, copy and move operations expect you to feed them a directory name, while what you did is really a rename (and that's available on `R`). I am surprised it worked at all.

I've opened https://github.com/Alexander-Miller/treemacs/issues/367 to extend that api.
