### ISSUE TITLE
Custom error handling on ENOSPC error

### ISSUE THREAD

**Issue by DougBeney** [Alexander-Miller/treemacs#274]
On Fedora Linux and I noticed the following error pop up when opening projects.

I remembered a similar error on a different machine with a different piece of software. It was the ENOSPC error.

The fix is actually quite easy: https://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

```
Debugger entered--Lisp error: (file-notify-error "Could not add watch for file" "No space left on device" "/home/doug/dotfiles/.emacs.d")
  inotify-add-watch("/home/doug/dotfiles/.emacs.d" (create delete delete-self modify move-self move) file-notify-callback)
  file-notify-add-watch("/home/doug/dotfiles/.emacs.d" (change) treemacs--filewatch-callback)
  treemacs--start-watching("/home/doug/dotfiles/.emacs.d")
  treemacs--expand-root-node(#<marker (moves after insertion) at 3 in  *Treemacs-Framebuffer-1*>)
  treemacs-toggle-node(nil)
  treemacs-RET-action(nil)
  funcall-interactively(treemacs-RET-action nil)
  call-interactively(treemacs-RET-action nil nil)
  command-execute(treemacs-RET-action)
```

I'm not sure how difficult Emacs error handling is but perhaps you could add some documentation explaining how this is most likely an error caused by sysctl and can be fixed by modifying fs.inotify.max_user_watches.

EDIT: Btw, does this project have a donation page or Beerpay? This package has been super helpful for me. (Viewing a file's tags by pressing tab is epic!).

**Comment by Alexander-Miller** [comment]
> I'm not sure how difficult Emacs error handling is but perhaps you could add some documentation explaining how this is most likely an error caused by sysctl

It's basically try/catch and try/finally, but with more parentheses. Adding a log statement in case of this error is doable.

> Btw, does this project have a donation page or Beerpay? This package has been super helpful for me. 

Nope, I'm doing this for shits and giggles. Maybe someday, but for now I'm good.

> (Viewing a file's tags by pressing tab is epic!).

That is just imenu in a tree. You'll see the same tags with something like`helm-imenu`.

**Comment by Alexander-Miller** [comment]
I've looked around the code and the `file-notify-add-watch` calls happen in quite a few disparate and performance-crucial spots, so I'd rather not burden them with more overhead, no matter how miniscule it may be. This error should be quite rare (what's the default max_watches anyway? On system it's already at 524288), so I'll add an entry to the FAQ instead.
