### ISSUE TITLE
pfuture not found.

### ISSUE THREAD

**Issue by jigmpatel** [Alexander-Miller/treemacs#277]
I am trying to install treemacs but keep on getting error on pfuture.

**Comment by Alexander-Miller** [comment]
It works for me, so there's 2 possible reasons for your problem: 

 * You just need to run `package-refresh-contents`.
 * You're on emacs <25.2, in which case you're out of luck, since treemacs doesn't support anything below that.

**Comment by jigmpatel** [comment]
Thanks Alexander. It worked and it's amazing.

**Comment by Alexander-Miller** [comment]
:+1:
