### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by avkoval** [Alexander-Miller/treemacs#28]
Hi Alexander,
The 1.8 version looks great and the integration with imenu is killing feature! ;-) Waiting until the bugs are fixed and so I'll start using it in full.

Meanwhile, I have a small feature request. Could you please either explain in docs how to add custom key bindings for treemacs functions? I would like for example that std. 'oo' opens 'dired' where it stays on dir, I even did this locally in my config:

```lisp

(defun treemacs--open-file (&optional window split-func)
  "Visit file of the current node.  Split WINDOW using SPLIT-FUNC.
Do nothing if current node is a directory.
Do not split window if SPLIT-FUNC is nil.
Use `next-window' if WINDOW is nil."
  (let* ((path     (treemacs--prop-at-point 'abs-path))
         (is-file? (f-file? path)))
    (if is-file?
        (progn
          (select-window (or window (next-window)))
          (when split-func
            (call-interactively split-func)
            (call-interactively 'other-window))
          (find-file path)
          )
      (dired path)
      )
    )
  )
```

so just overrided the std. function in 1.7.6 and it works fine. But I believe there could be more needs like that.

even if not on 'oo' but some other method how to open dired in place would be good, like may be adding 'od' etc...

**Comment by Alexander-Miller** [comment]
As far as changing default behaviour overwriting the defaults is the way to go. The new `treemacs--execute-button-action` macro introduced in 1.8 will make that much easier for you (once I've gotten rid of the current bugs that is). It does all the button state checking and case handling for you, all you need to do is copy the current implementation and add a `:dir-action` argument

I'll add opening dired for directories is default, IMO it's better than doing nothing.

As for plain configurability I'll probably be adding a bunch of default-action vars that will be used by RET, so it's no longer doing the same thing as TAB.

I'll add a couple of paragraphs to the readme on this after I'm done with the bugs.

**Comment by avkoval** [comment]
ok, testing Version: 1.8.4. Apparently, when I press 'oo' on a directory, nothing happens. BTW, in version installed from git (1.8) I've seen nice debug about the event occurs (like that there is no imenu, or that directories can't be open). Right now this verbosity level seems to be gone, probably disabled? Could be good if it can be customized.

**Comment by Alexander-Miller** [comment]
That's odd. It's working on my end.
 
Do you see anything suspicious in the messages buffer? Treemacs ought to complain if it doesn't know what to do with a button.

What's oo bound to? What's the code look like? It should look like this:
```
(treemacs--execute-button-action
   :file-action (find-file (treemacs--safe-button-get btn 'abs-path))
   :dir-action (dired (treemacs--safe-button-get btn 'abs-path))
   :tag-action (treemacs--goto-tag btn)
   :no-match-explanation "Node is neither a file, a directory or a tag - nothing to do here.")
```
Does it still not work if you evaluate the function? What about after restarting emacs and deleting and reinstalling treemacs?

BTW, I've added a couple pointers [to the wiki]. Your wanting to know about how to handle buttons should be covered as well.

**Comment by Alexander-Miller** [comment]
My emails say you also asked about lack of logging. Since the question is no longer here can I assume logging logging works as expected now? 

I did fix a bug in my log suppression that should silence treemacs when it's e.g. doing  a refresh after deleting a file, but telling you about lack of an imenu index should still work.

**Comment by avkoval** [comment]
> My emails say you also asked about lack of logging. Since the question is no longer here can I assume logging logging works as expected now?

Yes, logging works.

**Comment by Alexander-Miller** [comment]
What about opening dirs in dired?

**Comment by avkoval** [comment]
> What about opening dirs in dired?

Fixed! ;-)
Last time I probably tried and forget to comment the 'git' version which was 1.8 (I have several workspaces and the problem was only present on one of them)
Now its fixed, thank you!
