### ISSUE TITLE
feature request: tree like buffer overview

### ISSUE THREAD

**Issue by minad** [Alexander-Miller/treemacs#284]
I am currently using ibuffer as a buffer viewer. It might be nice to have something like treemacs showing buffers categorized somehow? Is this within the scope of this project?

**Comment by yyoncho** [comment]
https://github.com/Alexander-Miller/treemacs/issues/263#issuecomment-414559738 you may take a look at this comment and the reply.

**Comment by minad** [comment]
Wow that looks incredible. It seems there is already a showcase doing something like that. I will dig a bit around then!

**Comment by minad** [comment]
@yyoncho Any idea on when those things will lang in master?

**Comment by minad** [comment]
@Alexander-Miller Cool, I am looking very much forward to that! You mean extension support is already in master? I've found the buffer viewer in the dev branch (WIP SHOWCASE).

**Comment by Alexander-Miller** [comment]
I had only included the buffer viewer at first to serve as an example. It's certainly easier than writing proper documentation for the whole process, especially when the api is far from solid and done.

What meant is that the extension support code is in master, but it's not really used yet, except in @yyoncho's fork. You'll need to be a bit more patient before this whole thing comes into its own.

**Comment by minad** [comment]
Sure no hurry!

**Comment by minad** [comment]
@Alexander-Miller I've seen you updated https://github.com/Alexander-Miller/treemacs/blob/master/Extensions.org about using extensions to get a buffer view :+1:  

Is it possible to create a separate treemacs window, which only shows the buffer nodes under some special buffer root node instead of putting them below some project? Do you plan something like that?

**Comment by Alexander-Miller** [comment]
Yes. That kind of stuff is the goal of the extension api. You can track that in https://github.com/Alexander-Miller/treemacs/issues/263.

**Comment by minad** [comment]
@Alexander-Miller Since the extensions api seems done now, will this feature be implemented as part of the treemacs package?

**Comment by Alexander-Miller** [comment]
Yeah, that is the plan. I have just done plenty of work on account of https://github.com/Alexander-Miller/treemacs/issues/247, so I want to play catch up with the older issues first, but doing a buffer view is high up on the list.

**Comment by minad** [comment]
Cool. Looking forward to it! Great work you are doing! I haven't had issues anymore since a while with treemacs and I am updating quite often from melpa. Everything working smoothly!

**Comment by Alexander-Miller** [comment]
Work on buffers has started, see #326.
