### ISSUE TITLE
feature request: show projectile compilation errors in treeview

### ISSUE THREAD

**Issue by minad** [Alexander-Miller/treemacs#285]
Would it be possible to somehow flag tree entries if they have an associated error due to projectile compilation output? Maybe it would make sense to generalize this and just provide some "flag this entry" api in treemacs, which could be connected with arbitrary providers? Does such an API already exists?

**Comment by yyoncho** [comment]
Duplicate of https://github.com/Alexander-Miller/treemacs/issues/180

**Comment by minad** [comment]
Thank you @yyoncho
