### ISSUE TITLE
Pinned treemacs sidebar behaves differently in emacs25 and emacs26

### ISSUE THREAD

**Issue by minad** [Alexander-Miller/treemacs#286]
I just tested emacs26. There the treemacs sidebar disappears when I press C-x-1 in the main window. In emacs25 the sidebar stays.

**Comment by minad** [comment]
There is a new option no-delete-other-windows in 26, see https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS.26#L1755

**Comment by minad** [comment]
can be fixed for all dedicated windows as follows:
~~~ elisp
(add-hook 'window-configuration-change-hook
          (lambda ()
            (dolist (w (window-list))
              (if (window-dedicated-p w)
                  (set-window-parameter w 'no-delete-other-windows t)))))
~~~

**Comment by Alexander-Miller** [comment]
Is the behaviour still different for windows created when `treemacs-display-in-side-window` is nil?

**Comment by minad** [comment]
No it is the same. If I set that variable to nil the sidebar is closed by C-x 1 on both 25 and 26.

**Comment by Alexander-Miller** [comment]
I've now added `treemacs-no-delete-other-windows` (t by default) that will allow this kind of behaviour on emacs 26.
