### ISSUE TITLE
Question: support for themes

### ISSUE THREAD

**Issue by yyoncho** [Alexander-Miller/treemacs#287]
I am planning to implement a few themes for treemacs(Eclipse/Idea/VScode). I wonder whether you want to support that in treemacs core similar to what widgets do(e. g. have icons directory + theme name which is the name of the folder in icons directory). The alternative approach is to have a function which sets the icons to new values.

**Comment by Alexander-Miller** [comment]
I've started another overhaul of the icon system now, one that's going to thoroughly simplify things, especially when adding new icons. I'm not done yet, but basically adding a new icon, with all fallbacks and defaults looks like this:
`(treemacs--create-icon :file "warning.png" :var warning :fallback (propertize "• " 'face 'font-lock-string-face))`

Once everything is in a single place I'll go about adding theme support. The current plan is to change this api a bit the icons are automagically defined based on whatever is in a given directory, so adding a theme is as simple as including a new folder and the right icon names.

**Comment by Alexander-Miller** [comment]
Ok, here's my plans on the icon and theme front:

Icons will now be stored in one of two hash maps, depending on whether the current buffer runs in a gui or tui environment. There's no more defvars for file icons, the others keep their icon/icon-png/icon-txt setup. I will do away with icons being resettable to their defaults, loading themes will take precedence.

Themes will be implemented via subdirectories, so loading a theme is as simple as loading whatever in treemacs/icons/$theme. Specifically this is done by iterating over every created icon and switching up the image's `:file` property, assuming that an icon with the same file name exists in the new theme's directory.

That does make things very simple and straightforward for me, but does come with some restrictions. A new theme cannot just add *new* icons, and the file names must all align, which can make things awkward if you want to override one of the vsc icons (though I doubt it's a common case, I assume for themes you'll want mostly to add different dir and root icons). 

Providing the right hooks for when a theme is loaded/unloaded should help fill these gaps.

**Comment by yyoncho** [comment]
Does this mean that all the icons should be contained in the treemacs project or we can define a theme root per component? Native emacs tree widget allows predefining the theme root like this https://github.com/emacs-lsp/lsp-java/blob/master/lsp-java.el#L920 . I am ok if you want to host all icons that the components want to use in treemacs but IMO it might be problematic for the project longterm.

**Comment by Alexander-Miller** [comment]
Nope, the next step is to add a list of directories where themes should be drawn from.

Not sure about component specific parts though. I think at best we can make things buffer-local.

**Comment by yyoncho** [comment]
> Nope, the next step is to add a list of directories where themes should be drawn from.

That would work too.

**Comment by yyoncho** [comment]
One more thing to consider - It would be good if you have built it support for more than one icon per node, like this - 
![Selection_136](https://user-images.githubusercontent.com/13259670/57395922-e83e2080-71d1-11e9-87b7-beacfa8971c2.png) since some of the IDEs have one icon for folder and have an additional icon to indicate whether it is open or not.

**Comment by Alexander-Miller** [comment]
Minor update: some of my designs got screwed over icons weren't `eq` when I thought they would be, so now I'm redesigning some more. The new api is going to look something like this:
`(cl-defmacro treemacs-create-theme (name &key icon-directory base config) ...`

**Comment by Alexander-Miller** [comment]
Got a working version going, uploaded it to the themes branch. Your entry point is https://github.com/Alexander-Miller/treemacs/blob/themes/src/elisp/treemacs-icons.el#L142.

That should give you most of what you need, the only thing I can think of that's missing is easily assigning the icons you create to some variable, currently they're all just inserted into a hash map

About your two-icon proposal. I'd rather just use a single broader icon. Thanks to @Jasu  tt should be possible to pad the file icons pixelwise so they still align with the now non-square dir icons.

**Comment by yyoncho** [comment]
@Alexander-Miller thanks, I will start testing it. 

> About your two-icon proposal. I'd rather just use a single broader icon. Thanks to @Jasu it should be possible to pad the file icons pixelwise so they still align with the now non-square dir icons.

Sure, whatever is easier for you.

**Comment by Alexander-Miller** [comment]
Any news on the theme front? If it didn't break anything important I would like to merge it into master and release a new stable version.

**Comment by yyoncho** [comment]
@Alexander-Miller sorry, I havent tested yet. I thought that you will merge in develop and I was waiting for that.

**Comment by Alexander-Miller** [comment]
Themes are in now. Feedback discussion continues in #470.
