### ISSUE TITLE
Cache imenu results for cursor movements

### ISSUE THREAD

**Issue by minad** [Alexander-Miller/treemacs#288]
If the cursor is moved the imenu is queried many times, which can lead to quite some load for example on lsp servers. The imenu must only be reloaded when real editing happens.

See parts of the discussion at https://github.com/Alexander-Miller/treemacs/issues/283

**Comment by Alexander-Miller** [comment]
Added basic caching. An unmodified buffer will now reuse the results of the last imenu call.

**Comment by minad** [comment]
:+1: thank you!
