### ISSUE TITLE
Is there a way to disable auto flattening of directories?

### ISSUE THREAD

**Issue by FieryCod** [Alexander-Miller/treemacs#292]
@Alexander-Miller thank you for your wonderful package. It's brilliant but there is one thing which is annoying for me.

Question the same as in the title. @Alexander-Miller please help 👍

**Comment by Alexander-Miller** [comment]
Can you give me a concrete use-case? I'm not sure what you mean by here. I do reopen things automatically, but I can't think of a case where I close them.

**Comment by FieryCod** [comment]
![image](https://user-images.githubusercontent.com/14275210/47100107-0ee93980-d237-11e8-9363-c56430e48086.png)

I want to disable flattening of directories and let it be just:
```
abc 
  abc
``` 
instead of `abc/abc`

**Comment by Alexander-Miller** [comment]
Oh, you mean *that* collapsing. Yeah, that's possible. The maximum depth for that is controlled by `treemacs-collapse-dirs`, so you can just set it to zero.

**Comment by FieryCod** [comment]
Thank you very much for the help ;)
