### ISSUE TITLE
[Treemacs] Error on highlight, this shouldn't happen: (wrong-type-argument overlayp nil)

### ISSUE THREAD

**Issue by semla** [Alexander-Miller/treemacs#294]
I am getting `[Treemacs] Error on highlight, this shouldn't happen: (wrong-type-argument overlayp nil)` when I try to enable treemacs-mode.
- I have copied the [use-package example](https://github.com/Alexander-Miller/treemacs#installation).
- I used to use emacs 25.1, but have now built 26.1 to try out treemacs. Don't know alot about building from source but it seems to be working with other stufff

**Comment by Alexander-Miller** [comment]
Does the error go away if you display treemacs-fringe-indicator-mode?

What is the value of `treemacs--fringe-indicator-bitmap`?

Also try again after evaluating the following code and enabling debug-on-error. I'll need a stack trace to debug this.

```
(defun treemacs--update-icon-selection ()
  "Highlight current icon, unhighlight `treemacs--last-highlight'."
  (when (eq major-mode 'treemacs-mode)
    (progn
      (when treemacs-fringe-indicator-mode
        (treemacs--move-fringe-indicator-to-point))
      (-when-let (btn (treemacs-current-button))
        (let* ((pos (max (point-at-bol) (- (button-start btn) 2)))
               (img-selected (get-text-property pos 'img-selected)))
          (treemacs-with-writable-buffer
           (when treemacs--last-highlight
             (let* ((last-pos (- (button-start treemacs--last-highlight) 2))
                    (img-unselected (get-text-property last-pos 'img-unselected)))
               (put-text-property last-pos (1+ last-pos) 'display img-unselected)))
           (when img-selected
             (put-text-property pos (1+ pos) 'display img-selected)
             (setq treemacs--last-highlight btn))))))))
```

**Comment by duianto** [comment]
It might have been fixed, I just updated the packages, and I'm not seeing the error message:
`[Treemacs] Error on highlight, this shouldn't happen: (args-out-of-range 12 12)`

I should have updated the packages before posting, sorry about that 😄

**Comment by Alexander-Miller** [comment]
To be fair I think I only pushed that fix this morning.

**Comment by duianto** [comment]
I had started a draft on this issue yesterday and posted it today, but as the rule goes: pull before push

**Comment by Alexander-Miller** [comment]
Did I forget to close this? I think I did.

**Comment by deb75** [comment]
Hi,

I face this error when trying  `treemacs mode`, with latest treemacs package from melpa (20190211) and emacs 26 (on MS Windows).

**Comment by duianto** [comment]
@deb75: Do you mean that your calling the command `treemacs-mode` in a buffer for example the `*scratch*` buffer?

Because I'm getting this message when I do that:
`[Treemacs] Error on highlight, this shouldn't happen: (wrong-type-argument overlayp nil)`

But that's not how Treemacs is supposed to be used.

You just call `M-x` `treemacs` `RET` and the Treemacs side window opens.

Since a lot of packages are enabled with `treemacs-mode`, I can see that one could come to that conclusion about Treemacs as well, but Treemacs is a side window it's not a mode that's enabled in any buffer.

@Alexander-Miller If `treemacs-mode` is called manually from a non-treemacs buffer, then maybe a message could be shown describing how to use Treemacs, or the Treemacs side window could open (although that might lead to the conclusion that `treemacs-mode` is the command to open Treemacs).

**Comment by deb75** [comment]
Hi,

Thanks for your anweer.

Indeed, it works following your piece of advice.

Regards

**Comment by duianto** [comment]
@Alexander-Miller This issue should probably be reopened, I see now that the original report is the same as reported by dab75.

About calling `treemacs-mode` directly.

My issue report about error messages when collapsing the parent node and expanding it, was unrelated (it's fixed).

**Comment by Alexander-Miller** [comment]
> when I try to enable treemacs-mode.

Boy do I suck at reading comprehension.

> then maybe a message could be shown describing how to use Treemacs, or the Treemacs side window could open

It'd rather not bend around my major-mode in arcane ways to try and do the right thing the way javascript bends the meaning of `{} + []` to prevent a type error. That'd only encourage the wrong behavior. An error message is definitely the way to go. In fact I've got just the right format for it as well:

```
--------------------------
< You're doing it wrong. >
--------------------------
\
\
__
/  \
|  |
@  @
|  |
|| |/
|| ||
|\_/|
\___/

```
