### ISSUE TITLE
Ace-window compatibility

### ISSUE THREAD

**Issue by seagle0128** [Alexander-Miller/treemacs#299]
Hi, I noticed this section in README. 
> Winum compatibility
treemacs will not interfere with winum’s numbering layout, your first window will always remain your first window.

Is it any possible to support the same feature for  `ace-window`? The related codes are in `ace-window-display-mode`.

**Comment by Alexander-Miller** [comment]
Good idea. Patch will drop in a couple of minutes.

**Comment by seagle0128** [comment]
Thanks for your quick fixing!

**Comment by rswgnu** [comment]
The base use case of ace-window is to quickly move to a desired window.  Moving to the Treemacs window when there are many windows on screen can be especially important.  Therefore, ace-window users are most likely to want to be able to select the Treemacs window as a target for movement and therefore not have it be part of the ignored-buffers list.  When ace-window is used to display a buffer in a window, one simply chooses a window by ace-window id easily ignoring the Treemacs window.

So I would recommend reversing this patch as it presently causes that other problem that I CCed you on that is ace-window's fault but is triggered by this addition to Treemacs.

**Comment by seagle0128** [comment]
I don't think reverting this patch is a good idea. `trremacs` provides a method to select itself, and the first window should be `1` as `winum` does for consistence. Miller also provided a workaround of recovering the old behavior in #301.

**Comment by rswgnu** [comment]
Treemacs could be window 0 under winum and all would stay consistent plus its window would be selectable like any other by winum.  Can you explain it some detail what you think any issue would be it provide a recipe for replicating a problem?

-- Bob

**Comment by Alexander-Miller** [comment]
> Treemacs could be window 0 under winum

No, it couldn't. By default winum's scope is to assign numbers to all windows in all frames (or maybe just the visible ones?). Treemacs however assigns every frame its own unique treemacs buffer. That means if you had 2 frames with 1 treemacs window each you'd have 2 windows getting the same number.

Treemacs used to be window number 0 by default, and I tried resolving that conflict when it first came to light in spacemacs, but couldn't find a good solution. I don't see how the status quo is much different anyway. `M-0` would usually select window 0, just bind it to `treemacs-select-window`. That's how it's handled in spacemacs with both treemacs and neotree.
