### ISSUE TITLE
Consider using all-the-icons

### ISSUE THREAD

**Issue by asok** [Alexander-Miller/treemacs#3]
Hi,
actually I'm not using your package but just by browsing through it I thought it's worth mentioning [all-the-icons](https://github.com/domtronn/all-the-icons.el) to you in case you're not aware of it :)

**Comment by Alexander-Miller** [comment]
Yeah, I actually tried it out a while ago when it was posted on /r/emacs. Had some font issues then, but today things seemed to go well.

It's potentially not quite as pretty as the .png's I'm using (more than 1 color), but I'll see if I can use it to fill the gaps.

**Comment by jsmestad** [comment]
I'd like to use `all-the-icons` instead of images if its supported (or can be)

**Comment by Alexander-Miller** [comment]
[This screenshot](https://i.imgur.com/UjSzf1h.png), the icon of the file image in particular, shows why I will not support all-the-icons *directly*. You are of course free to [use your own icons](https://github.com/Alexander-Miller/treemacs#custom-icons) as you please.

**Comment by jsmestad** [comment]
@Alexander-Miller yeah I read that in the README. How though would you replace ALL the icons with the font instead of just unsupported ones?

**Comment by Alexander-Miller** [comment]
You'll need to get your hands dirty. All-the-icons stores its icons in lists like `all-the-icons-icon-alist`. Each item consists of first the file extension and then a function and arguments to call to get the icon:

```
(let* ((item   (car all-the-icons-icon-alist))
        (extension (car item))
        (icon (apply (cdr item))))
  (cons extension icon))
```

So you can just iterate over that. Only problem is that the extension is a regexp, so youll need to clean up characters like `\$.^`.

Defining custom icons will also overwrite the builtins.

**Comment by brettatoms** [comment]
It must be possible to set the icon size somehow since when `neotree` uses `all-the-icons` the text appears to be aligned.

**Comment by Alexander-Miller** [comment]
[Not sure I'd call neotree with all-the-icons an improvement](https://imgur.com/a/7zR7S).

You can make the text after the icon appear somewhat even by separating text and icon with a tab, given a learge enough `tab-width` value. The icons themselves will still have a different width and the tab will make the distance between icon and text slightly too large IMO.

Of course if there some specific icon thats available in all-the-icons that youre missing in treemacs its better to open an issue and ask for just that. A good chunk of the icon in treemacs are adapted from all-the-icons as it is.

**Comment by nealot** [comment]
[Doom-Emacs](https://github.com/hlissner/emacs-doom-themes/tree/screenshots) has managed to create a very nice looking Neotree theme using all the icons. Could something similiar be added to treemacs?

**Comment by Alexander-Miller** [comment]
From what I saw when I tried doom myself for a short while it has the same space problems once you see different types of icons.

If you want to see for yourself you can try the code below, though at this point I'd prefer people tell me what icons missing.

```
(dolist (item all-the-icons-icon-alist)
  (let* ((extension (car item))
         (icon (apply (cdr item))))
    (ht-set! treemacs-icons-hash 
             (s-replace-all '(("\\" . "") ("$" . "") ("." . "")) extension)
             (concat icon " "))))
```

**Comment by Alexander-Miller** [comment]
I've just tried doom again. Looks like it's using a  small subset of icons which are all the same size, at least in the default config, so I guess you're not missing out on much.

I also tried opening my performance test directory in doom. It contains close to 3000 files and directories and takes nearly 200ms to open with treemacs. Doom's neotree needs about 90 seconds.
