### ISSUE TITLE
treemacs-visit-node-ace issue

### ISSUE THREAD

**Issue by mpanarin** [Alexander-Miller/treemacs#301]
after fix for https://github.com/Alexander-Miller/treemacs/issues/299
I have an issue now, that if I have treemacs window open and 2 other windows, treemacs-visit-node-ace will always open a file in the first window without popping regular ace window selection. No errors or messages.

**Comment by Alexander-Miller** [comment]
I think we can safely sort this under "not my fault". I haven't looked at its code to confirm my suspicions, but it is most likely an error in ace-window's calculations: There's 3 windows, but 1 is ignored, so it thinks there is only 1 valid target, and instantly jumps. This would've been correct in most cases, but not when focus is on the ignored window. In that case you will have 2 jump targets, and should see a selection.

I'll raise the issue with ace-window.

**Comment by Alexander-Miller** [comment]
In the meanwhile you can `(setq aw-ignored-buffers (delete 'treemacs-mode aw-ignored-buffers))` to restore the old behaviour.

**Comment by Alexander-Miller** [comment]
The issue has now been fixed in ace-window.
