### ISSUE TITLE
Finish and consolidate extension API

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#309]
Everything that's left after the initial push in #263.

**Comment by Alexander-Miller** [comment]
ping @yyoncho https://github.com/Alexander-Miller/treemacs/commit/fc937d8bb8b96ada24d72d77e4ea0faf3708478a should give you what you need to begin your migrations.

There's some minor issues with the fringe indicator that I need to track down, but other than that everything seems to work fine.

**Comment by yyoncho** [comment]
Thanks a lot! I am in the middle of big `lsp-mode` restructoring, when it is ready I will utilize treemacs for the new `lsp-java` views.

**Comment by Alexander-Miller** [comment]
I think this is done.

By now I do have more plans to move away from macros to a polymorphism based approach, but that'll be elaborated in a new ticket.

**Comment by yyoncho** [comment]
> By now I do have more plans to move away from macros to a polymorphism based approach

As a side note, in lsp-treemacs I have created a wrapper over treemacs extension api which is purely data-driven. Something like:
```
(list :name "Name"
      :icon 'dir-open
      :code-actions <list of code actions>
      :children `((...
```

This supports async functions for the children.
