### ISSUE TITLE
wrong-type-argument listp fatal:

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#314]
Messages buffer:
```
Error running timer ‘treemacs--apply-deferred-git-state’: (wrong-type-argument listp fatal:) [2 times]
```

**Comment by Alexander-Miller** [comment]
Can you provide a stacktrace? I need to know which part is not a list.

**Comment by Alexander-Miller** [comment]
> fatal

I should've read that part. Is this the same bug as in #312?

**Comment by Compro-Prasad** [comment]
Seems like it. Haven't confirmed the fix.

**Comment by Compro-Prasad** [comment]
Can I close this? I no more get any error.

**Comment by Alexander-Miller** [comment]
¯\\\_(ツ)\_/¯
