### ISSUE TITLE
treemacs-collapse-dirs Error when opening treemacs

### ISSUE THREAD

**Issue by CSRaghunandan** [Alexander-Miller/treemacs#315]
I'm getting the following error when I open treemacs:

`treemacs--collapse-dirs: Wrong type argument: number-or-marker-p, nil`

This what I see when I enable debug on error:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  button-start(nil)
  treemacs--collapse-dirs((("/home/csraghunandan/.emacs.d/anaconda-mode" "/0.1.13" "/home/csraghunandan/.emacs.d/anaconda-mode/0.1.13")))
  treemacs--expand-root-node(#<marker at 3 in  *Treemacs-Framebuffer-1*>)
  treemacs-goto-file-node("/home/csraghunandan/.emacs.d/setup-files/setup-tre..." #s(treemacs-project :name ".emacs.d" :path "/home/csraghunandan/.emacs.d"))
  treemacs--follow()
  treemacs--init()
  treemacs-select-window()
  funcall-interactively(treemacs-select-window)
  call-interactively(treemacs-select-window nil nil)
  command-execute(treemacs-select-window)
```

This is my treemacs configuration: https://github.com/CSRaghunandan/.emacs.d/blob/master/setup-files/setup-treemacs.el

This is my emacs environment:

```
Emacs version: GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, X toolkit, Xaw scroll bars)
 of 2018-12-05, built using commit 9a162e276e377f112173bbe099900358f157edd1.

./configure options:
  --with-modules --with-rsvg --with-dbus --with-imagemagick --without-pop --with-xft --with-x-toolkit=lucid --with-xml2 --with-libotf

Features:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON LCMS2 GMP
```

**Comment by Alexander-Miller** [comment]
Difficult to say why this is going wrong. Can you show me what the file structure of your projects looks like?

**Comment by CSRaghunandan** [comment]
I'm not sure if this got anything to do with file structure for projects. This is happening on any project I open.

One such project is my own emacs config which is hosted here: https://github.com/CSRaghunandan/.emacs.d

**Comment by Alexander-Miller** [comment]
Is your treemacs up-to-date? I did fix a bug that looked quite similar a couple weeks back.

If that doesn't work:
 * Disable follow-mode and direrctory flattening.
 * Open a buffer in the directory that would be flattened like .emacs.d/anaconda-mode from your example.
 * Call treemacs-follow manually.
 * What happens?

**Comment by CSRaghunandan** [comment]
Okay, the latest version of treemacs, the error seems to be isolated only to my` .emacs.d` project.

Follow mode is working as intended even after I get the error. 

I  tried commented out the `treemacs-collapse-dir` variable from my emacs configuration and I'm not getting any errors when I open my .emacs.d project

I tried to open a buffer in the anaconda-mode directory after disabling follow-mode and directory flattening and enabled follow-mode again and nothing happened. Maybe this is because anaconda-mode is in my `.gitignore` file?

**Comment by Alexander-Miller** [comment]
> I tried commented out the treemacs-collapse-dir

You have to set it vaue to zero to disable it.Maybe this is because anaconda-mode is in my .gitignore file?

> Maybe this is because anaconda-mode is in my .gitignore file?

That's only relevant for git-mode.

> I tried to open a buffer in the anaconda-mode directory after disabling follow-mode and directory flattening and enabled follow-mode again and nothing happened

Try the following: disable collapsing and then run the following code:
```
(with-current-buffer (treemacs-get-local-buffer)
  (treemacs-goto-file-node "/path/to/anaconda-mode"))
```

Is point moved correctly? Does the code return a marker?

**Comment by CSRaghunandan** [comment]
I disabled collapsing and ran the code snippet above with the right path and I got `nil` as the output.

I'm not really sure what that means? Also, I don't see the anaconda-mode directory and a few other directories are missing as well. Pls check the image below

![treemacs-emacs d](https://user-images.githubusercontent.com/5226809/50203767-97e03680-0388-11e9-8100-ea06d7be88b2.png)

**Comment by CSRaghunandan** [comment]
> Are these directories all ignored in git and did you make treemacs hide gitignored directories? That would explain what's going on here.

Yes, I had completely forgotten I had added this to my configuration. I commented out that line from my emacs config and treemacs is no longer showing any errors when I open my project.  I also found out that gitignored files are grayed out now, which is really neat and I prefer this over hiding them completely.

**Comment by fth86** [comment]
I am encountering a similar problem on having treemacs trying to navigate to a file:

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  goto-char(nil)
  (prog1 (point) (goto-char (treemacs-project->position project)))
  (let* ((start (prog1 (point) (goto-char (treemacs-project->position project)))) (path-minus-root (->> project (treemacs-project->path) (length) (substring path))) (dir-parts (nreverse (s-split (f-path-separator) path-minus-root 'omit-nulls))) (goto-path (if dir-parts (treemacs--parent path) path)) (counter (length dir-parts)) (manual-parts nil) (shadow-node nil)) (while (and (> counter 0) (or (null shadow-node) (null (treemacs-shadow-node->position shadow-node)))) (setq shadow-node (treemacs-get-from-shadow-index goto-path) goto-path (treemacs--parent goto-path) counter (1- counter)) (push (pop dir-parts) manual-parts)) (let* ((btn (if (= 0 counter) (treemacs-project->position project) (treemacs-shadow-node->position shadow-node))) (search-result (if manual-parts (save-match-data (treemacs--follow-each-dir btn manual-parts)) btn))) (if (eq 'follow-failed search-result) (prog1 nil (goto-char start)) (treemacs--evade-image) (hl-line-highlight) (set-window-point (get-buffer-window) (point)) search-result)))
  treemacs-goto-file-node("/home/X/system/emacs/modules/ui/general/c..." #s(treemacs-project :name "system" :path "/home/X/system"))
  treemacs--follow()
  treemacs--init()
  treemacs()
  funcall-interactively(treemacs)
  call-interactively(treemacs nil nil)
  command-execute(treemacs)
```

This happens consistently for a time, after which it works as intended.

I'm on melpa version 20181216.2005.

**Comment by CSRaghunandan** [comment]
@Alexander-Miller I can confirm that this issue is fixed in the latest commit.

Thank you
