### ISSUE TITLE
Filewatch and automatic git process spawning

### ISSUE THREAD

**Issue by Luki21** [Alexander-Miller/treemacs#316]
When running on WSL treewatch starts every 5000ms a git process for every expanded git project without any change to the files, which results in high cpu load:

![image](https://user-images.githubusercontent.com/42112531/50053938-cec20c80-013c-11e9-9451-df509604c218.png)

**Comment by Alexander-Miller** [comment]
Ok , let's and and track this one down. Call `trace-function` on `treemacs--filewatch-callback`, see what that outputs.

**Comment by Luki21** [comment]
Here is the output but i dont understand why that file would be changed

1 -> (treemacs--filewatch-callback ((1 . 0) changed "/mnt/c/*ProjectPath*/.git"))
1 <- treemacs--filewatch-callback: nil
======================================================================
1 -> (treemacs--filewatch-callback ((1 . 0) changed "/mnt/c/*ProjectPath*/.git"))
1 <- treemacs--filewatch-callback: nil
======================================================================
1 -> (treemacs--filewatch-callback ((1 . 0) stopped "/mnt/c/*ProjectPath*"))
1 <- treemacs--filewatch-callback: nil
======================================================================
1 -> (treemacs--filewatch-callback ((1 . 0) changed "/mnt/c/*ProjectPath*/.git"))
1 <- treemacs--filewatch-callback: nil
======================================================================
1 -> (treemacs--filewatch-callback ((1 . 0) changed "/mnt/c/*ProjectPath*/.git"))
1 <- treemacs--filewatch-callback: nil
======================================================================
....
....

**Comment by Alexander-Miller** [comment]
I've no idea what's going on in there either, but I don't think we'll miss anything if changes inside .git are ignored. Try evaluating the following and see if it helps:

```
(define-inline treemacs--std-ignore-file-predicate (file _)
  (declare (side-effect-free t) (pure t))
  (inline-letevals (file)
    (inline-quote
     (s-matches? (rx bol
                     (or (seq (or ".#" "flycheck_") (1+ any))
                         (seq (1+ any) "~")
                         (seq "#" (1+ any) "#")
                         (seq (1+ any) ".git")
                         (or "." ".."))
                     eol)
                 ,file))))
```

**Comment by Luki21** [comment]
Yeah it worked, thanks.

How do i achieve that permanently. When i put it in my init.el i have to manually eval it or it won't work.

**Comment by Alexander-Miller** [comment]
Pretty simple: just update when the new version is built.

>  When i put it in my init.el i have to manually eval it or it won't work.

Probably because it's overwritten when treemacs is actually loaded. To make that work you'd have to use `with-eval-after-load`. It'd be better for you startup time too, since you don't load everything up-front.
