### ISSUE TITLE
icon background problem again

### ISSUE THREAD

**Issue by avkoval** [Alexander-Miller/treemacs#318]
Hi @Alexander-Miller 
I am not sure what happen but now with any dark theme the icons always display light background, no matter what I do (refreshing theme does not help)

![](http://scr.ua2web.com/avk/ss_20190104162639_zcarcUlEgMWTO6QTolWx.png)

How to debug this issue?
WBR, Alex

**Comment by Alexander-Miller** [comment]
Something's not right with the code that updates these colors on a theme change. I'll investigate.

**Comment by avkoval** [comment]
Yes, fixed! Thank you @Alexander-Miller, thank you for excellent package, and Happy New Year!
