### ISSUE TITLE
icons missing: treemacs-dir incorrect when installed through elpa

### ISSUE THREAD

**Issue by bilemon** [Alexander-Miller/treemacs#319]
When installing from elpa, the `treemacs-dir` constant is set to `/home/<user>/.emacs.d/`.
This causes rendering errors with the following error:

     Cannot find image file ‘/home/<user>/.emacs.d/icons/emacs.png’

I believe the issue is that the `.elc` files are generated with an incorrect path. I'm not sure if there is something I am doing wrong with my system. I have found no other issues which would point to an incorrect `treemacs-dir` path, which makes me hesitate to report this as a bug. That being said, installing through elpa on a fresh system yields the above errors.

Can someone confirm this error on their system?
Is there a way to override the path in a startup script?

**Comment by Alexander-Miller** [comment]
> When installing from elpa

You mean melpa, right? 

> I believe the issue is that the .elc files are generated with an incorrect path.

Quick test shows it works on my end. It looks like the path is set 2 steps too far back, normally it should be emacs.d/elpa/treemacs-version. And that only happens when the currently loaded file lies in ".../treemacs/src/elisp/", which is only the case when you load a local dev version.

Do you use a non-standard package manager? 
Can you confirm that the actual .el and .elc files are where they should be.

> Is there a way to override the path in a startup script?

You should be able to just set your own value for treemacs-dir *before* treemacs is loaded.

**Comment by bilemon** [comment]
Yes, I meant melpa. Apologies.

I manually removed treemacs-<date>, and reinstalled from melpa. Seems to work now.

Sorry for the erroneous report. I'm not sure what caused the initial bug.

**Comment by Alexander-Miller** [comment]
¯\\\_(ツ)\_/¯

**Comment by Technologicat** [comment]
Just ran into the same issue using treemacs in the develop branch of Spacemacs, installing treemacs in the default way. Recompiling treemacs fixed it. Thanks for the info!

("The default way" in Spacemacs is to add `treemacs` to `dotspacemacs-configuration-layers` in the Spacemacs config. It should download from MELPA, but somehow my `treemacs-dir` still got set to `~/.emacs.d/`.)

**How to fix**, if someone else runs into this:

 - Check your treemacs-dir: `SPC h d v treemacs-dir RET`. If the value looks wrong (see above comments), proceed.
 - Find your treemacs installation. The help window should have a link for the `.el` file where the variable is defined. `RET` on that to open the file.
 - `C-0 M-x byte-recompile-directory RET`. The zero prefix argument forces a recompile of all `.el` files in the current directory.
 - Restart emacs. Now icons should appear in treemacs.

(This fix relies on the fact that `treemacs-dir` is set at compile time.)

**Comment by Alexander-Miller** [comment]
> This fix relies on the fact that treemacs-dir is set at compile time.

I think I'll be dropping this part soon. Compile time constants sounds like a neat idea, but if they cause bugs like yours, then I see no reason not to set the directory at load-time.
