### ISSUE TITLE
Create a keybinding to always expand the current directory

### ISSUE THREAD

**Issue by axelson** [Alexander-Miller/treemacs#323]
As far as I can tell there is no command to always expand the current directory. Although really I want a keybinding to expand the current directory, move into it (without changing the root), and select the first file/item inside, but I think I can build that on top of a command that would always expand the current directory. So it would be similar to `treemacs-TAB-action`, but always expanding the directory and never closing it.

**Comment by Alexander-Miller** [comment]
Let's make sure we're on the same page: you want something like `treenacs-toggle-node`, except without the entries for open nodes:

```
(treemacs-do-for-button-state
   :on-root-node-open   (treemacs--collapse-root-node btn arg)
   :on-root-node-closed (treemacs--expand-root-node btn)
   :on-dir-node-open    (treemacs--collapse-dir-node btn arg)
   :on-dir-node-closed  (treemacs--expand-dir-node btn :recursive arg)
   :on-file-node-open   (treemacs--collapse-file-node btn arg)
   :on-file-node-closed (treemacs--expand-file-node btn arg)
   :on-tag-node-open    (treemacs--collapse-tag-node btn arg)
   :on-tag-node-closed  (treemacs--expand-tag-node btn arg)
   :on-tag-node-leaf    (progn (other-window 1) (treemacs--goto-tag btn))
   :on-nil              (treemacs-pulse-on-failure "There is nothing to do here."))
```
And it should also call forward-line?

**Comment by axelson** [comment]
Yes, although I think I'll build my own function that calls forward-line because I can see the first function being generally useful for others.

**Comment by Alexander-Miller** [comment]
I've now added the `treemacs-move-forward-on-expand` option.

**Comment by axelson** [comment]
Awesome, thanks!

**Comment by Alexander-Miller** [comment]
Except that the code was broken because I forgot to stage a final refactoring :facepalm: . It'll work *now*.

**Comment by axelson** [comment]
It's working, thanks! :heart:
