### ISSUE TITLE
Show open buffers

### ISSUE THREAD

**Issue by ffffwh** [Alexander-Miller/treemacs#325]
It is metioned in README.md
> It also opens the potential for concurrent display not only of the file system, but e.g. the currently open buffers

Is it implemented (and how to configure) or is there any road map?

Actually I have tried 'dired-sidebar + ibuffer-sidebar' (github.com/jojojames), but it feels not as mature as treemacs.

**Comment by Alexander-Miller** [comment]
> It also opens the **potential**

Emphasis mine. So no, there's nothing just yet, but I've now begun work on it. You can track it in #326 .
