### ISSUE TITLE
Stuck in empty directory

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#327]
#### Description :octocat:
Stuck after `l` (`treemacs-root-down`) to an empty directory.

#### Reproduction guide :beetle:

With a project open that contains an empty directory:
```
project
  dir1
```
- Pressing `l` (lowercase L)
- Changes the project root to `dir1`

*Observed behaviour:* :eyes: :broken_heart:

One is now stuck.
- `h` (`treemacs-root-up`) says: `user-error: No more buttons`
- `u` (`treemacs-goto-parent-node`) says: `[Treemacs] There is no parent to move up to.`

*Expected behaviour:* :heart: :smile:

`h` and `u` should probably move back to the parent directory called `project`.

#### Notes 📓 

If one tries to remove the project `C-p d` then this message is shown:
`user-error: No more buttons`

#### System Info :computer: :information_source:

- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 00e870815)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp git helm html ibuffer markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
A possibly related issue is if one adds another project:
- `C-p a` `c:/project` `project`
- unfolds the project (`TAB`) (in this case it has 3 directories):
```
project
  dir1
  dir2
  dir3
```
The Treemacs window now looks like this:
```
dir1

project
  dir1
  dir2
  dir3
```
- if one now selects the stuck `dir1` project (`C-k`) and removes it `C-p d`
Then both project names are removed and only the directories are visible.
```
  dir1
  dir2
  dir3
```

I'm not sure if this should be a separate issue, or maybe if the initial "stuck" issue is solved, then maybe this second issue won't occur.

**Comment by Alexander-Miller** [comment]
I need some time to investigate this. To get yourself unstuck you can use (the yet undocumented) `treemacs-edit-workspaces`.

**Comment by duianto** [comment]
Take your time.

The edit/finish workspaces commands worked 👍 

It also works to restart Emacs. Then `h` moves up from the single project `dir1` (that was stuck before the restart), to the parent directory `project`.

Correction `u` might be working as intended, it seems to go to the selected dir/files parent, up to the project header.

**Comment by Alexander-Miller** [comment]
Fix is pushed. Hoe I caught everything.

> Restarting Emacs brings back the project header.

Shouldn't be necessary. When you're dealing with display issues like this just killing the buffer with Q is sufficient to get back to a clean state.

**Comment by duianto** [comment]
Yeah your right. Before the fix: `Q` (`treemacs-kill-buffer`) or `SPC b d` (`spacemacs/kill-this-buffer`) and reopening Treemacs `SPC f t`, made `h` navigate to the parent directory.

Now that I've updated the packages, `h` works as expected, thanks.

**Comment by duianto** [comment]
Both project headers being removed doesn't occur anymore, so it might have been related.
