### ISSUE TITLE
Error message when opening Treemacs without a project, after Spacemacs startup

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#329]
The first time Treemacs is opened (`SPC f t`) after (re)starting Spacemacs.

When no previous project has been defined, then these messages are shown:
```
[Treemacs] Could not restore saved state, found error in line '* Default Workspace':
Cannot end with a project or workspace name
Broken state was saved to c:/Users/username/.emacs.d/.cache/treemacs-persist-at-last-error
[Treemacs] Window width has been unlocked.
```

(The `[Treemacs] Window width has been unlocked.` message is unrelated since it also appears (as the only message) when a previous project was defined. It was included to show all messages that appeared.)

The "Project root: " prompt appears as expected, so maybe it's just a warning message.

Handling projects (add/remove/rename) seems to be working as expected.

#### Reproduction guide :beetle:

- Remove all projects from the Treemacs window, by selecting them and pressing `C-p d`
- Restart Spacemacs `SPC q r`
- Open the `*Messages*` buffer `SPC b m`
- Open Treemacs `SPC f t`

#### System Info :computer:

The packages were updated before submitting this issue and the Treemacs version was:
`treemacs-20190127.1059`

- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e8a6bc269)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp git helm html ibuffer markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by Alexander-Miller** [comment]
> Emacs crashes when I try to open treemacs

You mean a full-blown crash to desktop? Now that's some serious business.

Let's start with the simple things. When you start emacs make sure that `(featurep 'treemacs)` evaluates to nil. Then `(require 'treemacs)` to just load treemacs without starting it. Does that work?

**Comment by Alexander-Miller** [comment]
I was unable to reproduce this with an empty persist file. Starting treemacs showed the prompt for the first project, as expected.

Please reopen if you're still seeing the problem.
