### ISSUE TITLE
Scripts won't work on windows? 

### ISSUE THREAD

**Issue by zijianyue** [Alexander-Miller/treemacs#333]
(setq treemacs-collapse-dirs 3)
 (setq treemacs-git-mode t)
but the dirs with one sub dir are not collapsed, the modified file has no indicate at all
![image](https://user-images.githubusercontent.com/6119928/52032377-972bea00-255b-11e9-9092-509540d64577.png)

emacs 26.1 WIN7 X64 , the latest treemacs clone from git

**Comment by Alexander-Miller** [comment]
> (setq treemacs-git-mode t)

[This is wrong.](https://github.com/Alexander-Miller/treemacs#git-mode)

> emacs 26.1 WIN7 X64 , the latest treemacs clone from git

What's your python version? The scripts need python 3. You can test if the scripts work like this:
```
python /path/to/treemacs-git-status.py /some/repository 3000 ""
```

**Comment by zijianyue** [comment]
Traceback (most recent call last):
  File "c:/Users/g00280886/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-git-status.py", line 10, in <module>
    STDOUT    = sys.stdout.buffer
AttributeError: 'file' object has no attribute 'buffer'
:python --version
Python 2.7.15

**Comment by zijianyue** [comment]
It still won't work.

[14:40:27] /g/cquery/src:python --version
Python 3.7.2
[14:40:41] /g/cquery/src:python  /c/Users/myname/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-git-status.py /g/cquery 3000 ""
(("M" . "g:/cquery/src/cache_manager.cc")("M" . "g:/cquery/src"))[14:41:09] /g/cquery/src:
[14:41:15] /g/cquery/src:git --version
git version 2.20.1.windows.1
[14:42:19] /g/cquery/src:
![image](https://user-images.githubusercontent.com/6119928/52035836-643b2380-2566-11e9-83cf-00c94e620ad2.png)

**Comment by Alexander-Miller** [comment]
Next tests: 

What do the docs say about `treemacs--git-status-process-function` and `treemacs--git-status-parse-function`? It should say something like "treemacs--git-status-parse-function is a function alias for treemacs--parse-git-status-extended" in both cases.

What's the output of
```
(-> "/g/cquery"
    (treemacs--git-status-process-function)
    (treemacs--git-status-parse-function))
```
Btw to use python3 in treemacs you just need to adjust the value of `treemacs-python-executable`.

**Comment by zijianyue** [comment]
OK, the treemacs-git-mode work now by setting treemacs-python-executabl to python3.
But the treemacs-collapse-dirs still won't work now, why ?
![image](https://user-images.githubusercontent.com/6119928/52039026-55586f00-256e-11e9-8844-8118430b04be.png)

**Comment by Alexander-Miller** [comment]
Let's see:
```
(-> "/test/project"
    (treemacs--collapsed-dirs-process)
    (treemacs--parse-collapsed-dirs))
```

**Comment by zijianyue** [comment]
(-> "G:\\test-treemacs"
    (treemacs--collapsed-dirs-process)
    (treemacs--parse-collapsed-dirs))
returns nil

**Comment by Alexander-Miller** [comment]
That should've found something. Let's look at the python: 

```
python .../treemacs-dirs-to-collapse.py "G:\test-treemacs" 3 t
```

**Comment by zijianyue** [comment]
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect.

**Comment by Alexander-Miller** [comment]
> `from posixpath import join`

Try changing that to `from path`. 

Let's try some debug output as well:
```
def dir_content(path):
    ret = []
    print("Get content of " + path)
    for item in listdir(path):
        print("Item " + item)
        full_path = join(path, item)
        print("Full path " + item)
        if os.access(full_path, os.R_OK) and (SHOW_ALL or item[0] != '.'):
            ret.append(full_path)
    print("Finish")
    return ret
```

**Comment by zijianyue** [comment]
Get content of g:/test-treemacs
Item 1
Full path 1
Finish
(Get content of g:/test-treemacs/1
Item 2
Full path 2
Finish
Get content of g:/test-treemacs/1/g:/test-treemacs/1/2
Traceback (most recent call last):
  File "c:/Users/g00280886/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-dirs-to-collapse.py", line 53, in <module>
    main()
  File "c:/Users/g00280886/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-dirs-to-collapse.py", line 40, in main
    content     = dir_content(collapsed)
  File "c:/Users/g00280886/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-dirs-to-collapse.py", line 17, in dir_content
    for item in listdir(path):
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'g:/test-treemacs/1/g:/test-treemacs/1/2'

**Comment by zijianyue** [comment]
Traceback (most recent call last):
  File "c:/Users/g00280886/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-dirs-to-collapse.py", line 3, in <module>
    from path import join
ModuleNotFoundError: No module named 'path'

**Comment by Alexander-Miller** [comment]
> 'g:/test-treemacs/1/g:/test-treemacs/1/2'

Something seems to be wrong with the posixpath.join implementation on your end. Can you reproduce the following bits in the repl:

```
❯❯❯ python
Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from os.path import join
>>> join("/A/B/C", "/A/B/C/D")
'/A/B/C/D'
>>> from posixpath import join as pjoin
>>> pjoin("/A/B/C", "/A/B/C/D")
'/A/B/C/D'
```

**Comment by zijianyue** [comment]
I'm on Chinese spring festival these days ,about 8 days later ,I'll try it.

**Comment by zijianyue** [comment]
G:\Python3>python --version
Python 3.7.2

G:\Python3>python
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from os.path import join
>>> join("/A/B/C", "/A/B/C/D")
'/A/B/C/D'
>>> from posixpath import join as pjoin
>>> pjoin("/A/B/C", "/A/B/C/D")
'/A/B/C/D'
>>>

**Comment by Alexander-Miller** [comment]
> \>>> join('g:/A', 'g:/A/B')
> 'g:/A/g:/A/B'

Paths need to start with a `/` for this to work. That should be fixable on my end.

**Comment by Alexander-Miller** [comment]
You closed too early, we still have some testing to do. I don't have a windows machine, so I will need your help to fix this. Try the following version of the script:

```python
from os import listdir
from os.path import abspath, isdir, isfile
from posixpath import join
import sys
import os

ROOT     = sys.argv[1]
LIMIT    = int(sys.argv[2])
SHOW_ALL = sys.argv[3] == 't'


if sys.platform == 'windows':
    def join_dirs(d1,d2):
        missing_slash = False
        if not d1.starts_with("/"):
            missing_slash = True
            d1 = "/" + d1
        if not d2.starts_with("/"):
            missing_slash = True
            d2 = "/" + d2
        joined = join(d1, d2)
        if missing_slash:
            return joined[1:]
        else:
            return joined
else:
    def join_dirs(d1,d2):
        return join(d1,d2)

if LIMIT <= 0:
    exit(0)

def dir_content(path):
    ret = []
    for item in listdir(path):
        full_path = join_dirs(path, item)
        if os.access(full_path, os.R_OK) and (SHOW_ALL or item[0] != '.'):
            ret.append(full_path)
    return ret

def main():
    out  = sys.stdout
    dirs = [d for d in dir_content(ROOT) if isdir(d)]
    out.write("(")
    for current_dir in dirs:
        content   = dir_content(current_dir)
        collapsed = current_dir
        steps     = []
        depth     = 0
        while True:
            if len(content) == 1 and isdir(content[0]):
                single_path = content[0]
                collapsed   = join_dirs(collapsed, single_path)
                content     = dir_content(collapsed)
                depth      += 1
                steps.append(single_path)
                if depth >= LIMIT:
                    break
            else:
                break
        if depth > 0:
            final_dir      = steps[-1]
            display_suffix = final_dir[len(current_dir):]
            out.write("(" + '"' + current_dir + '" ' + '"' + display_suffix + '" ' + '"' + '" "'.join(steps) + '")')
    out.write(")")

main()
```

**Comment by Alexander-Miller** [comment]
Scratch that, I just had a better idea, try that instead:
```python
from os import listdir
from os.path import isdir
from posixpath import join
import sys
import os

ROOT     = sys.argv[1]
LIMIT    = int(sys.argv[2])
SHOW_ALL = sys.argv[3] == 't'

if LIMIT <= 0:
    exit(0)

def dir_content(path):
    ret = []
    for item in listdir(path):
        full_path = join("/", path, item)
        if os.access(full_path, os.R_OK) and (SHOW_ALL or item[0] != '.'):
            ret.append(full_path)
    return ret

def main():
    out  = sys.stdout
    dirs = [d for d in dir_content(ROOT) if isdir(d)]
    out.write("(")
    for current_dir in dirs:
        content   = dir_content(current_dir)
        collapsed = current_dir
        steps     = []
        depth     = 0
        while True:
            if len(content) == 1 and isdir(content[0]):
                single_path = content[0]
                collapsed   = join("/", collapsed, single_path)
                content     = dir_content(collapsed)
                depth      += 1
                steps.append(single_path)
                if depth >= LIMIT:
                    break
            else:
                break
        if depth > 0:
            final_dir      = steps[-1]
            display_suffix = final_dir[len(current_dir):]
            out.write("(" + '"' + current_dir + '" ' + '"' + display_suffix + '" ' + '"' + '" "'.join(steps) + '")')
    out.write(")")

main()

```

**Comment by zijianyue** [comment]
It seems still can't work well now, but no OSError: [WinError 123] disappeared , only a "(" was outputted instead.

![image](https://user-images.githubusercontent.com/6119928/52606635-49de3f80-2eae-11e9-8486-73365d209bf2.png)

[10:06:59] /g: python /c/Users/g00280886/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-dirs-to-collapse.py "G:\test-treemacs" 3 t
([10:08:19] /g:

**Comment by Alexander-Miller** [comment]
Looks like my better idea was wrong. Try the first script.

> sys.platform == 'windows'

And make sure that this branch is taken.

**Comment by zijianyue** [comment]
Still not work.

([14:25:26] /g: python /c/Users/me/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-dirs-to-collapse.py "G:\test-treemacs" 3 t
d1:G:\test-treemacs
d2:1
joined[1:]:1
([14:28:34] /g:

The code I have edited:
``` python
if sys.platform == 'win32':
    def join_dirs(d1,d2):
        print("d1:" + d1)
        print("d2:" + d2)
        missing_slash = False
        if not d1.startswith("/"):
            missing_slash = True
            d1 = "/" + d1
        if not d2.startswith("/"):
            missing_slash = True
            d2 = "/" + d2
            joined = join(d1, d2)
        if missing_slash:
            print("joined[1:]:" + joined[1:])
            return joined[1:]
        else:
            print("joined:" + joined)
            return joined
else:
    def join_dirs(d1,d2):
        return join(d1,d2)
```

**Comment by Alexander-Miller** [comment]
My bad. This part is wrong, you should delete it.
```python
 if not d2.startswith("/"):
    missing_slash = True
    d2 = "/" + d2
```

The line `joined = join(d1, d2)` is also incorrectly indented in your example.

**Comment by zijianyue** [comment]
It reported error:
[16:16:58] /g: python /c/Users/me/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-dirs-to-collapse.py "G:\test-treemacs" 3 t
d1:G:\test-treemacs
d2:1
joined[1:]:G:\test-treemacs/1
(d1:G:\test-treemacs/1
d2:2
joined[1:]:G:\test-treemacs/1/2
d1:G:\test-treemacs/1
d2:G:\test-treemacs/1/2
joined[1:]:G:\test-treemacs/1/G:\test-treemacs/1/2
Traceback (most recent call last):
  File "c:/Users/me/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-dirs-to-collapse.py", line 68, in <module>
    main()
  File "c:/Users/me/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-dirs-to-collapse.py", line 55, in main
    content     = dir_content(collapsed)
  File "c:/Users/me/AppData/Roaming/.emacs.d/site-lisp/treemacs/src/scripts/treemacs-dirs-to-collapse.py", line 36, in dir_content
    for item in listdir(path):
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'G:\\test-treemacs/1/G:\\test-treemacs/1/2'
[16:19:20] /g:

The diff between our code now:
![image](https://user-images.githubusercontent.com/6119928/52621372-14ebe000-2ee2-11e9-954c-07de7d85c3ff.png)

**Comment by Alexander-Miller** [comment]
We are getting somewhere. Try this:
```python
from os import listdir
from os.path import abspath, isdir, isfile
from posixpath import join
import sys
import os

ROOT     = sys.argv[1]
LIMIT    = int(sys.argv[2])
SHOW_ALL = sys.argv[3] == 't'

if sys.platform == 'win32':
    def join_dirs(d1, d2, full_path=False):
        missing_slash = False
        if not d1.startswith("/"):
            missing_slash = True
            d1 = "/" + d1
        if full_path and not d2.startswith("/"):
            missing_slash = True
            d2 = "/" + d2
        joined = join(d1, d2)
        if missing_slash:
            return joined[1:]
        else:
            return joined
else:
    def join_dirs(d1, d2, _):
        return join(d1, d2)

if LIMIT <= 0:
    exit(0)

def dir_content(path):
    ret = []
    for item in listdir(path):
        full_path = join_dirs(path, item)
        if os.access(full_path, os.R_OK) and (SHOW_ALL or item[0] != '.'):
            ret.append(full_path)
    return ret

def main():
    out  = sys.stdout
    dirs = [d for d in dir_content(ROOT) if isdir(d)]
    out.write("(")
    for current_dir in dirs:
        content   = dir_content(current_dir)
        collapsed = current_dir
        steps     = []
        depth     = 0
        while True:
            if len(content) == 1 and isdir(content[0]):
                single_path = content[0]
                collapsed   = join_dirs(collapsed, single_path, True)
                content     = dir_content(collapsed)
                depth      += 1
                steps.append(single_path)
                if depth >= LIMIT:
                    break
            else:
                break
        if depth > 0:
            final_dir      = steps[-1]
            display_suffix = final_dir[len(current_dir):]
            out.write("(" + '"' + current_dir + '" ' + '"' + display_suffix + '" ' + '"' + '" "'.join(steps) + '")')
    out.write(")")

main()
```

**Comment by zijianyue** [comment]
OK, it work now
![image](https://user-images.githubusercontent.com/6119928/52757652-6ca05d80-3040-11e9-93ed-b9ed885ab0a0.png)

**Comment by Alexander-Miller** [comment]
I've now pushed the corrected script to master.
