### ISSUE TITLE
Change default C-p Project prefix to C-c C-p.

### ISSUE THREAD

**Issue by rswgnu** [Alexander-Miller/treemacs#337]
I see this topic has been broached before without success.  I know that I have not been following Treemacs evolution, so I am late on this issue but I will briefly try my hand at it.

Touch typists who use Emacs (and there are a lot of us) are definitely used to C-p moving to previous line most anywhere and they do not expect to have to rebind it to make another tool compatible with one of the most basic movement keys.  The fact that C-n works as expected makes this more of a default UI issue.

C-c C-p is a nice presently unused key sequence that would be a good alternative prefix for the lesser used Project commands and is only one key longer to type.  It jives with many other modes that have similar prefixes.

Although changing it represents a backward incompatibility, the benefit is that many more new users will be comfortable right away using the keyboard to move around in Treemacs.  Admitedly, n and p are inverse commands for movement by a line.

I know this is a hard issue for you but I thought I would give it a go.

**Comment by rudi** [comment]
For what it's worth, this is the first thing I stumbled over as well, in an otherwise very nice package ;)

Here is what I did in my `.emacs` to adapt the keybindings to my taste; maybe the bug report can be left open so that others with the same problem can find this?

```elisp
(use-package treemacs :ensure t
  :config
  (unbind-key "C-p" treemacs-mode-map)
  (bind-key "C-n" 'treemacs-next-line treemacs-mode-map)
  (bind-key "C-p" 'treemacs-previous-line treemacs-mode-map)
  (bind-key "C-x p r" 'treemacs-rename-project treemacs-mode-map)
  (bind-key "C-x p a" 'treemacs-add-project-to-workspace treemacs-mode-map)
  (bind-key "C-x p d" 'treemacs-remove-project-from-workspace treemacs-mode-map)
  (bind-key "C-x p c c" 'treemacs-collapse-project treemacs-mode-map)
  (bind-key "C-x p c o" 'treemacs-collapse-other-projects treemacs-mode-map)
  (bind-key "C-x p c a" 'treemacs-collapse-all-projects treemacs-mode-map))
```

Note: if you use treemacs-projectile, the above needs to be in the `use-package` form for treemacs-projectile instead; you might want to add a binding for the `treemacs-projectile` command as well.

**Comment by rudi** [comment]
Implementation note: if the project-related commands were contained in their own keymap (see elisp manual Section 22.6, "Prefix Keys"), it would be easy to rebind them all in one go.  Would a pull request implementing this (but not changing any keybindings, of couse) be accepted?

**Comment by Alexander-Miller** [comment]
I am usually loath to change to make such backwards-incompatible changes, but the point about confusion for non-evil users is one that I find convincing. I have plenty of other stuff to work on, so, yes, PRs are very much welcome.

**Comment by rudi** [comment]
With the above pull request, adjusting the keybindings reduces to the following:

```
(use-package treemacs
  :bind (:map treemacs-mode-map
         ("C-c C-p" . treemacs-project-map)
         ("C-p" . treemacs-previous-line)))
```

**Comment by mengelhart** [comment]
I also just installed Treemacs (non-evil mode - just straight up Emacs 26) and was banging my head around trying to figure out why C-p didn't work.. then I read the fine manual and realized C-p was bound.   Also I don't use use-package so preferably a way to make this configurable out of the box when just using package-install would be ideal

**Comment by rudi** [comment]
Hi @mengelhart, if you install the bind-keys package from melpa, you should be able to put the bind-key/unbind-key forms after `:config` in my above comment into your .emacs directly, without use-package.

**Comment by Alexander-Miller** [comment]
Fixed in https://github.com/Alexander-Miller/treemacs/commit/89196165c1467767865c44d82ba2bd6eb240d844

**Comment by rswgnu** [comment]
The commit shows a typo of C-p C-p rather than C-c C-p.

-- Bob

**Comment by Alexander-Miller** [comment]
Already fixed in https://github.com/Alexander-Miller/treemacs/commit/a2f4550d68491570ad9b40cb3c456324b7aeec40.
