### ISSUE TITLE
treemacs-persist buffer created when adding/removing a project

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#339]
When a project is added with `C-p a` or if Treemacs is opened the first time (without a previous project) after (re)starting Spacemacs. Then a `treemacs-persist` buffer appears in the HELM Mini `SPC b b` buffer list.

It contains:
```
* Default Workspace
** project
 - path :: c:/project
```

If a project is deleted and
- the `treemacs-persist` buffer exists, then it gets deleted
- there is no `treemacs-persist` buffer (it has been deleted manually), then it is created

(A buffer can be deleted from the HELM Mini buffer with `M-D`)

The (delete project) `treemacs-persist` buffer contains:
```
* Default Workspace
```

#### Possible solutions

Maybe the buffer should be hidden, I seem to remember that a buffer can be hidden by adding a leading space to the name (I don't know if the buffer name needs surrounding `*` asterisks or if it just is a convention).

The visibility of hidden buffers can be toggled in HELM Mini (`SPC b b`) with the keybinding: `C-c a`

Or maybe the buffer isn't needed, since the same info is written to the file:
`c:/Users/username/.emacs.d/.cache/treemacs-persist`

I found the file because the `*messages*` buffer (`SPC b m`) shows the following two lines every time a project is added/removed.
>Saving file c:/Users/username/.emacs.d/.cache/treemacs-persist...
Wrote c:/Users/username/.emacs.d/.cache/treemacs-persist

**Comment by duianto** [comment]
Update:
I incorrectly assumed that `treemacs-persist` was just a temporary buffer, that was created in addition to the file in `.cache`.

But now I see that it's actually the file: `c:/Users/username/.emacs.d/.cache/treemacs-persist`

So maybe the file shouldn't be opened when adding/removing a project.

**Comment by Opimenov** [comment]
Could be related to this. When I remove the project from the workspace it is still there as if nothing happened. I need to close the Treemacs buffer and open it again in order for project to go away.

**Comment by duianto** [comment]
@Opimenov Your issue is unrelated, but it has been fixed, just update your Treemacs package.

**Comment by duianto** [comment]
This seems to have been fixed. I'm not seeing the `treemacs-persist` buffer any more, either with or without Spacemacs.
