### ISSUE TITLE
file-icon 

### ISSUE THREAD

**Issue by jbharat** [Alexander-Miller/treemacs#34]
I tried to use js file icons  from all-the-icons as per the instruction. But file icon is not getting inserted. Is this right?

```
(with-eval-after-load "treemacs"
  (defvar treemacs-custom-js-icon (all-the-icons-icon-for-file "file.js"))
  (treemacs-define-custom-icon treemacs-custom-js-icon "js" "jsx"))
```

treemacs-20170812.134
treemacs-evil-20170625.1401

**Comment by Alexander-Miller** [comment]
The code is correct, and for me it's worked as intended. Let's debug this.

 * First of all update treemacs and restart emacs to make sure we've a clean start
 * Then run the code
 * Does it still not work?
 * What's the value value of `treemacs-custom-js-icon`?
 * What do you see when you run `(insert (gethash "js" treemacs-icons-hash))`?

**Comment by jbharat** [comment]
It didnt work. I checked the varaible  and got this
```
treemacs-custom-js-icon’s value is
#("" 0 1
  (font-lock-ignore t rear-nonsticky t display
                    (raise 0.0)
                    face
                    (:family "all-the-icons" :height 1.2 :inherit all-the-icons-yellow)))
```
It seems the variable is defined fine. But for treemacs-icons-hash I am getting this

```
*** Eval error ***  Symbol’s value as variable is void: treemacs-icons-hash
```

**Comment by Alexander-Miller** [comment]
Something's off here. The only reason `treemacs-icons-hash` can be undefined  is that treemacs has not been loaded, but `with-eval-after-load` makes sure that the code is only run *after* treemacs is loaded, which it was, since the custom js icon var is defined.

If you can run treemacs at all `treemacs-icons-hash` *must* be defined and filled, or you'd see the very same error.

Did you run the code including the with-eval block? You need to make sure treemacs is fully loaded. Just launching it is enough.

**Comment by jbharat** [comment]
I am using this code 
```
(use-package treemacs
  :ensure t
  :defer t
  :config
  (use-package treemacs-evil
    :ensure t
    :demand t)
  (setq treemacs-header-function            #'treemacs--create-header-projectile
        treemacs-follow-after-init          t
        treemacs-width                      35
        treemacs-indentation                2
        treemacs-git-integration            t
        treemacs-change-root-without-asking nil
        treemacs-sorting                    'alphabetic-desc
        treemacs-show-hidden-files          nil
        treemacs-never-persist              nil
        treemacs-goto-tag-strategy          'refetch-index)
  (treemacs-follow-mode t)
  (treemacs-filewatch-mode t)
  :bind
  (:map global-map
   ([f8]        . treemacs-toggle)
   ("<C-M-tab>" . treemacs-toggle)
   ("M-0"       . treemacs-select-window)
   ("C-c 1"     . treemacs-delete-other-windows)
   :map spacemacs-default-map
   ("ft"    . treemacs)
   ("fT"    . treemacs-projectile)
   ("f C-t" . treemacs-find-file))
  )


(with-eval-after-load "treemacs"
  (defvar treemacs-custom-js-icon (all-the-icons-icon-for-file "file.js"))
  (treemacs-define-custom-icon treemacs-custom-js-icon "js" "jsx"))
```

treemacs works fine.  I am using it. I am just unable to replace js icon.

**Comment by Alexander-Miller** [comment]
Ah, I think I've found what's wrong. I'll start fixing it now, in the meantime running the code again after treemacs was loaded should give you the icon.

**Comment by jbharat** [comment]
Perfect. Reloaded .spacemacs and got the icon. Thanks

**Comment by jbharat** [comment]
Icon loaded by all-the-icons for js does not match with the dimensions used by the png icons in treemacs. If you can guide me, I can add the icons for json, js, to treemacs

**Comment by Alexander-Miller** [comment]
The width of iconic fonts is always inconsistent, that's why I don't use them.

>  If you can guide me, I can add the icons for json, js,

That's simple. First your icons must be 22x22 pixel png images that look reasonably nice with both dark and light themes. If that's the case put the icons in /treemacs/icons/, open treemacs-visuals.el and make another `treemacs--setup-icon` entry alongside all the others.

**Comment by jbharat** [comment]
I have added the icons. #37 pr

**Comment by Alexander-Miller** [comment]
Treemacs has proper js icons after your PR was merged. Nonetheless adding custom icons should work as intended in the newest version.

**Comment by jbharat** [comment]
great. Thanks. :smile:
