### ISSUE TITLE
Added project message missing from automatic prompt

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#340]
When Treemacs doesn't have a previously defined project, and Treemacs is opened the first time after (re)starting Spacemacs, then a prompt appears asking: `Project root` (as expected).

When a project is added, then the messages buffer shows:
>Saving file c:/Users/username/.emacs.d/.cache/treemacs-persist...
Wrote c:/Users/username/.emacs.d/.cache/treemacs-persist

However when a project is added with the keybinding `C-p a`, then the messages buffer shows an additional message:
>Saving file c:/Users/username/.emacs.d/.cache/treemacs-persist...
Wrote c:/Users/username/.emacs.d/.cache/treemacs-persist
[Treemacs] Added project temp to the workspace.

Removing a project also shows a descriptive message:
>Saving file c:/Users/username/.emacs.d/.cache/treemacs-persist...
Wrote c:/Users/username/.emacs.d/.cache/treemacs-persist
[Treemacs] Removed project temp from the workspace.

I suspect that the message only gets appended when the keybindings are used.

It should probably also be shown when the project is added from the automatic first time prompt.

**Comment by duianto** [comment]
I noticed another difference with the after startup prompt, it asks for:
- First the `Project root:`
- Second the `Project Name:`

The add project key binding `C-c C-p a` prompt only asks for `Project root:` and uses the directory name as the project name. This seems like it might be the expected result, then the project is added without a second step, and if one want to rename the project then there's a key binding for it `C-c C-p r`.

**Comment by duianto** [comment]
I found another difference between the initial `Project Name:` prompt and the `New name:` prompt when one tries to rename an existing project.

If one tries to use a line break `M-j` in the name, then the prompt just closes without any message that a line break is an invalid project name.

Like it does at the rename prompt:
>[Treemacs] 'a
b' is an invalid name.

Reproduction steps:
- Remove all projects from Treemacs
- Restart Emacs
- Open Treemacs: `M-x treemacs`
- Choose a project at the `Project root:` prompt and press `RET` to confirm

At the `Project Name:` prompt:
- Type `a`
- Add a line break: `M-j`
- Type `b`
- Press `RET`

The prompt just closed. An error message should probably be shown.

**Comment by Alexander-Miller** [comment]
That one is awkward to handle. The minibuffer is used for both reading the name and displaying an error if a name is invalid. I don't see many options here:

 * Change prompt to something like "Previous name was invalid"
 * not ask for a name and just go with the name of the directory

**Comment by Alexander-Miller** [comment]
Solved via the 2nd option.
