### ISSUE TITLE
treemacs--expand-root-node: Wrong type argument: number-or-marker-p, t

### ISSUE THREAD

**Issue by philipsd6** [Alexander-Miller/treemacs#345]
Again, installed as documented. I've set up my workspaces and projects with `M-x treemacs-edit-workspaces` (I have one workspace with two projects, one of them a git repo and another not.)

After displaying the treemacs frame `M-x treemacs-select-window` I can get the treemacs frame to display, but double-clicking on the projects causes this error:

    treemacs--expand-root-node: Wrong type argument: number-or-marker-p, t

...and nothing happens. TAB does the same, or anything that should expand the node.

**Comment by Alexander-Miller** [comment]
* Does it work when you push TAB instead of using the mouse?
* Can you produce a stack trace? Try again after calling `toggle-debug-on-error`.

**Comment by philipsd6** [comment]
Yes, I messed up my original issue message hiding the fact that I'd tried TAB too. Here's the stack trace using TAB:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p t)
  treemacs--collapsed-dirs-process("/home/philipdsd6/super-secret-project")
  treemacs--expand-root-node(#<marker (moves after insertion) at 10 in  *Treemacs-Framebuffer-1*>)
  treemacs-toggle-node(nil)
  treemacs-TAB-action(nil)
  funcall-interactively(treemacs-TAB-action nil)
  call-interactively(treemacs-TAB-action nil nil)
  command-execute(treemacs-TAB-action)
```

**Comment by Alexander-Miller** [comment]
> treemacs--collapsed-dirs-process("/home/philipdsd6/super-secret-project")

Did you set `treemacs-collapse-dirs` to t? That's wrong, see its docs:
 
> When > 0 treemacs will collapse directories into one when possible.
> The value determines how many directories can be collapsed at once, both as a
performance cap and to prevent a too long directory names in the treemacs view.

**Comment by Alexander-Miller** [comment]
Bump?

**Comment by philipsd6** [comment]
Yup, my bad -- changed the 't' to a number and all is well.
