### ISSUE TITLE
grep on project files from treemacs buffer

### ISSUE THREAD

**Issue by Opimenov** [Alexander-Miller/treemacs#346]
It would be nice to have the ability to do grep and file search (using only part of the file name, and not the entire path) without leaving treemacs buffer.

**Comment by Alexander-Miller** [comment]
What grep method do you use? [Treemacs already allows grepping and similar actions to some degree](https://github.com/Alexander-Miller/treemacs#current-directory-awareness).

**Comment by Opimenov** [comment]
It wasn't working because projectile mode was disabled for what ever reason. Treemacs is nice indeed. 
I should have investigated more before opening up the ticket.
