### ISSUE TITLE
[Feature request] Sorting based on custom sort function

### ISSUE THREAD

**Issue by AshKash** [Alexander-Miller/treemacs#347]
I use ivy and the sorting it uses gives preferential treatment to which buffer was most recently visited etc. It looks like this is all exposed under:
 ivy-sort-file-function-default (x y)
ivy-sort-file-function-using-ido (x y)

The functions take two arguments similar to the Treemacs sort functions.

Is it possible to call one of these functions from Treemacs? Any pointers on how to get this to work?

**Comment by Alexander-Miller** [comment]
> ivy-sort-file-function-default (x y)

Not gonna work. It requires text properties added somewhere else by ivy. Besides that I don't see any special sorting, it's the same alphabetic sorting that treemacs would use.

```
(if (get-text-property 0 'dirp x)
      (if (get-text-property 0 'dirp y)
          (string< (directory-file-name x) (directory-file-name y))
        t)
    (if (get-text-property 0 'dirp y)
        nil
      (string< x y)))
```

> ivy-sort-file-function-using-ido

That's just a thin wrapper around `ido-file-extension-lessp` that makes sure that `ido-file-extensions-order` is non-nil. This can work, assuming your `ido-file-extensions-order` is actually filled with something.

**Comment by AshKash** [comment]
Thanks for looking into this. The main issue I have is the project is huge and has many directories and files but I tend to keep 2-3 open files. Also I work on 2-3 such projects. Showing all the unvisited directories and files is  not the best user experience - it clutters and I cannot focus on what is most relevant to the task at hand (this is very closely correlated to the open file buffers). 

If you are considering an enhancement, please consider this use case - sorting is just a workaround for this problem.

**Comment by Alexander-Miller** [comment]
If you have a lot of files, but only need a few, then a project explorer like treemacs won't really scale, no matter what you do. Your best bet will be to stick around for #326.

**Comment by Alexander-Miller** [comment]
Custom functions are now possible. Using it is as simple as `(setf treemacs-sorting #'string>)`.
