### ISSUE TITLE
dired-maybe-insert-subdir issue in dired mode.

### ISSUE THREAD

**Issue by jayhanjaelee** [Alexander-Miller/treemacs#348]
In dired mode, after pressing i key which measn dired-maybe-insert-subdir function, sub directory is shown, But icon is not shown. So if I pressing g key which menas revert-buffer. then Emacs stops.
Maybe Loading images for sub directory affects problem.
emacs version is 26.1 and I'm using Mac Mojave.

**Comment by Alexander-Miller** [comment]
>  then Emacs stops

It's not a stop, but an infinite loop that you can get out of with `C-g`. Probably treemacs-dired cannot deal with the subdirectory and get stuck.

I'll investigate.

**Comment by Alexander-Miller** [comment]
Should be all good now.
