### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by jbharat** [Alexander-Miller/treemacs#35]
I get the following errors when I try to open json/js/txt files

```
test.json
No imenu found for test.json
```
```
test.txt
imenu unavailable: "This buffer cannot use 'imenu-default-create-index-function'"
```
```
test.js
no imenu found for test.js
error in process filter: selecting deleted buffer
Button in current line is not a directory
```
For javacript file the errors are not consistent. I get different error of the above 3 when I try to open a js file through keyboard. I like the idea of imenu. But it should just open the file if no imenu.

I want to replace neotree with treemacs as it seems faster and has follow-mode. But I am unable to open files at all. 

treemacs-20170812.134
treemacs-evil-20170625.1401

**Comment by Alexander-Miller** [comment]
> I get different error of the above 3 when I try to open a js file through keyboard

Consistently catching and displaying imenu errors is on my todo list.

> But I am unable to open files at all.

I assume you mean using TAB with the default key bindings. That's working as intended, TAB's purpose is to expand and close nodes. You've half a dozen different ways to open files, all bound under `o` as a prefix. oo for open directly, ov for open in vertical split, ox for open with xdg-open etc.

Now that my readme has gotten so fat I probably should add a quickstart section.

**Comment by jbharat** [comment]
Yes. oo/ov/oh works. I am used to just plain RET as I have been using neotree. sorry. I will close this issue. Thanks.

**Comment by Alexander-Miller** [comment]
> I am used to just plain RET

That's also on the todo list. The plan is to bind RET to some configurable default open action, outside of multiple o+ key presses.
