### ISSUE TITLE
Extra empty line after removing a project

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#351]
#### Description :octocat:

An empty line is left behind when removing a project above the last project.

#### Reproduction guide :beetle:

- With two or more projects added
- Select a project above the last and remove it `C-p d`

*Observed behaviour:* :eyes: :broken_heart:

An empty line was left behind when the project was removed.

*Expected behaviour:* :heart: :smile:

There shouldn't be any extra empty lines above or between the projects.

#### What doesn't work:
Refreshing `gr` doesn't help.

#### What works:
Restarting Spacemacs and opening Treemacs shows the projects without the extra empty lines.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 95422ae5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp git helm html markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by Alexander-Miller** [comment]
Should be fixed now.

**Comment by duianto** [comment]
Fixed, there are no empty lines left behind. Thanks
