### ISSUE TITLE
Unexpected project selected after project removal.

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#352]
#### Description :octocat:

Removing a project doesn't always select the closest project.

#### Reproduction guide :beetle:

With four projects:
```
p1
p2
p3
p4
```
Remove a project:  `C-p d`
Test 1: Remove p1
Test 2: Remove p2
Test 3: Remove p3
Test 4: Remove p4

Each test were done with the four projects re-added in the same order:
p1, p2, p3, p4

*Observed behaviour:* :eyes: :broken_heart:

Test 1: p3 selected (unexpected, p2 was the closest project but it was skippedover )
Test 2: p4 selected (unexpected, p1 and p3 were closer but it selected downwards and skipped over p3)
Test 3: p2 selected (probably expected, if the rules is to select the closest project with priority above).
Test 4: p3 selected (expected since it's the closest project)

*Expected behaviour:* :heart: :smile:

Removing a project should select the closest project, possibly with priority to the project above.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 95422ae5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp git helm html markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by Alexander-Miller** [comment]
> Removing a project should select the closest project, possibly with priority to the project above.

Done, but best make sure I didn't miss some edge case.

**Comment by duianto** [comment]
It seems to be working as expected for the test cases above 👍 thanks.

Projects: p1 to p4 were added in that order before every test.
test 1: p1 deleted, p2 selected
test 2: p2 deleted, p3 selected
test 3: p3 deleted, p4 selected
test 4: p4 deleted, p3 selected

It selects the closest with priority below (unless it's the last project then above).
I have no preference for selecting up or down, as long as it's consistent.

But I noticed that if the cursor is between two projects, then `C-c C-p d` opens a buffer called:
HELM Treemacs Remove Project From Workspace
where one can choose any of the projects to remove.

The cursor seems to always jump to the first line after removing any project.

With the cursor between p1 and p2 or between p3 and p4, removing any of the four projects moves the cursor to p1.
And with the cursor between p2 and p3, I only tried deleting p1 or p4, but the same thing happened, the cursor moved to p1.

It seems like the only case where the cursor should move is if it's between the next to last and last project, then it would move up to the project above which now is last.

**Comment by Alexander-Miller** [comment]
This is indeed the type of edge case I thought we might still discover. When you use a prefix arg, or when there is no project at point, you must select the project you want removed by its name. If the project selected and the project at point (nil in your case) are not the same the resulting do-delete call is wrapped in a `save-position` macro. This macro is meant to let treemacs update its display without the annoyance of shifting the point and moving around the view - it tries to both keep point on the same node (or a close neighbor) as well as in the same screen line.

Point being on an empty line is a seldom encountered use-case - so all it does it move point to `point-min`. Usually that kind of thing would be noticed whenever you run a refresh, but refreshing an empty line does nothing.

Either way, this case is now covered as well, and point will remain in the same empty line when you delete a project by name.

**Comment by duianto** [comment]
There seems to be an issue with where a project gets added.

Starting out with no projects.

#### Issue

I added: p1, then: p2
but p2 was added above p1:
```
p2
p1
```
adding a project should probably add it below the selected project.

#### Expected
With p2 selected, I added p3
p3 was added below p2 (expected if projects were added below the selected project)
```
p2
p3
p1
```

#### Issue

With p2 selected, added p4

p4 was added as the third project, jumping over the second project (p3)
```
p2
p3
p4
p1
```

**Comment by duianto** [comment]
The projects might be added in the correct order internally. They might just be shown in the wrong order.

Because when trying to move a project, with `M-` `up` or `down`, then this happens:

With two added projects, (p1 was added first, then p2):
```
p2
p1
```
with p2 selected.
Pressing: `M-down` (to try and move p2 below p1).
Then this message is shown:
>[Treemacs] There is no project to switch places with below.

With p2 still selected.
Pressing `M-up` moved p2 below p1:
```
p1
p2
```

**Comment by duianto** [comment]
Yes that seems to be what's happening.
In the previous end state, the treemacs window shows:
```
p1
p2
```
but when the cursor is placed between the projects, and `C-c C-p d` is pressed to open:
Helm Treemacs Remove Project From Workspace
then they are listed as:
```
p2
p1
```

**Comment by duianto** [comment]
After removing all projects.
Now they were added in the expected order:
```
p1
p2
p3
p4
```
And the Helm remove project buffer also shows them in the same order.

Now I can test the cursor placement after removing a project from helm remove project

With the cursor on the empty line between p2 and p3.
Removing p1 from the helm remove project buffer, seems to be working as expected:
```
p2
(cursor)
p3
(empty line, as expected)
p4
```

#### Issue

With the cursor still between p2 and p3.
Removing p4 from the helm remove project buffer, removed both p2 and p4 from the treemacs window, and the cursor is on an empty line above p3:
```
(cursor)
p3
```
The helm remove project buffer shows:
```
p2
p3
```

**Comment by Alexander-Miller** [comment]
> Removing p4 from the helm remove project buffer, removed both p2 and p4 from the treemacs window, and the cursor is on an empty line above p3

[Looks like I cannot reproduce it.](https://imgur.com/E4XlI6G) Project placement and rendering saw quite a few changes recently, so I have two guesses:

 - Maybe you didn't restart emacs and some redefined function or new defvar is causing trouble
 - We have another edge case, related to cursor placement (treemacs now tracks where projects end with a marker to be able to insert new projects in the right place when there are also extensions about).

**Comment by duianto** [comment]
It doesn't seem to be a restart issue, because I restarted Emacs and the four projects was in numerical order from before the restart, and I'm seeing the same thing.

I even tried restarting without any previous projects. After adding the projects and using `M-` `up`/`down` to move them into order.
```
p1
p2
(cursor)
p3
p4
```
This time I tried removing p4, it shows the same result, the first project isn't visible:
```
(empty line)
p2
(cursor)
p3
```
`C-c C-p d` opens helm remove project, which shows:
```
p1
p2
p3
```

#### Eureka 😄 
Now I see what's going on, p1 scrolled above the top of the window.
scrolling down shows:
```
p1
p2
p3
```

I have been thinking about submitting an issue about adding some kind of indicator that the window is scrolled, and there are projects above the first line.

**Comment by Alexander-Miller** [comment]
I believe we were done with the original content of the issue, so I'll close here.
