### ISSUE TITLE
Rename to old project name, reported as renamed

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#353]
#### Description :octocat:

Mistaken rename to old project name is reported as if the project actually was renamed.

#### Reproduction guide :beetle:

With a project named `old` added.
- Rename it `C-p r`
- Give it the same name: `old`

*Observed behaviour:* :eyes: :broken_heart:

[Treemacs] Renamed project old to old

*Expected behaviour:* :heart: :smile:

Since it says that the project was "Renamed", if one was stressed and thought that a new name was typed, but one actually typed the old name, then the "Renamed" message looks like the operation was successful.

If it instead said something like:
```
[Treemacs] Rename failed, same old and new name
```
I just noticed that the `[Treemacs]` text is colored blue for the Renamed project... message , maybe just the square bracket text or the whole message could use the error (red) or warning (orange) face (those are the colors in the Spacemacs-dark theme), to emphasize that the command failed.

Then it will be obvious that something went wrong.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 95422ae5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp git helm html markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by Alexander-Miller** [comment]
> maybe just the square bracket text or the whole message could use the error (red) or warning (orange) face (those are the colors in the Spacemacs-dark theme), to emphasize that the command failed.

Treemacs simply uses `font-lock-keyword-face` for that part. Feedback for success and failure is done via pulse.el. You should a green or red pulse pulse, unless you set `treemacs-pulse-on-failure/success` to nil. But different colors for log statements are a good idea, I'll put this on the todo list.

**Comment by Alexander-Miller** [comment]
Opened an issue for logging colors at #355.

**Comment by duianto** [comment]
The rename message works 👍 
>[Treemacs] The new name is the same as the old name.
