### ISSUE TITLE
With defaults (treemacs-show-hidden-files t) cannot see .git directory.

### ISSUE THREAD

**Issue by Antiarchitect** [Alexander-Miller/treemacs#356]

**Comment by Alexander-Miller** [comment]
That one's on purpose. I removed it to stop follow-mode from tracking COMMIT_EDITMSG and similar files. Do you think you need to see .git anyway?

**Comment by Antiarchitect** [comment]
I stand for common behavior - was very frustrated when I see other hidden files and no .git.

**Comment by JoshTRN** [comment]
Glad I found this answer. Was sort of frustrated that I didn't understand why I didn't see it.

**Comment by Alexander-Miller** [comment]
In hindsight it's not a decision I fully agree with either, so I have now added `treemacs-hide-dot-git-directory` to give you the option to show the .git directory.
