### ISSUE TITLE
Error when opening dired buffers after enabling treemacs-icons-dired-mode

### ISSUE THREAD

**Issue by CSRaghunandan** [Alexander-Miller/treemacs#357]
After having started treemacs, if I try to open dired, I get the following error:

```
Debugger entered--Lisp error: (invalid-function treemacs-block)
  treemacs-block(nil)
  treemacs-icons-dired--display-icons-for-subdir("/home/csraghunandan/.emacs.d/setup-files/" #<marker at 1 in *Dired* setup-files/>)
  treemacs-icons-dired--display()
  run-hooks(dired-after-readin-hook)
  dired-readin()
  dired-internal-noselect("/home/csraghunandan/.emacs.d/setup-files/" nil)
  dired-noselect("/home/csraghunandan/.emacs.d/setup-files/" nil)
  dired("/home/csraghunandan/.emacs.d/setup-files/")
  dired-jump(nil nil)
  funcall-interactively(dired-jump nil nil)
  call-interactively(dired-jump nil nil)
  command-execute(dired-jump)
```

Did a recent upgrade to treemacs break this feature?

**Comment by CSRaghunandan** [comment]
Okay, I managed to find out the problem. My package-quickstart.el file was corrupt which was causing emacs to behave strangely at times.

After deleting and refreshing the package-quickstart file, everything seems to be okay

**Comment by Alexander-Miller** [comment]
> Did a recent upgrade to treemacs break this feature?

`treemacs-block` is a minor macro abstracting around `cl-block` that I have pushed yesterday. I don't know how your files was "corrupt", but an error like yours could happen if you update treemacs-icons-dired without updating treemacs. That you shouldn't do, the extra packages are explicitly unversioned and meant to work with the latest treemacs release, so if you update one you should always update the other as well.

**Comment by Opimenov** [comment]
I have the similar problem. I have to call Dired twice to get it started. First time I see the same error message. On the second run it just works... my treemacs version 20190219.1558 and treemacs-icons-dired is 20190214.1914. Both are updated through melpa

**Comment by avkoval** [comment]
removal & reinstallation of both packages fixes it

**Comment by Alexander-Miller** [comment]
> my treemacs version 20190219.1558 and treemacs-icons-dired is 20190214.1914

I *guess* the problem could be updating treemacs after icons-dired, but even if that is the case I do not see what I can do to proactively prevent this from happening.

**Comment by Opimenov** [comment]
Updating solved this problem, but now I'm getting: 
`
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("c:/git_prod_tools/rs_common_prod_tools/Q49A/AccuracyVerificationTool" nil nil)
  treemacs--apply-deferred-git-state(#<marker (moves after insertion) at 14 in  *Treemacs-Framebuffer-1*> #<process Process Future> #<buffer  *Treemacs-Framebuffer-1*>)
  apply(treemacs--apply-deferred-git-state (#<marker (moves after insertion) at 14 in  *Treemacs-Framebuffer-1*> #<process Process Future> #<buffer  *Treemacs-Framebuffer-1*>))
  timer-event-handler([t 23677 14680 766162 nil treemacs--apply-deferred-git-state (#<marker (moves after insertion) at 14 in  *Treemacs-Framebuffer-1*> #<process Process Future> #<buffer  *Treemacs-Framebuffer-1*>) nil 0])

`
and constantly

`
error running timer treemacs--apply-deffer-git-state: (wrong-type-argument hash-table-p nil)
`
any pointers?

**Comment by Alexander-Miller** [comment]
That error is being investigated in https://github.com/Alexander-Miller/treemacs/issues/363
