### ISSUE TITLE
collapse-dirs no longer collapsing w/ treemacs-20190218.1924

### ISSUE THREAD

**Issue by perezd** [Alexander-Miller/treemacs#361]
It used to work, then I updated it.
I checked the option and its non-zero, meaning it should be active but seems to not be working. I don't see any errors anywhere, how can I help you diagnose?

**Comment by perezd** [comment]
Last version I had that was working properly:
treemacs-20190104.1527

**Comment by perezd** [comment]
Realizing these version numbers may be meaningless to you. The current version I am running is v2.4. The version I was running was v2.3

**Comment by Alexander-Miller** [comment]
Are you affected by https://github.com/Alexander-Miller/treemacs/commit/42296cc10c9f2639856cc0c84f21e3bb77ae87e4 or https://github.com/Alexander-Miller/treemacs/commit/6a1ba8640b371b89c9828eab4cf65bc1812871bd?

> Realizing these version numbers may be meaningless to you.

Why would they? It's basically the date when treemacs was downloaded and compiled. There is `treemacs-version` command that will summarize all that.

**Comment by perezd** [comment]
I didn't realize that was the date I downloaded it, sorry for the confusion, thought that was a real version number.

As for the two commits, I am using local filesystem projects on Ubuntu Linux 18.10 emacs version 2.52.2

**Comment by Alexander-Miller** [comment]
Found the problem, I left a stupid mistake in the script and hadn't even noticed myself.

**Comment by perezd** [comment]
That's great news! 
What cadence to fixes like these roll out to elpa/melpa in your experience?

**Comment by Alexander-Miller** [comment]
Check the sidebar at https://melpa.org/, it's usually every couple hours.
