### ISSUE TITLE
wrong-type-argument number-or-marker-p nil

### ISSUE THREAD

**Issue by sergeyklay** [Alexander-Miller/treemacs#364]
Hello,

I'm Spacemacs user.  I've set up my workspaces and projects with <kbd>Meta</kbd>-<kbd>x</kbd> `treemacs-edit-workspaces`. My current workflow is to keep treemacs opened. I can get the treemacs frame to display and can work in the main frame, however, I constantly see annoying errors in the `*messages*` buffer:

```
Error running timer ‘treemacs--process-file-events’: (wrong-type-argument number-or-marker-p nil)
```
Currently I use this buffer for debugging/profiling purposes by sending messages to this buffer. So I can't ignore these errors.

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  count-screen-lines(9803 14)
  treemacs--maybe-recenter(on-distance)
  treemacs--expand-root-node(#<marker at 3 in  *Treemacs-Framebuffer-1*>)
  treemacs--do-refresh(#<buffer  *Treemacs-Framebuffer-1*> #s(treemacs-project :name "zephir-mode" :path "/home/klay/workspace/elisp/zephir-mode"))
  treemacs--recursive-refresh()
  treemacs--process-file-events()
  apply(treemacs--process-file-events nil)
  timer-event-handler([t 23674 48890 297204 nil treemacs--process-file-events nil nil 522000])
```

**Comment by Alexander-Miller** [comment]
Seems to be the same problem as https://github.com/Alexander-Miller/treemacs/issues/363. You should follow the workaround outline there. I'll make fixing this bug a priority.

**Comment by Alexander-Miller** [comment]
Bug should be fixed now. Please verify.

**Comment by sergeyklay** [comment]
@Alexander-Miller I would like to wait resolving https://github.com/Alexander-Miller/treemacs/issues/363#issuecomment-468988586 and https://github.com/Alexander-Miller/treemacs/issues/365. BTW, could you advice a better way to update Treemacs for Spacemacs w/o tagged release? Thank you

**Comment by Alexander-Miller** [comment]
You mean as in update simply treemacs grabbing the newest version of treemacs & treemacs-evil, -projectile, -magit etc or do you have some additional requirements?

**Comment by sergeyklay** [comment]
I mean I would like to receive the most recent Treemacs changes, without waiting for a formal, tagged release. I could just copy the files from GitHub and put them somewhere in ~/.emacs.d, but I don’t think that this is the best way for the Spacemacs users.

**Comment by Alexander-Miller** [comment]
AFAIK spacemacs is simply using Melpa for its packages, unless you explicitly set `dotspacemacs-use-spacelpa` to t, so whatever changes I push to treemacs will be made available to you in at most a couple hours' time. Waiting for proper tagged releases is only necessary if you are using something like Melpa Stable.

**Comment by sergeyklay** [comment]
Oh! I completely forgot that the changes are synchronized with Melpa without needs to release a stable version. Thank you
