### ISSUE TITLE
treemacs--expand-root-node: Wrong type argument: hash-table-p, nil

### ISSUE THREAD

**Issue by victorolinasc** [Alexander-Miller/treemacs#365]
Hello! Thanks for your great work! 

After last update (commit https://github.com/Alexander-Miller/treemacs/commit/e4bbe1b3637485e379ccacca3ba3fb833e52797c) it does not open folders with error:

`treemacs--expand-root-node: Wrong type argument: hash-table-p, nil`

Regards,

**Comment by seagle0128** [comment]
See https://github.com/Alexander-Miller/treemacs/issues/363#issuecomment-468988586

**Comment by victorolinasc** [comment]
Not sure what was updated but the issue is now gone. I'll be closing this now.
