### ISSUE TITLE
Extend copy & move to allow renaming

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#367]

**Comment by jumarko** [comment]
Just want to add that it's quite confusing coming from Neotree that the current file copy actually doesn't work that way. So would love to see this extension :).

**Comment by Alexander-Miller** [comment]
Old issue, and I don't remember what this is about exactly. Can anyone remind me?

**Comment by antonalekseev** [comment]
@Alexander-Miller You opened this issue (probably) in response to my https://github.com/Alexander-Miller/treemacs/issues/273#issuecomment-469017596 regarding errors I had encountered then when tried to use `copy`/`move` operations on files (Neotree way).

**Comment by antonalekseev** [comment]
Sorry for bringing this up again, but passing `:must-match` here
https://github.com/Alexander-Miller/treemacs/blob/6a4de5085fbe1d02ad3593bb152ad5646eebfa55/src/elisp/treemacs-core-utils.el#L1210
makes it impossible to copy a file within the same directory in order, for example, to make a backup copy (`cp file.txt file.txt.bak`) as well as to copy a file to the directory other than current but with the different name (`cp file.txt otherdir/file2.txt`). Is there specific reason behind this limitation?

**Comment by Alexander-Miller** [comment]
I think my thought at the time of writing this was that you'd just select the destination directory, not the name. And when I did try the latter it worked anyway because helm doesn't seem to care about `:must-match`.

I'll be pushing a patch for this in a minute.

**Comment by antonalekseev** [comment]
@Alexander-Miller, thank you for your swift response and action. I really appreciate the time and effort you put into the project!
