### ISSUE TITLE
Identify open files by major mode not extension

### ISSUE THREAD

**Issue by memeplex** [Alexander-Miller/treemacs#368]
I often write python scripts which don't include a .py extension. Treemacs shows them as plain files that I can't expand and navigate, even if they're open in python mode.

**Comment by Alexander-Miller** [comment]
Treemacs does not know anything about files' major modes. The icon is determined strictly from a file's name, and trying to look at a file's content would slow things down by orders of magnitude.

The next best thing you can do is define the right icons for the names of the files you use, like this:
`(treemacs-define-custom-icon treemacs-icon-python "foo-file")`
