### ISSUE TITLE
Add a "Recent Projects" option to show all projects in projectile

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#372]
If user clicks on any of the projects in the "Recent Projects" option, it gets centred, highlighted and show the tree. If not present, it will first add the project and then show the tree it.

**Comment by Alexander-Miller** [comment]
> If not present, it will first add the project 

That's already present. See `treemacs-projectile`.

**Comment by Alexander-Miller** [comment]
> If user clicks on any of the projects in the "Recent Projects" option,

What do you think this should look like that it's clickable?

**Comment by Compro-Prasad** [comment]
A recent projects option in the right click menu.

**Comment by Alexander-Miller** [comment]
I have now added purely mouse-based sub-menus for selecting both project.el and projectile projects. I hope this is what you had in mind.

**Comment by Compro-Prasad** [comment]
Thanks. I have switched to `project.el` and the best thing is that you also added support for it. 

Happy New Year!
