### ISSUE TITLE
Change behaviour of add project

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#373]
Currently, a new project when added is collapsed by default. It would be better to collapse all other projects and show the top level of the currently added project. A variable for controlling the collapsed state will also be useful.

**Comment by Alexander-Miller** [comment]
> A variable for controlling the collapsed state will also be useful.

Control how?

**Comment by Compro-Prasad** [comment]
> > A variable for controlling the collapsed state will also be useful.

> Control how?

Some users might like the previous behaviour. Its optional though.

**Comment by Alexander-Miller** [comment]
~treemacs-expand-added-projects~ has now been added.
