### ISSUE TITLE
Treemacs unwanted resizing

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#376]
Treemacs automatically increases the width of its own window after a which key popup. My which-key popup is shown on the right side.

**Comment by Compro-Prasad** [comment]
Isn't there a hook when a window is resized? We could use that instead.

**Comment by Alexander-Miller** [comment]
Reopening on account of https://github.com/Alexander-Miller/treemacs/issues/41

**Comment by bk138** [comment]
[My config](https://github.com/bk138/dotfiles/blob/master/.emacs) is affected as well, though the symptoms really are what #41 covers.

**Comment by Alexander-Miller** [comment]
Does this help:

```Elisp
(with-eval-after-load 'which-key

  (defun treemacs--fix-width-after-which-key (func &rest args)
    "Advice to sure treemacs' window size stays put when which-key is active.
Wraps original FUNC + ARGS."
    (let* ((window (treemacs-get-local-window))
           (should-toggle (when window
                            (not (buffer-local-value 'treemacs--width-is-locked
                                                     (window-buffer window))))))
      (when should-toggle
        (with-selected-window window
          (treemacs-toggle-fixed-width)))
      (apply func args)
      (when should-toggle
        (with-selected-window window
          (treemacs-toggle-fixed-width)))))

  (advice-add 'which-key--update :around 'treemacs--fix-width-after-which-key)
  (advice-add 'which-key--hide-popup :around 'treemacs--fix-width-after-which-key))
```

**Comment by bk138** [comment]
Nope. When unlocking fixed-width and trying to drag the window border, I get:

```
Error during redisplay: (which-key--hide-popup-on-frame-size-change #<frame emacs@denkpad 0x1203c30>) signaled (wrong-number-of-arguments (lambda (func &rest args) "Advice to sure treemacs' window size stays put when which-key is active.
Wraps original FUNC + ARGS." (let* ((window (treemacs-get-local-window)) (should-toggle (if window (progn (not (buffer-local-value (quote treemacs--width-is-locked) (window-buffer window))))))) (if should-toggle (progn (let ((save-selected-window--state (internal--before-with-selected-window window))) (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (treemacs-toggle-fixed-width)) (internal--after-with-selected-window save-selected-window--state)))))) (apply func args) (if should-toggle (progn (let ((save-selected-window--state (internal--before-with-selected-window window))) (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (treemacs-toggle-fixed-width)) (internal--after-with-selected-window save-selected-window--state)))))))) 0)
Error in pre-command-hook (which-key--hide-popup): (wrong-number-of-arguments (lambda (func &rest args) "Advice to sure treemacs' window size stays put when which-key is active.
Wraps original FUNC + ARGS." (let* ((window (treemacs-get-local-window)) (should-toggle (if window (progn (not (buffer-local-value (quote treemacs--width-is-locked) (window-buffer window))))))) (if should-toggle (progn (let ((save-selected-window--state (internal--before-with-selected-window window))) (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (treemacs-toggle-fixed-width)) (internal--after-with-selected-window save-selected-window--state)))))) (apply func args) (if should-toggle (progn (let ((save-selected-window--state (internal--before-with-selected-window window))) (save-current-buffer (unwind-protect (progn (select-window (car save-selected-window--state) (quote norecord)) (treemacs-toggle-fixed-width)) (internal--after-with-selected-window save-selected-window--state)))))))) 0)
LSP :: Connected to [clangd:24750 status:starting].
[Treemacs] Window width has been unlocked.
user-error: No resizable window on the left of this one [4 times]

```

This is on `GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.4) of 2019-02-03, modified by Debian`. 

Please let me know what kind of additional info I can provide.

**Comment by Alexander-Miller** [comment]
> wrong-number-of-arguments

Weird stuff. My advice for which-key's functions calls them with the very same arguments they'd be called with anyway.

Let's try again. My guess is that the previously defined advice was interfering, so we'll remove that first.

```Elisp
(with-eval-after-load 'which-key

  (advice-remove 'which-key--update 'treemacs--fix-width-after-which-key)
  (advice-remove 'which-key--hide-buffer-side-window 'treemacs--fix-width-after-which-key)

  (defun treemacs--fix-width-after-which-key (func &rest args)
    "Advice to sure treemacs' window size stays put when which-key is active.
  Wraps original FUNC + ARGS."
    (let* ((window (treemacs-get-local-window))
           (should-toggle (and (with-no-warnings (which-key--popup-showing-p))
                               (when window
                                 (not (buffer-local-value 'treemacs--width-is-locked
                                                          (window-buffer window))))))
           (treemacs--no-messages t))
      (when should-toggle
        (with-selected-window window
          (treemacs-toggle-fixed-width)))
      (apply func args)
      (when should-toggle
        (with-selected-window window
          (treemacs-toggle-fixed-width))))

    (advice-add 'which-key--update :around 'treemacs--fix-width-after-which-key)
    (advice-add 'which-key--hide-buffer-side-window :around 'treemacs--fix-width-after-which-key)))
```

**Comment by bk138** [comment]
No error anymore, but no resize either:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
[Treemacs] Window width has been unlocked.
LSP :: Connected to [clangd:29301 status:starting].
user-error: No resizable window on the left of this one [54 times]
Mark set
```

Are you able to repro with my config: https://github.com/bk138/dotfiles/blob/master/.emacs ?

**Comment by Alexander-Miller** [comment]
All I'm getting up to is setting a single variable that determines whether the width of the treemacs window should be fixed or not. If dashboard.el interferes with that then I think it's on them to look into this.

**Comment by bestlem** [comment]
On Aquamacs this bug with treemacs getting larger with which-key seems to have come back after the 20190814.459 elpa version now on 20191106.2038

I don't remeber seeing this size increase before

**Comment by Alexander-Miller** [comment]
Let's have a look. What do your which-key and treemacs settings look like?

**Comment by bestlem** [comment]
(use-package which-key
  :ensure t
  :defer 5
  :config (which-key-setup-side-window-right-bottom)
  (setq which-key-sort-order 'which-key-key-order-alpha
        which-key-side-window-max-width 0.33
        which-key-idle-delay 0.05)
  (which-key-mode)
  :diminish which-key-mode)

(use-package treemacs
  :ensure t
  :defer t
  :init
  (with-eval-after-load 'winum
    (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
  :config
  (progn
    (setq hydra-key-regex "\\[\\|]\\|[-\\[:alnum:] ~.,;:/|?<>={}*+#%@!&^⇧⌘⌥↑↓←→⌫⌦⏎'`()\"$]+?") ; add Mac key symbols

    (setq treemacs-silent-refresh t
          treemacs-persist-file (mwb-user-emacs-file "data/treemacs-persist"))
    (with-eval-after-load 'treemacs
      (add-to-list 'treemacs-pre-file-insert-predicates #'treemacs-is-file-git-ignored?))

    ;; The default width and height of the icons is 22 pixels. If you are
    ;; using a Hi-DPI display, uncomment this to double the icon size.
    ;;(treemacs-resize-icons 44)

    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-fringe-indicator-mode t)
    (pcase (cons (not (null (executable-find "git")))
                 (not (null treemacs-python-executable )))
      (`(t . t)
       (treemacs-git-mode 'deferred))
      (`(t . _)
       (treemacs-git-mode 'simple))))
  :hydra (mwb/hydra-treemacs-mode
          (:color teal)
          ("p" matcha-projectile/body "Projectile")
          ("c" treemacs-add-project-to-workspace "Create Project")
          ("d" treemacs-remove-project-from-workspace "Delete Project")
          ("q" nil "Quit"))
  (mwb/hydra-treemacs-global
   (:color blue)
   ("t" treemacs "Treemacs toggle" :column "Project")
   ("p" mwb/hydra-treemacs-mode/body "Projectile")
   ("0" treemacs-select-window "Select" :column "Other Window")
   ("1" treemacs-delete-other-windows "Delete")
   ("B" treemacs-bookmark "Bookmark" :column "Rest")
   ("f" treemacs-find-file "Find File")
   ("T" treemacs-find-tag "Find Tag"))
  :bind (("H-t" . mwb/hydra-treemacs-global/body)
         :map treemacs-mode-map
         ("<mouse-5>" . treemacs-rightclick-menu)
         ("<mouse-4>" . treemacs-rightclick-menu)
         ("<f5>" . treemacs-switch-workspace)
         ("<C-f5>" . treemacs-edit-workspaces)))

**Comment by fjl** [comment]
One thing that tripped me up when trying out treemacs for the first time is that it still honors `window-min-width`. If this is set, setting the treemacs window size doesn't really work and you can't resize it below this value.

The workaround is to use `window-resize` with the right `ignore` parameter in `treemacs--set-width`.

**Comment by Alexander-Miller** [comment]
Hmm, I had integrated the which-key glue code a long time ago, but forgot about this ticket. And based on https://github.com/Alexander-Miller/treemacs/issues/674 the resizing no longer even happens. I think we can safely close this.

@fjl Why shouldn't it honor `window-min-width`? The default is only 10 columns, if you want less than that you're probably better off just closing treemacs.

**Comment by fjl** [comment]
I added this comment because my `window-min-width` used to be 80, and that broke treemacs. I've since restructured my config to avoid relying on `window-min-width`, but still don't see a reason why treemacs should care about it. If you want to avoid crashing emacs with a window that's too small, consider using `window-safe-min-width` instead.
