### ISSUE TITLE
Add an error message to: do add project to workspace

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#380]
When `treemacs-do-add-project-to-workspace` is called with the path argument: `nil`

This happens when `SPC p t` is pressed in Spacemacs, from for example:
`.spacemacs` which isn't in a project by default.

Then the minibuffer shows: `Wrong type argument: arrayp, nil`
and the messages buffer also shows the command:
`treemacs-do-add-project-to-workspace: Wrong type argument: arrayp, nil`

It should probably have a descriptive error message. Maybe something like:
- [Treemacs] Not in a project, nothing to add.
- [Treemacs] This needs to be called from a project.

Or something better.

**Comment by Alexander-Miller** [comment]
I could handle the error, but an error message is out of the scope of `treemacs-do-add-project-to-workspace`. It's an api function that returns a pattern depending on how the operation fared. Interactivity is up to its callers, for example see how it is used in `treemacs-add-project-to-workspace`.

I think I'll just implement spacemacs' project toggle in treemacs, I've been wanting that kind of function anyway.

**Comment by duianto** [comment]
I noticed that the Spacemacs Treemacs layer documentation is missing the global `SPC p t` binding.
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bfiletree/treemacs#global

It can be fixed with the Spacemacs PR when your project toggle function is finished:
- Replace the current `spacemacs/treemacs-project-toggle` function:
https://github.com/syl20bnr/spacemacs/blob/4b195ddfc9228256361e0b264fe974aa86ed51a8/layers/%2Bfiletree/treemacs/funcs.el#L12
- update the keybinding function: https://github.com/syl20bnr/spacemacs/blob/4b195ddfc9228256361e0b264fe974aa86ed51a8/layers/%2Bfiletree/treemacs/packages.el#L53
- And add the missing documentation.
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+filetree/treemacs/README.org#global

**Comment by Alexander-Miller** [comment]
Add-and-display-project command is made available in https://github.com/Alexander-Miller/treemacs/commit/86d5d91021c250b46a3beacf07a2e3250a5707e1. I didn't go with the toggle option as in spacemacs (I don't even remember when and why I dropped the whole toggle approach, but I'd rather let sleeping dogs lie), so spacemacs will still need a wrapper, but it can use the new macro in https://github.com/Alexander-Miller/treemacs/commit/c6ad6410c4893d9508e9b3dfc94a8a13b149c164.

**Comment by duianto** [comment]
Since this has been fixed in Treemacs I'll close this issue.

There's a PR in Spacemacs for possibly using the new function:
Fix treemacs-project-toggle (SPC p t) https://github.com/syl20bnr/spacemacs/pull/12614
