### ISSUE TITLE
treemacs-git-mode 'simple not working

### ISSUE THREAD

**Issue by jhacksworth** [Alexander-Miller/treemacs#383]
`treemacs-git-mode` `simple` variant stopped working after changes made in 8710692. The last working version for me is 51fd748.

I don't know if `extended` and `deferred` are affected as those variants don't work for me anyway.

This is on MacOS Mojave (10.14.3).

Edit: Sorry, I forgot to add Emacs version: 27.0.5 via  `brew install emacs-plus --HEAD`

**Comment by Alexander-Miller** [comment]
> treemacs-git-mode simple variant stopped working after changes made in 8710692. 

Fix will be pushed tomorrow.

> I don't know if extended and deferred are affected as those variants don't work for me anyway.

Do you have python3, is `treemacs-python-executable` pointing to it?

**Comment by jhacksworth** [comment]
> Fix will be pushed tomorrow.

Awesome! Thank you, @Alexander-Miller!

> Do you have python3, is treemacs-python-executable pointing to it?

You mean the way it's explained in the _Configuration_ section of the README? Arghh. Thanks for pointing it out to me. 😳 Both `extended` and `deferred` variants work, it's only `simple` that doesn't work.

Thanks for making treemacs, it's a great package. 🍻

**Comment by Alexander-Miller** [comment]
The readme is a bit on the long side, so it's easy for such details to split by unnoticed. I'm hoping https://github.com/Alexander-Miller/treemacs/issues/370 can fix that.

**Comment by jhacksworth** [comment]
> The readme is a bit on the long side, so it's easy for such details to split by unnoticed.

That's very gracious of you. #370 looks like good idiot-proofing ;)

The fix in 5230528 works great, thanks again!
