### ISSUE TITLE
[Misc] Another Clippy message typo

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#384]
It sounds like a word is missing from this line:
https://github.com/Alexander-Miller/treemacs/blob/b1aa44e0136c4144e02ef5bffc88d8ac4c41fec6/src/elisp/treemacs-mode.el#L379

Maybe `but this only the major mode` should be changed to:
- `but this is only the major mode`
- or just: `but this is the major mode`

Or to something better.

**Comment by Alexander-Miller** [comment]
Doh!
