### ISSUE TITLE
View highlighted file and/or directory name

### ISSUE THREAD

**Issue by dmocek** [Alexander-Miller/treemacs#389]
I have projects where the file names have a similar beginning and where the names can be long.  E.g.

MyFileLongFileNameAbc.js
MyFileLongFileNameDef.js
MyFileLongFileNameGhi.js

  When I'm in a directory in Treemacs with files like this and traversing the tree, I only see the beginning portion of the file names, which are the same.  E.g.

MyFileLongFileNa
MyFileLongFileNa
MyFileLongFileNa

  So I see 2 or more files which looks the same.  When deciding which file to open, It seems my current only choices are to change the width of Treemacs to see the whole file names, then change it back when I'm done; to preview the file; or to open it.

I'd like to see the name of the highlighted file (at least) and possibly the dir/name of the file somewhere (in the Emacs status bar perhaps).

**Comment by Compro-Prasad** [comment]
I think it would be good to check for long file names and check if they have common prefix or suffix. Then we can decide which part to show with leading or ending `...`.

**Comment by Alexander-Miller** [comment]
For now you can change the default width of the treemacs window. Calling `end-of-line` will also move the view to the right.

> I think it would be good to check for long file names and check if they have common prefix or suffix.

Oh no, those kind of checks and transformations will need to happen straight inside the most inner part of the render loop, slowing down *everyhing*. I'd rather take a look at implementing eldoc-mode for treemacs.

**Comment by Compro-Prasad** [comment]
That seems like a good option.

**Comment by Alexander-Miller** [comment]
Turns out it's very inconvenient to implement eldoc for a mode like treemacs, I would have to deal with adding most of treemacs' commands to eldoc's it's-ok-to-display-now obarray. Luckily I already had implemented a mechanism I could hook into.

**Comment by dmocek** [comment]
I would like to re-visit this issue.  Going to the end of the line does work, but it's not a very good UI.  I go from seeing the first half of the file name to seeing only the second half.  Some of our repos have very long directory structures and this isn't a great option.  The best solution I've worked with is to provide a toggle hot key which expands the Treemacs window to the right-most text in Treemacs.  I can then toggle/expand, browse Treemacs, then toggle/contract and continue my work.

**Comment by Alexander-Miller** [comment]
> View highlighted file and/or directory name

This part \^ is done and you're asking for a new feature, so let's handle that in a new issue.

A width toggle should not be a problem, but I'm curious how you handled the problem in other editors. AFAIK the likes of vsc and eclipse don't have a width-adjustment either.

**Comment by dmocek** [comment]
This is related to issue #439 (https://github.com/Alexander-Miller/treemacs/issues/439).
