### ISSUE TITLE
Ignoring git files in simple git mode broke in 5230528

### ISSUE THREAD

**Issue by dds** [Alexander-Miller/treemacs#390]
Ignoring git files with simple `treemacs-git-mode` broke in 5230528 because it changed the type of the keys in the git-info HT into strings.  

Changing `treemacs--is-file-git-ignored?` to use the following test fixes it for me:

`(equal "!" (ht-get ,git-info ,file))`

**Comment by Alexander-Miller** [comment]
Should be fixed now.
