### ISSUE TITLE
[Eldoc] Potential for subtle bugs in the current Eldoc implementation 

### ISSUE THREAD

**Issue by Jasu** [Alexander-Miller/treemacs#396]
This is not a bug report, just a warning about the behavior of the Eldoc feature. I have not (at least yet) had any issues with this, but there might be some subtle issues lurking:

The Eldoc string is propertized with `put-text-property` instead of `propertize`, so  the original path string is modified in place. The path string is also used as `:key` for the nodes.

```
(when treemacs-eldoc-display
  (put-text-property 0 (length path) 'face 'font-lock-string-face path)
```

With `treemacs-eldoc-display`, both `(treemacs-button-get (treemacs-current-button) :key)` and `(treemacs-button-get (treemacs-current-button) :path)`
output `#("/home/jasu/.emacs.d/evil-cleverparens/evil-cleverparens-autoloads.el" 0 68 (face font-lock-string-face))`

**Comment by Alexander-Miller** [comment]
Oh yes, I thought so as well, and will correct this soon. I wrote that part with the mindset from https://github.com/Alexander-Miller/treemacs/commit/4d26e81f09f5bb38d63995df87a4cadce7f58b0c, where I found out that `put-text-property` is much faster than `propertize` (no allocations and no garbage), but of course that does not matter for a single string.

Whatever bugs this would cause would even not be without precedent, I remember running some difficult to track issues caused by `nconc` altering nodes' paths from somewhere deep inside the extension api.

**Comment by Jasu** [comment]
Yeah, I have my own mode line and I used `put-text-property` for the same reason. I used it on constant strings, thinking that surely Emacs would have to copy that constant. But after the `put-text-property` on a constant `" "` all `" "` strings used in the function were propertized, even on subsequent calls.

One option would be to write to the minibuffer directly, it would also not clutter the messages buffer, something like this:

```
        (when (and treemacs-eldoc-display
                   (not (current-message)))
          (with-current-buffer " *Minibuf-0*"
            (erase-buffer)
            (insert path)
            (put-text-property 1 (1+ (length path)) 'face 'font-lock-string-face)))
```

I'm not exactly sure though if there are cases other than `(current-message)` that should be checked, and whether `" *Minibuf-0*"` is always the default minibuffer. Getting the buffer shown in the minibuffer window is probably a bad idea, since it might be something other than the buffer showing the echo area, e.g. Ivy.

**Comment by Alexander-Miller** [comment]
> and whether " *Minibuf-0*" is always the default minibuffer.

From what I can see it is (counsel uses Minibuf-1). I don't think we'd be in the wrong to always use Minibuf-0 - cases when it is not the minibuffer are exceptional, so whatever exceptions they may be, we'll simply bypass them without interfering.

**Comment by Alexander-Miller** [comment]
Change is reverted. I noticed that the minibuffer remains filled with treemacs' output, even if you navigate to another window, right after pushing. Maybe dealing with eldoc will be easier after all.

**Comment by Alexander-Miller** [comment]
Next attempt, now with 100% more eldoc.

I think I caught most of the commands eldoc should be triggered after, let me know if I missed anything.

**Comment by Jasu** [comment]
Nice! At least `treemacs-leftclick-action` should be on the list I think.

**Comment by Alexander-Miller** [comment]
Done.
