### ISSUE TITLE
Treemacs dired seems to miss first two entries

### ISSUE THREAD

**Issue by mcraveiro** [Alexander-Miller/treemacs#397]
Hi treemacs developers,

many thanks for an **incredible** addition to emacs! I've used it for a couple of days and my emacs life has already improved dramatically :-) I have one minor problem with treemacs dired though, which I believe must be related to my configuration but I just can't figure it out. Any pointers would be really appreciated. The gist of it is, when I go into a dired buffer I somehow seem to be missing icons for the first two entries:

![missing_first_two_lines](https://user-images.githubusercontent.com/180654/55063076-20006700-506f-11e9-9aef-f955ae428375.png)

This is for every folder, regardless of its content (e.g. files, directories, etc). Its always the first two entries. I thought this could be related to my dired settings so I tried a few permutations:

```
(setq dired-listing-switches "-l")
(setq dired-listing-switches "-lGh1v --group-directories-first")
...
```

But I always get the same result. I have tried restarting emacs after changing as well. Apologies if this has been answered before but my google-fu was weak and could not find it.

Many thanks for your time.

Marco

**Comment by Compro-Prasad** [comment]
Did you tried with `-a`?

**Comment by mcraveiro** [comment]
Hi @Compro-Prasad 

Ah, I'm afraid I didn't, as I didn't want all of the hidden files to start showing up! But that's a great point, could this be some artefact related to the handling ```.``` and ```..```?

**Comment by mcraveiro** [comment]
Jeez, this is so obvious, can't believe I didn't think of it! :-) I was wondering, "weird, why is it always _exactly_ the first two entries?" :-D

**Comment by Alexander-Miller** [comment]
I don't even know why I didn't include those 2 in the first place...

Since there is no good way to detect whether the "a" switch is present (the switches are just a string so I cannot just look for an "a" or I'll also find `--almost-all`) adding icons for . and .. is the only solution.

**Comment by mcraveiro** [comment]
Excellent, thanks very much for your prompt response @Alexander-Miller!

**Comment by mcraveiro** [comment]
By the by, I've applied the fix locally and it works great. Cheers.
