### ISSUE TITLE
Jump over empty lines between projects?

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#401]
Could there be a use for having the cursor on an empty line between the projects?

If not, then maybe the cursor should jump over the empty lines and only move between the projects (or from a projects last dir/file to the next project).

**Comment by Jasu** [comment]
I have the commands in my config, bound to up/down. If @Alexander-Miller thinks this should be incorporated into `treemacs-next-line` and `treemacs-previous-line`, I could open a PR (and maybe make the wrapping over at buffer bounds configurable)

```elisp
(defun config/treemacs-next-line ()
  "Go to the next line in Treemacs, handling empty lines."
  (interactive)
  (if (and (treemacs-current-button)
           (not (next-button (button-start (treemacs-current-button)))))
      (progn
        ;; If we are in the middle of a button, forward-button goes to
        ;; movement must happen twice. Move to the last column first.
        (goto-char (line-end-position))
        (forward-button 1 t))

    (treemacs-next-line 1)
    ;; Skip empty lines
    (unless (treemacs-current-button)
      (treemacs-next-line 1))))

(defun config/treemacs-previous-line ()
  "Go to the previous line in Treemacs, handling empty lines."
  (interactive)
  (if (and (treemacs-current-button)
           (not (previous-button (button-start (treemacs-current-button)))))
      (progn
        ;; If we are in the middle of a button, backward-button goes to
        ;; the start of the button. Move to the first column first.
        (move-to-column 0)
        (backward-button 1 t))

    (treemacs-previous-line 1)
    ;; Skip empty lines
    (unless (treemacs-current-button)
      (move-to-column 0)
      (treemacs-previous-line 1))))
```

**Comment by Alexander-Miller** [comment]
I'm not opposed to this kind of change, but I wonder if it's really necessary. If you don't like the space between projects you can just set `treemacs-space-between-root-nodes` to nil.

**Comment by duianto** [comment]
I'm not for or against them. It probably looks better with an empty line between the projects for separation.
I just thought that if there's no real reason to stop on an empty line, then the cursor might as well jump over it. I'll adapt to any changes you make. Your doing a great job with Treemacs 👍 

Just stick this at the bottom of the "maybe some day" pile, if someone else brings it up again in the future, then it can be revisited 😄

**Comment by Compro-Prasad** [comment]
I was thinking of providing a dropdown menu for selecting a project in a workspace instead of jumping to a different project tree in the same buffer. It will look cleaner but might take a bit more rendering time. @Alexander-Miller Am I correct about this?

**Comment by Jasu** [comment]
I'll make a PR about the line-skipping soon - I like to have the projects visually separated, but that shouldn't affect usability. (The PR will be cleaner than the config example I gave, I wrote that when I was still an Elisp beginner)

**Comment by Alexander-Miller** [comment]
@Compro-Prasad I'm not sure I follow, your proposal sounds like it has nothing to do with this particular ticket. Also treemacs' workspaces have yet to reach the kind of state where you can freely switch between them, so I am not sure if we're talking about the same things.

> It will look cleaner but might take a bit more rendering time. 

Cleaner and slower than what? I think  I think I'm missing some context here.

**Comment by Compro-Prasad** [comment]
Currently, when I have opened 3 projects, Treemacs  shows it like:
```
- p1
  + f1
  + f2

+ p2

+ p3
```
What I want is:
```
[- p2]
  + f3
  + f4
```
Where `[- p2]` is basically a dropdown menu which will provide a list of opened projects to switch to(here `p1` and `p3`). This will require some kind of narrowing or re-rendering of the project tree in the buffer. Narrowing will probably be faster than re-rendering so it is the only way to go.

**Comment by Alexander-Miller** [comment]
Ok, now I understand what you're going for. Narrowing would work, getting the first part to work is even downright trivial, but it would also turn many common operations into edge cases, basically forcing me to splatter the code base with calls to `save-restriction` and `widen`, which I would rather not get into.

I will try an overlay-based approach à la org next, but if that turns out to have similar issues I'd rather stop pursuing this.

A selection mechanism on the other hand is no problem at all, and there's an issue already in #306, all I need to do is wait for @TimoFreiberg to stop deploying on a friday :o.

**Comment by Compro-Prasad** [comment]
IMO narrowing would restrict the operations only to the currently selected project. This would be beneficial to the user in many ways. This is a huge step but don't know if its the step in the right direction.
