### ISSUE TITLE
Indicator for when project(s) are scrolled above the window

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#402]
There should probably be some kind of indicator when the window is scrolled so that there are project(s) above the Treemacs window.

Possibly: `^^^` on the first line.

**Comment by Alexander-Miller** [comment]
Fortunately this can be achieved using the header-line-format, I would not have wanted to add a global timer for this. I'll come around to this after https://github.com/Alexander-Miller/treemacs/issues/371

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Stayin alive.
