### ISSUE TITLE
Treemacs fails to load projects into workspac after restart

### ISSUE THREAD

**Issue by Wojtek242** [Alexander-Miller/treemacs#412]
I updated treemacs today from `20190331.1019` to `20190413.958` and every time I restart Emacs it fails to find the projects in the workspace and it outputs the following error:

```
# Error was (void-function (setf treemacs-project->path-status))

* Default Workspace
** .emacs.d
 - path :: /home/wojtek/.emacs.d
```

**Comment by Wojtek242** [comment]
From `*Messages*` buffer

```
[Treemacs] Error '(void-function (setf treemacs-project->path-status))' when loading the persisted workspace.
```

**Comment by Alexander-Miller** [comment]
> (setf treemacs-project->path-status)

I cannot find this line in the code base. My guess is that treemacs was not installed/compiled correctly, it certainly wouldn't be the first time something like this happened. Check if simply reinstalling treemacs fixes it. If not then evaluate the following code *before* loading treemacs, then try again. You should see a stack trace that I need to track this down.

```Lisp
(defun treemacs--restore ()
  "Restore treemacs' state from `treemacs-persist-file'."
  (unless (treemacs--should-not-run-persistence?)
    (-when-let (lines (treemacs--read-persist-lines))
      (let ((kill-emacs-hook (remq #'treemacs--persist kill-emacs-hook)))
        (pcase (treemacs--validate-persist-lines lines)
          ('success
           (setf treemacs--workspaces (treemacs--read-workspaces (make-treemacs-iter :list lines))
                 (treemacs-current-workspace) (car treemacs--workspaces)))
          (`(error ,line ,error-msg)
           (treemacs--write-error-persist-state lines (format "'%s' in line '%s'" error-msg line))
           (treemacs-log "Could not restore saved state, %s:\n%s\n%s"
                         (pcase line
                           (:start "found error in the first line")
                           (:end "found error in the last line")
                           (other (format "found error in line '%s'" other)))
                         error-msg
                         (format "Broken state was saved to %s"
                                 (propertize treemacs--last-error-persist-file 'face 'font-lock-string-face)))))))))
```

**Comment by Wojtek242** [comment]
Yep, that worked. Would you like to close this now? I can help chase the root cause down, but that's only if you think that's worth the time.

**Comment by Jasu** [comment]
> I cannot find this line in the code base.

The error is a bit misleading here. When you create a `defstruct`, Elisp creates a `setf` extension for the field, and `(setf function-name)` refers to that setter. If you run `(setf (some-function-that-does-not-exists) 1)`, you will get this:

```
Symbol’s function definition is void: \(setf\ some-function-that-does-not-exists\)
e
```

**Comment by Alexander-Miller** [comment]
Yep, I'm aware of the whole gv thing. I was really just hoping that an incorrect call somehow made it inside the code. That would've been an easy fix. Instead we have what appears to be some kind of compiler or package.el bug. 

Something similar has already happened once or twice before and I could never trace it. All my `require` calls were in the right place, all the macros were available at compile-time etc. Do you have any clue where this might be coming from?
