### ISSUE TITLE
On any changes, Treemacs grabs the window, causing lsp-ui-doc to go away

### ISSUE THREAD

**Issue by jdemilledt** [Alexander-Miller/treemacs#417]
This is linked to behavior in lsp-ui-doc that tells it to hide the documentation if a different window is active. Whenever I make a change, Treemacs updates its tag tree, taking the active window briefly, and tripping lsp-ui-doc.

**Comment by Alexander-Miller** [comment]
Are your lsp packages up-to-date? This should've been fixed in https://github.com/emacs-lsp/lsp-ui/pull/273.

**Comment by jdemilledt** [comment]
I need to run updates more frequently, I guess. Checking now.

**Comment by jdemilledt** [comment]
That fixed it, thanks!
