### ISSUE TITLE
How am I suppose to ignore files in treemacs

### ISSUE THREAD

**Issue by patata3000** [Alexander-Miller/treemacs#419]
I would like treemacs to stop showing __pycache__ directories.
How am I suppose to do that? I don't know a thing in elisp so I'd need a detailed explaination. :/
I tried stuff from: https://github.com/Alexander-Miller/treemacs/issues/164 but I couldn't manage to make it work. I couldn't find a way to use treemacs-ignored-file-predicates...

Another question. Am I supposed to post these kind of question here or should I go to stackoverflow or others?

**Comment by Alexander-Miller** [comment]
> Am I supposed to post these kind of question here or should I go to stackoverflow or others?

I dunno if treemacs is popular enough for you to get an answer there (I don't have an account), so asking here is fine.

> I couldn't find a way to use treemacs-ignored-file-predicates

The example in #164 is correct, all you should need to do is replace "gitignore" with whatever you don't want to see. I've added another example to the FAQ, but it's essentially the same code, so you will have to elaborate what "couldn't find a way" really means.

**Comment by patata3000** [comment]
Oh my bad, I thought that the snippet in #164 was to not include all files referenced inside the .gitignore file. Yeah I replaced ".gitignore" by __pycache__ and it worked just fine :)
