### ISSUE TITLE
Is it possible to rename a file?

### ISSUE THREAD

**Issue by tanrax** [Alexander-Miller/treemacs#42]
It seems like an obvious question, but I can not find the form :)

**Comment by Alexander-Miller** [comment]
It's not possible yet, but I can implement it.

**Comment by Alexander-Miller** [comment]
Renaming's pushed now, you'll find it bound to R. 

Please go ahead and play around with it, I need to make sure I didn't miss anything. All cases should be covered correctly - caches are updated, so any expanded dirs and tags stick around, windows and buffers are properly reloaded, including buffers visiting files inside a renamed directory, recentf-list is likewise updated with the renamed files.

**Comment by Alexander-Miller** [comment]
I take it that hooray emoji reaction thing on my comment means everything's well? If so I'll be close up here.

(For future reference: it's better for feedback to be a comment, since I'll get an email notification for it.)
