### ISSUE TITLE
[Feature Request] Drag and drop a file to a specific window

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#425]

**Comment by Compro-Prasad** [comment]
@Alexander-Miller I have an implementation for this feature. See if its okay so that I can open a PR:
```
(defvar treemacs-selected-button nil)

(defun treemacs-do-selection (event)
  (interactive "e")
  (when (eq 'down-mouse-1 (elt event 0))
    (select-window (elt (elt event 1) 0))
    (goto-char (posn-point (cadr event)))
    (setq treemacs-selected-button (treemacs-current-button))
    (when (region-active-p)
      (keyboard-quit))))

(defun treemacs-open-selection (event)
  (interactive "e")
  (when (eq 'drag-mouse-1 (elt event 0))
    (select-window (elt (elt event 2) 0))
    (find-file (treemacs-safe-button-get treemacs-selected-button :path))))

(evil-define-key 'treemacs treemacs-mode-map [down-mouse-1] 'treemacs-do-selection)
(evil-define-key 'treemacs treemacs-mode-map [drag-mouse-1] 'treemacs-open-selection)
```

**Comment by Compro-Prasad** [comment]
@Jasu Any thoughts on this?

**Comment by Alexander-Miller** [comment]
> See if its okay so that I can open a PR

LGTM

**Comment by Compro-Prasad** [comment]
Will I use `evil-define-key` or something else?

**Comment by Jasu** [comment]
I think there should also be a check that `:path` is a string, so that extension nodes may not be dragged.

**Comment by Jasu** [comment]
Oh, and directory paths should probably use `dired` instead of `find-file`.

**Comment by Alexander-Miller** [comment]
> Will I use evil-define-key or something else? 

Keybinds must work with and without evil, so you'll need a default keymap entry in -mode.el and an evil entry in -evil.el, same as the current click setup.

> I think there should also be a check that :path is a string, so that extension nodes may not be dragged.

Tags will probably need their own checks and extensions could define their own drag actions (it'd make sense for your bookmarks or my buffers), but that's an idea for another issue. Making files and directories work will be enough for right now.

**Comment by Compro-Prasad** [comment]
> Oh, and directory paths should probably use `dired` instead of `find-file`.

IMO `find-file` uses `dired` for directories.

**Comment by Jasu** [comment]
> IMO find-file uses dired for directories.

My bad, you're right!

> Making files and directories work will be enough for right now.

I meant a simple check to prevent an error if the user accidentally dragged an extension node (or tag), not actually making the dragging work for other button types.

**Comment by Compro-Prasad** [comment]
> I meant a simple check to prevent an error ...

Yeah I will put that check.
