### ISSUE TITLE
[feature request] consider gitignore files and folders as hidden

### ISSUE THREAD

**Issue by mpanarin** [Alexander-Miller/treemacs#426]
I think it is worth to make files and directories ignored by git to be considered hidden. Is there a way to do this? Because most of the time its some autogenerated config folders etc, that are not very useful most of the time, but can be usefull enough not to add them to treemacs ignore list.

**Comment by Compro-Prasad** [comment]
Its already there https://github.com/Alexander-Miller/treemacs#faq

**Comment by Compro-Prasad** [comment]
Its already there https://github.com/Alexander-Miller/treemacs#faq

**Comment by Alexander-Miller** [comment]
Yep, the faq points out the correct answer, though now that I think about it there is no other reason you would ever want to touch `treemacs-pre-file-insert-predicates` other than disabling display of ignored files, so unless you guys can think of something else I'll use this issue to replace the current approach with a simple toggle variable.

**Comment by mpanarin** [comment]
big thanks for the answers!

And yes, i think you are correct and it will be a lot clearer after )

**Comment by martenlienen** [comment]
The solution from the FAQ works nicely to hide for example `__pycache__` files. But sometimes I still want to look at files that are gitignored, for example program outputs. Is there a way to mark files as hidden similar to dotfiles instead of filtering them completely? That way they would be out of the way but I could still show them with `t v`.

**Comment by Alexander-Miller** [comment]
The toggle is added, you can now switch the display of gitignored files at will with "ti".

**Comment by martenlienen** [comment]
Thanks a lot, that feature is exactly what I was looking for!
