### ISSUE TITLE
Is it possible to mute the refresh message ?

### ISSUE THREAD

**Issue by jschaeff** [Alexander-Miller/treemacs#43]
Thank you, this tree mode is excellent !

I find it annoying the message in the minibuffer each time a refresh is done. Specifically when using magit, this message gets in the way. Is it possible to deactivate it ?

**Comment by Alexander-Miller** [comment]
Not yet. I'll add the option in a new version alogside https://github.com/Alexander-Miller/treemacs/issues/42.

**Comment by Alexander-Miller** [comment]
Renaming is taking a while, so I pushed this first. See the new `treemacs-silent-refresh` option.
