### ISSUE TITLE
Error running timer ‘treemacs--follow’: (invalid-function (file-notify-error "No file notification program found")) 

### ISSUE THREAD

**Issue by iocanel** [Alexander-Miller/treemacs#430]
Using the current master:

The message in the title appears each time `follow` is triggered  (e.g. switching buffer).
The `follow` seems to work, but the message is a bit annoying.

**Comment by Alexander-Miller** [comment]
> (invalid-function (file-notify-error "No file notification program found"))

There's nothing wrong with the part of the code where this is specified, so I assume it's a compiler/package.el blooper - it wouldn't be the first time it happened. Try reinstalling.

**Comment by iocanel** [comment]
Thanks for the hint. It seeems that it worked.

**Comment by Jasu** [comment]
I'm guessing that these issues are caused by `byte-recompile-directory` compiling files with already loaded macro definitions, or compiling `treemacs-follow-mode.el` before `treemacs-macros.el` while an old `treemacs-macros.elc` exists.
