### ISSUE TITLE
Rebuilding treemacs breaks wipes my workspace setup

### ISSUE THREAD

**Issue by iocanel** [Alexander-Miller/treemacs#431]
Each time I rebuild treemacs I loose my workspace configuration.

FWIW, I use `straight-use-package` for pulling changes and rebuilding.

**Comment by Alexander-Miller** [comment]
Treemacs saves its state in `treemacs-persist-file`, its default value is `$user-emacs-directory/.cache/treemacs-persist`. Let's start with observing this file, see if and when it's deleted or its content changed during an update.

**Comment by iocanel** [comment]
More info:

- At the moment it happens most of the time, even between restarts (most but not always).
- Even when it happens, the file is there and it DOES contain my workspaces and projects.
- The file is wiped if I try to edit workspace or add/remove.

**Comment by iocanel** [comment]
When it happens the error I see in the logs is:

[Treemacs] Could not restore saved state, found error in line '* Default Workspace':

**Comment by Alexander-Miller** [comment]
And then what? The actual error message is the interesting part.

**Comment by Alexander-Miller** [comment]
In fact if you have a file that you *know* is going to break just paste it here, I'll try if it works on my end.

**Comment by iocanel** [comment]
Here's one:

    * Default Workspace
    ** home
     - path :: /home/iocanel
    * idee
    ** idee
     - path :: /home/iocanel/.emacs.d/straight/repos/idee
    * ap4k
    ** ap4k
     - path :: /home/iocanel/workspace/src/github.com/ap4k/ap4k

**Comment by Alexander-Miller** [comment]
Well there's your problem. You cannot have directories appearing in treemacs twice. it introduces ambiguities that treemacs is not equipped to deal with.

Of course I need to properly catch and report that error, but your first project still needs to go.

**Comment by iocanel** [comment]
@Alexander-Miller: thanks, let me remove that and see how it goes.

**Comment by iocanel** [comment]
It seems that after removing the duplicate directory, everything works fine.

**Comment by Alexander-Miller** [comment]
Let's keep this open, not catching this issue in your layout is a bug
that needs to be fixed on my end.
