### ISSUE TITLE
Bookmark integration v2

### ISSUE THREAD

**Issue by Jasu** [Alexander-Miller/treemacs#438]
In my Treemacs Bookmark, I integrated Treemacs with `bookmark.el`'s `bookmark-set` and `bookmark-jump`.

The difference from `treemacs-bookmark` is that the bookmark actually points to a Treemacs path, and is not a regular file bookmark. Jumping to the bookmark with `bookmark-jump` or `bookmark-bmenu-list` from anywhere will open Treemacs, rather than relying on a special command to find a regular file bookmark in Treemacs.

I feel that this functionality could be in Treemacs itself rather than in treemacs-bookmark - do you want a PR about this, or should I keep it in treemacs-bookmark?

The preliminary version of this is [here.](https://github.com/Jasu/treemacs-bookmark/commit/02420c7aba12c9407fff80fa590eee64558ebca3) If I was to open a PR, I would implement it without having to `(require 'bookmark)` and make some fixes I'm about to do anyway, e.g. make the handler function autoloadable and the default bookmark name configurable.

**Comment by Alexander-Miller** [comment]
> I feel that this functionality could be in Treemacs itself rather than in treemacs-bookmark

Sounds good to me :+1:
