### ISSUE TITLE
Toggle to expand FileTree window

### ISSUE THREAD

**Issue by dmocek** [Alexander-Miller/treemacs#439]
I have projects where the file names have a similar beginning and where the names can be long. E.g.

MyFileLongFileNameAbc.js
MyFileLongFileNameDef.js
MyFileLongFileNameGhi.js

When I'm in a directory in Treemacs with files like this and traversing the tree, I only see the beginning portion of the file names, which are the same. E.g.

MyFileLongFileNa
MyFileLongFileNa
MyFileLongFileNa

So I see 2 or more files which looks the same. When deciding which file to open, It seems my current only choices are to change the width of Treemacs to see the whole file names, then change it back when I'm done; to preview the file; or to open it.

The best solution I've worked with is to provide a toggle hot key which expands the Treemacs window to the width of the right-most text in Treemacs. I can then toggle/expand, browse Treemacs, then toggle/contract and continue my work.

GUI IDE's like Visual Studio Code and IntelliJ have a pop-up with the full file name when you hover over the partially displayed file name with the mouse pointer.  Fine, if you want to reach for the mouse, which I don't.

A toggle expand/contract window is a better solution than highlighting the file as you can see all of the files and spot the one you want quicker.

This is related to issue #389 (https://github.com/Alexander-Miller/treemacs/issues/389)

**Comment by Alexander-Miller** [comment]
> It seems my current only choices are to change the width of Treemacs to see the whole file names, then change it back when I'm done; to preview the file; or to open it.

#389 saw the implementation of eldoc integration just for that purpose. Is this insufficient, or do you just not use eldoc (I should probably turn it on for treemacs if `treemacs-eldoc-display` is t, now that I think about it)?

**Comment by dmocek** [comment]
eldoc works for now (Thanks!), but after I think about it, I think the toggle is a better way of working.  The reason being I can visually scan the whole list of files in Treemacs easily if the window is larger.  I can page up/down and see the entire tree.

**Comment by kriansa** [comment]
@dmocek 

In case you still need it, I'm using the function below to provide the width toggle functionality:

```elisp
(defun mine/toggle-maximize-treemacs ()
  "Maximize/restore Treemacs buffer."
  (interactive)
  (unless (boundp 'treemacs--original-width)
    (setq treemacs--original-width treemacs-width))
  (with-selected-window (treemacs-get-local-window)
    (setq treemacs-width
      (if (= treemacs-width treemacs--original-width)
        (/ (frame-width) 2)
        treemacs--original-width))
    (treemacs--set-width treemacs-width)))
```

It enlarges by the half the size of the frame.

**Comment by dmocek** [comment]
Nice!  I added this also to my dotspacemacs/user-config so I can use 'SPC t t' to toggle this:

(spacemacs/set-leader-keys "tt" 'mine/toggle-maximize-treemacs)

**Comment by Alexander-Miller** [comment]
Stayin alive.
