### ISSUE TITLE
ignore file patterns

### ISSUE THREAD

**Issue by thorstengrothe** [Alexander-Miller/treemacs#442]
Hi,

I have several latex projects with lots of file types like

`*.aux *.log *.rel etc`

I would like to advise treemacs to ignore those filetypes. I found this in #164 

```
(with-eval-after-load 'treemacs
  (defun treemacs-ignore-gitignore (file _)
    (string= file ".gitignore")) ;; (string= file "*.aux) --> does not work
  (push #'treemacs-ignore-gitignore treemacs-ignored-file-predicates))
```

As you can see my modified version does not work. How can I filter out several file types in treemacs?

I'm not a elisp programmer, sorry :)

Thorsten

**Comment by Alexander-Miller** [comment]
Looks like you want to filter file extensions. You can do that like this:

```Lisp
(with-eval-after-load 'treemacs
  (defun treemacs-custom-filter (file _)
    (or (s-ends-with? ".aux" file)
        (s-ends-with? ".log" file)))
  (push #'treemacs-custom-filter treemacs-ignored-file-predicates))
```

**Comment by thorstengrothe** [comment]
Works perfect, thank you!
