### ISSUE TITLE
Changing theme hides non-selected items

### ISSUE THREAD

**Issue by mguentner** [Alexander-Miller/treemacs#446]
I am using syl20bnr/spacemacs@6f3418578466c45e2ac95b6edaf1783707e521a1

When I start emacs fresh with any theme, treemacs works as expected, once I change to
another theme, all icons disappear that are not selected.
After going once to another theme only `default` theme will display icons again, for
all other themes I need to restart emacs.

![Peek 2019-05-22 14-44](https://user-images.githubusercontent.com/668926/58175278-162a6700-7ca0-11e9-84c4-f498dd6017ef.gif)

**Comment by Alexander-Miller** [comment]
What is the value of `treemacs-icon-open`, both with the default theme and after loading another?

**Comment by mguentner** [comment]
# before
```
Its value is
#("  " 0 1
  (img-unselected #1=(image :type imagemagick :file "/home/max/.emacs.d/elpa/develop/treemacs-20190309.1812/icons/dir_open.png" :scale 1 :ascent center :width 22 :height 22 :background "#292b2e")
                   img-selected
                   (image :type imagemagick :file "/home/max/.emacs.d/elpa/develop/treemacs-20190309.1812/icons/dir_open.png" :scale 1 :ascent center :width 22 :height 22 :background "#212026")
                   display #1#))
```

# after
```
Its value is
#("  " 0 1
  (img-unselected #1=(image :type imagemagick :file "/home/max/.emacs.d/elpa/develop/treemacs-20190309.1812/icons/dir_open.png" :scale 1 :ascent center :width 22 :height 22 :background unspecified)
                   img-selected
                   (image :type imagemagick :file "/home/max/.emacs.d/elpa/develop/treemacs-20190309.1812/icons/dir_open.png" :scale 1 :ascent center :width 22 :height 22 :background "#383838")
                   display #1#))
```

**Comment by Alexander-Miller** [comment]
Do the icons come back if you run this?

```Lisp
(--each (treemacs--created-icons)
  (treemacs--set-img-property
   (get-text-property 0 'img-selected it)
   :background "red")
  (treemacs--set-img-property
   (get-text-property 0 'img-unselected it)
   :background "green"))
```

**Comment by Alexander-Miller** [comment]
> :background unspecified

Had time to run some tests and this here's the culprit. Now we need to find out why it's set like this - I added explicit guards to prevent that value.

Assuming you're on emacs 26 run the following code, then change your theme. I will need to see the backtraces it produces.

```Lisp
(add-variable-watcher
 'treemacs--not-selected-icon-background
 (lambda (_ newval operation where)
   (backtrace)
   (message "SET BG Value %s OP %s WHERE %s" newval operation where)))
```

**Comment by mguentner** [comment]
Okay. This is the output of the process: Starting emacs, changing theme once:

https://gist.github.com/mguentner/9f9deb34b4b8bab27dc25ed8b5fdc9c2

**Comment by Alexander-Miller** [comment]
Now I understand why the fallback didn't work, but not why it would have been necessary in the first place. Let's try something else. Instead of the variable-watcher load treemacs, eval the folllowing code and change your theme once. What does that output?

```Lisp
(defun treemacs--setup-icon-background-colors (&rest args)
  (treemacs-log  "Icon change with args: %s" args)
  (let* ((default-background (face-attribute 'default :background nil t))
         (hl-line-background (face-attribute 'hl-line :background nil t))
         (icon               (car (treemacs--created-icons)))
         (icon-background    (treemacs--get-img-property (get-text-property 0 'img-unselected icon) :background))
         (icon-hl-background (treemacs--get-img-property (get-text-property 0 'img-selected icon) :background)))
    (treemacs-log "Current default background %s" default-background)
    (treemacs-log "Current hl-line background %s" hl-line-background)
    (treemacs-log "Current default icon background %s" icon-background)
    (treemacs-log "Current hl-line icon background %s" icon-hl-background)
    (when (memq default-background '(unspecified-bg unspecified))
      (treemacs-log "Default background is unspecified, falling back to #2f2f31")
      (setq default-background "#2d2d31"))
    (unless (and (string= default-background icon-background)
                 (string= hl-line-background icon-hl-background))
      (setf treemacs--selected-icon-background hl-line-background
            treemacs--not-selected-icon-background default-background)
      (treemacs-log "treemacs--selected-icon-background set to %s" treemacs--selected-icon-background)
      (treemacs-log "treemacs--not-selected-icon-background set to %s" treemacs--not-selected-icon-background)
      (--each (treemacs--created-icons)
        (progn
          (treemacs--set-img-property
           (get-text-property 0 'img-selected it)
           :background treemacs--selected-icon-background)
          (treemacs--set-img-property
           (get-text-property 0 'img-unselected it)
           :background treemacs--not-selected-icon-background))))))
```

**Comment by mguentner** [comment]
Wow. I learning quite a lot about how to do plumbing in emacs :)

So here is the output:

```
[Treemacs] Icon change with args: (spacemacs-dark)
[Treemacs] Current default background white
[Treemacs] Current hl-line background darkseagreen2
[Treemacs] Current default icon background #292b2e
[Treemacs] Current hl-line icon background #212026
[Treemacs] treemacs--selected-icon-background set to darkseagreen2
[Treemacs] treemacs--not-selected-icon-background set to white
[Treemacs] Icon change with args: (user)
[Treemacs] Current default background unspecified
[Treemacs] Current hl-line background #383838
[Treemacs] Current default icon background white
[Treemacs] Current hl-line icon background darkseagreen2
[Treemacs] Default background is unspecified, falling back to #2f2f31
[Treemacs] treemacs--selected-icon-background set to #383838
[Treemacs] treemacs--not-selected-icon-background set to #2d2d31
[Treemacs] Icon change with args: (zenburn)
[Treemacs] Current default background unspecified
[Treemacs] Current hl-line background #383838
[Treemacs] Current default icon background #2d2d31
[Treemacs] Current hl-line icon background #383838
[Treemacs] Default background is unspecified, falling back to #2f2f31
```

**Comment by mguentner** [comment]
With the code above it works as expected :+1: . Didn't notice at first

**Comment by Alexander-Miller** [comment]
> With the code above it works as expected 

Well it shouldn't. I did include a fix to properly recognize when a fallback is needed, but using the fallback means that the icons' background should not quite fit with the rest of your theme (though I guess it could be close enough to be difficult to see).

It also doesn't explain why the fallback is necessary. Zenburn does not define a default background only when run in a terminal, when icon colors don't matter anyway, but the gif you showed in a gui. If `(face-attribute 'default :background nil t)` returns a color treemacs should see it and use it.

**Comment by mguentner** [comment]
Ah, well. What I meant with expected was that the fallback works, with the rather unfitting background.

**Comment by Alexander-Miller** [comment]
In that case there's not much more I can do here. The fix for fallback recognition will be pushed soon, alongside a wider change for theme support, but the need for the fallback cannot be fixed on my end. All I do is ask emacs for the default background color and the answer I get is "dunno".

I didn't have the same problem when I tried zenburn myself today, so maybe you are running an old version?

**Comment by mguentner** [comment]
It appears to be okay now after I updated the packages again. Maybe I was indeed running an old version. I will test this a bit and report back if there are again issues.

Thank you.
