### ISSUE TITLE
TAB can't expand node in centos

### ISSUE THREAD

**Issue by shaynez** [Alexander-Miller/treemacs#447]
Hi author 
     As title, when I try to enable treemacs in spacemacs, everything is ok in windows version, but in my centos server, "TAB" can't expand node and hanged till I press Ctrl-g(emacs key mode) to cancel it, and after Ctrl-g, the node will expand out, next time is same,  TAB and C-g to expand node, TAB and C-g to expand....  no error in log, could you please help to find the root cause? thanks.

**Comment by Alexander-Miller** [comment]
Does it work when you disable git-mode or set `treemacs-collapse-dirs` to 0?

**Comment by shaynez** [comment]
Thanks.
1. I don't enable git mode
2.  (treemacs :variables
               treemacs-use-follow-mode t
               treemacs-use-filewatch-mode t
               treemacs-collapse-dirs 0)
     set treemacs-collapse-dirs to 0 still not work.
BTW:
when I try  to close emacs, app remind me there has running process, I find the number of running process equal the time I press TAB and C-g, so the problem looks like when I press TAB, a process will invoke and wait the result of it, but the process can't quit, then C-g could let treemacs quit wait, and expand to display the content of this node, and the process "Future" still hang there.
![image](https://user-images.githubusercontent.com/8834246/58464330-12975400-8168-11e9-8b14-50524331a185.png)

**Comment by Alexander-Miller** [comment]
> I don't enable git mode

Treemacs does. You have to disable it explicitly. The processes you see are started by either git-mode or the collapse-dirs feature.

**Comment by shaynez** [comment]
I have re-configured my .spacemacs from default, this issue has gone, I still don't find the root cause, thanks for your support.

**Comment by Alexander-Miller** [comment]
I guess we're done then :man_shrugging:
