### ISSUE TITLE
Toggle Display of Ignored Files in Git Mode

### ISSUE THREAD

**Issue by JP-Ellis** [Alexander-Miller/treemacs#450]
Is there any intention to add a toggle to show/hide files ignored by `.gitignore` (when `git-mode` is enabled).  It is nice having the files greyed out, but sometimes I would like to hide them completely.

I guess  this would work in exactly the same way as `treemacs-toggle-show-dotfiles`

**Comment by Alexander-Miller** [comment]
Good idea.

**Comment by Alexander-Miller** [comment]
The bad news is I've forgotten about this issue and it got lost among the others. The good news is that `treemacs-hide-gitignored-files-mode` has been implemented not too long ago.
