### ISSUE TITLE
`treemacs-root-open-png` and `treemacs-root-close-png`?

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#452]
I see there are these variables:

https://github.com/Alexander-Miller/treemacs/blob/242b3f265949d729726d6c4c999625e6ee7d6da6/src/elisp/treemacs-icons.el#L144-L149

I see that there are `treemacs-icon-open-png` and `treemacs-icon-close-png` so I've set up my Treemacs to look like this:
![image](https://user-images.githubusercontent.com/19470159/58758579-e6902000-8525-11e9-8c88-caa6c154c4c6.png)

But I'd like to have this arrow indicator for root node too, however there's no `treemacs-icon-root-open-png` or `treemacs-icon-root-closed-png` for that. Any chance there will be closed and opened icons for root?

**Comment by Alexander-Miller** [comment]
Sure, why not. I'll be adding support for icon themes soon, might as
well include this then.

**Comment by andreyorst** [comment]
Iguess with current approach the request is now changed to have new `:extensions` like `:extensions (root-closed))` and `:extensions (root-open))`?

**Comment by Alexander-Miller** [comment]
That's how it'll be used, but I will need to implement this first.
