### ISSUE TITLE
[not-a-bug][question] icons are not sized properly 

### ISSUE THREAD

**Issue by ngortheone** [Alexander-Miller/treemacs#454]
Hi @Alexander-Miller 
I am investigating Remacs bug that manifests in a small treemacs icons, that do not resize (`treemacs-resize-icons` has no effect) 
Some screenshots can be found here https://github.com/remacs/remacs/issues/1513

I wanted to ask for some help in debugging this problem. Remacs project replaces C code with Rust and it is likely that some regression was introduced during code rewrite. Maybe you have seen similar symptoms as you were developing treemacs?

We can exclude all the lisp (*.el) code from the suspects since nobody touched it. The bug is likely somewhere in C functions that treemacs relies upon (the ones that say `is a built-in function in ‘C source code’. ` in a docstring.

Can you help me narrow down my search of the suspect? Do you know what C functions might cause such problems?

Thanks!

P.S. This is not a bug report for Treemacs. This is an ask for help from opensource community!

**Comment by Alexander-Miller** [comment]
> Maybe you have seen similar symptoms as you were developing treemacs?

Not that I remember.

>Can you help me narrow down my search of the suspect? Do you know what C functions might cause such problems?

Icon creation comes down to calling into `create-image` with either a `png` or `imagemagick` type, preferring the latter since it makes the icons resizable. Here's the code that turns a path into an image:

```Elisp
(define-inline treemacs--create-image (file-path)
  "Load image from FILE-PATH and size it based on `treemacs--icon-size'."
  (inline-letevals (file-path)
    (inline-quote
     (let ((height treemacs--icon-size)
           (width treemacs--icon-size))
       ;; special case for the root icon which is unique in being 20x26 pixels large
       (when (and (integerp treemacs--icon-size)
                  (s-ends-with? "root.png" ,file-path))
         (treemacs--size-adjust width height))
       (if (and (integerp treemacs--icon-size) (image-type-available-p 'imagemagick))
           (create-image ,file-path 'imagemagick nil :ascent 'center :width width :height height)
         (create-image ,file-path 'png nil :ascent 'center))))))
```

It is used inside an `eval-when-compile` block to cut down on load time (though that'll be dropped in the next version to make the code  a lot simpler and to make room for icon themes). The macro to set up a single icon for some extensions will expand into this:

```Elisp
(defvar treemacs-icon-yaml nil)

(setq treemacs-icon-yaml
      (eval-when-compile
        (if
            (treemacs--is-image-creation-impossible\?)
            treemacs-icon-fallback-text
          (defvar treemacs--icon-size nil)
          (let* ((image-unselected (treemacs--create-image (f-join treemacs-dir "icons/" "yaml.png")))
                 (image-selected (treemacs--create-image (f-join treemacs-dir "icons/" "yaml.png"))))
            (treemacs--set-img-property image-selected :background treemacs--selected-icon-background)
            (treemacs--set-img-property image-unselected :background treemacs--not-selected-icon-background)
            (concat
             (propertize " " 'display image-unselected 'img-selected image-selected 'img-unselected image-unselected)
             " ")))))
(push treemacs-icon-yaml treemacs--created-icons)
(--each '("yml" "yaml") (ht-set! treemacs-icons-hash it treemacs-icon-yaml))
```

So my guess would be to look at how Remacs' internals deal with png and imagemagick images. You should have a proper test case by just calling `treemacs--create-image` on any image.

**Comment by ngortheone** [comment]
I guess this explains it.
> Icon creation comes down to calling into create-image with either a png or imagemagick type, preferring the latter since it makes the icons resizable.

```lisp
(format "%s"(treemacs--create-image "~/img/we-are-from-tech-support-weare-hereto-delete-your-cookies.png"))
```

Emacs: 
```lisp
(image :type imagemagick :file ~/img/we-are-from-tech-support-weare-hereto-delete-your-cookies.png :scale 2.3146341463414632 :ascent center :width 22 :height 22)
```

Remacs:
```lisp
-#+RESULTS:
: (image :type png :file ~/img/we-are-from-tech-support-weare-hereto-delete-your-cookies.png :scale 2.321951219512195 :ascent center)
```

```
( format "%s"   (image-type-available-p 'imagemagick))
```
Gives `t` on Emacs and `nil` on Remacs

![Tech Support](https://pics.me.me/we-are-from-tech-support-weare-here-to-delete-your-41473465.png)

**Comment by ngortheone** [comment]
Is there a way to control icon size without imagemagic?

**Comment by Alexander-Miller** [comment]
> Is there a way to control icon size without imagemagic?

No idea. Then again I don't know much more about Emacs' image handling capabilities than these calls to `create-image` that I implemented ages ago. Even the imagemagick resizing came with a PR. I'll do some testing tomorrow.

It's also quite strange that those icons are so small for you. Are you running a very large resolution? It doesn't really look like the 22x22 px default.

**Comment by ngortheone** [comment]
Yes, my laptop is 15 inch and has 4k resolution

**Comment by Compro-Prasad** [comment]
Emacs 27.0.50 now doesn't include imagemagik by default for security reasons. So, its better to only use png which currently has no issues with Emacs(both current and dev versions).

**Comment by ngortheone** [comment]
There must be something else going on

I have just installed emacs 27.0.50 and it does not have imagemagic support. But icon resizing still works
```
#+Begin_Src emacs-lisp
( format "%s"   (image-type-available-p 'imagemagick))
#+END_SRC

#+RESULTS:
: nil
```
And `create-image` gives me the same thing as Remacs
```
#+RESULTS:
: (image :type png :file ~/img/we-are-from-tech-support-weare-hereto-delete-your-cookies.png :scale 2.3046153846153845 :ascent center)
```

**Comment by ngortheone** [comment]
I did more digging. `treemacs--created-icons` looks exactly the same on emacs 27 and on remacs.
So it is not an image creation process (other images outside treemacs look fine)
And  `treemacs-resize-icons` successfully sets `:width` and `:height` properties to every icon. 

The problem is that none of that has visual effect.

**Comment by ngortheone** [comment]
Thanks for your help. I was able to figure out what is going on. Apparently 26.2 emacs without imagemagic has limted PNG support, which results in described behavior. 27.0.50 does not have this problem.
The confusion was added by the fact that Arch's emacs packages has statically linked imagemagic support, but remacs build did not.

**Comment by Alexander-Miller** [comment]
:+1:
