### ISSUE TITLE
Treemacs doesn't switch workspaces if a buffer is switched without treemacs active

### ISSUE THREAD

**Issue by howdoicomputer** [Alexander-Miller/treemacs#455]
I'm coming from Spacemacs so I'll use those bindings as an example.

Treemacs is fine with switching workspaces and focusing on an open file if:

1. Action: Open Treemacs with `SPC p t`
2. Action: Switch buffers to a file in a differing workspace using `SPC b b`
3. Result: Treemacs rebuilds its tree is in the correct workspace focused on the correct file.

However, if Treemacs is *closed* and I switch buffers to a different workspace and then toggle Treemacs on it doesn't know that I'm in a different workspace and focuses on the previous workspace.

I don't know if this should go into the Spacemacs repo for the Treemacs layer or if it should go here but it would be nice if Treemacs looked at the current focused buffer and switch to the right workspace.

**Comment by Compro-Prasad** [comment]
I use `SPC p t` for toggling treemacs and it automatically highlights the right file when I switch to that buffer. It doesn't do it when toggling though. It does it when I am using(in) that specific file buffer.

**Comment by howdoicomputer** [comment]
Yeah, more or less. It's annoying but not, like, super breaking my workflow or anything. I'll switch buffers to another file in another project directory but Treemacs will still be focused on the previous project directory when I open it.

I can fix that by opening Treemacs and re-opening the buffer but it's kind of janky.

**Comment by Compro-Prasad** [comment]
The point is that there might be many windows open. So, treemacs currently does't know which was the last buffer you used. There might be a way to access most recently used buffer(s) which treemacs can use to switch to that specific file in the tree.

**Comment by Alexander-Miller** [comment]
> Treemacs rebuilds its tree is in the correct workspace focused on the correct file.

Terminology: that's not a workspace, I think you mean a project. A workspace is a collection of projects (file trees). So far there's only one, but you'll be able to switch them soon.

> Treemacs currently doesn't know which was the last buffer you used.

Sure it does. It's whatever is the current buffer when treemacs is called to be opened again. So the fix is quite simple. I'll drop a patch tomorrow.

**Comment by Alexander-Miller** [comment]
> There might be a way to access most recently used buffer(s)

There is a way to at least get the most recently used window. See also `treemacs-visit-node-in-most-recently-used-window`.

**Comment by howdoicomputer** [comment]
Wow, that was *really* fast. Sorry for mixing up my terminology! That's awesome! Super appreciated.
