### ISSUE TITLE
treemacs-icons-dired custom icons

### ISSUE THREAD

**Issue by emacsomancer** [Alexander-Miller/treemacs#457]
`treemacs-icons-dired` doesn't seem to inherit custom specifications for icons like:

```
(with-eval-after-load "treemacs"
  (defvar treemacs-custom-tex-icon (all-the-icons-icon-for-file "name.tex"))
  (treemacs-define-custom-icon treemacs-custom-tex-icon "tex"))
```

(Which works in the normal treemacs mode, but doesn't seem to be inherited by in the dired icons mode.)

[Still a bit surprised .tex and .rkt aren't supported icons by default.]

**Comment by emacsomancer** [comment]
Nevermind, it looks like the non-stable version does behave as expected.

**Comment by Alexander-Miller** [comment]
> Nevermind, it looks like the non-stable version does behave as expected.

That'll become the next stable release in a couple of days.

> Still a bit surprised .tex and .rkt aren't supported icons by default.

Icon support is mostly based around availability of good - and properly licensed - icons. There's an issue for looking through vscode's icons somewhere, but that's mostly background noise until I'm done with more interesting and important stuff.
