### ISSUE TITLE
check File-Date information? in mini-buffer?

### ISSUE THREAD

**Issue by technician77** [Alexander-Miller/treemacs#459]
Is there any way to see the file date/time information?

I think the mini-buffer shows the full file path by default. Is there any way to change this to the file (last edited) date/time?

Let's assume I download an archive that contains files that were edited by multiple people and let's say they don't always use the same naming conventions. So I need the date to see which one is the newest. Example:
important-information.xlsx
important-information_2018_11_12.xlsx
important-informationV2.xlsx
Now imagine the "important-information.xlsx" is the newest. Yep, just because.

**Comment by Compro-Prasad** [comment]
You could instead use `dired` for that purpose.

**Comment by technician77** [comment]
Yeah, but if possible I would like to stay in treemacs to get that information. A customization that allows selection which file information is shown in the mini-buffer would be great. Or another idea would be to split the treemacs sidebar/buffer horizontally 3/4 1/4 and show the extended file information below if a customization is enabled.

**Comment by Alexander-Miller** [comment]
I will expand `treemacs-eldoc-display` to accept either a `simple` or a `detailed` value. In case of the letter the message will include similar info to what you'd see in dired: permissions, size, modification time and the absolute path.

**Comment by technician77** [comment]
Thanks, I'm looking forward to it.

**Comment by Compro-Prasad** [comment]
I was thinking if the eldoc could auto scroll horizontally? Or wrapping is also a good option.

**Comment by technician77** [comment]
Since I'm not a coder, I'm not really sure what is meant here exactly, but I don't think I would like to have file information to "scroll in" each time I switch a file. That would would be a time waster.

**Comment by Alexander-Miller** [comment]
No scrolling, if things get too long they'll get wrapped, just like the usual eldoc messages.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Compro-Prasad** [comment]
@Alexander-Miller I guess you should make stale bot to not close issues with a specific label (for example, `Not stale`).

**Comment by Alexander-Miller** [comment]
Took me a while, but `treemacs-eldoc-display` now supports a `detailed` option.

> I guess you should make stale bot to not close issues with a specific label (for example, Not stale).

The status quo is fine with me actually. A few things might get closed accidentally when I've too little time to check them all, but the bot's constant reminders do bring old issues to the top of my queue again, which is a good thing.
