### ISSUE TITLE
Problem with wanderlust

### ISSUE THREAD

**Issue by egh** [Alexander-Miller/treemacs#460]
When using with https://github.com/wanderlust/wanderlust, I get the following error when sending a message:

```
Debugger entered--Lisp error: (error "Attempt to delete main window of frame #<frame ema...")
  signal(error ("Attempt to delete main window of frame #<frame ema..."))
  error("Attempt to delete main window of frame %s" #<frame emacs@michel 0x562078d0d7c0>)
  delete-window()
  wl-draft-hide(#<buffer .drafts/1389>)
  wl-draft-normal-send-func(#<buffer .drafts/1389> t)
  wl-draft-send(t)
  wl-draft-send-and-exit()
  funcall-interactively(wl-draft-send-and-exit)
  call-interactively(wl-draft-send-and-exit nil nil)
  command-execute(wl-draft-send-and-exit)
```

It seems to boil down to the following code:
```
(or (one-window-p) (delete-window))
```

To be clear, I'm not sure if the problem here is with Wanderlust or treemacs.

**Comment by Alexander-Miller** [comment]
By default treemacs acts as a [side-window](https://www.gnu.org/software/emacs/manual/html_node/elisp/Side-Windows.html). I think side-windows are a fairly new feature, introduced with around Emacs25, and not widely used. You cannot delete the last non-side-window of a frame, but wanderlust does not take them into account when checking whether to delete the window you sent your mail from.

There's isn't anything that *I* can do about that. IMO you have 2 options:

1) Set `treemacs-display-in-side-window` to nil, but that might mean you'll end with treemacs as your only window after sending an email, which isn't supposed to happen either.

2) Try to get a change into wanderlust- it does seem to be actively developed. AFAICT it should be sufficient to add another check for `window-deletable-p` and call `bury-buffer` when that returns nil.

**Comment by egh** [comment]
Excellent, thank you very much for the helpful information! I will try to fix this in wanderlust. I wasn't aware of side windows and thought perhaps treemacs was doing a lot of magic.

**Comment by Alexander-Miller** [comment]
Your PR was merged, so I assume the issue if fixed now.

**Comment by egh** [comment]
Yes, thank you! And thanks for treemacs. I find it really useful.
