### ISSUE TITLE
incorrectly getting error "Could not add watch for file: No space left on device"

### ISSUE THREAD

**Issue by emacsomancer** [Alexander-Miller/treemacs#462]
On my one machine (with plenty of storage space), when I open certain treemacs projects, I get an error:
`treemacs--expand-root-node: Could not add watch for file: No space left on device,` and then the directory path.

**Comment by Alexander-Miller** [comment]
Does the solution from the ENOSPC FAQ entry help?

**Comment by emacsomancer** [comment]
Doing the following seems to have resolved it:
`echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p`
