### ISSUE TITLE
New way to configure the appearance?

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#465]
Sorry, but didn't managed to find any information on how to configure the appearance of treeemacs after the last update, that includes themes. Previously, I was using modified configuration inspired by emacs-doom-themes, that looked like this (on the left):

![image](https://user-images.githubusercontent.com/19470159/60107943-706f8980-9770-11e9-991a-6c47630474ef.png)

But after the update it looks like on the right.

Previously I was using pretty huge config, that looked like this:

```emacs-lisp
  (eval-after-load 'treemacs
    (lambda ()
      "Adjust DOOM Themes settings for Treemacs.

This lambda function sets root icon to be regular folder icon,
and adds 'chevron' icons to directories in order to display
opened and closed states.  Also it indents all file icons with
two spaces to match new directory icon indentation."
      (unless (require 'all-the-icons nil t)
        (error "`all-the-icons' isn't installed"))
      (let ((all-the-icons-default-adjust 0))
        (setq treemacs-icons-hash (make-hash-table :size 200 :test #'equal)
              treemacs-icon-fallback (concat "  " (all-the-icons-octicon "file-code" :v-adjust 0) " ")
              treemacs-icon-text treemacs-icon-fallback
              treemacs-icon-root
              (concat " " (all-the-icons-octicon
                           "file-directory"
                           :v-adjust 0
                           :face '(:inherit font-lock-doc-face :slant normal))
                      " ")
              treemacs-icon-open
              (concat (all-the-icons-octicon
                       "chevron-down"
                       :height 0.75
                       :face '(:inherit font-lock-doc-face :slant normal))
                      " "
                      (all-the-icons-octicon
                       "file-directory"
                       :v-adjust 0
                       :face '(:inherit font-lock-doc-face :slant normal))
                      " ")
              treemacs-icon-closed
              (concat (all-the-icons-octicon
                       "chevron-right"
                       :height 0.9
                       :face '(:inherit font-lock-doc-face :slant normal))
                      " "
                      (all-the-icons-octicon
                       "file-directory"
                       :v-adjust 0
                       :face '(:inherit font-lock-doc-face :slant normal))
                      " ")))
      (treemacs-define-custom-icon (concat "  " (all-the-icons-octicon "file-media" :v-adjust 0))
                                   "png" "jpg" "jpeg" "gif" "ico" "tif" "tiff" "svg" "bmp"
                                   "psd" "ai" "eps" "indd" "mov" "avi" "mp4" "webm" "mkv"
                                   "wav" "mp3" "ogg" "midi")
      (treemacs-define-custom-icon (concat "  " (all-the-icons-octicon "file-text" :v-adjust 0))
                                   "md" "markdown" "rst" "log" "org" "txt"
                                   "CONTRIBUTE" "LICENSE" "README" "CHANGELOG")
      (treemacs-define-custom-icon (concat "  " (all-the-icons-octicon "file-code" :v-adjust 0))
                                   "yaml" "yml" "json" "xml" "toml" "cson" "ini"
                                   "tpl" "erb" "mustache" "twig" "ejs" "mk" "haml" "pug" "jade")))
```

And it seems that it doesn't do anything right now. Except that `.org` extension file is using the `fallback` icon that is defined here.

There's an issue opened on the doom themes side: https://github.com/hlissner/emacs-doom-themes/issues/288 but I wanted to ask here as well what's the correct or recommended way to configure treemacs to make it look like before the update?

**Comment by Alexander-Miller** [comment]
Ahh crap, I pushed too early. I wanted to get the new theme support out of the door quickly to get feedback, but forgot all about stuff like doom. 

At least there's some good news: the new api is meant to make modifications like yours a lot easier -  project like doom could go as far as to publish its treemacs theme on melpa. Now that api does not exist just yet, I am currently finishing up and documenting workspaces, but I'll make it a priority now.

**Comment by andreyorst** [comment]
> the new api is meant to make modifications like yours a lot easier - project like doom could go as far as to publish its treemacs theme on melpa

That's great, but I also would like to know how I can make such theme myself, since I don't quite like how doom looks OOTB and ended up changing bits of its config, like shown in the code above. But giving your next statement:

> Now that api does not exist just yet

I understand this can't be done right now, right?

**Comment by Alexander-Miller** [comment]
What you can do now is what treemacs needs on its own: creating a theme based on png icons. I'll be adding two more options: using non-file icons (stuff like all-the-icons) and modifying an existing theme.

**Comment by andreyorst** [comment]
@Alexander-Miller I've seen what you've posted in the doom-themes issue, and updated that configuration a bit:

```emacs-lisp
(treemacs-create-theme "Atom"
  :config
  (progn
    (treemacs-create-icon
     :icon (concat " " (all-the-icons-octicon
                        "file-directory"
                        :v-adjust 0
                        :face '(:inherit font-lock-doc-face :slant normal))
                   " ")
     :extensions (root))
    (treemacs-create-icon
     :file nil
     :icon (concat (all-the-icons-octicon
                    "chevron-down"
                    :height 0.75
                    :v-adjust 0.1
                    :face '(:inherit font-lock-doc-face :slant normal))
                   "\t"
                   (all-the-icons-octicon
                    "file-directory"
                    :v-adjust 0
                    :face '(:inherit font-lock-doc-face :slant normal))
                   " ")
     :extensions (dir-closed))
    (treemacs-create-icon
     :file nil
     :icon (concat (all-the-icons-octicon
                    "chevron-right"
                    :height 0.75
                    :v-adjust 0.1
                    :face '(:inherit font-lock-doc-face :slant normal))
                   "\t"
                   (all-the-icons-octicon
                    "file-directory"
                    :v-adjust 0
                    :face '(:inherit font-lock-doc-face :slant normal))
                   " ")
     :extensions (dir-open))
    (treemacs-create-icon
     :file nil
     :icon (concat "  " (all-the-icons-octicon "file-media" :v-adjust 0) " ")
     :extensions ("png" "jpg" "jpeg" "gif" "ico" "tif" "tiff" "svg" "bmp"
                  "psd" "ai" "eps" "indd" "mov" "avi" "mp4" "webm" "mkv"
                  "wav" "mp3" "ogg" "midi"))
    (treemacs-create-icon
     :file nil
     :icon (concat "  " (all-the-icons-octicon "file-text" :v-adjust 0) " ")
     :extensions ("md" "markdown" "rst" "log" "org" "txt"
                  "CONTRIBUTE" "LICENSE" "README" "CHANGELOG"))
    (treemacs-create-icon
     :file nil
     :icon (concat "  " (all-the-icons-octicon "file-code" :v-adjust 0) " ")
     :extensions ("yaml" "yml" "json" "xml" "toml" "cson" "ini"
                  "tpl" "erb" "mustache" "twig" "ejs" "mk" "haml" "pug" "jade"))
    (treemacs-create-icon
     :file nil
     :icon (concat "  " (all-the-icons-octicon "file-code" :v-adjust 0) " ")
     :extensions (fallback))))

(treemacs-load-theme "Atom")
```

And now it looks amazing again:

![image](https://user-images.githubusercontent.com/19470159/60173474-77050c00-9817-11e9-9734-8a0a82ef4ac4.png)

Thanks for that so much! :+1: 

But on compiling my init.el I get these warnings:

```
Compiling file /home/andreyorst/.emacs.d/init.el at Wed Jun 26 13:32:46 2019
init.el:147:2:Warning: Unused lexical variable ‘icon-path’
init.el:147:2:Warning: Unused lexical variable ‘icon-path’
init.el:147:2:Warning: Unused lexical variable ‘icon-path’
init.el:147:2:Warning: Unused lexical variable ‘icon-path’
init.el:147:2:Warning: Unused lexical variable ‘icon-path’
init.el:147:2:Warning: Unused lexical variable ‘icon-path’
init.el:147:2:Warning: Unused lexical variable ‘icon-path’
```

Which points to this line in my init.el:

```
(use-package doom-themes
```

That's where I create the theme for treemacs. Inside doom-themes `use-package` macro. Am I missing something here?

**Comment by Alexander-Miller** [comment]
> Am I missing something here?

No, that variable is simply unused because there is no path where your icons are stored. I'll push a patch to fix that warning later today.

Btw you don't need the file=nil part, it should work just as well without it.

**Comment by andreyorst** [comment]
> Btw you don't need the file=nil part, it should work just as well without it.

I've thought that it might be needed because it expects paths, and `nil` will be used in that `icon-path`.

**Comment by andreyorst** [comment]
I guess I can close this now, since the way to configure treemacs was explained. If I'll encounter some problems I'll open separate issues for those. Thanks again

**Comment by andreyorst** [comment]
> No, that variable is simply unused because there is no path where your icons are stored. I'll push a patch to fix that warning later today.

This warning is still a thing

**Comment by Alexander-Miller** [comment]
How about after https://github.com/Alexander-Miller/treemacs/commit/934ad105bb7fb11f4e43a996f7f13f231dfe6454?

**Comment by andreyorst** [comment]
Seems to be fixed. Thanks!)
