### ISSUE TITLE
Themes discussion & feedback

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#470]

**Comment by Alexander-Miller** [comment]
@yyoncho Have a look whether you can use the new `treemacs-get-icon-value` function to get the icon values you need. It should work for all file extensions and other icons. For the latter you need to use a symbol as the extension argument that is the `X` in `treemacs-icon-X`, for example `(treemacs-get-icon-value 'dir-open)`.

**Comment by yyoncho** [comment]
Thank you, I will take a look. One question: how do we handle the case when a component defines a theme that has no equivalent in treemacs core? What do you think about defaulting to "Default" theme?

**Comment by yyoncho** [comment]
And one more thing - what is the expected way to handle 2 icon nodes? (E. g. indicator for node state + the node icon itself). It was discussed in the past but I am not sure what is the current state

**Comment by yyoncho** [comment]
It seems like treeemacs-modify-theme cannot use icons that are not under the original directory. IMO this diminishes the value of this method.

**Comment by Alexander-Miller** [comment]
> how do we handle the case when a component defines a theme that has no equivalent in treemacs core?

That's the next big question that needs answering. The current plan is to come up with an api for new icons that will make them propagate through all themes that don't have them already. So you if for example load a vscode-icons theme and then define a series of icons for dap-mode they all get added to the default and other themes as well. It may not be consistent, but it's better than a void-variable error or ugly default placeholder.

> It seems like treeemacs-modify-theme cannot use icons that are not under the original directory.

Adding an argument to temporarily override the icon directory should be easy enough.

**Comment by Alexander-Miller** [comment]
https://github.com/Alexander-Miller/treemacs/issues/475
https://github.com/Alexander-Miller/treemacs/issues/476

**Comment by Alexander-Miller** [comment]
> And one more thing - what is the expected way to handle 2 icon nodes?

Nothing's changed so far - unless you're expecting a complexity explosion I'd rather combine things into 1 icon.

**Comment by Alexander-Miller** [comment]
First steps: when creating a theme new icons will now be propagated to other themes if they don't have a mapping for the given extension already. For example if you run this:
```
(treemacs-create-theme "Test-Theme"
  :config
  (progn
    (treemacs-create-icon :icon "+ " :extensions ("FOO" "BAR"))))
```
you'll find the new icons also in the default theme.

**Comment by Alexander-Miller** [comment]
Icon propagation and custom icon directory are in now. Let me know how it works out.

I'll document the whole thing and then start working on more granular update mechanisms - I expect that this will also provide me with many of the tools necessary to get error display going.

**Comment by Alexander-Miller** [comment]
Added documentation for theme api: https://github.com/Alexander-Miller/treemacs#theme-support

Let me know if anything is missing.

**Comment by seagle0128** [comment]
I realized #504 should be listed here.

**Comment by Alexander-Miller** [comment]
Looks like the discussion is quite finished.
