### ISSUE TITLE
treemacs-persist-file does not work with non-default value

### ISSUE THREAD

**Issue by rangilin** [Alexander-Miller/treemacs#477]
Recently I experience similar issue in #257 and cannot restore my workspace after restarting Emacs. However, it will work if I use default `treemacs-persist-file`.

Here is an `init.el` file that I use to reproduce the issue.

```emacs-lisp
(require 'package)

(add-to-list 'package-archives (cons "melpa"  "https://melpa.org/packages/"))

(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile (require 'use-package))


(use-package treemacs
  :ensure t
  :config
  (setq treemacs-persist-file (expand-file-name "my-treemacs-persist" user-emacs-directory)))
```

### Steps to  reproduce

After Emacs loaded `init.el` completely

1.  `M-x treemacs` to toggle Treemacs
2.  Add any project to the default workspace. (After this step, workspace data is in the custom persist file.)
3. Restart Emacs.
4. `M-x treemacs` again

The workspace will be empty after step 4.

### Emacs Version

```
GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-04-13
```

**Comment by Alexander-Miller** [comment]
> Here is an init.el file that I use to reproduce the issue.

Thanks for that, I think I finally figured out why this is not working. The restore process is probably running too. I'll try pushing it back somewhere more appropriate.

**Comment by Alexander-Miller** [comment]
Should be fixed now.

**Comment by rangilin** [comment]
I can confirm it is now fixed, thank you for your prompt action.

However, it also now leave an empty `.cache` directory in the `user-emacs-directory`. I don't recall seeing this behavior before, could it be caused by this change ? This behavior can also be reproduced by the same step.

**Comment by Alexander-Miller** [comment]
Let's have a look.

**Comment by Alexander-Miller** [comment]
> However, it also now leave an empty .cache directory in the user-emacs-directory

That's because it was also ensuring the existence of the base directory of `treemacs-last-error-persist-file`. That one only exists for debugging purposes, so I made sure the directory is only created when the file is actually needed.
