### ISSUE TITLE
Treemacs switch between files

### ISSUE THREAD

**Issue by lromor** [Alexander-Miller/treemacs#478]
Hi, 

sorry for the maybe (silly) question, is there a way to move between the files shown in treemacs
in the current buffer without going back and forth between treemacs and current buffer windows?
Something like move up and down in the current folder?

Thank you,

-l

**Comment by Compro-Prasad** [comment]
Is it similar to single left click in Sublime Text which shows the file temporarily?

**Comment by Alexander-Miller** [comment]
- `treemacs-peek` (P) will let you temporarily look at files,a nd close them again if you move away
 - Calling any visit-node command with a prefix argument will open the file, but you'll stay in treemacs

Does that cover your case?

**Comment by lromor** [comment]
I was thinking as something more like:

https://emacs.stackexchange.com/questions/12153/does-some-command-exist-which-goes-to-the-next-file-of-the-current-directory

So the idea is that instead of switching between buffers as for instance with `C-x left/right`, one could
switch between files in the directory (and not the opened buffers) with for instance `C-x down/up`.

Without the need of searching for them, or manually go to the treemacs window and use the arrows to select them. 
Not sure if it's the right place to ask for this feature. It seemed related to treemacs but maybe it's not.
Maybe is more an emacs question.
What do you think?

**Comment by Alexander-Miller** [comment]
Not really a thing for treemacs, but if the answers in the link don't help I can create something that'd align with the way treemacs shows your files.

**Comment by dato** [comment]
I would find this very useful. In fact, there are two things I would find terribly useful (and they're kind of orthogonal one another):

- first, a kind of “sticky” peek state, in which navigation in the treemacs buffer keeps on reusing the preview window to show files (without having to press `P` again, that is)

- second, and perhaps more important, a way to “upgrade” from peek state to edit state. At the moment, if I try to visit a file I'm previewing (with, say, `oo`), the window is closed, and the buffer _and position_ reverted to the previously edited buffer. It'd be great being able to press, say, `M-RET` or `RET` or `TAB` or even plain `oo` and start visiting/editing the peek'd file.

  (Perhaps there's an easy way to achieve this, and I haven't been able to figure out.)

Do either of these make sense to you? Would you like me to open a new, separate issue about them?

**Comment by Alexander-Miller** [comment]
>  Would you like me to open a new, separate issue about them?

Please do.
