### ISSUE TITLE
Renaming a project accepts an empty string

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#479]
### Description :octocat:

Renaming a project accepts an empty string, which breaks multiple things.

#### Reproduction guide :beetle:

- Add a project `C-c C-p a`
- Rename the project `C-c C-p r`
- At the `New name:` prompt, erase the current name and press `RET`

*Observed behaviour:* :eyes: :broken_heart:
- The `*Messages*` buffer shows:
>[Treemacs] Renamed project Temp to .

Editing the workspace (`C-c C-w e`) looks like this:
```
#+TITLE: Edit Treemacs Workspaces & Projects
# Call ~treemacs-finish-edit~ or press ~C-c C-c~ when done.
# [[https://github.com/Alexander-Miller/treemacs#conveniently-editing-your-projects-and-workspaces][Click here for detailed documentation.]]
# To cancel you can simple kill this buffer.

* Default Workspace
** 
 - path :: c:/Users/username/Temp
```

*Expected behaviour:* :heart: :smile:

There should probably be a warning that the project name can't be empty.

#### Notes :notebook:

- Trying to rename the empty string project shows the message:
>[Treemacs] There is no project here.

- Adding a new project when there's a project with an empty name adds the new project to the left of the empty string project:

![adding new project to empty string project](https://user-images.githubusercontent.com/13420573/60795997-f5917000-a16c-11e9-8850-7abe206f1b48.png)

The workspace looks as expected:
```
#+TITLE: Edit Treemacs Workspaces & Projects
# Call ~treemacs-finish-edit~ or press ~C-c C-c~ when done.
# [[https://github.com/Alexander-Miller/treemacs#conveniently-editing-your-projects-and-workspaces][Click here for detailed documentation.]]
# To cancel you can simple kill this buffer.

* Default Workspace
** 
 - path :: c:/Users/username/Temp
** .emacs.d
 - path :: c:/Users/username/.emacs.d
```

- Restarting Emacs with an empty string project in the workspace (with or without other named projects) seems to clear the workspace, because Treemacs is empty and the startup prompt asks for a new project root.

#### System Info :computer:

[Treemacs] v2.6-2019.07.08 @ 26.2
GNU Emacs 26.2 (build 1, x86_64-w64-mingw32) of 2019-04-13
Windows 10 Version 1803

**Comment by Alexander-Miller** [comment]
Not yet.

**Comment by Alexander-Miller** [comment]
Ok, now it should be fixed properly.

**Comment by duianto** [comment]
Both the empty and whitespace strings are blocked.
>[Treemacs] '' is an invalid name.
[Treemacs] ' ' is an invalid name.

And a two line string is also blocked:
>[Treemacs] 'a
b' is an invalid name.

That kind of newline can be entered at the `New name:` prompt like this:
- type `a`
- press `M-:` to show the `Eval:` prompt
- type `(newline)` and press `RET`
- type `b`
- press `RET`

Or by copying two lines from the scratch buffer:
```
a
b
```
and pasting `C-y` in the minibuffer.

#### Possible issue?
The string `"a\nb"` from the test:
```
(it "detects a string with newlines"
    (expect (treemacs--is-name-invalid? "a\nb") :to-be t)))
```
is accepted with `\n` at the start, middle or end of the project name.

Is there a chance that it might be interpreted as a newline and cause issues in a future (or maybe a current) feature that interacts with the project name?

**Comment by Alexander-Miller** [comment]
> The string "a\nb" from the test: is accepted with \n at the start, middle or end of the project name.

You sure? For me it looks like this:

> [Treemacs] '
> b' is an invalid name.

**Comment by duianto** [comment]
After (re)starting Spacemacs.
Open Treemacs `SPC f t`
The `Project root:` prompt shows the path: `c:/Users/username/.emacs.d/` with the `.ci` directory selected.
I want to add `.emacs.d` as the root, therefore I move to the parent directory with `C-h`.
Now `.emacs.d` is selected, and `RET` confirms it.
The `Project Name: .emacs.d` prompt appears.
I move the cursor to the beginning of the line `C-a` and kill the text after the cursor `C-k`.
Type: `a\nb`
Press `RET`

![emacs_2019-07-15_23-02-32](https://user-images.githubusercontent.com/13420573/61249085-ba86d200-a754-11e9-925c-eb1a315eb74a.png)

There was no message in the minibuffer or messages buffer that the project was added. (see below for a possible reason).

`C-c C-w e` (`treemacs-edit-workspaces`) shows:
```org
#+TITLE: Edit Treemacs Workspaces & Projects
# Call ~treemacs-finish-edit~ or press ~C-c C-c~ when done.
# [[https://github.com/Alexander-Miller/treemacs#conveniently-editing-your-projects-and-workspaces][Click here for detailed documentation.]]
# To cancel you can simply kill this buffer.

* Default Workspace
** a\nb
 - path :: c:/Users/username/.emacs.d
```

Removing the project `C-c C-p d`, shows the result in the minibuffer/messages buffer:
>[Treemacs] Removed project a\nb from the workspace.

### Missing minibuffer/messages buffer added project message

There was no project added <name> message in the minibuffer or in the messages buffer.

#### I think I found the reason.
There is a difference between the:
- Automatic add project prompt that appears when Treemacs is opened after a Spacemacs restart, and there is no previously defined projects.
- And the add project prompt when it's called with the key binding `C-c C-p a`.

The automatic prompt doesn't show a project added message.
But the key binding prompt does.
>[Treemacs] Added project .emacs.d to the workspace.

The automatic prompt asks for the project name, 
The add project key binding doesn't.

Renaming a project with the rename key binding `C-c C-p r` to `a\nb` shows:
>[Treemacs] Renamed project .emacs.d to a\nb.

I have a separate issue open about sine differences between the automatic and the key binding `C-c C-p a` add project prompts.

Added project message missing from automatic prompt #340

I'll try to reproduce the `a\nb` name with `spacemacs-base` and without Spacemacs to see if it only occurs with the main Spacemacs distribution.

**Comment by duianto** [comment]
I retested this and the project can still be (re)named with the characters: `a\nb`
>[Treemacs] Renamed project .emacs.d to a\nb.

It was tested with `[Treemacs] v2.6-2019.09.17 @ 26.3` in both Ubuntu and Windows on the latest Spacemacs develop branch with updated packages.

And in Windows without Spacemacs, just Treemacs installed.

It is however blocked when trying to rename it to:
```
a
b
```
Which can be typed like this, when renaming an existing project:
- `a`
- `M-j`
- `b`

>[Treemacs] 'a
b' is an invalid name.

If it's acceptable to use the characters `a\nb` as the project name, then this thread can remain closed. Otherwise this issue probably should be reopened until it's fixed, so that it isn't forgotten.

**Comment by Alexander-Miller** [comment]
Ah, I think I misunderstood what you had meant here. Basically yes, `a\nb` is an acceptable name. I had tested how it's treated by treemacs and the `\n` was always seen as just that, a literal backslash-n, and was saved and loaded as such without any problems. So as far as I can see the current state is fine as it is.
