### ISSUE TITLE
Follow mode doesn't always work

### ISSUE THREAD

**Issue by ambihelical** [Alexander-Miller/treemacs#48]
I have one project where it works, another where it doesn't.  The only difference I can see is that the project where it does not work, there are collapsed directories in the ancestry of the files which I'm switching buffers on.  Let me know if you need any more information.

**Comment by Alexander-Miller** [comment]
Shouldn't need more information, I think I've fixed it already. 
Let's try something new - I've never had need to create or apply git patches, but now's a good opportunity. Here's a patch that worked in my own testing, can you apply it and see if it works for you as well?
```

---
 treemacs-impl.el | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/treemacs-impl.el b/treemacs-impl.el
index c434972..c7ec692 100644
--- a/treemacs-impl.el
+++ b/treemacs-impl.el
@@ -651,7 +651,9 @@ Callers must make sure to save match data"
                 (search-forward filename nil t))
       (beginning-of-line)
       (let ((btn (next-button (point) t)))
-        (if (s-equals? abs-path (button-get btn 'abs-path))
+        (if (or (s-equals? abs-path (button-get btn 'abs-path))
+                (-when-let (parent-path (button-get btn 'parent-path))
+                  (treemacs--is-path-in-dir? abs-path parent-path)))
             (progn (treemacs--evade-image)
                    (setq keep-looking nil
                          ret btn))
--
2.14.1
```

**Comment by ambihelical** [comment]
I'd have been ok with a branch, as I already have treemacs repo setup to load, but the patch seems to work for this problem.  The only lingering problem I'm seeing follow related is that switching perspectives requires that I rerun treemacs-projectile to get treemacs to show the right file.   I have a feeling this is a separate problem though.

**Comment by Alexander-Miller** [comment]
> I'd have been ok with a branch, as I already have treemacs repo setup to load, but the patch seems to work for this problem.

Just something I wanted to try out once. The change is pushed to master now,

> switching perspectives requires that I rerun treemacs-projectile to get treemacs to show the right file.

I've given it a quick try now, and calling persp-next selects the correct file, given that both perspectives' files are inside the directory treemacs shows. If one perspective shows a buffer that's not in treemacs it looks like the wrong file is selected on switch, and selecting the treemacs window corrects that. I think persp is saving window-point for every perspective, so 2 perspectives showing the same treemacs window can have 2 different lines selected in treemacs, but switching a perspective does not always correctly update window-point in treemacs, or at least the hl-line part.

My description is awfully convoluted, but if this sounds like your problem, I should have a solution. Try this:
```
(defun treemacs--reset-window-point ()
  (-when-let (w (treemacs--is-visible?))
    (with-selected-window w
      (hl-line-mode -1)
      (hl-line-mode t))))
(add-hook 'window-configuration-change-hook #'treemacs--reset-window-point)
```

**Comment by ambihelical** [comment]
That doesn't seem to help any.  It looks like treemacs is not changing the root on switching perspectives, it's not just a matter of selecting the right line--if I understand your description correctly, which I'm not sure I am.

**Comment by Alexander-Miller** [comment]
> it's not just a matter of selecting the right line--if I understand your description correctly

You do understand correctly. Unfortunately what you want is not quite supported. Follow-mode only follows files within the same root. 
Is this an important feature for you to have? The necessary changes would take a while, and I think it's a problem better solved by my current todo list anyway: first make treemacs frame-local, then introduce the idea of workspaces, so that instead of directly showing a part of the file system, you'll import different projects, as in eclipse.

**Comment by ambihelical** [comment]
It'd be a nice thing to have, but not that important, I can get around it by running treemacs-projectile again.

**Comment by jeregrine** [comment]
I am also having this issue. New install of spacemacs develop using macosx emacs. 

I setup the treemacs layer. When I change files in a project nothing changes in treemacs.

**Comment by Alexander-Miller** [comment]
Frame locality has been around for a while now, and work on multiple roots is just beginning.
I'll be closing this then.
