### ISSUE TITLE
Option to disable icon?

### ISSUE THREAD

**Issue by ianpan870102** [Alexander-Miller/treemacs#482]
As much as I love treemacs and appreciate all the work that's put in, I like a minimal emacs look and would love to have the option to replace the big bright icons with subtle arrows are triangular shapes.

Has it been considered?

**Comment by ianpan870102** [comment]
Nevermind, I found the option in the README!

**Comment by Alexander-Miller** [comment]
Don't know which option you mean, but you can try either setting `treemacs-no-png-images` to t or using another theme like doom: https://github.com/hlissner/emacs-doom-themes/blob/master/doom-themes-ext-treemacs.el
