### ISSUE TITLE
Using proportional fonts?

### ISSUE THREAD

**Issue by ianpan870102** [Alexander-Miller/treemacs#486]
I'd love to set Treemacs font to something like Helvetica Neue, I've tried something like:
`(set-face-attribute 'treemacs-directory-face nil :family "Helvetica Neue")` but it takes no effect. How should I achieve this?

**Comment by Alexander-Miller** [comment]
https://imgur.com/a/I0rzk3V
Works for me, so I guess you should try another font.

**Comment by ianpan870102** [comment]
I see, turns out I have the git integration turned on and the fonts are controlled by another property now. That said, I could potentially achieve having all the fonts in Treemacs be proportional by individually setting `treemacs-directory-face`, `treemacs-directory-collapsed-face`, `treemacs-file-face`, `treemacs-root-face`, and 20 others etc. But is there a master variable that controls them all?, something like: `treemacs-default-face`?

**Comment by Alexander-Miller** [comment]
Nope, no default. Treemacs' faces inherit directly from your syntax highlighting colors, so they always fit in with the rest of your theme. I don't think adding more inheritance is a good idea, or even if it's possible at all.

You'll have to copy a few lines, or work through them on a loop.

**Comment by ianpan870102** [comment]
For others looking for the answer, here's what I have now in my config (modified from doom-themes-treemacs-config):

```
    (dolist (face '(treemacs-root-face
                    treemacs-git-unmodified-face
                    treemacs-git-modified-face
                    treemacs-git-renamed-face
                    treemacs-git-ignored-face
                    treemacs-git-untracked-face
                    treemacs-git-added-face
                    treemacs-git-conflict-face
                    treemacs-directory-face
                    treemacs-directory-collapsed-face
                    treemacs-file-face
                    treemacs-tags-face))
      (set-face-attribute face nil :family "San Francisco" :height 140))

```
