### ISSUE TITLE
Project-oriented Usage

### ISSUE THREAD

**Issue by dustinlacewell** [Alexander-Miller/treemacs#489]
Treemacs is great, however I find the Workspaces metaphor to not be very useful. I already use Projectile, and it would be great when I use projectile to switch to a project, treemacs could simply show the contents of that project without having to constantly create new workspaces, or using a monolithic workspace with everything in it.

It'd be great if there was a "projectile-follow" mode or something.

**Comment by Compro-Prasad** [comment]
This will be great addition but I don't think it will be easy to follow specific projects as treemacs is built around the workspace model and I don't think it supports narrowing to a specific project automatically.

**Comment by Alexander-Miller** [comment]
I had the idea to implement something like this for a while now. 

The current plan is to have a special workspace that automatically syncs with your projectile projects. That should remove the need for any special narrow or follow implementations, from your POV it'll be like a normal workspace - with a few automatic project add/remove parts going on underneath - that you can switch to and away from whenever.

**Comment by Compro-Prasad** [comment]
@Alexander-Miller Narrowing is very useful as it will retain the contents of the buffer showing contents which are needed. If you try to implement without narrowing then following projects using projectile would trigger multiple deletions and creations which takes time AFAIK.

**Comment by nils-schween** [comment]
I don't know about the details, but I would like to say that I would love such a feature.
Thank you four considering it. 
Take my post as a support post for a further projectile integration.

Thanks for all your work,
Nils

**Comment by contrapunctus-1** [comment]
I have a related request - while I like Treemacs' modern looks (over, say, sr-speedbar), I too do not want to have anything to do with workspaces and projects. `treemacs-tag-follow-mode` helps, but all I want at this point is for Treemacs to automatically display the containing directory of the file displayed in the current _window._ I couldn't find a way to do this - does one exist? If not, can it be implemented? (`treemacs-follow-mode` does not seem to do what I describe.)

**Comment by Alexander-Miller** [comment]
> Is there a way to get Treemacs to do this? If not, can it be implemented?

No and yes. There is clearly demand for such a feature, so I'll move it to the top of my list.

**Comment by Alexander-Miller** [comment]
Survey time: 

I am implementing a minor mode that automatically switches to the current project after a short idle delay, like an automated `treemacs-display-current-project-exclusively`.

 - Is that the kind of feature you are looking for?
 - What's a good name for it? So far I have `treemacs-only-current-project-mode`. Would you be able to find that mode without asking the readme if you were looking for it on your own?

**Comment by dustinlacewell** [comment]
`treemacs-project-follow-mode` ? 

And yeah this feature would be very welcome. It will make grabbing treemacs and getting started with a useful workflow quite painless. Thanks for taking this on.

**Comment by Alexander-Miller** [comment]
> treemacs-project-follow-mode

Yeah, on 2nd thought this is probably the best name. If there's something else people tend to look for it can be added as an alias.

**Comment by Compro-Prasad** [comment]
`treemacs-show-current-project-only` should also be a good alias as it has multiple user keywords like `show`, `current`, `project` and `only`.

**Comment by Alexander-Miller** [comment]
Al right everyone, I have now pushed an *initial* version of `treemacs-project-follow-mode`. This is not a feature I will be using myself, which is why it is very important that I get your feedback. So please grab the latest version of treemacs and tell me about everything that is missing or broken.

Since the release is not yet official the only proper documentation is in the doc string of `treemacs-project-follow-mode`. Other than that there isn't anything else to configure. Just switch it on and go.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by frgomes** [comment]
@Alexander-Miller :: I suppose you are aware of this stuff below.

For the benefit of people landing here:

I was able to circumvent the difficulty by setting:

```lisp
(setq lsp-auto-guess-root nil)`
```

... as explained in detail at: https://github.com/hlissner/doom-emacs/issues/1928

In a nutshell:

Now, when I add a new project ``projectile`` does not try to guess the project root anymore and defaults to the directory being added, which is exactly what I always expected to happen or even... I would dare to say... it is always what everyone would always expected to happen.

To be transparent and completely honest about this issue: I do not understand in detail how Treemacs, LSP and Projectile work together. And I do not know what happens (or not happens!) if you do not have LSP as part of this equation. I haven't tested that. But I know that it works as expected when these three components are configure together. In case anyone is interested, the configuration suggested above is being experimented at https://github.com/frgomes/.emacs.d/tree/experimental

Long life to Treemacs! :-)

Thanks.

**Comment by daanturo** [comment]
`treemacs-project-follow-mode` eliminates the need for session persistence, can we automatically disable it when the former mode is enabled?

**Comment by Alexander-Miller** [comment]
> I do not understand in detail how Treemacs, LSP and Projectile work together.

The treemacs part is simple. Whenever treemacs needs to find your current project it tries calling the functions in `treemacs--find-user-project-functions` until one returns something (and the last one always will because `default-directory` is always set). Having treemacs-projectile loaded will put projectile-based lookup at the top of the list. So the order is projectile > project.el > default-directory.

As for lsp, I don't know what it does either.

> treemacs-project-follow-mode eliminates the need for session persistence, can we automatically disable it when the former mode is enabled?

You can set `treemacs-persist-file` to nil to turn it off. You'll need an up-to-date treemacs for that, I have pushed this change only a few days ago.

Is there anything still open w.r.t this issue? I've been busy the last few months, but now I've more time for treemacs again, so if you've any wishes or issues now is the time to ask.

**Comment by frgomes** [comment]
@Alexander-Miller : Thanks a lot for enlighten me on the internals of Treemacs.

To be honest with you, I do not fully understand the business around neither `treemacs-project-follow-mode` nor `treemacs-persist-file`. So, in this case, I don't know how to answer your question "Can we automatically disable it when the former mode is enabled?". But I can inform that I have all plugins automagically updated every week... and Treemacs is working just fine. So, I believe that your recent updates are not breaking anything on my side.

I think that this issue can be closed.

Maybe you just need to document how to circumvent the issue or maybe you decide to make Treemacs "help users avoid this issue without their explicit consent and knowledge", which is something I do not usually advocate... but I guess it would be justifiable in this case in particular. Maybe you've already did that... and I just don't understand exactly what you've done, despite your efforts to explain to me above.

Just for the sake of clarification and documentation:

I have a git repository which contains several projects under several subdirectories. These projects are completely independent from each other: Every subdirectory has its own `README`, its own `.gitignore` and its own build scripts, etc, etc. Everything is working just fine and the workflow is just normal and works as expected after I've added the setting below: 

    (setq lsp-auto-guess-root nil)`

I hope it helps.

**Comment by aquilacf** [comment]
@Alexander-Miller `treemacs-project-follow-mode` seems to be working fine apart of the error message 
```Error running timer ‘treemacs--apply-annotations-deferred’: (wrong-type-argument number-or-marker-p nil)```
every time I switch projects.

Also, just an observation, if `treemacs-persist-file` is nil treemacs will always ask for project root.

**Comment by Alexander-Miller** [comment]
@aquilacf I'm looking into it now.

**Comment by Alexander-Miller** [comment]
Pushed a patch, let me know if it works.

> Also, just an observation, if treemacs-persist-file is nil treemacs will always ask for project root.

Will take a look at this next.

**Comment by Alexander-Miller** [comment]
> > Also, just an observation, if treemacs-persist-file is nil treemacs will always ask for project root.
> 
> Will take a look at this next.

I've played around without a persist file and didn't see anything that looked wrong. Can you give  me a reproduction recipe?

**Comment by liushihao456** [comment]
`Error running timer ‘treemacs--apply-annotations-deferred’: (wrong-type-argument number-or-marker-p nil)` still occurs when switching buffers of different projects. My config is as below:

```
(with-eval-after-load 'treemacs
  (treemacs-follow-mode)
  (treemacs-project-follow-mode)
  (setq treemacs--project-follow-delay 0.1)
  (setq treemacs-file-follow-delay 0.1)
  (setq treemacs-project-follow-cleanup t)
  (setq treemacs-follow-after-init t)
  (setq treemacs-width 30)

  (defun my/treemacs-ignore-file-predicate (file _)
    (or (string= file ".gitignore")
        (string-suffix-p ".pyc" file)
        (string= file "__pycache__")
        (string-prefix-p ".cache" file)))
  (push #'my/treemacs-ignore-file-predicate treemacs-ignored-file-predicates))
```

Could you have a look? Thanks. :)

**Comment by Alexander-Miller** [comment]
> Error running timer ‘treemacs--apply-annotations-deferred’: (wrong-type-argument number-or-marker-p nil) still occurs when switching buffers of different projects.

I can't reproduce this, but I have made a few other rendering-related changes in the meantime. Try again with the latest version, maybe it'll help.

> What I expect is that when I open treemacs, it shows my current project. I thought treemacs-follow-after-init would achieve this but it doesn't.

`treemacs-follow-after-init` is only for files. 
This case was supposed to work already, but some of my performance improvements made things more complicated, so it didn't work as expected. That's also fixed now.

**Comment by liushihao456** [comment]
Thanks! Both issues disappear now! :D

**Comment by Alexander-Miller** [comment]
This is an old ticket that has seen a few different strands of conversation popup over time, so much that I always have to go a way back to look up what happened last. Which is why I think this ticket has served its purpose and I would like to close it now.

If you still have points that are unaddressed feel free to create new issues.
