### ISSUE TITLE
Indentation Error (treemacs-edit-workspaces)

### ISSUE THREAD

**Issue by ni-ko-o-kin** [Alexander-Miller/treemacs#495]
Hi,
first of all: awesome package!!

I'm using:
 - emacs 26.1
 - spacemacs dev-branch (0.300)
 - treemacs 2.6-2019.07.08

From the [documentation](https://github.com/Alexander-Miller/treemacs/blob/master/README.org#conveniently-editing-your-projects-and-workspaces) I thought there should be 3 spaces because it looks like it in the image and because it is a path declaration for the project and not the workspace. Is there a bug in the code or should the documentation be fixed?

does not work:
```
* workspace
** project <- Project name must be followed by path declaration
  - path :: /path/to/some/project
```
does not work either:
```
* workspace
** project <- Project name must be followed by path declaration
   - path :: /path/to/some/project
```

does work:
```
* workspace
** project
 - path :: /path/to/some/project         <-- one less space for indentation
```

**Comment by Alexander-Miller** [comment]
It's actually only 0 or 1 spaces (and the 1 is only permitted because I use some code that makes `" -"` look  like `" •"`). It only looks like there's a lot more indentation due to `org-ident-mode`. 

I'll add that detail to the docs tomorrow.

**Comment by Alexander-Miller** [comment]
Oops, so much for tomorrow :man_facepalming:.

It's up now.

**Comment by ambs** [comment]
Hi. The current documentation still not helping. I would suggest adding a pure ascii version.
I managed to understand what was going on looking only to this ticket.

BTW, if `.emacs.d/.cache` does not exist, it is not automatically created (unfortunately)
