### ISSUE TITLE
Turn off follow-mode "permanently" in Spacemacs

### ISSUE THREAD

**Issue by dmocek** [Alexander-Miller/treemacs#500]
I've set these in my dotspacemacs/user-config section of .spacemacs:

(setq treemacs-follow-mode nil)
(setq treemacs-tag-follow-mode nil)

but follow-mode remains on.  How do I disable it "permanently"?

**Comment by Alexander-Miller** [comment]
Set them how?

**Comment by Compro-Prasad** [comment]
> I've set these in my dotspacemacs/user-config section of .spacemacs, but follow-mode remains on.

What **these**?

**Comment by dmocek** [comment]
I've added the command I use to turn follow mode off to the original question.

**Comment by Alexander-Miller** [comment]
> (setq treemacs-follow-mode nil)

* That's not how you turn off a minor mode, any minor mode. You need to call it: `(treemacs-follow-mode -1)`.

 * Treemacs enables these modes automatically on load, your settings must come after that, so you must use `with-eval-after-load`.

 * You're on spacemacs, so there's some layer-owned variables you can disable instead. Check the configuration part of the layer documentation.

**Comment by dmocek** [comment]
I've found the "magic setup" to get this to work with Spacemacs v0.300.0 as of 9/18/2019.  This page: http://develop.spacemacs.org/layers/+filetree/treemacs/README.html states I should be able to set :

(treemacs :variables treemacs-use-follow-mode nil)

in the dotspacemacs-configuration-layers section and follow mode should be turned off, but it does not work by itself.  I'm not sure which version of Spacemacs this documentation is for, probably v0.200.  However, if I ALSO add:

(with-eval-after-load "treemacs" (treemacs-follow-mode -1))

in the dotspacemacs/user-config section, it works.

**Comment by Alexander-Miller** [comment]
> and follow mode should be turned off, but it does not work by itself.

That's a bug. Minor modes are enabled by default, so spacemacs should be disabling them https://github.com/syl20bnr/spacemacs/pull/12745 should fix that.

> I'm not sure which version of Spacemacs this documentation is for, probably v0.200. 

Must be for the develop branch, AFAIK treemacs is not yet in master.

**Comment by dmocek** [comment]
Yes, develop branch.
