### ISSUE TITLE
Switch between buffers & treemacs

### ISSUE THREAD

**Issue by stratacast** [Alexander-Miller/treemacs#505]
I feel like this is going to be a dumb question with a stupidly easy answer, but I can't find out how to toggle between treemacs and my other buffers. I can's simply switch to it with `C-x o` or ace-window, I end up either having to move my hand off the keyboard or close and reopen treemacs. Is there some easy shortcut or command that I can bind to a shortcut that simply switches to an already visible treemacs pane?

**Comment by stratacast** [comment]
Found it. I can find things in documentation just like I can find my screwdrivers after I set them down

treemacs-select-window

**Comment by Alexander-Miller** [comment]
There's plenty other window switching packages, so I never felt the need to add much else. Personlly I use winum to move between windows, with selecting treemacs bound to M-0 and I've yet to want anything more.
