### ISSUE TITLE
Relative paths for projects 

### ISSUE THREAD

**Issue by shrysr** [Alexander-Miller/treemacs#508]
The paths entered in the treemacs configuration file are converted to absolute paths when I hit C-c. How can the setting retain the relative path like ~/my_projects ?

This is causing problems when I switch machines (eg Linux to Mac). Request your advice in resolving this.

**Comment by Alexander-Miller** [comment]
Normally I'd say the persist file should not be shared like that, but this is a piece of portability I don't mind adding. I'll drop a patch later that will abbreviate the paths in the persist file.
