### ISSUE TITLE
Modeline is not displaying properly

### ISSUE THREAD

**Issue by taigacute** [Alexander-Miller/treemacs#510]
hi， i am new come to emacs, i used the treemacs, love your greate work. but  i got a problem .you can the pic ,the modeline in treemacs  is not normal，by the way i use spaceline.

![image](https://user-images.githubusercontent.com/41671631/62700046-7b763480-ba13-11e9-94c9-fa7a060fb067.png)

**Comment by Alexander-Miller** [comment]
What happens if you run this?

```Elisp
(setq-local mode-line-format
      (if ((fboundp 'spaceline-install)
           (progn
             (spaceline-install
              "treemacs" '((workspace-number
                            :face highlight-face)
                           major-mode)
              nil)
             '("%e" (:eval (spaceline-ml-treemacs)))))
          (error "Spaceline not recognized")))
```

**Comment by taigacute** [comment]
@Alexander-Miller  hi ,i got this error
```
Error (use-package): treemacs/:config: Invalid function: (fboundp (quote spaceline-install))

```

**Comment by Compro-Prasad** [comment]
I think the code should be:

```
(setq-local mode-line-format
      (if (fboundp 'spaceline-install)
           (progn
             (spaceline-install
              "treemacs" '((workspace-number
                            :face highlight-face)
                           major-mode)
              nil)
             '("%e" (:eval (spaceline-ml-treemacs))))
          (error "Spaceline not recognized")))
```

**Comment by taigacute** [comment]
ok , i got this error 
```
error: Spaceline not recognized
```

**Comment by Alexander-Miller** [comment]
That means `(fboundp 'spaceline-install)` returns nil, so the spaceline-install function is not defined. Spaceline has not been updated since end of 2018 and it works when I install the newest version now, so something else must be wrong.

What does `(featurep 'spaceline)` return?

What is the value of `mode-line-format` in your other buffers?

**Comment by taigacute** [comment]
`(featurep 'spaceline)` return t
the value is
```
Value: ("%e" (:eval (spaceline-ml-treemacs)))
Original value was 
("%e" mode-line-front-space mode-line-mule-info mode-line-client mode-line-modified mode-line-remote mode-line-frame-identification mode-line-buffer-identification "   " mode-line-position
 (vc-mode vc-mode)
 "  " mode-line-modes mode-line-misc-info mode-line-end-spaces)
Local in buffer  *Treemacs-Framebuffer-1*; global value is 
("%e"
 (:eval
   (spaceline-ml-main)))

```

**Comment by Alexander-Miller** [comment]
That actually looks correct. Strange that the check from above didnt work. What's the output of this?

```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (spaceline-ml-treemacs))
```
It should begin with something like `#(" 1   Treemacs   " 0 1 (face spaceline-highlight-face) 1 2` ....

**Comment by taigacute** [comment]
@Alexander-Miller   sorry  i want to know how to run this code?

**Comment by Alexander-Miller** [comment]
Same as you quickly run any other code. Paste it wherever and call `eval-last-sexp`.

**Comment by taigacute** [comment]
@Alexander-Miller   i paste it on command line  i used `evil`  because i am a vimer..  bu t i got error
![image](https://user-images.githubusercontent.com/41671631/62759859-1d019280-bab5-11e9-8c5a-5e572d2587df.png)

**Comment by Alexander-Miller** [comment]
End of file - you sure you got the full expression? 

Make sure your cursor is on the right of the expression, use insert mode of you have to.

**Comment by Compro-Prasad** [comment]
@taigacute You can just run it through `M-:` prompt.

**Comment by taigacute** [comment]
ok like this?
![image](https://user-images.githubusercontent.com/41671631/62764380-55f33480-bac0-11e9-9e54-d1d54d602cde.png)
i  got this
![image](https://user-images.githubusercontent.com/41671631/62764402-5ee40600-bac0-11e9-8f9e-cbf5b75bd1fb.png)

**Comment by taigacute** [comment]
thanks for your help . it works because i have a spaceline set.
```
  ;; (spaceline-toggle-major-mode-off)

```

**Comment by Alexander-Miller** [comment]
Ah, you don't use eyebrowse and have no major mode display, so treemacs' simple modeline was empty.

I'll be expanding on the modeline in https://github.com/Alexander-Miller/treemacs/issues/513
