### ISSUE TITLE
File watching not possible, no file descriptor left: 207

### ISSUE THREAD

**Issue by tam5** [Alexander-Miller/treemacs#512]
I sometimes get the following error when trying to call `treemacs-find-file`

```treeemacs--expand-dir-node: File watching not possible, no file descriptor left: 207```

It seems to happen after having a project open for a while. But switching to a different project and trying the same function _does_ work.

**Comment by Alexander-Miller** [comment]
No idea what this is, and google isn't helpful either. Best link I found is this: https://github.com/ruediger/magit-filenotify/issues/18. 

Maybe this will help: https://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by aconchillo** [comment]
For me this was fixed by increasing the number of file descriptors a process can open. In my system (macOS 10.15.6) it defaults to 256. So just ran:

```
sudo launchctl limit maxfiles 65536 200000
```

Following https://wilsonmar.github.io/maximum-limits/

After that I haven't seen the error anymore. So, I would say this issue can be closed.

**Comment by Alexander-Miller** [comment]
This ticket should have been closed a while ago - the solution is even part of the FAQ in the readme now.

Thanks for the macos link @aconchillo , I have added it to the FAQ entry.
