### ISSUE TITLE
A

### ISSUE THREAD

**Issue by rlazo** [Alexander-Miller/treemacs#52]

**Comment by rlazo** [comment]
The README mentions buffers when talking about ace-window, when it should be frames.

- A buffer is a Lisp object containing text to be edited.
- A window is an area of the screen that is used to display a buffer.
- A frame is a screen object that contains one or more Emacs windows.

**Comment by Alexander-Miller** [comment]
Well, you get bonus points for reading the manual.

It's windows I should be talking about, not frames, though, hence ace-window. Either way, https://github.com/Alexander-Miller/treemacs/commit/2153846a7b894444cb0cd3d50710ad9d300f8ef6 should have gotten them all.
