### ISSUE TITLE
Could not restore saved state

### ISSUE THREAD

**Issue by jgrodziski** [Alexander-Miller/treemacs#521]
When restarting Emacs I've got this error message when treemacs try to restore the workspace/project state from persistent file:
`[Treemacs] Could not restore saved state, found error in line '** project-name':`

The syntax of the persistent file seems correct, I recreate some projects from scratch after the error and still get it after restart.

I'm on the following versions:
```
Emacs 26.2 with spacemacs on the development branch (latest)
lsp-treemacs       20190817.1904 available  melpa      LSP treemacs
...
treemacs           20190814.459  dependency            A tree style file explorer package
treemacs-evil      20190619.1516 dependency            Evil mode integration for treemacs
treemacs-projec... 20190619.1516 dependency            Projectile integration for treemacs
```

**Comment by Alexander-Miller** [comment]
> The syntax of the persistent file seems correct

I need to see it. What doe your `treemacs-last-error-persist-file` look like?

**Comment by jgrodziski** [comment]
Here is the content of my `~/.emacs.d/.cache/treemacs-persist-at-last-error` file:

```
# State when last error occurred on 2019-08-25 12:13:03
# Error was 'Project name must be followed by path declaration' in line '** specy'

* Default
** specy
 - path :: ~/Dropbox/projects/specy
```
Thanks Alexander :)

**Comment by Alexander-Miller** [comment]
Works fine on my end if I copy-paste it, so we need to dig deeper.

 Can you reproduce the issue when using `treemacs-edit-workspaces`? What is the output of `(treemacs--read-persist-lines)`?

**Comment by jgrodziski** [comment]
Here are my steps:
* I start Emacs, my treemacs seems empty. 
* I create a workspace and project with treemacs, 
* then invoke `treemacs-edit-workspaces` then `(treemacs--read-persist-lines)`
* the ouput is: `("* Default" "** markov-book-title" " - path :: ~/Dropbox/projects/markov-book-title")`. So everything seems fine.
* I restart Emacs, my treemacs now seems empty again.
* I invoke `treemacs-edit-workspaces` then `(treemacs--read-persist-lines)`
* the output is: `("* Default")`

**Comment by Alexander-Miller** [comment]
> I restart Emacs, my treemacs now seems empty again.

First make sure that the persist file is written correctly when you quit emacs. If it is restart and call read-lines *before* treemacs is loaded. The function is mostly independent, you just need some libraries and replace/load `treemacs-persist-file`:

```Elisp
(defun treemacs--read-persist-lines (&optional txt)
  (-some->> (or txt (when (file-exists-p treemacs-persist-file)
                      (f-read treemacs-persist-file)))
            (s-trim)
            (s-lines)
            (--reject (or (s-blank-str? it)
                          (s-starts-with? "#" it)))))
```

**Comment by jgrodziski** [comment]
Updating the Emacs package and .emacs.d (spacemacs distrib) now seems to have fixed the issue....
treemacs version 20190826.1125

Thanks for your time Alexander and the awesome Treemacs :)
