### ISSUE TITLE
Can "treemacs-follow-mode" update on "treemacs-file-follow-delay" when I switch buffers using eyebrowse?

### ISSUE THREAD

**Issue by mrbig033** [Alexander-Miller/treemacs#523]
### Runtime Environment

- OS: MX Linux 18.3
- [dotfiles](https://github.com/mrbig033/dotfiles)
- GNU Emacs 27.0.50
- Evil version 1.2.14
- Treemacs v2.6-2019.09.03 @ 27.0.50
- Treemacs Evil 20190619.1516
- [treemacs use-package declarations](https://github.com/mrbig033/emacs.d/blob/master/modules/packages/misc/movements.org#treemacs)
- [eyebrowse use-package declaration](https://github.com/mrbig033/emacs.d/blob/master/modules/packages/misc/movements.org#eyebrowse)
- [~/.emacs.d](https://github.com/mrbig033/emacs)

### Issue

`treemacs-follow-mode` works very well, unless with `eyebrowse`. When I switch to a different buffer in another eyebrowse workspace, it ~~ceases to work~~ only updates when I refocus `treemacs`. Is it possible for treemacs to work as usual with eyebrowse?

**Comment by Alexander-Miller** [comment]
I'll look into this.

**Comment by Alexander-Miller** [comment]
Does this do the trick?

```Elisp
(defun treemacs--follow-after-eyebrowse-switch ()
  (when treemacs-follow-mode
    (--when-let (treemacs-get-local-window)
      (with-selected-window it
        (treemacs--follow-after-buffer-list-update)
        (hl-line-highlight)))))
(add-hook 'eyebrowse-post-window-switch-hook #'treemacs--follow-after-eyebrowse-switch)
```

**Comment by mrbig033** [comment]
It seems to be working really fine! I'll make more tests before closing the issue. Thank you very much!

**Comment by Alexander-Miller** [comment]
> before closing the issue.

No need. If the code works I'll be adding it to treemacs' compatibility layer.
