### ISSUE TITLE
File disappears from sidebar after saving

### ISSUE THREAD

**Issue by mrbig033** [Alexander-Miller/treemacs#524]
### Runtime Environment

- OS: MX Linux 18.3
- [dotfiles](https://github.com/mrbig033/dotfiles)
- GNU Emacs 27.0.50
- Evil version 1.2.14
- Treemacs v2.6-2019.09.03 @ 27.0.50
- Treemacs Evil 20190619.1516
- [treemacs use-package declarations](https://github.com/mrbig033/emacs.d/blob/master/modules/packages/misc/movements.org#treemacs)
- [~/.emacs.d](https://github.com/mrbig033/emacs)

### Issue

Shortly after I save a buffer, its corresponding file disappears from the treemacs sidebar. I tested with no configurations and the results were the same. 

### Update

The issue does not happen if `(setq treemacs-filewatch-mode nil)`.

**Comment by Alexander-Miller** [comment]
What version, if any, of treemacs-git-mode do you use?

**Comment by Alexander-Miller** [comment]
Also what happens if you try the following:
 - Disable filewatch mode
 - Open treemacs and move to some unmodified file
 - Modify it and save
 - Evaluate this:
```Elisp
(with-selected-window (treemacs-get-local-window)
  (treemacs-update-single-file-git-state "/path/to/modified/file"))
```

Does this make the file disappear?

**Comment by mrbig033** [comment]
> What version, if any, of treemacs-git-mode do you use?

I'm not sure, I never installed this package, it came with treemacs. `describe-package` cannot find it. I installed it by altering the `use-package` on the readme,

**Comment by mrbig033** [comment]
> ```emacs-lisp
> (with-selected-window (treemacs-get-local-window)
>   (treemacs-update-single-file-git-state "/path/to/modified/file"))
> ```

I got this message: `treemacs-update-single-file-git-state: Wrong type argument: arrayp, nil`

**Comment by mrbig033** [comment]
> ```emacs-lisp
> (with-selected-window (treemacs-get-local-window)
>   (treemacs-update-single-file-git-state "/path/to/modified/file"))
> ```

It did not.

**Comment by Alexander-Miller** [comment]
> I never installed this package, it came with treemacs

It's not a package, but a minor mode. I just need to know the value of the corresponding `treemacs-git-mode` variable.

> It did not.

I saw something about an error message, but it looks like you edited it. What was that about? It looked like a solid hint for where to look next.

Did running the command correctly update the file's color in treemacs?

**Comment by mrbig033** [comment]
> I saw something about an error message, but it looks like you edited it. What was that about?

Thanks. I had an error because I followed the instructions without changing `"/path/to/modified/file"`.

> Did running the command correctly update the file's color in treemacs?

There were no changes.

**Comment by Alexander-Miller** [comment]
Let's test the python parts then. First make sure that you have python3 installed and that `treemacs-python-executable` is set to a python3 binary.

Then find treemacs' installation directory and run its git status script like this:

> `python3 -O treemacs-single-file-git-status.py /home/a/Documents/git/treemacs/src/elisp/treemacs-dom.el 0 /home/a/Documents/git/treemacs/src/elisp /home/a/Documents/git/treemacs/src`

The first file argument is a modified file, the remaining files are its parent directories up to, but not including, the project root. The output should look like this: 

> `(("/home/a/Documents/git/treemacs/src/elisp/treemacs-dom.el" . "M")("/home/a/Documents/git/treemacs/src/elisp" . "M")("/home/a/Documents/git/treemacs/src" . "M"))`

**Comment by Alexander-Miller** [comment]
Closing here on account of inactivity. Feel free to re-open if this issue is still relevant.
