### ISSUE TITLE
Treemacs seems to require all-the-icons

### ISSUE THREAD

**Issue by mchuck** [Alexander-Miller/treemacs#526]
After loading Emacs, strange error appears:

`Error (use-package): treemacs/:catch: all-the-icons isn’t installed`

The same error shows up when I try to open treemacs window.

OS: Ubuntu 19.04
Emacs: 26.2

My treemacs config:

```
(use-package treemacs
  :ensure t
  :init
  (global-set-key (kbd "<f5>") 'treemacs)
  (global-set-key (kbd "<f6>") 'treemacs-projectile)
  (global-set-key (kbd "<f7>") 'treemacs-select-window)
  (setq treemacs-position 'right)
  (add-hook 'treemacs-mode-hook 'treemacs-follow-mode))

(use-package treemacs-projectile
  :ensure t
  :requires treemacs)
```

**Comment by Alexander-Miller** [comment]
Works for me. The only mentions of all-the-icons in the entire code base are either comments or examples from the readme, so I have no idea where this is coming from.

Try it again with debug-on-error enabled, hopefully the stack trace will have more info.

**Comment by mchuck** [comment]
It turns out that [doom-themes](https://github.com/hlissner/emacs-doom-themes) treemacs integration requires all-the-icons, thanks :)
