### ISSUE TITLE
Scroll bar and left-click drop down are at the wrong place in a 4K display.

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#528]
I tried using it on my normal laptop screen which happens to be 4K and the scroll bar is almost in the middle of the screen and the left-click drop down menu appears far away from the position of click.
![Screenshot from 2019-09-10 17-34-51](https://user-images.githubusercontent.com/43047754/64655502-1a66c580-d3f2-11e9-9288-995ca8b729d6.png)

**Comment by Alexander-Miller** [comment]
Probably a GTK problem: https://www.reddit.com/r/emacs/comments/am64y8/bug_with_scrollbar_on_ubuntu_1804/

**Comment by simurgh9** [comment]
Thanks! That solved my problem, I'll just quote the [answer](https://www.reddit.com/r/emacs/comments/am64y8/bug_with_scrollbar_on_ubuntu_1804/) here as well,

> "You use HiDPI resolution scaling, don't you? Last I checked, Emacs still uses some GTK widgets and some custom widgets, and they don't play well together in the presence of resolution scaling. I ended up aliasing emacs on my laptop to:
> 
>  `/usr/bin/env GDK_SCALE= emacs`
> (note the space after the equals sign is required) which tells GTK widgets to not resolution scale, which results in correct scrollbar behaviour. (It also results in icons being small, but I don't care because I don't use the icon bar.)
> 
> I filed a bug about this a long time ago, but no one ever responded and nothing came of it.
> 
> Edit: You can set the alias the normal way for launching emacs from a command line. For launching emacs from a desktop menu, you've got to copy `/usr/share/applications/emacs25.desktop` to `~/.local/share/applications/emacs25.desktop` and edit the Exec line." -(robolange)
