### ISSUE TITLE
treemacs-peek enchancements

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#531]
Can I alter how `(treemacs-peek)` works so I could map it to single click? And if I click to the resulting buffer it will not be closed, so only peeking (clicking) another file would close the buffer. Much like Atom behaves OOTB.

**Comment by Alexander-Miller** [comment]
> Can I alter how (treemacs-peek) works so I could map it to single click?

There's a recipe in #527

> And if I click to the resulting buffer it will not be closed, so only peeking (clicking) another file would close the buffer. 

This I'll have to look into.

**Comment by andreyorst** [comment]
I've tried this recipe, all solutions there are setting single click to peek thus making it harder to click on directories. Perhaps treemacs could just ignore this instead of flashing red and displaying the message.

Also, this advice:

```emacs-lisp
(defun dont-restore-window-on-leftclick (_)
  (remove-hook 'post-command-hook #'treemacs--restore-peeked-window))
(advice-add #'treemacs-leftclick-action :before #'dont-restore-window-on-leftclick)
```

disables automatic kill of the buffer which results into lot of buffers that were opened while peeking are still accessible, and thus visible in the tabline and buffer list:

![image](https://user-images.githubusercontent.com/19470159/64920289-7f3d6980-d7be-11e9-8244-eaf63d23cb43.png)
(all these buffers were picked and remain open)

**Comment by Alexander-Miller** [comment]
In that case I'll have to investigate how to properly rig this up. You'll need to be patient though, unless a new issue is trivial or a bug the items in the backlog take priority.

**Comment by andreyorst** [comment]
No problem

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Is this genuinely obsolete with the recent peek-mode changes, or are you frustrated because of the long wait? I'll have some free time in a few weeks, so if it's the latter I'd rather we reopen try again.
