### ISSUE TITLE
treemacs-peek closes buffer if simlink to the buffer was peeked

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#532]
I have file `config.org` and `README.org` both in one directory. `README.org` is a symbolic link to the `config.org` so GitHub could display config file in the repo. If I open `config.org` as a normal buffer, and then peek the `README.org`, `config.org` will be closed.

> The buffer visiting the peeked file will also be killed again, unless it was already
open before eing used for peeking.

also typo in `being` written as `eing`

**Comment by Compro-Prasad** [comment]
What is the value of `vc-follow-symlinks`?

**Comment by andreyorst** [comment]
`ask`

**Comment by Alexander-Miller** [comment]
The symlink wasn't resolved so treemacs didn't see that the file is open already. Should be fixed now.
