### ISSUE TITLE
Request: Improved usability with a different set of keybindings

### ISSUE THREAD

**Issue by sdwolfz** [Alexander-Miller/treemacs#534]
Here is what my general expectations would be:

- [x] `h` and `M-h` - close directory if current node is open, navigate up if current node is closed, or a file.
- [x] `l` and `M-l` - open directory if current node is closed, navigate inside to the first element if node is open, RET-action if it's not a directory
- [x] `M-S-h` (`M-H`) and `M-S-l` (`M-L`) would take the role of the current `h` and `l`. `C-h` and `C-l` are very usefull with the default functionality so that's why I choose `Meta` for the modifier.
- [ ] as @Compro-Prasad suggested, having `left` and `right` do the same thing as `h` and `l` would also be good.

The general idea is to re-allocate `h` and `l` to open/close directories, similar to whats happening in neotree. While the root manipulation keys are useful, they become useless when having multiple projects in your tree, and navigating with one hand using `h,j,k,l` while having a glass of water in the other is really something I would like more people to have the change to experience 😄 .

- [x] `Esc` when the Hydra is open should close it. This is just something that I instinctlvely press, probably due to my memory of using spacemacs transient states. I don't know a way to achieve that from my current config, without modifying the code. (https://github.com/Alexander-Miller/treemacs/pull/535)
- [ ] `'` - peek, open a file in the previous buffer, but keep the cursor in the treemacs buffer. Currently the file is only temporarily opened. Not sure how I feel about this yet, but an option to change the peek behaviour would be nice.
- [ ] `P` should probably be re-purposed for the current projects functionality, instead of using `C-c C-p`.
- [ ] `W` could also be used for workspace manipulation, instead of `C-c C-w`.
- [x] `w` for setting the width is a powerful feature, but quite awquard to use. What I suggest is to have `>` for increasing the window size by `increment` (default 1) and `<` to decrease the window size by `increment`. Instead of using the `w` for this, which could easily be mis-pressed.
- [ ] `|` and `-` to open in a split window, as suggested by @czert. Also it would be nice to have an option to invert the horizontal/vertical splits so they behave like `SPC w s` and `SPC w v` in spacemacs.

I have the following settings in my dotfiles as a workaround for the behaviour I want:
```elisp
  (with-eval-after-load "treemacs-evil"
    (evil-define-key 'treemacs treemacs-mode-map (kbd "'") #'treemacs-peek)
    (evil-define-key 'treemacs treemacs-mode-map (kbd "h") #'treemacs-collapse-parent-node)
    (evil-define-key 'treemacs treemacs-mode-map (kbd "l") #'treemacs-RET-action)
    (evil-define-key 'treemacs treemacs-mode-map (kbd "M-h") #'treemacs-root-up)
    (evil-define-key 'treemacs treemacs-mode-map (kbd "M-l") #'treemacs-root-down))
```
It's not perfect nor complete but it gets rid of most of my trouble.

I understand this is a breaking change, especially to the people that already formed their muscle memory, but getting keybindings right the first time is extremely difficult and this change would be an overall workflow improvement.

If you don't want to break functionality, I would also be hapy with only having the appropriate functions available in the code, and binding to them in my config, as long as they have the behaviour described above. I'm also willing to tackle some of these myself and open PRs, just let me know your opinion about it and maybe point me to the related area in the code and I'll find my way from there.

**Comment by Compro-Prasad** [comment]
This is a well thought issue with a ready made solution. Thanks @sdwolfz for opening this issue. Looks good to me.

**Comment by Compro-Prasad** [comment]
I would also like to have `left` and `right` do the same as `h` and `l`.

**Comment by Alexander-Miller** [comment]
> `h` - close directory if current node is open, navigate up if current node is closed, or a file.

I was ready to begin arguing that changing defaults is not something I want to get into, but h & l I'm willing to make an exception.

> `M-h` and `M-l` would take the role of the current `h` and `l`.

Can't believe they're not already taken. If I hadn't forgotten about them they'd be used for scrolling next-window, instead M-J/K.

> `'` - peek, open a file in the previous buffer, but keep the cursor in the treemacs buffer.

There's already `treemacs-visit-node-in-most-recently-used-window`, though you'll need a prefix arg to stay in treemacs.

Also where's `'` on your keyboard? For me it' next to RET and I need to press shift to get it. Maybe something like `,` can be used instead?

> but an option to change the peek behaviour would be nice.

The point of peeking is to open a file temporarily, and press RET when you want to keep it. How would you change that?

> I'm also willing to tackle some of these myself and open PRs, just let me know your opinion about it and maybe point me to the related area in the code and I'll find my way from there.

Sounds good. There's certainly enough in here to make working in small chunks easy, and I am quite busy with the current backlog, so PRs are welcome.

**Comment by sdwolfz** [comment]
For both keyboard layouts that I have to deal with regularly it's the second key right from `L`:

https://en.wikipedia.org/wiki/File:KB_United_Kingdom.svg
https://en.wikipedia.org/wiki/File:KB_United_States-NoAltGr.svg

I've suggested `'` since that was the one neotree used. Show me your layout and we can find a better one.

**Comment by Alexander-Miller** [comment]
My keyboard looks [like this](https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg).

**Comment by czert** [comment]
The `|` and `-` key bindings were used for vertical and horizontal splits in neotree (at least in spacemacs), and they were extremely usable. I keep using them in my config of treemacs and I think they should be made default again.

**Comment by sdwolfz** [comment]
thanks for the suggestion @czert, I remember these now. To be fair I kind of got used to the current `oav` and `oah` keys so I did not miss them so much, although I wish they were reversed so they behave like `SPC w v` and `SPC w s` in spacemacs.

I'll add to the main thread a note about them.

**Comment by sei40kr** [comment]
@sdwolfz 
https://github.com/sei40kr/spacemacs.d/blob/master/treemacs-custom.el
I did it for some key bindings in my `spacemacs.d`.

**Comment by sdwolfz** [comment]
Thanks @sei40kr, that's a good resource. I'll get back to working on this issue soon.

**Comment by billop** [comment]
So is it intended behavior for "open horizontal" to open vertically?

**Comment by Alexander-Miller** [comment]
I based the split behavior in i3wm :man_shrugging:

**Comment by czert** [comment]
@Alexander-Miller you are right that in i3, `split h` splits the screen into columns, while `split v` splits into rows. In VIM, though, `C-W h` splits into rows, and `C-W v` splits into columns. I gues that's where the confusion started. Personally, I prefer the VIM way, as it's the way I learned first, but I can imagine others preferring the i3 way.

As a solution, I suggest not using `v` or `h` as mnemotechnic keys, but rather `|` and `-`. Both have a clear meaning and are easy enough to remember. For example, in my i3 conf, I have:

```
bindsym $mod+bar split h
bindsym $mod+minus split v
```

And in my spacemacs dotfile:

```
 (evil-define-key 'treemacs treemacs-mode-map
    (kbd "|") 'treemacs-visit-node-ace-horizontal-split)
  (evil-define-key 'treemacs treemacs-mode-map
    (kbd "-") 'treemacs-visit-node-ace-vertical-split)
```

I also use `\` as an alias for `|` so that I don't have to use the shift key.

**Comment by billop** [comment]
> I based the split behavior in i3wm

Oh that makes sense, I use sway but never use the split bindings. It seems like there's two schools of thought on what "split vertical" means, and I'm so used to how vim does it.

**Comment by sdwolfz** [comment]
@Alexander-Miller Finally managed to find some time for this. Here is my current setup:

```elisp
  (with-eval-after-load 'treemacs
    (treemacs-define-TAB-action 'file-node-open   'treemacs-visit-node-default)
    (treemacs-define-TAB-action 'file-node-closed 'treemacs-visit-node-default)

    (defun treemacs-open-node-and-enter (&optional arg)
      (interactive "P")
      (progn
        (treemacs-toggle-node)
        (treemacs-next-line 1)))

    (treemacs-define-RET-action 'dir-node-closed  'treemacs-open-node-and-enter)
    (treemacs-define-RET-action 'root-node-closed 'treemacs-open-node-and-enter)

    (defun treemacs-goto-parent-node-with-arg (&optional arg)
      (interactive)
      (treemacs-goto-parent-node))

    (defcustom treemacs-UP-actions-config
      '((root-node-open   . treemacs-toggle-node)
        (root-node-closed . treemacs-goto-parent-node-with-arg)
        (dir-node-open    . treemacs-toggle-node)
        (dir-node-closed  . treemacs-goto-parent-node-with-arg)
        (file-node-open   . treeamcs-toggle-node)
        (file-node-closed . treemacs-goto-parent-node-with-arg)
        (tag-node-open    . treemacs-toggle-node)
        (tag-node-closed  . treemacs-goto-parent-node-with-arg)
        (tag-node         . treemacs-goto-parent-node-with-arg))
      ""
      :type '(alist :key-type symbol :value-type treemacs-up-action)
      :group 'treemacs)

    (defun treemacs-define-UP-action (state action)
      (setf treemacs-UP-actions-config (assq-delete-all state treemacs-UP-actions-config))
      (push (cons state action) treemacs-UP-actions-config))

    (defun treemacs-UP-action (&optional arg)
      (interactive "P")
      (-when-let (state (treemacs--prop-at-point :state))
        (--if-let (cdr (assq state treemacs-UP-actions-config))
          (progn
            (funcall it arg)
            (treemacs--evade-image))
          (treemacs-pulse-on-failure "No UP action defined for node of type %s."
            (propertize (format "%s" state) 'face 'font-lock-type-face)))))

    (defun treemacs-goto-child-node-with-arg (&optional arg)
      (interactive)
      (treemacs-next-line 1))

    (defcustom treemacs-DOWN-actions-config
      '((root-node-open   . treemacs-goto-child-node-with-arg)
        (root-node-closed . treemacs-open-node-and-enter)
        (dir-node-open    . treemacs-goto-child-node-with-arg)
        (dir-node-closed  . treemacs-open-node-and-enter)
        (file-node-open   . treemacs-visit-node-default)
        (file-node-closed . treemacs-visit-node-default)
        (tag-node-open    . treemacs-toggle-node-prefer-tag-visit)
        (tag-node-closed  . treemacs-toggle-node-prefer-tag-visit)
        (tag-node         . treemacs-visit-node-default))
      ""
      :type '(alist :key-type symbol :value-type treemacs-up-action)
      :group 'treemacs)

    (defun treemacs-define-DOWN-action (state action)
      (setf treemacs-DOWN-actions-config (assq-delete-all state treemacs-DOWN-actions-config))
      (push (cons state action) treemacs-DOWN-actions-config))

    (defun treemacs-DOWN-action (&optional arg)
      (interactive "P")
      (-when-let (state (treemacs--prop-at-point :state))
        (--if-let (cdr (assq state treemacs-DOWN-actions-config))
          (progn
            (funcall it arg)
            (treemacs--evade-image))
          (treemacs-pulse-on-failure "No DOWN action defined for node of type %s."
            (propertize (format "%s" state) 'face 'font-lock-type-face)))))

    (evil-define-key 'treemacs treemacs-mode-map (kbd "h") #'treemacs-UP-action)
    (evil-define-key 'treemacs treemacs-mode-map (kbd "l") #'treemacs-DOWN-action)
    (evil-define-key 'treemacs treemacs-mode-map (kbd "M-h") #'treemacs-UP-action)
    (evil-define-key 'treemacs treemacs-mode-map (kbd "M-l") #'treemacs-DOWN-action)
    (evil-define-key 'treemacs treemacs-mode-map (kbd "M-H") #'treemacs-root-up)
    (evil-define-key 'treemacs treemacs-mode-map (kbd "M-L") #'treemacs-root-down))
```

Basically I copied the `treemacs-RET-action` setup and updated it to fit my "One handed navigation" vision. As I also disable tags as I don't find them useful here, this needs to be refined a bit before it can be added.

Please let me know what you think and I can open a PR.

**Comment by Alexander-Miller** [comment]
> treemacs-open-node-and-enter

There's `treemacs-move-forward-on-expand` for that now.

> Please let me know what you think and I can open a PR.

Switching around TAB and RET is a no-go, that's way too big a change (I also need to stop internally relying on the TAB config always being useful for expanding/collapsing stuff, but that's another story). 

The UP and DOWN configs look good, all that stuff is PR material.

However I'm not sure about the name. We're talking about binding h & l, wouldn't LEFT & RIGHT make more sense?

> treemacs-goto-parent-node-with-arg

What's the point of these?

**Comment by sdwolfz** [comment]
Don't worry, the TAB config is a personal preference I'm keeping in my config, won't push that, the names were what random word came to mind when I wrote this, will change them.

The `treemacs-goto-parent-node-with-arg` was needed since `treemacs-goto-parent-node` does not accept an arg yet it's called with `(funcall it arg)`. Wrote that so I can have all the code in my config file, but when opening the PR I'll make that function receive an optional arg instead.

**Comment by Alexander-Miller** [comment]
Sorry for the delay, I've been busy renovating.
Everything's looking good, so we can merge now :+1:

**Comment by sdwolfz** [comment]
@Alexander-Miller no worries, take your time.

I'll carry on with the rest of the list now...

**Comment by Alexander-Miller** [comment]
Stayin alive.
