### ISSUE TITLE
C-c C-c mapping collides with existing Org mode keybinding

### ISSUE THREAD

**Issue by Kuba-Jasinski** [Alexander-Miller/treemacs#536]
In `treemacs-edit-workspaces` `C-c C-c` keybinding is assigned with `local-set-key`. This happens after switching to org mode. This should be probably unset later as it shadows another keybinding in org mode (even after leaving the buffer intended to edit treemacs workspaces).

**Comment by Alexander-Miller** [comment]
Should be fixed now.
