### ISSUE TITLE
Helpful hydra cannot print special chars (Aquamacs)

### ISSUE THREAD

**Issue by heatherleaf** [Alexander-Miller/treemacs#539]
Perhaps this is an integration problem with Aquamacs and/or Mac, because that's what I'm using.

When I start Helpful Hydra, I get the following warning messages (in buffer `*Warnings*`):

```
Warning (emacs): Unrecognized key: _C P A_
Warning (emacs): Unrecognized key: _C P D_
Warning (emacs): Unrecognized key: _C P R_
```

and the help buffer looks like this:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1324196/65574870-d84f8f00-df6e-11e9-892e-92456596f144.png">

i.e., any shortcut involving Ctrl, Meta or Shift seems to have viewing problems

**Comment by Alexander-Miller** [comment]
First things first, let's try tracking down those overly fancy symbols. What's the output of the following code (treemacs must be open for this):

```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (-if-let (keys (where-is-internal #'treemacs-next-project))
      (let ((key
             (key-description
              (-if-let (evil-keys (--first (eq 'treemacs-state (aref it 0)) keys))
                  (--map (aref evil-keys it) (number-sequence 1 (- (length evil-keys) 1)))
                (--map (aref (car keys) it) (number-sequence 0 (- (length (car keys)) 1)))))))
        key)))
```

**Comment by heatherleaf** [comment]
"^J"

(I haven't used elisp a lot, but I ran `eval-expression`, pasted your code, and got the result above)

**Comment by heatherleaf** [comment]
...and if I try the same, but with `#'treemacs-rename`, I get:

    "⇧R"

and with `#'treemacs-add-project-to-workspace `:

    "^C ^P A"

and `#'treemacs-previous-neighbour`:

    "⇢⌘P"

and `#'treemacs-next-line-other-window`:

    "⇢⌘⇧N"

The last one are the following unicode code points: [8674, 8984, 8679, 78]

**Comment by Alexander-Miller** [comment]
> "^C ^P A"

So you get both ^ for control and that ⌘ mac thing? I should be able to replace those fancy symbols with something hydra can display, but what do I use as a replacement for ⌘?

Let's give it a go. Does running the following improve the display of the hydra?

```Elisp
(cl-defun treemacs--find-keybind (func &optional (pad 8))
  (-if-let (keys (where-is-internal func))
      (let ((key
             (key-description
              (-if-let (evil-keys (--first (eq 'treemacs-state (aref it 0)) keys))
                  (--map (aref evil-keys it) (number-sequence 1 (- (length evil-keys) 1)))
                (--map (aref (car keys) it) (number-sequence 0 (- (length (car keys)) 1)))))))
        (setf key
              (s-replace-all
               '(("<return>" .  "RET")
                 ("<left>"   . "LEFT")
                 ("<right>"  . "RIGHT")
                 ("<up>"     . "UP")
                 ("<down>"   . "DOWN")
                 ("⇢"        . "M-")
                 ("⇧"        . "S-"))
               key))
        (cons (s-pad-right pad " " (format "_%s_:" key)) key))
    (cons (s-pad-right pad " " (format "_%s_:" " ")) " ")))
```

**Comment by heatherleaf** [comment]
Nope, but I experimented a little more. Apparently `defhydra` cannot handle arbitrary unicode inside bold formatting (`_⇧R_`), and it treats `^` as a special formatting character. If I remove bold formatting, and replace `^` with `\^`, it works:
```
        ...
        (setf key
              (s-replace-all
               '(("<return>" .  "RET")
                 ("<left>"   . "LEFT")
                 ("<right>"  . "RIGHT")
                 ("<up>"     . "UP")
                 ("<down>"   . "DOWN")
                 ("^"        . "\\^"))
               key))
        (cons (s-pad-right pad " " key) key))
    (cons (s-pad-right pad " " " ") " ")))
```

The result is like this:
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/1324196/65857769-c867ee80-e364-11e9-92f1-d3e24d1fc107.png">

The wiggly lines is because my font seems to be not exactly fixed-width for all unicode characters, and that's my own fault. 

The column padding gets two chars wider for every column, even in the first rows where there are no special characters - I don't know why, but I can live with that.

I don't know how to solve the bold formatting of keys: personally I don't care too much, but I understand if you want to keep it for non-Aquamacs users. Is it possible to check if the key string contains non-ascii chars, and then not bold format it?

**Comment by heatherleaf** [comment]
Btw, here's some background info about Aquamacs. Macs don't have a meta key, and Aquamacs provides several alternatives for the user:

- **option** is meta (`treemacs-next-neighbour` displays as **⌥N**)
- **right option** is meta (... displays as **⇢⌥N**)
- **right command** is meta (**⇢⌘N**)
- **escape** is meta (**Esc N**)

So, here are the modifier keys that Aquamacs recognises and displays as:

- **shift**: **⇧**
- **control**: **^**
- **option**: **⌥**
- **command**: **⌘**
- **right option**: **⇢⌥**
- **right command**: **⇢⌘**
- (plus probably some more that I don't know of)

**Comment by Alexander-Miller** [comment]
> Nope

What went wrong exactly? I'd rather use these replacements and make it look decent and more or less correct than give up bold text and still be left with a broken hydra because those special symbols are not monospaced.

Ideally I'd just use the following replacements:
```Elisp
(("<return>" .  "RET")
                 ("<left>"   . "LEFT")
                 ("<right>"  . "RIGHT")
                 ("<up>"     . "UP")
                 ("<down>"   . "DOWN")
                 ("^"        . "\\^")
                 ("⇢⌥"      . ">M-")
                 ("⌥"       . "M-")
                 ("⇢⌘"      . ">C-")
                 ("⌘"       . "C-")
                 ("⇧"        . "S-"))
```

**Comment by heatherleaf** [comment]
> I'd rather use these replacements and make it look decent and more or less correct than give up bold text and still be left with a broken hydra because those special symbols are not monospaced.

You're the boss!
(meaning, personally I'd prefer to see the ⌥⌘⇧ chars, but I understand your reasoning)

But, I think `M-` and `C-` are bad choices, because they already have emacs meanings:
- `M-` means meta, and in Aquamacs, you can configure almost any key as meta. ⌥ is called "option" in mac lingo, so I think `OPT-` (or `O-`) is a better replacement
- `C-` means ctrl, and macs already have the ctrl key. ⌘ is called "command" in mac, so `CMD-` is better. If you want a 1-char modifier, perhaps `#-` (because of visual similarity, not at all something that mac users are used to)
- And to make things consistent, `^` is really the control key, so it should be replaced by `C-`.

I tried a little bit, and it seems that `>CMD-` and `>OPT-` are too long, so perhaps `>#-` and `>O-` is a better choice.

How about this?
```
              (s-replace-all
               '(("<return>" . "RET")
                 ("<left>"   . "LEFT")
                 ("<right>"  . "RIGHT")
                 ("<up>"     . "UP")
                 ("<down>"   . "DOWN")
                 ("^"        . "C-")  ;; or "CRTL-"
                 ("⇢⌥"       . ">O-") ;; or ">OPT-" or "ROPT-" 
                 ("⌥"        . "O-")  ;; or "OPT-"
                 ("⇢⌘"       . ">#-") ;; or ">CMD-" or "RCMD-"
                 ("⌘"        . "#-")  ;; or "CMD-"
                 ("⇧"        . "S-")) ;; or "SHFT-"
               key))
```

Then my hydra looks like this:
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/1324196/66025231-3abc0880-e4f6-11e9-882d-e1cb8b623e3b.png">
so perhaps widen the 1st column by 1?

**Comment by Alexander-Miller** [comment]
> How about this?

Looks like that's the best compromise. I'll also make the first column1 character wider and we should be good to go.

**Comment by Alexander-Miller** [comment]
Got stuck elsewhere, sorry about the delay.

Let's make one final test before going live. Does everything look and work as expected if you run [this](https://gist.github.com/Alexander-Miller/365b8c3a0fb7caf3fe2e25a89886390c)?

**Comment by heatherleaf** [comment]
> Got stuck elsewhere, sorry about the delay.

No problem, thanks for taking the time!

> Let's make one final test before going live. Does everything look and work as expected if you run [this](https://gist.github.com/Alexander-Miller/365b8c3a0fb7caf3fe2e25a89886390c)?

Almost:
- "option is meta": 
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/1324196/67378703-f3221d00-f587-11e9-8966-eafdde41cb07.png">

- "right option is meta":
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/1324196/67378818-22d12500-f588-11e9-9a51-65a9498bf735.png">

- "right command is meta":
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/1324196/67378562-bce49d80-f587-11e9-80ca-34cdc8d59045.png">

- "escape is meta:
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/1324196/67378883-3e3c3000-f588-11e9-88bf-992dadf6ffde.png">

Personally I don't have a problem with the columns slightly off. I think the default in Aquamacs is the first version ("option is meta")

**Comment by Alexander-Miller** [comment]
> I think the default in Aquamacs is the first version ("option is meta")

So let's go with that. That means adjusting these replacements, right? 
` ("⇢⌘"      . ">#-") ("⌘"       . "#-")`

**Comment by Alexander-Miller** [comment]
Pushed a patch to master. Let me know if it looks correct.

**Comment by heatherleaf** [comment]
Looks fine!
(I.e., exactly as the screenshots 4 comments ago)

**Comment by Alexander-Miller** [comment]
:+1:
