### ISSUE TITLE
Feature Request: Bookmarks/Favorites

### ISSUE THREAD

**Issue by ysgard** [Alexander-Miller/treemacs#54]
First off, I gotta say: Awesome job with this plugin!  It's definitely displaced Neotree as my favorite file viewer.

Nerdtree, a vim plugin that inspired Neotree, had the ability to save bookmarks/favorites and quickly pull those up for quick access to frequently-used directories and files.  I'd love to see similar functionality in Treemacs, either by leveraging Emac's existing bookmarks functionality or via its own system.

**Comment by Alexander-Miller** [comment]
Yeah, I can offer a bridge to emacs' builtin bookmarks system.

Can you go into more detail about what neotree does, or provide a wiki link? Open view in bookmarked dir is an obvious case, but there's probably more stuff that can be added.

**Comment by fiveNinePlusR** [comment]
nerdtree just had a list of bookmarks in a simple file that were put at the top of the list of files. 

see example here: https://i.imgur.com/nTzIHpb.png sorry for the redaction

the display format is just bookmark name <the/path/to/the/file>

the bookmark format was a file in ~/.vim/NERDTreeBookmarks

each line was a bookmark in display order and the bookmarks are just:

`bookmark_name bookmark_path` 

spaces not allowed in the bookmark name(might have been allowed if you `\ ` but I am not sure. 

```
" ----------------------------
" Bookmark commands~
" :Bookmark [<name>]
" :BookmarkToRoot <name>
" :RevealBookmark <name>
" :OpenBookmark <name>
" :ClearBookmarks [<names>]
" :ClearAllBookmarks
```

and 

```
" ----------------------------
" Bookmark table mappings~
" double-click,
" o: open bookmark
" t: open in new tab
" T: open in new tab silently
" D: delete bookmark
```

were the docs for it.

**Comment by Alexander-Miller** [comment]
I won't change the treemacs view to manage bookmarks, a fuzzy matching selection framework like helm does that much better than treemacs can.

What I did do is add `treemacs-bookmark` that you can use to find your bookmarks in treemacs. I've pushed it to master now, go ahead and test it and see if anything's missing. If all's well I'll add update the readme - the keybind for it will be `M-m f B`.

**Comment by fiveNinePlusR** [comment]
Haven't had a chance to check out what you did but this is not something like emacs' bookmarks. it's actually bookmarks for folders instead of files that change the root of the top level tree to that node. helm is fantastic for files that you recall the name of and don't have the same effect as a project folder navigation bookmark.

**Comment by Alexander-Miller** [comment]
Helm offers `helm-bookmarks` which you can use to list/create/edit/delete your bookmarks. That's the wheel I won't be reinventing. `treemacs-bookmark` does what you describe, it changes the root to or selects or opens bookmarks.

Maybe something to add the selected node to your bookmarks would be useful, too, now that I think about it.

**Comment by Alexander-Miller** [comment]
> Maybe something to add the selected node to your bookmarks would be useful, too, now that I think about it.

That's now available as `treemacs-add-bookmark` and bound to b.

**Comment by ysgard** [comment]
Thank you!!!
