### ISSUE TITLE
error after update to Emacs 27

### ISSUE THREAD

**Issue by slk500** [Alexander-Miller/treemacs#540]
GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2019-09-28
After update while using Emacs form time to time I got this error: 
[Treemacs] "  File "/home/slk500/.emacs.d/elpa/treemacs-20190922.1026/treemacs-single-file-git-status.py", line 65
    elisp_conses = "".join([f'("{path}" . "{state}")' for path,state in result_list])

How I can fix this?

**Comment by Alexander-Miller** [comment]
What's the output of `git status --porcelain --ignored .` for the project where the error happens?

**Comment by slk500** [comment]
Saving file /home/slk500/Dropbox/phprefactor/index.org...
Wrote /home/slk500/Dropbox/phprefactor/index.org
[Treemacs] Update of node "/home/slk500/Dropbox/phprefactor/index.org" failed with status "exited abnormally with code 1" and result
[Treemacs] "  File "/home/slk500/.emacs.d/elpa/treemacs-20190922.1026/treemacs-single-file-git-status.py", line 65
    elisp_conses = "".join([f'("{path}" . "{state}")' for path,state in result_list])

git status --porcelain --ignored .
 D index.html
 M index.org
?? clean.html~
?? clean.org~
?? index.html~
?? index.org~
?? phpunithack.sh
?? test.php

**Comment by Alexander-Miller** [comment]
Locate treemacs' installation directory and run the status script like this:

`python -O treemacs-single-file-git-status.py FILE .  PARENTS` 

where FILE is a single file that's been changed and PARENTS is a list of the file's parent directories up to, and excluding, the project root.

It should look like this:

```
[I]-(a@a-laptop)-(/home/a/Documents/git/treemacs)-(master)
❯❯❯ python -O src/scripts/treemacs-single-file-git-status.py /home/a/Documents/git/treemacs/src/elisp/treemacs-core-utils.el . /home/a/Documents/git/treemacs/src/elisp /home/a/Documents/git/treemacs/src
(("/home/a/Documents/git/treemacs/src/elisp/treemacs-core-utils.el" . "M")("/home/a/Documents/git/treemacs/src/elisp" . "M")("/home/a/Documents/git/treemacs/src" . "M"))
```

Best use the index.html. Treemacs doesn't handle the deleted status, so maybe that's the cause of the trouble.

**Comment by jclosure** [comment]
Same when I run the status script issue:
```
➜  cd ~/.emacs.d/elpa/treemacs-20190927.1836
➜  treemacs-20190927.1836 python -O $(pwd)/treemacs-single-file-git-status.py $(pwd)/treemacs-core-utils.el . $(pwd) $(pwd)
  File "/home/local/me/.emacs.d/elpa/treemacs-20190927.1836/treemacs-single-file-git-status.py", line 66
    elisp_conses = "".join([f'("{path}" . "{state}")' for path,state in result_list])
                                                    ^
SyntaxError: invalid syntax
```

**Comment by jclosure** [comment]
The issue is that f-strings were introduced into Python 3.6.  Where I have:
```
➜  ~ python3 -V
Python 3.5.2
```

**Comment by Alexander-Miller** [comment]
@slk500 https://github.com/Alexander-Miller/treemacs/pull/548 should have fixed your problem, try again with the newest version.

**Comment by Alexander-Miller** [comment]
Closing on account of inactivity.
