### ISSUE TITLE
Attempt a Fat Dom

### ISSUE THREAD

**Issue by Alexander-Miller** [Alexander-Miller/treemacs#541]
Having a backing dom element for every single node - instead of just the ones that are expanded - should greatly simplify the remainder of #226 and downright trivialize #180.

**Comment by yyoncho** [comment]
Thanks for the heads up. I am on a short vacation but when I am back I will try it.

**Comment by yyoncho** [comment]
I tested the fat dom branch with the extensions that we have and didn't notice any issues. Few questions regarding the fat dom implementation:

1. Will this make the restoring the nodes state possible only by setting the node dom root? E. g. I have an extension which is associated with a buffer, I open node A, switch to another buffer, go back and I have A opened. 

2. Will this make possible to render extension node open by default?

**Comment by Alexander-Miller** [comment]
1. Sounds like you want to transplant a dom. That should be possible, though I need to look into what other metadata might need to be taken into account as well.

 2. It'll at least make is easier on my end.

So it's all doable, but will require some more work . You should open open an issue for both points.
