### ISSUE TITLE
COMMENT project in workspace

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#543]
I want to temporarily disable project in my workspace, since I'm not going to work on it in any observable future, but will come back to it eventually. Since Treemacs uses Org Mode format to store projects in workspaces I expect such thing as `COMMENT` (`C-c ;`) to work on project nodes:

```
* Work
** CModel
 - path :: ~/grid/cmodel
** KMD Trunk
 - path :: ~/grid/kmdtrunk
** COMMENT SoftFloat 3E
 - path :: ~/grid/SoftFloat-3e
```
Commented node should not appear in project list:

![image](https://user-images.githubusercontent.com/19470159/66297792-09c64400-e8f9-11e9-9800-bf60e4eac204.png)

Org mode disables `COMMENT`ed nodes when exporting, I expect the same thing from Treemacs. Is it possible?

**Comment by Alexander-Miller** [comment]
Disabling projects isn't possible right now, I didn't even know about org's COMMENT feature.

I'll put this on the todo list.
