### ISSUE TITLE
Icons missing in fresh Ubuntu install of Spacemacs

### ISSUE THREAD

**Issue by tgroshon** [Alexander-Miller/treemacs#549]
I'm using treemacs in Emacs 26.3 + Spacemacs (develop branch) on Ubuntu 19.04 and I see the following in my file tree:

![File tree showing black squares instead of icons](https://user-images.githubusercontent.com/1794859/66516294-b72e8880-eaae-11e9-8287-0096a2a2992a.png)

As you can see, the file/folder icons are missing and just displaying black squares.  I verified that the icons are here on the filesystem but am not sure how to debug further.

I have the same setup on a Macbook and the file icons show up correctly, it's just on a Linux machine that I'm experiencing the issue.

Any pointers would be appreciated.

**Comment by Alexander-Miller** [comment]
Try reinstalling. The compiler is known to make the occasional blooper with treemacs, I already had a case where the icons' location was set incorrectly.

If that doesn't work I need to know the output of the following code:
```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (symbol-value 'treemacs-icon-dir-open))
```

**Comment by chriselrod** [comment]
I just upgraded my emacs packages for the first time in months on two computers, and in both Treemacs quit working (no icons or text, `Wrong type argument: arrayp, nil` errors when trying to edit workspaces), but sure enough uninstalling/deleting and reinstalling Treemacs fixed the problem.

Treemacs is great when working on multiple computers thanks to the seamless Tramp.

**Comment by tgroshon** [comment]
just uninstalled and reinstalled and things work 
:man_shrugging: 
thanks for the pointers
