### ISSUE TITLE
many python processes of treemacs-single-file-git-status.py that don't complete 

### ISSUE THREAD

**Issue by jclosure** [Alexander-Miller/treemacs#550]
When I modify a file in a project defined in treemacs, it does not update the color.  Instead it spawns a python process for `treemacs-single-file-git-status.py` that never completes.  I get many of these for every file changed.  

```
Treemacs Upd... 17426   run     --              --           /usr/bin/python3 -O /home/me/.emacs.d/elpa/treemacs-20190922.1026/treemacs-single-file-git-status.py /home/me/project/Dockerfile 0 /home/me/project
Treemacs Upd... 21258   run     --              --           /usr/bin/python3 -O /home/me/.emacs.d/elpa/treemacs-20190922.1026/treemacs-single-file-git-status.py /home/me/project/Dockerfile 0 /home/me/project
Treemacs Upd... 22394   run     --              --           /usr/bin/python3 -O /home/me/.emacs.d/elpa/treemacs-20190922.1026/treemacs-single-file-git-status.py /home/me/project/Dockerfile 0 /home/me/project
Treemacs Upd... 24315   run     --              --           /usr/bin/python3 -O /home/me/.emacs.d/elpa/treemacs-20190922.1026/treemacs-single-file-git-status.py /home/me/project/Dockerfile 0 /home/me/project
```

There is also a buffer created for each of these processes that just hangs around.

```
Treemacs Update Single File Process
Treemacs Update Single File Process<2> 
Treemacs Update Single File Process<3>
…
```

I notice when I run it manually, it does the same thing as above, new process and new buffer that never completes/closes.

```elisp
(with-selected-window (treemacs-get-local-window)
  (treemacs-update-single-file-git-state "/home/me/project/Dockerfile"))
```

This happens for both `(treemacs-git-mode 'deferred)` and `(treemacs-git-mode 'extended)`.  Any idea why?

I'm running Python3.7.  It happens on multiple machines.  Here's my config
```elisp
(use-package treemacs
  :ensure t
  :defer 1
  :config
  (progn
    (setq treemacs-be-evil                       nil
          treemacs-collapse-dirs                 (if (executable-find "python3") 3 0)
          treemacs-deferred-git-apply-delay      0.5
          treemacs-display-in-side-window        t
          treemacs-eldoc-display                 t
          treemacs-file-event-delay              2000
          treemacs-max-git-entries               10000
          treemacs-file-follow-delay             0.2
          treemacs-follow-after-init             nil
          treemacs-git-command-pipe              ""
          treemacs-goto-tag-strategy             'refetch-index
          treemacs-indentation                   2
          treemacs-indentation-string            " "
          treemacs-is-never-other-window         nil
          treemacs-max-git-entries               5000
          treemacs-missing-project-action        'ask
          treemacs-no-png-images                 nil
          treemacs-no-delete-other-windows       t
          treemacs-project-follow-cleanup        nil
          treemacs-persist-file                  (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
          treemacs-recenter-distance             0.1
          treemacs-recenter-after-file-follow    nil
          treemacs-recenter-after-tag-follow     nil
          treemacs-recenter-after-project-jump   'always
          treemacs-recenter-after-project-expand 'on-distance
          treemacs-show-cursor                   nil
          treemacs-show-hidden-files             t
          treemacs-silent-filewatch              t
          treemacs-silent-refresh                t
          treemacs-sorting                       'alphabetic-desc
          treemacs-space-between-root-nodes      t
          treemacs-tag-follow-cleanup            t
          treemacs-tag-follow-delay              1.5
          treemacs-width                         35)

    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-fringe-indicator-mode t)
    (pcase (cons (not (null (executable-find "git")))
                 (not (null (executable-find "python3"))))
      (`(t . t)
       (treemacs-git-mode 'deferred))
      (`(t . _)
       (treemacs-git-mode 'simple)))

(use-package treemacs-projectile
  :after (treemacs projectile))

(use-package treemacs-icons-dired
  :after (treemacs dired)
  :config (treemacs-icons-dired-mode))

(use-package treemacs-magit
  :after (treemacs magit))
```

**Comment by Alexander-Miller** [comment]
I cannot reproduce it locally, so I'll need your help debugging this. The bulk of the legwork is done in a python script, so let's first see if it gets stuck outside emacs as well. Find treemacs' installation and launch it lik this:

> `python -O treemacs-single-file-git-status.py $file $current-state $parents`

For example:

```
❯❯❯ python -O treemacs-single-file-git-status.py /home/a/Documents/git/treemacs/Cask XXX /home/a/Documents/git/treemacs/src/elisp /home/a/Documents/git/treemacs/src
(("/home/a/Documents/git/treemacs/Cask" . "0")("/home/a/Documents/git/treemacs/src/elisp" . "0")("/home/a/Documents/git/treemacs/src" . "0"))
```
The current-state arg keep any work from getting done when the file's status hasn't changed since the last invocation, so we pass some garbage. The rest of the arguments is made up of the file's parents up to, and excluding the project root (though there's currently a bug that'll include the root is the file is directly below it).

If that doesnt finish either we can use good old println debugging to find out where things get stuck. I cannot reproduce it locally, so I'll need your help debugging this.

**Comment by Alexander-Miller** [comment]
I don't think it's directly my code that is blocking, any infinite loop would quickly make itself felt on your CPU. There is however this for the `wait()` method:

> This will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use Popen.communicate() when using pipes to avoid that.

One of the scripts does call `git ls-files` which could produce a lot of output. Luckily I only need the exit status, so you can try changing lines 70-72 to use `stdout=DEVNULL`.

**Comment by jclosure** [comment]
Ok, so that works.  Changing `add_git_processes` to the following makes it work:
```
def add_git_processes(status_listings, path):
    ignored_proc = Popen(IS_IGNORED_CMD + path, shell=True, stdout=DEVNULL, stderr=DEVNULL)
    tracked_proc = Popen(IS_TRACKED_CMD + path, shell=True, stdout=DEVNULL, stderr=DEVNULL)
    changed_proc = Popen(IS_CHANGED_CMD + path, shell=True, stdout=DEVNULL, stderr=DEVNULL)
One thing I did notice before making this change is that using `stdout=PIPE` did work on smaller projects, but not on large projects.

Should we go ahead make the default `stdout=DEVNULL`?  It's working well for me now on a large complex project (1500+ files) and lots of nested submodules.
```

**Comment by jclosure** [comment]
When I manually run the `IS_TRACKED_CMD + path` command, I see there's actually 2700 paths, e.g. 
```
$ git ls-files --error-unmatch /Users/me/projects/big_project
```

It's notable that I already have 
```elisp
(setq treemacs-max-git-entries 10000)
```
however, that's not the problem.

When I run the following manually `stdout=PIPE`, it still hangs.
```bash
python3 -O /Users/me/.emacs.d/elpa/treemacs-20191008.1937/treemacs-single-file-git-status.py /Users/me/projects/big_project/Dockerfile 0 /Users/me/projects/big_project
```
But if I change it to `stdout=DEVNULL`, that command completes and I get.
```elisp
(("/Users/me/projects/big_project/Dockerfile" . "M")("/Users/me/projects/big_project" . "M"))
```

**Comment by jclosure** [comment]
Ok, so Popen.wait() is subject to a deadlock when a lot of data is returned as is described here: 
https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait

> Note This will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use Popen.communicate() when using pipes to avoid that.

With large projects, we can hit this limitation on the returned data from the `tracked_proc` here: https://github.com/Alexander-Miller/treemacs/blob/master/src/scripts/treemacs-single-file-git-status.py#L49

We have a choice either we can use `stdout=DEVNULL` in the `Popen()` or we can follow the advice in the Python documentation and use `tracked_proc.communicate()` instead of `tracked_proc.wait()`.  For example the subprocess return code processing could be rewritten as:

```python
    i = 0
    l = len(proc_list)
    propagate_state = None
    while i < l:
        path, ignore_proc, tracked_proc, changed_proc = proc_list[i]
        if ignore_proc.communicate() and ignore_proc.returncode == 0:
            propagate_state = "!"
            print("ignore completed")
            result_list.append((path, propagate_state))
            break
        elif tracked_proc.communicate() and tracked_proc.returncode == 1:
            propagate_state = "?"
            print("tracked completed")
            result_list.append((path, propagate_state))
            break
        elif changed_proc.communicate() and changed_proc.returncode == 1:
            print("changed completed")
            result_list.append((path, "M"))
        else:
            print("no change completed")
            result_list.append((path, "0"))
        i += 1
```

This works the same way.  It waits but provides the EOF detection of communicate().  Since, we're not actually using the `(stdout_data, stderr_data)`, I'm not sure this is a better solution than just using DEVNULL for stdout.  I'm happy to provide a patch, but would ask for your guidance as to which approach you think is more appropriate here.

**Comment by Alexander-Miller** [comment]
> Since, we're not actually using the (stdout_data, stderr_data), I'm not sure this is a better solution than just using DEVNULL for stdout

Imo using DEVNULL is the way to go. It's the simplest change, properly signals our intent of ignoring the output and doesn't change semantics the way using `communicate` instead of `wait` might.

The ideal solution would of course be some command that detects untracked files without having to list them all, which I assume is an O(n) operation, but for now it's good enough that things are working as expected without any performance issues of other hitches.

**Comment by andyjda** [comment]
@Alexander-Miller I've been running into a very similar issue
For me the color update works without any apparent problem, but I'm left with many buffers and processes called "Treemacs Update Single File Process".

I tried applying the DEVNULL fix: changed line 95 to:
`    changed_proc = Popen(IS_CHANGED_CMD + path, shell=True, stdout=PIPE,    stderr=DEVNULL)`

This would trigger another problem at line 76: `AttributeError: 'NoneType' object has no attribute 'read1'`

I tried simply getting rid of that check on line 76, changing it to:

`        elif changed_proc.wait() == 0:`

And this seems to work fine for now: no additional buffers/processes, no errors in the *Messages* buffer, and Treemacs is applying the right colors to untracked and changed files.

Is there any reason why the original fix was not applied to all `_proc` variables (lines 94-96)? 
I'm not too familiar with this python script, am I messing something up with my changes?

**Comment by Alexander-Miller** [comment]
> I tried applying the DEVNULL fix: changed line 95 to:
changed_proc = Popen(IS_CHANGED_CMD + path, shell=True, stdout=PIPE, stderr=DEVNULL)

That's what the line looks like right now, a change that was added back in may. Try again with the latest treemacs version.

**Comment by andyjda** [comment]
Sorry I pasted the wrong yank!
`stdout=PIPE` was giving me the issue; I had to change it to `stdout=NULL`.

The fix seems to work fine for me, but I'm not sure what was wrong with the original code, or if it's something I should fix in my setup instead

**Comment by Alexander-Miller** [comment]
>  stdout=PIPE was giving me the issue; I had to change it to stdout=NULL.

Discarding stdout won't work, the script needs the output of `git ls-files` (at least that is the best way I have found to check if a *directory* contains modified files).

If the current version is giving you trouble then we can try using `communicate()`. Does this change help?

```Diff
modified   src/scripts/treemacs-single-file-git-status.py
@@ -1,4 +1,4 @@
-from subprocess import Popen, PIPE, DEVNULL
+from subprocess import run, Popen, PIPE, DEVNULL, check_output
 import sys
 import os
 
@@ -65,15 +65,15 @@ def main():
     propagate_state = None
     while i < l:
         path, ignore_proc, tracked_proc, changed_proc = proc_list[i]
-        if ignore_proc.wait() == 0:
+        if ignore_proc.communicate() and ignore_proc.returncode == 0:
             propagate_state = "!"
             result_list.append((path, propagate_state))
             break
-        elif tracked_proc.wait() == 1:
+        elif tracked_proc.communicate() and tracked_proc.returncode == 1:
             propagate_state = "?"
             result_list.append((path, propagate_state))
             break
-        elif (changed_proc.wait() == 0 and changed_proc.stdout.read1() != b''):
+        elif changed_proc.communicate() != b'' and changed_proc.returncode == 0:
             result_list.append((path, "M"))
         else:
             result_list.append((path, "0"))
```

**Comment by andyjda** [comment]
Been using this for the past few days and everything looks good! 
Thanks a lot for the quick fix!
