### ISSUE TITLE
How to open a file in the last active buffer?

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#553]
I sometimes work with my screen split in two where on the right hand there is an `*eshell*` buffer. Or, I set up buffers in a way I want. Then I go to open a file, navigate to it's node in treemacs and hit enter (or just use mouse and click). I am not sure how it chooses the buffer it opens this file in. But I want this file to be opened in the last active buffer, i.e., where the cursor last was. This is how the `C-x b` works, it opens the buffer you choose in place of the last active buffer area. Right now, I am using `o a a` and manually telling it where to open the new file.

**Comment by Alexander-Miller** [comment]
You can use "o r" - `treemacs-visit-node-in-most-recently-used-window`.

**Comment by simurgh9** [comment]
Is there a smart way to bind this to `<mouse-1>`? I tried simply binding the function `treemacs-visit-node-in-most-recently-used-window` to `<mouse-1>` but that even opens the directory nodes in buffers. Could we do something like `treemacs-single-click-expand-action` where it opens nodes in buffers only when it makes sense, e.g., a file node.

**Comment by Alexander-Miller** [comment]
Is ~pepsi~ double click ok? That'd be very easy to do (though I do need to push a fix, nobody has yet to notice that double click is using the RET action settings).

Dragging with the mouse also works.

**Comment by simurgh9** [comment]
Did I just help you find a bug? I feel proud heh, I am used to single click so if not too hard I'd like that but, I'll take double click as well. And, thanks for letting me know about the drag feature. I am slowly trying to transition to using the keyboard more but at times knowing how to do it with the mouse is nice as well!

**Comment by Alexander-Miller** [comment]
Sure did. 
Sorry about the delay, I was working my way though a big big bunch of fixes and enhancements. That's done now and the version I just pushed will include the fix you need. You can reconfigure click behavior to use the last window like this:
```Elisp
(treemacs-define-doubleclick-action 'file-node-open   #'treemacs-visit-node-in-most-recently-used-window)
(treemacs-define-doubleclick-action 'file-node-closed #'treemacs-visit-node-in-most-recently-used-window)
```

**Comment by simurgh9** [comment]
Thank You!
