### ISSUE TITLE
How to match two periods extension?

### ISSUE THREAD

**Issue by XO39** [Alexander-Miller/treemacs#554]
How to match the last two periods ?
I usually have a bunch of files `xxx.service.js` (two periods), and it will be very helpful if I can separate them from files like `xxx.js` (one period).

**Comment by Alexander-Miller** [comment]
As of now it is not possible. The get-extension function is used smack in the middle of very performance critical code, so I will first do some profiling to see whether allowing it to be overwritten is an option.

**Comment by XO39** [comment]
Thanks, looking forward to it. :)

**Comment by Alexander-Miller** [comment]
Found a workaround that will enable the choice without compromising performance. See `treemacs-file-extension-regex`.
