### ISSUE TITLE
[Extensions] Provide a way to render extension node expanded

### ISSUE THREAD

**Issue by yyoncho** [Alexander-Miller/treemacs#555]
This will allow us to persist the state of an extension and also will solve potential performance problems. I think that fat dom could possibly fix the performance problem.

**Comment by Alexander-Miller** [comment]
Oops.

**Comment by yyoncho** [comment]
I want to have the following behaviour in some of the extensions:

`C-0 TAB` - open all children
`C-3 TAB` - open 3 levels.

WDYT, does this make sense to be part of treemacs core?

**Comment by Alexander-Miller** [comment]
That is exactly what I planned in https://github.com/Alexander-Miller/treemacs/issues/441, so yeah I am all for it.

**Comment by yyoncho** [comment]
Ah, cool. It looks like I have requested before :)

I implemented lsp-mode references tree view  - https://raw.githubusercontent.com/emacs-lsp/lsp-treemacs/master/screenshots/references.gif which will benefit a lot from this feature.
