### ISSUE TITLE
[Question] matching full filename w/ extension for `treemacs-create-icon`?

### ISSUE THREAD

**Issue by gugutz** [Alexander-Miller/treemacs#556]
I wanna add a specific set of icons for files like tsconfig.js, eslintrc.js, webpack.config.js, but treemacs-create-icon is only considering the final extension (the word after the period)

How can i match exact full filenames so *.js files will have an icon, but tslint.js, tsconfig.js or *.spec.ts will have different icons?

Thanks in advance.

**Comment by Alexander-Miller** [comment]
Not possible right now, but I think it is a good option to have, so I will put it on my list.

**Comment by Alexander-Miller** [comment]
I've now changed the icon selection to check the full name first, so you can have different icons for tslint.js vs *.js.
