### ISSUE TITLE
Eyebrowse and workspace switching

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#559]
I'm `eyebrowse` user, and I'd like to have ability to have different Treemacs workspaces in different window configs managed by `eyebrowse`.

We have pretty much everything for this:

- `eyebrowse-(pre|post)-window-switch-hook` for remembering current treemacs workspace before configuration change, and changing to the remembered for another configuration if exists.
- `eyebrowse-(pre|post)-window-delete-hook` - for freeing remembered workspaces.

We need two functions in Treemacs for that:
- `treemacs-switch-workspace` - which exists, but it should accept optional argument for `WORKSPACE`, e.g. `treemacs-swithc-workspace &optional workspace)`
- `treemacs-active-workspace` - to return the name of active workspace

So there might be set these hooks:
- `eyebrowse-pre-window-switch-hook` - remember current workspace for current window config
- `eyebrowse-post-window-switch-hook` - set workspace to remembered for this config, or if none, remember currently selected workspace.
- `treemacs-switch-workspace-hook` - update remembered workspace for current window configuration.

What do you think?

**Comment by Alexander-Miller** [comment]
It's doable.
How'd you figure workspaces should be assigned to eyebrowse desktops - expanding the org interface?
```
* Default
 - eyebrowse-desktop :: 1, 2, 3
** dotfiles
 - path :: ~/Documents/git/dotfiles

* Other Stuff
 - eyebrowse-desktop :: &default
** Org
 - path :: ~/Documents/Foo

```

**Comment by andreyorst** [comment]
I, personally, do not see myself using such feature, because I create eyebrowse desktops occasionally when I need those, and some-times dynamically for ediff and other stuff that will break my current config. So for me it is more like a feature that ties certain treemacs workspace to certain eyebrowse workspace.

But I see the usecase for that as well, so this feature may be needed by others.

**Comment by Alexander-Miller** [comment]
Ah, you meant making this implicit. That would work, too, though the constant switching would play into the solution proposed in https://github.com/Alexander-Miller/treemacs/issues/563.

I have #222 lying around since forever, so maybe I'll be adding full eyebrowse integration eventually. Gotta start a poll first to see whether people would rather see eyebrowse or something like persp.

**Comment by andreyorst** [comment]
I think the functionality should be general enough that user could set it up for any workspace/window-config switching plugin, because Emacs 27 features it's own tab method of switching workspaces. So maybe the need is just exposing some functions to obtain current workspace, and change workspace non interactively.

Builtin eyebrowse would be nice, but there's too many layout managers around, and this will bring more and more requests to support.

**Comment by Alexander-Miller** [comment]
I have been looking for an excuse to give eieio a try. Let's see how that goes.

**Comment by MyriaCore** [comment]
+1 for `(treemacs-switch-workspace &optional workspace)` . My use-case doesn't actually have to do with eyebrowse, but *does* necessitate a nice way to switch workspaces non-interactively. For now I'm stuck trying to hack together a solution myself - hardly optimal.
