### ISSUE TITLE
C-m doesn't work, but RET does

### ISSUE THREAD

**Issue by rlazo** [Alexander-Miller/treemacs#56]
I can open a file without issues by pressing the RET key. But if I try to do it using C-m, which should be the same, I get the following error message

apply: Buffer is read-only: #<buffer *Treemacs*>

**Comment by Alexander-Miller** [comment]
They should be the same, but one is RET and the other is <return>, and for whatever reason, they're different.

I've pushed a patch to fix that, let me know if it works.

**Comment by rlazo** [comment]
commit 7f3c5668b8d52b2c6f0ac9fcf2269ac29eb8bc40 does fix the issue. Thanks!
