### ISSUE TITLE
treemacs-root-up not expanding parent

### ISSUE THREAD

**Issue by mpanarin** [Alexander-Miller/treemacs#561]
It seems that after some latest updates (in last day or 2) when treemacs-root-up is used, it is no longer exapanded. 
imagine directory structure 
```
test1 ---- test2
       \__ test3
```
moving from test2 to test1 will result in closed node test1. So I'll have to manually expand it to get to test3

**Comment by Antiarchitect** [comment]
Same here - very annoying.

**Comment by Alexander-Miller** [comment]
I'm looking into this.

**Comment by Alexander-Miller** [comment]
Should be fixed now.
