### ISSUE TITLE
How can I make project roots persist between sessions?

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#564]
I am not sure what causes this but I add projects by right clicking, selecting `Projects` and then `Add Project`. Then when I close emacs and reopen it, sometimes the projects that I opened last time are there and sometimes nothing is there I am prompted by a pop up to add a new root for a project. I would like for my project roots to persist in between sessions. How can I do this? Is there a variable I can set to paths so that I always have certain project roots set up when I open emacs?

**Comment by Alexander-Miller** [comment]
Your layout should always be persisted. There have been issues like this in the past, so first make sure you are using an up-to-date version of treemacs.

If that doesn't help you need to find out *when* things disappear. Create a minimal example for a setup that won't stick around and show it here. You can find it saved in `treemacs-persist-file`.

**Comment by simurgh9** [comment]
This is my version `20191106.2038`. I think I know when the session does not persist. I have a folder in which I keep most of my projects, let's call it `root` and I like to always have that open as a root project. But, sometimes when I am majorly working on only one of the projects inside `root`, I also open `root/dir1` as it's own separate project. Now, treemacs complains and says that `root` is already open and `dir1` is inside it. To get around that, I open `dir1` first and `root` again after that. This is when the session does not persist when you have `root` and `root/dir1` both opened as projects. Hope, this made sense.

**Comment by Alexander-Miller** [comment]
That is a big no-no around here. There is a good reason you had to work around treemacs not letting you do something: basically a file's absolute path is used as a primary key in many places in treeemacs' innards. When that key is no longer unique things break - in sometimes more and sometimes less obvious ways.

I clearly need to improve my validation, but there's nothing I can do about your workspace layout. I suggest using different workspaces for working on different things. You can open different workspaces in different frames, so you'd be able to see both at once.

**Comment by simurgh9** [comment]
So the project root address can not overlap? And thank you for the suggestions. :)
