### ISSUE TITLE
Error running timer

### ISSUE THREAD

**Issue by XO39** [Alexander-Miller/treemacs#566]
I'm getting this annoying error:

> Debugger entered--Lisp error: "Error running timer ‘treemacs--process-file-events’: (wrong-type-argument arrayp nil)"
>   message("Error running timer%s: %S" " ‘treemacs--process-file-events’" (wrong-type-argument arrayp nil))
>   timer-event-handler([t 24009 65408 532009 nil treemacs--process-file-events nil nil 0])
> 

Any idea what's the cause of it?

**Comment by Alexander-Miller** [comment]
This is a handler for dealing with file change events, so I need to know what's happening in the background in your file system and what treemacs is showing.
And make sure you are up-to-date, this area saw a lot of change recently.

**Comment by XO39** [comment]
> ..., so I need to know what's happening in the background in your file system and what treemacs is showing.

What should I do to help?

**Comment by Alexander-Miller** [comment]
Ideally a reproducible recipe like:
 - you have project that shows files A, B, C
 - you delete A and rename B to X from the shell
 - that's when the error appears

Treemacs is aware when the files it is showing are changed, create, deleted or renamed, so there must be *some* combination of such events that problems.

And of course you should always use an up-to-date version of treemacs. What does calling `treemacs-version` output?

**Comment by XO39** [comment]
Sorry for the late replay, for some reason didn't get notified about your reply...

Treemacs v2.6-2019.11.16  @ 26.3

The error starts when I start creating (C-x C-f) and/or writing (C-x C-w) withing emacs, I don't do much of these operations from terminal when I'm using emacs.

I have one project in treemacs that uses both django and vue

**Comment by Alexander-Miller** [comment]
OK, try this:
 - disable filewatch-mode
 - change some file
 - make sure it's actually changed from clean to modified in git or vice versa, or treemacs wont do anything
 - enable debug on error
 - run this: 
```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (treemacs-update-single-file-git-state "/file/you/changed"))
```

If it works right you'll see your file change git color, if not there will be a stack trace.

**Comment by Alexander-Miller** [comment]
Closing here on account of inactivity. Feel free to reopen if the issue is still relevant.

**Comment by hraban** [comment]
This seems to be the same error as #749 ?
