### ISSUE TITLE
treemacs-icons-dired interfering with file rename in Wdired

### ISSUE THREAD

**Issue by cwhatley** [Alexander-Miller/treemacs#568]
In emacs 27 head as of 11/14/2019:

With treemacs-icons-dired-mode (commit 092f907) loaded, I enter wdired mode with C-x C-q and modify a filename and hit C-c C-c. The file rename fails with the following error log:

![Screen Shot 2019-11-14 at 5 40 09 PM](https://user-images.githubusercontent.com/573757/68902266-da7bd180-0705-11ea-9e09-6ea84ff475a4.png)

Note that the filename it attempted to rename includes the icon.

**Comment by cwhatley** [comment]
Just realized this is only when a doom treemacs theme is chosen. The default theme doesn't interfere with dired wedit.

**Comment by Alexander-Miller** [comment]
Doom modifies treemacs' innards to some non-trivial degree, and I personally do not use it, and couldn't replace the problem when running doom-themes' treemacs extension, so I'm not sure I can help here. You should raise this with doom as well.
