### ISSUE TITLE
Can I make Treemacs "sticky" when switching between eyebrowse workspaces?

### ISSUE THREAD

**Issue by mrbig033** [Alexander-Miller/treemacs#569]
# My Environment

- **OS**: MX Linux 18
- **$ uname -r**: 4.19.0-5-amd64
- [dotfiles](https://github.com/mrbig033/dotfiles)
- **i3wm** version 4.13
- [~/.config/i3](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
- **GNU Emacs** 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2019-11-19
- [~/.emacs.d](https://github.com/mrbig033/emacs)
- [treeemacs use-package declaration](https://github.com/mrbig033/emacs02/blob/92ff2a36c688c5199550dd8d324743b784c8cd96/init.el#L618)
- [eyebrowse use-package declaration](https://github.com/mrbig033/emacs02/blob/92ff2a36c688c5199550dd8d324743b784c8cd96/init.el#L2254)

# Issue

I use [eyebrowse](https://github.com/wasamasa/eyebrowse) for workspace functionality on Emacs, but when I switch workspaces the Treemacs sidebar goes away. Can I somehow force it to stick on every workspace, window configuration, etc?

**Comment by Alexander-Miller** [comment]
If you want treemacs to *always* be around you can do this:
```Elisp
(defun popup-treemacs ()
  (save-selected-window
    (treemacs-select-window)))
(add-hook 'eyebrowse-post-window-switch-hook #'popup-treemacs)
```

**Comment by mrbig033** [comment]
Yep, that works, thanks!
