### ISSUE TITLE
Allow customization of xdg-open command

### ISSUE THREAD

**Issue by tlhr** [Alexander-Miller/treemacs#57]
I think it would be great if it were possible to customize the command used for `treemacs-xdg-open`, as it doesn't work on macOS (the equivalent command is just `open`).

**Comment by Alexander-Miller** [comment]
Good idea. Shouldn't even be necessary for you to customize yourself - ranger uses a different command based on your `system-type`. I can do the same.

**Comment by ylluminarious** [comment]
I concur, this would be very nice to have. Just came here from the reddit post and was about to ask for the very same feature :P

**Comment by Alexander-Miller** [comment]
Patch is pushed now.
The old xdg-open command is declared deprecated and will be removed eventually, ox is now bound to `treemacs-visit-node-in-external-application` in tandem with the other visit-node functions. It knows how to open files on linux, mac and windows. Let me know how it works for you.

**Comment by ylluminarious** [comment]
@Alexander-Miller Thanks, currently waiting for the MELPA build to finish.

**Comment by ylluminarious** [comment]
@Alexander-Miller Apologies for the delayed reply. Your new change seems to work fine, so you could close this ticket as far as I'm concerned.
