### ISSUE TITLE
Follow dired directory

### ISSUE THREAD

**Issue by sei40kr** [Alexander-Miller/treemacs#572]
I want Treemacs to follow the directory opened in dired.

**Comment by Alexander-Miller** [comment]
A bit weird to use what's basically 2 file managers ([dired can do trees too](https://github.com/jojojames/dired-sidebar)), but ok, a bit of extra compatibility can't hurt.

**Comment by sei40kr** [comment]
@Alexander-Miller Thanks for a lot!
