### ISSUE TITLE
Workspace maintainance and key discovery

### ISSUE THREAD

**Issue by bestlem** [Alexander-Miller/treemacs#573]
Neither the ? hydra nor the popup menu on mouse button show any workspace manipulation commands.

I mean the [Workspace keybinds](https://github.com/Alexander-Miller/treemacs#workspaces-keybinds-prefix-c-c-c-w)

Can at least switch and edit(as this covers deletion rename etc) be added to a menu somewhere.

**Comment by Alexander-Miller** [comment]
Thanks for the heads up. I'll add the keybinds in both places.
