### ISSUE TITLE
How to make return key open the file nodes in the most recent buffer?

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#574]
A while back I asked a question about how to make the file open in the most recent buffer when opened with a mouse click and I got it to work as per your suggestion of,

```lisp
(treemacs-define-doubleclick-action
   'file-node-open   #'treemacs-visit-node-in-most-recently-used-window)
(treemacs-define-doubleclick-action
   'file-node-closed #'treemacs-visit-node-in-most-recently-used-window)
```

I know `o r` can be used with the keyboard but I was wondering if something similar could be set for the return key to automatically open the file nodes in the most recent buffer.

**Comment by Alexander-Miller** [comment]
Same procedure as with the mouse, but using `treemacs-define-RET-action`.

**Comment by simurgh9** [comment]
```lisp
(treemacs-define-RET-action
   'file-node-open   #'treemacs-visit-node-in-most-recently-used-window)
(treemacs-define-RET-action
   'file-node-closed #'treemacs-visit-node-in-most-recently-used-window)
```
This works! Thanks.
