### ISSUE TITLE
Theme Support link is broken

### ISSUE THREAD

**Issue by PiyushDatta** [Alexander-Miller/treemacs#578]
I want to learn more about treemac theme support, since I want to customize my treemac. 

However, the link is broken in the readme, this link is href'ed under the word 'Configuration'.

Link:
https://github.com/Alexander-Miller/treemacs/blob/master/Custom%20Themes%20and%20Icons

**Comment by Alexander-Miller** [comment]
The link should go here: https://github.com/Alexander-Miller/treemacs#customizing-themes-and-icons

Looks like github fails with links with spaces and I need to look for a workaround.
