### ISSUE TITLE
Error in latest treemacs: `treemacs--create-buffer-for-scope: Symbol’s function definition is void: assoc-delete-all`

### ISSUE THREAD

**Issue by egh** [Alexander-Miller/treemacs#579]
emacs version: GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-09-08, modified by Debian

`assoc-delete-all` seems to have been added in emacs 27.

See https://github.com/emacs-mirror/emacs/blob/e3661f8c35b3057c58e8c0b474f597697ce413ba/etc/NEWS#L960

**Comment by Alexander-Miller** [comment]
> assoc-delete-all seems to have been added in emacs 27.

Not quite, looks like it's been added some 7 months ago in 26.2, at least that's what the NEWS file says when you look at it on the emacs26 branch. Which is quite surprising - when I looked it up yesterday I saw discussions on emacs-devel about adding it all the way back in 2005.
Oh well, I'll push a workaround shortly.

**Comment by Alexander-Miller** [comment]
Should be fixed now.

**Comment by egh** [comment]
Oops, my mistake. Yes, unfortunately 26.2 seems to be delayed on debian for some reason. Thank you!
