### ISSUE TITLE
Make treemacs follow a file opened in a Projectile project

### ISSUE THREAD

**Issue by tuhdo** [Alexander-Miller/treemacs#58]
It would be nice whenever I open a file using `projectile-find-file`, `treemacs-projectile` also moves the focus to that specific file. It could be done by using a `find-file-hook` to update `treemacs`.

Finally, thanks for this great package.

**Comment by Alexander-Miller** [comment]
Assuming you're selecting a file from the same project treemacs is already showing you can either call `treemacs-find-file` to manually selected the file, or enable `treemacs-follow-mode` to automatically move focus to whatever is currently selected (again in the same file tree treemacs already shows).

Or did you mean something else?

**Comment by tuhdo** [comment]
Ah yes, `treemacs-follow-mode` is exactly what I need. Thanks.
