### ISSUE TITLE
treemacs-map-icons-with-auto-mode-alist not working as expected

### ISSUE THREAD

**Issue by sandinmyjoints** [Alexander-Miller/treemacs#581]
I'd to use the CSS icon for LESS files. Based on the readme, I tried the following, but I still see the generic icon for files with extension `.less`. Am I doing it wrong?

```emacs-lisp
     (treemacs-map-icons-with-auto-mode-alist
     '("\\.less\\'")
     '(less-css-mode   . (treemacs-get-icon-value "css")))
```

**Comment by Alexander-Miller** [comment]
Treemacs is looking for a regex match, not the actual regex, so just ".less" should work. 

I'll update the eldoc to clarify that.
