### ISSUE TITLE
Fix treemacs buffer width

### ISSUE THREAD

**Issue by anihm136** [Alexander-Miller/treemacs#582]
I'm trying to ensure that the treemacs window does not get resized when using golden-ratio-mode. Currently, when I switch from a treemacs window to a regular buffer in golden-ratio-mode, the treemacs window gets resized, althought spacemacs seems to have an exclusion for it in the layers.

What does work is when I interactively set the window to be fixed width (`tw`). I'd like that to be the default behaviour. I've found the variable that tracks it (`treemacs--width-is-locked`) and tried setting it in a few places, but as I understand, it becomes a buffer local value when treemacs is opened. It appears that the variable is actually initialised to `t`, but changed somewhere later on (I wasn't able to follow too well due to my inexperience in elisp).

So, how do I make treemacs have fixed width by default?

**Comment by anihm136** [comment]
UPDATE: This happens to occur only on the latest update of treemacs (~ 1 week). The previous version had an issue where all windows were renumbered, but the buffer-local value of `treemacs--width-is-locked` was `t`. The current version fixes the numbering issue, but now the buffer-local value of the variable is `nil`

**Comment by anihm136** [comment]
UPDATE: Figured it out. At init, the width lock actually depends on another global variable (`treemacs-width-lock`), which is set to nil by default. This causes the treemacs window to be unlocked for resize at init. Changing this to `t` solved my issue.

**Comment by Alexander-Miller** [comment]
> when I switch from a treemacs window to a regular buffer in golden-ratio-mode, the treemacs window gets resized

Treemacs-mode is part of `golden-ratio-exclude-modes` by default, so this should not happen regardless of other width settings.

>  the width lock actually depends on another global variable (treemacs-width-lock

I cannot find it on my end, where is it declared?

**Comment by anihm136** [comment]
> Treemacs-mode is part of `golden-ratio-exclude-modes` by default, so this should not happen regardless of other width settings.

I read this too, that's why I was a bit confused when it happened.

> I cannot find it on my end, where is it declared?

I'm sorry, it was `treemacs-lock-width`. It's defined in config.el of the treemacs layer
