### ISSUE TITLE
Ability to disable treemacs-git-mode

### ISSUE THREAD

**Issue by cbourgeois** [Alexander-Miller/treemacs#583]
Hi Alexander and thanks for all the great development around treemacs.

I would like to have an option to disable treemacs-git-mode altogether, as it slows down my setup significantly and I am tied to python2. Unfortunately setting treemacs-git-mode to nil forces setup-git-mode at startup which forces me to manually disable it every time.
Can you add a 'none mode on top of simple, extended and deferred ?

**Comment by Alexander-Miller** [comment]
> and I am tied to python2

My condolences.

> Unfortunately setting treemacs-git-mode to nil

That is not how minor modes work. You disable it with `(treemacs-git-mode -1)`. 

If you use the use-package example from the readme you need to replace the part that enables it, otherwise use `with-eval-after-load` so you code runs *after* treemacs is loaded.

**Comment by cbourgeois** [comment]
Thanks a lot Alexander, that did it !
