### ISSUE TITLE
error: (void-variable treemacs--buffer-access)

### ISSUE THREAD

**Issue by seagle0128** [Alexander-Miller/treemacs#585]
- GNU Emacs 27.0.50
- macOS Catalina
- Package: treemacs-20191210.1843
- Configuration: [Centaur Emacs](https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-treemacs.el)

```elisp
Debugger entered--Lisp error: (void-variable treemacs--buffer-access)
  treemacs-magit--extended-git-mode-update("/Users/vincent/.emacs.d")
  #f(compiled-function () #<bytecode 0x1fe145201091>)()
  apply(#f(compiled-function () #<bytecode 0x1fe145201091>) nil)
  timer-event-handler([t 0 3 0 nil #f(compiled-function () #<bytecode 0x1fe145201091>) nil idle 0])
```

**Comment by Alexander-Miller** [comment]
Byte code bleed over. You updated treemacs, but not treemacs-magit, so the latter is using macro-expanded code from the former that no longer exists. Reinstalling - maybe just recompiling - treemacs-magit will fix this.

**Comment by seagle0128** [comment]
Thank you!
