### ISSUE TITLE
Improvements to peek mode: sequential previews and open/edit shortcut

### ISSUE THREAD

**Issue by dato** [Alexander-Miller/treemacs#590]
(This comes from a comment in #478.)

There are two improvements to the peek functionality that I’d find very useful, and which might make sense to implement if other people think so too. (Both features are orthogonal and could be implemented independently.)

  - first, a kind of “sticky” peek state, in which navigation in the treemacs buffer keeps on reusing the same preview window to show files (without having to press `P` again, that is)

  - second, a way to “upgrade” from peek state to edit state. At the moment, if I try to visit (with, say, `oo`) the current peek’d file, the preview buffer is lost, the window goes back to the previously edited file, and the _position_ in the Treemacs buffer is reverted as well (this last bit might be only in follow mode, I’m not sure).

    It'd be great being able to press, say, `M-RET` or `RET` or `TAB` or even plain `oo` and start visiting/editing the peek'd file. (Perhaps there's an easy way to achieve this, and I haven't been able to figure out.)

Do either of these make sense to you?

**Comment by mijoharas** [comment]
A "peek mode" as suggested is something I'd very much like (I actually implemented one for neotree a few years back https://github.com/jaypei/emacs-neotree/pull/270 ).

I also agree with the second point. I tend to open files with enter, and wanting to press enter after peeking at the file feels very natural to me.

Are you keen for these features?

**Comment by rileyrg** [comment]
A +1 for peek mode staying active  but only based on a config or toggle  - default to no. I bind right arrow to peek, left arrow could cancel the sticky peek for example. 

Certainly currently when "peeking" I would think enter should open that file in edit mode rather than close the peek and return to the previous buffer.

**Comment by Alexander-Miller** [comment]
> Are you keen for these features?

My feelings can be summed up as "so much to do, so little time". The
proposals sound good to me, but my current plan is to get through my
other issues oldest-first, so it might take a while.

**Comment by qoops-1** [comment]
Not sure whether it is a good idea, because it uses internal API `treemacs--restore-peeked-window`, but here's a quick hack you can do to fix the second issue in your own config:

    (defun custom-treemacs-visit-node (&optional arg)
      (interactive "P")
      (remove-hook 'post-command-hook #'treemacs--restore-peeked-window)
      (funcall-interactively 'treemacs-visit-node-no-split arg))
    (setq treemacs-default-visit-action 'custom-treemacs-visit-node)

**Comment by Alexander-Miller** [comment]
Stayin alive,

**Comment by Alexander-Miller** [comment]
Just pushed a change that covers all points. Peeking is now a minor mode, files will be peeked at while you move around in the treemacs buffer. Peeking will stop (and peeked buffers cleaned up) when you leave the treemacs window, so `RET`, `oo` and everything else will work automatically.

The new setup requires an Emacs version that supports `window-selection-change-functions`, so IIRC you need at least Emacs 27.

**Comment by simurgh9** [comment]
So...

I used `treemacs-peek` and had it bound to `/` but after this there seems to be no `treemacs-peek` since when called using `/` I get, `command-execute: Autoloading file path/to/treemacs.elc failed to define function treemacs-peek`. This alluded me to think that there may have been some oversight during byte-compilation or something and I tried to fix it in *dumb ways* before I started looking here.

Interestingly, `C-h f treemacs-peek` gives,

```
treemacs-peek is an autoloaded interactive Lisp function in
‘treemacs.el’.

[Arg list not available until function definition is loaded.]

Not documented.
```
Which also made me think the solution is to make the function load. So why is this function still there? If it is, should it not say something helpful about the `treemacs-peek-mode`?

---
While in `treemacs-peek-mode`, sometimes I don't get any code highlighting on the first peek.

---
When I open a markdown file, which runs the spell checker, this happens,

```
Blocking call to accept-process-output with quit inhibited!! [48 times]
Spell Checking...42%
Blocking call to accept-process-output with quit inhibited!! [50 times]
Spell Checking...86%
Blocking call to accept-process-output with quit inhibited!! [16 times]
Spell Checking completed.
```
And the peek mode is disabled leaving the markdown file permanently opened.

---
Peek minor mode also seems to peek at directory nodes by opening them in dired. I don't really want this. It should just ignore a node unless it is a file.

**Comment by Alexander-Miller** [comment]
> So why is this function still there?

It isn't. That function has been deleted and `treemacs-peek` is now `treemacs-peek-mode` (I should've set up an alias for it). My guess is that you are seeing an old autoload that didn't go away, one with an incorrect location at that - `treemacs-peek` used to be in the treemacs-interface module.

> When I open a markdown file, which runs the spell checker, this happens,

I need to recheck my cancel conditions. If a spell checker interferes with peeking I might have to rethink the entire cancel peeking when leaving treemacs idea.

> Peek minor mode also seems to peek at directory nodes by opening them in dired.

I'll add an option for that and disable it by default.

**Comment by Alexander-Miller** [comment]
@simurgh9 Can you check whether the following change fixes your spell check issue?

```Diff
modified   src/elisp/treemacs-peek-mode.el
@@ -45,7 +45,8 @@
 
 (defun treemacs--setup-peek-buffer (path)
   "Setup the peek buffer and window for PATH."
-  (let* ((file-buffer (get-file-buffer path))
+  (let* ((inhibit-message t)
+         (file-buffer (get-file-buffer path))
```

**Comment by simurgh9** [comment]
I had,

```lisp
(defun treemacs--setup-peek-buffer (path)
  "Setup the peek buffer and window for PATH."
  (let* ((inhibit-message t) (file-buffer (get-file-buffer path))
         (next-window (next-window (selected-window)))
         (window (if file-buffer
                     (or (get-buffer-window file-buffer)
                         next-window)
                   next-window)))
    (save-selected-window
      (select-window window)
      (unless treemacs--pre-peek-state
        (setf treemacs--pre-peek-state (list window (window-buffer window))))
      (if file-buffer
          (switch-to-buffer file-buffer :norecord)
        (find-file-existing path)
        (add-to-list 'treemacs--peeked-buffers (current-buffer))))))
```

in my treemacs-peek-mode.el and then ran `byte-recompile-file`.

Peek mode was still disabled after visiting a markdown.

```
Treemacs-Peek mode enabled
Starting new Ispell process /usr/bin/aspell with british dictionary...done
Blocking call to accept-process-output with quit inhibited!! [48 times]
Spell Checking...42%
Blocking call to accept-process-output with quit inhibited!! [50 times]
Spell Checking...86%
Blocking call to accept-process-output with quit inhibited!! [16 times]
Spell Checking completed.
```

**Comment by simurgh9** [comment]
> My guess is that you are seeing an old autoload that didn't go away

How do I make it go away?

**Comment by Alexander-Miller** [comment]
> How do I make it go away?

Dunno. You'll have to take it up with your package manager. Normally a reinstall or upgrade and a restart should be enough.

> in my treemacs-peek-mode.el and then ran byte-recompile-file.

Best I can tell from the eldoc `byte-recompile-file` doesn't actually load the file. Did you also restart Emacs after recompilation? If not just call `eval-defun` on the changed function and try again. If that doesn't work either you can try this patch:

```Diff
modified   src/elisp/treemacs-peek-mode.el
@@ -74,14 +74,19 @@ Check if the node at point is a file, and if yes take a peek."
 (defun treemacs--finish-peek-on-window-leave (&optional _)
   "Finish peeking when the treemacs window is no longer selected.
 Shut down peek-mode while making sure that the current buffer will not be
 purged."
-  (let ((treemacs-buffer (treemacs-get-local-buffer))
-        (current-buffer (current-buffer)))
-    (unless (equal treemacs-buffer current-buffer)
-      (setf treemacs--peeked-buffers
-            (delete current-buffer treemacs--peeked-buffers))
-      (treemacs-peek-mode -1))))
+  (run-with-timer
+   0.1 nil
+   (lambda ()
+     (let ((treemacs-buffer (treemacs-get-local-buffer))
+           (current-buffer (current-buffer)))
+       (unless (equal treemacs-buffer current-buffer)
+         (setf treemacs--peeked-buffers
+               (delete current-buffer treemacs--peeked-buffers))
+         (treemacs-peek-mode -1))))))

```

**Comment by simurgh9** [comment]
Pending till I figure out how to apply patches ...(sorry)

**Comment by Alexander-Miller** [comment]
As usual, magit can help with that. Anyway you just need this function:

```Elisp
(defun treemacs--finish-peek-on-window-leave (&optional _)
  "Finish peeking when the treemacs window is no longer selected.
Shut down peek-mode while making sure that the current buffer will not be
purged."
  (run-with-timer
   0.1 nil
   (lambda ()
     (let ((treemacs-buffer (treemacs-get-local-buffer))
           (current-buffer (current-buffer)))
       (unless (equal treemacs-buffer current-buffer)
         (setf treemacs--peeked-buffers
               (delete current-buffer treemacs--peeked-buffers))
         (treemacs-peek-mode -1))))))
```

**Comment by simurgh9** [comment]
Okay so I did fresh reinstall of everything. And, it works sometimes. I am not much concerned so I don't feel like meddling with the source code (unless it is absolutely essential to some bug here).

I can tell you this though, each time I opened a markdown file, `(flyspell-buffer)` was getting called. You can close this issue as far as I am concerned right now.

**Comment by Alexander-Miller** [comment]
All right, I'll push my initial fix.
