### ISSUE TITLE
Icons in dired mode are poor quality until after treemacs is invoked for the first time

### ISSUE THREAD

**Issue by emacsomancer** [Alexander-Miller/treemacs#596]
Before invoking treemacs:

![screenshot@2019-12-30T06:05:59 055337-07:00](https://user-images.githubusercontent.com/9464083/71583321-25da1b80-2acb-11ea-96a6-068618240b6f.png)

After invoking treemacs:

![screenshot@2019-12-30T06:06:37 119838-07:00](https://user-images.githubusercontent.com/9464083/71583323-2d012980-2acb-11ea-95bc-b4f1e542b7c9.png)

Close-up of before/after:

![treemacs-beforfile:⁄⁄⁄home⁄slade⁄Pictures⁄emacs⁄treemacs-before-after pnge-after](https://user-images.githubusercontent.com/9464083/71583448-ba447e00-2acb-11ea-9800-e469251a4861.png)

**Comment by Alexander-Miller** [comment]
Can't reproduce it on my end. What's your treemacs version, emacs version, OS etc?

What's the output of `(treemacs-get-icon-value "org")` before after invoking treemacs?

Does the icon also look bad at first when you call `(insert (treemacs-get-icon-value "org"))`? Does the insert icon improve or look the same after you call treemacs?

**Comment by emacsomancer** [comment]
> Can't reproduce it on my end. What's your treemacs version, emacs version, OS etc?

Latest version of treemacs; I've tried on both emacs 26.3 and emacs-git, and on both Void and Arch Linux (using the distro-provided and Guix-provided, and custom-build emacs), and I get the same behaviour uniformly. So since you can't reproduce, and it happens to me when varying other factors, I assume it's something to do with my Emacs setup.

> What's the output of `(treemacs-get-icon-value "org")` before after invoking treemacs?

Before invoking `treemacs`:
```
Debugger entered--Lisp error: (void-function treemacs-get-icon-value)
  (treemacs-get-icon-value "org")
  (progn (treemacs-get-icon-value "org"))
  eval((progn (treemacs-get-icon-value "org")) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```
After invoking `treemacs`:

`#("  " 0 1 (display (image :type png :file "/home/slade/.emacs.d/elpa/treemacs-20200103.1907/icons/default/vsc/org.png" :scale 1 :ascent center :background "#000000") img-selected (image :type png :file "/home/slade/.emacs.d/elpa/treemacs-20200103.1907/icons/default/vsc/org.png" :scale 1 :ascent center :background "#333333") img-unselected (image :type png :file "/home/slade/.emacs.d/elpa/treemacs-20200103.1907/icons/default/vsc/org.png" :scale 1 :ascent center :background "#000000")))`

> Does the icon also look bad at first when you call `(insert (treemacs-get-icon-value "org"))`? Does the insert icon improve or look the same after you call treemacs?

Before invoking `treemacs`, I get the error:

```
Debugger entered--Lisp error: (void-function treemacs-get-icon-value)
  (treemacs-get-icon-value "org")
  (insert (treemacs-get-icon-value "org"))
  (progn (insert (treemacs-get-icon-value "org")))
  eval((progn (insert (treemacs-get-icon-value "org"))) t)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

After invoking `treemacs` I get the good-looking org icon inserted.

**Comment by Alexander-Miller** [comment]
> Before invoking treemacs, I get the error:

My bad. I meant after you do call dired, since that will load treemacs as well. I want to see if there's any obvious differences in the icons after treemacs is actually opened.

**Comment by emacsomancer** [comment]
>  output of (treemacs-get-icon-value "org") before  invoking treemacs but after invoking dired:

`#("  " 0 1 (display (image :type png :file "/home/slade/.emacs.d/elpa/treemacs-20200103.1907/icons/default/vsc/org.png" :scale 1 :ascent center :background "unspecified-bg") img-selected (image :type png :file "/home/slade/.emacs.d/elpa/treemacs-20200103.1907/icons/default/vsc/org.png" :scale 1 :ascent center :background "unspecified-bg") img-unselected (image :type png :file "/home/slade/.emacs.d/elpa/treemacs-20200103.1907/icons/default/vsc/org.png" :scale 1 :ascent center :background "unspecified-bg")))`
`
>  output of (treemacs-get-icon-value "org") after  invoking treemacs:

#("  " 0 1 (display (image :type png :file "/home/slade/.emacs.d/elpa/treemacs-20200103.1907/icons/default/vsc/org.png" :scale 1 :ascent center :background "#000000") img-selected (image :type png :file "/home/slade/.emacs.d/elpa/treemacs-20200103.1907/icons/default/vsc/org.png" :scale 1 :ascent center :background "#333333") img-unselected (image :type png :file "/home/slade/.emacs.d/elpa/treemacs-20200103.1907/icons/default/vsc/org.png" :scale 1 :ascent center :background "#000000")))`

Notice that the background changes. This could be one reason you can't reproduce, if your theme is different from mine.

> Does the icon also look bad at first when you call (insert (treemacs-get-icon-value "org"))? Does the insert icon improve or look the same after you call treemacs?

Yes, the inserted icon looks bad (i.e. the same as my original 'before' in the first post) before invoking treemacs. Once I invoke treemacs, the inserted icon looks good (i.e. the same as the 'after' image in my first post).

**Comment by Alexander-Miller** [comment]
> Notice that the background changes.

Looks like we have our culprit. Do the icons start looking right if you call`(treemacs--setup-icon-background-colors)`? You may need a new dired buffer, I'm not sure if the changes will apply to icons already rendered).

**Comment by TatriX** [comment]
> > Notice that the background changes.
> 
> Looks like we have our culprit. Do the icons start looking right if you call`(treemacs--setup-icon-background-colors)`? You may need a new dired buffer, I'm not sure if the changes will apply to icons already rendered).

This helps!

**Comment by emacsomancer** [comment]
>  Do the icons start looking right if you call`(treemacs--setup-icon-background-colors)`?

Yes, indeed, this fixes the icons. Just selecting an already open dired buffer is enough for the change to take place.

**Comment by Alexander-Miller** [comment]
All right, fix is pushed.
