### ISSUE TITLE
Symbol's function definition is void: pfuture-process (on treemacs-refresh)

### ISSUE THREAD

**Issue by kahrkunne** [Alexander-Miller/treemacs#60]
Not much more to add other than what is in the title, running treemacs-refresh gives that error. Emacs 25.2.1

**Comment by Alexander-Miller** [comment]
Try updating both treemacs and pfuture. I introduced a breaking change in the latter and updated both. Maybe something got out of synch.

**Comment by kahrkunne** [comment]
Thanks, that fixed it.

One would think that Emacs would update automatically, or at least not let things like this happen.. but alas

**Comment by Alexander-Miller** [comment]
At least it got resolved quickly and easily.

Let's keep this issue open for a few days, in case someone has the same problem.

**Comment by Alexander-Miller** [comment]
Should be safe to close now.
