### ISSUE TITLE
Directory and subdirectory can be added as project

### ISSUE THREAD

**Issue by zoechi** [Alexander-Miller/treemacs#600]
According to #265 this should not be possible.

Actually I came here because that's what I actually wanted to do, but it only works when directories are added in reverse order.
Now I wanted it use `treemacs-edit-workspaces` but there it does not work at all.

So if I add 

- `~/source/customer1/web_project/angular_client` (client)

and then

- `~/source/customer1/web_project/` (server)

it adds both.
Only when I add them in in reverse order it shows an error.

(the project layout was not my idea ;-) )

- treemacs 20200103.1907
- Emacs 26.1

**Comment by Alexander-Miller** [comment]
> Actually I came here because that's what I actually wanted to do, but it only works when directories are added in reverse order.

Definitely a bug. It'd be nice to have, but absolute paths are basically primary keys in many circumstances, and this is not the type of gordian knot I am up to cutting just yet.

**Comment by zoechi** [comment]
Could that not just be solved by associating files only to the closest project?

```
P1
|_File 1
|- P2
  |_File 2
```
So only `File 1` would belong to `P1` and `File 2` would only belong to `P2`?

**Comment by Alexander-Miller** [comment]
It's not as simple as just an association. The treemacs view is backed
up by a full dom. Files' paths are the keys used to efficiently access
the underlying dom node and all the information it carries.

The information which project's file cannot always be available either.
Filewatch only receives change events like "File X was changed",
follow-mode only acts based on `buffer-file-name`.

And if one path can map to multiple dom nodes a massive rewrite is
required - grep alone counts some 66 instances of dom interaction,
usually with wildly different business logic behind them.

**Comment by zoechi** [comment]
I see. Perhaps you kan keep it in mind for when you have spare time and don't know anything better to do ;-)
The package is super helpful as it is already as it is.

**Comment by Alexander-Miller** [comment]
It's a task for the time when I manage to actually reduce the number of
issues to maybe a single page, whenever that may be.
