### ISSUE TITLE
Treemacs lists Prolog files as Perl

### ISSUE THREAD

**Issue by hjek** [Alexander-Miller/treemacs#609]
I have a file `foo.pl` with some Prolog terms listed in Treemacs.

- **What happened:** Next to `foo.pl` I see a small picture of an onion.

- **What I expected:** Next to `foo.pl` I expected to see a small picture of an owl. 
![owl](https://user-images.githubusercontent.com/11958965/73016859-fa72f400-3e1e-11ea-8d9e-01a39d6f997c.png)

**Comment by Alexander-Miller** [comment]
As per a quick google search .pl is used for both perl and prolog files,
so the default is at least not wrong.

Treemacs also doesn't have any prolog icons at the moment. If the owl
you've posted here is the proper icon for prolog files I can push a
patch to use it, but you will still have to tell treemacs that .pl files
should be use the prolog icon as described here:
https://github.com/Alexander-Miller/treemacs#customizing-themes-and-icons
