### ISSUE TITLE
wrong-type-argument error while enabling treemacs-toggle

### ISSUE THREAD

**Issue by seagle0128** [Alexander-Miller/treemacs#61]
GNU Emacs 25.3, Ubuntu LTS 16.04
with the latest treemacs on 9/27.

```elisp
Debugger entered--Lisp error: (wrong-type-argument arrayp #<process Process Future>)
  treemacs--create-branch("/home/avamar/.emacs.d/lisp" 0 #<process Process Future> #<process Process Future<1>>)
  treemacs--build-tree("/home/avamar/.emacs.d/lisp")
  treemacs--init("/home/avamar/.emacs.d/lisp/")
  treemacs()
  treemacs-toggle()
  funcall-interactively(treemacs-toggle)
  call-interactively(treemacs-toggle nil nil)
  command-execute(treemacs-toggle)
```

**Comment by Alexander-Miller** [comment]
This is probably the same issue as https://github.com/Alexander-Miller/treemacs/issues/60. Try updating both treemacs and pfuture.

**Comment by seagle0128** [comment]
Hi, What's the latest version of pfuture? I installed 20170726.1502 and didn't find newer one on MELPA.

**Comment by Alexander-Miller** [comment]
Judging by the error your pfuture is up-to-date, but your treemacs isn't. You say you're on the newest version, but it looks like some old code is still loaded. Try deleting all treemacs packages from the file system and restarting emacs.

**Comment by seagle0128** [comment]
Okay. I deleted treemacs and pfuture packages, and reinstalled. It does work!
Thanks for the update. Closing it.
