### ISSUE TITLE
No window left from selected window

### ISSUE THREAD

**Issue by taigacute** [Alexander-Miller/treemacs#610]
Hi new come to emacs from vim . when i use `C-w-h` i got this error
![image](https://user-images.githubusercontent.com/41671631/73055289-6f016d80-3ec7-11ea-8ef5-9d8e8f1f442c.png)

## evil config
```elisp
(straight-repo evil
  :hook (after-init . evil-mode)
  :demand t
  :preface
  (setq evil-want-visual-char-semi-exclusive t
        evil-magic t
        evil-echo-state t
        evil-indent-convert-tabs t
        evil-ex-search-vim-style-regexp t
        evil-ex-substitute-global t
        evil-ex-visual-char-range t  ; column range for ex commands
        evil-insert-skip-empty-lines t
        evil-mode-line-format 'nil
        evil-respect-visual-line-mode t
        ;; more vim-like behavior
        evil-symbol-word-search t
        ;; cursor appearance
        evil-normal-state-cursor '(box "orchid")
        evil-normal-state-cursor '(box "#F29718")
        evil-motion-state-cursor '(box "YellowGreen")
        evil-insert-state-cursor '(bar "#B8CC52")
        evil-emacs-state-cursor '(bar "Red")
        evil-visual-state-cursor '(box "#F86155")
        ;; must be set before evil/evil-collection is loaded
        evil-want-keybinding nil)

  :config
  (evil-select-search-module 'evil-search-module 'evil-search))

(straight-repo evil-collection
  :after evil
  :config
  (evil-collection-init))

```
## treemacs config
```elisp
(straight-repo treemacs
    :config
    (setq treemacs-collapse-dirs           (if treemacs-python-executable 3 0)
          treemacs-sorting                 'alphabetic-case-insensitive-desc
          treemacs-follow-after-init       t
          treemacs-is-never-other-window   t
          treemacs-silent-filewatch        t
          treemacs-silent-refresh          t
          treemacs-persist-file (concat supremacs-cache-dir "treemacs-persist")
          treemacs-last-error-persist-file (concat supremacs-cache-dir "treemacs-last-error-persist")
          treemacs-width                   30)

    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (pcase (cons (not (null (executable-find "git")))
                 (not (null (executable-find "python3"))))
      (`(t . t)
       (treemacs-git-mode 'deferred))
      (`(t . _)
       (treemacs-git-mode 'simple))))

(straight-repo treemacs-evil
  :after treemacs evil
  :config
  (general-def evil-treemacs-state-map
    [return] #'treemacs-RET-action
    [tab]    #'treemacs-TAB-action
    "TAB"    #'treemacs-TAB-action
    ;; REVIEW Fix #1875 to be consistent with C-w {v,s}, but this should really
    ;;        be considered upstream.
    "o v"    #'treemacs-visit-node-horizontal-split
    "o s"    #'treemacs-visit-node-vertical-split))


(straight-repo treemacs-projectile
  :after treemacs projectile)


(straight-repo treemacs-magit
  :after treemacs magit)


(straight-repo treemacs-persp
  :after treemacs persp)

```

**Comment by Alexander-Miller** [comment]
> when i use `C-w-h` i got this error

I assume you mean `C-w h`, or evil-window-left.

In that case the error message looks correct to me. Judging by your
screenshot treemacs is selected already, so you can't go any more left
than that.

**Comment by taigacute** [comment]
but i cant jump to treemacs window .what keymap should i use?

**Comment by Alexander-Miller** [comment]
It works on my end, both in my working setup and using `make clean-start`.
I cannot say why evil is unable to find the window.

Either way the canonical means to get to treemacs is calling
`treemacs-select-window`, bound to something like `M-0` to integrate
with winum-mode.

**Comment by taigacute** [comment]
I dont install winum-mode ..so how can i debug it?

**Comment by Alexander-Miller** [comment]
You don't *need* winum mode. The `M-0` keybind is just a recommendation
based on winum's conventions.

**Comment by taigacute** [comment]
hmm  dont know what happend..did you use evil? i want know does it work on your emacs

**Comment by taigacute** [comment]
i can use `C-w l`(evil-window-right) jump to main area from treemacs. but cant use jump to treemacs by `C-w h` (evil-window-left)

**Comment by taigacute** [comment]
i found this  ` treemacs-is-never-other-window `,if i set to nil  i can use `c-w l` but i try to use doom,i found doom can work with `treemacs-is-never-other-window t` ..

**Comment by taigacute** [comment]
another question is i cant use any keymap on treemacs buffer .... new come to emacs from vim .thanks for your help  if you have time can check my [config]( https://github.com/hardcoreplayers/supremacs)

**Comment by Alexander-Miller** [comment]
> i found doom can work with treemacs-is-never-other-window t

I don't know what doom is doing. It does patch treemacs to some degree,
so for all I know the parameter is not applied correctly.

Either way now that I know the cause I can tell that things are working
as intended. The never-other-window parameter makes treemacs invisible
to commands like `other-window` and apparently `evil-window-left`. It
doesn't even have to be about treemacs, it works with any 2 windows on a
clean start. I will adjust the documentation accordingly.

**Comment by shivekkhurana** [comment]
I was also able to fix it by setting `treemacs-is-never-other-window` to `nil`.
