### ISSUE TITLE
treemacs file name misalignment

### ISSUE THREAD

**Issue by taigacute** [Alexander-Miller/treemacs#614]
like this pic.
![image](https://user-images.githubusercontent.com/41671631/73588757-dcd11900-4507-11ea-83f7-e9755e120e91.png)

**Comment by Alexander-Miller** [comment]
Unless you have the same problem with the default theme I cannot help you. 

To me it looks like a problem with tab width, but you need to ask whoever made that theme.

**Comment by taigacute** [comment]
used the doom-theme

**Comment by Compro-Prasad** [comment]
Which doom theme?

**Comment by taigacute** [comment]
@Compro-Prasad  doom-one

**Comment by Compro-Prasad** [comment]
@taigacute How did you fix it?

**Comment by taigacute** [comment]
@Compro-Prasad   @hlissner  had fixed .update your doom-themes
