### ISSUE TITLE
treemacs-iconcs-dired-mode is not enabled when using dired-jump

### ISSUE THREAD

**Issue by CSRaghunandan** [Alexander-Miller/treemacs#615]
When using `dired-jump` to open the dired buffer of the current working directory for a buffer visting a file, `treemacs-icons-dired-mode` is not enabled. I would have to go up a directory or inside a directory for `treemacs-iconcs-dired-mode` to be enabled again, but if i go back to the previous directory, i still don't see the treemacs icons enabled.

**Comment by Alexander-Miller** [comment]
It looks like the code is just not loaded when you use dired-jump because it is a dired-x command. What does your use-package setup look like?

**Comment by CSRaghunandan** [comment]
> It looks like the code is just not loaded when you use dired-jump because it is a dired-x command. What does your use-package setup look like?

[here](https://github.com/CSRaghunandan/.emacs.d/blob/master/setup-files/setup-treemacs.el) is my treemacs config and [here](https://github.com/CSRaghunandan/.emacs.d/blob/master/setup-files/setup-dired.el) is my dired config

**Comment by Alexander-Miller** [comment]
Does adding the following lines help?

```Elisp
(with-eval-after-load 'dired-x
  (treemacs-icons-dired-mode))
```

**Comment by CSRaghunandan** [comment]
> Does adding the following lines help?
> 
> ```emacs-lisp
> (with-eval-after-load 'dired-x
>   (treemacs-icons-dired-mode))
> ```

Nope, same result. Its still not enabled after I use `dired-jump`.

**Comment by Alexander-Miller** [comment]
My guess is that this part is responsible:

>   :after treemacs dired

When first testing this I must've made a mistake, because I thought dired is always loaded, so running things `:after dired` would not have been lazy. That's why treemacs is there as well, and probably why it doesn't work on your end.

Try removing treemacs from the `:after`. It seems to work on my end.

**Comment by CSRaghunandan** [comment]
> My guess is that this part is responsible:
> 
> > :after treemacs dired
> 
> When first testing this I must've made a mistake, because I thought dired is always loaded, so running things `:after dired` would not have been lazy. That's why treemacs is there as well, and probably why it doesn't work on your end.
> 
> Try removing treemacs from the `:after`. It seems to work on my end.

Can you share your config?? Even after removing treemacs from `:after`, its not working for me.

**Comment by Alexander-Miller** [comment]
Config's below in [this section](https://github.com/Alexander-Miller/dotfiles/blob/master/.config/spacemacs/user-config.org#treemacs). If i change to icons-dired part to

```Elisp
(use-package treemacs-icons-dired
      :after dired
      :load-path "~/Documents/git/treemacs/src/extra"
      :config (treemacs-icons-dired-mode))
```

the icons show up.

**Comment by CSRaghunandan** [comment]
> Config's below in [this section](https://github.com/Alexander-Miller/dotfiles/blob/master/.config/spacemacs/user-config.org#treemacs). If i change to icons-dired part to
> 
> ```emacs-lisp
> (use-package treemacs-icons-dired
>       :after dired
>       :load-path "~/Documents/git/treemacs/src/extra"
>       :config (treemacs-icons-dired-mode))
> ```
> 
> the icons show up.

Strange, I made the same configuration, and they don't show up for me.
Maybe something to do with emacs version i'm running. I'm on emacs 28.0.50 version compiled from git.

**Comment by Alexander-Miller** [comment]
Let's check the version then. Install cask, clone treemacs and run `make clean--start` and evaluate the following:

```Elisp
(add-to-list 'load-path "/treemacs/dired/location")
(autoload 'treemacs-icons-dired-mode "treemacs-icons-dired")
(autoload 'dired-jump "dired-x")
(with-eval-after-load 'dired
  (treemacs-icons-dired-mode)
  (message "LOAD AFTER DIRED"))
(dired-jump)
```

If I do that I see a dired buffer with icons, and the message is displayed as expected.

**Comment by Alexander-Miller** [comment]
Bump?

**Comment by CSRaghunandan** [comment]
Hey @Alexander-Miller 

Looks like I'm no longer seeing this issue with latest treemacs. I'm not really sure which version fixed it, but thanks a lot for your efforts :)
You can close this issue

**Comment by Alexander-Miller** [comment]
:+1:
