### ISSUE TITLE
When calling treemacs-add-project-to-workspace: funcall-interactively: Wrong type argument: arrayp, nil

### ISSUE THREAD

**Issue by xuhdev** [Alexander-Miller/treemacs#617]
- Download this file to an empty directory: https://github.com/pytorch/pytorch/blob/4bcf4796aa68cde64922aa13fbfd2b3111c10526/aten/src/ATen/native/TensorIterator.h
- cd into this directory and generate tags for this file: `ctags -R -e .` (or download a pre-generated TAGS file [here](https://gist.github.com/xuhdev/08151fc261e140f9441a278db903d8ad))
- Open TensorIterator.h in Emacs, and add the directory to workspace
- `M-x treemacs-add-project-to-workspace`, got the error:

      funcall-interactively: Wrong type argument: arrayp, nil

Debug backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  treemacs-add-project-to-workspace("/home/hong/tmp/")
  funcall-interactively(treemacs-add-project-to-workspace "/home/hong/tmp/")
  call-interactively(treemacs-add-project-to-workspace record nil)
  command-execute(treemacs-add-project-to-workspace record)
  counsel-M-x-action("treemacs-add-project-to-workspace")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "treemacs-find-file" "electric-indent-mode" "edebug-defun" "treemacs-version" "prog-mode" "python-mode" "delete-trailing-whitespace" "delete-whitespace-rectangle" "copy-file" "find-tag" "counsel-git" "emacs-version" "add-name-to-file" "delete-file" "list-tags" "magit-pull" "counsel-colors-web" "counsel-ag" "counsel-rg" "spacemacs/counsel-search" "counsel-grep" "revert-buffer" "magit-log-buffer-file" "browse-at-remote" "forge-browse-remote" "counsel-down-directory" "goto-history-element" "previous-history-element" "help" "find-file" "ivy-call-and-recenter" "lsp-treemacs-symbols" "counsel-git-grep" "visit-tags-table" "magit-find-file" "package-install-file" "magit-blame" "evil-insert-state" "counsel-dired-jump" "treemacs-tag-follow-mode" "gnus" "counsel-fzf" "emacs-lisp-mode" "counsel-file-jump" "find-file-at-point" "xref-find-definitions" "package-lint-current-buffer" "customize" "customize-group" ...) :predicate #f(compiled-function (x) #<bytecode 0x1bdf26d>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

**Comment by Alexander-Miller** [comment]
Cannot reproduce on my end, the directory with the project and the TAGS
file is added without issue. The error you see is likely to appear because
some previous action left treemacs' backing dom data structure in an
invalid state. If that is the case the project addition should work if
you quit treemacs with Q and open it again.

It's unlikely, but not impossible, that ivy is involved, so you should
also try disabling it and see if that helps. You should also make sure
that your treemacs is up-to-date - I am constantly in the business of
fixing bugs.

Finally if nothing helps you can try adding the project
non-interactively like this:

`(treemacs-do-add-project-to-workspace "/path/to/project" "Some Name")`

If that part fails it would be *very* useful if you could turn on edebug
and tell me in exactly which line the error is thrown in.

**Comment by xuhdev** [comment]
@Alexander-Miller Thanks. I tried to run `(treemacs-do-add-project-to-workspace "/home/hong/tmp" "tmp")`, and turned on `edebug` for `treemacs-do-add-project-to-workspace`. Once I entered the first line of `treemacs-do-add-project-to-workspace`, i.e., `(treemacs-block`, it seems like that some timer blocked me and printed the following error:

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  apply(debug error (wrong-type-argument arrayp nil))
  edebug(error (wrong-type-argument arrayp nil))
  treemacs--follow-tag-at-point()
  apply(treemacs--follow-tag-at-point nil)
  timer-event-handler([t 0 1 500000 t treemacs--follow-tag-at-point nil idle 0])
  recursive-edit()
  #f(compiled-function (arg-mode) #<bytecode 0x3296325>)(before)
  transient--edebug--recursive-edit(#f(compiled-function (arg-mode) #<bytecode 0x3296325>) before)
  apply(transient--edebug--recursive-edit #f(compiled-function (arg-mode) #<bytecode 0x3296325>) before)
  edebug--recursive-edit(before)
  edebug--display-1(nil 0 before)
  edebug--display(nil 0 before)
  edebug-debugger(0 before nil)
  edebug-before(0)
  (edebug-after (edebug-before 0) 143 (catch (quote --cl-block-__body__--) (edebug-after (edebug-before 1) 5 (if (edebug-after (edebug-before 2) 4 (null (edebug-after 0 3 path))) (progn (throw (quote --cl-block-__body__--) (treemacs-pulse-on-failure (quote ...)))))) (edebug-after (edebug-before 6) 142 (let ((path-status (edebug-after (edebug-before 7) 9 (treemacs--get-path-status ...)))) (edebug-after (edebug-before 10) 16 (if (edebug-after (edebug-before 11) 15 (not ...)) (progn (throw ... ...)))) (edebug-after (edebug-before 17) 21 (setq path (edebug-after (edebug-before 18) 20 (let* ... ...)))) (edebug-after (edebug-before 22) 31 (let ((project ...)) (if project (progn ...)))) (edebug-after (edebug-before 32) 50 (let ((project ...)) (if project (progn ...)))) (edebug-after (edebug-before 51) 141 (let* ((name ...) (project ...)) (edebug-after (edebug-before 65) 69 (if ... ...)) (edebug-after (edebug-before 70) 88 (let ... ...)) (edebug-after (edebug-before 89) 91 (let* ... ...)) (edebug-after (edebug-before 92) 93 (let ... ...)) (edebug-after (edebug-before 94) 132 (let ... ...)) (edebug-after (edebug-before 133) 134 (treemacs--persist)) (edebug-after (edebug-before 135) 137 (run-hook-with-args ... ...)) (edebug-after (edebug-before 138) 140 (list ... ...))))))))
  (closure ((name . "tmp") (path . "/home/hong/tmp") t) nil (edebug-after (edebug-before 0) 143 (catch (quote --cl-block-__body__--) (edebug-after (edebug-before 1) 5 (if (edebug-after (edebug-before 2) 4 (null (edebug-after 0 3 path))) (progn (throw (quote --cl-block-__body__--) (treemacs-pulse-on-failure ...))))) (edebug-after (edebug-before 6) 142 (let ((path-status (edebug-after ... 9 ...))) (edebug-after (edebug-before 10) 16 (if (edebug-after ... 15 ...) (progn ...))) (edebug-after (edebug-before 17) 21 (setq path (edebug-after ... 20 ...))) (edebug-after (edebug-before 22) 31 (let (...) (if project ...))) (edebug-after (edebug-before 32) 50 (let (...) (if project ...))) (edebug-after (edebug-before 51) 141 (let* (... ...) (edebug-after ... 69 ...) (edebug-after ... 88 ...) (edebug-after ... 91 ...) (edebug-after ... 93 ...) (edebug-after ... 132 ...) (edebug-after ... 134 ...) (edebug-after ... 137 ...) (edebug-after ... 140 ...))))))))()
  edebug-enter(treemacs-do-add-project-to-workspace ("/home/hong/tmp" "tmp") (closure ((name . "tmp") (path . "/home/hong/tmp") t) nil (edebug-after (edebug-before 0) 143 (catch (quote --cl-block-__body__--) (edebug-after (edebug-before 1) 5 (if (edebug-after (edebug-before 2) 4 (null ...)) (progn (throw ... ...)))) (edebug-after (edebug-before 6) 142 (let ((path-status ...)) (edebug-after (edebug-before 10) 16 (if ... ...)) (edebug-after (edebug-before 17) 21 (setq path ...)) (edebug-after (edebug-before 22) 31 (let ... ...)) (edebug-after (edebug-before 32) 50 (let ... ...)) (edebug-after (edebug-before 51) 141 (let* ... ... ... ... ... ... ... ... ...))))))))
  edebug-enter(treemacs-do-add-project-to-workspace ("/home/hong/tmp" "tmp") (closure ((name . "tmp") (path . "/home/hong/tmp") t) nil (edebug-after (edebug-before 0) 143 (catch (quote --cl-block-__body__--) (edebug-after (edebug-before 1) 5 (if (edebug-after (edebug-before 2) 4 (null ...)) (progn (throw ... ...)))) (edebug-after (edebug-before 6) 142 (let ((path-status ...)) (edebug-after (edebug-before 10) 16 (if ... ...)) (edebug-after (edebug-before 17) 21 (setq path ...)) (edebug-after (edebug-before 22) 31 (let ... ...)) (edebug-after (edebug-before 32) 50 (let ... ...)) (edebug-after (edebug-before 51) 141 (let* ... ... ... ... ... ... ... ... ...))))))))
  treemacs-do-add-project-to-workspace("/home/hong/tmp" "tmp")
  eval((treemacs-do-add-project-to-workspace "/home/hong/tmp" "tmp") nil)
  elisp--eval-last-sexp(nil)
  #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x2041df>)(nil)
  #f(compiled-function (&rest _it) #<bytecode 0x39bb751>)()
  eval-sexp-fu-flash-doit-simple(#f(compiled-function (&rest _it) #<bytecode 0x39bb751>) #f(compiled-function (&rest args2) #<bytecode 0x4cff41>) #f(compiled-function (&rest args2) #<bytecode 0x4d078d>))
  eval-sexp-fu-flash-doit(#f(compiled-function (&rest _it) #<bytecode 0x39bb751>) #f(compiled-function (&rest args2) #<bytecode 0x4cff41>) #f(compiled-function (&rest args2) #<bytecode 0x4d078d>))
  esf-flash-doit(#f(compiled-function (&rest _it) #<bytecode 0x39bb751>) #f(compiled-function (&rest args2) #<bytecode 0x4cff41>) #f(compiled-function (&rest args2) #<bytecode 0x4d078d>) #f(compiled-function (&rest args2) #<bytecode 0x4d0b9d>))
  ad-Advice-eval-last-sexp(#f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x2041df>) nil)
  apply(ad-Advice-eval-last-sexp #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.\nInteger values are printed in several formats (decimal, octal,\nand hexadecimal).  When the prefix argument is -1 or the value\ndoesn't exceed `eval-expression-print-maximum-character', an\ninteger value is also printed as a character of that codepoint.\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x2041df>) nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by Alexander-Miller** [comment]
>   treemacs--follow-tag-at-point()

You are using tag-follow-mode. It's not the first time I've seen this issue, someone else had the exact same problem with the exact same file just some months ago (or is this your 2nd attempt?). I think the issue is even still open because I got stuck being unable to reproduce the error.

The actual problem is that the mode tries to look up some tag in treemacs, but is somehow unable to find it, and the tag path (e.g. namespace -> class -> function) and the actual info in the dom diverge to the point that things break.

Now on my end even with the tags I only have the default imenu lookup that treemacs also uses as a source. So all I actually see is a DimCounter class, nothing else. You probably have some special setup to let emacs use the tags you have generated. If you can share that part of your config I should be able to track down the root cause of this bug.

**Comment by xuhdev** [comment]
@Alexander-Miller Are you referring to #562 ? I reported there but it was actually fixed for me when you posted https://github.com/Alexander-Miller/treemacs/issues/562#issuecomment-552514816 . I would say this is my attempt for the reemerge of a similar issue (but actually not exactly the same) :) Right now in my timer I'm getting the following error message printed at all time:

    Error running timer ‘treemacs--follow-tag-at-point’: (wrong-type-argument arrayp nil)

If you think it's too difficult to know where the issue might be, maybe I can find some time to bisect.

**Comment by xuhdev** [comment]
@Alexander-Miller I'm also happy to provide you with my configuration. I'm using the develop branch of spacemacs and here's the link to my configuration: https://gist.github.com/xuhdev/4d0a843890dbd079d5be894d618424dd

**Comment by Alexander-Miller** [comment]
I don't see anything tag-related in your config. lsp did bug me to import the tensor file when I opened it after enabling the c++ layer. Do you have a language server running for this stuff?

What tags do you see when you call imenu?

What tags do you see in treemacs (without tag-follow-mode, and the file must be open for all the right hooks to run).

What do you get when you call `(treemacs--get-imenu-index "/path/to/TensorIterator.h")` (again with the file already open)?

**Comment by xuhdev** [comment]
> I don't see anything tag-related in your config. lsp did bug me to import the tensor file when I opened it after enabling the c++ layer. Do you have a language server running for this stuff?

Not for this buffer. I have the following message in `*Message*`:

    LSP :: File /home/hong/tmp/TensorIterator.h is in blacklisted directory /home/hong/tmp/
    LSP :: TensorIterator.h not in project or it is blacklisted.


> 
> What tags do you see when you call imenu?
> 

```
*Rescan*
Class
```

> What tags do you see in treemacs (without tag-follow-mode, and the file must be open for all the right hooks to run).

I see only `DimCounter`.

> 
> What do you get when you call `(treemacs--get-imenu-index "/path/to/TensorIterator.h")` (again with the file already open)?

The following message is printed and the return value is nil:

    Use M-x make-directory RET RET to create the directory and its parents

**Comment by Alexander-Miller** [comment]
> Use M-x make-directory RET RET to create the directory and its parents

Looks like you didn't use the file's proper path. I made that example with a placeholder.

**Comment by xuhdev** [comment]
Ah right...

`(treemacs--get-imenu-index "/home/hong/tmp/TensorIterator.h")` returns 

    (("Class" ("DimCounter" . #<marker at 1906 in TensorIterator.h>)))

**Comment by Alexander-Miller** [comment]
That is also what I am seeing. Looks like you will need to edebug your way through `treemacs--follow-tag-at-point`.  The error should appear somewhere in the start in the `let*` block since most of the function body is wrapped in a `condition-case` that would prevent the stack trace you are seeing.

I also have a mild suspicion about the conditions that are responsible for the bug, so check these 2 things first:

 - What's the output of `(treemacs-is-path "/home/hong/tmp/TensorIterator.h" :in-workspace)`
 - What is the output of `(treemacs-current-workspace)`

The first one must return the right project (e.g. `#s(treemacs-project "pytorch" "/home/a/Documents/pytorch" local-readable)`), the second one must be a a workspace with all your projects, including the one for the tensor file. 

Don't bother with debugging if either is not the case, the real cause must be a bug in how your projects were set up.

**Comment by xuhdev** [comment]
I think previously https://github.com/Alexander-Miller/treemacs/issues/617#issuecomment-582092532 I edebugged the wrong function. I just tried to edebug `treemacs-add-project-to-workspace` in `treemacs-interface.el`, I got the error of

    edebug-signal: Wrong type argument: arrayp, nil

when evaluating `treemacs-current-workspace` on the 4th line of the function. Strangely, edebugging `treemacs-current-workspace` does not trigger the debugger.

**Comment by xuhdev** [comment]
I tried the following using `eval-expression` (`M-:`) when the `TensorIterator.h` buffer was active.

- `(treemacs-is-path "/home/hong/tmp/TensorIterator.h" :in-workspace)` output `let*: Wrong type argument: arrayp, nil`

- `(treemacs-current-workspace)` output `nil`.

**Comment by xuhdev** [comment]
Ah, I figured that I must run `treemacs` first before running `treemacs-add-project-to-workspace` to avoid the issue above! Once I run `treemacs`, the two commands above output expected messages.

But then a different error message comes up... After answering the name of the project, I got the following:

    ht-get: Wrong type argument: hash-table-p, nil

**Comment by Alexander-Miller** [comment]
> Strangely, edebugging treemacs-current-workspace does not trigger the debugger.

An inconvenient side effect of inline functions.

> Ah, I figured that I must run treemacs first before running treemacs-add-project-to-workspace to avoid the issue above! Once

Ah, that is a potentially buggy combination. A workspace is first selected when treemacs is first opened, not just loaded. I'll have to make sure that a workspace is selected as needed.

> But then a different error message comes up... After answering the name of the project, I got the following:

Do you have a full stack trace? With luck it'll be meaningful enough to save on more debugging.

**Comment by xuhdev** [comment]
Here is the stack (turns out this will show up if I have already added the project to workspace)

```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("/home/hong/tmp" nil nil)
  ht-get(nil "/home/hong/tmp")
  treemacs-add-project-to-workspace("/home/hong/tmp/")
  funcall-interactively(treemacs-add-project-to-workspace "/home/hong/tmp/")
  call-interactively(treemacs-add-project-to-workspace record nil)
  command-execute(treemacs-add-project-to-workspace record)
  counsel-M-x-action("treemacs-add-project-to-workspace")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "treemacs-add-project" "edebug-defun" "delete-trailing-whitespace" "browse-at-remote" "magit-log-current" "ff-find-other-file" "visit-tags-table" "counsel-ag" "revert-buffer" "magit-diff" "new-frame" "rename-buffer" "copy-file" "counsel-dired" "counsel-find-file" "chmod" "delete-file" "list-tags" "treemacs" "magit-branch" "magit-run-git-gui-blame" "magit-blame" "magit-find-file" "find-file" "magit-checkout" "company-etags" "xref-etags-mode" "xref-find-references" "find-tag-noselect" "find-tag" "electric-indent-mode" "lsp-mode" "python-mode" "grep" "counsel-git-grep" "c-mode" "flycheck-mode" "restart-emacs" "flyspell-buffer" "magit-stash-apply" "spacemacs/xclipboard-paste" "s" "cd" "5x5" "arp" "dbx" "dig" "erc" "ert" ...) :predicate #f(compiled-function (x) #<bytecode 0x18d96b5>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

```

**Comment by Alexander-Miller** [comment]
Pushed a change to load find a workspace whenever one is needed. Adding projects shouldn't cause trouble now.

**Comment by xuhdev** [comment]
I can confirm the latest version fixed the issue. Thanks!
