### ISSUE TITLE
[Windows Native][Emacs 26.3] Treemacs + Tramp + Plink - something is adding "c:/" to my project paths

### ISSUE THREAD

**Issue by reverent-lapwing** [Alexander-Miller/treemacs#618]
# Bug report

## Setup

OS: Windows 7
Emacs: Emacs 26.3 (build 1, x86_64-x64-mingw32)
Treemacs: Treemacs v2.7

## Description

For some reason `treemacs--canonical-path` turns valid plink paths into local windows paths on drive `C:\`. This causes problems with `treemacs--restore` as well as `treemacs--persist`. Wrong path is stored in `treemacs--persist-file` and irregardless of value in this file, the loaded path is always transformed and stored back as a local path.

## Steps to reproduce

1. [In treemacs buffer] M-x treemacs-add-project-to-workspace RET
2. Enter path to a directory on remote server (ex. "/plink:username@host:/home/username/example")
3. Enter any project name
4. Error is displayed: "Project <project name> at c:/plink:username@host:/home/username/example cannot be read.

# Workaround

I haven't found proper solution yet, however this change allowed me to use treemacs without problem until the patch is released. When solution is found, I would be happy to help with testing changes.

File: `treemacs-persistance.el`
Line: L123

```diff
+++ treemacs-persistance.el new
--- treemacs-persistance.el old
@@ -123,1 +123,1 @@
+                 (setf (treemacs-project->path project) val))
-                 (setf (treemacs-project->path project) (treemacs--canonical-path val)))
```

I tried adding code equivalent to `(replace-regexp "c:/plink:" "/plink:" path)` to `treemacs--canonical-path` but to no avail.

## Update

It seems that the fix above works only for storing and loading paths to projects, however some functionality still breaks (ex. creating file), so I redefined `treemacs--canonical-path` to identity altogether. Still doesn't work. I will resort to using dired-mode when possible and report further issues as they come up.

**Comment by Alexander-Miller** [comment]
The canonical-path code is very small, so if we determine which part changes the path we can fix it for the other cases:

```Elisp
(let (file-name-handler-alist)
       (-> PATH (expand-file-name) (treemacs--unslash)))
```
My money's on the file-handler, in which case I can make an exception for windows (I'm not even sure why it's there in the first place).

**Comment by Alexander-Miller** [comment]
Bump?

**Comment by Alexander-Miller** [comment]
Closing on account of inactivity.
