### ISSUE TITLE
Properly handle directory symlinks

### ISSUE THREAD

**Issue by vsemyonoff** [Alexander-Miller/treemacs#622]
When trying to open symlink to directory in project tree:
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  treemacs--reentry("/home/svlad/.local/var/lib/qemu" nil)
  treemacs--expand-dir-node(#<marker (moves after insertion) at 40 in  *Treemacs-Scoped-Buffer-#<frame emacs@vladxps01 0x55ea9b26f2e0>*> :recursive nil)
  treemacs-toggle-node(nil)
  treemacs-RET-action(nil)
  funcall-interactively(treemacs-RET-action nil)
  call-interactively(treemacs-RET-action nil nil)
  command-execute(treemacs-RET-action)
```
Any ideas?

**Comment by Alexander-Miller** [comment]
Investigating.

**Comment by Compro-Prasad** [comment]
If this symlink is outside project then a confirmation should be made before following the symlink. The user can remove this confirmation using a simple configuration variable like `treemacs-follow-non-project-symlinks`.

**Comment by Alexander-Miller** [comment]
Should be fixed now. Hopefully without breaking anything else.

> If this symlink is outside project then a confirmation should be made before following the symlink. 

IMO that's overkill. What would that confirmation accomplish, other than being a mild inconvenience?

**Comment by vsemyonoff** [comment]
It works fine now, thank you ))
