### ISSUE TITLE
how to exclude icons from being picked up in swiper for treemacs

### ISSUE THREAD

**Issue by CSRaghunandan** [Alexander-Miller/treemacs#625]
This causes slight annoyance as `swiper` search will be slower as it'll include all the icons in `treemacs-icons-dired-mode` and `treemacs`. Is there anyway I can stop this from happening?

**Comment by Alexander-Miller** [comment]
I'm afraid that is not possible. The icons are nothing more than normal text with a special `display` property, they are part of the buffer just as any other string. You would need to extend the search mechanism to ignore certain text properties, but that would be slow also and unlikely to help.

In fact are you sure it's the icons slowing things down? In my experience dired's major-mode mode-line segment is very slow when scrolling and searching. It shows the total numbers of files in the current directory and which file point is on in a form like "Dired/name 15/76" and appears to recalculate that on every move.

**Comment by CSRaghunandan** [comment]
> In fact are you sure it's the icons slowing things down? In my experience dired's major-mode mode-line segment is very slow when scrolling and searching. It shows the total numbers of files in the current directory and which file point is on in a form like "Dired/name 15/76" and appears to recalculate that on every move.

I tried turning off the `treemacs-icons-dired-mode` and searching in swiper seems to be faster and I use `doom-modeline` and in it, it doesn't play much apart from the directory name in the mode-line. So, I'm not sure if its doing the recalculations as when you have normal mode-line. 

Also, in swiper search, the correct icons are not displayed, and only on the current line, the correct icon is displayed. So, when I scroll over the lines, it makes for a jarring UX where the icons keep changing for the currrent line. I don't know why this is happening. Are you able to reproduce this?

**Comment by Alexander-Miller** [comment]
> I tried turning off the treemacs-icons-dired-mode and searching in swiper seems to be faster

That is unfortunate, but there is nothing I can do about it. The icons are part of the content of the buffer, and will be picked up by whatever search function you use.

> Are you able to reproduce this?

No, the icons behave as expected on my end: https://imgur.com/a/95kZLsq
Using doom's treemacs theme works as well.

**Comment by CSRaghunandan** [comment]
> > I tried turning off the treemacs-icons-dired-mode and searching in swiper seems to be faster
> 
> That is unfortunate, but there is nothing I can do about it. The icons are part of the content of the buffer, and will be picked up by whatever search function you use.

I see. 


> > Are you able to reproduce this?
> 
> No, the icons behave as expected on my end: https://imgur.com/a/95kZLsq
> Using doom's treemacs theme works as well.


This seems to be a problem only when using `treemacs-icons-dired-mode`, please check the same on a dired buffer. On `treemacs` window, it seems to be fine.

**Comment by Alexander-Miller** [comment]
Dired is working as well: https://imgur.com/a/C2LiiZW Both with default spacemacs (no dired+), my own config and clean start loading nothing but swiper and treemacs.
I have updated my swiper yesterday, so an old version is not the problem.

Sounds like you need to bisect your own config.

**Comment by CSRaghunandan** [comment]
> Dired is working as well: https://imgur.com/a/C2LiiZW Both with default spacemacs (no dired+), my own config and clean start loading nothing but swiper and treemacs.
> I have updated my swiper yesterday, so an old version is not the problem.
> 
> Sounds like you need to bisect your own config.

I see. Strangely, its working fine when using the default-theme for treemacs. I guess I will shift to using the default theme for treemacs for now.
