### ISSUE TITLE
Not-deleting still removes

### ISSUE THREAD

**Issue by passeride** [Alexander-Miller/treemacs#629]
So when i delete a file "index.tsx" and presses "no" on delete and "no" on kill buffer, it's still removed from treemacs view, it comes back when i refresh as it's not acually removed. 

Probably a trivial issue to fix. 
Might take a look at it if i have time .

**Comment by Alexander-Miller** [comment]
Looks like a misplaced return statement somewhere. I'll look into it.

**Comment by ayrat555** [comment]
I have the same problem. And since I do almost all my file management in emacs (neotree before, now treemacs). it's really annoying issue to me.

But this issue aside. @Alexander-Miller  Thanks for your hard work on the project. It's great!
