### ISSUE TITLE
How to bind l to treemacs-RET-action?

### ISSUE THREAD

**Issue by taigacute** [Alexander-Miller/treemacs#630]
I most like the behavior of `l` is `treemacs-RET-action`, because the `l` of my vim conf do this.

**Comment by Alexander-Miller** [comment]
Either

`(define-key treemacs-mode-map (kbd "l") #'treemacs-RET-action)`

or if you use evil 

`(evil-define-key 'treemacs treemacs-mode-map (kbd "l") #'treemacs-RET-action)`

**Comment by taigacute** [comment]
I tried this but failed...

**Comment by Alexander-Miller** [comment]
Tried how?
