### ISSUE TITLE
[feature request] Fuzzy searching mode for treemacs

### ISSUE THREAD

**Issue by Rareform** [Alexander-Miller/treemacs#631]
Hello, I like your treemacs mode and have a proposal how to make it even better.
[My question going in this direction](https://emacs.stackexchange.com/questions/54410/use-helm-fuzzy-search-inside-ranger-inside-spacemacs).
From what I've understood treemacs has no direct connection with ivy or helm. What I would like to see for some file browser is a fuzzy search mode. When activated by some key you should have a small mini buffer similar to that of ivy or helm (it could be also implemented using one of those). In this buffer you should be able to see all the depicted folder and files currently present in the left treemacs panel as candidates. Fuzzy searching, marking some of them and pressing enter should then collapse or uncollapse the marked directories depending on their current state (uncollapse, if collapsed and vice versa). The mode should be also deactivatable by some key sequence.

It could be that this a highly nontrivial issue, as I am not familiar with treemacs implementation, but it would be cool.

**Comment by Alexander-Miller** [comment]
Marking and then collapsing stuff is pretty much a no-go, it's not just difficult, it'd also only be possible with some specialized helm interface.

But a general fuzzy-matched go-to implementation for helm/ivy etc is simple to do, I'd just have to plug into Emacs' imenu interface.

**Comment by Rareform** [comment]
Looking soberly at it, marked candidates might indeed be an overkill. General fuzzy searching would be appreciated. You have already a collapse function, which toggles collapsing and uncollapsing by pressing enter on some node. Collapsing a single node via imenu would be possible or not?

**Comment by andreyorst** [comment]
I'm trying to imagine a use case for such feature, as collapsing and uncollapsing directories using fuzzy search, and can't think of one. However I occasionally use fuzzy searching in Treemacs to locate files without need to unfold anything, by using `project.el` functions `project-find-file` and `project-find-regexp`

Maybe having similar functions that will allow to search over multiple projects in projectile would be a thing?

**Comment by Compro-Prasad** [comment]
@Rareform Try using `project-find-file` or `projectile-find-file`. Treemacs doesn't need to do everything. It shows sidebar file explorer and does a good job at it.

**Comment by Rareform** [comment]
`projectile-find-file` works great, didn't know you could use it inside treemacs. Well, the collapsing and uncollapsing directory with fuzzy search would be cool because you alter the tree visually and don't just use the minibuffer. But the shortcuts `j`, `k`, `tab` work good enough and I think the use cases are quite limited, which is why I am going to close my proposal.

**Comment by Alexander-Miller** [comment]
> projectile-find-file works great, didn't know you could use it inside treemacs.

Plenty of commands can be used with treemacs like this. See https://github.com/Alexander-Miller/treemacs#current-directory-awareness.

> But the shortcuts j, k, tab work good enough

There's plenty more keybinds for navigation to next neighbour, next project, parent etc.

I'm pretty sure I still have a ticket for imenu support somewhere that I intend to implement, so fuzzy
navigation will come around eventually.
