### ISSUE TITLE
 New Feature: natural sort

### ISSUE THREAD

**Issue by KVAnton-WEB** [Alexander-Miller/treemacs#632]
I suggest adding **natural sorting** to possible default options.
I know that I can write custom sort function, but I am not an advanced programmer for Lisp/elisp and don't have enough time now.

#### Now for alphabetic-asc:
* foo1.bar
* foo10.bar
* foo2.bar

#### What I would like to have for  alphabetic-natural-asc:
* foo1.bar
* foo2.bar
* foo10.bar

**Comment by Alexander-Miller** [comment]
I have good news and bad news.

The good news is that I can do implement this, and probably even improve general performance to some degree.

The bad news is that it requires a thorough rewrite of the "get and sort all the files and directories in some given path" part of treemacs so it might take a bit until I'm sure it's good and stable. Might not always be available either as I have to dive pretty deeply into the dark magic dired is practicing with `ls`.

**Comment by Alexander-Miller** [comment]
Stayin alive.
