### ISSUE TITLE
open external not working

### ISSUE THREAD

**Issue by wnkw** [Alexander-Miller/treemacs#633]
Hi, thanks for your great work, I love treemacs.

Unfortunately one thing is not working for me. The problem is `(treemacs-visit-node-in-external-application)` is not doing what it's supposed to. When I press `o x` or call the function with `M-x (treemacs-visit-node-in-external-application)` I see an icon jumping near my mouse cursor indicating that a program will be opened but nothing happens. I am on linux (with KDE if that's important). I use spacemacs develop (commit `83fbc7a13`).

**Comment by Alexander-Miller** [comment]
On Linux treemacs will try to open things using `xdg-open`. Can you open the file like this from the shell? Does it not work for all files, or just those for a specific type or in a specific project?

**Comment by iskna** [comment]
Thanks for your reply. I can open any file from the shell using `xdg-open`. Even more when I open a directory in treemacs with `o o` which results in a `dired` buffer I can still open any file from `dired` with `W` (which is bound to `(browse-url-of-dired-file)`).

**Comment by Alexander-Miller** [comment]
Try this version:

```Elisp
(defun treemacs-visit-node-in-external-application ()
  "Open current file according to its mime type in an external application.
Treemacs knows how to open files on linux, windows and macos."
  (interactive)
  ;; code adapted from ranger.el
  (-if-let (path (treemacs--prop-at-point :path))
      (pcase system-type
        ('windows-nt
         (declare-function w32-shell-execute "w32fns.c")
         (w32-shell-execute "open" (replace-regexp-in-string "/" "\\" path t t)))
        ('darwin
         (shell-command (format "open \"%s\"" path)))
        ('gnu/linux
	 (pfuture-new "xdg-open" (shell-quote-argument path)))
        (_ (treemacs-pulse-on-failure "Don't know how to open files on %s."
             (propertize (symbol-name system-type) 'face 'font-lock-string-face))))
    (treemacs-pulse-on-failure "Nothing to open here.")))
```

**Comment by iskna** [comment]
This doesn't seem to change anything :(
I also found out that when I open emacs in terminal (ie `emacs -nw`) I can open nodes externally using both versions of the function.

**Comment by Alexander-Miller** [comment]
I've tried opening pdfs with okular on xfce and didn't have any problems. Since it does come down to something KDE specific I don't think there's anything I can do here.

**Comment by Zalewa** [comment]
_Always sorry to be a necromancer but I've found a workaround for myself and since the link to this issue pops up as the first result in a Google search for "treemacs external open" I think that maybe someone else will also benefit from this._

Basing on `treemacs-20210524.1338`:

```diff --git a/treemacs-interface.el.bak b/treemacs-interface.el
index 527eff5..ddde4a3 100644
--- a/treemacs-interface.el.bak
+++ b/treemacs-interface.el
@@ -370,7 +370,7 @@ Treemacs knows how to open files on linux, windows and macos."
          (shell-command (format "open \"%s\"" path)))
         ('gnu/linux
          (let ((process-connection-type nil))
-           (start-process "" nil "xdg-open" path)))
+           (start-process "" nil "sh" "-c" "xdg-open $0 ; sleep 1" path)))
         (_ (treemacs-pulse-on-failure "Don't know how to open files on %s."
              (propertize (symbol-name system-type) 'face 'font-lock-string-face))))
     (treemacs-pulse-on-failure "Nothing to open here.")))
```
Unfortunately I can't provide an explanation for this solution other than a guess that there is a race-condition where Emacs kills the spawned processes while they're still starting up. I gained the idea from this StackOverflow answer: https://askubuntu.com/a/1124455

My OS is Kubuntu 20.04.

**Comment by Alexander-Miller** [comment]
I've pushed that change to master, so hopefully that piece of trouble is now solved for good.
