### ISSUE TITLE
Inverted orizontal and vertical split

### ISSUE THREAD

**Issue by joshuachp** [Alexander-Miller/treemacs#634]
When opening a file with vertical or horizontal split the file is opened with the wrong split. The vertical split the window in one above and one below and the horizontal one on the left and one on the right and one on the left.

I don't know if this is intended, but wouldn't it be better the other way around having the "spit line" horizontal or vertical?

**Comment by Alexander-Miller** [comment]
I based the split behavior is based on i3wm.  I thought i3 was weird as well, but then I guess I got used to it. This does seem to be a pretty universal point of contention however, so consider me convinced into changing it.
