### ISSUE TITLE
clojure-mode breaks workspace loading

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#635]
It seems that `desktop-save-mode` breaks Treemacs ability to read `treemacs-persist` in some way. 

I'm working on a minimal reproducible example.

The behavior is extremely similar to #431

**Comment by andreyorst** [comment]
This seem to happen when I start [cider](https://cider.mx/) REPL. After that restarting emacs bugs Treemacs

**Comment by andreyorst** [comment]
Here's minimal `init.el`:

```emacs-lisp
(defvar package-archives)
(setq package-archives
      '(("gnu" . "https://elpa.gnu.org/packages/")
        ("melpa" . "https://melpa.org/packages/")))

(package-initialize)

(unless (or (package-installed-p 'treemacs)
	    (package-installed-p 'cider))
  (package-refresh-contents)
  (package-install 'treemacs)
  (package-install 'cider))

(require 'treemacs)
(require 'cider)

(add-hook 'after-init-hook #'treemacs)

(desktop-save-mode t)
```

You'll need [clojure](https://clojure.org/) and [leiningen](https://leiningen.org/) installed though. Steps:

- create project with `lein new app bug`
- open emacs with provided `init.el`. Treemacs will ask you to add project, add this `bug` directory and use default name Treemacs suggests.
- Open `bug/src/bug/core.clj` file
- `M-x cider RET cider-jack-in-clj RET`
- once REPL started exit Emacs with `C-x C-c`. Emacs will ask if you want to save desktop, answer yes
- launch Emacs

Treemacs will ask to add project again.

Interestingly though if you remove `after-init` hook it works fine. If you do not use `cider` it also works fine.

**Comment by andreyorst** [comment]
I've found a simpler way. You can probably skip installation of clojure and leiningen. With this `init.el`:

```emacs-lisp
(defvar package-archives)
(setq package-archives
      '(("gnu" . "https://elpa.gnu.org/packages/")
        ("melpa" . "https://melpa.org/packages/")))

(package-initialize)

(unless (or (package-installed-p 'treemacs)
	    (package-installed-p 'cider))
  (package-refresh-contents)
  (package-install 'treemacs)
  (package-install 'cider))

(require 'treemacs)
(require 'cider)

;; (add-hook 'after-init-hook #'treemacs)

(desktop-save-mode t)
```

Follow these steps:
- `mkdir -p bug/src/bug; touch bug/src/bug/core.clj`
- start emacs with empty `.emacs.d` that contains only this `init.el`, wait til emacs installes everything
- add `bug` project in Treemacs upon installation
- Navigate to `core.clj` and open
- Close emacs saving workspace
- open emacs, `core.clj` should be opened by workspace-save-mode
- `M-x treemacs RET`

Threemacs will promt to add project.

It seems that combination of cider and workspace-save-mode make Treemacs forget about it's projects

**Comment by andreyorst** [comment]
Here's a recording of steps described above:

https://asciinema.org/a/8rvhVEDSEMnrFZjJjj2nDU0Cj

**Comment by andreyorst** [comment]
It seems that if I load `desktop-save-mode` with `after-init-hook` the issue is not reproducible. So I have to fully load Treemacs before `desktop-save-mode`

**Comment by Alexander-Miller** [comment]
> Close emacs saving workspace

Before this step what do you see in `treemacs-persist-file` if you manually call `treemacs--persis`?

What do you see there after you quit emacs?

**Comment by andreyorst** [comment]
Once I've added project I see this:

```
* Default
** bug
 - path :: ~/bug
```

- Once I open file `core.clj` I see the same contents.
- After exit, the contents are the same.
- After I open emacs again the contents are still the same.
- Once I open Treemacs it's still there, but Treemacs asks to create the project and contents are destroyed. It seems that this happens only if the last buffer that was restored by `desktop-save-mode` was `core.clj`

`treemacs--persist` function shows `t` or `nil` depending on the buffer I call it in

**Comment by Alexander-Miller** [comment]
> After I open emacs again the contents are still the same.

Are they still there if you just `(require 'treemacs)` without opening it? What do you see when you call `treemacs--read-persist-lines`?

**Comment by andreyorst** [comment]
> Are they still there if you just `(require 'treemacs)`

Yes

> What do you see when you call `treemacs--read-persist-lines`?

    ("* Default" "** bug" " - path :: ~/bug")

**Comment by Alexander-Miller** [comment]
Ok, so reading works. Let's see what validation and transformation do. Assuming you save those `lines` what do the following output:

 - `(treemacs--should-not-run-persistence?)`
 - `(treemacs--validate-persist-lines lines)`
 - `(treemacs--read-workspaces (make-treemacs-iter :list lines))`

**Comment by andreyorst** [comment]
> Ok, so reading works. Let's see what validation and transformation do. Assuming you save those `lines` what do the following output:
> 
> * `(treemacs--should-not-run-persistence?)`

    nil

> * `(treemacs--validate-persist-lines lines)`

If called while `core.clj` is active buffer:

    (error "** bug" #("Project name must be followed by path declaration" 0 49 (face warning)))

If called while `*Messages*` is active buffer

    success

> * `(treemacs--read-workspaces (make-treemacs-iter :list lines))`

If invoked while `core.clj` is active buffer:

    [Treemacs] Project bug has no path and will be ignored.
    (#s(treemacs-workspace "Default" nil))

If invoked while `*Messages*` is active buffer:

     (#s(treemacs-workspace "Default" (#s(treemacs-project "bug" "/home/andreyorst/bug" local-readable))))

**Comment by andreyorst** [comment]
I've tested, and this happens without `save-desktop-mode`. So my initial assumption was not correct.

**Comment by Alexander-Miller** [comment]
Ok, I'll investigate what clojure-mode is up to.

> I've tested, and these errors from previous tests happen without save-desktop-mode

Treemacs is exempt from desktop-save-mode. Dealing with the restoration of treemacs' buffer to frame was ultimately more trouble than it was worth.

**Comment by andreyorst** [comment]
Also, `treemacs--read-persist-lines` actually fails if clojure buffer is active. Previously I've used this with `*scratch*` buffer, and it works there in the same session. So it seems that `cider` and `Treemacs` have some conflict

**Comment by andreyorst** [comment]
> Treemacs is exempt from desktop-save-mode. Dealing with the restoration of treemacs' buffer to frame was ultimately more trouble than it was worth.

I've noticed that, and that's why I'm calling `desktop-save-mode` after `treemacs` in my configuration. Though this seem nothing to do with this issue, as we've found out that it happens without `desktop-save-mode`

**Comment by andreyorst** [comment]
@Alexander-Miller Should I rename the issue?

**Comment by Alexander-Miller** [comment]
Sure.

**Comment by andreyorst** [comment]
Ahem. It's not `cider` but `clojure-mode`. `cider` depends on it, so minimal init.el is this:

```emacs-lisp
(defvar package-archives)
(setq package-archives
      '(("gnu" . "https://elpa.gnu.org/packages/")
        ("melpa" . "https://melpa.org/packages/")))

(package-initialize)

(unless (or (package-installed-p 'treemacs)
	    (package-installed-p 'clojure-mode))
  (package-refresh-contents)
  (package-install 'treemacs)
  (package-install 'clojure-mode))

(require 'treemacs)
(require 'clojure-mode)
```

**Comment by Alexander-Miller** [comment]
Turns out clojure-mode's syntax table was interfering with treemacs' regexes. Problem should be fixed now.
