### ISSUE TITLE
Error in treemacs-TAB-action

### ISSUE THREAD

**Issue by Sasanidas** [Alexander-Miller/treemacs#637]
Hello.
It seems like when I tried to use treemacs-TAB-action, it show me an error: 
```lisp
treemacs-TAB-action: Wrong type argument: listp, #(" 	" 1 2 (face (:family "github-octicons" :height 1.44 :inherit doom-themes-treemacs-root-face) font-lock-face (:family "github-octicons" :height 1.44 :inherit doom-themes-treemacs-root-face) display (raise -0.12) rear-nonsticky t))

```
I found that this is because it tries to use the car function for a string in the treemacs--evade-image function:
```lisp
(car (get-text-property (point) 'display))
```
The solution i found was use car-safe instead of car, and doesn't trigger the error anymore.
I don't know if is the right solution, but, i can make a merge request if it is the right case.
Thank you!

**Comment by Alexander-Miller** [comment]
The solution is right and implemented, so unless I missed as spot all you need to do is update.

**Comment by Sasanidas** [comment]
Oh, ok no problem then.
Thank you.
