### ISSUE TITLE
Is there a way to open the currently highlighted directory within Treemacs buffer in a file manager, e. g., Nautilus?

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#638]
Could I bind a key that opens the currently highlighted directory node in the operating system's file manager say GNOME Files/Nautilus?

**Comment by Alexander-Miller** [comment]
Somewhat. `ox` will open nodes in an external application, for directories that's your file manager, for files your $editor. If you want something like opening the current file's containing directory in a file manager you'll need a custom solution.

**Comment by simurgh9** [comment]
Okay, I figured this out. On a tangent, is there a way to open the current directory's location in eshell?

**Comment by yyoncho** [comment]
@simurgh9 `shell-pop` should do

**Comment by Alexander-Miller** [comment]
Any terminal package that starts based on the `default-directory` should work. I have tested `vterm`, `ansi-term` and `eshell` and they all do just that.
