### ISSUE TITLE
treemacs-edit-workspaces should allow non-existing folders

### ISSUE THREAD

**Issue by zoechi** [Alexander-Miller/treemacs#639]
I use qubes-os and frequently drop and recreate my development VMs.
When I do this not all source repositories are checked out at first.
I clone them on demand. 

When I start Emacs the first time, it asks me about missing projects and I chose to keep them (would be nice if there were a "keep all" option instead of accepting every single one individually)

When I now want to check out a project to a different location than I had in my last VM 
I call treemacs-edit-workspaces to fix the path, but I can't accept the changes without removing all other projects that are not yet checked out.

This is IMHO inconsistent with the way it allows to accept on startup.

Also it would be nice if `C-c C-c` would show all errors at once instead of just the next one, and after fixing the next one, asf

**Comment by Alexander-Miller** [comment]
> Also it would be nice if C-c C-c would show all errors at once 

Maybe, but that would mean I'd have to write some kind of Real capital R parser, required some capital E Effort. It might work for semantic issues like missing files, but a broken syntax will most likely just lead to follow-up-error weirdness. So I don't think this is worth it.

> would be nice if there were a "keep all" option instead of accepting every single one individually

This I can add. Couple that with a config option to ignore missing-file errors and I think you should be covered.

https://github.com/Alexander-Miller/treemacs/issues/543 might also be mildly relevant, once it's implemented.

**Comment by zoechi** [comment]
> some capital E Effort

It would be nice but, if it's not easy it's better to forget about it.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by zoechi** [comment]
I just stumbled upon the `COMMENT` feature, but even projects in workspaces marked as comment or projects marked as comment are validated

**Comment by Alexander-Miller** [comment]
> I just stumbled upon the COMMENT feature, but even projects in workspaces marked as comment or projects marked as comment are validated

I've removed this validation for projects that are ignored now. 
If you want to keep all projects that treemacs cannot read on startup you can set `treemacs-missing-project-action` to `keep`.

Does that cover you use-case?

**Comment by zoechi** [comment]
@Alexander-Miller To be able to commit the workspace config to my shared Emacs config, I have all my projects listed in the workspace file. I access only a subset on each VM though.

I don't think COMMENT wouldn't really help.
I posted a comment about it because I found it weird that Treemacs even enforces such entries to be valid.  
It would still force me to modify the config in each VM in a way that I can not commit.

I switched away from workspace config and enabled Treemacs to follow the current directory.
This works well enough.
Workspaces would still be nice for the bigger projects though.

**Comment by Alexander-Miller** [comment]
> I posted a comment about it because I found it weird that Treemacs even enforces such entries to be valid.

That's also removed now.

>  Workspaces would still be nice for the bigger projects though.

Could you create multiple workspaces for the different projects layouts you have?

**Comment by zoechi** [comment]
| That's also removed now.

Great news :rocket: 

| Could you create multiple workspaces for the different projects layouts you have?

Yes, that would work for me.

**Comment by Alexander-Miller** [comment]
Great, then it sounds like this issue is resolved now :+1: .
