### ISSUE TITLE
[Extension] treemacs extensions cause cursor move in different buffer 

### ISSUE THREAD

**Issue by yyoncho** [Alexander-Miller/treemacs#642]
To reproduce: load the Extension.org and do `showcase-display-buffer-list`. Delete the window displaying the extension and execute:

``` 
(with-current-buffer "*Showcase Buffer List*"
  (treemacs-update-node '(:custom Buffers) t))
```

Actual: the cursor moves in the current buffer.
Expected: the cursor does not move in the current buffer.

**Comment by Alexander-Miller** [comment]
Confirmed and investigating.
