### ISSUE TITLE
[feature request] implement treemacs-icons-ivy

### ISSUE THREAD

**Issue by dinkonin** [Alexander-Miller/treemacs#646]
Hello, I'm a big fan of treemacs-icons-dired mode, and the treemacs iconset in general. Could treemacs icons be used in ivy similar to the `all-the-icons-ivy` package. 

Thank you for your work.

**Comment by yyoncho** [comment]
Off-topic: just a heads up for @Alexander-Miller - I am working for the same but for helm.

**Comment by Alexander-Miller** [comment]
I wouldn't mind giving it a try.

> I am working for the same but for helm.

Neat!

**Comment by yyoncho** [comment]
@Alexander-Miller FYI https://github.com/yyoncho/helm-treemacs-icons/

**Comment by Alexander-Miller** [comment]
You are running into the icon background problem described here: https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-icons.el#L33

I have no general solution, and I'm not sure how feasible it would be, but you can have a look at the 2 workarounds I have implemented:
 - https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-visuals.el#L65
 - https://github.com/Alexander-Miller/treemacs/blob/master/src/extra/treemacs-icons-dired.el#L94

**Comment by Alexander-Miller** [comment]
Stayin alive.
