### ISSUE TITLE
`y f new-file-name` answers “Opening output file: No such file or directory”

### ISSUE THREAD

**Issue by Ekleog** [Alexander-Miller/treemacs#647]
As stated in the title, trying to copy a file to another file name in the same directory leads to a no such file or directory error (using helm, maybe that's relevant?)

In the same way, `m` doesn't allow me to move a file to another name in the same directory.

Currently, I'm just using `ansi-term` to do that kind of file management, but it'd be great to do it via treemacs.

Am I missing something obvious?

**Comment by Alexander-Miller** [comment]
Works on my end, so it must be some edge case you are running into. Try again with debug-on-error enabled, I'll need to see the stack trace for this.

**Comment by Alexander-Miller** [comment]
Other than a buttload of sanity-checking the actual copy process comes down to calling `(f-copy "/source/file" "/destination/file")`. Try doing that manually, maybe this isn't even a treemacs-specific problem.

**Comment by Ekleog** [comment]
Hmm… I have no idea (yet?) about how to use the debug mode of emacs, but here is the stack trace:
```lisp
(file-missing "Opening output file" "No such file or directory" "/home/ekleog/prog/fun-tamarin/test.spthy/request-response.spthy")
  copy-file("/home/ekleog/prog/fun-tamarin/request-response.spthy" "/home/ekleog/prog/fun-tamarin/test.spthy/")
  f-copy("/home/ekleog/prog/fun-tamarin/request-response.spthy" "/home/ekleog/prog/fun-tamarin/test.spthy/")
  treemacs--copy-or-move(:copy)
  treemacs-copy-file()
  funcall-interactively(treemacs-copy-file)
  call-interactively(treemacs-copy-file nil nil)
  command-execute(treemacs-copy-file)
```

I think the issue comes from the `/` at the end of the `f-copy` second argument. I'm not sure how treemacs calls the file picker for copy, but it probably ends up with helm assuming it wants a directory, and thus returning a `/` at the end?

**Comment by Alexander-Miller** [comment]
I've refactored the relevant code,so let's try again now. At the very least the problem will be easier to debug.

**Comment by Alexander-Miller** [comment]
Bump?

**Comment by Ekleog** [comment]
Sorry for the delay! I have installed treemacs from my distro's packages, and, still being pretty new to emacs and especially elisp, I don't really know how to install emacs packages outside of them / from source, so I can't really test. Should we close this until the distro packages catch up, so this could get off of your radar in the meantime? :)

**Comment by Alexander-Miller** [comment]
There's a distro package for treemacs? Now that's new. I don't know how
often these things are updated, so it may well be that you are on a
pretty old version.

 > I don't really know how to install emacs packages outside of them /
 > from source

That's easy enough. You'll need about 10 lines to set up MELPA and
`use-package` and you're good to go:
http://cachestocaches.com/2015/8/getting-started-use-package/

The readme has an example how to install treemacs with use-package.

 > Should we close this until the distro packages catch up, so this could
 > get off of your radar in the meantime? :)

Yes, let's do that.

**Comment by Ekleog** [comment]
Well, NixOS gets a MELPA import semi-regularly: according to `M-x package-list-packages`, my version is `20200103.1907` -- what I'm far from sure about is whether that MELPA import will get updated before 20.09 or not. So I'll still have to try getting a development version of treemacs running locally by having installing from a local MELPA :)

**Comment by Alexander-Miller** [comment]
You don't need a whole local MELPA just for treemacs. Cloning it and
adding a `:load-path` argument to use-package will work just as well.
