### ISSUE TITLE
Latest update seems to have issues with doom-themes-treemacs-config

### ISSUE THREAD

**Issue by zoechi** [Alexander-Miller/treemacs#649]
Since today (probably after I installed package updates) as soon as I have a directory expanded in Treemacs that contains Dart source files, Emacs becomes horribly slow with 100% CPU usage (removing dart-mode and lsp-mode didn't help)

```
- command-execute                                               73626  99%
 - call-interactively                                           73626  99%
  - funcall-interactively                                       73626  99%
   - swiper                                                     64680  87%
    - ivy-read                                                  64593  87%
     - read-from-minibuffer                                     64543  87%
      + ivy--queue-exhibit                                        356   0%
      + url-http-generic-filter                                   321   0%
        mouse-fixup-help-message                                   16   0%
      + redisplay_internal (C function)                            11   0%
      + timer-event-handler                                         8   0%
        tooltip-show-help                                           1   0%
      + minibuffer-inactive-mode                                    1   0%
      + command-execute                                             1   0%
    + swiper--candidates                                           85   0%
   + counsel-M-x                                                 8911  12%
   + next-line                                                     30   0%
   + previous-line                                                  3   0%
   + handle-focus-out                                               1   0%
   + profiler-report-toggle-entry                                   1   0%
+ ...                                                             351   0%
+ mouse-fixup-help-message                                         52   0%
+ timer-event-handler                                              27   0%
+ redisplay_internal (C function)                                  25   0%
+ url-http-generic-filter                                           8   0%
+ winner-save-old-configurations                                    3   0%
+ tooltip-show-help                                                 2   0%
  yas--post-command-handler                                         1   0%
+ nsm-verify-connection                                             1   0%
  internal-echo-keystrokes-prefix                                   1   0%
```
I tried with Elm, TypeScript, and Rust projects, but couldn't reproduce, but I can reliably reproduce in ~10 directories containing Dart files.

```list
(use-package
  doom-themes
  :ensure t
  :init
  (setq doom-themes-enable-bold t ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled
  (load-theme 'doom-one t)

  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config) 

  (setq doom-themes-treemacs-theme "doom-colors") ; use the colorful treemacs theme
  (doom-themes-treemacs-config) ;; !!! this line causes the performance issue !!!

  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config)
  )
```
```
GNU Emacs 28.0.50 (build 4, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2020-04-03
```

Any ideas?

**Comment by Alexander-Miller** [comment]
I cannot reproduce it locally, so it must be caused by some combination of things on your end.

There is nothing dart-specific in both treemacs and doom-themes, lsp-dart on the other hand recently announced a new version making use of treemacs for its tree views: https://www.reddit.com/r/emacs/comments/g0qax2/announcement_lspdart_130_released/. So for me this is the most likely culprit.

The profiler is suspiciously inconclusive. Is it actually just Emacs burning your CPU? It could be some bad loop with the dart language server.

There was a similar issue some time ago that basically triggered an infinite loop that treemacs was involved in. The mode-line was another component. Try running `(setf mode-line-format nil)` when the slow down happens.

You can also try killing Emacs with SIGUSR2 a few times. That will show you backtraces of what Emacs was up to when the signal hit. Maybe there will be something in one of them.

My money's still on lsp-dart however, so try again with that purged from your system, and make sure the language server is not running.

Depending on the results of these points I'll be able to start debugging on my own or have to get help from the lsp gang.

**Comment by zoechi** [comment]
Thanks a lot for the pointers! I'll try to narrow it down further.

**Comment by zoechi** [comment]
- `(setf mode-line-format nil)` didn't help

- SIGUSR2 always prints 
```
debug(lambda)
* #f(advice-wrapper :after command-error-default-function help-command-error-confusable-suggestions)((quit) "" nil)
  recursive-edit()
```
with 100% CPU usage (folder with *.dart files expanded) and otherwise (folder collapsed)

- >There is nothing dart-specific 

I found this quite weird as well. Perhaps my strategy to not load config and installed packages is flawed. 
I run `emacs -q` and then run `eval-last-sexp` for the few things I want to have loaded to reproduce. I also run `package-delete lsp-dart` and deleted all folders in `emacs.d` subdirectories where I found them, to ensure it's not loaded by other means and I checked that no `lsp-dart-...` variables existed.

**Comment by Alexander-Miller** [comment]
> SIGUSR2 always prints

It's different that what I get, but not helpful either.

Does it help to disable follow-mode or filewatch-mode?

**Comment by Alexander-Miller** [comment]
I've installed lsp-dart and its language server. No luck on reproduction, though lsp-mode doesn't quite work with a single dart file thrown into the treemacs tree:

> LSP :: Connected to [dart_analysis_server:323392 status:starting].
LSP :: dart_analysis_server:323392 initialized successfully
LSP :: When using onlyAnalyzeProjectsWithOpenFiles, files opened that are not contained within project folders containing pubspec.yaml, .packages or BUILD files will not be analyzed.
LSP :: Invalid file path [5 times]

Can you provide me with a sample project?

**Comment by Alexander-Miller** [comment]
Another thing you can try is load the Default treemacs theme, and load only small parts of the doom theme. The `with-eval-after-load 'treemacs` seems to do most of the setup, so loading it piece by piece could reveal which specific part causes your problems (the treemacs buffer will need to be killed, not just closed, and restarted for this).

**Comment by zoechi** [comment]
I just experienced a similar behavior (high CPU) when I scroll in a Dart file.
In this case your earlier suggestion `(setf mode-line-format nil)` fixed it.

I tried `(setf mode-line-format nil)` again (in all windows) with `(doom-themes-treemacs-config)` but in this situation it didn't have any effect.

I'll continue investigating with your other suggestions later.

**Comment by zoechi** [comment]
It looks like https://github.com/domtronn/all-the-icons.el/commit/0b74fc361817e885580c3f3408079f949f5830e1 is the cause. I commented the changes out locally and now the issue is gone with treemacs and doom-modeline

**Comment by zoechi** [comment]
Currently I'm not able to reproduce in Treemacs anymore, with or without `(doom-themes-treemacs-config)`. I still see it with doom-modeline icon.

Could this be some cache issue? Are the icons created with `(treemacs-resize-icons xx)` cached somewhere on disk?

**Comment by Alexander-Miller** [comment]
> Are the icons created with (treemacs-resize-icons xx) cached somewhere on disk?

No, as I understand things the resize happens in-memory.

> I still see it with doom-modeline icon.

It looks like your system is struggling with that one icon for whatever reason. I don't have the fonts for it (and my own doom modeline is 100% custom), so I guess I'm not affected.

You can try giving that icon a different font. I've a utility in my config for that:

```Elisp
(cl-defmacro std::downscale (char &key font (size 12))
  `(set-fontset-font "fontset-default" (cons ,char ,char) (font-spec :size ,size :name ,font)))
(std::downscale ?\✿ :font "Symbola" :size 11)
```

**Comment by zoechi** [comment]
I can't reproduce anymore. 
There were updates the recent days (lsp-mode, treemacs, others)
Perhaps one of those fixed it.
