### ISSUE TITLE
[Feature Request] Sorting functions

### ISSUE THREAD

**Issue by technician77** [Alexander-Miller/treemacs#65]
I don't know about other people, but for me it comes to happen that I like to have things sorted alphabetically, but from time to time I open an directory full of files, sometimes with nearly identical names and I just need the "latest". I know there is a treemacs-sorting variable, but I need something "on the fly". So I can say "sort the tree by mod-time-asc", then I open the latest file and get back to alphabetic-desc sorting of the tree.

**Comment by Alexander-Miller** [comment]
Try the new `treemacs-push-button-select-sort`.

**Comment by technician77** [comment]
That function seems practical but I have two problems. First it doesn't seem to work. Even when I hit g it stays at alphabetical order (default oder).
Second when I'm on a file (not on the root folder name at the top) something odd happens. As an example when I'm on a PDF I get:
```
[Treemacs] No imenu index found for X:/xxxxxxxxxxxx/xxxx/xxxxxxxxxx/xxx/xxxxxxxxxx.pdf
DocView: process pdf/ps->png changed status to exited abnormally with code 255.
```
It seems it tries to process the files somehow when I execute the sorting.

**Comment by Alexander-Miller** [comment]
> First it doesn't seem to work. Even when I hit g after resorting it stays at alphabetical order (default oder).

Looks like we didnt quite understand each other. When you talked about opening folders I assumed you meant expanding nodes with TAB. So the function I built applies the special sorting before opening the selected node (it doesnt check the button type and just delegates to the push-button command). I take it you want the resort for the entire view?

> It seems it tries to process the files somehow when I execute the sorting.

Thats not about the sorting. Treemacs integrates with imenu, pressing TAB on files shows their imenu tags. For pdfs that obviously doesnt work.

**Comment by technician77** [comment]
I retried the function after I read your information. Yes, it works as you describe. But to me that behaviour is not very intuitive and additional it I don't think it is optimal for the workflow. Let me first tell me about my and presumably the workflow of a lot other people: I go to inside a folder, assume a project main folder. Now I find inside this project folder another folder, maybe copied from a file share. Assume this copied folder is a mess, because it is old and was altered by different people, but you don't know it's a mess until you have opened it. With your function I would have to go up and reopen the leaf using that sorting function.

So what I (and presumably other people) need is a sorting of the files inside an opened folder if the opened folder is made root this would mean resorting of the entire view otherwise just of the folder the cursor is in. You could also resort everything but that would confuse and I wouldn't need it. Why should the other project folders be resorted (in this case). But then there could be cases where you need exactly this. Assume you forgot which projectfolder was the last one you created and you want to check, then I would need a resort of the root folder. To sum it up I would need something like this:

1. resort-folder-current-leaf (level where the cursor is)
2. resort-folder-root
3. resort-everything (Most tree explorers only offer that option)

**Comment by Alexander-Miller** [comment]
Ive been busy with https://github.com/Alexander-Miller/treemacs/issues/50, but now that its winding down sorting comes next.

So heres my idea: 1 new command, well call it resort, bound to `s`.  

 * Call it once to permanently set a new sorting method. 

 * Call with prefix arg to temporarily (until the next refresh) resort the current dir. If point is on a dir node itll open and resort that node. If point is on a file in root itll resort everything.

 * Call with double prefix arg to temporarily resort the entire view.

Does that cover you use-case?

**Comment by technician77** [comment]
It should cover my use-cases but could you elaborate on the prefixes? Prefixes often don't go well with the way I think. I'd rather pay the price by calling the main used command using two letters something like this:
method 1: s s
method 2: s c
method 3: s e

**Comment by Alexander-Miller** [comment]
> It should cover my use-cases but could you elaborate on the prefixes?

I mean prefix as in `C-u`,  or `SPC u` if your'e on spacemacs. Not that much of a difference to multiple keys and it's consistent with the rest of treemacs. If that's not to you liking you can easily set up a keybind to directly call set the prefix arg, like this:

`(define-key treemacs-mode-map (kbd "sc") (lambda () (interactive) (treemacs-resort '(4))))`

You'll also need to unbind s first. Prefix arg values go up by power of two, so case 3 is the same, but with a value of 16.

**Comment by Alexander-Miller** [comment]
I still need a bit of cleanup, but the resort is done. You can go ahead and try it out, see if it works four you:

```
(defun treemacs-resort (&optional arg)
  "Select a new permanent value for `treemacs-sorting' and refresh.
With a single prefix ARG use the new sort value to *temporarily* resort the
\(closest\) directory at point.
With a double prefix ARG use the new sort value to *temporarily* resort the
entire treemacs view.
Temporary sorting will only stick around until the next refresh, either manual
or automatic via `treemacs-filewatch-mode'."
  (interactive "P")
  (let* ((sort-names '(("Sort Alphabetically Ascending" . alphabetic-asc)
                       ("Sort Alphabetically Descending" . alphabetic-desc)
                       ("Sort by Size Ascending" . size-asc)
                       ("Sort by Size Descending" . size-desc)
                       ("Sort by Modification Date Ascending" . mod-time-asc)
                       ("Sort by Modification Date Descending" . mod-time-desc)))
         (selected-value (completing-read (format "Sort Method (current is %s)" treemacs-sorting)
                                          (-map #'car sort-names)))
         (selected-pair (--first (s-equals? (car it) selected-value) sort-names))
         (selected-name (car selected-pair))
         (new-value (cdr selected-pair)))
    (pcase arg
      ;; Resort current dir only
      (`(4)
       (let ((treemacs-sorting new-value))
         (-if-let (btn (treemacs--current-button))
             (pcase (button-get btn 'state)
               (`dir-node-closed
                (treemacs--open-dir-node btn)
                (treemacs--log "Resorted %s with sort method '%s'."
                               (propertize (treemacs--get-label-of btn) 'face 'font-lock-string-face)
                               (propertize selected-name 'face 'font-lock-type-face)))
               (`dir-node-open
                (treemacs--close-node btn nil)
                (goto-char (button-start btn))
                (treemacs--open-dir-node btn)
                (treemacs--log "Resorted %s with sort method '%s'."
                               (propertize (treemacs--get-label-of btn) 'face 'font-lock-string-face)
                               (propertize selected-name 'face 'font-lock-type-face)))
               ((or `file-node-open `file-node-closed `tag-node-open `tag-node-closed `tag-node)
                (let* ((parent (button-get btn 'parent)))
                  (while (and parent
                              (not (-some-> parent (button-get 'abs-path) (f-directory?))))
                    (setq parent (button-get parent 'parent)))
                  (if parent
                      (let ((line (line-number-at-pos))
                            (window-point (window-point)))
                        (goto-char (button-start parent))
                        (treemacs--close-node parent nil)
                        (goto-char (button-start btn))
                        (treemacs--open-dir-node parent)
                        (with-no-warnings (goto-line line))
                        (set-window-point (selected-window) window-point)
                        (treemacs--log "Resorted %s with sort method '%s'."
                                       (propertize (treemacs--get-label-of parent) 'face 'font-lock-string-face)
                                       (propertize selected-name 'face 'font-lock-type-face)))
                    ;; a top level file's containing dir is root
                    (treemacs--without-messages (treemacs-refresh))
                    (treemacs--log "Resorted root directory with sort method '%s'."
                                   (propertize selected-name 'face 'font-lock-type-face)))))))))
      ;; Temporarily resort everything
      (`(16)
       (let ((treemacs-sorting new-value))
         (treemacs--without-messages (treemacs-refresh))
         (treemacs--log "Temporarily resorted everything with sort method '%s.'"
                        (propertize selected-name 'face 'font-lock-type-face))))
      ;; Set new permanent value
      (_
       (setq treemacs-sorting new-value)
       (treemacs--without-messages (treemacs-refresh))
       (treemacs--log "Sorting method changed to '%s'."
                      (propertize selected-name 'face 'font-lock-type-face))))
    (treemacs--evade-image)))
```

**Comment by Alexander-Miller** [comment]
Above code is now on master, but I'll split things up so you can directly bind the version you want.

**Comment by Alexander-Miller** [comment]
Split work is done. Now you also have `treemacs-temp-resort-current-dir` and `treemacs-temp-resort-root`. Go ahead and try it out, make sure I didn't miss anything.

**Comment by technician77** [comment]
The dedication to your project is quite awesome. Not only everything works as expected in regards of my requests but the project also gained in a lot of other areas since I opend the issue - nice. Since the original issue is resolved I think you close it on my part.

Just one suggestion for a function that might be useful in regards of the temporary resorts. When I did a temporary resort, sometimes I would like to undo it. So instead of manually selecting the last sorting method before the temporary resort it would be nice to have a function like "treemacs-temp-resort-undo-last". That would be sufficient for me. Theoretically this can be take further with multiple undos, if treemacs would track them, but that might be overkill.

**Comment by Alexander-Miller** [comment]
Yeah, I think a sorting stack would be more confusing than anything. Probably not worth the trouble either, since the use-case is very limited, but tracking each directories resort now persistent resort stack is very a complicated task.

W.r.t sort undoing: it's the temporary variant, why not just call a refresh?

**Comment by technician77** [comment]
Yes, refresh does the job.
