### ISSUE TITLE
Installation from MELPA fails

### ISSUE THREAD

**Issue by jzohrab** [Alexander-Miller/treemacs#650]
Hello,

On emacs v26.2,  M-x package-install treemacs fails with error `https://stable.melpa.org/packages/pfuture-1.7.el: Not found`

I'm using melpa-stable: `(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)`

**Comment by Alexander-Miller** [comment]
If tags were missing I have pushed them now. Also try `package-refresh-contents`.

**Comment by Alexander-Miller** [comment]
Bump?

**Comment by jzohrab** [comment]
Thank you!  I’m traveling and will be back to try again tonight or
tomorrow. Cheers! Z

**Comment by jzohrab** [comment]
Thanks again for following up.  I did as you said, restarted emacs, and it started correctly, though it has an error at one point: `Error (use-package): treemacs/:config: Symbol’s value as variable is void: treemacs-last-period-regex-value`.  I blindly copied that from the [treemacs readme](https://github.com/Alexander-Miller/treemacs#installation), here's the snippet from my init.el: 

```
  :config
  (progn
    (setq treemacs-collapse-dirs                 (if treemacs-python-executable 3 0)
          treemacs-deferred-git-apply-delay      0.5
...
          treemacs-file-extension-regex          treemacs-last-period-regex-value
```

Restarted, and the error occurred again.  Looking into it!

**Comment by jzohrab** [comment]
I think this is user error, where `user == me`.

I had commented out the items under `;;(use-package treemacs-evil ;;  :after treemacs evil ;;  :ensure t)` due to prior problems.  Re-enabling everything, it all loaded correctly.  Doing one last check.

**Comment by jzohrab** [comment]
Super, all works.  Thank you very much for the prompt reply.  I'm now trying to sort out icons -- `(setq treemacs-no-png-images t)` is not working, but that's a different issue!

Cheers and thanks again! jz

**Comment by Alexander-Miller** [comment]
> (setq treemacs-no-png-images t) is not working

You need to kill the treemacs buffer for that. `q` just hides it, you need `Q`.

**Comment by jzohrab** [comment]
**Thank you very much!** That was exactly what I was looking for ... I think!  I'll see how it goes with this.  Cheers and regards, I hope you're doing well in this whacked-out time!
