### ISSUE TITLE
Scale all fonts by a proportion?

### ISSUE THREAD

**Issue by SreenivasVRao** [Alexander-Miller/treemacs#652]
Hi, thank you for this awesome package. I was wondering if there's a way to scale all the font sizes. I find them a little too big for my screen.

And also the icons!

**Comment by Alexander-Miller** [comment]
Icons yes, that's what `treemacs-resize-icons` is for. Fonts aren't handled by treemacs, for them you need to call something like `text-scale-adjust` or change the default: http://pragmaticemacs.com/emacs/change-text-size/

**Comment by SreenivasVRao** [comment]
Hi, text scale adjust works pretty well - I'm guessing I can add a hook using the example above to make it persist across sessions. 

Can't figure out where the hook should be added though... I see treemacs hooks. maybe a post refresh hook?

Would appreciate your help!

1. text-scale-adjust is interactive. I tried the elisp snippet above, but I get "invalid function". I'll dig around some more for the right snippet - let me know if you have an idea what I need. 
2. treemacs-resize-icons seems to have no effect. I understand the default is 22 pixels? I tried 10 pixels, and 100 pixels. No change observed...

**Comment by Alexander-Miller** [comment]
> Can't figure out where the hook should be added though.

Major mode hooks, like `treemacs-mode-hook`, are called just once when the buffer is first set up.

> I tried the elisp snippet above, but I get "invalid function"

Dunno what you tried but calling it with `(text-scale-adjust -1)` works just fine, so you can stick it in a hook.

> treemacs-resize-icons seems to have no effect.

Then your Emacs probably has no imagemagick support. You can check that with `(image-type-available-p 'imagemagick)`. I will add some explicit feedback for that case, but that is all I can do n this front.
