### ISSUE TITLE
Warning using treemacs-modify-theme

### ISSUE THREAD

**Issue by ericdallo** [Alexander-Miller/treemacs#654]
When I use the `treemacs-modify-theme`, my emacs byte-compile gets a `value returned from (aref theme 1) is unused` warning.

![image](https://user-images.githubusercontent.com/7820865/80283241-71ed4380-86ec-11ea-9c4b-abeabb54a509.png)

Maybe [this](https://stackoverflow.com/questions/17073755/value-returned-is-unused-warning-when-byte-compiling-a-macro) can fix it?

**Comment by Alexander-Miller** [comment]
You see the warning because I return the modified theme's name instead of the return value of the last setter the macro is calling. I'll change that to nil instead.

**Comment by ericdallo** [comment]
Thank you @Alexander-Miller !
