### ISSUE TITLE
Canceling Project root: prompt

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#656]
### Description
Canceling the `Project root:` prompt with: `C-g`
leaves the file: `treemacs-persist` in a broken state.

And if the prompt is canceled in another workspace, 
then the previous workspace projects are removed when Emacs is restarted.

### Reproduction steps
Without a `treemacs-persistent` file in: `~/.emacs.d/.cache/`
- Start Emacs
- Start Treemacs: `M-x treemacs`
the `Project root:` prompt appears
- Cancel it with: `C-g`
- Close Emacs: `C-x C-c`
A `~/.emacs.d/.cache/treemacs-persist` file was created, containing:
```
* Default

```
- Start Emacs again
- Start Treemacs: `M-x treemacs RET`
The `Project root:` prompt appears, and adding a project works as expected.
But the `*Messages*` buffer shows:
>[Treemacs Error] Could not restore saved state, found error in line '* Default':
Cannot end with a project or workspace name
Broken state was saved to c:/Users/username/.emacs.d/.cache/treemacs-persist-at-last-error

And the `treemacs-persist-at-last-error` file contains:
```
# State when last error occurred on 2020-04-27 11:19:07
# Error was 'Cannot end with a project or workspace name' in line '* Default'

* Default

```

### Previous project removed
With a project added in the default workspace: `~/.emacs.d`
- Create a new workspace: `C-c C-w a`
- At the `Workspace name:` prompt, type: `workspace2`
The file `treemacs-persist` contains:
```
* Default
** .emacs.d
 - path :: ~/.emacs.d
* workspace2

```
- Switch to the other workspace: `C-c C-w s workspace2`
A `Project root:` prompt appears.
- Cancel the prompt: `C-g`
- Close Emacs: `C-x C-c`
- Start Emacs
- Start Treemacs: `M-x treemacs`
The file `treemacs-persist-at-last-error` was created, and it contains:
```
# State when last error occurred on 2020-04-27 14:43:49
# Error was 'Cannot end with a project or workspace name' in line '* workspace2'

* Default
** .emacs.d
 - path :: ~/.emacs.d
* workspace2

```
A `Project root:` prompt appeared.
- Add a project: `~/Temp`
The minibuffer shows: `[Treemacs] Created first project.`
`treemacs-persist` now contains:
```
* Default
** Temp
 - path :: ~/Temp
```
The `*Messages*` buffer shows:
>[Treemacs Error] Could not restore saved state, found error in line '* workspace2':
Cannot end with a project or workspace name
Broken state was saved to c:/Users/username/.emacs.d/.cache/treemacs-persist-at-last-error

The Default workspace project `~/.emacs.d/` was replaced with the new one: `~/Temp/`

### System Info
[Treemacs] v2.8-2020.04.27 @ 26.3
GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
Windows 1903

**Comment by Alexander-Miller** [comment]
Problem: Persist happens when Emacs shuts down - not the right place to
show warnings or even ask the user what to do with the empty workspace,
and there is no space to get clever either.

Solution: Just don't save empty workspaces. You do have to go out of
your way to even end up with one, so if it wasn't filled by the time you
quit Emacs you've probably forgotten all about it anyway.

**Comment by duianto** [comment]
Removing empty workspaces seems like a fine solution, it's easy enough to recreate it if one didn't finish adding a project before restarting Emacs.

But the current fix doesn't seem to have been enough. The reproduction steps above are still reproducible.

The issue doesn't seem to be occurring when Emacs is shutting down, but instead when Treemacs is started after restarting Emacs with an empty workspace in `treemacs-persist` .

The first reproduction steps isn't a problem, it just shows some possibly unnecessary error messages in the messages buffer.

The `Project root:` prompt still appears as if it's the first time Treemacs was started.

Nothing is lost, since the user hasn't defined any projects yet.

The persist files are identical:
- `treemacs-persist`
```
* Default

```
- `treemacs-persist-at-last-error` (except for the comments)
```
# State when last error occurred on 2020-04-27 11:19:07
# Error was 'Cannot end with a project or workspace name' in line '* Default'

* Default

```

### Main issue
The main issue occurs in the `Previous project removed` reproduction steps above.

It's unlikely to occur often, but if someone switches to a new workspace, but has to cancel the 
`Project root:` prompt and close Emacs, before defining a new project. Then they probably will be surprised/unhappy that the Treemacs window is empty on startup and a new `Project root:` prompt is shown. If a project is defined then it replaces the previous projects.

`treemacs-persist` still contains the previous projects and the empty workspace, when Treemacs is started, when the `Project root:` prompt is shown.
```
* Default
** .emacs.d
 - path :: ~/.emacs.d
* workspace2

```

If one cancels the prompt: `C-g`
and tries to switch workspace `C-c C-w s`, then it shows:
>[Treemacs Failure] There are no other workspaces to select.

If one tries to edit the workspaces: `C-c C-w e`
Then `treemacs-persist` updates:
```
* Default

```
The `*Edit Treemacs Workspaces*` buffer shows:
```
#+TITLE: Edit Treemacs Workspaces & Projects
# Call ~treemacs-finish-edit~ or press ~C-c C-c~ when done.
# [[https://github.com/Alexander-Miller/treemacs#conveniently-editing-your-projects-and-workspaces][Click here for detailed documentation.]]
# To cancel you can simply kill this buffer.

* Default
```

**Comment by Alexander-Miller** [comment]
treemacs-persist still contains the previous projects and the empty
> workspace,

I cannot reproduce what you describe. If a new workspace is created, but
the addition of a project is cancelled, then that workspace is not
saved.

> The persist files are identical:
> * Default

With the latest changes it should be impossible for your persisted state
to ever look like this. The only way this could still happen is if this
broken state was persisted like this previously, before you pulled in
the latest fixes. If that is the case you will still see the old
warnings appear when treemacs tries to load things, it's only after the
*next* restart that empty workspaces can be avoided.

**Comment by duianto** [comment]
Your right the latest update doesn't save an empty workspace :+1:

This seems to be what caused the confusion.

After reading the previous comment about the solution, when the fix was implemented.

I was just going to temporarily test the fix with a new `~/.emacs.d` setup, so I only evaluated the melpa setup, from the `*scratch*` buffer:
```
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives '("gnu" . (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)
```
I updated installed `treemacs` from: `M-x package-list-packages`

`M-x treemacs-version` showed:
>[Treemacs] v2.8-2020.04.27 @ 26.3

And since the date of the latest github commits: https://github.com/Alexander-Miller/treemacs/commits/master
showed the date as:
>Commits on Apr 27, 2020

I assumed that I had the latest version.

Today when I read that you were unable to reproduce the issue.

I checked again if there was an update: `M-x package-list-packages`
but it didn't find any updates.

I started typing out what I was seeing, but before I posted the comment tried checking if there was an update again and I realized that it didn't check melpa as a source, and I remembered that I only had evaluated the melpa archive temporarily yesterday.

Now when I added the melpa setup to the file: `~/.emacs` and updated, then it found an update.

The version is now shown as:
`M-x treemacs-version`
>[Treemacs] v2.8-2020.04.28 @ 26.3

But the date is a day later than the github commit dates.

Hmm.. it seems like I misunderstood the date in the output from: `M-x treemacs-version`
I thought that it was the date when the version was published.

But if I understand it correctly, then it seems to be set when Treemacs is installed/compiled:
https://github.com/Alexander-Miller/treemacs/blob/c3c449b56968b2808176da44ad40a778a05023d2/src/elisp/treemacs.el#L58-L62

Would it be better to say something like:
>[Treemacs] v2.8-(installed 2020.04.28) @ 26.3

**Comment by Alexander-Miller** [comment]
> so I only evaluated the melpa setup, from the `*scratch*` buffer:

If it helps: treemacs has a `clean-start` make target that boots an
instance of Emacs with just treemacs and its dependencies loaded. It
does require Cask however.

 > Would it be better to say something like:
 > [Treemacs] v2.8-(installed 2020.04.28) @ 26.3

Having a publish date is most likely overkill - I'd have to include some
automatism on every push to master - but making clear this is the
install date is a good idea. I've pushed that change now.
