### ISSUE TITLE
void-variable treemacs--selected-icon-background

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#657]
I see a lot of errors during native compilation of Treemacs:

```
Compiling /home/andreyorst/.config/emacs/elpa/treemacs-20200427.1100/treemacs-themes.el...
Compiling /home/andreyorst/.config/emacs/elpa/treemacs-20200427.1100/treemacs-icons.el...
Compiler-macro error for treemacs--create-icon-strings: (void-variable treemacs--selected-icon-background)
Compiler-macro error for treemacs--create-icon-strings: (void-variable treemacs--selected-icon-background)
Compiler-macro error for treemacs--create-icon-strings: (void-variable treemacs--selected-icon-background)
```

Not sure if this affects anything, as everything seem to work fine. `treemacs-version`: `v2.8-2020.04.27 @ 28.0.50`

**Comment by Alexander-Miller** [comment]
The code looks solid on my end, and the byte compiler has no issues, it's probably the native compiler getting confused by the macro+define-inline layers. Let's ask.

Hello @AndreaCorallo, this looks like a case for you: 

 - the defvar is here: https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-icons.el#L62
 - it's used in the inline function here: https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-icons.el#L196
 - which is called in this macro: https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-icons.el#L231
 - The macro is finally used here: https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-icons.el#L257

Is this a native compiler problem or did gccemacs just uncover some subtle treemacs bug?

**Comment by AndreaCorallo** [comment]
Hi @Alexander-Miller ,

I believe to a quick look is the second case.

If a variable is used by a macro in the compile time its definition should be wrapped into an `eval-and-compile`.

We had several similar cases signaled.   You should be able to reproduce this also byte-compiling from command line.

**Comment by Alexander-Miller** [comment]
Ah, I need to compile every file individually. I do have flycheck and CI and all that, but it never came up because my compile command is something like `cask exec emacs -Q -batch -L src/elisp -L src/extra -f batch-byte-compile src/elisp/*.el` and compiling other modules that need the icons file in the same go suppresses that problem.

Yep, looks like I have a makefile to fix. Thanks for the info, @AndreaCorallo.

**Comment by AndreaCorallo** [comment]
@Alexander-Miller welcome :)

Yeah the native compiler is quite picky with these, but in reality what it does is just to invoke the byte compiler infrastructure as its front-end so for these kind of errors is often not his fault.
