### ISSUE TITLE
Symbol's function definition is void: helm-treemacs-icons-enable

### ISSUE THREAD

**Issue by Gahamelas** [Alexander-Miller/treemacs#659]
I have this on my init, before loading helm:

```
(require 'treemacs)
(add-to-list 'load-path "~/.emacs.d/other/helm-treemacs-icons")
(helm-treemacs-icons-enable)
```

However I get the error: "Symbol's function definition is void: helm-treemacs-icons-enable".

Any help is welcome, thanks!

**Comment by yyoncho** [comment]
add `(require 'helm-treemacs-icons)` before the enable call.

**Comment by Gahamelas** [comment]
Thank you!
