### ISSUE TITLE
Switch workspace automatically?

### ISSUE THREAD

**Issue by SreenivasVRao** [Alexander-Miller/treemacs#660]
Hi, I was wondering if treemacs can switch from Workspace A/Project A, to WorkspaceB/ProjectB when I do a projectile-switch-project.
I have treemacs-follow-mode enabled, but it doesn't seem to work in this context...

Would be really neat! I think even the solution in #489 would be sufficient for this.

**Comment by Alexander-Miller** [comment]
Does adding`treemacs-display-current-project-exclusively` to `projectile-after-switch-project-hook` work?

You'll have to update treemacs, the commands has just been added today.

**Comment by SreenivasVRao** [comment]
`(add-hook 'projectile-after-switch-project-hook 'treemacs-display-current-project-exclusively)`

yup - awesome! This works really well. Thanks!
