### ISSUE TITLE
Automatically switch workspace to `treemacs-override-workspace`

### ISSUE THREAD

**Issue by sandinmyjoints** [Alexander-Miller/treemacs#665]
Following up on https://github.com/Alexander-Miller/treemacs/issues/247#issuecomment-623196595: I tried setting `treemacs-override-workspace` in dir locals and it works as expected (value is set) but, as you said in that comment, treemacs doesn't actually switch to that workspace. This is a feature request for it to do so!

**Comment by Alexander-Miller** [comment]
There's a problem with the dir-locals approach: once the
override-workspace is set it won't go away (you cannot unset dir-locals,
right?) even if you do manually select a different workspace.

So unless that is acceptable we need 2 things to make this work: a
user-definable workspace selection option in the vein of
`treemacs--find-user-project-functions` and
launch-treemacs-pick-workspace command.

**Comment by sandinmyjoints** [comment]
That makes sense!

**Comment by sandinmyjoints** [comment]
Would also love a similar feature that worked for tab-bar-mode: when switch tabs, switch treemacs workspace.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
I have looked into this issue now, and I don't think dir-locals and the override workspace could be anything other than a giant hack. I know it's been a while, so in case you are still interested, do you think that `treemacs-project-follow-mode` and the recent change to `treemacs` and `treemacs-select-window` that force a workspace selection with a prefix arg are enough to cover your use-case?

> Would also love a similar feature that worked for tab-bar-mode: when switch tabs, switch treemacs workspace.

I don't use tabs myself, so for that I'd need examples of your config and workflow.

**Comment by sandinmyjoints** [comment]
Thanks for following up! `treemacs-project-follow-mode` isn't right for me -- I really want to see multiple related projects in treemacs at once. `treemacs-select-window` with a prefix arg makes it slightly easier to change workspaces, so I'll use that going forward.

I'm not using tabs anymore, so nothing to share about that config.

FWIW, this actually does what I'm looking for:

```lisp
((nil
  (eval . (progn
            (treemacs-do-switch-workspace
             (treemacs--select-workspace-by-name "Default"))))))
```

I can put that in the dir-locals of each project that I use the Default workspace for, and for each project that uses a different workspace, I can use basically the same snippet but with the name of the other workspace instead. I don't mind that I wouldn't be able to manually switch to a different workspace (and stay in it) while visiting files in a project that has this in its dir-locals. It fits my workflow to see only the workspace associated with the projects/files that I'm currently visiting. The only issue I'm seeing with this is that Emacs essentially goes blank for several seconds when I switch between projects that have different workspaces defined this way. The way I'm switching is with `projectile-switch-project-by-name` with `projectile-vc` as the default action. I don't use `treemacs-git-mode` (I call it with -1 as part of init) so I'm not sure what's taking so long.
