### ISSUE TITLE
Error bringing treemacs back when current buffer has left and right margin width greater than 67

### ISSUE THREAD

**Issue by admacro** [Alexander-Miller/treemacs#669]
I have a hook for markdown mode, see below. I launch Emacs with treemacs open on the left. Here's what I did:

1. launch Emacs (with treemacs open on the left side of the window and `recentf` on the right)
2. open a markdown file in `recentf`
    1. treemacs still open on the left, markdown buffer is open on the right with `left-margin-width` and `right-margin-width` set to 35 and 35 respectively
3. close treemacs by command `treemacs` (treemacs window closed successfully)
4. reopen treemacs by command `treemacs` (**Error**)
    1. `wrong-type-argument window-live-p nil` (see backtrace at the bottom)
5. _changing either left or right margin width making sum of them to be <= 67 solved the issue_

### Markdown hook
```
(add-hook 'markdown-mode-hook
          (lambda ()
            ;; sum of left and right margin cannot be greater than 67 (treemacs bug)
            (setq left-margin-width 35)
            (setq right-margin-width 35)))

```

### Treemacs config
```
(setq treemacs-show-cursor 1)
(setq treemacs-fringe-indicator-mode nil)
(setq treemacs-width 40)
(setq treemacs-space-between-root-nodes nil)
(add-hook `treemacs-mode-hook
          (lambda ()
            (display-line-numbers-mode 0)
            (setq mode-line-format nil)))
```

### Backtrace
```
Debugger entered--Lisp error: (wrong-type-argument window-live-p nil)
  select-window(nil)
  treemacs--popup-window()
  treemacs--setup-buffer()
  treemacs-select-window()
  treemacs()
  funcall-interactively(treemacs)
  call-interactively(treemacs nil nil)
  command-execute(treemacs)
```

### My Emacs version
```
"GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02"
```

**Comment by Alexander-Miller** [comment]
Nothing I can do about that I'm afraid. It's Emacs internals that decide the split cannot happen. You would see an error message that your window is too small for splitting if `split-window-no-error` wasn't used internally. Instead it just fails silently to create a window that treemacs of course cannot select.

You can try changing `window-min-width`, but given that the default is as low as 10 I doubt the results would look any good.

I suggest trying a package like [writeroom](https://github.com/joostkremers/writeroom-mode) for your margin enlargement.

**Comment by admacro** [comment]
Thanks for the suggestion. About splitting window, it's true that Emacs won’t vertically split a window (i.e., into two side-by-side windows) that has wide margins. (https://github.com/joostkremers/visual-fill-column#splitting-a-window)
