### ISSUE TITLE
Where is the treemacs personal information stored?

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#671]
I have been thinking about putting my `.emacs.d` on github to share my Emacs configs with friends. However, I'd like to not push everything about my projects and workspace. Are there any specific treemacs related directories I could put in `.gitignore`?

**Comment by Alexander-Miller** [comment]
As of now there are 2 files treemacs reads and writes: `treemacs-persist-file` and `treemacs-last-error-persist-file`.
