### ISSUE TITLE
Is there a function to create file from template ?

### ISSUE THREAD

**Issue by lawrsp** [Alexander-Miller/treemacs#672]
it will be very useful if we can create new file with template:

e.g we can use `c t` to create file form a named template

after enter `c t`, it shows like:
```
- a -> treemacs-create-file-with-template-a
- b -> treemacs-create-file-with-template-b
- c -> treemacs-create-file-with-template-c
```
push a RET xxx RET
we can get a file with template-a
how do you think ?

**Comment by Compro-Prasad** [comment]
IMO its better to define custom yasnippet snippets which can literally be used in any buffer. Doing this in treemacs specifically would be duplicating the same work that yasnippet does.

**Comment by lawrsp** [comment]
@Compro-Prasad 
Yes, it seems that yasnippet is better

but sometimes snippets does not well
e.g. when create react file with suffix .js, it will be recognized as js2-mode, you must change to rsjx mode manually
I think there are also simillar situations as there are some other magic-modes

is there a way to do the work before open the file ?

**Comment by Alexander-Miller** [comment]
No, the *content* of files has nothing to do with treemacs, this is very much out of scope. Yasnippet, or even the builtin skeletons,  are the right tool for this particular problem.

> when create react file with suffix .js, it will be recognized as js2-mode, you must change to rsjx mode manually

That sounds like a problem that should be solved with your `auto-mode-alist`, or a `// -*- mode: rsjx -*-` cookie.

Alternatively you can assign your snippets to a major-mode both js2 and rsjx derive from (from a quick glance both are based on js-mode).

**Comment by lawrsp** [comment]
@Alexander-Miller 
yes , the specific template must beyond the scope,
but, what about `do-something after file created by pre-select` mechanism?
I found there is a hook `treemacs-create-file-functions`,
if it can be customized to select a function by key stroke, would it be more convenient?

**Comment by Alexander-Miller** [comment]
That's just yasnippet with extra steps. 
You are free to fill the hooks however you want, but snippets are an entirely different domain that treemacs has no business getting directly involved with.

**Comment by lawrsp** [comment]
@Alexander-Miller 
I am not saying about the snippets' works
I mean when to run the snippets,
auto-mode-alist is not enough

and thanks to the treemacs-create-file-functions, I have work out how to use it, some hooks to do the work, likes: 

```
(defun hook1)
(defun hook2)

(set-key "c1" create-with-hook1)
(set-key "c2" create-with-hook2)

```
