### ISSUE TITLE
treemacs--fix-width-after-which-key poor perfomance

### ISSUE THREAD

**Issue by seregaxvm** [Alexander-Miller/treemacs#674]
Sometimes my Emacs slows down significantly. `profiler-report` showed that this is `treemacs--fix-width-after-which-key` fault: 
```
- timer-event-handler                                            3875  61%
 - apply                                                         3875  61%
  - which-key--update                                            3716  59%
   - apply                                                       3716  59%
    - treemacs--fix-width-after-which-key                        3716  59%
     - apply                                                     3712  59%
      + #<compiled 0x19f20c5>                                    3712  59%
```

`treemacs v2.8 (installed 2020.05.11) @ Emacs 26.3`

**Comment by Alexander-Miller** [comment]
The fixes might not even be required anymore, at least I didn't see any problems after some quick tests.

Try this:

```Elisp
(advice-remove 'which-key--update 'treemacs--fix-width-after-which-key)
(advice-remove 'which-key--hide-buffer-side-window 'treemacs--fix-width-after-which-key)
```
If you can confirm that which key and treemacs get along on your end as well (especially with which-key set to appear on the right) I will get rid of the compatibility code.

**Comment by seregaxvm** [comment]
At first glance everything looks good. Tried all which-key positioning options. Not sure what I'm looking for though. What was the original problem which which-key?

**Comment by Alexander-Miller** [comment]
IIRC having which key on the right would change treemacs' width whenever which-key's popup would appear. Not the sort of thing that'd be difficult to notice, so if we both don't see it I think my glue code can be safely removed.
