### ISSUE TITLE
Treemacs do not ignore files on .gitignore

### ISSUE THREAD

**Issue by mrbig033** [Alexander-Miller/treemacs#676]
I tried the suggested configuration in many different syntaxes (exactly like the README, in and out of use-package) but Treemacs keeps showing ignored files. The `.gitignore` is committed and pushed.

- My [treemacs settings](https://github.com/mrbig033/doom/blob/efabc8f52c7ccc6d0be77fb5426d953911c566f0/my-lisp/my-packages.el#L672)

I'm using macOS Mojave, GNU Emacs 27.0.91.

**Comment by Alexander-Miller** [comment]
The check uses information stored in treemacs' git info cache, so git-mode must be enabled as well. `extended` will work best, the other variants are limited/might have issues. 

I will update the documentation accordingly.

**Comment by mrbig033** [comment]
Cool. I think it's working now:

```
(use-package! treemacs
  :demand t
  :init
  (setq +treemacs-git-mode 'extended)
  (setq treemacs-git-mode 'extended)
  :config
  (add-to-list 'treemacs-pre-file-insert-predicates #'treemacs-is-file-git-ignored?))
```

The extra variable is from Doom Emacs. Thanks!
