### ISSUE TITLE
[Request] Open files in the buffer from which I called Treemacs

### ISSUE THREAD

**Issue by mrbig033** [Alexander-Miller/treemacs#679]
When I have multiple windows in a frame, and I call Treemacs, I believe it would be nice to have the option to open files on the same buffer I called Treemacs from, and not to the closest one, which is what it seems to be doing right now.

**Comment by Alexander-Miller** [comment]
Does `treemacs-visit-node-in-most-recently-used-window` fit your bill? You can make that the default with `treemacs-define-RET-action`.

**Comment by mrbig033** [comment]
It does! How can I make this default?

**Comment by Alexander-Miller** [comment]
If I have done my job right I should not have to explain that because the documentation for `treemacs-define-RET-action` contains all the info you need.

**Comment by mrbig033** [comment]
No problem, thank you.

**Comment by Alexander-Miller** [comment]
Sounds like all is cleared up then.
