### ISSUE TITLE
[Feature Request] Move root up when pressing return on root folder name at the top

### ISSUE THREAD

**Issue by technician77** [Alexander-Miller/treemacs#68]
Well, I guess the title says it all. It would make the behaviour more like other tree explorers.

with kind regards,
tech77

**Comment by Alexander-Miller** [comment]
Ive given it some thought now and I'll have to pass, for 2 reasons:

 * Moving root up already has a dedicated keybind on `h`, available anywhere.
 * The headline does not always show the parent folder's name. It's explicitly customizable (see `treemacs-header-function`), you can put *anything* there. For example treemacs-projectile comes with a function that that will instead show the project's name if it's available.

**Comment by technician77** [comment]
Oh, I see.
