### ISSUE TITLE
Undefined function `treemacs-unlese-let`

### ISSUE THREAD

**Issue by seagle0128** [Alexander-Miller/treemacs#682]
https://github.com/Alexander-Miller/treemacs/commit/bf4bdeb90cc36c09a4c9fa4ffdfea1b85c4f1220 breaks some packages. For example, for `doom-themes`, `lsp-treemacs`,  got undefined function `treemacs-unlese-let` error while calling `treemacs-create-theme`, `treemacs-delete-other-winows`.

**Comment by Alexander-Miller** [comment]
Pushed a potential fix, try again with the latest version.

**Comment by seagle0128** [comment]
Wow, super quick fixing. Will try later. Thanks!

**Comment by seagle0128** [comment]
Confirm. It's fixed.
