### ISSUE TITLE
make-treemacs-dom-node, make-treemacs-project are not defined

### ISSUE THREAD

**Issue by kurnevsky** [Alexander-Miller/treemacs#683]
With recent treemacs update we started getting the following error (https://github.com/melpa/melpa/pull/6913#issuecomment-636500967):
``` 
Warning: the following functions are not known to
    be defined: make-treemacs-dom-node, make-treemacs-project
```
It seems these functions weren't renamed properly.

**Comment by Alexander-Miller** [comment]
Try again, I'm pretty sure I got them all now:
![rg](https://user-images.githubusercontent.com/5951157/83396391-3422bf80-a3fc-11ea-8201-2b326bed09a7.png)

**Comment by kurnevsky** [comment]
Then why does github manage to find them: https://github.com/Alexander-Miller/treemacs/search?q=make-treemacs-dom-node&unscoped_q=make-treemacs-dom-node ? :)

**Comment by Alexander-Miller** [comment]
Because I apparently forgot to commit those changes :facepalm:

**Comment by Alexander-Miller** [comment]
BTW since you are also making use of extensions you should have a look at https://github.com/Alexander-Miller/treemacs/issues/677.
