### ISSUE TITLE
tags of org file is not refreshed though imenu-auto-rescan is t

### ISSUE THREAD

**Issue by zijianyue** [Alexander-Miller/treemacs#684]

**Comment by Alexander-Miller** [comment]
Looking into it.

**Comment by Alexander-Miller** [comment]
Should be fixed now. Let me know if the problem persists.

**Comment by zijianyue** [comment]
No, not fixed yet.

**Comment by Alexander-Miller** [comment]
Looks fine on my end: https://imgur.com/a/u8QN0CH

Please provide reproduction steps.

**Comment by zijianyue** [comment]
I tried again with latest treemacs in two org file, one is my personal note, it worked well, the other org file is my work todo list which is very large and can not share with you, it still can not work well.
For example, the steps of one case are:
1. open the org file ,trigger the treemacs command that display the treemacs window
2. add one entry in org file 
3. trigger treemacs-find-tag command, but in treemacs window ,the entry did not represent, treemacs-refresh did not work either.

**Comment by Alexander-Miller** [comment]
> treemacs-refresh did not work either

You have to save the file for the automatic change, treemacs only listens for events from your file system. However if even manual refresh didn't work then I don't think treemacs is to blame. Treemacs takes its tags information from imenu, so the item probably won't appear in imenu either. Maybe you have exceeded `org-imenu-depth`?

**Comment by zijianyue** [comment]
I found that after I invoke imenu-list, the new entry can represent in imenu-list, and then invoke treemacs-refresh, it appeared in treemacs too.

**Comment by Alexander-Miller** [comment]
You will have to share the file then. The content does not matter. All imenu and treemacs care about is the hierarchy and layout of headlines, so whatever problems you have, they must still be reproducible in a file that looks like

```
* A
** B
*** C
```
Transform your file into something like this, and I'll investigate.
