### ISSUE TITLE
Identify projects with unmerged remote commits or not-pushed local commits

### ISSUE THREAD

**Issue by gregsgit** [Alexander-Miller/treemacs#686]
Based on magit status, it would be nice if Project icons could indicate whether a project has unmerged remote commits (based on a fetch) or unpushed local commits. 

In magit's status, it will identify 'unpulled from remote/branch' if remote has unmerged commits from a remote. Similarly, magit will identify as 'unmerged into remote/brance' for local commits that have not been pushed to remote.

In my case, I have a workspace with a few dozen git repos in it as projects. It would be convenient if, having done 'git fetch' on all the repos, if, at a glance, I can see which repos have remote commits, for the current local branch. For example, if something breaks, I can quickly survey projects and notice that I'm missing a few merges, and I should do those before complaining to someone.

Similarly, some visual indication to avoid the "oops, I forgot to push that" situation, when I had to make changes to a number of repos for one feature, and forgot to push to one of the repos, would be nice.

Thanks.

**Comment by Alexander-Miller** [comment]
It's a good addition, but there's some caveats:

 - I'd rather not to have to get busy with git all on my own, so I will try to get all the necessary info from magit, thus making this usable only when magit & treemacs-magit are installed and loaded
 - That also means that the display depends on magit's knowledge of your git status and may be out of date
 - At least that's all assuming there's a good magit api for all of that. If you have to manually call `magit-status` in every project first I may change my approach.
 - I don't think there's meaningful icons for this, so the commit difference will look like '3↑1↓' (iirc that's how eclipse does it

**Comment by gregsgit** [comment]
Good points.
Obvious on hindsight, but yes, (a) this would be tied to magit), (b) I
suppose treemacs would have to ask magit to refresh its status for each
project in turn. I think something like '3↑1↓' would be perfect.
-- Greg

--
Greg Sullivan   gregs@sulliwood.org
12 Ware Rd., Auburndale, MA 02466
h: 617-964-7699     c: 617-417-4746

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
It took a while, but `treemacs-git-commit-diff-mode` has now been implemented.

**Comment by gregsgit** [comment]
That is amazing! Thank you so much for implementing this!
-- Greg

--
Greg Sullivan   email: ***@***.***   cell: 617-417-4746
70 Pigeon Hill Street, Rockport, MA 01966
