### ISSUE TITLE
No evil keybinding for treemacs-TAB-action

### ISSUE THREAD

**Issue by Crosse** [Alexander-Miller/treemacs#689]
I'm trying out treemacs and treemacs-evil, and decided to also look at [emacs-lsp/lsp-treemacs](https://github.com/emacs-lsp/lsp-treemacs), but stumbled on an issue that looked a lot like emacs-lsp/lsp-treemacs/issues/31. When I ran opened any of the lsp-treemacs windows, I typically got a single line and couldn't figure out what to do with it. In the issue linked above, someone mentioned "have you pressed TAB on the line?" I thought, "that's it, I just didn't know the key to use to make it do things!" Unfortunately TAB didn't work for me, either.

However, what I noticed after some more poking around is that, while treemacs-evil.el [has a keybinding for `treemacs-RET-action`](https://github.com/Alexander-Miller/treemacs/blob/7d6c0c6e410be00d3d36bec3baaa685e69b4fca1/src/extra/treemacs-evil.el#L83), it does not have a corresponding one for `treemacs-TAB-action`.

I don't know enough about anything here to know whether this is intentional or not, but I feel like maybe `treemacs-TAB-action` should be bound to TAB even in evil mode? If that's the case I can make a PR for it if you'd like!

Thank you!

**Comment by Alexander-Miller** [comment]
> I don't know enough about anything here to know whether this is intentional or not

It's intentional. Keymaps are complicated and evil doesn't appropriate every single key, so the evil module doesn't need a keybind for every single key. So TAB works just fine as it is, I use evil myself so if it didn't I'd have noticed years ago. You can also verify yourself with `describe-key`.

So your problem is probably specific to lsp-treemacs, or even just your setup. What view are you having problems with exactly? I can try having a look on my end.

**Comment by Crosse** [comment]
Well, I've been a bad reporter and have let this sit for almost a month. I honestly don't remember what I was doing with it at the time; work has been busy (excuses) and I've not had time to continue attempting to integrate lsp-treemacs into my workflow. I think the best option for now is for me to close this issue, and if I ever get back to trying lsp-treemacs again, I'll take your advice and do some more investigation on my own, including into my own setup.

Thank you for being kind to a pretty new Vim-to-Emacs convert!

**Comment by Alexander-Miller** [comment]
Yeah, well, I take back what I said - except the keymaps being complicated part. Looks like an extra TAB bind is necessary, but only if you use Emacs in a terminal. If that's the case for you then it should work now.

**Comment by Crosse** [comment]
Well, I'm guessing you can figure out where I was using Emacs… 😄 Thank you for the follow-up!
