### ISSUE TITLE
Better mapping between treemacs workspaces and persp-mode perspectives

### ISSUE THREAD

**Issue by betaprior** [Alexander-Miller/treemacs#692]
It seems that when I invoke treemacs from a buffer that belongs to a perspective, treemacs creates a new workspace for that perspective. However, if I delete that perspective (or am in a new emacs instance) and open that workspace in treemacs (`M-x treemacs-switch-workspace`), it will open the files in whatever happens to be the current perspective. A better behavior would be to recreate the perspective (for example, this is the behavior of `counsel-projectile-switch-project`). Arguably, if there's a mapping between perspectives and workspaces (which is what auto-creation of a workspace seems to suggest), this mapping should be preserved.

**Comment by Alexander-Miller** [comment]
I do not use perspectives myself, so I will need a detailed description of your use-case to get my head around it. Can you give me a step by step rundown of the current & desired behavior, starting from "start emacs, enable persp-mode"?

**Comment by exp2ipi** [comment]
Ok, here's an illustration of my point: you can see in the gif that when I open the project, a new perspective gets created (in this example, it's number 5).  This corresponds to an auto-created workspace in treemacs.  Then I delete that perspective and open the file from the treemacs workspace. No perspective gets created.  

I don't consider it a major bug, just something to think about. Also, if treemacs workspaces could indeed open a new perspective it could be a nice way to organize perspectives in general.

![treemacs](https://user-images.githubusercontent.com/338250/86465996-a7636e00-bce7-11ea-84a3-b381e1b09196.gif)

**Comment by Alexander-Miller** [comment]
I don't think that's a bug at all, but very much intended behavior. The integration with perspecives is not strict at all, it only synchronizes workspaces with the perspectives you switch to at the time the switch happens. If the user decides to manually switch to another workspace I see no reason for treemacs to not respect that decision. (And the vigil needed to keep perspective and workspace constantly in sync would require *a lot* of effort to implement)

> Also, if treemacs workspaces could indeed open a new perspective it could be a nice way to organize perspectives in general.

You mean synchronizing things also in the other direction - create a new perspective when you switch workspaces? That does sound doable.

**Comment by exp2ipi** [comment]
To clarify, yes, I'm mostly talking about syncing when switching workspaces, since treemacs already knows a workspace was created from a particular perspective.

**Comment by Alexander-Miller** [comment]
Stayin alive.
