### ISSUE TITLE
close all open buffers while switching to another workspace

### ISSUE THREAD

**Issue by prassee** [Alexander-Miller/treemacs#694]
I consider it would be good to add an config option to  close all buffes current workspace before switching to another one. This way the buffer list look less cluttered. In case of LSP, if there is a way to source the tree of buffers we can call lsp-workspace-shutdown transitively.

**Comment by Alexander-Miller** [comment]
I think it's best to split this option in 2

 1) Killing all buffers, except treemacs and scratch
 2) Killing just the file-visiting buffers, in case you want to keep stuff like elfeed around

Either way there is going to be a soft conflict for the case that you have 2 workspaces open in 2 different frames, but I think that situation will be rare enough that it's not worth it to try and find workarounds

> In case of LSP, if there is a way to source the tree of buffers we can call lsp-workspace-shutdown transitively.

Best I can do is offer all the hooks this setup will require, but the actual lsp interaction must be implemented in lsp-treemacs
