### ISSUE TITLE
Error throw with perspective mode wrong-number-of-arguments

### ISSUE THREAD

**Issue by MiyamotoAkira** [Alexander-Miller/treemacs#696]
Hi,

today I updated my packages on emacs. One of them was dap-mode, which brings with it treemacs as a dependency. Originally opened an [issue](https://github.com/emacs-lsp/dap-mode/issues/315) with them, but after getting the stack trace, the issue stems from treemacs.

The stack trace is
```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 0)
  treemacs--remove-treemacs-window-in-new-frames()
  run-hooks(persp-activated-hook)
  persp-activate(#s(perspective :name ".emacs.d" :buffers (#<buffer *Backtrace*>) :killed nil :local-variables nil :last-switch-time (24327 5174 809078 470000) :created-time (24327 5174 809080 758000) :window-configuration #<window-configuration> :point-marker #<marker at 77 in *GNU Emacs*>))
  persp-switch(".emacs.d" norecord)
  persp-new(".emacs.d")
  persp-switch(nil)
  funcall-interactively(persp-switch nil)
  call-interactively(persp-switch nil nil)
  command-execute(persp-switch)
```

Treemacs version is: treemacs-20200708.2136

**Comment by Alexander-Miller** [comment]
> A hook that's run after a perspective has been activated.
Run with the activated perspective active.

Isn't it great when documentation is wrong?

Well, at least fixing it won't take long.

**Comment by Alexander-Miller** [comment]
Things should work now.
