### ISSUE TITLE
Too easy to delete folder

### ISSUE THREAD

**Issue by IntelligentFunction** [Alexander-Miller/treemacs#698]
Just installed this and deleted my entire development folder on first use, not impressed.

**Comment by IntelligentFunction** [comment]
Ok, my bad it moved it somewhere else and just deleted the containing folder. It's still a little strange behaviour though. Using emacs26.3 on linux Mint 19 Cinnamon Version 3.8.9

**Comment by Alexander-Miller** [comment]
**ಠ_ಠ** 

> Can you provide reproducible steps so that we can test it out?

Also this.

Deleting in treemacs is bound to `d`. When you do press it you will be asked to confirm with `yes-or-no-p` (probably aliased to `y-or-np`), so you at the very least have to press `dy` to immediately delete something. And even then treemacs only trashes files, you need a prefix argument for an actual `rm`. 

The same goes for other actions like moving files, I am pretty sure it is always a 2-step process that always requires you to confirm or select a target.

So yeah, unless you can tell me what exactly you did I can't really help.
