### ISSUE TITLE
Evil binding for resort missing

### ISSUE THREAD

**Issue by rodelrod** [Alexander-Miller/treemacs#700]
Hello, I believe that an evil binding for `treemacs-resort` is missing. I'm on Doom Emacs but it seems like a `treemacs` issue: looking through `treemacs-evil.el` this binding is absent (I assume this is the file where it would be declared?)

I would suggest binding it to `s`, I don't see any major conflict with that binding. 

![image](https://user-images.githubusercontent.com/1851908/87777647-29947c00-c82a-11ea-9eea-b4d6df4f3bb2.png)

Thanks for all your work!

**Comment by Alexander-Miller** [comment]
The key is there on my end, so this might be a doom-specific thing. Let's try the fix first. Does this help?

```Elisp
(define-key evil-treemacs-state-map (kbd "s")   #'treemacs-resort)
```

**Comment by rodelrod** [comment]
Yes it does, as does the "doom-y" version of that that I had put on my config:

```
(map! :map evil-treemacs-state-map
      "s" #'treemacs-resort)
```

I would expect to see a reference to `treemacs-resort` in [treemacs-evil.el](https://github.com/Alexander-Miller/treemacs/blob/644e9402f74dc6100a60fc2b54a2f94ba9bc52e0/src/extra/treemacs-evil.el), though. That's why I assumed it was a treemacs omission.

**Comment by Alexander-Miller** [comment]
Let's see if it's a doom issue. The fix is trivial, but it shouldn't be needed at all, so I'd prefer not to have to include it out of principle.

Ping @hlissner Does doom do anything to break this one keybind?

**Comment by rodelrod** [comment]
I believe you are correct, it's a Doom issue.

Doom binds "s" to `evil-snipe-s`. I just assumed that the key wasn't being bound to begin with because of the missing reference in `treemacs-evil.el`. However, by disabling `evil-snipe` the keybinding shows up correctly. I'll take up the issue with Doom. 

Thanks.

**Comment by Alexander-Miller** [comment]
:ok_hand:

**Comment by rodelrod** [comment]
Fixed in Doom (https://github.com/hlissner/doom-emacs/issues/3606). Thanks.
