### ISSUE TITLE
Automatically treat a git repository as a project

### ISSUE THREAD

**Issue by xuhdev** [Alexander-Miller/treemacs#701]
When opening a file in a git repository, it would be convenient to automatically treat the git repository as a project (absent of a manual project addition).

**Comment by Compro-Prasad** [comment]
The top most level should be treated as project in case of nested repositories.

**Comment by Alexander-Miller** [comment]
Yes and no.

I'm not going to do this myself - projectile already sees your git repositories and adds them as projects. All that's left if for treemacs to use that information, and that happens in https://github.com/Alexander-Miller/treemacs/issues/489

In the meantime the occasional call to `treemacs-add-and-display-current-project` shouldn't be too much trouble.
