### ISSUE TITLE
Is there convenient way to close *compilation* buffer after run python code?

### ISSUE THREAD

**Issue by wztdream** [Alexander-Miller/treemacs#703]
Hi
Treemacs is great, but there is a noisy problem. 
Suppose I opened a python file from treemacs, then run the code, there will be a "compilation" buffer appear at the bottom of the window, the width is across the whole window. Suppose my cursor is still in the python code buffer, the problem is how to close this "compilation" buffer? Maximize the python code buffer will not work, it seems this "compilation" buffer is out of control of treemacs. I have to switch to "compilation" buffer to delete it. Or I can turn off treemacs first then maximize the python code buffer, it also works. But both method are a little noisy, as running a testing code is very often. **So is there a convenient way to close this "compilation" buffer without switch to it or turn off treemacs first?** The best feature is that I run `M-x maximize-window` from python code buffer then all other window, except treemacs buffer, are hidden.
![example](https://user-images.githubusercontent.com/39213018/88870475-074a2780-d248-11ea-9c39-49184b50f5ba.jpeg)

**Comment by yyoncho** [comment]
`SPC c k`

**Comment by wztdream** [comment]
Thank you both, I can close the complication buffer by M-x close-complication-window, bounded to `SPC c d`
