### ISSUE TITLE
(treemacs-fringe-indicator-mode nil) in .emacs does not remove the fringe

### ISSUE THREAD

**Issue by ClementMassonnaud** [Alexander-Miller/treemacs#706]
Hi,

I copied the default 'use-package' code from the documentation to my .emacs.
However when I change `(treemacs-fringe-indicator-mode t)` to `(treemacs-fringe-indicator-mode nil)`, it does not seem to have any effect. At restart the fringe is back on

I am using emacs 26.3

Thanks!

**Comment by Compro-Prasad** [comment]
Are you seeing the fringe indicator or the fringe itself?

**Comment by Alexander-Miller** [comment]
You have to use -1 to disable a minor mode, not nil: `(treemacs-fringe-indicator-mode -1)`
