### ISSUE TITLE
How to add new icon (Meson build support)

### ISSUE THREAD

**Issue by johhnry** [Alexander-Miller/treemacs#709]
Hi,

Simple question : how can I add a new icon in treemacs?

Specially, I want to have support for [meson](mesonbuild.com/) build files. 

Currently I have : 

![Capture d’écran de 2020-08-13 22-02-30](https://user-images.githubusercontent.com/35373357/90181500-d8d45c80-ddb0-11ea-8267-767e746ff2e9.png)

Btw : I am using spacemacs so I don't really know if this is related to only treemacs or the whole distribution...

**Comment by Alexander-Miller** [comment]
To add an icon to your config see here: https://github.com/Alexander-Miller/treemacs#custom-icons

To contribute an icon see https://github.com/Alexander-Miller/treemacs#custom-icons, especially the example at the end.

**Comment by Alexander-Miller** [comment]
Correction: 2nd link should have pointed to https://github.com/Alexander-Miller/treemacs#contributing

**Comment by johhnry** [comment]
Hi,

Thanks for your answer.

I was about to make a pull request to add the meson icon but then I saw that there's already an icon [here](https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-icons.el#L394) but a meson build file doesn't have a `.meson` extension but rather the name `meson.build` so that's why it doesn't work properly : 

![Capture d’écran de 2020-08-20 10-52-26](https://user-images.githubusercontent.com/35373357/90749450-c0de6a80-e2d3-11ea-8014-b4185625cd56.png)

Also the logo changed as you can see [here](https://github.com/mesonbuild/meson/commit/011c77ee22f600548bffaf94e67608b31a3722c8) and in the legal information it's written : 

`If you are a third party and want to use the Meson logo, you must first obtain written permission from Jussi Pakkanen.`

So what do we do?

**Comment by Alexander-Miller** [comment]
> a meson build file doesn't have a .meson extension but rather the name meson.build so that's why it doesn't work properly

The full name is checked first, so fixing that is trivial. I'll drop a patch in a bit.

> Also the logo changed as you can see here and in the legal information it's written

And now it's the kind of purple that would probably be barely visible as a small icon on a dark theme, so I think we can safely pass this update.
