### ISSUE TITLE
[Feature Request] Mouse-click support

### ISSUE THREAD

**Issue by seagle0128** [Alexander-Miller/treemacs#71]
Is there any plan to support mouse-click operations in `treemacs`, like `neotree`? It's better UI experience for the people,  especially for newbies.

**Comment by Alexander-Miller** [comment]
Mouse support is already around, you just need to click the icon. I plan to expand the clickable area eventually.

**Comment by seagle0128** [comment]
Is the functionality in the newer release? It's not in 1.11.3, right?

**Comment by Alexander-Miller** [comment]
Uuuh, no, it just doesnt work as of now. It used to, and afaik I didnt change the code, so I guess its an emacs version thing again? I did install emacs25 now, as well.

Either way, I'll just make the whole line clickable when I fix this.

**Comment by Alexander-Miller** [comment]
Fix is off, version is bumped, it's 1.11.5 by now. As always let me know if everything's working.

**Comment by seagle0128** [comment]
Thank you. Waiting for the melpa update.

**Comment by seagle0128** [comment]
Cool! Close it.
