### ISSUE TITLE
treemacs-root-up/down freezes cursor 

### ISSUE THREAD

**Issue by cheeze2000** [Alexander-Miller/treemacs#710]
### Expected Behaviour
Upon selecting the directory with cursor, pressing `h` or `l` would change the project root.

### Actual Behaviour
Pressing `h` or `l` freezes the cursor but doesn't freeze Emacs. `C-g` will somehow make Emacs work again but the project root is unchanged.

### Steps to Reproduce
```elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(setq-default straight-use-package-by-default t)
(straight-use-package 'use-package)
(use-package treemacs)
```
1. Use the `init.el` above
2. `M-x treemacs`
3. `M-x toggle-debug-on-quit`
4. `h` or `l`
5. `C-g` to show backtrace

This is what happens when I did `l` on my `.emacs.d` directory.
```
Debugger entered--Lisp error: (quit)
  file-name-directory("/")
  treemacs-find-file-node("/home/cheeze/.emacs.d" nil)
  treemacs-root-down()
  funcall-interactively(treemacs-root-down)
  call-interactively(treemacs-root-down nil nil)
  command-execute(treemacs-root-down)
```

### Details
GNU Emacs 27.1
Ubuntu 20.04.1 LTS (WSL 2)

**Comment by SketchyLxve** [comment]
I was able to reproduce this issue on the following environment:
- **OS**: Manjaro-Linux (20.0.3)
- **Emacs**: GNU Emacs 26.3
- **Treemacs**: 20200802.819

Following the steps specified in the issue, if done whilst there's only a single directory in the treemacs window, it will freeze. And doing `C-g` will somehow "unfreeze" it.

**Comment by Alexander-Miller** [comment]
Confirmed and working on a fix.
