### ISSUE TITLE
treemacs automatically switches layout according to the current buffer

### ISSUE THREAD

**Issue by c02y** [Alexander-Miller/treemacs#714]
For example, I open a file in repoA(git repo), and `M-0` will show the layout of this repo, then I open a file in repoB with just keybinding like `C-x C-f` or from recentf list (not projectile related command), then the layout of the treemacs is still the old one, if I close the treemacs window, `M-0` again to open it, the layout is still the old repo.

How to automatically refresh the layout according to the current buffer?
- When I leave the treemacs window open, switch or open another buffer which is in another repo, the treemacs window will auto refresh
- When I close the treemacs window, switch or open another buffer which is in another repo, `M-0` to open the treemacs, the layout will be the directory structure of current buffer.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Yanhao** [comment]
1

**Comment by Alexander-Miller** [comment]
Sorry for the late response, I guess the issue got buried somewhere. At least stale bot managed to remind me. 

At any rate there's a few options to quickly manage projects:

- Just add both projects to treemacs. See also `treemacs-edit-workspaces`
- Add the current project with `treemacs-add-and-display-current-project` or `treemacs-display-current-project-exclusively`
- Use `treemacs-project-follow-mode`
