### ISSUE TITLE
Can treemacs define tab action function be used like this?

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#717]
Should I be able to do this:  
```lisp
(treemacs-define-TAB-action
   'file-node-closed
   #'treemacs-peek)
```

And then when open a closed file node, not get this?

```
treemacs-TAB-action: Wrong number of arguments: (0 . 0), 1
``` 

In other words, this works if the event is `#'treemacs-visit-node-in-most-recently-used-window`.

**Comment by Alexander-Miller** [comment]
Should be doable with a small workaround - the TAB-action functions all expect `(treemacs-current-button)` to be passed to them from the infrastructure above them, `treemacs-peek` does that on its own - that's the wrong number of arguments you see.

Keyword being *should* - for whatever reason the simple setup doesn't work for me, so there's some R&D to be done first.

**Comment by simurgh9** [comment]
Well, for now I'll be leaving this alone! As always, thank you!
