### ISSUE TITLE
j and k navigation doesn't work

### ISSUE THREAD

**Issue by ezjones** [Alexander-Miller/treemacs#72]
By default pressing j should go to the next line. Right now it doesn't work after a clean install.

When I press j i get:

    j is undefined

**Comment by Alexander-Miller** [comment]
[The keybind is still there](https://github.com/Alexander-Miller/treemacs/blob/master/treemacs-evil.el#L38). Are you sure treemacs-evil is installed and loaded?

**Comment by ezjones** [comment]
Oh i see what's going on. I dont use evil mode.

 I thought j and k would work anyways since they are not assigned to anything in that buffer.

**Comment by Alexander-Miller** [comment]
Nope, if you use evil, but not treemacs-evil youre gonna have a bad time. The kind of bad time where half the keybindings dont work.
