### ISSUE TITLE
Is a bug about treemacs-tag-follow-mode?

### ISSUE THREAD

**Issue by yyangdid** [Alexander-Miller/treemacs#720]
1. create a org file  `~/.emacs.d/x.org` :
```
* aaa
** bbb
bbb
*** ccc
ccc
* ddd
ddd
** eee
eee
** fff
fff
```
2. enable treemacs-tag-follow-mode,
3. edit x.org file, insert a header, save file
4. delete a header, save file.
get this error:
`[Treemacs Error] Encountered error while following tag at point: (wrong-type-argument stringp (~/.emacs.d/x.org ddd eee))`

windows 10 x64   Emacs 27

i think the folder name is important, the folder name include dot? this dot ` . `

**Comment by Alexander-Miller** [comment]
I have the error reproduces locally. Working on a fix now.

**Comment by yyangdid** [comment]
Quickly   and   Professional   👍

**Comment by Alexander-Miller** [comment]
It helps that I got your email when I was deciding what to do next :man_shrugging:

**Comment by Alexander-Miller** [comment]
Should be fixed now.

**Comment by yyangdid** [comment]
yes, fixed,  thank you. 🥇
