### ISSUE TITLE
About cursor position in org file when treemacs-tag-follow-mode is enabled.

### ISSUE THREAD

**Issue by yyangdid** [Alexander-Miller/treemacs#721]
1. create a org file `~/x.org`
```
* aaa
aaa
** bbb
bbb
*** ccc
```
save file
2. Enable treemacs-tag-follow-mode .
3. this is the cursor symbol : `▍`
this is the cursor position:
```
* aaa
aaa
** bbb
bbb
*** ccc▍
```
4. Now edit x.org file , press the `Backspace` key , delete `ccc` : `Backspace` `Backspace` `Backspace`

Now the cursor jump to there:
```
* aaa
aaa
▍** bbb
bbb
*** 
```

Maybe you want this:
```
* aaa
aaa
** bbb
bbb
*** ▍
```

**Comment by Alexander-Miller** [comment]
Confirmed and working on a fix.

**Comment by Alexander-Miller** [comment]
I made a mistake in the last patch, it should be all fixed now.

The whole tag-following feature is rarely used (I do not use it myself), so the likelihood of running into bugs like these is a bit higher than for other parts of treemacs, but if you keep reporting this stuff I will keep fixing it.

**Comment by yyangdid** [comment]
Thank you 👍 👍 👍
