### ISSUE TITLE
Invalid Version Syntax Error

### ISSUE THREAD

**Issue by ZanderKraig** [Alexander-Miller/treemacs#722]
I started using the latest Spacemacs configuration (develop branch) only yesterday with Emacs 27.1 and I happen to have run into a problem with Treemacs. For some reason, `SPC f t` (for opening the file tree) does not work. Instead it outputs an error message: 

`Invalid version syntax: ‘'’ (must start with a number)`. 

So, I tried using `SPC SPC dired` instead (and its equivalent `M-x dired`) but I was greeted by the same error message again. One of the reasons I switched over from the master to the develop branch was to use Treemacs (apart from the numerous other improvements) but unfortunately, now I can't even operate on directories from Spacemacs which is really frustrating. 

I performed the same operations again with **toggle-debug-on-error** enabled and some Lisp error back-trace was output which I have attached in the file: [back-trace.txt](https://github.com/Alexander-Miller/treemacs/files/5276471/backtrace.txt). Is there any way to fix this?

Note:
The \*Messages\* buffer in Spacemacs displayed the exact error message as `version-to-list: Invalid version syntax: ‘'’ (must start with a number)`. I am mentioning this so as to not leave out any possible detail.

I'm not sure but this error may be related to the problem corrected by this commit:
[53e8bccf334098f3a9e573a3e8dc8e84aab80c50](https://github.com/Alexander-Miller/treemacs/commit/53e8bccf334098f3a9e573a3e8dc8e84aab80c50)

**Comment by Alexander-Miller** [comment]
Hooray for more edge cases

Now, before I clobber this bug into submission I am curious: what exactly does `(shell-command-to-string "where python")`  output that it passes through `file-exists-p` but ends up with a `'` when you ask for a version?

**Comment by ZanderKraig** [comment]
@Alexander-Miller, thanks for considering the issue I posted. Here is the output of `(shell-command-to-string "where python")`:
```
"c:\\Microsoft\\AndroidSDK\\25\\platforms\\android-25\\skins\\WQVGA400\\cygwin\\bin\\python
c:\\Users\\jsvhp\\AppData\\Local\\Programs\\Python\\Python38\\python.exe
c:\\Users\\jsvhp\\anaconda3\\envs\\python-3.6.8\\python.exe
c:\\Microsoft\\AndroidSDK\\25\\extras\\android\\m2repository\\com\\android\\support\\gridlayout-v7\\21.0.0\\emacs-26.3\\bin\\python.exe
"
```

Apologies for not mentioning something very important. I actually happen to keep the configuration of spacemacs within the /home/\<user-name\> directory of my **Cygwin installation**(on Windows 10) and the python my Cygwin bash points to (and apparently what Emacs picks up based on the output of `(shell-command-to-string "where python")`) is **version 2.7**. I switched my configuration over to the default location on windows (under AppData/Roaming) and treemacs and everything else is working pretty fine. So, I believe the problem must have been with the python version that Emacs happened to use(I'm guessing python 2 is not supported).

This is the output of `(shell-command-to-string "where python")` after I changed the location of the configuration:
```
"c:\\Users\\jsvhp\\AppData\\Local\\Programs\\Python\\Python38\\python.exe
c:\\Users\\jsvhp\\anaconda3\\envs\\python-3.6.8\\python.exe
c:\\Microsoft\\AndroidSDK\\25\\extras\\android\\m2repository\\com\\android\\support\\gridlayout-v7\\21.0.0\\emacs-26.3\\bin\\python.exe
"
```

My, guess is that this problem was specific to me(since I have a crazy set of configurations on my computer and everything is really confusing) and perhaps not really a bug. I would like your opinion on this @Alexander-Miller. I am nevertheless deeply grateful to you @Alexander-Miller as I could not have solved this without your suggestion to try out `(shell-command-to-string "where python")`.

**Comment by Alexander-Miller** [comment]
> I do have to add though that the fact that ' is returned from (shell-command-to-string "where python") might indicate there is something wrong but I am a newbie and I have no idea.

It's not this output itself that contains a `'`, but rather the result of calling one of these items (after making sure that it actually exists) with a `--version` flag that produces the single quote. So it's probably just some strange version string format.

We could debug around and maybe find something eventually, but the situation is already resolved for you and I don't think knowing the exact cause would change my solution - Emacs has AFAIK no way to check whether some string is a valid version, so I'll just make the check ignore errors.

**Comment by ZanderKraig** [comment]
I understand @Alexander-Miller. Thanks for the help and continue your good work.
