### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by zw963** [Alexander-Miller/treemacs#725]
![image](https://user-images.githubusercontent.com/549126/94566161-9e5d4b00-029c-11eb-991d-92f0f6910b31.png)

**Comment by SanjayDevTech** [comment]
Shall I fix this typo @zw963 ?
Could you assign this issue to me

**Comment by zw963** [comment]
@SanjayDevTech , i think i can't assign this issue to someone. no permission.

**Comment by Alexander-Miller** [comment]
I don't do any ticket assigning. Dropping an FYI if you want to contribute is enough.
