### ISSUE TITLE
Creating a new directory doesn't expand 'abbreviated' paths when necessary

### ISSUE THREAD

**Issue by ksqsf** [Alexander-Miller/treemacs#726]
Before:
<img width="245" alt="截屏2020-09-29 23 50 26" src="https://user-images.githubusercontent.com/23358293/94582193-8e4e6700-02ae-11eb-93de-095074813002.png">

After creating a new directory `/Labs/Docs/lab2` and treemacs auto-refreshes, the 'abbreviated' path is not expanded,
<img width="237" alt="截屏2020-09-29 23 51 47" src="https://user-images.githubusercontent.com/23358293/94582377-bfc73280-02ae-11eb-9e1b-4a2ef78e9046.png">

Even though lab1 and lab2 are on the same level, treemacs is confused and thinks lab2 is inside lab1.

Refreshing manually (`g`) can solve this problem.

**Comment by Alexander-Miller** [comment]
You created the new directory externally, and then waited for treemacs to pick up on the change, right?

**Comment by ksqsf** [comment]
@Alexander-Miller Yes. I created the directory in dired, and switch to any buffer that treemacs recognizes.

**Comment by Alexander-Miller** [comment]
Yep, that stuff is all sorts of tricky. I discovered a set of uncovered edge cases just by replicating your issue. 

Working on a fix now.

**Comment by Alexander-Miller** [comment]
I hope I've caught everything now. Let me know if you find anything else.
