### ISSUE TITLE
TUI mode in OS X

### ISSUE THREAD

**Issue by kujohn** [Alexander-Miller/treemacs#727]
I am running emacs inside of tmux and kitty terminal on OSX. Doesn't look like treemacs render correctly in TUI?

![Screen Shot 2020-09-29 at 4 26 18 PM](https://user-images.githubusercontent.com/1356936/94626733-82dc4b00-0270-11eb-9e09-d9b342fd25e7.png)

**Comment by Alexander-Miller** [comment]
All you're missing is the `+` & `-` icons for closed & opened directories, but I think there's themes removing those. What's your treemacs config look like?

**Comment by kujohn** [comment]
I had enable treemac via Doom's `package.el`. Did not add any configuration for treemacs.

**Comment by kujohn** [comment]
Ahh, I loaded the default theme and refreshed and it works! I guess the doom treemac themes don't show them. Thanks!
