### ISSUE TITLE
dired buffers do not display icons until refreshing

### ISSUE THREAD

**Issue by xuhdev** [Alexander-Miller/treemacs#729]
I'm using spacemacs, and `dired-mode-hook` contains `treemacs-icons-dired-mode`:

    dired-mode-hook is a variable defined in ‘dired.el’.
    Its value is
    (dired-quick-sort treemacs-icons-dired-mode ranger-set-dired-key drupal-mode-bootstrap)

However, firing up dired won't have icons displayed. However, if I run `revert-buffer` to refresh the dired buffer once, the icons will display.

**Comment by Alexander-Miller** [comment]
I just tried it with the lastest develop spacemacs and treemacs/ranger packages and and apart from needing a small patch for icon background color correction with ranger the icons showed up just fine. 

So try updating everything. If that doesn't work I will need to see your spacemacs config.

**Comment by xuhdev** [comment]
Looks like the reason is the presence of `dired-quick-sort`. But this is weird, because `treemacs-icons-dired-mode` should load after `dired-quick-sort`.

Relevant line: `(dired-quick-sort-setup)`

PS: I'm the author of `dired-quick-sort` but I couldn't figure out anything on my end

**Comment by Alexander-Miller** [comment]
Try passing the `no-revert` flag to `dired-sort-other`. If you don't need the revert to happen that will be all we need.

**Comment by xuhdev** [comment]
Look like I need to have `no-revert` be off. One thing I don't understand is that treemacs should be loaded later than `dired-quick-sort`, and whatever `dired-quick-sort` has done shouldn't affect the insertion of icons. What else do you think might be happening here?

**Comment by Alexander-Miller** [comment]
Treemacs insert its icons in `dired-after-readin-hook`, but knows to prevent icons being inserted twice over, and the way dired-quicksort is set up those hooks do run twice. First in dired-mode's hook when dired-quicksort reverts the buffer, and again as part of dired-mode's normal setup routine.

I see two solutions: either you provide a hook that runs at the end of `dired-quick-sort`. That will allow me reset some values so the icons are inserted again. Or you pass a no-revert flag and then call `(run-with-timer 0 nil #'revert-buffer)`, so the revert happens after all the other hooks have run.

**Comment by xuhdev** [comment]
Actually the solution is right under my eyes but I ignored it: https://gitlab.com/xuhdev/dired-quick-sort/-/merge_requests/3

Thanks for providing all the help!
