### ISSUE TITLE
treemacs modify theme

### ISSUE THREAD

**Issue by 354651432** [Alexander-Miller/treemacs#732]
when treemacs opened, I can use `M-X` `treemacs-load-theme` modify the theme, and `gr` to refresh,
I put the code to `~/.doom.d/config.el` but errored with the message "void function treemacs-load-theme".

I am a newcomer,  look for a resolve

**Comment by Alexander-Miller** [comment]
Long answer: you will need to learn about how Emacs handles lazy-loading and what it calls autoloading. Here's links that will help get you there:

- https://www.gnu.org/software/emacs/manual/html_node/eintr/Autoload.html
- https://www.gnu.org/software/emacs/manual/html_node/elisp/Hooks-for-Loading.html

Short answer: There  is no autoload for `treemacs-load-theme`, you should use `with-eval-after-load`. If you use use-package then you can use the installation example from the readme.
