### ISSUE TITLE
Add icons to folders too

### ISSUE THREAD

**Issue by system306** [Alexander-Miller/treemacs#733]
In editors like VSCode, folders like `components` or `test` are given a specific icon.
It would be nice if this functionality existed here too.

**Comment by andreyorst** [comment]
Yes, a general mechanism for theming directories would be nice. I believe that #452 whould be solved with such change as well.

**Comment by Alexander-Miller** [comment]
I had this idea for a while myself. I'll definitely implement this eventually.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by ikapo** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Support is in: https://imgur.com/a/FEPIzSb
Adding your own directory icons is described here: https://github.com/Alexander-Miller/treemacs#custom-icons
