### ISSUE TITLE
xref-pop-marker-stack puts Emacs in unusable state, if Treemacs buffer is in the stack

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#734]
I have multiple projects listed in Treemacs, and often search within these projects by using Emacs' inbuilt `project.el`. My typical usecase is to select project in treemacs and run `project-find-regexp` function. Since treemacs sets the current directory to selected one, project always able to find root of active project, and execute the search. However this action puts Treemacs' buffer into the marker stack, and when popping this stack afterwards I often put Emacs into unusable state, when I can no longer manipulate windows.

Minimal init.el:

```emacs-lisp
(defvar package-archives)
  (setq package-archives
        '(("gnu" . "https://elpa.gnu.org/packages/")
          ("melpa" . "https://melpa.org/packages/")))

(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(use-package treemacs
  :ensure t
  :config
  (treemacs))
```

### Steps:
After Emacs started, and Treemacs buffer appeared, select some directory in the filetree and call `project-find-regexp` while treemacs buffer is active.
When `*xref*` buffer appears, select any item.
After successful jump press <kbd>Alt+,</kbd> or call `xref-pop-marker-stack`

#### Outcome
Treemacs buffer shown in current window:

![image](https://user-images.githubusercontent.com/19470159/97462772-242dee00-1950-11eb-8e99-e8c05af5d927.png)

Trying to kill any window will produce the following error:

```
Window #<window 13 on core_test.fnl> has same side left as window #<window 7 on  *Treemacs-Scoped-Buffer-#<frame emacs@s540 0x233b240>*> but no common parent
```

**Comment by andreyorst** [comment]
Seems I've found a workaround for this problem:

```emacs-lisp
(use-package xref
  :straight nil
  :hook (xref-after-jump . aorst/xref-remove-treemacs-from-marker-ring)
  :requires seq
  :config
  (defun aorst/xref-remove-treemacs-from-marker-ring ()
    (if-let ((elem (seq-find (lambda (elt)
                               (and elt (string-match-p
                                         " \*Treemacs-Scoped-Buffer.*"
                                         (buffer-name (marker-buffer elt)))))
                             (cddr xref--marker-ring))))
        (setq xref--marker-ring
              `(,(car xref--marker-ring)
                ,(- (cadr xref--marker-ring) 1)
                .
                ,(seq-into
                  (append
                   (seq-remove
                    (lambda (elt) (eq elt elem))
                    (cddr xref--marker-ring))
                   '(nil)) ;; appending nil, so the length of the vector won't change
                  'vector))))))
```

In short, I'm looking if the vector contains Treemac's buffer, and remove it, then append `nil` to the resulting list so the overall length won't change, and decrement the counter. I'm not sure if everything is correct though, but it works. I guess Treemacs should do this housekeeping as without this hook Emacs fully unusable.

**Comment by andreyorst** [comment]
After reading a bit more about ring, I've narrowed this down to
```emacs-lisp
(use-package xref
  :straight nil
  :hook (xref-after-jump . aorst/xref-remove-treemacs-from-marker-ring)
  :requires seq
  :config
  (defun aorst/xref-remove-treemacs-from-marker-ring ()
    (when-let ((i (seq-position (ring-elements xref--marker-ring)
                                " \*Treemacs-Scoped-Buffer.*"
                                (lambda (elem re)
                                  (when elem
                                    (string-match-p re (buffer-name (marker-buffer elem))))))))
      (ring-remove xref--marker-ring i))))
```

**Comment by Alexander-Miller** [comment]
I have looked around and it looks like there is no good way to avoid this with the current xref api. The current buffer is pushed to/popped off the marker stack indiscriminately. Only some invasive advice can keep that from happening.

Yours works, but it does prevent *any* buffer from going on the stack, which might be inconvenient. Instead we can override the marker push to check if it is pushing a treemacs buffer, and if it does we instead use the next buffer (the one that would be used if you press `RET` on a file):

```Elisp
(defun treemacs--compatibility-xref-push-marker-stack (original-fn &optional m)
  (let ((m (or m (point-marker))))
    (when (buffer-local-value 'treemacs--in-this-buffer (marker-buffer m))
      (with-current-buffer (window-buffer (next-window (selected-window) nil nil))
        (setf m (point-marker))))
    (funcall original-fn m)))

(advice-add #'xref-push-marker-stack :around #'treemacs--compatibility-xref-push-marker-stack)
```

Another option is to use window-purpose, its window re-use rules will prevent treemacs from popping up where it doesn't belong if the rules are set up right.

I'll also make an emacs bug report for this. There should be some kind of exclusion mechanism to prevent side-windows from popping up in a place that is not a side. Or the marker-pop could check if the target buffer is already visible in some other window and move there instead (that would also be easy enough to do with advice).

> but I'm not sure how I can reliably et the name of treemacs buffer when jumping.

Treemacs' buffers are stored rather deeply, you can get to the current one like this:

```Elisp
(treemacs-scope-shelf->buffer (treemacs-current-scope-shelf))
```

**Comment by andreyorst** [comment]
> Yours works, but it does prevent any buffer from going on the stack, which might be inconvenient. 

I've thought on this one, and decided that this is fine, because there's is no buffer to return to anyway. Well, if it could just jump to Treemacs instead it would be nice, but I'm not sure if I want this. But I see your point.

Thanks for pointing how to get Treemacs buffer

**Comment by andreyorst** [comment]
Actually I've still managed to put Treemacs' buffer into marker stack even with my code, so this is not 100% solution.

**Comment by Alexander-Miller** [comment]
Exactly.

**Comment by brc** [comment]
Just ran into this for the first time ever after using Treemacs for the last ~3 years with Spacemacs. And I'm not a casual user. Not sure what I did to get into the situation -- my key lossage ring filled up pretty quickly during the confusion and disbelief of trying to escape the situation. 😂 😭 

This is amazing. I'm stunned!
