### ISSUE TITLE
Margin between icons and texts

### ISSUE THREAD

**Issue by minikN** [Alexander-Miller/treemacs#735]
Hello,

is it possible to adjust the margin/space between the icons and the text (name of file/folder)

![image](https://user-images.githubusercontent.com/1888338/97615789-0928b000-1a1c-11eb-8daf-6a5ec5ae952f.png)

Thanks in advance.

**Comment by Alexander-Miller** [comment]
Sure, you can transform the displayed file names however you want:

```Elisp
(setf treemacs-file-name-transformer (lambda (it) (concat " " it))
      treemacs-directory-name-transformer (lambda (it) (concat " " it)))
```

(Keep in mind that the transformers will be called for *every* file on display, so they shouldn't do anything expensive.)

**Comment by minikN** [comment]
@Alexander-Miller Thanks for your answer. But I'd actually like to see less space, not more. Is this possible as well?

**Comment by minikN** [comment]
Also, on that note (maybe I should open a new ticket for it). Would you know why some Icons appear larger than usual?

![image](https://user-images.githubusercontent.com/1888338/97709198-3c218100-1aba-11eb-9813-d9b793de41cf.png)

**Comment by Alexander-Miller** [comment]
That is possible, too. The space is part of the icon, so they all need to be changed. Treemacs also expects icons to be 2 characters long, so we need to delve into display text properties to replace the whitespace in the icon with one that is shorter:

```Elisp
(treemacs-create-theme "Default With Smaller Space"
  :extends "Default"
  :config
  (let ((icons (treemacs-theme->gui-icons theme)))
    (maphash
     (lambda (ext icon)
       (puthash ext (concat (substring icon 0 1)
                            (propertize " " 'display '(space . (:width 0.5))))
                icons))
     icons)))
(treemacs-load-theme "Default With Smaller Space")
```

**Comment by minikN** [comment]
Thanks!
