### ISSUE TITLE
performance hit when opening large repo

### ISSUE THREAD

**Issue by Lyonsclay** [Alexander-Miller/treemacs#736]
I am using spacemacs with osx catalina and when I open this repo(https://github.com/whosonfirst-data/whosonfirst-data-admin-us) in treemacs I get a long delay and a bunch of git processes running.
I have set treemacs-max-git-entries to 200 and added the (data) directory and (.geojson) file type to .gitignore with no change in behaviour.
In issue #175 you mentioned adding the variable treemacs-git-command-pipe, but I am unsure in how to use that.

**Comment by Alexander-Miller** [comment]
> ❯❯❯ git status                                                                                                               
On branch master                                                                                                             
Your branch is up to date with 'origin/master'.                                                                              
                                                                                                                             
                                                                                                                             
> It took 22.01 seconds to enumerate untracked files. 'status -uno'                                                            
may speed it up, but you have to be careful not to forget to add                                                             
new files yourself (see 'git help status').                                                                                  
nothing to commit, working tree clean  

It's not  a treemacs problem - there are so many untracked files in that repo that git itself struggles to enumerate them all. There is nothing treemacs can do directly, you will not see proper git integration for that project.

>  In issue #175 you mentioned adding the variable treemacs-git-command-pipe, but I am unsure in how to use that.

That is the first option for a workaround. Treemacs asks for git status information by calling `git status --porcelain --ignored . ` The value of this variable is simply appended at the end of this command. I thought it would be used to pipe git's output into a reverse grep to remove unneeded information, hence the name. You can use to add `"-uno"` to treemacs' git commands.

The downside would be that you lose all information about untracked files.

The other option is for me to develop a blacklist of projects for git-mode to ignore. That would take some time.

**Comment by Lyonsclay** [comment]
Thanks for the explanation and I will give `"-uno"` a try :)

**Comment by Lyonsclay** [comment]
Adding `-uno` definitely reduced the time git took in processing but there was still a hit so I hoped I could use dir-locals.el with `((nil . ((treemacs-git-mode . nil))))`  but that didn't work, I might need the `eval` way of doing it but that is beyond me technically, so I opted to turn it off globally while I worked with this repo.

**Comment by Alexander-Miller** [comment]
Stayin alive.
