### ISSUE TITLE
Is it possible to automatically expand the root node of a workspace when opening treemacs?

### ISSUE THREAD

**Issue by MPE2016** [Alexander-Miller/treemacs#740]
Hi there,

Title pretty much says it all. When I open treemacs (M-x treemacs) the node of the workspace that is shown is always collapsed. Like so:
![afbeelding](https://user-images.githubusercontent.com/15818884/98465832-01ab9880-21cc-11eb-9aba-3a7048535b6f.png)

What I would really like is for the root node of the project to automatically always uncollapse when opening treemacs, like so:
![afbeelding](https://user-images.githubusercontent.com/15818884/98465872-4e8f6f00-21cc-11eb-8966-e16609a8a0f0.png)

I have looked extensively at the documentation, but couldn't figure it out myself. Is there a way to do that?

All the best,

MPE

**Comment by Alexander-Miller** [comment]
Sorry for the late reply, the email has slipped through the cracks.

What you're asking for is doable, but I'd have to change how `treemacs-select-hook` works - I assume you wouldn't want to expand your project every time you select treemacs, but only when the treemacs buffer didn't exist previously. So I would modify the hook to pass treemacs'  previous visibility (see `treemacs-current-visibility`). Then you could do something like this:

```Elisp
(defun treemacs-expand-when-first-used (visibility)
  (when (eq visibility 'none)
    (treemacs-do-for-button-state
     :on-root-node-closed (treemacs-toggle-node)
     :no-error t)))
```

**Comment by MPE2016** [comment]
Hi Alexander,

> /Sorry for the late reply, the email has slipped through the cracks./
> 
That's totally okay, no worries.

Your description is indeed how I would imagine the function to work, 
but it also makes me think of something else. What would happen if I 
were to switch to another workspace? I would like for those to be open 
as well. If it's not too much of a hassle it would be great if you 
could add that, but you would already make me very happy if you'd 
include the functionality as described below.

All the best,

MPE

Op zaterdag 14 november 2020 om 7u22 schreef Alexander-Miller 
<notifications@github.com>:

**Comment by Alexander-Miller** [comment]
There's a hook for workspaces as well. Grab the latest version and you can make both work like this:

```Elisp
(defun treemacs-expand-when-first-used (&optional visibility)
  (when (or (null visibility) (eq visibility 'none))
    (treemacs-do-for-button-state
     :on-root-node-closed (treemacs-toggle-node)
     :no-error t)))

(add-hook 'treemacs-select-functions #'treemacs-expand-when-first-used)
(add-hook 'treemacs-switch-workspace-hook #'treemacs-expand-when-first-used)
```

**Comment by MPE2016** [comment]
Hi Alexander,

Thanks a lot for doing this!

And it's probably me, but it isn't completely working yet. When I 
switch workspaces it works exactly as expected and the root node 
expands. But the first time I open treemacs, the default workspace is 
still collapsed.

I tried fixing it myself by adding a different hook, which looked 
something along these lines:

> (add-hook 'treemacs-hook #'treemacs-expand-when-first-used)

But that didn't get it working, helas.

Anyway, again, thank you for your time.

All the best,

Maarten

Op dinsdag 17 november 2020 om 13u09 schreef Alexander-Miller 
<notifications@github.com>:

**Comment by Alexander-Miller** [comment]
It works as expected on my end. Do you have the latest version? The changes from https://github.com/Alexander-Miller/treemacs/commit/26ab9ea95e53f7ea28d1cb2d83529bda9bdfcdea must be included or the hook will do nothing. You'll know you have an up-to-date treemacs when `treemacs-select-functions` is properly defined and documented.

**Comment by MPE2016** [comment]
Its working, great!

I think the problem was that on my first attempt I only replaced the 
changed files from 26a9ea, but that wasn't enough to get the whole 
thing working.

After a removal of the melpa version of treemacs and a manual install 
of the latest github version it immediately spurred into action. Just 
like you said:)

Thanks again for your time and patience. Treemacs is great. Keep up the 
good work!




Op maandag 7 december 2020 om 9u20 schreef Alexander-Miller 
<notifications@github.com>:

**Comment by Alexander-Miller** [comment]
> I think the problem was that on my first attempt I only replaced the
changed files from 26a9ea, but that wasn't enough to get the whole
thing working.

Sounds like the old byte code was still being used. For this stuff you need to remove the old .elc files or recompile the files you have changed. Preferably the latter for performance reasons.

**Comment by MPE2016** [comment]
Correct. I hadn't touched the .elc files.

Thanks again!

Cheers,

Maarten

Op woensdag 9 december 2020 om 9u24 schreef Alexander-Miller 
<notifications@github.com>:
