### ISSUE TITLE
Bookmark restoration seems broken?

### ISSUE THREAD

**Issue by minad** [Alexander-Miller/treemacs#745]
I was wondering before if it's my code (#744) or if its treemacs but it seems treemacs has problems restoring bookmarks when I have selected a node in the imenu.

1. Select a node
2. Call `bookmark-set` in the treemacs buffer, which stores the path to the node
3. Restart emacs
4. Restore the treemacs bookmark, I am getting a listp type error from inside the `treemacs--bookmark-handler`

It seems restoring works if I am not restarting. Is it a serialization problem?

Example backtrace:

~~~ elisp
Debugger entered--Lisp error: (wrong-type-argument listp "/home/user/.config/emacs/init.el")
  -last-item("/home/user/.config/emacs/init.el")
  treemacs--find-custom-dir-node(("/home/user/.config/emacs/init.el" "Functions" "warp--log"))
  treemacs-goto-node(("/home/user/.config/emacs/init.el" "Functions" "warp--log"))
  treemacs--bookmark-handler(("Treemacs - emacs: warp--log" (treemacs-bookmark-path "/home/user/.config/emacs/init.el" "Functions" "warp--log") (handler . treemacs--bookmark-handler)))
  bookmark-handle-bookmark("Treemacs - emacs: warp--log")
  bookmark--jump-via("Treemacs - emacs: warp--log" pop-to-buffer-same-window)
  bookmark-jump("Treemacs - emacs: warp--log")
~~~

**Comment by Alexander-Miller** [comment]
I'll investigate.

It's possible that the bookmark integration before the whole scoping business from #744. If that's the case and bookmarks need a reliable buffer name we might have a problem.

**Comment by Alexander-Miller** [comment]
Update: The problem is specific to tag nodes, files are working.

**Comment by minad** [comment]
> Update: The problem is specific to tag nodes, files are working.

Yes, this is what I meant by imenu.

**Comment by Alexander-Miller** [comment]
Ok, here's where it gets ugly: Treemacs actually has no way to "move to a tag node" in the way that restoring a bookmark would require. The fact that it does work under some circumstances is pure chance, a related move method is used that does sometimes work out.

Now I could go and fill that gap of course, but the code responsible for finding nodes has undergone a major rewrite on account of #677, working on it now would be utterly uneconomical. So I'm afraid I'm going to have to put this bug on ice until #677 is finished.

In fact please remind me to tackle this issue if you see I haven't done so after #677, bugs are always my first priority, so this one should be fixed as soon as possible.

**Comment by minad** [comment]
Ok, thank you for looking at this! Actually for me it would be ok if treemacs does not restore the selected tag node for a bookmark and only restore up to the file. Just in case this makes things simpler.

**Comment by Alexander-Miller** [comment]
> Just in case this makes things simpler.

It does. I'll add it as a temporary workaround.

**Comment by minad** [comment]
If I recall correctly, most bugs I had in treemacs were due to the imenu. So I think every simplification in that part would help a lot. Furthermore since this imenu part is also dynamically created by an external provider I think treemacs should not try too hard in this area!

**Comment by Alexander-Miller** [comment]
The whole imenu feature hasn't seen much change since I've written it a long time ago, when I was a lot less experienced with elisp. I don't think it's all that well used either. So it makes sense that it can sometimes be rickety.  When #677 is done I plan to rewrite it based on the new extension api. That should help with the issues and instabilities that  are caused by the current special-casing.

**Comment by minad** [comment]
Sounds good!

**Comment by Alexander-Miller** [comment]
Workaround is up now.

**Comment by minad** [comment]
Thank you! I will try when updating the packages the next time.

**Comment by minad** [comment]
I can confirm, it works!
