### ISSUE TITLE
About Screenshots Font

### ISSUE THREAD

**Issue by xvindiex** [Alexander-Miller/treemacs#746]
I know this is not an issue, I just want to know what font is used in the screenshots.
I even used the Font Squirrel's Font Identifier but the results weren't that similar.
(I suggest to include the font's name in the README)

**Comment by Alexander-Miller** [comment]
The font I use is Fantasque Sans Mono.

>I suggest to include the font's name in the README

Done

**Comment by xvindiex** [comment]
Awesome! Thank you!! B-)

**Comment by claytonrcarter** [comment]
@Alexander-Miller On the subject of the screenshots, what package/code is in use to put the minibuffer in the center of the frame?
