### ISSUE TITLE
Melpa badges?

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#75]
Maybe it would be helpful to add the two melpa badges, stable and current to readme.org.

The embed codes for html, markdown and org are listed here:
<a href="https://melpa.org/#/treemacs"><img alt="MELPA" src="https://melpa.org/packages/treemacs-badge.svg"/></a> https://melpa.org/#/treemacs 
<a href="https://stable.melpa.org/#/treemacs"><img alt="MELPA Stable" src="https://stable.melpa.org/packages/treemacs-badge.svg"/></a> https://stable.melpa.org/#/treemacs

I could make a PR, but I don't know where they should be placed and in which order.

**Comment by Alexander-Miller** [comment]
Good idea. Badges are included now.
