### ISSUE TITLE
helpful hydra buffer to small

### ISSUE THREAD

**Issue by E3D3** [Alexander-Miller/treemacs#750]
The ? key invokes the helpfull treemacs hydra, but the buffer is to small to show all available commands.

![treemacs-?-hydra](https://user-images.githubusercontent.com/10961837/102758541-2f5f3200-4373-11eb-82e8-03a6483beaa7.jpg)

I use treemacs with Emacs 26.1 on EasyOS (a Puppy Linux variant) and with use of the 'try' package, so I don't have treemacs installed yet.

**Comment by Alexander-Miller** [comment]
Yeah, its time to split the hydra in two.

**Comment by Alexander-Miller** [comment]
There's 2 hydras now, one for the more common commands, and one for the rarely used items.

**Comment by E3D3** [comment]
Thank you for the quick and adequate response.
Both hydra are now complete visible.

I experienced some troubles a couple of times when I tried both hydra's. Don't know exactly what I did wrong but suddenly normal key-bindings like M-x and C-x b didn't work anymore, or opened a hydra-buffer, that was closed before cq not visible in the buffer list. Because I try treemacs with the try-package and I don't know how to reproduce this problem, I will only report a new issue about this when I'm more sure that it is not due to some of my other configuration. First I'll install your very nice package, maybe this also makes a difference.

Maybe it is also a good idea to add the posibility to switch between the 2 hydra's, thus add 'M-?' to the ?-hydra, and vice versa.

**Comment by Alexander-Miller** [comment]
Should be all fixed and working now.  Note that I had to change the keybind to C-?, the hydra kept telling me that M-? is undefined for some reason.

**Comment by E3D3** [comment]
All works nice here. 
I guess my previous trouble was due to the try-package. After installation they where gone, and also treemacs after restarting Emacs ! A second install, without first using 'try', seems to have solved this also.
Thank you again.
