### ISSUE TITLE
Update projectile cache when deleting file

### ISSUE THREAD

**Issue by kriansa** [Alexander-Miller/treemacs#751]
This might have to do with #595, but for file move/deletion. It seems that whenever I move/delete files, the cache gets stale and I need to rebuild it manually.

**Comment by Alexander-Miller** [comment]
Treemacs should not need to do anything for deleting. Projectile advises `delete-file`, which is what treemacs calls internally.

For moving, copying and renaming I'll add the necessary hooks.

**Comment by Alexander-Miller** [comment]
The hooks are there now, but dealing with projectile's caching api is less than pleasant, it clearly wasn't meant to be used in the way treemacs would like. So I would like to reduce my interaction with it to a minimum. For that I need to know what is missing exactly in your use-case.

Updating a cache has 2 parts: out with the old, and in with the new. Which one do you need - do you have old files stuck in the cache, or new ones that aren't there? And for what interactions - renaming, moving, etc?

**Comment by kriansa** [comment]
I appreciate you acting so quickly on this one :bowing_man: 

I just updated my packages and tested all operations:
- Renaming a file won't remove the previous entry - the new one shows up in the list. 
- Moving files won't update either one so I need to manually invalidate the cache to get them listed.
- Not mentioned previously, but creating a file works just fine :ok_hand: 
- Lastly, I know you won't interact with it since `delete-file` is supposed to be advised by projectile, however I noticed that deleting a file keeps its entry in the cache -- not sure that's something only on my setup tho. I'll file an issue on their repo, but I just want to let you know this.

**Comment by kriansa** [comment]
Sorry for the previous message @Alexander-Miller -- I messed up my env. I'll test again and will update you. Thanks!

**Comment by kriansa** [comment]
:clap: :clap: 

Hooks are working flawlessly! Thanks!

However as you mentioned, projectile's caching api isn't great. I had a hard time trying to debug few edge cases here, particularly because the default ordering method uses recentf, which may store files on a separate list which is merged with the cache, and this made me nuts until I found that out.

I've written a tiny "integration" between the two, I'll be using on my setup but I don't know if that would be useful to the community so I'll be posting here. It's working for all create/move/delete and rename operations :pray: 

```lisp
(defun mine/delete-from-cache (file)
    ;; Ensure we also delete it from recentf, which is the default ordering backend used by
    ;; projectile, otherwise it will keep showing up on projectile-project-files
    (setq recentf-list (delete file recentf-list))
    (let ((file-relative (file-relative-name file (projectile-project-root))))
      (ignore-errors (projectile-purge-file-from-cache file-relative))))

;; Partially copied from https://github.com/bbatsov/projectile/blob/master/projectile.el#L968
(defun mine/add-to-cache (file)
  (let* ((current-project (projectile-project-root))
          (abs-current-file file)
          (current-file (file-relative-name abs-current-file current-project)))
    (unless (or (projectile-file-cached-p current-file current-project)
              (projectile-ignored-directory-p (file-name-directory abs-current-file))
              (projectile-ignored-file-p abs-current-file))
      (puthash current-project
        (cons current-file (gethash current-project projectile-projects-cache))
        projectile-projects-cache)
      (projectile-serialize-cache))))

(defun mine/move-on-cache (old new)
  (mine/delete-from-cache old)
  (mine/add-to-cache new))

(defun mine/copy-on-cache (src dest)
  (mine/add-to-cache dest))

(defun mine/rename-file-on-cache (old new)
  (mine/move-from-cache old new))

(setq treemacs-delete-file-functions 'mine/delete-from-cache
      treemacs-move-file-functions 'mine/move-on-cache
      treemacs-copy-file-functions 'mine/copy-on-cache
      treemacs-rename-file-functions 'mine/rename-file-on-cache)
```

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by kriansa** [comment]
@Alexander-Miller 

![aha-ha-ha-ha-stayin-alive-robin-gibb](https://user-images.githubusercontent.com/962032/146216190-2559a5fe-793a-4140-8e12-deca8c416196.gif)

**Comment by Alexander-Miller** [comment]
:+1:

**Comment by Alexander-Miller** [comment]
@kriansa I've carried over your setup into treemacs. Let me know if anything's amiss.
