### ISSUE TITLE
Copy Full/Relative Path

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#754]
Copying full or relative path is an option in VS Code right click menu which I think would be useful in treemacs too.

There is a keybinding for copying full path on `y y`. I think it can be moved to `y F` to copy full path and `y y` should instead copy the relative path from the project root as it is mostly useful for sharing with others or using in code. It would also be great to have it in the right click options menu.

**Comment by Alexander-Miller** [comment]
I don't think that yy and other copy commands are used all that often, so I instead opted to make these keybinds consistently mnemonic.
