### ISSUE TITLE
Right click submenu not usable in `emacs -nw`

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#756]
Gives error:

```
treemacs-rightclick-menu: Wrong type argument: commandp, (keymap "Copy" (Copy\ File menu-item "Copy File" treemacs-copy-file) (Copy\ Absolute\ Path menu-item "Copy Absolute Path" treemacs-copy-absolute-path-at-point) (Copy\ Relative\ Path menu-item "Copy Relative Path" treemacs-copy-relative-path-at-point) (Copy\ Project\ Path menu-item "Copy Project Path" treemacs-copy-project-path-at-point))
```

EDIT: I use `mouse-3` for `menu-bar-edit-menu` in all buffers and the submenus work fine for it in `emacs -nw`.

**Comment by Compro-Prasad** [comment]
I guess the submenus should be defined as separate keymaps?

**Comment by Alexander-Miller** [comment]
Stupid limited menus in terminals are limited and stupid. Clicking on a nested item does not expand it, but selects it, thus your error - you can't execute a submenu (that's internally implemented as a keymap). 
No idea why it happens. no idea why it does work in the menubar for other packages. The current workaround should fix things.
