### ISSUE TITLE
treemacs-dirs-to-collapse.py doesn't work for dirs having "

### ISSUE THREAD

**Issue by Compro-Prasad** [Alexander-Miller/treemacs#757]
I ran the following commands from `elpa/treemacs-version` directory:

```
$ mv icons/default/ icons/x\"
$ python treemacs-dirs-to-collapse.py $PWD 100 t
(("/x"" "/home/compro/.emacs.d/.cache/elpa/treemacs-20210101.1823/icons" "/home/compro/.emacs.d/.cache/elpa/treemacs-20210101.1823/icons/x""))
```

And I don't think the output is correct as per lisp. There should probably be a `\` before each `"` appearing in a string. Is it intentional?

EDIT: Also, it doesn't work for `\` in a filename.

**Comment by Alexander-Miller** [comment]
And unfortunately making this work is a mess of escapes and needs constant filtering. In my opinion it's not worth the effort to support such a strange and rare  case, so I'll just do the necessary minimum and make sure the scripts don't run into any errors.
