### ISSUE TITLE
Variable binding depth exceeds max-specpdl-size

### ISSUE THREAD

**Issue by kinleyd** [Alexander-Miller/treemacs#76]
Whenever a treemacs buffer is active, if I engage the mini-buffer with M-x and try to select a command, I get this error:

`Debugger entered--Lisp error: (error "Variable binding depth exceeds max-specpdl-size")
  window-normalize-window(#<window 20 on *Treemacs*> t)
  window-preserved-size(#<window 20 on *Treemacs*> t)
  window--preserve-size(#<window 20 on *Treemacs*> t)
  window--size-fixed-1(#<window 20 on *Treemacs*> t nil)
  window-size-fixed-p(#<window 20 on *Treemacs*> t nil)
  window--min-size-1(#<window 20 on *Treemacs*> t nil nil)
  window-min-size(#<window 20 on *Treemacs*> t nil nil)
  window-min-delta(#<window 20 on *Treemacs*> t nil nil nil nil nil)
  window--resizable(#<window 20 on *Treemacs*> -276 t nil nil nil nil nil)
  window--resizable-p(nil -276 t)
  shrink-window(276 t)
  shrink-window-horizontally(276)
  treemacs--set-width(35)
  treemacs--on-window-config-change()
  run-window-configuration-change-hook(#<frame  *Minibuf-1* 0x371a130>)
  window-resize(nil 0 t)
  shrink-window(276 t)
  shrink-window-horizontally(276)
  treemacs--set-width(35)
  treemacs--on-window-config-change()
  run-window-configuration-change-hook(#<frame  *Minibuf-1* 0x371a130>)
  window-resize(nil 0 t)
  shrink-window(276 t)
  shrink-window-horizontally(276)
  treemacs--set-width(35)
  treemacs--on-window-config-change()
  run-window-configuration-change-hook(#<frame  *Minibuf-1* 0x371a130>)
  window-resize(nil 0 t)
  shrink-window(276 t)
  shrink-window-horizontally(276)
  treemacs--set-width(35)
  treemacs--on-window-config-change()
  run-window-configuration-change-hook(#<frame  *Minibuf-1* 0x371a130>)
... and on and on` 

The debug print out is very long, with the above representing just about 2 or 3% of it.

The problem seems to be related to helm (I have helm M-x keybindings), and is something from which I can't recover from in the present session. It doesn't occur with helm M-x interaction in other non-treemacs buffers.

**Comment by Alexander-Miller** [comment]
What are your helm settings?

Do you use any packages to control the size of windows, like golden-ratio?

What's the value of `window-configuration-change-hook`?

Does the problem still happen if you go to treemacs-mode.el and change line 239 to `(add-hook 'window-configuration-change-hook #'treemacs--on-window-config-change nil t)` and recompile the file with `emacs-lisp-byte-compile` and restart emacs?

**Comment by kinleyd** [comment]
< What are your helm settings?

(require 'helm)
(require 'helm-config)
(helm-mode 1)
(helm-autoresize-mode 1
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-x b") 'helm-buffers-list)

> Do you use any packages to control the size of windows, like golden-ratio?

No packages. I just have some code for one buffer which have window-width and max-text-width settings:

(defun kdd-zen-mode ()
    "Switch to text-mode and set margins leaving a composition space of only 80 characters."
    (interactive) ; required if you want the function accessible in the mini buffer
    (let* ((current-extension (file-name-extension (or (buffer-file-name) "foo.unknown")))
    (max-text-width 80)
    (margin (max 0 (/ (- (window-width (selected-window)) max-text-width) 2))))
    (if (not (string= current-extension "zen"))
    ;; Do nothing if this isn't a .zen file, my custom zen mode file extension..
    ()
    (set-window-margins (selected-window) margin margin)
    (text-mode))))
;; custom keybinding...
(global-set-key (kbd "C-x Z") 'kdd-zen-mode)

> What's the value of window-configuration-change-hook?

window-configuration-change-hook is a variable defined in ‘C source code’.
Its value is (window--adjust-process-windows)

> Does the problem still happen if you go to treemacs-mode.el and change line 239 to (add-hook 'window-configuration-change-hook #'treemacs--on-window-config-change nil t) and recompile the file with emacs-lisp-byte-compile and restart emacs?

[Will update here when I check this out]

**Comment by Alexander-Miller** [comment]
> (helm-autoresize-mode 1

Looks like a likely culprit. Try turning it off.

**Comment by kinleyd** [comment]
Ha. that was it. I'll keep it off although I *do* like to have helm-autoresize-mode on.

**Comment by Alexander-Miller** [comment]
Its a stopgap until I come up with a proper fix. The change in line 239 from above might be a solution, so you should still try that.

**Comment by kinleyd** [comment]
No, changing line 239 doesn't help.

**Comment by Alexander-Miller** [comment]
Looking at the stacktrace it looks like theres some kind of feedback loop, with the hook code running the hooked function running the hook code etc. Of course this is such an obvious error case that emacs certainly has safeguards againt it. At the very least I am unable to reproduce the problem, which leads me to believe it might be something in your config.

Lets try tackling the hook in hook case. Evaluate this code and try again:
```
(defun treemacs--on-window-config-change ()
  "Collects all tasks that need to run on a window config change."
  (-when-let (w (treemacs--is-visible?))
    (with-selected-window w
      (let (window-configuration-change-hook)
        ;; Reset the treemacs window width to its default - required after window deletions
        (when treemacs--width-is-locked
          (treemacs--set-width treemacs-width))
        ;; Prevent treemacs from being used as other-window
        (when treemacs-is-never-other-window
          (set-window-parameter w 'no-other-window t))))))
```

**Comment by kinleyd** [comment]
After evaluating the above code and resetting helm-autoresize-mode to true, the problem doesn't recur.

**Comment by Alexander-Miller** [comment]
Fix is pushed and will be there with the next melpa build.
Let me know if it works.

**Comment by kinleyd** [comment]
Awesome, @Alexander-Miller. Thank you!

**Comment by kinleyd** [comment]
After installing v. 1.11.7 and running the same key sequences in the treemacs buffer, no error was triggered even with helm-autoresize-mode active. Hooray! :)
