### ISSUE TITLE
treemacs fails to load with emacs master due to change in define-obsolete-variable-alias

### ISSUE THREAD

**Issue by anticrisis** [Alexander-Miller/treemacs#760]
This call causes loading of treemacs to fail in the current master branch of emacs: https://github.com/Alexander-Miller/treemacs/blob/7bc482b1022753c27e91441363219b6d3b03281e/src/elisp/treemacs-customization.el#L873

This is the commit in emacs that made the change a few days ago. According to NEWS, this change in API was noted in emacs 23.1.

https://github.com/emacs-mirror/emacs/commit/32c6732d16385f242b1109517f25e9aefd6caa5c

It's a simple enough fix, I would have submitted a pull request but I wouldn't know what version number to supply as the `when` argument.

**Comment by Alexander-Miller** [comment]
Yep, I was the thread on /r/emacs and thought to myself that if it's been obsolete since Emacs 23 it's your own fault if you still use it.  :man_shrugging:
