### ISSUE TITLE
treemacs-rightclick-menu error in 20210106.1417

### ISSUE THREAD

**Issue by zy9306** [Alexander-Miller/treemacs#762]
right click in a item, then thow:

Debugger entered--Lisp error: (void-variable project--list)
  treemacs--builtin-project-mouse-selection-menu()
  #f(compiled-function (it) #<bytecode 0x1fefb3a8c579>)(("Add Project.el project" . treemacs--builtin-project-mouse-selection-menu))
  mapcar(#f(compiled-function (it) #<bytecode 0x1fefb3a8c579>) (("Add Project.el project" . treemacs--builtin-project-mouse-selection-menu)))
  treemacs-rightclick-menu((mouse-3 (#<window 9 on  *Treemacs-Scoped-Buffer-#<frame miku@.emacs.d: *scratch* 0x7fbec880c430>*> 191 (117 . 460) 86537965 nil 191 (11 . 21) nil (5 . 7) (9 . 19))))
  funcall-interactively(treemacs-rightclick-menu (mouse-3 (#<window 9 on  *Treemacs-Scoped-Buffer-#<frame miku@.emacs.d: *scratch* 0x7fbec880c430>*> 191 (117 . 460) 86537965 nil 191 (11 . 21) nil (5 . 7) (9 . 19))))
  call-interactively(treemacs-rightclick-menu nil nil)
  command-execute(treemacs-rightclick-menu)

**Comment by Alexander-Miller** [comment]
Looks like you are on an Emacs version where the project.el api is not available. The rightclick menu will check for that now.
