### ISSUE TITLE
Wrong type argument, commandp, treemacs-helpful-hydra

### ISSUE THREAD

**Issue by toogad** [Alexander-Miller/treemacs#764]
Got the error message shown in the title of this issue when pressed "?" in treemacs.

treemacs-common-helpful-hydra and treemacs-advance-helpful-hydra work okay when typed in M-x.

**Comment by Alexander-Miller** [comment]
There's been some trouble in melpa with building treemacs' addon packages: https://github.com/melpa/melpa/issues/7354

It's been fixed now, so updating treemacs-evil will get the hydras working again.

**Comment by toogad** [comment]
Thank you!
