### ISSUE TITLE
Trying to rename a file/folder with treemacs-perspective installed causes prompt for perspective name

### ISSUE THREAD

**Issue by Randy1Burrell** [Alexander-Miller/treemacs#767]
When I try to rename a file within treemacs, I get a prompt for perspective name. This is weird because before I installed treemacs-perspective and perspective renaming would prompt me in the mini-buffer for a new name. But now I am prompted for the new name at the file level in treemacs, and when I insert a new name then press return I find I am prompted again, this time in the mini buffer for a perspective name. See the picture below:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/10135939/104820096-a49e1580-5800-11eb-8e09-1305e5ef2d7b.png">

When I provide a name I get the error `Lisp nesting exceeds ‘max-lisp-eval-depth’`:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/10135939/104820225-6e14ca80-5801-11eb-9aa5-36cc8645f7cb.png">

Checking the *Messages* buffer, here's what I see:

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/10135939/104820291-ce0b7100-5801-11eb-92a1-f498f0f53970.png">

Can anyone help to solve this issue?

**Comment by Alexander-Miller** [comment]
Hmmm. For whatever reason persp thinks there's a perspective switch happening when `cfrs-read` is called. I'll have to dig into what's going on. In the meantime you can use `(setf treemacs-read-string-input 'from-minibuffer)`.

Side notes:
Customizing the `internal-border` face can give the popup a properly visible border.
What line numbers implementation do you use? There shouldn't be any in the cfrs popup.

**Comment by Randy1Burrell** [comment]
@Alexander-Miller here are my line number settings:

```emacs-lisp
(setq display-line-numbers-width-start t)
(global-display-line-numbers-mode      t)
(setq display-line-numbers-type 'relative)
(column-number-mode t)
```

**Comment by Alexander-Miller** [comment]
Persp was being too clever in how it handles recursive edits, but its case did not apply because cfrs uses child-frames. I've added a workaround for it now (to cfrs, not treemacs). The line numbers issue should be taken care of as well.
