### ISSUE TITLE
R icon not showing in treemacs

### ISSUE THREAD

**Issue by atanasj** [Alexander-Miller/treemacs#769]
Not sure if this an issue with `treemcs-all-the-icons` or this is related to [`doom-emacs`](@hlissner), but the `R` icon does not appear in the `treemacs` window, even though this has been implemented in `all-the-icons` (see [this issue](https://github.com/domtronn/all-the-icons.el/issues/215#issue-630771661)). 

Any ideas why this could be happening

**Comment by Alexander-Miller** [comment]
I've added an R icon for treemacs' own all-the-icons theme now. If you are using doom's treemacs theme you'll have to ask there, or modify the theme yourself.
