### ISSUE TITLE
Do not use cfrs by default?

### ISSUE THREAD

**Issue by minad** [Alexander-Miller/treemacs#770]
I think it is preferred if treemacs would not read input via cfrs by default but by the Emacs standard minibuffer. For example, in my tiling window manager setup cfrs is a pretty unexpected default because I do not use frames at all. Furthermore I think it would also be better if packages keep their dependencies minimal and do not add superfluous dependencies, like cfrs as in this case. I saw that cfrs is a pretty small package. But still - I always wonder when packages pull in new dependencies.

**Comment by Alexander-Miller** [comment]
I get where you're coming from - I'm no fan of clutter myself - but this does put me into an awkward position. cfrs was developed based on another user's request, or at least as a compromise because I wouldn't go for full a full wdired clone. 

And to be honest I think treemacs has crossed the line from "simple and minimalistic" to "powerful and customizable" a long time ago. If you are looking for the former maybe dired-sidebar will suit you better.

Finally there's also no good way not have such a feature enabled by default, and actually have people use, it is not worth it to turn into its own package (which of course is bloat in its own right) and if it has to be enabled hardly anyone will see it. And while writing code like this is to some degree its own reward for me, a strong part of my motivation for treemacs is derived from it being useful to others.

So yeah, I'm going to have to say no to this one, though I am far from happy with the situation myself. (I do however feel inspired to reduce some clutter by investigating and hopefully removing my f.el and s.el dependencies)

**Comment by minad** [comment]
> I get where you're coming from - I'm no fan of clutter myself - but this does put me into an awkward position. cfrs was developed based on another user's request, or at least as a compromise because I wouldn't go for full a full wdired clone.

What is the problem with removing the dependency and just using the default minibuffer input by default as would be expected in Emacs? cfrs could still be used if explicitly configured. I am not arguing about having it available as option, only against making it a default and against adding it as a dependency.

> And to be honest I think treemacs has crossed the line from "simple and minimalistic" to "powerful and customizable" a long time ago. If you are looking for the former maybe dired-sidebar will suit you better.

Yes, it is always a hard question on where to stop when adding features. I must admit I considered dropping treemacs from my setup for multiple reasons. I rarely use most of its power since the standard Emacs navigation utilities are often good enough. I generally prefer when packages somehow stay within a certain scope and don't attempt to do everything or deviate too much from some standard expectations. But overall I like the treemacs look and feel and I like how solid it has become over time and I like to have it for certain navigation tasks and to get a good overview. 

> Finally there's also no good way not have such a feature enabled by default, and actually have people use, it is not worth it to turn into its own package (which of course is bloat in its own right) and if it has to be enabled hardly anyone will see it.

I don't understand what you mean here. You mean if you don't enable crfs by default nobody will use it?

> And while writing code like this is to some degree its own reward for me, a strong part of my motivation for treemacs is derived from it being useful to others.

This makes a lot of sense - I feel exactly the same way when writing some open source code.

> (I do however feel inspired to reduce some clutter by investigating and hopefully removing my f.el and s.el dependencies)

Any potential reduction of clutter is appreciated from my perspective, but it is also not the most important priority. It is better to develop something amazing using the tools you like. And I am not super critical on the dependencies like dash, f and s since these are very widespread. But when I looked into these libraries, I found the benefits to be rather marginal in contrast to just using the builtins, which are sometimes a bit ugly, I admit. I try to only use the builtins in my packages. I recently made [Consult](https://github.com/minad/consult), you may have seen it.

**Comment by Alexander-Miller** [comment]
> What is the problem with removing the dependency and just using the default minibuffer input by default as would be expected in Emacs?

I just think that cfrs is a genuine improvement over the default. I don't like
reading input from the minibuffer, especially not on a large screen. You
disagree, but I have no way of knowing if how popular the change really is, so I
prefer getting it out there.

Maybe we should go ask /r/emacs?

> I generally prefer when packages somehow stay within a certain scope and don't attempt to do everything or deviate too much from some standard expectations.

So do I, treemacs definitely has a delimited scope beyond which I will not
move. I usually summarise it as "treemacs is a file explorer, not a file
manager". In practice that means I am fine with adding the kind of features that
you'd find in the sidebars of the likes of IntelliJ or VSC (including modern-ish
input popups), or helpers like `treemacs-edit-workspaces` , the helpful hydras
and clippy that can soften the learning curve and make treemacs less
intimidating, but treemacs will never try to be a real alternative to dired.

> You mean if you don't enable crfs by default nobody will use it?

Most likely. Treemacs' readme is huge as it is, and I doubt many read the
changelog. If I don't use a new feature myself I'm lucky to receive the first bug
report a year from now, even if something's obviously broken.

> I recently made Consult, you may have seen it.

Seen it, and put it on my todo list, alongside selectrum and marginalia. The
whole combo looks really interesting, but I do have a helm-based setup that I am
happy with, so it'll have to wait until I have some tinkering-time available.

**Comment by minad** [comment]
> I just think that cfrs is a genuine improvement over the default. I don't like
reading input from the minibuffer, especially not on a large screen. You
disagree, but I have no way of knowing if how popular the change really is, so I
prefer getting it out there.

I do not necessarily disagree with the eye-movement argument regarding the minibuffer. There are all these mini-frame solutions to fix this on a general level. Maybe this would not work for the treemacs use case? But still - I wouldn't want a package to impose such decisions on me. I think it is much better to stick with the defaults (as long as they are not totally broken, sometimes they are). But in this case moving the minibuffer to the position of the cursor is not something I would consider to be in the scope of treemacs. From my perspective it is out of scope.

> Maybe we should go ask /r/emacs?

:+1:

> So do I, treemacs definitely has a delimited scope beyond which I will not
move. I usually summarise it as "treemacs is a file explorer, not a file
manager". In practice that means I am fine with adding the kind of features that
you'd find in the sidebars of the likes of IntelliJ or VSC (including modern-ish
input popups), or helpers like treemacs-edit-workspaces , the helpful hydras
and clippy that can soften the learning curve and make treemacs less
intimidating, but treemacs will never try to be a real alternative to dired.

I like the scope of a file explorer as you describe it! But the IDE features you mention later - there I am bit on the more conservative side I guess. While I agree there are many good sides of IDEs they are also missing a lot of things I like in Emacs. I wouldn't want to see refactoring features becoming part of treemacs. If such features are provided externally I am fine. I think people are working on that as part of lsp-mode?

> Most likely. Treemacs' readme is huge as it is, and I doubt many read the
changelog. If I don't use a new feature myself I'm lucky to receive the first bug
report a year from now, even if something's obviously broken.

Okay this is interesting. I would expect to see more coverage in particular since treemacs has so many installs. In the case of Consult it seems to me that everyone is poking this thing from all different sides (even with only 4000 downloads), but maybe the reason is that on this stage this attracts people who want to do a lot of Emacs experimentation instead of just a rock solid development platform. Another reason could be that treemacs is mature, so most people have it installed and it works well for them and they won't spend time on going over the config again and again. So by adding cfrs you are disrupting these users in a sense, as has happened for me. I am not sure if I like being disrupted by Emacs packages though ;)

> Seen it, and put it on my todo list, alongside selectrum and marginalia. The
whole combo looks really interesting, but I do have a helm-based setup that I am
happy with, so it'll have to wait until I have some tinkering-time available.

I guess it is really a tough sell for Helm users since it takes the much more minimalistic approach. We've got some enthusiastic feedback by some Helm users, but I guess in these cases they have already been looking for alternatives from time to time. The general look and feel is more familiar to Ivy users. I would not declare feature parity with either Helm or Ivy, and I cannot know since in particular Helm has a big ecosystem. But I went a few times over the Ivy/Counsel and Helm docs and didn't find too many features I would miss. Maybe you could tell me some? We also have this wishlist discussion issue on the Consult issue tracker, but recently there haven't been that many new suggestions. For me it feels as if the basic needs are covered.

Btw, you should also not miss out on Embark, which is great. See these two videos by Prot, https://protesilaos.com/codelog/2021-01-06-emacs-default-completion/ and https://protesilaos.com/codelog/2021-01-09-emacs-embark-extras/.

**Comment by Alexander-Miller** [comment]
> I wouldn't want to see refactoring features becoming part of treemacs. If such features are provided externally I am fine. I think people are working on that as part of lsp-mode?

You misunderstand, I was talking only of the side-trees in those editors, not everything else they can do.

>   I would expect to see more coverage in particular since treemacs has so many installs.

Treemacs is included with both spacemacs and doom, so MELPA's download numbers don't reflect the number of people who made a conscious decision to use treemacs.

> But I went a few times over the Ivy/Counsel and Helm docs and didn't find too many features I would miss. Maybe you could tell me some? 

There's a few things helm can do that, while rarely used, are very convenient when you need them. What comes to mind is multiple sources, so for example in `helm-mini` you can switch between your buffers, recent files, and creating a new buffer for your input. Or support for multiple actions so you can delete files/buffer instead of opening them. 

Ecosystem is a point, too. I don't use too many helm extensions, but stuff like helm-org is great. I have setup my own command that shows me the headings from each of my agenda files as a helm source each, all nicely sorted and fontified with org's own colors and I can either navigate to some heading or use it as a refile target. helm-ag's live search is also great and it's not difficult to make it use rg instead.

Helm also supports being shown in a child frame, which I am very much a fan of. That's probably going to be more challenging with a minibuffer-based selectrum.

> Btw, you should also not miss out on Embark

Yep, that's also on the list.

**Comment by minad** [comment]
> Treemacs is included with both spacemacs and doom, so MELPA's download numbers don't reflect the number of people who made a conscious decision to use treemacs.

I thought these pull from git nowadays?

> There's a few things helm can do that, while rarely used, are very convenient when you need them. What comes to mind is multiple sources, so for example in helm-mini you can switch between your buffers, recent files, and creating a new buffer for your input. Or support for multiple actions so you can delete files/buffer instead of opening them.

Yes, helm-mini seems to be great. I have a small version of it in Consult, `consult-buffer`, which allows to select between "virtual buffers". Right now it supports buffers, recent files, project files, bookmarks and views. However the sources are hard-coded. I consider making the buffer sources configurable (https://github.com/minad/consult/issues/135). Besides helm-mini I am not so sure of the value of multiple sources. Since the Consult way is less abstracted than the Helm sources, in cases where you would want to put multiple sources together you would have to write a new command based on `completing-read`. I am sure heavy Helm users use the sources mechanism a lot and create their commands this way.

> Helm also supports being shown in a child frame, which I am very much a fan of. That's probably going to be more challenging with a minibuffer-based selectrum.

This is something where I think the Selectrum/Consult/Embark/default-completion "ecosystem" is actually very flexible. You can chose from these options:

* minibuffer vertical - Selectrum/Icomplete-vertical
* minibuffer horizontal - Selectrum/Icomplete
* buffer - Default completion/Embark completion (also possible in a separate frame, maybe?)
* mini-frame - Minibuffer in an extra frame

You can even combine things like Selectrum-horizontal + Embark-live-collect, which gives you both the minibuffer completion and a separate real buffer.

> helm-ag's live search is also great and it's not difficult to make it use rg instead.

We have consult-ripgrep, consult-grep, consult-git-grep. It is asynchronous and live updating, similar to Ivy and Helm.

> Ecosystem is a point, too. I don't use too many helm extensions, but stuff like helm-org is great. I have setup my own command that shows me the headings from each of my agenda files as a helm source each, all nicely sorted and fontified with org's own colors and I can either navigate to some heading or use it as a refile target. 

Sure, there exist many packages, this cannot be denied! Hopefully in many cases you can get a simplified version of the corresponding Helm command by reusing the functions which generate the candidates. 

While I think Selectrum/Consult etc is pretty good and I like it, I would not go so far as suggesting to happy Helm users to use something else. It really depends on the personal preferences and experience I guess. For me, I never bought into the Helm ecosystem, because at the time when I tried it I didn't have too much tinkering time and I needed something working. Back then I had a relatively broken barebone Emacs configuration with Ido and not many fancy features and Helm somehow overwhelmed me. For this reason I am very much favoring the component based approach of small packages which can be plugged together and can be added independently step by step.

**Comment by Alexander-Miller** [comment]
> I thought these pull from git nowadays?

Doom does, yes. Spacemacs is afaik still using melpa, with the option to use its own spacelpa archive, but I don't know
how mature that option is.

> This is something where I think the Selectrum/Consult/Embark/default-completion "ecosystem" is actually very flexible.

Ah yes, I must've missed that option because the readme is so large. Now where have we heard that story before?

> Sure, there exist many packages, this cannot be denied! Hopefully in many cases you can get a simplified version of
> the corresponding Helm command by reusing the functions which generate the candidates.

I'd say you're pretty close actually. I've looked around my config now, and while helm-org is the big hitter, I don't
see anything else that consult would not be able to provide in time. I'll probably look around some more over the weekend and maybe open some issues.

**Comment by minad** [comment]
> I'd say you're pretty close actually. I've looked around my config now, and while helm-org is the big hitter, I don't
see anything else that consult would not be able to provide in time. I'll probably look around some more over the weekend and maybe open some issues.

I am looking forward to your feedback. There have been some proposals for a few consult-org-* commands and consult-org package, but it was not clear to me what kind of functionality would actually be needed, since org provides a lot of ui by itself. I will take a look what helm-org provides.
