### ISSUE TITLE
Renaming animation seems glitched. 

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#775]
The in-place renaming animation seems buggy. When you press `R`, first you see nothing. I then press the arrow key and that makes the wonky text display in a strange way.

![treemacs](https://user-images.githubusercontent.com/43047754/107609910-dd65ba80-6c05-11eb-81c3-245290479c20.gif)

I am at `[Treemacs] v2.8 (installed 2021.02.05) @ Emacs 26.3`. Not sure what more information I could provide. Let me know!

**Comment by Alexander-Miller** [comment]
There should be no animation here, at least no animation other than the final confirmation in green. Where is that gray pulse coming from? It might interfere with the cfrs popup.

Your theme should also set a distinct background for the `internal-border` face, the popup should look like this: https://raw.githubusercontent.com/Alexander-Miller/cfrs/master/cfrs.png

**Comment by simurgh9** [comment]
> Where is that gray pulse coming from?

That is [beacon](https://github.com/Malabarba/beacon). It flashes the point when your cursor moves.

I turned it off and tried renaming and this time the wonkiness went away; though no border still. I am using Doom themes.

```lisp
;; doom-themes
(use-package doom-themes
  :if window-system
  :ensure t
  :custom
    (doom-themes-enable-bold t "if nil, bold is universally disabled")
    (doom-themes-enable-italic t "if nil, italics is universally disabled")
    (doom-themes-treemacs-theme "doom-colors" "use the colorful treemacs theme")
  :config
    ;; Global settings (defaults)
    (load-theme 'doom-one t)
    ;; Enable flashing mode-line on errors
    (doom-themes-visual-bell-config)
    ;; (doom-themes-treemacs-config)
    ;; Corrects (and improves) org-mode's native fontification.
    (doom-themes-org-config))
```

Though, as you can see, I have commented out the `(doom-themes-treemacs-config)` because I don't quite like the way it sets up the treemacs. Should there not be a default border? Could I set it manually somehow?

Or, better yet, I actually am not quite sold on this in place renaming idea. I liked  the old renaming in the minibuffer, kept things tidy. Anyway I could revert back to it without downgrading?

**Comment by Alexander-Miller** [comment]
> That is beacon. It flashes the point when your cursor moves.

Does this help: `(add-to-list 'beacon-dont-blink-major-modes 'cfrs-input-mode)`

> Should there not be a default border? Could I set it manually somehow?

The border is always there, it's just that most themes don't properly set its color, so it's the same as the default background. You can set it yourself like this: `(set-face-background 'internal-border "#6699CC")`. With Emacs 28 the face you need will instead be `child-frame-border`, but that's [a different story](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=45620).

> Anyway I could revert back to it without downgrading?

Always.  If there's a new change you don't like, or want to know the name of to customize you can find it in `treemacs-show-changelog`.  In this case you need `(setf treemacs-read-string-input 'from-minibuffer)`.

**Comment by simurgh9** [comment]
Yeap that helped! Thank you!

**Comment by Alexander-Miller** [comment]
I've made the beacon exclusion part of cfrs now, so you won't need to keep it around in your config.
