### ISSUE TITLE
Error running timer ‘treemacs--follow’: (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by andreyorst** [Alexander-Miller/treemacs#776]
This message appears from time to time and `treemacs-follow-mode` stops working until I switch workspaces back and forth. This happens quite randomly, not sure what triggers this.

**Comment by Alexander-Miller** [comment]
I'll need a stack trace for this, so the next time it  happens enable debug-on-error and call `treemacs-find-file` manually.

**Comment by Alexander-Miller** [comment]
Looks like I managed to run into the bug you described. Things should be fixed in the latest version.
