### ISSUE TITLE
Treemacs window partially freezes with error.

### ISSUE THREAD

**Issue by mtbar131** [Alexander-Miller/treemacs#778]
emacs version: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2020-06-16 (running in terminal mode)

I am running treemacs with lsp and I work with 2/3 projects simultaneously (all are Golang projects if that helps). Recently I have started seeing below error 10/15 mins after starting treemacs. Whenever this happens the treemacs window seems to be partially frozen such that I can still move my cursor around but hitting TAB on a folder doesn't do anything. I see below error in the command window. 

Error running timer ‘treemacs--process-file-events’: (wrong-type-argument integer-or-marker-p #<overlay from 114 to 152 in  *Treemacs-Scoped-Buffer-#<frame F1 0xcac7b0>*>)

**Comment by Alexander-Miller** [comment]
Try enabling debug-on-error. I'll need a stack trace to understand what's going on.

**Comment by mtbar131** [comment]
This what I got after enabling debug-on-error.

```
 Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p #<overlay from 31 to 38 in  *Treemacs-Scoped-Buffer-#<frame F1 0xcac7b0>*>)
  treemacs--collapse-dir-node(#<marker (moves after insertion) at 35 in  *Treemacs-Scoped-Buffer-#<frame F1 0xcac7b0>*> nil)
  treemacs-toggle-node(nil)
  treemacs-TAB-action(nil)
  funcall-interactively(treemacs-TAB-action nil)
  call-interactively(treemacs-TAB-action nil nil)
  command-execute(treemacs-TAB-action)
```

**Comment by Alexander-Miller** [comment]
Hmm, that doesn't help unfortunately.  That method isn't small, and should not be touching overlays anyway.

What does this output?

```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (dolist (ov (overlays-at (point)))
    (message "ov properties %s" (overlay-properties ov))))
```

Normally the output should look like this

>ov properties (window nil face hl-line priority -50)
>ov properties (before-string  )

If the output does not look suspicious we'll need to dig deeper. You'll have to eval and edebug the following function, try to close another node, and then tell me which line exactly the error happens.

```Elisp
(defun treemacs--collapse-dir-node (btn &optional recursive)
  "Close node given by BTN.
Remove all open dir and tag entries under BTN when RECURSIVE."
  (save-excursion
    (treemacs-with-writable-buffer
     (treemacs--button-symbol-switch treemacs-icon-dir-closed)
     (treemacs-button-put btn :state 'dir-node-closed)
     (-let [next (next-button (point-at-eol))]
       (if (or (null next)
               (/= (1+ (treemacs-button-get btn :depth))
                   (treemacs-button-get (copy-marker next t) :depth)))
           (delete-trailing-whitespace)
         (let* ((pos-start (treemacs-button-end btn))
                (next (treemacs--next-non-child-button btn))
                (pos-end (if next
                             (-> next (treemacs-button-start) (previous-button) (treemacs-button-end))
                           (point-max))))
           (delete-region pos-start pos-end))))
     (-let [path (treemacs-button-get btn :path)]
       (treemacs--stop-watching path)
       (treemacs-on-collapse path recursive)))))
```

**Comment by mtbar131** [comment]
Apologies for the delay.

I tried to edbug the `treemacs-collapse-dir-node` function but didn't see a lot of helpful information. Debugger just reaches this line: https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-rendering.el#L568 and throws a message saying
```edebug-signal: Wrong type argument: number-or-marker-p, #<overlay from 31 to 40 in  *Treemacs-Scoped-Buffer-#<frame F1 0xcac7b0>*>```

I have never used edebug before so I might be missing something. Let me know if I need to try something else.

**Comment by Alexander-Miller** [comment]
All right, that stack trace was very useful in helping me understand what's going on, because now I know for sure that this doesn't make any sense. `(next-button (point-at-bol) t)` is somehow returning an overlay in a place where there should not be any overlays, which means that *something* must be doing some *very* strange things with overlays.

Once you are in this error state what does the following code output:

```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (dolist (ov (overlays-in (point-min) (point-max)))
    (message "ov properties %s" (overlay-properties ov))))
```

What about this:

```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (-let [properties (text-properties-at (treemacs-current-button))]
    (while properties (message "%s %s" (pop properties) (pop properties)))))
```

**Comment by mtbar131** [comment]
Here is the output for the above two snippets:

```
ov properties (window nil face hl-line priority -50)
ov properties (before-string  )
ov properties (lsp-link t category default-button button #<overlay from 109 to 131 in  *Treemacs-Scoped-Buffer-#<frame F1 0xcac7b0>*> help-echo mouse-2, M-RET: Visit this link keymap (keymap (mouse-2 . push-button) (M-return . push-button)) action #[257 \301\300!\207 [https://godoc.org/go.opencensus.io/trace lsp--document-link-handle-target] 3

(fn _) nil])
ov properties (lsp-link t category default-button button #<overlay from 93 to 106 in  *Treemacs-Scoped-Buffer-#<frame F1 0xcac7b0>*> help-echo mouse-2, M-RET: Visit this link keymap (keymap (mouse-2 . push-button) (M-return . push-button)) action #[257 \301\300!\207 [https://godoc.org/github.com/Microsoft/hcsshim/internal/oc lsp--document-link-handle-target] 3

(fn _) nil])
ov properties (lsp-link t category default-button button #<overlay from 79 to 90 in  *Treemacs-Scoped-Buffer-#<frame F1 0xcac7b0>*> help-echo mouse-2, M-RET: Visit this link keymap (keymap (mouse-2 . push-button) (M-return . push-button)) action #[257 \301\300!\207 [https://godoc.org/github.com/Microsoft/hcsshim/internal/hcserror lsp--document-link-handle-target] 3

(fn _) nil])
ov properties (lsp-link t category default-button button #<overlay from 31 to 38 in  *Treemacs-Scoped-Buffer-#<frame F1 0xcac7b0>*> help-echo mouse-2, M-RET: Visit this link keymap (keymap (mouse-2 . push-button) (M-return . push-button)) action #[257 \301\300!\207 [https://godoc.org/context lsp--document-link-handle-target] 3

(fn _) nil])
nil
```


```
:depth 3
:parent #<marker (moves after insertion) at 2186 in  *Treemacs-Scoped-Buffer-#<frame F1 0xcac7b0>*>
:key /home/amit/go/src/github.com/Microsoft/hcsshim/internal/wclayer/zsyscall_windows.go
:path /home/amit/go/src/github.com/Microsoft/hcsshim/internal/wclayer/zsyscall_windows.go
:state file-node-closed
:default-face treemacs-git-unmodified-face
keymap nil
help-echo nil
category default-button
button (t)
face treemacs-git-unmodified-face
nil
````

**Comment by mtbar131** [comment]
My emacs config (relevant to treemacs), if it helps:

**Comment by Alexander-Miller** [comment]
Found the culprit. Those `lsp-link` overlays are not my doing. I have reported the problem downstream: https://github.com/emacs-lsp/lsp-mode/issues/2701

**Comment by mtbar131** [comment]
Thanks! I will also track the other issue.

**Comment by Alexander-Miller** [comment]
lsp-mode bug has been fixed, so let's close here as well.
