### ISSUE TITLE
Resizing toggle only works when focus is in treemacs

### ISSUE THREAD

**Issue by mruegenberg** [Alexander-Miller/treemacs#781]
When running `M-x treemacs-toggle-fixed-width`, it only works when the focus is in the treemacs panel (e.g via `C-x o`)

If it's in a regular buffer next to it, I get the message `[Treemacs] Window width has been unlocked`, but resizing fails.

This is with Emacs 27.1 on Arch Linux.

**Comment by Alexander-Miller** [comment]
The width toggle was never meant to be used outside of treemacs, but making that change is not a problem. I'll push a patch shortly.
