### ISSUE TITLE
[Question] How to custom snakemake icon ?

### ISSUE THREAD

**Issue by alienzj** [Alexander-Miller/treemacs#782]
Treemacs, great tools, I like!

when I set:
  ```elisp
  (defvar treemacs-custom-snakemake-icon (all-the-icons-icon-for-file "images/snakemake.png"))
  (treemacs-define-custom-icon treemacs-custom-snakemake-icon "smk" "snakefiles")
  ```
![image](https://user-images.githubusercontent.com/8847420/109575619-25a13a00-7b2d-11eb-9087-31cc4d0e6510.png)
![image](https://user-images.githubusercontent.com/8847420/109575650-3a7dcd80-7b2d-11eb-8b28-2ca23aef6da7.png)

As shown in the figure above, the snakemake icon is not displayed correctly.
Can you help? Very much looking forward to your reply 
Thanks~

**Comment by Alexander-Miller** [comment]
The code you are using is working exactly as designed. `all-the-icons-icon-for-file ` looks at the extension of the string you give it - in your case that ".png". So treemacs correctly shows all your .smk file with an image icon.

Using custom icons with images wasn't possible yet, I've just added the command for it, so you have to update. The code you need looks like this:

```Elisp
(treemacs-define-custom-image-icon "/path/to/your/icon.png" "smk" "snakefiles")
```

Note that treemacs expects icons to be exactly 22x22 pixels large.

**Comment by alienzj** [comment]
![image](https://user-images.githubusercontent.com/8847420/110087304-6ff51600-7dce-11eb-8991-fb873cca275f.png)
Good work, thanks very much~
