### ISSUE TITLE
coding system is always asked when closing treemacs-persist.

### ISSUE THREAD

**Issue by Vonfry** [Alexander-Miller/treemacs#783]
This problem is found in recent update. It is not come out in updating before 6th Feb. 

**Details**
- It is tested with `emacs -Q`
- `treemacs-persist` is coded as `utf-8`.
- `treemacs-persist` contains chinese characters.
- `treemacs-edit-workspaces` is opened without problem. And `treemacs-finish-edit` is called without error as well.

Emacs version: 27.1.91
Treemacs: 20210224.2045
`$LANG`:  en_US.UTF-8
python: 3.8

**Reproduce**
1. run startup script
2. call `treemacs-edit-workspaces`
3. edit it as follows
4. `C-c C-c`
5. `C-x C-c`

Startup:
```
(add-to-list 'exec-path <python path>)
(setq-default treemacs-follow-mode t
              treemacs-tag-follow-mode t
              treemacs-filewatch-mode t
              treemacs-persist-file (expand-file-name "treemacs-persist" <my-path>))
(require 'treemacs)
```

treemacs-persist:
```
* Default
** dotfiles
 - path :: ~/dotfiles
** tmp
 - path :: /tmp
* Lab
** report
 - path :: ~/Documents/lab/论文与实验/01/report
** source
 - path :: ~/Documents/lab/论文与实验/01/src
** cites
 - path :: ~/Documents/lab/论文整理
```
**Output**
```
These default coding systems were tried to encode text
in the buffer ‘treemacs-persist’:
  (utf-8-unix (205 . 4194280) (206 . 4194222) (207 . 4194234) (208 . 4194278)
  (209 . 4194198) (210 . 4194183) (211 . 4194278) (212 . 4194197) (213
  . 4194228) (214 . 4194279) (215 . 4194192))
However, each of them encountered characters it couldn’t encode:
  utf-8-unix cannot encode these: � � � � � � � � � � ...

Click on a character (or switch to this window by ‘M-x other-window’
and select the characters by RET) to jump to the place it appears,
where ‘C-u g a’ will give information about it.

Select one of the safe coding systems listed below,
or cancel the writing with C-g and edit the buffer
   to remove or modify the problematic characters,
or specify any other coding system (and risk losing
   the problematic characters).

  raw-text no-conversion
```

**Comment by Vonfry** [comment]
When opening file from treemacs, the `pwd` will also print something like `\350\256`, which is not happended when using `find-file`.

**Comment by Alexander-Miller** [comment]
Sounds like it may be related to https://github.com/Alexander-Miller/treemacs/pull/779. Does it still happen with the latest version?

**Comment by Alexander-Miller** [comment]
> When opening file from treemacs, the pwd will also print something like \350\256, which is not happened when using find-file.

You mean opening a file with RET? Treemacs does not do anything special in that case, it'll just use find-file as well. 

What's the value of `default-directory` in the treemacs buffer? What does the following code output when point is on a file where the wrong path is shown?

```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (message "%s" (treemacs--prop-at-point :path)))
```

**Comment by Vonfry** [comment]
Thanks for reply. #779 has fixed this.
