### ISSUE TITLE
LSP doesn't trigger for files opened through treemacs buffer

### ISSUE THREAD

**Issue by hjpotter92** [Alexander-Miller/treemacs#787]
Whenever I open a file from the treemacs buffer, either using the `RET` (dwim) or `o o` (open no-split) the newly opened file doesn't hook into lsp mode with it. I have to manually revisit/refresh the file buffer or call lsp.

Is this the expected/default behaviour? I have also tried with and without the `lsp-treemacs-sync-mode`, but this behaviour is consistent. Any help/ideas would be appreciated.

**Comment by Alexander-Miller** [comment]
Not sure what's going on here. Treemacs does not do anything special to open files. There's a bit of indirection to make space for some user-options, but `RET` or `oo` will always land you right here: https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-interface.el#L223 - a simple call to `find-file`.

Let's try the other side. Ping @yyoncho  - can you make sense of this?

**Comment by hjpotter92** [comment]
@yyoncho The hook is configured for `lsp-deferred`:

``` elisp
  :hook
  (((web-mode js-mode json-mode js2-mode css-mode dockerfile-mode
              python-mode ruby-mode c++-mode c-mode go-mode)
              . lsp-deferred))
  (yaml-mode . (lambda ()
                  (when (eq major-mode 'yaml-mode)
                    (lsp-deferred))))
```

and similarly for `lsp-pyright` (I am working with python+node project currently in treemacs)

```elisp
  :hook
  (python-mode . (lambda ()
                   (require 'lsp-pyright)
                   (lsp-deferred)))
```

The `debug-on-entry` for `lsp` is being triggered for 1 in 3/4 files. Any further details that I missed on, please ask.

Thanks

**Comment by yyoncho** [comment]
@hjpotter92 it might be a focus-related bug related to `lsp-deffered`, can you test with using `lsp` instead of `lsp-deffered` in your config?

**Comment by hjpotter92** [comment]
> @hjpotter92 it might be a focus-related bug in `lsp-deffered`, can you test with using `lsp` instead of `lsp-deffered` in your config?

Tried again with `lsp` instead of `lsp-deferred`, and that seems to have fixed the issue.
