### ISSUE TITLE
When you rename a directory buffers do not get updated to refrence the new file location

### ISSUE THREAD

**Issue by wizardwatch** [Alexander-Miller/treemacs#789]
I am not sure if this is desired behavior, however, the behavior does not match renaming files which update their buffers to reference the new names. This isn't a big issue but I figured I would point it out. Sorry if I missed documentation on this and once again, thank you for making treemacs :)

**Comment by Alexander-Miller** [comment]
Yes, that's definitely a thing that should be happening.

**Comment by Alexander-Miller** [comment]
I've tested it now, and for me it is actually happening:

![rename](https://user-images.githubusercontent.com/5951157/110848975-fa49e800-82ae-11eb-803c-af54f2ab6b3a.gif)

Can you provide a full reproduction recipe?

**Comment by wizardwatch** [comment]
I am not sure how to provide a full reproduction recipe, but I recorded a video showing the behavior. I am using doom emacs.

https://user-images.githubusercontent.com/48140117/110976692-3329a180-832f-11eb-9bcb-0888f162dd6a.mp4

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
Let's have a look at the issue again if it's still relevant.

I've just uploaded a new treemacs version with some improvements to file renaming. First check if the problem still persists with that version (assuming your doom setup doesn't pin a specific version of treemacs).

Looking at the video I'm also suspicious that the pdf viewer might be to blame. To verify that we can add some logs to treemacs' buffer-buffers-after-rename routine. Just eval the following code, run a rename, and tell me what it outputs:

```Elisp
(defun treemacs--reload-buffers-after-rename (old-path new-path)
  "Reload buffers and windows after OLD-PATH was renamed to NEW-PATH."
  ;; first buffers shown in windows
  (dolist (frame (frame-list))
    (dolist (window (window-list frame))
      (let* ((win-buff  (window-buffer window))
             (buff-file (buffer-file-name win-buff)))
        (treemacs-log "Check Buffer %s File %s" win-buff buff-file)
        (when buff-file
          (setq buff-file (expand-file-name buff-file))
          (when (treemacs-is-path buff-file :in old-path)
            (treemacs-without-following
             (with-selected-window window
               (kill-buffer win-buff)
               (let ((new-file (s-replace old-path new-path buff-file)))
                 (treemacs-log "Reload %s as %s" buff-file new-file)
                 (find-file-existing new-file)
                 (treemacs--replace-recentf-entry buff-file new-file)))))))))
  ;; then the rest
  (--each (buffer-list)
    (-when-let (buff-file (buffer-file-name it))
      (setq buff-file (expand-file-name buff-file))
      (treemacs-log "Check Buffer %s File %s" it buff-file)
      (when (treemacs-is-path buff-file :in old-path)
        (let ((new-file (s-replace old-path new-path buff-file)))
          (treemacs-log "Reload %s as %s" buff-file new-file)
          (kill-buffer it)
          (find-file-noselect new-file)
          (treemacs--replace-recentf-entry buff-file new-file))))))
```
