### ISSUE TITLE
Recursively collapse all directories except the one containing the file opened in the current buffer.

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#791]
I have tried to do this myself many times but can't quite get it to work. I want a function that can be globally bound to a keybinding. The function should collapse all opened directories recursively except the one that contains the file that is currently open in the active buffer. I should be able to call this function from any buffer and not just the treemacs one.

**Comment by Alexander-Miller** [comment]
That is actually pretty easy to do if you know the right ingredients: `treemacs-collapse-all-projects` followed by `treemacs-find-file`. 

It does sound useful, so I'd include it in treemacs. All I need is help with a name: when you were looking for this command what terms did you search for?

**Comment by simurgh9** [comment]
Maybe something with "focus" or "narrow-focus"?

**Comment by Alexander-Miller** [comment]
I'v pushed it as `treemacs-narrow-to-current-file` now.
