### ISSUE TITLE
Error with persp-kill

### ISSUE THREAD

**Issue by jkdufair** [Alexander-Miller/treemacs#793]
I'm using `treemacs-perspective`. Working amazingly well! The only problem I'm running into is when I try to kill a perspective (interactively), I get an error saying `treemacs--on-scope-kill` is being called with 0 arguments and the perspective is not killed. I tried to remedy the problem but apparently I'm not knowledgeable enough to do so and submit a PR. For now, I just defined `treemacs--on-scope-kill` with zero args in the `:config` section of `use-package` and it at least allows me to kill the perspective.

Glad to create a PR if you could point me in the general direction of a fix. Thank you!

**Comment by Alexander-Miller** [comment]
I have looked at the code of both treemacs and perspective and I don't see anything that looks like a wrong number of arguments. 

Try producing a stack trace with debug-on-error.

**Comment by jkdufair** [comment]
Thanks for the fast response @Alexander-Miller! I should have provided a bit more detail. Here's what I'm getting:

```
Debugger entered--Lisp error: (wrong-number-of-arguments #<subr treemacs--on-scope-kill> 0)
  treemacs--on-scope-kill()
  persp-kill(nil)
  funcall-interactively(persp-kill nil)
  command-execute(persp-kill)
```

It appears that maybe it's related to adding that function to the `'delete-frame-functions` hook perhaps? The docs for that hooks suggest it should be called with a single parameter that is the frame.

I should also note I'm running Emacs 28. I don't have a functioning Emacs 27 right now. I wouldn't think anything in 28 would be a cause? I don't have a functioning Emacs 27 right now to test.
