### ISSUE TITLE
Debugger entered--Lisp error: (error "Hash table data is not a list of even length")

### ISSUE THREAD

**Issue by nrdsp** [Alexander-Miller/treemacs#794]
I still can use treemacs, but geting this on every start, which is kind of annoying:

    Debugger entered--Lisp error: (error "Hash table data is not a list of even length")
      read("#s(hash-table size 2610 test equal rehash-size 1.5...")
      treemacs--git-status-parse-function(#<process Process Future<4>>)
      treemacs--get-or-parse-git-result(#<process Process Future<4>>)
      treemacs--apply-deferred-git-state(#<marker at 1266 in  *Treemacs-Scoped-Buffer-#<frame emacs@ nunop0x1de4e90>*> #<process Process Future<4>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>)
      apply(treemacs--apply-deferred-git-state (#<marker at 1266 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<4>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>))
      timer-event-handler([t 24677 42618 644758 nil treemacs--apply-deferred-git-state (#<marker at 1266 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<4>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>) nil 610000])
      accept-process-output(#<process Process Future>)
      pfuture-await-to-finish(#<process Process Future>)
      treemacs--git-status-parse-function(#<process Process Future>)
      treemacs--get-or-parse-git-result(#<process Process Future>)
      treemacs--apply-deferred-git-state(#<marker at 746 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>)
      apply(treemacs--apply-deferred-git-state (#<marker at 746 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>))
      timer-event-handler([t 24677 42618 612096 nil treemacs--apply-deferred-git-state (#<marker at 746 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>) nil 544000])
      accept-process-output(#<process Process Future<1>>)
      pfuture-await-to-finish(#<process Process Future<1>>)
      treemacs--git-status-parse-function(#<process Process Future<1>>)
      treemacs--get-or-parse-git-result(#<process Process Future<1>>)
      treemacs--apply-deferred-git-state(#<marker at 709 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<1>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>)
      apply(treemacs--apply-deferred-git-state (#<marker at 709 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<1>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>))
      timer-event-handler([t 24677 42618 586063 nil treemacs--apply-deferred-git-state (#<marker at 709 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<1>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>) nil 269000])
      accept-process-output(#<process Process Future>)
      pfuture-await-to-finish(#<process Process Future>)
      treemacs--git-status-parse-function(#<process Process Future>)
      treemacs--get-or-parse-git-result(#<process Process Future>)
      treemacs--apply-deferred-git-state(#<marker at 629 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>)
      apply(treemacs--apply-deferred-git-state (#<marker at 629 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>))
      timer-event-handler([t 24677 42618 559983 nil treemacs--apply-deferred-git-state (#<marker at 629 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>) nil 351000])
      accept-process-output(#<process Process Future<1>>)
      pfuture-await-to-finish(#<process Process Future<1>>)
      treemacs--git-status-parse-function(#<process Process Future<1>>)
      treemacs--get-or-parse-git-result(#<process Process Future<1>>)
      treemacs--apply-deferred-git-state(#<marker at 477 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<1>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>)
      apply(treemacs--apply-deferred-git-state (#<marker at 477 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<1>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>))
      timer-event-handler([t 24677 42618 458654 nil treemacs--apply-deferred-git-state (#<marker at 477 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<1>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>) nil 782000])
      accept-process-output(#<process Process Future<2>>)
      pfuture-await-to-finish(#<process Process Future<2>>)
      treemacs--git-status-parse-function(#<process Process Future<2>>)
      treemacs--get-or-parse-git-result(#<process Process Future<2>>)
      treemacs--apply-deferred-git-state(#<marker at 354 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<2>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>)
      apply(treemacs--apply-deferred-git-state (#<marker at 354 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<2>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>))
      timer-event-handler([t 24677 42618 435406 nil treemacs--apply-deferred-git-state (#<marker at 354 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<2>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>) nil 95000])
      accept-process-output(#<process Process Future<1>>)
      pfuture-await-to-finish(#<process Process Future<1>>)
      treemacs--git-status-parse-function(#<process Process Future<1>>)
      treemacs--get-or-parse-git-result(#<process Process Future<1>>)
      treemacs--apply-deferred-git-state(#<marker at 202 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<1>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>)
      apply(treemacs--apply-deferred-git-state (#<marker at 202 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<1>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>))
      timer-event-handler([t 24677 42618 399885 nil treemacs--apply-deferred-git-state (#<marker at 202 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future<1>> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>) nil 773000])
      accept-process-output(#<process Process Future>)
      pfuture-await-to-finish(#<process Process Future>)
      treemacs--git-status-parse-function(#<process Process Future>)
      treemacs--get-or-parse-git-result(#<process Process Future>)
      treemacs--apply-deferred-git-state(#<marker at 2 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>)
      apply(treemacs--apply-deferred-git-state (#<marker at 2 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>))
      timer-event-handler([t 24677 42618 370405 nil treemacs--apply-deferred-git-state (#<marker at 2 in  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*> #<process Process Future> #<buffer  *Treemacs-Scoped-Buffer-#<frame emacs@nunop 0x1de4e90>*>) nil 611000])

**Comment by Alexander-Miller** [comment]
What's the output of running `git status --porcelain --ignored` in your repository?
