### ISSUE TITLE
Expand auto-collapsed directories

### ISSUE THREAD

**Issue by chessman** [Alexander-Miller/treemacs#795]
Treemacs automatically collapses directories which content is exactly one directory (controlled by treemacs-collapse-dirs). I wonder, is there a way to do manipulations (rename, move, etc) on any collapsed directory, not just the last one? Or at least a way to expand those directories?

In other words, if directories are collapsed to a/b/c, it seems, there is no way to do something with 'a' or 'b'.

**Comment by Alexander-Miller** [comment]
Yeah, it's not possible yet.
I'll add an extra selection to pick the exact directory.

**Comment by Alexander-Miller** [comment]
Stayin alive.

**Comment by Alexander-Miller** [comment]
I have now added specifying dialogues to all the file management parts like renaming & moving files.

Let me know if anything's missing or broken.
