### ISSUE TITLE
error: [Treemacs] Something went wrong when finding tag 'foo': (wrong-type-argument integer-or-marker-p nil)

### ISSUE THREAD

**Issue by phisu** [Alexander-Miller/treemacs#796]
in my project i open the tags of a file and then click on "All Methods". Now I see all functions in the selected file. if I now click on the function foo I get the following error message: 

`[Treemacs] Something went wrong when finding tag 'foo': [wrong-type-argument integer-or-marker-p nil].`

what is wrong?

i would expect the file to open and the cursor to jump to the function foo. even if the file is already open and i click on the function foo in treemacs, i get the above error message. Is this wrong what i expect? what does the error message mean?

i am using the centaur emacs configuration framework with emacs 27.1 on ubuntu 20.10.

**Comment by Alexander-Miller** [comment]
> what does the error message mean?

Just what it says, something was nil that should not have been. To understand why this is happening I need to reproduce your problem. What does the content of the file look like? Does it happen only in specific files or laguages or always? Are you using something like lsp-mode or is it the same tags you get from `imenu`?

**Comment by phisu** [comment]
i did not try every file in my project; but it happens in (mostly) each php file. i have javascript files in my project too. but with these files nothing happens when i click on "open tags", that is, with these no functions are shown. but that is probably another problem. 

as an example i attach a php file where i have the problem.

yes, i use lsp-mode and the lsp server is intelephense (iph).  until now i had never used imenu. i tried it now and noticed that imenu shows the same symbols as treemacs. when i select one in imenu, i can hop to the symbol.

[c.validate.zip](https://github.com/Alexander-Miller/treemacs/files/6276368/c.validate.zip)

**Comment by phisu** [comment]
i open the treemacs window, switch to my project and navigate to my file c.validate.inc. now i do toggle-debug-on-error and call treemacs-find-tag (C-x t M-t). i get the message in the minibuffer
 
[ Treemacs ] Current buffer is not visiting a file.

Backtrace:

Debugger entered--Lisp error: (error "Cannot make side window the only window")
  signal(error ("Cannot make side window the only window"))
  error("Cannot make side window the only window")
  delete-other-windows()
  open-dashboard()
  funcall-interactively(open-dashboard)
  call-interactively(open-dashboard nil nil)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1fd154df999f>)(open-dashboard nil nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1fd154df999f>) open-dashboard)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1fd154df999f>) open-dashboard)
  command-execute(open-dashboard)


second Try: 
i navigate to my file c.validate.inc and do by the mouse "open tags". then I navigate to "All Methods" .  By Pressing "enter" the tags opens and i navigate to one of them. now i enable "Debug on Error". and do t C-x t M-t . in the minibuffer i get the message:

[Treemacs] Current buffer is not visiting a file.

Backtrace:
Debugger entered--Lisp error: (error "Cannot make side window the only window")
  signal(error ("Cannot make side window the only window"))
  error("Cannot make side window the only window")
  delete-other-windows()
  open-dashboard()
  funcall-interactively(open-dashboard)
  call-interactively(open-dashboard nil nil)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1fc8586a399f>)(open-dashboard nil nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1fc8586a399f>) open-dashboard)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x1fc8586a399f>) open-dashboard)
  command-execute(open-dashboard)

when i click in treemacs on a tag in c.validate.inc, i get the message in the minibuffer : 

[Treemacs] Something went wrong when finding tag 'emptyStr': (wrong-type-argument integer-or-marker-p nil)

and i cannot find a Backtrace.

**Comment by Alexander-Miller** [comment]
Sorry for the late reply, I've been busy for a while and had some catching up to do.

>  error("Cannot make side window the only window")
> delete-other-windows()
> open-dashboard()

Whatever is happening here is a side-effect of you calling this dashboard command which attempts to split the treemacs window. Doing that is not possible because it is a (side window)[https://www.gnu.org/software/emacs/manual/html_node/elisp/Side-Windows.html], unless you set `treemacs-display-in-side-window` to nil.

>  now i enable "Debug on Error". and do t C-x t M-t 

Where did that keybind come from?

**Comment by phisu** [comment]
> now i enable "Debug on Error". and do t C-x t M-t

sorry, this is a typo. correct is C-x t M-t. this keybinding comes from the centaur configuration framework for emacs.

now i set `treemacs-display-in-side-window` to nil. now it works: i click by the mouse on a method and the file will be opened and it jumps to the beginning of the function. this is great! thank you!

one more question: how can i sort the function-names under the tag "All Methods"? when i press s, i can only sort the filenames.

**Comment by Alexander-Miller** [comment]
> now i set treemacs-display-in-side-window to nil. now it works

That may work, but it's no solution. You should really look into where this dashboard command is coming from. 

> how can i sort the function-names under the tag "All Methods"?

Right now you can't. Treemacs just takes whatever it's given by imenu. I'd have to look into how doable sorting tags would be.

**Comment by seagle0128** [comment]
Are you sure they are the same issue?

```elisp
Debugger entered--Lisp error: (error "Cannot make side window the only window")
signal(error ("Cannot make side window the only window"))
error("Cannot make side window the only window")
delete-other-windows()
open-dashboard()
funcall-interactively(open-dashboard)
call-interactively(open-dashboard nil nil)
```

There is no `(wrong-type-argument integer-or-marker-p nil)` error in above backtrace. They looks totally different. I don't think `open-dashboard` will affect `treemacs` if you use it correctly.

**Comment by Alexander-Miller** [comment]
> Are you sure they are the same issue?

I couldn't reproduce the problem OP was having with the file they provided, so I assumed the wrong-type-argument was a follow-up problem, because whatever is happening with the dashboard somehow puts treemacs into an invalid state.

First OP said

> By Pressing "enter" the tags opens and i navigate to one of them. now i enable "Debug on Error". and do t C-x t M-t 

That should call `treemacs-find-tag`, however the stack trace starts with

>  command-execute(open-dashboard)

so my guess is that there's some keybind remap or advice that is doing things it shouldn't.

@phisu What does `describe-key` say about the ` C-x t M-t` keybind? What does `describe-function` say about `treemacs-find-tag`?

**Comment by phisu** [comment]
C-x t M-t runs the command treemacs-find-tag (found in global-map), which is an
autoloaded interactive Lisp closure in ‘treemacs.el’.

It is bound to C-x t M-t.

(treemacs-find-tag)

Find and move point to the tag at point in the treemacs view.
Most likely to be useful when ‘treemacs-tag-follow-mode’ is not active.

Will ask to change the treemacs root if the file to find is not under the
root.  If no treemacs buffer exists it will be created with the current file’s
containing directory as root.  Will do nothing if the current buffer is not
visiting a file or Emacs cannot find any tags for the current file.


treemacs-find-tag is an autoloaded interactive Lisp closure in ‘treemacs.el’.

It is bound to C-x t M-t.

(treemacs-find-tag)

Find and move point to the tag at point in the treemacs view.
Most likely to be useful when ‘treemacs-tag-follow-mode’ is not active.

Will ask to change the treemacs root if the file to find is not under the
root.  If no treemacs buffer exists it will be created with the current file’s
containing directory as root.  Will do nothing if the current buffer is not
visiting a file or Emacs cannot find any tags for the current file.


@seagle0128 can you reproduce the issue?

**Comment by Alexander-Miller** [comment]
No advice, no remapping. Where is that dashboard coming from?

**Comment by seagle0128** [comment]
@phisu  I couldn't reproduce the issue. I believe it's totally another issue.

> Where is that dashboard coming from?
@Alexander-Miller It's from https://github.com/seagle0128/.emacs.d/blob/d008c71e4c358f2bf5bfa421c082441d9c897070/lisp/init-dashboard.el#L208. But it's irrelevant.

**Comment by phisu** [comment]
`I guess you were trying to open dashboard in treemacs window, then got this error, but it's different from the original issue.`

i believe this is correct because i had done the following:

- in the treemacs buffer i navigated to the file c.validate.inc
- pressed tab
- navigated to "All Methods
- pressed tab
- navigated to the password function
- M-x toggle-debug-on-error: in minibuffer I see Debug on Error enabled globally
- C-x t M-t: minibuffer [Treemacs] Current buffer is not visiting a file.
- to find a backtrace i pressed <F2> 

and found the above backtrace in the minibuffer.

now i have the assumption that "[Treemacs] Current buffer is not visiting a file" does not show an error and on the other hand C-x t M-t in treemacs buffer does not open the file and jumps to the selected function, which i expected. 

on the other hand, if i press enter in the treemacs buffer when the cursor is over a function, the main buffer shows scratch and i don't find a backtrace. but in messages i find

```
Followed link to /var/www/html/hbp/webSite/lib/c.validate.inc
LSP :: Connected to [iph:496990/starting].
dap-php: felixfbecker.php-debug debug extension are not set. You can download it with M-x dap-php-setup
LSP :: Connected to [iph:496990/starting].
Followed link to /var/www/html/hbp/webSite/lib/c.validate.inc
/var/www/html/hbp/lib/c.validate.inc and /var/www/html/hbp/webSite/lib/c.validate.inc are the same file
[Treemacs] Something went wrong when finding tag 'url': (wrong-type-argument integer-or-marker-p nil)
LSP :: iph:496990 initialized successfully in folders: (/var/www/html/hbp)
```
here you can see that the link from /var/www/html/hbp/webSite/lib/c.validate.inc to /var/www/html/hbp/lib/c.validate.inc and /var/www/html/hbp/webSite/lib/c.validate.inc causes problems. 

so i navigated to the actual file in treemacs (/var/www/html/hbp/webSite/lib/c.validate.inc) and pressed enter when i was over the function. then the file opened and jumped to the function. 

that means treemacs has problem in this context with links and C-x t M-t above a function not as i expected. i have to press enter to open the file and jump to the function.

**Comment by Alexander-Miller** [comment]
> It's from https://github.com/seagle0128/.emacs.d/blob/d008c71e4c358f2bf5bfa421c082441d9c897070/lisp/init-dashboard.el#L208. But it's irrelevant. I think OP tried to create/delete window in treemacs window.

Yeah, I figured that it's from some external package or a centaur feature. What I meant is why is it being called instead of treemacs, given that it appeared in multiple stack trace I thought it's not just a simple mistype.

> now i have the assumption that "[Treemacs] Current buffer is not visiting a file" does not show an error and on the other hand C-x t M-t in treemacs buffer does not open the file and jumps to the selected function, which i expected.

You have it backwards. Going from inside treemacs to the tag's position in your code is as simple as pressing RET, same as files.

What `treemacs-find-tag` does is find the current tag in treemacs for you when you are currently inside your code. The error (it's really just a warning because it's a common case) says the current buffer has no file because the current buffer is treemacs.

> Followed link to /var/www/html/hbp/webSite/lib/c.validate.inc

That looks familiar. Does the info in https://github.com/emacs-lsp/lsp-mode/issues/2701 help?

**Comment by seagle0128** [comment]
> > now i set treemacs-display-in-side-window to nil. now it works
> 
> That may work, but it's no solution. You should really look into where this dashboard command is coming from.

I agree. `command-execute(open-dashboard)` means `open-dashboard` was executed in the backtrace you provided. But in Centaur, it's only bind to `<f2>`. You should figure out why is called.

**Comment by phisu** [comment]
`That looks familiar. Does the info in emacs-lsp/lsp-mode#2701 help?`

@Alexander-Miller I set  
```
(custom-set-variables
'(lsp-enable-links nil))
```
but it does not help.

**Comment by phisu** [comment]
`You should figure out why is called.`
@seagle0128 I pressed f2 to find the backtrace. but there was no backtrace (https://github.com/Alexander-Miller/treemacs/issues/796#issuecomment-832168490)

**Comment by seagle0128** [comment]
@phisu I believe it's a mistype. I can reproduce while pressing <f2> in treemacs window. IMO it's more like a warning.

![image](https://user-images.githubusercontent.com/140797/117245766-ef09d780-ae6d-11eb-891d-00b2e2bd41ca.png)

**Comment by phisu** [comment]
yes you are right! I misunderstood treemacs-find-tag . 

thank you for your efforts and for your great configuration framework.thank you!
