### ISSUE TITLE
File icons disappear if indent-guide is on

### ISSUE THREAD

**Issue by jbharat** [Alexander-Miller/treemacs#80]
I have file-icons disappearing, but this issue is not related to #66. File icons disappear if indent-guide is on. The fix I am using is 
```
(add-hook 'treemacs-mode-hook 'spacemacs/toggle-indent-guide-off)
```
I think this can be part of treemacs. Or if there is a better fix.

Spacemacs develop branch.
treemacs-20171014.737
treemacs-evil-20170925.2232
treemacs-projectile-20170903.1235

**Comment by Alexander-Miller** [comment]
Thanks. This will be fixed with https://github.com/Alexander-Miller/treemacs/commit/c2a34fe0e3b36985685d47ee6f34760dad394a2a, you just need to wait for melpa to build.
