### ISSUE TITLE
treemacs-icons-dired and hl-line-mode, can't select in dired

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#802]
When `treemacs-icons-dired` and `hl-line-mode` are enabled,
Then it isn't possible to select text in a dired buffer.

### Reproduction steps
With just Emacs and the `treemacs-icons-dired` package installed.
- open a dired buffer: `C-x d`
- start a selection: `C-SPC`
- move the cursor to show that the selection is active: hold Ctrl and press: `f`, `b`, `n` or `p` a couple of times
- enable `M-x` `treemacs-icons-dired-mode`
the selection was canceled (side note, below).
- start a new selection and move the cursor, it still works as expected.
- enable `M-x` `hl-line-mode`

### Observed
Now it isn't possible to select anything.

Pressing `C-SPC` just shows `Mark set`.
Moving the cursor doesn't show a selection.

Any additional `C-SPC` presses, keeps showing `Mark activated`.
And `C-x SPC` the first or more times, keeps showing `Mark set (rectangle mode)`

Disabling either `treemacs-icons-dired-mode` or `hl-line-mode`.
Makes it possible to select again.

In Spacemacs, both `treemacs-icons-dired-mode` and `global-hl-line-mode` are enabled by default.

A selection can be started, with the `vim` editing style (evil-mode), 
`v` shows a cursor box selection on the current character.
`V` selects the current line.
but both are canceled when the cursor is moved.

However a block selection `C-v`, can be modified without any issues.
The block selection is probably handled differently to be able to show it,
with a vertical left and right side.

I encountered one case where it worked to modify a selection, on one dired line,
with both `treemacs-icons-dired-mode` and `hl-line-mode` enabled.

It occurred when a directory icon didn't appear on the line with the cursor.
I might have opened a directory and navigated back with `^`.
~But I'm unable to reproduce it.~

#### Update
I found a way to reproduce this.
When a new directory is created: `+`
Then that line doesn't get an icon until the dired buffer is refreshed.

In this state, it is possible to keep the selection active, 
while moving left and right all the way to the beginning or end of the line.

But as soon as one moves up to the line above or down to the line below,
then the selection is canceled. Because those lines have an icon.

In evil mode, it's possible to extend the selection to the line above or 
to the line below, but as soon as the cursor is moved on those lines,
then the selection is canceled.

### Expected
It should be possible to select text when both `treemacs-icons-dired-mode` and `hl-line-mode`  are enabled.

### Side note:
Currently when `hl-line-mode` is disabled.

If there's an active selection when `treemacs-icons-dired-mode` is enabled.
Then the selection is canceled.

And if there's an active selection when `treemacs-icons-dired-mode` is disabled.
Then the selection starts from the buffers first character and ends at the beginning of the current lines file name.

The selection should probably remain active and unmodified in both cases.

That's what happens when `hl-line-mode` is enabled or disabled.

### System info
treemacs-icons-dired-20210107.1251
[Treemacs] v2.8 (installed 2021.04.16) @ Emacs 27.2 (might not be relevant, at least it shows the installation date)
GNU Emacs 27.2 (build 1, x86_64-w64-mingw32) of 2021-03-26
Windows 10 Version 2004

**Comment by Alexander-Miller** [comment]
Looks like the icon background color correction is interfering with the region selection for whatever reason. 

The whole thing is set up to only handle single line movements anyway, so disabling color correction when the region is active should be a valid fix.

**Comment by duianto** [comment]
Selecting in a dired buffer, works as expected now, thanks.
