### ISSUE TITLE
Treemacs 2.8 There is no parent to move up to.

### ISSUE THREAD

**Issue by Antiarchitect** [Alexander-Miller/treemacs#803]
With todays update I cannot change root up by pressing `h` with the following:
[Treemacs] There is no parent to move up to. [19 times]

**Comment by Alexander-Miller** [comment]
There's been some (breaking) changes with the keybinds.

Long story short: `h` is now just as configurable as TAB and RET and `l` is rebound as well. By default they now open/close stuff or move up if the node is already closed. You can read about it in https://github.com/Alexander-Miller/treemacs/issues/534

To get the previous behavior back you can either

 - use `M-H` & `M-L` instead
 - change the config like this `(treemacs-define-COLLAPSE-action 'dir-node-open #'treemacs-root-up)` 
   That'll have to be repeated for every other node type there is (the eldoc will tell you where to look this up).

(Actually I just noticed I'll have to push a small patch to make the 2nd solution work, I'll do that some time tomorrow.)

**Comment by Antiarchitect** [comment]
```
(defun dotspacemacs/user-config ()
  ;; TREEMACS
  (with-eval-after-load 'treemacs
    ;; (treemacs-define-COLLAPSE-action 'dir-node-open)
    (treemacs-define-COLLAPSE-action 'treemacs-root-up)
  )
)
```
Now gives me this error JFYI:
Wrong number of arguments: (2 . 2), 1

**Comment by Antiarchitect** [comment]
One more thing, when I type M-H according to hydra help, I got already at root and cannot move to parent folder either

**Comment by Alexander-Miller** [comment]
Oh and you also need to grab the latest version of treemacs for the code to work properly, I've no pushed the fix that I mentioned yesterday.

**Comment by Antiarchitect** [comment]
Thank you so much, I'm not very into lisp, so your explanation is very helpful👍

**Comment by Antiarchitect** [comment]
Grabbed latest version. Inserted your config part inside `(defun dotspacemacs/user-config () ... )`. Getting this error:
```
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s value as variable is void: treemacs-mode-map
```

My full function is:
```
(defun dotspacemacs/user-config ()
  ;; VISUAL MODE REPLACE
  (setq evil-ex-visual-char-range t)

  ;; HELM AG SETUP
  (evil-leader/set-key "/" 'spacemacs/helm-project-do-ag)
  (setq helm-ag-base-command "rg --glob=!*.git/* --hidden --no-heading --no-ignore --smart-case --text --vimgrep")

  ;; JSON indentation
  (setq js-indent-level 2)

  ;; org-projectile
  (require 'org-projectile)
  (org-projectile-per-project)
  (setq org-projectile-per-project-filepath "TODO.org")
  (setq org-agenda-files (append org-agenda-files (org-projectile-todo-files)))
  (setq org-todo-keywords '((sequence "TODO(t)" "INPROGRESS(p)" "CHECK!(c)" "WAIT(w)" "DONE(d)")))
  (setq org-todo-keyword-faces
        '(("INPROGRESS" . org-warning)
          ("CHECK!" . org-warning)
          ("WAIT" . org-warning)
        ))
  ;; TREEMACS
  (define-key treemacs-mode-map (kbd "l") #'treemacs-root-down)
  ;; for evil (evil-define-key 'treemacs treemacs-mode-map (kbd "l") #'treemacs-root-down)

  (dolist (state '(root-node-open root-node-closed dir-node-open dir-node-closed file-node-open
                                  file-node-closed tag-node-open tag-node-closed tag-node))
    (treemacs-define-COLLAPSE-action state #'treemacs-root-up)))
```

**Comment by Antiarchitect** [comment]
If I switch to evil-define-key (seems work) I get:
```
Symbol’s function definition is void: treemacs-define-COLLAPSE-action
```

**Comment by Antiarchitect** [comment]
Alright, this works:
```
(defun dotspacemacs/user-init ()
  "Initialization for user code:
This function is called immediately after `dotspacemacs/init', before layer
configuration.
It is mostly for variables that should be set before packages are loaded.
If you are unsure, try setting them in `dotspacemacs/user-config' first.")


(defun dotspacemacs/user-load ()
  "Library to load while dumping.
This function is called only while dumping Spacemacs configuration. You can
`require' or `load' the libraries of your choice that will be included in the
dump.")

(defun dotspacemacs/user-config ()

  ...

  ;; TREEMACS
  (with-eval-after-load 'treemacs
    ;; (evil-define-key 'treemacs treemacs-mode-map (kbd "h") #'treemacs-root-up)
    (evil-define-key 'treemacs treemacs-mode-map (kbd "l") #'treemacs-root-down)
    ;; (define-key treemacs-mode-map (kbd "h") #'treemacs-root-up)
    ;; (define-key treemacs-mode-map (kbd "l") #'treemacs-root-down)

    (dolist (state '(root-node-open root-node-closed dir-node-open dir-node-closed file-node-open
                                    file-node-closed tag-node-open tag-node-closed tag-node))
      (treemacs-define-COLLAPSE-action state #'treemacs-root-up)))
)
```
Closing and many thanks! :)

**Comment by Alexander-Miller** [comment]
You need to use lazy-loading again. I left out the `with-eval-after-load 'treemacs` part because you already had it right.

You are seeing those errors because you are accessing variables that do not yet exist. That works with lines like `(setq js-indent-level 2)` because you are just setting a value, and js-mode will not override it when it sees that the variable already exists, but reading variables and calling functions will not work. Loading stuff later is also better for your load times, but that's a different story.
