### ISSUE TITLE
File-follow-mode not working

### ISSUE THREAD

**Issue by darim1** [Alexander-Miller/treemacs#804]
I encounter problems, when trying to use file-follow-mode in treemacs. In my setup it is enabled, but refreshing won't occur. Even quiting and re-opening treemacs won't change the tree. 

My setup:

emacs 27.1
Windows 10 Pro
filewatch-mode => enabled
follow-mode     => enabled

Can someone kindly give me a hint about how I can track this down?

Thanks,
Daniel

**Comment by Alexander-Miller** [comment]
What does the content of your project look like?

What happens when you call `treemacs-find-file`?

**Comment by darim1** [comment]
1. I create a file test.org => treemacs will show file
2. I add heading * bla and save => treemacs will show heading
3. I add sub-heading ** blabla => treemacs will not show sub-heading

treemacs-find-file does not help.

**Comment by Alexander-Miller** [comment]
> treemacs-find-file does not help.

`treemacs-find-file` and follow-mode both only work for moving to files. Since your problem is about org-mode headlines you need `treemacs-find-tag` or `treemacs-tag-follow-mode`.

Do either of these do what you want? Make sure that `imenu-auto-rescan` is set to `t`as well.

**Comment by darim1** [comment]
Yep, both are doing the job. It's pretty cool! Thanks a lot for the quick help!

**Comment by Alexander-Miller** [comment]
> In addition it may be advisable to lower treemacs-file-event-delay

Probably. I originally set it so high with the reasoning that some compiler might spit out a few hundred files, so it's better to wait to make sure that's all done, but in hindsight I doubt that use-case is all that common.
