### ISSUE TITLE
How to expand directory when treemacs

### ISSUE THREAD

**Issue by introom** [Alexander-Miller/treemacs#812]
When I invoke =treemacs=, the directory is closed.  For example, 
![image](https://user-images.githubusercontent.com/669045/119259130-4d211380-bbff-11eb-840e-f363cbc0ab82.png)

I want it to be expanded by default.
For example,
![image](https://user-images.githubusercontent.com/669045/119259140-5c07c600-bbff-11eb-99ef-4dbd8f3f796f.png)

**Comment by Alexander-Miller** [comment]
Not doable right now, the closes thing is `treemacs-follow-after-init`, but that requires already being in the file that you want to see in treemacs.

But it's easy to implement, so I can add such a feature in a bit.

**Comment by Alexander-Miller** [comment]
Added ~treemacs-expand-after-init~. Let me know if anything breaks.

**Comment by introom** [comment]
Thanks for the quick response.
Not using staight.el.  I will verify it after it hits melpa.

One off-topic question, treemacs-Tab-action  (basically expand the directory) is quite slow. Rougly takes 1 second.

This only happens in terminal, but not in GUI.

**Comment by Alexander-Miller** [comment]
> One off-topic question, treemacs-Tab-action (basically expand the directory) is quite slow. Rougly takes 1 second.

Is it still slow when you call `treemacs-TAB-action` with `M-x`?

**Comment by introom** [comment]
Yes. Expanding is slow but collapsing is fast.  1s might be some exaggeration, 0.5s maybe more accurate.

**Comment by introom** [comment]
@Alexander-Miller I found setting treemacs-collapse-dirs to 0 solves the issue.

**Comment by introom** [comment]
The doc says it is invoked asynchronously. Dunno how it impairs the performance.

**Comment by Alexander-Miller** [comment]
The asynchronicity, or rather the parallelism, is limited. Directories that can be flatten are searched in a python script that runs while Emacs itself is busy looking up a directories contents, building all the necessary metadata, and inserting things into the buffer. Once that's finished the output of python script is awaited and directories are flattened immediately. You as a user never notice that /foo becomes /foo/bar/baz the way it happens with deferred git mode.

It might be that the python is self is slow for whatever reason (too many directories, slow remote connection). You can try running it like this:

`python ~/path/to/treemacs/treemacs-dirs-to-collapse.py /path/to/project 3 x`
