### ISSUE TITLE
Prompt of avy-goto-char-2 immediately disappears

### ISSUE THREAD

**Issue by introom** [Alexander-Miller/treemacs#813]
Inside treemacs buffer, when I invoke avy-goto-char-2 *with*  a key binding, the prompt 
`char 1:` 
appears and then disappear immediately.

I have, if I invoke avy-goto-char-2 with M-x, the prompt stays there.

**Comment by Alexander-Miller** [comment]
Had a bug in the eldoc implementation. Should be fixed now.
