### ISSUE TITLE
Is it possible to achieve the following workflow?

### ISSUE THREAD

**Issue by introom** [Alexander-Miller/treemacs#815]
When the current buffer refers to a file in a project (in the sense of projectile, so .git, .svn., .projectile all will make a project), if we open treemacs, it will automatically show that project in treemacs.

At any time, the treemacs workspace only contains one project, and that project is the current project.

The cumbersome thing at the moment is, when I am in a project and I open treemacs, I have to manually create that project in treemacs.

**Comment by Alexander-Miller** [comment]
There's 2 commands in treemacs to quickly add a project:

 - `treemacs-add-and-display-current-project`
 - `treemacs-display-current-project-exclusively`

Both will add the current project to treemacs, the 2nd one will kick out everything else. Binding that to a convenient key should get you just what you want.

> (in the sense of projectile, so .git, .svn., .projectile all will make a project)

Treemacs supports whatever projects projectile and the builtin project.el know about.

**Comment by introom** [comment]
Thanks. This should pretty much solve the problem.

Just want to this for more general use.  Currently, treemacs-display-current-project-exclusively will fail if it is not inside a project.  In that case, intstead of let treemacs err with [Treemacs] Not in a project.

Could we just directly add the directory that the file is in as a treemacs project ?

**Comment by Alexander-Miller** [comment]
Sure, I can add that as a final fallback.
