### ISSUE TITLE
How to open file in last active window?

### ISSUE THREAD

**Issue by Qqwy** [Alexander-Miller/treemacs#816]
Hi all!

I recently switched from the stable version of Spacemacs to the development version. I like most of the features Treemacs brings over NeoTree. However, I am very much used to a file opening (using RET or double-mouse-click) in the last window which was active, rather than always in 'window 1'.

How can Treemacs be configured to do this?

Thank you for your help!

**Comment by Alexander-Miller** [comment]
The command to do that is `treemacs-visit-node-in-most-recently-used-window`, bound to `or`.

You can look that stuff up in the helpful hydra bound to `?` (though granted it's abbreviated as "mru window" in there).

To get that behavior by default (for files) you can configure treemacs with

```Elisp
(treemacs-define-RET-action 'file-node-open   #'treemacs-visit-node-in-most-recently-used-window)
(treemacs-define-RET-action 'file-node-closed #'treemacs-visit-node-in-most-recently-used-window)
```

Same with `treemacs-define-doubleclick-action` and any other node type you want (the eldoc explains where to look them up).
