### ISSUE TITLE
single mouse click expansion

### ISSUE THREAD

**Issue by heavyblack1** [Alexander-Miller/treemacs#818]
I put this line in to my config but it will brake treemacs from loading
`(define-key treemacs-mode-map [mouse-1] #'treemacs-single-click-expand-action)`
and it will give me this error
`Symbol's value as variable is void: treemacs-mode-map`

**Comment by Alexander-Miller** [comment]
You're missing the lazy loading. The code must look like this:

```Elisp
(with-eval-after-load 'treemacs
  (define-key treemacs-mode-map [mouse-1] #'treemacs-single-click-expand-action))
```
