### ISSUE TITLE
Current project is already shown.  While actually it is not shown.

### ISSUE THREAD

**Issue by introom** [Alexander-Miller/treemacs#819]
Phenomenon: treemacs-display-current-project-exclusively won't show the treemacs side window.
![image](https://user-images.githubusercontent.com/669045/120490711-393d9480-c3eb-11eb-85d3-13e583c66954.png)

Should we call the command treemacs first and then call treemacs-display-current-project-exclusively ?

**Comment by Alexander-Miller** [comment]
> Should we call the command treemacs first and then call treemacs-display-current-project-exclusively ?

No, that's not necessary. I've pushed a patch to adjust that behavior so `show-project` and `show-project-exclusively` will behave the same.

**Comment by introom** [comment]
Thanks for the efforts. Normally when will the master arrive at melpa stable?

**Comment by Alexander-Miller** [comment]
It won't. To get something to melpa stable I'd have to push a new tagged version, and I only plan to do that for #677.
