### ISSUE TITLE
Creating a new file with cf in an empty folder will fail

### ISSUE THREAD

**Issue by everiori** [Alexander-Miller/treemacs#82]
Steps for reproducing:
1. Open treemacs
2. Press cd to create a new directory named "test"
3. Press l to change the root to directory "test"
4. Press cf to create a new file, which will cause the failure as the attachment

![create_file](https://user-images.githubusercontent.com/5765846/31652092-9230bc0c-b350-11e7-94ae-3541293797b2.png)

**Comment by Alexander-Miller** [comment]
Confirmed.

Though actually its not about file creation. Its just that refersh does not work in an empty dir. I wanted to redo the create file/dir functions for a while now, make their interface a bit nicer, so Ill include that in the fix.

**Comment by Alexander-Miller** [comment]
Pushed a fix, refresh can now handle empty directories.
Also made create file/dir a bit smarter, they'll now pick up the path under point and will start selection from there.

Let me know if everything's fixed on your end.

**Comment by Alexander-Miller** [comment]
I'll take the lack of feedback to mean everything's ok.
