### ISSUE TITLE
treemacs icons load only on installation and then disappear after restarting emacs

### ISSUE THREAD

**Issue by mukundzare** [Alexander-Miller/treemacs#820]
Hi,
I have used the boilerplate treemacs config from the readme.md file in this repo. Upon installation and launching treemacs, the icons look okay. 
However after restarting emacs, the icons are gone.
Why would that be happening?
![Screenshot from 2021-06-16 21-28-28](https://user-images.githubusercontent.com/1909234/122281112-715bd180-ced9-11eb-9d9c-4e73726d543c.png)

**Comment by Alexander-Miller** [comment]
We have to debug.

In the broken state open treemacs and run this code in the scratch buffer:

```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (treemacs-get-icon-value "el"))
```

The output has to look like this:

```Elisp
#("  " 0 1
  (display (image :type png :file "/home/am/Documents/git/treemacs/icons/default/emacs.png" :scale 1 :ascent center :width 22 :height ...)
           img-selected (image :type png :file "/home/am/Documents/git/treemacs/icons/default/emacs.png" :scale 1 :ascent center :width 22 :height ...)
           img-unselected (image :type png :file "/home/am/Documents/git/treemacs/icons/default/emacs.png" :scale 1 :ascent center :width 22 :height ...)))
```

In particular the `:file` parts have to point at the icons of your treemacs installation.
Is this all correct on your end?

**Comment by mukundzare** [comment]
Hi, 

yes it seems to be the same the only difference being that I installed it via melpa so it is located under the elpa folder: 
```lisp
#("  " 0 1 (display (image :type png :file "/home/mz/.emacs.default/elpa/treemacs-20210606.1918/icons/default/emacs.png" :scale 1 :ascent center :width 22 :height ...) 
img-selected (image :type png :file "/home/mz/.emacs.default/elpa/treemacs-20210606.1918/icons/default/emacs.png" :scale 1 :ascent center :width 22 :height ...) 
img-unselected (image :type png :file "/home/mz/.emacs.default/elpa/treemacs-20210606.1918/icons/default/emacs.png" :scale 1 :ascent center :width 22 :height ...))
```

**Comment by Alexander-Miller** [comment]
Ok, let's try a few other things:

- Do you see the icon when inserted by `(insert (treemacs-get-icon-value "el"))`?
- Are any icons visible when you call `treemacs-icon-catalogue`?
- What does `(with-current-buffer (treemacs-get-local-buffer) (treemacs--should-use-tui-icons?))` return?
- Does the following work?
  `(insert (propertize " " 'display (create-image "/home/mz/.emacs.default/elpa/treemacs-20210606.1918/icons/default/emacs.png" 'png)))`

**Comment by mukundzare** [comment]
A bit late to answer, but here they are:

> Do you see the icon when inserted by `(insert (treemacs-get-icon-value "el"))`? 

No

> Are any icons visible when you call `treemacs-icon-catalogue`?

No, every icon is shown as an X.

> What does `(with-current-buffer (treemacs-get-local-buffer) (treemacs--should-use-tui-icons?)) return`?

`nil`

> Does the following work? 
> `(insert (propertize " " 'display (create-image "/home/mz/.emacs.default/elpa/treemacs-20210606.1918/icons/default/emacs.png" 'png)))`

Yes, this one does work.

**Comment by Alexander-Miller** [comment]
> Yes, this one does work.

Do icons for .el files also appear when you evaluate `(treemacs-create-icon :file "emacs.png" :extensions ("el" "elc"))`?

If yes take a look at the output of this code before and after the create-icon call:

```Elisp
(let ((print-level most-positive-fixnum)
      (print-length most-positive-fixnum))
  (print (treemacs-get-icon-value "el")))
```

It'll print the full output, without the `...` abbreviation. Does anything change, or are both outputs the same?
