### ISSUE TITLE
Speedbar-like Mode Mapping

### ISSUE THREAD

**Issue by dustinlacewell** [Alexander-Miller/treemacs#823]
In speedbar you associate a custom display modes with a given major modes. As buffers in those major-modes get focus, the speedbar updates by using the appropriate display mode.

If I am trying to create an treemacs extension(s?) that show certain items for foo-mode and different items for bar-mode how do I associate the extensions with those modes? I can't really understand how extensions are associated with specific major-modes from the documentation.

**Comment by Alexander-Miller** [comment]
I'll have to say no to this one. Dealing with these kind of updates is very much
outside of the extension api's scope, and I doubt this feature would be popular
enough to justify the non-trivial effort. At most I'll probably create some
related hooks as part of #788.

Covering just your own use-case should be straight forward enough with the new
`window-selection-change-functions`.

Also if you're getting into extensions keep in mind the api is getting a major
face-lift in #677.

**Comment by dustinlacewell** [comment]
I am hoping you might reconsider this feature with the advent of #489

I would be very very useful to be able to provide a unique treemacs hierarchy/interaction UX for specific major-modes. The use-case that inspired this issue was attempting to give one of the Emacs IRC clients modern side-bar concepts. For example, when looking at a channel buffer you'd get a list of users in that channel, etc.

Being able to easily associate a given treemacs view with a given buffer / major-mode is a kill feature for me.

**Comment by Alexander-Miller** [comment]
When you describe it like this it suddenly starts sounding similar to what I thought about with regards to #491. So, no promises, but I will revisit this when I finally get around to creating that mu4e addon.
