### ISSUE TITLE
Creating a file/directory with similar name

### ISSUE THREAD

**Issue by calebstewart** [Alexander-Miller/treemacs#828]
I must admit this could be a configuration issue, but I couldn't find any reference to it on the internet.

When creating a new directory or file from `treemacs`, a pane is display for you to type the new directory name. When typing, it tries to show files/directories with similar names, and pressing enter will select one from the list. This creates a problem when trying to create a new directory with a similar name to an existing directory. It's impossible. As an example, assume you have a directory tree like:

```
- project-root/
  - something/
  - file-one
```

And you want to create a new directory named `some`, pressing `c d` to create a new directory in `treemacs` presents this pane:

![image](https://user-images.githubusercontent.com/7529189/125327691-60a04f00-e311-11eb-8f46-b05a238ef2a2.png)

Pressing enter after typing `some` simply selects `something` from the list, and says that it already exists. There appears to be no way to create a new directory or file named with a substring of an existing item. Similarly, trying to create `file` would result in a message that `file-one` already exists because the pane auto-selects the existing item from the list instead of using what was typed.

 Is there any way to create a new file/directory with a name that is a substring of an existing item? This seems like a huge problem to me. I've had to resort to creating the files/directories from a terminal then switching back to `emacs`, which is fine, but not at all ideal. Again, if there is some configuration I'm missing, I'd love to know. This is currently the default configuration from `doom-emacs` with the exception of some custom `ignored-file-predicates`, so I'm not sure what the problem would be or how it would be different from anyone else.

**Comment by calebstewart** [comment]
I was informed this is just a weird/poor UI design decision from `ivy` and doesn't appear to be a `treemacs` specific issue. Just in case anyone stumbles on this:
 
 The official [documentation](https://oremacs.com/swiper/) appears to state that `C-M-j` should invoke `ivy-immediate-done` to use the current input instead of completing from a list, however this does not work for me. I assume this cryptic short-hand means `Ctrl+Shift+m+j`, and have tried every nearby combination I can think of, but all do nothing (however `Ctrl+m` does do the same as `RET` as the documentation above states).
 
 As a workaround, you can press the up arrow to select the input box and press enter, which will create the file as you have typed it. I didn't even know that was possible and it's not very intuitive, but does "solve" my problem in a way.

**Morale of the story, the above is just to help Googlers later, and this appears to not be relevant here. Sorry, and I appreciate your time!**

**Comment by Alexander-Miller** [comment]
To be fair to ivy: the function I am calling is called `read-file-name`. Making it non-straightforward to enter the name of a directory that does not actually exist is not too big a surprise. AFAIK only helm has your verbatim input as an explicit selection candidate. 

I am using selectrum myself and there this option is slightly hidden. The first line with your input can also be selected:
![s](https://user-images.githubusercontent.com/5951157/125521210-8ab1e672-4175-4063-a4ad-618cd9e5f62b.png)
Maybe ivy can do that as well?

**Comment by Compro-Prasad** [comment]
@calebstewart ,

> `C-M-j`

The above keybinding is the Emacs representation of `Ctrl` + `Alt` + `j` or you can also use `Esc` `Ctrl` + `j` (There is no + in between `Esc` and `Ctrl` which means you need to leave `Esc` before pressing `Ctrl` + `j`).

`M` in Emacs represents the `Meta` key which in modern keyboards is either `Alt` or `Esc`. This information has been covered in the Emacs tutorial. Make sure to go through it properly. You can access the tutorial using `C-h t` or `M-x` `help-with-tutorial` (Here `M-x` means `Alt` + `x`).
