### ISSUE TITLE
Wrong type argument: arrayp, nil

### ISSUE THREAD

**Issue by wibed** [Alexander-Miller/treemacs#829]
as in 
#501 

i am experiencing similar behaviour opening treemacs (starting treemacs `M-x treemacs`)
the message: "There is nothing to do" appears

while opening treemacs from within a folder results  
in: "Wrong type of argument: arrayp, nil"

the message log:
https://termbin.com/5ky2

the stack trace:
https://termbin.com/td4h

could it be because of recent commits?

i have pinned treemacs to:
  - 2655a8976d56719add893cec45a18e018626842d
  - a6f9e9f1cea3502b3ead082fd208c4011a55add0
  
without success

to pin treemacs to:
  - 1a02b862ad43761d5530b894bbdbf29f5b79fd9f

works as a workaround, i might add i have no idea about the versions inbetween.
and just picked a date late enough i could make sure not to build 20 times

**Comment by Alexander-Miller** [comment]
> Wrote /root/.emacs.d/.local/cache/treemacs-persist
"treemacs-persist" 0L, 0C written

Whatever is happening is likely caused by these lines. *Something* is making treemacs write an empty persist file in a way that you're not even asked to select your first project.

There are a few doom-specifica in the stack trace, so let's eliminate that as a cause of errors first. Try installing treemacs as a normal package, without the extras added by the doom module. `treemacs-add-and-display-current-project` should be the closest entry point to what doom is doing.

**Comment by wibed** [comment]
i too cant open a project from the fallback buffer, if treemacs is not pinned to said commit.


c2b0beaeb0383c3e6cbc453d6c42cdbc87c6da5e, is the breaking commit. up until this one treemacs works fine.

**Comment by Alexander-Miller** [comment]
>   treemacs-find-file-node(&rdquo;//work&ldquo; #s(treemacs-project :name &rdquo;&ldquo; :path &rdquo;*&rdquo; :path-status local-readable :is-disabled? nil))

This is another strange like. The page you uploaded the stack trace to broke some of the formatting, but it looks like treemacs is trying to move to a file `/work` which is in a project that's located at `*`, which isn't even a proper path. What is the content of you `treemacs-persist-file`?

**Comment by ogdenwebb** [comment]
I start getting a similar error recently as well. Whenever I call `M-x treemacs` it complains `wrong-type-argument char-or-string-p nil`

```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  treemacs--add-root-element(#s(treemacs-project :name "org" :path "/home/ogden/Drive/org" :path-status local-readable :is-disabled? nil))
  treemacs--render-projects((#s(treemacs-project :name "org" :path "/home/ogden/Drive/org" :path-status local-readable :is-disabled? nil)))
  treemacs--init()
  treemacs()
  funcall-interactively(treemacs)
  call-interactively(treemacs nil nil)
  command-execute(treemacs)
```

I've tried to wipe treemacs-persist-file, but it didn't fix the problem. Content of treemacs-persist-file
```
* Default
** org
 - path :: ~/Drive/org
```
