### ISSUE TITLE
Some issues with treemacs-do-remove-project-from-workspace

### ISSUE THREAD

**Issue by lucasvreis** [Alexander-Miller/treemacs#830]
I was investigating the cause of the error `apply: Wrong type argument: stringp, cannot-delete-last-project` (also reported in #711) and found some issues with the implementation of `treemacs-do-remove-project-from-workspace`:

1. Docstring - should be "Remove":
https://github.com/Alexander-Miller/treemacs/blob/e4a85e3266581b8a8f526dbf4142c26d6e76d294/src/elisp/treemacs-workspaces.el#L522-L523

2. Code - the docstring explains what it should return:
https://github.com/Alexander-Miller/treemacs/blob/e4a85e3266581b8a8f526dbf4142c26d6e76d294/src/elisp/treemacs-workspaces.el#L533-L541
this seems fine for the `sucess` case. But the error cases run `treemacs-error-return-if`, what causes the call to throw an error because `treemacs-error-return-if` passes the parameter to `treemacs-pulse-on-failure` (which expects a string):
https://github.com/Alexander-Miller/treemacs/blob/e4a85e3266581b8a8f526dbf4142c26d6e76d294/src/elisp/treemacs-workspaces.el#L543-L547

The function `treemacs-remove-project-from-workspace` also expects it to return a symbol as explained in the docstring.

**Comment by Alexander-Miller** [comment]
Thanks for the heads up. Looks like I have some cleaning up to do.

**Comment by Alexander-Miller** [comment]
Should all be fixed now. Let me know if I missed anything.
