### ISSUE TITLE
treemacs-show-gitignored-files does not apply on the initial call

### ISSUE THREAD

**Issue by martenlienen** [Alexander-Miller/treemacs#834]
Hi,
I have now added the new `treemacs-show-gitignored-files` feature into my emacs config and noticed a minor misbehavior. In my init.el, I call `(treemacs-toggle-show-gitignored-files)` in an after-load hook (`:config` in use-package), so that the filter hook gets set up correctly. When I then call `M-x treemacs`, the hook gets applied (I verified that the variables are set correctly afterwards) but ignored files are still visible. Refreshing the treemacs buffer hides them as expected.

All in all, it looks like treemacs may not obey `treemacs-pre-file-insert-predicates` on the initial display. If I kill the treemacs buffer and start it again or switch projects, everything works. It just happens on this very first call.

**Comment by martenlienen** [comment]
I just noticed another aspect of (apparently) the same problem. When I expand / open a directory node that includes an ignored directory, the directory will be correctly colored, i.e. grayed out, but only hidden after I refresh the buffer again.

**Comment by Alexander-Miller** [comment]
That is the major disadvantage of using `deferred` git-mode: the first thing you
see is always the information from the last time treemacs looked at this
directory. If this is the first time then treemacs simply doesn't know anything
yet.

The simplest solution is of course to use `extended` git-mode instead. But it is
not exactly the one I like. There's a good reason I made `deferred` mode the
standard, that extra delay really does help.

Another option is to just delete the ignored files at the time that the git
fontification is applied. That would work, but it would look weird to see files
disappear after half a second.

What I am hoping will be doable is to basically "pre-fetch" the list of ignored
files in the background when treemacs is first loaded and stuff that info into
treemacs' cache so it's available from the very start. The problem with this
approach that git might list those 25000 individual ignored files somewhere in
your build directory. Luckily it looks like the `git clean -ndX` command
provides just the information I need. So unless you tell me that this is not the
case and there is something wrong with the `git clean` approach this is the
solution I will be trying first.

**Comment by martenlienen** [comment]
I have checked and `git clean -ndX` lists all the files and directories that should be hidden, so a solution based on that should work nicely.

**Comment by martenlienen** [comment]
What leaves me wondering is that apparently treemacs knows about the ignored files and directories from the beginning because they are greyed out even when they are not hidden. Or is it the case that they change color to grey after the initial load and it just happens to quickly for me to notice?

**Comment by Alexander-Miller** [comment]
> Or is it the case that they change color to grey after the initial load and it just happens to quickly for me to notice?

That delay is governed by `treemacs-deferred-git-apply-delay`. You can turn that up to a few seconds and then try again.

**Comment by martenlienen** [comment]
I have set it to 5.0 before the initial `M-x treemacs` but the ignored items still appear in the greyed out font immediately. So somehow treemacs seems to already know about the ignored files and directories for fontification but not for filtering?

**Comment by Alexander-Miller** [comment]
> I have set it to 5.0 before the initial M-x treemacs

Does that include a restart? Treemacs does a lot of caching for git, so once a file is known to be ignored that knowledge will stick around for a while.

At any rate the current setup will soon become obsolete anway. I've made some solid progress and the simple show-gitignored-files variables will be replaced by a full minor mode now. I'll try and have something ready for pushing tomorrow, so the whole problem should be gone by then.

**Comment by martenlienen** [comment]
Yes, I tested it immediately after a restart. I am looking forward to the new minor mode then!

**Comment by Alexander-Miller** [comment]
`treemacs-hide-gitignored-files-mode` is up now. A few minor use-cases, like adding a new project, are not covered yet. I'll handle when you confirm that the important parts are working correctly.

**Comment by martenlienen** [comment]
Works great, I can open directory nodes and the gitignored files such as `__pycache__` are never shown. Only when I switch to a workspace for the first time, the ignored files in the top-level project directories are still visible, probably because of the deferred git mode. You can also easily reproduce this

```sh
make test
cd test
git init
echo ignored >> .gitignore
touch ignored
# Now add a workspace with this project
```

**Comment by Alexander-Miller** [comment]
> Only when I switch to a workspace for the first time, the ignored files in the top-level project directories are still visible

Pushed a patch to cover those cases as well now. Let me know if I've missed anything.

**Comment by martenlienen** [comment]
I think there is a bug in [treemacs-async.el#L395](https://github.com/Alexander-Miller/treemacs/blob/e047826bb4f7293667b4d5d844580ad34250b185/src/elisp/treemacs-async.el#L395). `treemacs-do-switch-workspace` already calls it with a list of all project paths that belong to a workspace. This line then wraps that list in another list but I think it should just stay a list. I have been able to fix it by changing the `if` into `when` and just drop the else path.

Now everything works except for one special case that I encountered in one of my repositories. I have an ignored directory `.ipynb_checkpoints`. gitignored files are hidden, hidden (dot) files are visible. This makes it so that the ignored dot-directory is shown when it is empty, but disappears when I create a file in it. But that is barely an inconvenience. Thanks a lot for the new mode!

**Comment by Alexander-Miller** [comment]
> This line then wraps that list in another list but I think it should just stay a list.

Good catch, I've straightened that out now.

> This makes it so that the ignored dot-directory is shown when it is empty, but disappears when I create a file in it.

That one's a git limitation, it [doesn't care about empty directories at all](https://git.wiki.kernel.org/index.php/GitFaq#Can_I_add_empty_directories.3F).

At any rate it sounds like this feature is finished for now..
