### ISSUE TITLE
Files shown as links and directory node weird behaviour

### ISSUE THREAD

**Issue by qoops-1** [Alexander-Miller/treemacs#835]
This is a recurring problem for me, but I have no idea how it can be reproduced as it occurs randomly for me. It would be great, if you could give me any tips on what steps I could undertake to debug this. 
The problem:
A number of treemacs nodes gets displayed as links (see attached image). This is often accompanied with some single directory node exhibiting weird behaviour: when it is collapsed, file nodes contained in it don't hide, so expanding and collapsing the directory node multiple times displays the same file nodes in the project tree over and over again and clutters treemacs. Only `treemacs-kill-buffer` amends the issue.
<img width="285" alt="Nodes as links" src="https://user-images.githubusercontent.com/10588791/131258723-a00d70f0-982f-4cab-8d53-732fd43b1542.png">

**Comment by Alexander-Miller** [comment]
> A number of treemacs nodes gets displayed as links 

There's no special link display in treemacs, that green face must be something else. Probably git-related.

When you're in a broken state try these:

```Elisp
(defun treemacs-debug-node ()
  (interactive)
  (-let [btn (treemacs-current-button)]
    (message
     "\nLabel: %s\nPath: %s\nKey: %s\nParent: %s\nState: %s\nFace: %s\nCollapsed: %s\nSymlink: %s"
     (treemacs--get-label-of btn)
     (treemacs-button-get btn :path)
     (treemacs-button-get btn :key)
     (-some-> (treemacs-button-get btn :parent) (treemacs-button-get :path))
     (treemacs-button-get btn :state)
     (treemacs-button-get btn :face)
     (treemacs-button-get btn :collapsed)
     (treemacs-button-get btn :symlink))))
```
That'll print some general debug info that might contain hints as to whats broken.

```Elisp
(defun treemacs-mark-node ()
  (interactive)
  (-let [btn (treemacs-current-button)]
    (treemacs-with-writable-buffer
     (save-excursion
       (goto-char (treemacs-button-start btn))
       (insert "X")
       (goto-char (treemacs-button-end btn))
       (insert "Y")))))
```

That'll let us know if there's something wrong with the text markers. In a non-broken setup it'll surround the text (not the icon) at the current node with X and Y.

Also try this:

```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (treemacs-goto-node "/home/am/Documents/git/treemacs/src"))
```

Replace the path with the one to your broken node. Does point move to where it's supposed to go?

```Elisp
(with-current-buffer (treemacs-get-local-buffer)
  (treemacs-walk-dom (treemacs-find-in-dom "/home/am/Documents/git/treemacs")
    (lambda (node)
      (message "%s" (treemacs-dom-node->key node)))))
```

Here use the path to the root of your project. Does the output correspond to the files treemacs is displaying?

**Comment by qoops-1** [comment]
It's quite problematic for me to reproduce this as it always happens to me when I can't spend time to debug it. But here are some pieces of information that I managed to extract when the problem has happenned to me last time.
Running `treemacs-mark-node`:
<img width="272" alt="Снимок" src="https://user-images.githubusercontent.com/10588791/134048106-0bf677c1-2667-4bf5-b04b-faed6f1e08dd.png">

Running `treemacs-debug-node`:
<img width="490" alt="Снимок" src="https://user-images.githubusercontent.com/10588791/134048220-7ca60734-5713-4d14-9c9e-0804c0644117.png">

In addition I could not expand the directory node (error in the minibuffer):
<img width="997" alt="Снимок" src="https://user-images.githubusercontent.com/10588791/134049160-2a06bf6c-1bda-4055-ac5d-54489159e1e2.png">


Then stuff got really weird.
<img width="285" alt="Снимок" src="https://user-images.githubusercontent.com/10588791/134048680-5b80194b-8451-4179-8366-847600ac6c16.png">

> Replace the path with the one to your broken node. Does point move to where it's supposed to go?

Nope, it didn't, don't quite remember what happened though. I'll try to pay more attention when it happens next time.

**Comment by Alexander-Miller** [comment]
That error with the overlay looks familiar. Try the solution from this issue: https://github.com/emacs-lsp/lsp-mode/issues/2701

**Comment by qoops-1** [comment]
Well, that lsp-mode fix certainly didn't help me, but I think turning the lsp-mode links off is good enough for me now. Otherwise, I might report that bug to lsp-mode again. Thanks for your help!
