### ISSUE TITLE
treemacs-git-mode clashes with custom-set-minor-mode

### ISSUE THREAD

**Issue by haselwarter** [Alexander-Miller/treemacs#836]
When changing theme, `custom-set-minor-mode` gets activated. But instead of honouring the value of `treemacs-git-mode` (eg `deferred`), it calls with either 1 or 0, see below.
```
(defun custom-set-minor-mode (variable value)
  ":set function for minor mode variables.
Normally, this sets the default value of VARIABLE to nil if VALUE
is nil and to t otherwise,
but if `custom-local-buffer' is non-nil,
this sets the local binding in that buffer instead."
  (if custom-local-buffer
      (with-current-buffer custom-local-buffer
	(funcall variable (if value 1 0)))
    (funcall variable (if value 1 0))))
```
As a result, the user gets queried every time, even when the value of `treemacs-git-mode` is one of `(simple extended deferred)`.

Instead of relying on the argument to the minor mode, treemacs should just make the git mode a separate configuration variable.

**Comment by haselwarter** [comment]
Using this workaround for now, if anyone else hits this
```
    (setq my-treemacs-git-mode treemacs-git-mode)
    (defun my-treemacs-git-mode-advice (arg)
      (if (equal arg '(1)) (list my-treemacs-git-mode) arg))
    (advice-add 'treemacs-git-mode :filter-args
                'my-treemacs-git-mode-advice)
```

**Comment by Alexander-Miller** [comment]
> Instead of relying on the argument to the minor mode, treemacs should just make the git mode a separate configuration variable.

I'll save that as a last resort - git-mode is an old feature and I'll be annoying a lot of people if I change how it's used or configured. The current approach should still be workable if I just don't rely on the minor-mode variable.

I'll try and have a patch ready over the weekend.

**Comment by Alexander-Miller** [comment]
I've pushed a patch now. Let me know if it works.

**Comment by dabrady** [comment]
@Alexander-Miller I found your patch (https://github.com/Alexander-Miller/treemacs/commit/90088cee342fe3418b4b6435094e51ff78f37efc) but it does not work. I believe it is based on an incorrect premise: `custom-set-minor-mode` does not call `treemacs-git-mode` with `t`, but rather with either the number 1 or 0, as @haselwarter mentioned in his original issue description, as you can see from this debug backtrace generated when attempting to enable a theme:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/2475919/147616223-81440bf1-26d8-42aa-83f2-7c6072144f6d.png">

**Comment by Alexander-Miller** [comment]
Thanks for the heads up, I've fixed it in https://github.com/Alexander-Miller/treemacs/commit/d67f30aa8374c63fa4d60fd8bb3f677eb92b1502 now.
