### ISSUE TITLE
Project structure is lost upon restart, if folders with certain characters in the path are added

### ISSUE THREAD

**Issue by falcowinkler** [Alexander-Miller/treemacs#837]
### Bug impact
The user looses all added projects when re-starting emacs
### Steps to reproduce
- `mkdir ~/some\ \(folder\)/`
- Add this folder as a project
- restart emacs
### Actual behaviour
```
[Treemacs] Could not restore saved state, found error in line '** some (folder)':
Project name must be followed by path declaration
Broken state was saved to /Users/fawi/.emacs.d/.cache/treemacs-persist-at-last-error
```
### Expected behaviour 
Treemacs works as usual

### Environment
MacOs 11.5.1 (20G80)
Emacs 27.2
Treemacs 20210823.1524

<img width="593" alt="Screenshot 2021-08-30 at 08 38 30" src="https://user-images.githubusercontent.com/8613031/131296456-a7aa8112-f1c7-448d-aa2b-94c29e39f269.png">

**Comment by Alexander-Miller** [comment]
The regex responsible for recognizing the `- path :: ...` lines was too strict, so it got confused by the parens. I've made it more tolerant now.
