### ISSUE TITLE
Treemacs doesn't always get the extensions correct

### ISSUE THREAD

**Issue by sethen** [Alexander-Miller/treemacs#840]
I've noticed that treemacs doesn't always get the extensions correct when trying to change the icons.  For instance, treemacs will notice fine that I have a `.zshenv` but does not notice a `.zshrc` for whatever reason.  Here is the screenshot:

![Screenshot from 2021-09-11 12-48-23](https://user-images.githubusercontent.com/1493530/132955219-b1086731-1273-4ffc-81b0-6aec6eaaaf52.png)

And here is my code:

```elisp
  (treemacs-modify-theme "Default"
	:config
	(progn
	  (treemacs-create-icon
	   :icon (all-the-icons-faicon "cog" :v-adjust 0) :extensions ("conf"))
	  (treemacs-create-icon
	   :icon (all-the-icons-fileicon "emacs" :v-adjust 0) :extensions ("el"))
	  (treemacs-create-icon
	   :icon (all-the-icons-octicon "git-compare" :v-adjust 0) :extensions ("gitconfig"))
	  (treemacs-create-icon
	   :icon (all-the-icons-faicon "folder" :v-adjust 0) :extensions (dir-closed))
	  (treemacs-create-icon
	   :icon (all-the-icons-faicon "folder-open" :v-adjust 0) :extensions (dir-open))
	  (treemacs-create-icon
	   :icon (all-the-icons-octicon "file-code" :v-adjust 0) :extensions ("json" "yml" "yaml"))
	  (treemacs-create-icon
	   :icon (all-the-icons-octicon "file-text" :v-adjust 0) :extensions ("md"))
	  (treemacs-create-icon
	   :icon (all-the-icons-faicon "folder-open" :v-adjust 0) :extensions (root-closed))
	  (treemacs-create-icon
	   :icon (all-the-icons-faicon "folder" :v-adjust 0) :extensions (root-open))
	  (treemacs-create-icon
	   :icon (all-the-icons-faicon "html5" :v-adjust 0) :extensions ("html"))
	  (treemacs-create-icon
	   :icon (all-the-icons-octicon "terminal" :v-adjust 0) :fallback "" :extensions ("fish" "sh" "zsh"))
	  (treemacs-create-icon
	   :icon (all-the-icons-octicon "file-code" :v-adjust 0) :extensions (fallback))
```
Looking through the source code I would imagine that the `zsh` extension would pick this up.

Further, if the zsh doesn't match shouldn't it pick up the fallback?  I am not sure what's going on here.

**Comment by sethen** [comment]
Using the actual name of `.zshrc` works but it seems like I shouldn't have to do that

**Comment by bestlem** [comment]
The comment for treemacs-create-icon is the explanation

>  EXTENSIONS is a list of file extensions the icon should be used for.
  Note that treemacs has a loose understanding of what constitutes an extension:
  it's either the text past the last period or the entire filename, so names
  like \".gitignore\" and \"Makefile\" can be matched as well.

So treemacs looks at the text upto the end of line - not a regex for any characters.

**Comment by sethen** [comment]
> The comment for treemacs-create-icon is the explanation
> 
> > EXTENSIONS is a list of file extensions the icon should be used for.
> > Note that treemacs has a loose understanding of what constitutes an extension:
> > it's either the text past the last period or the entire filename, so names
> > like ".gitignore" and "Makefile" can be matched as well.
> 
> So treemacs looks at the text upto the end of line - not a regexp for any characters. You don't want to match zsh.c or even binding.zsh.c

That still doesn't explain why it would match one zsh file and not the other

**Comment by Alexander-Miller** [comment]
> That still doesn't explain why it would match one zsh file and not the other

It doesn't with the default icon settings on my end, so my guess would be it's something in your config, or some experimental leftover.

You can check with `treemacs-icon-catalogue` which themes and icons treemacs currently knows about.

**Comment by sethen** [comment]
> > That still doesn't explain why it would match one zsh file and not the other
> 
> It doesn't with the default icon settings on my end, so my guess would be it's something in your config, or some experimental leftover.
> 
> You can check with `treemacs-icon-catalogue` which themes and icons treemacs currently knows about.

What's funny is it is also not picking up "LICENSE" for whatever reason?  I just started using emacs so I don't have a complicated set up

**Comment by Alexander-Miller** [comment]
Too much information is better than too little. All the issues you describe cannot be reproduced on my end, and if you started with Emacs only recently you won't have too old a version of treemacs either (the LICENSE icon has been around since middle of 2019). You are also modifying the default theme, so all the defaults should be set and available.

There's only 2 remaining culprits: 

 - Some code that you ran, but didn't keep. That can be cleared with a restart.
 - Your config.

**Comment by sethen** [comment]
Thanks for your patience here.  I've provided my config below:

```elisp
(require 'use-package)

(defun treemacs-icon-spacing ()
  (progn
	(setq
	 treemacs-file-name-transformer (lambda (it) (concat " " it))
	 treemacs-directory-name-transformer (lambda (it) (concat " " it))
	 )))

(defun treemacs-theme ()
  (treemacs-modify-theme "Default"
	:config
	(progn
	  (treemacs-create-icon
	   :icon (propertize "" 'face 'alert-urgent-face) :extensions ("appimage" "dll" "sln"))
	  (treemacs-create-icon
	   :icon "\ue954" :extensions ("bat" "conf" "config"))
	  (treemacs-create-icon
	   :icon "\uea23" :extensions ("cs"))
	  (treemacs-create-icon
	   :icon "\uea1f" :extensions ("css" "scss" "sass"))
	  (treemacs-create-icon
	   :icon "\ue94b" :extensions (dir-closed root-closed))
	  (treemacs-create-icon
	   :icon "\uea18" :extensions (dir-open root-open))
	  (treemacs-create-icon
	   :icon "\uea1d" :extensions ("dockerfile" "docker-compose.yml"))
	  (treemacs-create-icon
	   :icon "\ue98c" :extensions ("el"))
	  (treemacs-create-icon
	   :icon "\ue9d0" :extensions ("fish" "sh" "zsh"))
	  (treemacs-create-icon
	   :icon "\ue959" :extensions ("git" "gitignore" "gitignore_global" "gitconfig"))
	  (treemacs-create-icon
	   :icon (propertize "\uea15" 'face 'alert-urgent-face) :extensions ("html"))
	  (treemacs-create-icon
	   :icon "\ue973" :extensions ("LICENSE"))
	  (treemacs-create-icon
	   :icon "\ue946" :extensions ("log"))
	  (treemacs-create-icon
	   :icon "\uea0c" :extensions ("LICENSE"))
	  (treemacs-create-icon
	   :icon "\uea0c" :extensions ("lua"))
	  (treemacs-create-icon
	   :icon "\uea0a" :extensions ("nginx.conf"))
	  (treemacs-create-icon
	   :icon "\uea08" :extensions ("package.json" "package-lock.json"))
	  (treemacs-create-icon
	   :icon "\uea06" :extensions ("php"))
	  (treemacs-create-icon
	   :icon "\uea17" :extensions ("go"))
	  (treemacs-create-icon
	   :icon "\uea11" :extensions ("js"))
	  (treemacs-create-icon
	   :icon "\uea10" :extensions ("json"))
	  (treemacs-create-icon
	   :icon "\ue980" :extensions ("md"))
	  (treemacs-create-icon
	   :icon "\uea09" :extensions ("node"))
	  (treemacs-create-icon
	   :icon "\ue9ff" :extensions ("rs"))
	  (treemacs-create-icon
	   :icon (propertize "\ue9ae" 'face 'alert-urgent-face) :extensions ("rb"))
	  (treemacs-create-icon
	   :icon "\ue9f5" :extensions ("ts"))
	  (treemacs-create-icon
	   :icon "\uea02" :extensions ("tsx"))
	  (treemacs-create-icon
	   :icon "\ue9e9" :extensions ("yml" "yaml"))
	  (treemacs-create-icon
	   :icon "\ue949" :extensions (".aliases" "ps1" ".zshenv" ".zshrc" "xml"))
	  (treemacs-create-icon
	   :icon "\ue94e" :extensions ("zip"))
	  (treemacs-create-icon
	   :icon "\ue969" :extensions ("bmp" "jpg" "png" "svg"))
	  (treemacs-create-icon
	   :icon "\ue9da" :extensions ("otf" "ttf" "woff"))
	  (treemacs-create-icon
	   :icon "\ue946" :extensions (fallback))
)))

(use-package treemacs
  :ensure t
  :config
  (treemacs-icon-spacing)
  (treemacs-theme))

(use-package treemacs-evil
  :after (treemacs evil)
  :ensure t)

(provide 'init-treemacs)
```
As you can see below the `LICENSE` doesn't get an icon when I am accounting for it in the config
![Screenshot from 2021-09-14 20-25-25](https://user-images.githubusercontent.com/1493530/133351148-2ae60835-cb55-4759-bba7-ce89e8beae56.png)

As you can see below the `editorconfig` doesn't get an icon when I feel back it should be caught by the fallback?
![Screenshot from 2021-09-14 20-23-11](https://user-images.githubusercontent.com/1493530/133350888-73b44d93-cc86-4d14-bd3d-0cf37e0d29bd.png)

**Comment by Alexander-Miller** [comment]
> As you can see below the LICENSE doesn't get an icon when I am accounting for it in the config

Treemacs expects the `:extensions` to be all downcased. That is fixed on my end now. I've also added the zshrc and zshenv icons.


(You have 2 entries for LICENSE btw)

> As you can see below the editorconfig doesn't get an icon when I feel like it should be caught by the fallback?

That's the default theme's png icon you are seeing, so that's working as intended.

**Comment by sethen** [comment]
> > As you can see below the LICENSE doesn't get an icon when I am accounting for it in the config
> 
> Treemacs expects the `:extensions` to be all downcased. That is fixed on my end now. I've also added the zshrc and zshenv icons.
> 
> (You have 2 entries for LICENSE btw)
> 
> > As you can see below the editorconfig doesn't get an icon when I feel like it should be caught by the fallback?
> 
> That's the default theme's png icon you are seeing, so that's working as intended.

Ah, yes!  Changing `LICENSE` to `license` fixed the issue for me.  Really appreciate it!!
