### ISSUE TITLE
Icon colors

### ISSUE THREAD

**Issue by sethen** [Alexander-Miller/treemacs#841]
I don't see anyway of actually adding colors to icons.  I am using a custom font with unicode characters and I absolutely love my icons but I would like a way to add color to them.  Currently they all come out white like so:![Screenshot from 2021-09-11 17-01-17](https://user-images.githubusercontent.com/1493530/132961511-5ab2cbe8-aa81-486e-8900-b5f6a7269af0.png)

Is there an easy way to add colors to them or is this something that isn't available?

**Comment by Alexander-Miller** [comment]
No special way to add faces is needed. When you are using icons from a font your icons are just strings and adding the face you want is as simple as using `propertize`.

Just create your icons like this

```Elisp
(treemacs-create-icon :icon (propertize "X " 'face 'alert-urgent-face) :extensions ("el"))
```

and they will look like this:

![icons](https://user-images.githubusercontent.com/5951157/133325470-5c94ec31-9c9c-4bb1-b480-8b901e44a42f.png)

**Comment by sethen** [comment]
Here is my code @Alexander-Miller -- I've replaced my unicode font in emacs to be a unicode font that I want that has all of my icons and such in it.  I am using unicode to make the icons like so:

```elisp
(require 'use-package)

(defun treemacs-icon-spacing ()
  (progn
	(setq
	 treemacs-file-name-transformer (lambda (it) (concat " " it))
	 treemacs-directory-name-transformer (lambda (it) (concat " " it))
	 )))

(defun treemacs-theme ()
  (treemacs-modify-theme "Default"
	:config
	(progn
	  (treemacs-create-icon
	   :icon "\ue948" :extensions ("appimage" "dll" "sln"))
	  (treemacs-create-icon
	   :icon "\ue954" :extensions ("bat" "conf" "config"))
	  (treemacs-create-icon
	   :icon "\uea23" :extensions ("cs"))
	  (treemacs-create-icon
	   :icon "\uea1f" :extensions ("css" "scss" "sass"))
	  (treemacs-create-icon
	   :icon "\ue94b" :extensions (dir-closed root-closed))
	  (treemacs-create-icon
	   :icon "\uea18" :extensions (dir-open root-open))
	  (treemacs-create-icon
	   :icon "\uea1d" :extensions ("dockerfile" "docker-compose.yml"))
	  (treemacs-create-icon
	   :icon "\ue98c" :extensions ("el"))
	  (treemacs-create-icon
	   :icon "\ue9d0" :extensions ("fish" "sh" "zsh"))
	  (treemacs-create-icon
	   :icon "\ue959" :extensions ("git" "gitignore" "gitignore_global" "gitconfig"))
	  (treemacs-create-icon
	   :icon "\uea15" :extensions ("html"))
	  (treemacs-create-icon
	   :icon "\ue973" :extensions ("LICENSE"))
	  (treemacs-create-icon
	   :icon "\ue946" :extensions ("log"))
	  (treemacs-create-icon
	   :icon "\uea0c" :extensions ("lua"))
	  (treemacs-create-icon
	   :icon "\uea0a" :extensions ("nginx.conf"))
	  (treemacs-create-icon
	   :icon "\uea08" :extensions ("package.json" "package-lock.json"))
	  (treemacs-create-icon
	   :icon "\uea06" :extensions ("php"))
	  (treemacs-create-icon
	   :icon "\uea17" :extensions ("go"))
	  (treemacs-create-icon
	   :icon "\uea11" :extensions ("js"))
	  (treemacs-create-icon
	   :icon "\uea10" :extensions ("json"))
	  (treemacs-create-icon
	   :icon "\ue980" :extensions ("md"))
	  (treemacs-create-icon
	   :icon "\uea09" :extensions ("node"))
	  (treemacs-create-icon
	   :icon "\ue9ff" :extensions ("rs"))
	  (treemacs-create-icon
	   :icon "\ue9ae" :extensions ("rb"))
	  (treemacs-create-icon
	   :icon "\ue9f5" :extensions ("ts"))
	  (treemacs-create-icon
	   :icon "\uea02" :extensions ("tsx"))
	  (treemacs-create-icon
	   :icon "\ue9e9" :extensions ("yml" "yaml"))
	  (treemacs-create-icon
	   :icon "\ue949" :extensions (".aliases" "ps1" ".zshenv" ".zshrc" "xml"))
	  (treemacs-create-icon
	   :icon "\ue94e" :extensions ("zip"))
	  (treemacs-create-icon
	   :icon "\ue969" :extensions ("bmp" "jpg" "png" "svg"))
	  (treemacs-create-icon
	   :icon "\ue9da" :extensions ("otf" "ttf" "woff"))
	  (treemacs-create-icon
	   :icon "\ue946" :extensions (fallback))
)))

(use-package treemacs
  :ensure t
  :config
  (treemacs-icon-spacing)
  (treemacs-theme))

(use-package treemacs-evil
  :after (treemacs evil)
  :ensure t)

(provide 'init-treemacs)
```

Do I still need to use `propertize` with this?  Is there a way to use a hex value instead of `'face`?  Sorry I am new to emacs.

**Comment by sethen** [comment]
I did try to `propertize` with the `'face` as you suggested and no luck still... is it because I am modifying the theme?

**Comment by Alexander-Miller** [comment]
> I did try to propertize with the 'face as you suggested and no luck still... is it because I am modifying the theme?

Did you use the same face I did? That's a bad example - I wanted an obvious face, and I took one from a package you don't have, so for you it does nothing.

> Do I still need to use propertize with this? Is there a way to use a hex value instead of 'face?

Yes and kinda yes.  Faces are more or less Emacs' version of CSS styles, so you cannot just use a hex value, but you can use a raw face value:

```Elisp
(propertize "X " 'face '((:foreground "green")))
```

or you create your own face and use that:

```Elisp
(defface red-icon '((t (:foreground "#FF3333"))) "")

(propertize "X " 'face 'red-icon)
```

> 	 treemacs-file-name-transformer (lambda (it) (concat " " it))

BTW, you should just add a space to your icons instead.

**Comment by sethen** [comment]
@Alexander-Miller Thank you so much for the guidance here!  Really appreciate it and I got it work 😎
