### ISSUE TITLE
Try to `text-scale-adjust` in `treemacs-mode-hook`

### ISSUE THREAD

**Issue by chansey97** [Alexander-Miller/treemacs#842]
Hi,

Thank you for this awesome package.

I'd like to scale the font sizes in treemacs window (just for font size, not icon). Following [this thread](https://github.com/Alexander-Miller/treemacs/issues/652), I added a hook for `treemacs-mode-hook` but it doesn' work.

```
(require 'treemacs)
(add-hook 'treemacs-mode-hook
          (lambda ()
            (message "treemacs-mode-hook `%s'" (current-buffer))
            (text-scale-adjust -1)
            ))
```

Log messages:
```
treemacs-mode-hook ‘ *Treemacs-Scoped-Buffer-#<frame ~/.emacs.d/init.el 0000000400a69a50>*’
```

Is there way to workaround this issue?

Thanks!

**Comment by Alexander-Miller** [comment]
No idea why `text-scale-adjust` does not work. I guess it's meant only for interactive use? 

`text-scale-increase` does the job however, so I've added a user option for it. Instead of the hook you can now simply set `treemacs-text-scale`.

**Comment by chansey97** [comment]
Thanks. I use `text-scale-increase`/`text-scale-decrease` instead, it works.

BTW, I read [the latest modification about treemacs-text-scale](https://github.com/Alexander-Miller/treemacs/commit/05b4969a18f70624b4af10ccbc0e51c39b1e456f), but I didn't see you invoked `text-scale-increase`/`text-scale-decrease`. Does the `treemacs-text-scale` feature currently can work in the master?

**Comment by Alexander-Miller** [comment]
That's what you get when you want to finish that commit before lunch.
The correct version of the patch is up now.

**Comment by chansey97** [comment]
Thanks!
