### ISSUE TITLE
Python3 Detection May Fail on Windows

### ISSUE THREAD

**Issue by brownts** [Alexander-Miller/treemacs#844]
If multiple Python installations exist on the machine and one of them happens to be a Cygwin installation using a [magic cookie](https://cygwin.com/cygwin-ug-net/using.html#pathnames-symlinks) symlink, Python3 detection may not succeed.  The reason for this is that the Cygwin installation may use a symbolic link to point at the specific version of Python within the Cygwin installation.  However, that symbolic link may be an old-style link, not a Windows native link. The old-style Cygwin symlinks are just files containing a magic cookie and the link target.

```
C:\>where python
C:\Cygwin\bin\python
C:\Programs\Python37-32\python.exe

C:\>type C:\Cygwin\bin\python
!<symlink>python2.7.exe
C:\>
```

Since the Windows `where` command may list multiple installation paths, it's possible (depending on which is found first in PATH) that the Cygwin version will be found first.  When `treemacs--find-python3` attempts to run the Cygwin path, to obtain the version information, it will fail due to not being able to run this file and `treemacs--find-python3` will report `nil` back to the caller (via the error handler of the `condition-case`), since it aborts searching once any error has occurred.  This prevents subsequent paths which may have been listed in the `where` output from being checked causing treemacs to report back that it couldn't find a Python3 installation when one may in fact have existed.

**Comment by brownts** [comment]
The above scenario is likely the root cause of what was described in #722.  I noticed in the output of that issue for the `where python` command, the Cygwin version of python was listed first.  Additionally, when a magic cookie symlink is attempted to be run, the output error message is:
```
'C:\\Cygwin\\bin\\python' is not recognized as an internal or external command, operable program or batch file.
```
This explains why the single quote was attempted to be interpreted as the version, as noted in that issue.

Furthermore, it appears the commit for that issue only masked the problem, and the author of that issue fixed their problem by changing their configuration to remove Cygwin from the set of Python versions resulting in `where python` no longer finding the Cygwin version.

**Comment by Alexander-Miller** [comment]
Thanks for the great description and the fix. I wish my other tickets were even half as detailed as that :+1:
