### ISSUE TITLE
shell extensions

### ISSUE THREAD

**Issue by bestlem** [Alexander-Miller/treemacs#847]
I note in commit https://github.com/Alexander-Miller/treemacs/commit/538c8ae1991473e87d978bdc8faf6e03962fce47 you added some zsh extensions.

For completeness I would suggest adding more e.g.

zprofile zlogin zlogout

and for bash

bash_profile bashrc  bash_login profile (this is for sh as well) bash (to correspond with zsh) bash_aliases (not directly called but I suspect common)

I am sure there will be similar for other shells.

I tried to do some of these with
```
(treemacs-modify-theme "Default"
  :config
  (progn
	(treemacs-create-icon :file "shell.png"         
          :extensions ("sh" "zsh" "zshrc" "zshenv" "zprofile" "bashrc" "bash" "bash_profile"))
	))
```

But that just gave me no icon at all for the new files exising ones e.g. zsh still worked

in treemacs-modify-theme does the file have to be a new file?

**Comment by Alexander-Miller** [comment]
> in treemacs-modify-theme does the file have to be a new file?

No it doesn't. A `:file` will be relative to the theme's icon directory, and you just used an icon from the default theme. I don't know why it didn't work for you, it worked fine on my end, so I guess it's something in the rest of your config.

At any rate I'll the new extensions in a bit.
