### ISSUE TITLE
Adding padding to the left of treemacs

### ISSUE THREAD

**Issue by sethen** [Alexander-Miller/treemacs#849]
Is there any way to add a padding to the left of treemacs at all?  I would like to push the entire directory a little bit over to center it a bit in this view.  Right now the root is left aligned on the fringe:

![Screenshot from 2021-09-21 18-12-32](https://user-images.githubusercontent.com/1493530/134254862-71b8587b-5e52-477c-a5ad-4158252d6480.png)

**Comment by Alexander-Miller** [comment]
You can't do that with treemacs, but you can control the width of a widow's fringe like this: `(set-window-fringes (selected-window) 25)`.

You would have to add this line both to `treemacs-mode-hook` and `treemacs-select-functions` to make sure the fringes stick.

**Comment by Alexander-Miller** [comment]
No, hooks are a collection of callbacks (the variable will be called `-functions` when the callbacks should accept arguments).

Adding the hooks would look like this:
(with a minor optimization so the fringe won't be changed unnecessarily when treemacs was already open)

```Elisp
(defun increase-left-fringe (&optional visibility)
  (unless (or (null visibility) (eq 'visible visibility))
    (set-window-fringes (selected-window) 25)))

(add-hook 'treemacs-mode-hook #'increase-left-fringe)
(add-hook 'treemacs-select-functions #'increase-left-fringe)
```

You can also add the following to just `treemacs-mode-hook` to make sure the fringe has the right color: `(face-remap-add-relative 'fringe :background "blue")`
