### ISSUE TITLE
neotree style preview of files without visiting buffer

### ISSUE THREAD

**Issue by anildigital** [Alexander-Miller/treemacs#85]
Neotree has this feature called preview files which is trigged by running 'spacebar' on the files in tree.

I tried to search similar feature in Treemacs.. but did not find it. Please let me know if there any such existing feature I can map to spacebar.

Or We need this feature desperately.

**Comment by Alexander-Miller** [comment]
If I understand neotree's quicklook right it opens a file, but keeps the neotree window selected. Treemacs can do this, too. Alll the file opening commands, those bound under o++ and RET, will behave just like that when called with a prefix argument (C-u).

Putting that directly on space would look like this:
 `(define-key treemacs-mode-map (kbd "SPC") (lambda () (interactive) (treemacs-visit-node-no-split t)))`

**Comment by anildigital** [comment]
Just tried it. Awesome! 👍🏼❤️!
