### ISSUE TITLE
Feature request: visually indicate where the end of the open directory is

### ISSUE THREAD

**Issue by Martinsos** [Alexander-Miller/treemacs#851]
Right now, when file tree is relatively complex, I find it hard to figure out where the end of the directory contents is.

How hard would it be to add an option to show a vertical line (or some other kind of visual indication, maybe alternating background color) extending from each open directory all the way to the last of its children?

So for example, right now for me treemacs looks like this:

![image](https://user-images.githubusercontent.com/1536647/134422086-f46e82a2-71d6-4e04-b266-decfd0095f50.png)

But with the feature I described above, it could look like this (I sketched two different visualization ideas, and I like the one to the right better, it is visually easier to follow):

![treemacs-suggestion](https://user-images.githubusercontent.com/1536647/134423538-6917a51d-d534-4fbd-b0d8-82d323f43a7a.png)

**Comment by Compro-Prasad** [comment]
The second one looks better. https://user-images.githubusercontent.com/1536647/134423538-6917a51d-d534-4fbd-b0d8-82d323f43a7a.png

**Comment by bestlem** [comment]
Looks like [highlight-indent-guides](https://github.com/DarthFennec/highlight-indent-guides) mode.

I did a quick attempt with treemacs and it produced the highlighting as suggested but removed the treemacs icons 

So some digging around would be needed,

**Comment by Alexander-Miller** [comment]
No need to dig. I am working on implementing both versions now.

**Comment by Martinsos** [comment]
> No need to dig. I am working on implementing both versions now.

Awesome, thanks! I agree with @Compro-Prasad that the second version looks better. Further addition could be to have the bars alternate in colors, similar to the idea used in https://www.emacswiki.org/emacs/RainbowDelimiters -> so instead of alternating between black and gray, bars could each have different color. But that might be a mess aesthetically, not sure hm. Plus pallete needs to be defined, and then there needs to be a way to make it work for different themes -> ok, that is just an idea, probably too complicated.

**Comment by Alexander-Miller** [comment]
indent-mode has now landed. Let me know if anything is broken or missing.

**Comment by Martinsos** [comment]
Awesome @Alexander-Miller , thanks for a quick turnaround!

**Comment by Compro-Prasad** [comment]
It somewhat works for the first picture and opens up more bugs. Maybe because my font doesn't work.

Fig: Indent guide with *line* enabled
![image](https://user-images.githubusercontent.com/11143962/135300927-7df84ce4-4cd7-4492-a219-c1928c22f593.png)

Fig: Indent guide with *block* enabled
![image](https://user-images.githubusercontent.com/11143962/135301127-eacca679-7242-452a-a065-7c76b3b714ec.png)

Fig: Indent guide disabled
![image](https://user-images.githubusercontent.com/11143962/135301344-307f8fa3-c86f-4065-ac9f-68b274105a5e.png)

**Comment by Alexander-Miller** [comment]
> It somewhat works but also opens up more bugs. Maybe because my font doesn't work.

My bad. I forgot a thing. The fix is up now.


> I am using spacemacs lately and I am not sure how to pull the latest version of treemacs into it 

You can just delete the package and spacemacs will re-install it for you. Another option is use-package with a `:load-path` argument pointing to a cloned repo.

**Comment by Compro-Prasad** [comment]
Yeah it works now.

**Comment by Martinsos** [comment]
Works here also, great, thanks a lot!
