### ISSUE TITLE
Feature request: copy-filepath-at-point

### ISSUE THREAD

**Issue by AnselmC** [Alexander-Miller/treemacs#853]
Hi,
treemacs (+evil) is great - thanks for this!

I have a small feature request:
When browsing a directory, it would be great to be able to copy the filepath at point into the clipboard.

My current solution is:
```elisp
(defun custom/treemacs-copy-filepath-at-point ()
  "Copies the filepath at-point to the clipboard."
  (interactive)
  (let* ((node (treemacs-node-at-point))
         (fpath (treemacs-button-get node :path)))
    (progn
      (kill-new fpath)
      (message (concat "Yanked " fpath " to clipboard")))))
```
and then I bind that to
```elisp
(use-package treemacs-evil
  :after (treemacs evil)
  :config (evil-define-key 'treemacs treemacs-mode-map (kbd "y y") #'custom/treemacs-copy-filepath-at-point))
```

I'm most likely missing some edge cases so any pointers appreciated.

**Comment by Alexander-Miller** [comment]
That's already available (the advanced helpful hydra would've shown the keybinds). You can use `ya`, `yr` and `yp` to copy the absolute, relative and project root paths at point.

**Comment by AnselmC** [comment]
Ah ok, sorry for not doing my research properly..
