### ISSUE TITLE
Ghost indent guides

### ISSUE THREAD

**Issue by sethen** [Alexander-Miller/treemacs#854]
For some reason I get these ghost indent guides that are just barely noticeable in treemacs.  I don't use indent guides in Emacs so I am curious what this could even be?  For some reason they are blue but they go away when I scroll past them.
![Screenshot from 2021-10-04 19-30-12](https://user-images.githubusercontent.com/1493530/135937987-70199a50-0793-439e-b962-57fbeac8aa08.png)

**Comment by Alexander-Miller** [comment]
Indentation in treemacs is based on 3 variables:

 - `treemacs-indentation`
 - `treemacs-indentation-string`
 - `treemacs--indentation-cache`

What are their values?

**Comment by sethen** [comment]
`treemacs-identation` is `2`
`treemacs-indentation-cache` is `" "`

I don't see `treemacs--indentation-cache` popping up for me with `M-x`... Is there somewhere else I need to look?

**Comment by Alexander-Miller** [comment]
My bad, it's called `treemacs--indentation-string-cache`.

The space before the icon is built by taking `treemacs-indentation-string` and repeating it `treemacs-identation` times for every level of identation.  These strings are cached, so by all rights you should not see any indent guides, especially not so inconsistently. I'm more inclined to believe this is some kind of display error.

Try this: set `treemacs-show-cursor` to t, kill and re-open treemacs, move the cursor on top the indent guide and call `describe-char`. That'll let us know whether Emacs really thinks that something is there.

**Comment by sethen** [comment]
```
             position: 1030 of 8210 (13%), column: 4
            character: SPC (displayed as SPC) (codepoint 32, #o40, #x20)
              charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x20
               script: latin
               syntax:   	which means: whitespace
             category: .:Base, a:ASCII, l:Latin
             to input: type "C-x 8 RET 20" or "C-x 8 RET SPACE"
          buffer code: #x20
            file code: #x20 (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    ftcrhb:-APPL-SFMono Nerd Font-normal-normal-normal-*-17-*-*-*-*-0-iso10646-1 (#x01)

Character code properties: customize what to show
  name: SPACE
  general-category: Zs (Separator, Space)
  decomposition: (32) (' ')

There are 2 overlays here:
 From 1026 to 1046
  face                 hl-line
  priority             -50
  window               nil
 From 1026 to 1046
  face                 hl-line
  priority             -50
  window               [Show]

[back]
```

I did what you described and this is what it gave me

**Comment by sethen** [comment]
Thanks a lot for your help here!
