### ISSUE TITLE
Very blurry image icons in Retina screen

### ISSUE THREAD

**Issue by memeplex** [Alexander-Miller/treemacs#861]
See for example:

![image](https://user-images.githubusercontent.com/2845433/136672034-f5601d4d-e4df-4da3-8c0b-13639f92812b.png)

Presumably they are rendered as for a 96 dpi screen and then scaled up x 2.

I'm using emacs-28 branch built from source with svg support. (frame-scale-factor) is correctly reported as 2. My laptop is a MacBook Pro 2017.

Also reported to lsp-mode in https://github.com/emacs-lsp/lsp-mode/issues/3143

**Comment by Alexander-Miller** [comment]
Most of treemacs' icons are 22x22 px sized pngs, so the blurriness is to be expected with such a scale factor.

Converting them to svgs has been on my nice-to-have list for a while now, but it'll take me a while.

**Comment by memeplex** [comment]
Thinking about it, I believe it would be better if this icon set were distributed as part of all-the-icons or other new "icon distro package" instead of duplicating and fragmenting it across many projects. Most icons have a clear meaning which will likely be enough to achieve consistency across projects without explicit coordination. This is similar to the situation with font icons right now except that they bring a host of alignment problems and that their semantics is not always clear (being a mishmash of icons not necessarily designed for programming environments) which doesn't favor consistency.

**Comment by Alexander-Miller** [comment]
Stayin alive!

**Comment by cfclrk** [comment]
Stay alive!

**Comment by Alexander-Miller** [comment]
> Stay alive!

Yes, but also fyi making stay-alive comments is no longer strictly necessary now. I've turned off the part of the bot where it closes tickets, it only acts as a reminder now.

**Comment by ryanprior** [comment]
Emacs on HiDPI screens has become totally commonplace, and svg support in Emacs has matured nicely. Could be a good time to revisit this 😸
