### ISSUE TITLE
Change width of treemacs on focus

### ISSUE THREAD

**Issue by sethen** [Alexander-Miller/treemacs#864]
Is it possible to expand the width of treemacs on focus?  For instance, if you have nested directories sometimes they can get cut off and you can't see them.  It would be cool if treemacs could expand its width to show everything to the right of the fold... or it could be cool if treemacs could just put into focus when you've currently opened so you can always see it.

**Comment by Alexander-Miller** [comment]
Not right now. There's 2 things I can think of adding:

- a toggle to make treemacs extra large and bring it back
- a command to make treemacs large or small enough to fit every single of its lines
