### ISSUE TITLE
treemacs-delete not working from treemacs menu

### ISSUE THREAD

**Issue by bestlem** [Alexander-Miller/treemacs#869]
When I choose delete from the treemacs menu under treemacs-20210929.2010 it works when I use the latest treemacs-20211019.1654 I get the error `funcall-interactively: Wrong type argument: listp, treemacs-delete`
But using the keyboard d deletes the file using treemacs-delete-file which works.

I note that there has been a change between the two versions that treemacs-delete ius now a defalias.

I suspect that the treemacs-rightclick-menu code needs updating to use the new function names.

**Comment by Alexander-Miller** [comment]
I updated the code to use the new names, things should work now.
