### ISSUE TITLE
Value for projectile-switch-project-action?

### ISSUE THREAD

**Issue by anildigital** [Alexander-Miller/treemacs#87]
Hi,

So neotree has something like `neotree-projectile-action` for projectile, is there any something similar for treemacs?

Thanks!

**Comment by Alexander-Miller** [comment]
Not automatically, no, but I can put it on my todo list.

**Comment by Alexander-Miller** [comment]
I've looked at what exactly the projectile action is for now, and that feature is already available as `treemacs-projectile`. It'll open treemacs either in the current project's root, or, if you call it with a prefix argument, you'll be able to first select the project you want.
