### ISSUE TITLE
[all-the-icons] The `all-the-icons` theme should not use its own adhoc list

### ISSUE THREAD

**Issue by jeslie0** [Alexander-Miller/treemacs#871]
Currently, the `all-the-icons` themes uses it's own list, found in "treemacs/src/extra/treemacs-all-the-icons.el". The theme contains a list of file extensions and the icon and properties to assign to it, for example

`(treemacs-create-icon :icon (format "  %s%s" (all-the-icons-fileicon "access" :v-adjust 0 :face 'all-the-icons-red) treemacs-all-the-icons-tab) :extensions ("accdb" "accdt" "accdt") :fallback 'same-as-icon)`

Instead of explicitly writing out the above such expression for every extension, we should instead use the list already provided by all-the-icon.el: `all-the-icons-extension-icon-alist`. This list contains lists of the following form:

`("sh" all-the-icons-alltheicon "terminal" :face all-the-icons-purple)`

The first term here is the file extension, with the remainder being the icon and face properties. 

I believe it should be possible to take such an expression and transform it into one required to make a treemacs icon. I have managed to make such a function, however when I try to map this function over `all-the-icons-extension-icon-alist`, all of the face properties end up being lost and becoming ellipses. 
The main issue seems to be that the treemacs expression requires the face property to be quoted, while it is not quoted in the all-the-icons list. I'm an elisp newbie, so maybe someone with more experience will be able to whip up the required function, or improve my code (I can post it here if people want to see it).

I am also working on a PR for all-the-icons.el to add the file extensions that we have in this theme. 

I believe using the list provided by all-the-icons.el will help improve the consistency of using this treemacs theme with other packages that reply on all-the-icons, and mean that adding icons to extensions will be done in the all-the-icons.el repository, not here.

**Comment by jeslie0** [comment]
I believe I have solved my problem here. I will do some more testing then put in a PR.

**Comment by Alexander-Miller** [comment]
The last time I looked it all-the-icons those lists weren't there, or at least they weren't as readily available. Use them as a base for the theme would be a good idea.

**Comment by jeslie0** [comment]
I have managed to make a theme based on the referenced list in all-the-icons. It was missing a lot of extensions that the treemacs theme uses. I am tidying it up and will put in a PR to all-the icons. 

It looks like there will be a lot of changes between this theme and the current treemacs one. I'm wondering if I should add the new theme separately, rather than overwrite the original? What do you think the best approach is?

**Comment by Alexander-Miller** [comment]
Splitting will just create 2 themes with the same icons that don't quite cover the same extensions. Your changes should go in the current theme, first the mappings based on all-the-icons, then fill the gaps with treemacs' own settings. That'll give us the coverage from all-the-icons, plus parity with the Default theme.
