### ISSUE TITLE
When open file use click on treemacs, new buffer keep open on the window next to treemacs.

### ISSUE THREAD

**Issue by zw963** [Alexander-Miller/treemacs#876]
Maybe a video is more easy to explain this issue.

https://user-images.githubusercontent.com/549126/141443044-aa53f133-9b51-4eb1-8e6a-78d4f9290d16.mp4

For above video,  when i click to open buffer, it should open new file use current active window.

Thank you

**Comment by Alexander-Miller** [comment]
The default behavior for double-click if to do the same thing as RET, which means displaying the file at point in the window chosen by `(next-window (selected-window) nil nil)`.

However double-click settings are thoroughly configurable, so you can tell treemacs to use the last active window like this:

```Elisp
(treemacs-define-doubleclick-action 'file-node-open #'treemacs-visit-node-in-most-recently-used-window)
(treemacs-define-doubleclick-action 'file-node-closed #'treemacs-visit-node-in-most-recently-used-window)
```

**Comment by zw963** [comment]
> However double-click settings are thoroughly configurable, so you can tell treemacs to use the last active window like this:

It works, so, why not use this as default?  from my point, open the buffer with the last active window is the meaningful default?

**Comment by Alexander-Miller** [comment]
IntelliJ also goes for the last used window, so that's good enough for me.

Oh and by the way: opening files by dragging them to a window works as well.

**Comment by zw963** [comment]
> Oh and by the way: opening files by dragging them to a window works as well.

Yes, i test it, it works! though, there no cursor animate show one file/folder is current dragging ...

**Comment by Alexander-Miller** [comment]
Emacs is not exactly the kind of program to expect fancy animations from.
