### ISSUE TITLE
Follow file and treemacs-perspective

### ISSUE THREAD

**Issue by LevPetrovitch** [Alexander-Miller/treemacs#877]
I installed perspective and added use of treemacs-perspective to my init file. When I switch from perspective A to perspective B and then
back to perspective A file following stops working. I get the following error

Error running timer ‘treemacs--follow’: (wrong-type-argument integer-or-marker-p nil)

Is this a bug or I'm doing something wrong?

**Comment by LevPetrovitch** [comment]
Note that the problem goes away (i.e. follow file starts working again) if I manually switch to the already selected treemacs workspace with C-c C-w s

**Comment by Alexander-Miller** [comment]
I player around with the latest versions of perspective-el and treemacs now, and haven't managed to reproduce the bug. Can you give me a step-by-step recipe?
