### ISSUE TITLE
Should respect auto mode alist for icons?

### ISSUE THREAD

**Issue by quicknir** [Alexander-Miller/treemacs#88]
For me, .h files show the C icon in treemacs, even though they open as C++ files. I think that treemacs should respect emacs in this. Can provide more details if needed.

**Comment by Alexander-Miller** [comment]
Yeah, I can add that. Do you know of any more ambiguous cases like .h?

**Comment by quicknir** [comment]
@Alexander-Miller Well, C++/C can be a bit of a mess. If you look at the default alist, there's all kinds of things that people can use in theory: .c, .cc, .h, .cxx, .hxx, hpp, .H, .C, etc etc. It's a bit nuts. Is treemacs using the emacs alist at all? Just curious how it works (and if it is using the emacs major mode alist, why it wouldn't have picked up .h as c++ automatically in my case).

**Comment by Alexander-Miller** [comment]
> Is treemacs using the emacs alist at all?

Nope, it's just one big hash table that maps file extensions to icons. With a quite loose definition of "file extension". It's either the part after the last period, or the entire filename if there are no periods. This way I can match file names like ".gitignore" and "Makefile". It's also case insensitive, so ".c" and ".C" are the same. 
All icons are defined in a big block in treemacs-visuals.el, around line 160.

**Comment by Alexander-Miller** [comment]
Does this spit out the correct results for you?

```
(let ((ambigious-extensions '(".c" ".cc" ".h" ".hpp" ".cxx" ".hxx")))
      (dolist (auto-mode-cons (nreverse auto-mode-alist))
        (-let [(ext-regex . mode) auto-mode-cons]
          (-when-let (ext (--first (s-matches? ext-regex it) ambigious-extensions))
            (pcase mode
              (`c-mode (message "C-mode for %s with regex %s" ext ext-regex))
              (`c++-mode (message "C++-mode for %s with regex %s" ext ext-regex))
              (other (message "Other mode %s for %s with regex %s" other ext ext-regex)))))))
```

**Comment by Alexander-Miller** [comment]
This issue still relevant to you?
I'm willing to make the change, but I require your feedback first.

**Comment by quicknir** [comment]
Sorry I dropped this! Will test it tonight.

**Comment by Alexander-Miller** [comment]
Great. 
Note that the code is traversing auto-mode-alist from the bottom up (I've honestly forgotten why I'm reverting the list here), so in the case of multiple statements for the same extension the one that comes last it the one that wins.

**Comment by quicknir** [comment]
Isn't this incorrect though? I thought it should be the one that comes first?

**Comment by quicknir** [comment]
Here is the output from running this in IELM:

```
C++-mode for .cc with regex \.\(cc\|hh\)\'
C++-mode for .hpp with regex \.[ch]\(pp\|xx\|\+\+\)\'
C++-mode for .c with regex \.\(CC?\|HH?\)\'
C-mode for .c with regex \.[ch]\'
C++-mode for .h with regex \.h\'
```
Which is correct :-).

**Comment by Alexander-Miller** [comment]
I now remember what this reversing is about. I did not want to traverse the very large auto-mode-alist more times than necessary. The idea I came up with allows to do everything in a single pass: just search the list from the bottom up, and whenever you find an entry for an ambiguous extension just remember that mapping, overwriting any previously found mappings. The last mapping encountered this way is then the first to be found by calling assoc on that alist.

In your case this means you'd see the c icon for .c files, and the c++ icon for .h files. The latter sounds just like what you asked for, so I'll move on to implementing the change.

**Comment by Alexander-Miller** [comment]
Just pushed https://github.com/Alexander-Miller/treemacs/commit/b1d77dcc269fc0324d14f1a8040f7a9699eb13e6.
Let me know if it's working as expected on your end.

**Comment by Alexander-Miller** [comment]
Bump?

**Comment by quicknir** [comment]
Sorry! Let me try this today, things have been a little crazy.

**Comment by quicknir** [comment]
So I installed treemacs 20171219, and it still seems to show the C icon for .h files. Does that release include that patch?

**Comment by Alexander-Miller** [comment]
I made the whole process manual, but very configurable. See [this part in the readme](https://github.com/Alexander-Miller/treemacs#icons-according-to-auto-mode-alist).

At the time I thought maybe there are other cases where it's not quite clear which icon to use, but now I'm not so sure. Assuming the current approach works for you I'll make it automatic.

**Comment by quicknir** [comment]
My bad! I grabbed the relevant part of the README, works perfectly! And in general, treemacs following and tags, and just all around, is looking so slick! You should be very proud, and thanks for your awesome contribution,
