### ISSUE TITLE
use within tramp mode is slow/stuck

### ISSUE THREAD

**Issue by futurist** [Alexander-Miller/treemacs#880]
When open a remote project tree from tramp mode, move cursor from one file to another constantly got stucked, and slow responding, is there any way to optimize this behavior? Like cache the remote tree etc.?

**Comment by Alexander-Miller** [comment]
I won't get into caching remote trees. Too much trouble for too little gain. Slow movement on the other hand should be fixable.  Does it get better when you set `treemacs-eldoc-display` to nil?
