### ISSUE TITLE
treemacs-follow-mode move file tree aggressively when work with wakatime-mode 

### ISSUE THREAD

**Issue by zw963** [Alexander-Miller/treemacs#886]
i don't how other emacser use this, but, after i enable it with ` (treemacs-follow-mode t)`, it a little aggressive to moving.

e.g.

i am current opened this package.json.

![image](https://user-images.githubusercontent.com/549126/148241326-1f0cfdeb-f5a9-4388-8a52-aa725d8d848e.png)

then, i moving treemacs window like this. (we assume i want click to open _image_loader.dart, i am searching that file, still not found it, so stil not click to open this new file).

![image](https://user-images.githubusercontent.com/549126/148242589-38521d78-195b-4c34-80bc-7d3c85899aee.png)

in this case, treemacs pull my treemacs window to scroll back to show package.json on treemacs, as the first screenshot.

The expected behavior:

before i click and open new file,  treemacs should not scrolling to pull my back to `package.json`, it should keep no scroll, as follow mode not be enabled.

follow mode should only take effect when i open a buffer use other tools, e.g. helm, find-file, in that case, treemacs window should follow current buffer opened file.

thank you.

**Comment by zw963** [comment]
The really wired things is, lsp-dart will enable treemacs-follow-mode automaticlly when dap-debug, that cause issue when i want to click another file which need scroll in my project which not visible on current treemacs view.

**Comment by zw963** [comment]
Maybe a video is more easy for describe this issue.

following is reproduce:

1. current, i opened the `README.md` in `magpie-mobie-app` project, my cursor is in README.md.
2. then i want to click one file on another project(which below the first one) .
3. so, i have to scroll use mouse in the treemacs window.

https://user-images.githubusercontent.com/549126/149467570-82ed3476-dc78-4a32-8964-308334171f65.mp4

when issue is, when i am scrolling, it always pull my back to make the `README.md` to the old position.

**Comment by Alexander-Miller** [comment]
That is not supposed to happen.

Follow-mode only activates when your selected window changes. In your scenario that means you'd have to be scrolling in treemacs while treemacs is selected and then simultaneously select your json window - with your mouse still busy in the treemacs window. An unlikely combination.

Does the issue go away if you disable follow-mode? Do you see `treemacs--follow` being used when you call `trace-function` on it? When the answers are yes try the following: `(advice-add #'treemacs--follow :before #'backtrace)`.

It's going to produce a lot of output. What I need is a backtrace that's produced when following is activated while you are scrolling, hopefully it will contain a hint about what's causing this.

**Comment by zw963** [comment]
> Does the issue go away if you disable follow-mode?

Yes.

> Follow-mode only activates when your selected window changes. In your scenario that means you'd have to be scrolling in treemacs while treemacs is selected and then simultaneously select your json window - with your mouse still busy in the treemacs window. An unlikely combination.

I am afraid my bad english not describe clear, let me make it simple.

* my cursor still within current opened buffer 1.(this is necessary for reproduce)
* my mouse point move to treemacs, and try to open view another view which not show as same treemacs window. (that is, scrolling more than one screen)
* before i click to the new file buffer in new scrolling screen, treemacs-follow-mode pull(scroll) me back to previous screen.

**Comment by zw963** [comment]
I find the reason cause this, when enable treemacs with [wakatime-mode](https://github.com/wakatime/wakatime-mode) will cause this issue.

i guess wakatime will keep do something timely which cause treemacs refresh aggressively.

Following is log

```
  backtrace()
  apply(backtrace nil)
  treemacs--follow()
  apply(treemacs--follow nil)
  timer-event-handler([t 0 0 200000 nil treemacs--follow nil idle 0 nil])
```

I will report a bug there too, and disable this mode temporary.

**Comment by zw963** [comment]
it should be a issue of wakatime mode
