### ISSUE TITLE
`treemacs-map-icons-with-auto-mode-alist` example produces error if used in `dotspacemacs/user-config`

### ISSUE THREAD

**Issue by xuhdev** [Alexander-Miller/treemacs#888]
In spacemacs:

1. Enable treemacs layer
2. Add the following to `dotspacemacs/user-config` (copied from README):
    ```elisp
      (treemacs-map-icons-with-auto-mode-alist
       '(".cc" ".hh")
       '((c-mode   . (treemacs-get-icon-value "c"))
         (c++-mode . (treemacs-get-icon-value "cpp"))))
    ```
3. Restart Emacs.

The following error message pops up:

    (Spacemacs) Error in dotspacemacs/user-config: Wrong type argument: symbolp, (treemacs-get-icon-value "cpp")

**Comment by Alexander-Miller** [comment]
Fixed. The setup needs to look like this now:

```Elisp
(treemacs-map-icons-with-auto-mode-alist
   '(".cc" ".hh")
   `((c-mode   . ,(treemacs-get-icon-value "c"))
     (c++-mode . ,(treemacs-get-icon-value "cpp"))))
```
