### ISSUE TITLE
How to show current workspace

### ISSUE THREAD

**Issue by Luctins** [Alexander-Miller/treemacs#890]
As the title said, How can I show the current workspace somewhere? (maybe in the mode line or on top of the workspace contents)

I can guess what the current workspace is by the content's, but it would be very useful to have this displayed somewhere.

example:
 
![image](https://user-images.githubusercontent.com/4743486/149387496-94972896-0b94-42a5-b691-cfa727c3c2e0.png)

I'm using `spacemacs 0.300.0 emacs 27.1`

**Comment by Alexander-Miller** [comment]
I wouldn't recommend using the mode- or header-line, they are too small for that kind of information. The best overview is provided by the command `treemacs-edit-workspaces`. It'll show you all your workspaces and their contents in a nice org-mode layout.

If you insist on using the header-line you can do something like this:

```Elisp
(add-hook
 'treemacs-mode-hook
 (defun xxxx ()
   (setq-local header-line-format
               (string-join (-map #'treemacs-workspace->name treemacs--workspaces) " » "))))
```

**Comment by Luctins** [comment]
> I wouldn't recommend using the mode- or header-line, they are too small for that kind of information.

I am aware of this, but the intent is just to be a quick visual indicator to show the current workspace name and most of my workspace names are not very long.

thanks for the help!
