### ISSUE TITLE
Rendering of project is messed up when new project is added or moved in sidebar

### ISSUE THREAD

**Issue by anildigital** [Alexander-Miller/treemacs#891]
Rendering of projects is not good 

when I use `treemacs-add-project-to-workspace`
![image](https://user-images.githubusercontent.com/266/149462241-a9f3df1d-21ce-46ec-bdb6-77a678ad3c26.png)

or when I do use `treemacs-move-project-up`
![image](https://user-images.githubusercontent.com/266/149462517-d3e03ad4-8149-4833-8e4f-bfee16fb720c.png)

**Comment by Alexander-Miller** [comment]
That's a followup bug from #883. I've pushed a patch to fix it now.

**Comment by anildigital** [comment]
@Alexander-Miller Issue still exists in `[Treemacs] v2.9.5 (installed 2022.01.18) @ Emacs 28.0.90` 

I just added a new project and folders are so close to each other

![image](https://user-images.githubusercontent.com/266/149872581-a2938f3d-805f-44cc-8310-190b56b1255f.png)
