### ISSUE TITLE
treemacs-delete-file on a file asks recursively delete parent folder instead of file

### ISSUE THREAD

**Issue by anildigital** [Alexander-Miller/treemacs#896]
`treemacs-delete-file` or pressing `d` on a file  on a file asks recursively delete parent folder instead of file

Similarly `treemacs-rename-file` or pressing `R` on a file is causing rename parent folder instead of current file

Because of this, deleted important changes I made for an hour. Needs immediate fix.

`[Treemacs] v2.9.5 (installed 2022.01.28) @ Emacs 28.0.90`

**Comment by Alexander-Miller** [comment]
Sorry about that :/ It should all be fixed now.
