### ISSUE TITLE
 (args-out-of-range "" -1)

### ISSUE THREAD

**Issue by aggronmagi** [Alexander-Miller/treemacs#897]
System: Windows 10 
64-bit operating system, x64-based processor 

GNU Emacs 27.2
Copyright (C) 2021 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

lsp-treemacs-20220102.1517/
treemacs-20220127.2125/
treemacs-icons-dired-20211229.1448/
treemacs-magit-20211010.1005/
treemacs-persp-20211229.1448/
treemacs-projectile-20211223.1454/

I found emacs has much errors of "error in process sentinel: Args out of range: "", -1"
And I found that emacs opens a lot of buffers named "Treemacs Update Single File Process".

When I run the command "toggle-debug-on-error", I get the following error message: 

Debugger entered--Lisp error: (args-out-of-range "" -1)
  #f(compiled-function (process status) #<bytecode 0x70b59f5>)(#<process Treemacs Update Single File Process> "exited abnormally with code 49\n")

**Comment by aggronmagi** [comment]
byte code:
  doc:   ...
  args: (arg1 arg2)
0		constant  process-live-p
1		stack-ref 2
2		call	  1
3		not		  
4		goto-if-nil-else-pop 41
7		constant  process-exit-status
8		stack-ref 2
9		call	  1
10		constant  0
11		eqlsign	  
12		goto-if-nil 28
15		constant  buffer-live-p
16		constant  #<buffer  *Treemacs-Scoped-Buffer-#<frame go-mode.el (c:/Users/Administrator/AppData/Roaming/.emacs.d/elpa/go-mode-20220114.2239/go-mode.el) 0000000011a052e0>*>
17		call	  1
18		goto-if-nil 40
21		save-current-buffer 
22		constant  #<buffer  *Treemacs-Scoped-Buffer-#<frame go-mode.el (c:/Users/Administrator/AppData/Roaming/.emacs.d/elpa/go-mode-20220114.2239/go-mode.el) 0000000011a052e0>*>
23		set-buffer 
24		discard	  
25		constant  nil
26		varbind	  buffer-read-only
27		constant  read
28		save-current-buffer 
29		constant  #<buffer Treemacs Update Single File Process<2>>
30		set-buffer 
31		discard	  
32		constant  buffer-string
33		call	  0
34		unbind	  1
35		call	  1
36		dup		  
37		stack-ref 1
38		cdr		  
39		stack-set 2
41		car-safe  
42		dup		  
43		stack-ref 1
44		cdr		  
45		stack-set 2
47		car-safe  
48		stack-ref 1
49		constant  #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ())
50		goto-if-nil 1
53		constant  puthash
54		stack-ref 2
55		stack-ref 2
56		constant  #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ())
57		call	  3
58		discard	  
59:1	constant  treemacs-find-visible-node
60		stack-ref 2
61		call	  1
62		dup		  
63		goto-if-nil 14
66		constant  file-directory-p
67		stack-ref 3
68		call	  1
69		goto-if-nil 2
72		constant  treemacs-directory-face
73		goto	  3
76:2	constant  treemacs-git-unmodified-face
77:3	stack-ref 2
78		constant  <jump-table-equal (M 4 U 5 ? 6 ! 7 A 8 R 9)>
79		switch	  
80		goto	  10
83:4	constant  treemacs-git-modified-face
84		goto	  11
87:5	constant  treemacs-git-conflict-face
88		goto	  11
91:6	constant  treemacs-git-untracked-face
92		goto	  11
95:7	constant  treemacs-git-ignored-face
96		goto	  11
99:8	constant  treemacs-git-added-face
100		goto	  11
103:9	constant  treemacs-git-renamed-face
104		goto	  11
107:10	dup		  
108:11	constant  put-text-property
109		constant  previous-single-property-change
110		stack-ref 4
111		add1	  
112		constant  button
113		call	  2
114		goto-if-not-nil-else-pop 12
117		point-min 
118:12	constant  next-single-property-change
119		stack-ref 5
120		constant  button
121		call	  2
122		goto-if-not-nil-else-pop 13
125		point-max 
126:13	constant  face
127		stack-ref 4
128		call	  4
129		discardN  3
131:14	discardN  4
133		dup		  
134:15	dup		  
135		goto-if-nil 27
138		dup		  
139		car		  
140		dup		  
141		car		  
142		stack-ref 1
143		cdr		  
144		dup		  
145		stack-ref 2
146		constant  treemacs-find-visible-node
147		stack-ref 1
148		call	  1
149		dup		  
150		goto-if-nil 26
153		stack-ref 2
154		constant  <jump-table-equal (M 16 U 17 ? 18 ! 19 A 20 R 21)>
155		switch	  
156		goto	  22
159:16	constant  treemacs-git-modified-face
160		goto	  23
163:17	constant  treemacs-git-conflict-face
164		goto	  23
167:18	constant  treemacs-git-untracked-face
168		goto	  23
171:19	constant  treemacs-git-ignored-face
172		goto	  23
175:20	constant  treemacs-git-added-face
176		goto	  23
179:21	constant  treemacs-git-renamed-face
180		goto	  23
183:22	constant  treemacs-directory-face
184:23	constant  put-text-property
185		constant  previous-single-property-change
186		stack-ref 3
187		add1	  
188		constant  button
189		call	  2
190		goto-if-not-nil-else-pop 24
193		point-min 
194:24	constant  next-single-property-change
195		stack-ref 4
196		constant  button
197		call	  2
198		goto-if-not-nil-else-pop 25
201		point-max 
202:25	constant  face
203		stack-ref 4
204		call	  4
205		discardN  2
207:26	discardN  5
209		stack-ref 1
210		cdr		  
211		discardN-preserve-tos 2
213		goto	  15
216:27	discardN  2
218		unbind	  2
219		goto	  40
222:28	constant  process-exit-status
223		stack-ref 2
224		call	  1
225		constant  eql
226		stack-ref 1
227		constant  2
228		call	  2
229		goto-if-not-nil 39
232		save-current-buffer 
233		constant  #<buffer Treemacs Update Single File Process<2>>
234		set-buffer 
235		discard	  
236		constant  buffer-string
237		call	  0
238		unbind	  1
239		dup		  
240		length	  
241		sub1	  
242		stack-ref 1
243		stack-ref 1
244		aref	  
245		constant  10
246		eqlsign	  
247		goto-if-nil 29
250		constant  substring
251		stack-ref 2
252		constant  0
253		stack-ref 3
254		call	  3
255		goto	  30
258:29	stack-ref 1
259:30	stack-set 1
261		stack-set 1
263		varref	  treemacs--saved-eldoc-display
264		consp	  
265		goto-if-not-nil 31
268		varref	  treemacs-eldoc-display
270		list1	  
271		varset	  treemacs--saved-eldoc-display
272:31	constant  nil
273		varset	  treemacs-eldoc-display
275		varref	  treemacs--no-messages
277		goto-if-not-nil 34
280		constant  message
281		constant  "%s %s"
282		constant  propertize
283		constant  "[Treemacs]"
284		constant  face
285		constant  ((:inherit error :weight bold))
286		call	  3
287		constant  format
288		constant  "Update of node \"%s\" failed with status \"%s\" and result"
289		constant  "c:/Users/Administrator/AppData/Roaming/.emacs.d/projectile-bookmarks.eld"
290		stack-ref 8
292		length	  
293		sub1	  
294		stack-ref 9
296		stack-ref 1
297		aref	  
298		constant  10
299		eqlsign	  
300		goto-if-nil 32
303		constant  substring
304		stack-ref 10
306		constant  0
307		stack-ref 3
308		call	  3
309		goto	  33
312:32	stack-ref 9
314:33	stack-set 1
316		call	  3
317		call	  3
318		discard	  
319:34	constant  add-hook
320		constant  pre-command-hook
321		constant  treemacs--restore-eldoc-after-log
322		call	  2
323		discard	  
324		varref	  treemacs--saved-eldoc-display
325		consp	  
326		goto-if-not-nil 35
329		varref	  treemacs-eldoc-display
331		list1	  
332		varset	  treemacs--saved-eldoc-display
333:35	constant  nil
334		varset	  treemacs-eldoc-display
336		varref	  treemacs--no-messages
338		goto-if-not-nil 38
341		constant  message
342		constant  "%s %s"
343		constant  propertize
344		constant  "[Treemacs]"
345		constant  face
346		constant  ((:inherit error :weight bold))
347		call	  3
348		constant  format
349		constant  "\"%s\""
350		stack-ref 5
351		length	  
352		sub1	  
353		stack-ref 6
355		stack-ref 1
356		aref	  
357		constant  10
358		eqlsign	  
359		goto-if-nil 36
362		constant  substring
363		stack-ref 7
365		constant  0
366		stack-ref 3
367		call	  3
368		goto	  37
371:36	stack-ref 6
373:37	stack-set 1
375		call	  2
376		call	  3
377		discard	  
378:38	constant  add-hook
379		constant  pre-command-hook
380		constant  treemacs--restore-eldoc-after-log
381		call	  2
382		discardN  2
384:39	discard	  
385:40	constant  kill-buffer
386		constant  process-get
387		stack-ref 3
388		constant  buffer
389		call	  2
390		call	  1
391:41	return

**Comment by Alexander-Miller** [comment]
>  And I found that emacs opens a lot of buffers named "Treemacs Update Single File Process".

Try updating pfuture. If that does not help add the following 2 log statements to your treemacs install and eval the function to apply them and tell me what the log says when the bug appears. It should be reproducible when you edit a file in a way that changes its git status - unmodified to modified and vice versa.

```Diff
modified   src/elisp/treemacs-async.el
@@ -312,6 +312,7 @@ OVERRIDE-STATUS: Boolean"
              (cmd `(,treemacs-python-executable
                     "-O"
                     ,treemacs--single-file-git-status.py ,file ,current-state ,@parents)))
+        (treemacs-log "Git update %s %s %s" file current-state parents)
         (pfuture-callback cmd
           :directory parent
           :name "Treemacs Update Single File Process"
@@ -320,6 +321,7 @@ OVERRIDE-STATUS: Boolean"
             (with-current-buffer local-buffer
               (treemacs-with-writable-buffer
                ;; first the file node with its own default face
+               (treemacs-log "Pfuture result %s" (pfuture-callback-output))
                (-let [output (read (pfuture-callback-output))]
                  (-let [(file . state) (pop output)]
```

Normally the output should look like this:
```
[Treemacs] Git update /home/am/Documents/git/treemacs/src/elisp/treemacs-bookmarks.el 0 (/home/am/Documents/git/treemacs/src/elisp /home/am/Documents/git/treemacs/src)
[Treemacs] Pfuture result (("/home/am/Documents/git/treemacs/src/elisp/treemacs-bookmarks.el" . "M")("/home/am/Documents/git/treemacs/src/elisp" . "M")("/home/am/Documents/git/treemacs/src" . "M"))
```

Btw byte code is not helpful for debugging, it's not supposed to be human-readable, and the real code is right there anyway. So I've hidden your 2nd comment to reduce the scrolling.

**Comment by aggronmagi** [comment]
Thank you for your help and reply, I encountered this problem on the company computer. I will modify the code and submit the error log information after the Spring Festival!
Sorry for the inconvenience caused by pasting the byte code before!

**Comment by aggronmagi** [comment]
I remove all elc files in treemacs-20220127.2125 and get this error tip.


Debugger entered--Lisp error: (args-out-of-range "" -1)
  aref("" -1)
  (= 10 (aref str len))
  (if (= 10 (aref str len)) (substring str 0 len) str)
  (let ((len (1- (length str)))) (if (= 10 (aref str len)) (substring str 0 len) str))
  (let* ((str (save-current-buffer (set-buffer pfuture-buffer) (buffer-string)))) (let ((len (1- (length str)))) (if (= 10 (aref str len)) (substring str 0 len) str)))
  (let* ((err-str (let* ((str (save-current-buffer (set-buffer pfuture-buffer) (buffer-string)))) (let ((len (1- (length str)))) (if (= 10 (aref str len)) (substring str 0 len) str))))) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display (list treemacs-eldoc-display))) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" 'face '((:inherit error :weight bold))) (format "Update of node \"%s\" failed with status \"%s\" and re..." file (let ((len ...)) (if (= 10 ...) (substring status 0 len) status))))) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log)) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display (list treemacs-eldoc-display))) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" 'face '((:inherit error :weight bold))) (format "\"%s\"" (let ((len (1- (length err-str)))) (if (= 10 (aref err-str len)) (substring err-str 0 len) err-str))))) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log)))
  (if (eql val 2) (progn (ignore "No Change, Do Nothing")) (let* ((err-str (let* ((str (save-current-buffer (set-buffer pfuture-buffer) (buffer-string)))) (let ((len (1- (length str)))) (if (= 10 (aref str len)) (substring str 0 len) str))))) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display (list treemacs-eldoc-display))) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" 'face '((:inherit error :weight bold))) (format "Update of node \"%s\" failed with status \"%s\" and result" file (let ((len (1- (length status)))) (if (= 10 (aref status len)) (substring status 0 len) status))))) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log)) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display (list treemacs-eldoc-display))) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" 'face '((:inherit error :weight bold))) (format "\"%s\"" (let ((len (1- (length err-str)))) (if (= 10 (aref err-str len)) (substring err-str 0 len) err-str))))) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log))))
  (let* ((val (process-exit-status process))) (if (eql val 2) (progn (ignore "No Change, Do Nothing")) (let* ((err-str (let* ((str (save-current-buffer (set-buffer pfuture-buffer) (buffer-string)))) (let ((len (1- (length str)))) (if ... ... str))))) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display (list treemacs-eldoc-display))) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" 'face '...) (format "Update of node \"%s\" failed with status \"%s\" and re..." file (let ... ...)))) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log)) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display (list treemacs-eldoc-display))) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" 'face '...) (format "\"%s\"" (let ... ...)))) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log)))))
  (if (= 0 (process-exit-status process)) (if (buffer-live-p local-buffer) (progn (save-current-buffer (set-buffer local-buffer) (let (buffer-read-only) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display ...)) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" ... ...)) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log)) (let* ((output ...)) (let* (... ... ...) (if git-cache ...) (let ... ...)) (let (...) (while --dolist-tail-- ...))))))) (let* ((val (process-exit-status process))) (if (eql val 2) (progn (ignore "No Change, Do Nothing")) (let* ((err-str (let* (...) (let ... ...)))) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display (list treemacs-eldoc-display))) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" ... ...) (format "Update of node \"%s\" failed with status \"%s\" and re..." file ...))) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log)) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display (list treemacs-eldoc-display))) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" (propertize "[Treemacs]" ... ...) (format "\"%s\"" ...))) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log))))))
  (if (process-live-p process) nil (if (= 0 (process-exit-status process)) (if (buffer-live-p local-buffer) (progn (save-current-buffer (set-buffer local-buffer) (let (buffer-read-only) (progn (if ... nil ...) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil ...) (add-hook ... ...)) (let* (...) (let* ... ... ...) (let ... ...)))))) (let* ((val (process-exit-status process))) (if (eql val 2) (progn (ignore "No Change, Do Nothing")) (let* ((err-str (let* ... ...))) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display ...)) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" ... ...)) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log)) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display ...)) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" ... ...)) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log)))))) (kill-buffer (process-get process 'buffer)))
  (closure ((pfuture-buffer . #<buffer Treemacs Update Single File Process<7>>) (name . "Treemacs Update Single File Process") (cmd "c:/Users/Administrator/AppData/Local/Microsoft/WindowsApps/python3.exe" "-O" "c:/Users/Administrator/AppData/Roaming/.emacs.d/elpa/treemacs-20220127.2125/treemacs-single-file-git-status.py" "d:/workspace/blueprint..." "0" "d:/workspace/blueprint..." "d:/workspace/blueprint..." "d:/workspace/blueprint..." "d:/workspace/blueprint...") (current-state . "0") (git-cache . #<hash-table equal 0/65 0x9983ac9>) (parents "d:/workspace/blueprint..." "d:/workspace/blueprint..." "d:/workspace/blueprint..." "d:/workspace/blueprint...") (parent-node . ...) (parent . "d:/workspace/blueprint...") (local-buffer . #<buffer  *Treemacs-Scoped-Buffer-#<frame  *Minibuf-1* () 0000000012106190>*>) (override-status) (exclude-parents) (file . "d:/workspace/blueprint_example/public/lua_project/server/common/template.lua") t) (process status) (ignore status) (if (process-live-p process) nil (if (= 0 (process-exit-status process)) (if (buffer-live-p local-buffer) (progn (save-current-buffer (set-buffer local-buffer) (let (buffer-read-only) (progn (if (consp treemacs--saved-eldoc-display) nil (setq treemacs--saved-eldoc-display ...)) (setq treemacs-eldoc-display nil) (if treemacs--no-messages nil (message "%s %s" ... ...)) (add-hook 'pre-command-hook #'treemacs--restore-eldoc-after-log)) (let* ((output ...)) (let* (... ... ...) (if git-cache ...) (let ... ...)) (let (...) (while --dolist-tail-- ...))))))) ...) (kill-buffer ...)))(#<process Treemacs Update Single File Process> "exited abnormally with code 49\n")

**Comment by aggronmagi** [comment]
Maybe this code triggers the error 

(treemacs--remove-trailing-newline "") 

I modify func treemacs--remove-trailing-newline 

(define-inline treemacs--remove-trailing-newline (str)
  "Remove final newline in STR."
  (declare (pure t) (side-effect-free t))
  (inline-letevals (str)
    (inline-quote
     (let ((len (1- (length ,str))))
       (cond
		((<= len 0) ,str)
		((= 10 (aref ,str len))  (substring ,str 0 len))
        (t ,str))))))

then I get this tip info:

[Treemacs] Git update c:/Users/Administrator/AppData/Roaming/.emacs.d/projectile-bookmarks.eld 0 nil
[Treemacs] Update of node "c:/Users/Administrator/AppData/Roaming/.emacs.d/projectile-bookmarks.eld" failed with status "exited abnormally with code 49" and result
[Treemacs] ""

**Comment by aggronmagi** [comment]
The default python on my computer is 3.10, and no error is reported after changing the default python to 2.7 (fixed by modifying the order of paths in the system environment variable). 
Thank you!

**Comment by Alexander-Miller** [comment]
Treemacs needs python 3 for its fancy git integration. Without it you get a slower and simpler elistp-based implementation.

It'd be more interesting to know what's going wrong in the python script. If you are up for it you can try it like this:

```
python .../treemacs/src/scripts/treemacs-single-file-git-status.py C:/Users/Administrator/AppData/Roaming/.emacs.d/projectile-bookmarks.eld NONE 
```
