### ISSUE TITLE
crfs-read can't show the complete file name when do treemacs-rename

### ISSUE THREAD

**Issue by zw963** [Alexander-Miller/treemacs#898]
In fact,  there are indeed some problem in `crfs-read`, e.g. as i do rename like following screenshot.

![image](https://user-images.githubusercontent.com/549126/151656539-37c42d55-d00e-43d7-93e8-1b41b90f2f47.png)

crfs was run, but because file name is two long, it only show the last character in file name (that is b)

When i pressing `C-a` to line beginning, i get the file name for now, but i can 't see last `b` char anymore, as following screenshot.

![image](https://user-images.githubusercontent.com/549126/151656622-89eedd29-7fad-4992-b360-f5a689d5cb95.png)

**Comment by Alexander-Miller** [comment]
I have pushed a patch to cfrs that checks the length of the initial input for the initial width and lets you control its size via `cfrs-min-wdith` and `cfrs-max-width`.

**Comment by zw963** [comment]
https://github.com/Alexander-Miller/treemacs/issues/872#issuecomment-1024881888

> I have pushed a patch to cfrs that checks the length of the initial input for the initial width and lets you control its size via `cfrs-min-wdith` and `cfrs-max-width`.

Thank you, it works, the the new default value work quite well than before.
