### ISSUE TITLE
When do rename use cfrs, after editing done then pressing RET, highlight and cursor on the wrong line.

### ISSUE THREAD

**Issue by zw963** [Alexander-Miller/treemacs#899]
1. click on file name, ready to do rename use cfrs, see following screenshot.

![image](https://user-images.githubusercontent.com/549126/151672124-8da0b5ff-2629-4a4e-a81c-694bc6927f54.png)

2. do rename, see following screenshot.

![image](https://user-images.githubusercontent.com/549126/151672210-fb7b399c-730e-401b-87c9-c0e423278a91.png)

3. after done, pressing RET to confirm rename operation.

4. highlight and cursor on the wrong line (below original one), see following screenshot.
![image](https://user-images.githubusercontent.com/549126/151672302-79a959ea-9300-4b6a-a8b9-bd547e5d17db.png)

**Comment by zw963** [comment]
keep

**Comment by Alexander-Miller** [comment]
I've no idea how this hasn't been noticed sooner. This bug is not about cfrs, but is a fundamental logic error - treemacs' own save-excursion implementation sees that file it was on no longer exists because it was renamed, so it falls back to one of its neighbours.

At any rate it's fixed now.
