### ISSUE TITLE
treemacs--select-workspace-by-name behaves differently if there is only one workspace

### ISSUE THREAD

**Issue by aaronjensen** [Alexander-Miller/treemacs#902]
https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-workspaces.el#L816-L817

When there is only one workspace and you pass a workspace name that does not exist, it will return the first workspace. This differs from when there is 2 or more. In that case, it will return `nil`.

Is that intentional? As far as I can tell it interferes with something like this behaving as expected:

https://github.com/Alexander-Miller/treemacs/blob/master/src/extra/treemacs-perspective.el#L90-L91

**Comment by Alexander-Miller** [comment]
Yeah, that's not quite right. I've pushed a patch to separate interactive and non-interactive selection now.

**Comment by aaronjensen** [comment]
Thanks, looks good. I can update #903 to use that
