### ISSUE TITLE
Make `delete-other-windows`(C-x 1) can ignore treemacs window.

### ISSUE THREAD

**Issue by zw963** [Alexander-Miller/treemacs#904]
Sorry, i am not sure if treemacs can have this feature, for my issue, i found `C-x 1` often not work when i try to close all others visible window if works with treemacs.

I guess `C-x 1` will try close treemacs window, but it failed, which cause this issue, so, i thought, if there is a way can skip close treemacs window whenever i run `delete-other-window`(C-x 1)?

thank you.

**Comment by Alexander-Miller** [comment]
There's `treemacs-delete-other-windows`. It's the same as `C-x 1`, but will ignore treemacs.

**Comment by zw963** [comment]
> There's `treemacs-delete-other-windows`. It's the same as `C-x 1`, but will ignore treemacs.

thank you, i propose after require treemacs, we should bind `C-x 1` to this new command instead to avoid issue.

**Comment by Alexander-Miller** [comment]
Oh no, touching the defaults is a big no-no. I'd much rather have this one ticket from you than the 20 complaints about treemacs breaking `C-x 1` I'd get otherwise.

Discoverability is always an issue, but to be fair: this command is both part of the [installation](https://github.com/Alexander-Miller/treemacs#installation) and the [list of global functions](https://github.com/Alexander-Miller/treemacs#unbound-functions).

**Comment by zw963** [comment]
Hi, @Alexander-Miller ,  `(treemacs-delete-other-windows)` still not work well when enable treemacs, it still could not close another window.

Please check for following backtrace

Debugger entered--Lisp error: (error "Specified root is not an ancestor of specified window")
  delete-other-windows-internal(#<window 40 on pry_hack.rb> #<window 24 on pryx>)
  delete-other-windows()
  treemacs-delete-other-windows()
  funcall-interactively(treemacs-delete-other-windows)
  #<subr command-execute>(treemacs-delete-other-windows nil nil nil)
  ad-Advice-command-execute(#<subr command-execute> treemacs-delete-other-windows)
  apply(ad-Advice-command-execute #<subr command-execute> treemacs-delete-other-windows)
  command-execute(treemacs-delete-other-windows)

thank you.

**Comment by Alexander-Miller** [comment]
All treemacs does is call the builtin window deletion and restore treemacs if it was open: https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-interface.el#L536

Does the normal `delete-other-winows` work in this situation?

**Comment by zw963** [comment]
> All treemacs does is call the builtin window deletion and restore treemacs if it was open: https://github.com/Alexander-Miller/treemacs/blob/master/src/elisp/treemacs-interface.el#L536
> 
> Does the normal `delete-other-winows` work in this situation?

It possible caused by shackle.el, following is my config for it.

https://github.com/zw963/.emacs.d/blob/master/plugins/shackle/shackle_init.el

**Comment by evelyndanel** [comment]
```
Debugger entered--Lisp error: (error "Specified root is not an ancestor of specified win...")
  delete-other-windows-internal(#<window 25 on *Messages*> #<window 9 on *scratch*>)
  delete-other-windows()
  treemacs-delete-other-windows()
  eval-expression((treemacs-delete-other-windows) nil nil 127)
  funcall-interactively(eval-expression (treemacs-delete-other-windows) nil nil 127)
  command-execute(eval-expression)
```

No `shackle.el` here.

**Comment by Alexander-Miller** [comment]
I've no idea what causes this bug. Unless you can give me an exact recipe to reproduce the error on my end there's nothing I can do.
