### ISSUE TITLE
where is [goto root] command

### ISSUE THREAD

**Issue by gintering1000** [Alexander-Miller/treemacs#905]
where is goto root command?
id like to make [specific path] root like that other editors can open directory.

**Comment by Alexander-Miller** [comment]
Not sure what you mean exactly. To move between projects root there is `treemacs-next/previous-project`.

**Comment by gintering1000** [comment]
i am now neotree user cuz of this function.

when i select project folder with projectile. treemac dont change root folder.

**Comment by Alexander-Miller** [comment]
Sorry for the late response, I missed your answer.

> i am now neotree user cuz of this function.

Neotree is unmaintained now. I have slowed down recently, but I am still working on treemacs. It's even an issue neotree had with eyebrowse that first drove me to create treemacs.

> treemacs-projectile : not work ( i cant get any project after i added projectile dir )

If you see no projects then `projectile-known-projects` is empty. My guess is a stale projectile cache.

> and [ treemacs-add-and-display-current-project ] is only open project directory without changing root

Treemacs is intended for multiple projects. This command adds another project the workspace. Show *only* the current project is done with `treemacs-display-current-project-exclusively`.
