### ISSUE TITLE
treemacs tab bar mode not built on package install

### ISSUE THREAD

**Issue by cmccloud** [Alexander-Miller/treemacs#907]
The recently merged pulled request integrating treemacs with tab-bar-mode doesn't seem to be building on installation from Melpa.

Haven't looked very much into treemacs bootstrap process but I didn't see any accompanying changes to the makefile with the PR.

**Comment by Alexander-Miller** [comment]
The makefile is only for local development and CI. The tab-bar is not part of baseline treemacs, it is an optional, and thus independent, package. That means you need to wait until the new recipe is added to melpa for your package manager to be able to pick it up: https://github.com/melpa/melpa/pull/7913

Or you can just grab the file and manually load it in your config. use-package has a handy `:load-path` argument for just that kind of thing.
