### ISSUE TITLE
The winum-assign-func variable is obsolete

### ISSUE THREAD

**Issue by duianto** [Alexander-Miller/treemacs#91]
The emacs-winum package made the `winum-assign-func` variable obsolete on oct 19:
https://github.com/deb0ch/emacs-winum/commit/bfef4ae6d0e0e5f1fb7e13e06298e4692e5b11a6#diff-44da362b85e63f9109555d7fdb343cbdR96

While investigating the Spacemacs issue that it caused:
[Neotree/Treemacs opens as window number 1 #9798](https://github.com/syl20bnr/spacemacs/issues/9798)

I noticed that Treemacs also uses that variable here:
https://github.com/Alexander-Miller/treemacs/blob/3d3beef827ebe0ab856c65e8705420a29aa7c23e/treemacs-compatibility.el#L35-L36

I got it to work in Spacemacs by following the new `winum-assign-functions` symbols doc-string:
https://github.com/deb0ch/emacs-winum/blob/c56d1cdb8d1723eb4c0d7a7eb3ecd2697739146c/winum.el#L99-L130

I then commented out the Spacemacs Treemacs layers window number assignment:
https://github.com/syl20bnr/spacemacs/blob/d15772fadcb86937522c49cb0819fd36ba5184b6/layers/%2Bfiletree/treemacs/packages.el#L74

and applied it to the Treemacs compatibility definition, like this:
```
  (when (boundp 'winum-assign-functions)
    (add-to-list 'winum-assign-functions #'treemacs--window-number-ten)))
```
I then renamed: `treemacs-compatibility.elc` to `_backup_treemacs-compatibility.elc`, so that the compiled version didn't load, and now it seems to be working. `SPC 0` selects the Treemacs window in Spacemacs.

**Comment by Alexander-Miller** [comment]
Good research, wish all my issues looked like that.

Fixed in https://github.com/Alexander-Miller/treemacs/commit/1461078f0d3fe791864f536c3742db6c2265a2e6.
