### ISSUE TITLE
Add icon for Hy language

### ISSUE THREAD

**Issue by ekaschalk** [Alexander-Miller/treemacs#92]
Hy is a lisp embedded in Python.

https://imgur.com/a/Pboyv contains the full size icon for reference and a 22x22 version.

**Comment by Alexander-Miller** [comment]
The small version's details are badly visible, as is the icon's color on a dark background. As a workaround I took the large version, removed the detail, leaving only the "hy" part in the middle, and brightened the blue somewhat. Looks reasonably nice in both bright and dark themes in my testing.

Any other file extensions I should add - maybe something like a .hyc extension for compiled hy files?

**Comment by ekaschalk** [comment]
That's awesome, thanks. There are no other extensions (it actually compiles to .pyc).

**Comment by Alexander-Miller** [comment]
Icon is included as of https://github.com/Alexander-Miller/treemacs/commit/3cabb43905750998557284cb112e5b029556ac26
Just need to wait for melpa now.
