### ISSUE TITLE
Seems like `hl-line` is no longer a face in current Emacs `master`, breaking treemacs code

### ISSUE THREAD

**Issue by WJCFerguson** [Alexander-Miller/treemacs#928]
Reference to face `hl-line` failes in `treemacs-icons.el` on Emacs built from master, because it references the face `hl-line`, that I think has been renamed `hl-line-face`.

I may have misunderstood something, but that's how it looks to me.  Looks like I hit this right away - the commit 0a094fb65ca1392231ef8176f89f936e39f3296e from 1 day ago has a rewrite of `hl-line`.

**Comment by jsigman** [comment]
I see the same thing

**Comment by WJCFerguson** [comment]
I'm currently successfully working around with the temporary hack of changing `'hl-line` to `'hl-line-face` in `treemacs-icons.el`.  But obviously treemacs will need a more sophisticated fix to handle both, or avoid referencing `hl-line` at all.

**Comment by jsigman** [comment]
I'm also having success with `(define-obsolete-face-alias 'hl-line 'hl-line-face "28.x")` before loading lsp/treemacs

**Comment by WJCFerguson** [comment]
That's a much less hacky hack.  That should perhaps be in Emacs master itself(?).

**Comment by TheJJ** [comment]
The original face name was restored in emacs-mirror/emacs@f36d929ee768f03dcc63f59ff0572c2681c8f749

**Comment by Alexander-Miller** [comment]
> The original face name was restored in https://github.com/emacs-mirror/emacs/commit/f36d929ee768f03dcc63f59ff0572c2681c8f749

Does that mean we no longer need a workaround for treemacs when using the latest master?

**Comment by TheJJ** [comment]
Yes, I think this can just be closed :) It was broken for a very short period, and we were lucky

**Comment by Alexander-Miller** [comment]
:+1:
