### ISSUE TITLE
Treemacs should not open files in bottom window

### ISSUE THREAD

**Issue by anildigital** [Alexander-Miller/treemacs#93]
Please see attached gif.

![](http://g.recordit.co/6KxXHg04ti.gif)

When treemacs window is fully open and I select a file and hit enter. it opens the file in bottom window. 

Expected behaviour should be default treemacs behaviour, the file should open on right side.. with Treemacs width properly set.

**Comment by Alexander-Miller** [comment]
Why is treemacs shown in fullscreen? I go out of my way to prevent that from happening, so unless you do it manually something's going wrong somewhere.

As for a fix, does it work as expected after you eval this code:

```
(defun treemacs-visit-node-no-split (&optional arg)
  "Open current file or tag within `next-window'.
Stay in current window with a prefix argument ARG."
  (interactive "P")
  (when (one-window-p)
    (save-selected-window
      (split-window nil nil (if (eq 'left treemacs-position) 'right 'left))))
  (treemacs--execute-button-action
   :file-action (find-file (treemacs--safe-button-get btn 'abs-path))
   :dir-action (dired (treemacs--safe-button-get btn 'abs-path))
   :tag-action (treemacs--goto-tag btn)
   :save-window arg
   :no-match-explanation "Node is neither a file, a directory or a tag - nothing to do here."))
```

**Comment by anildigital** [comment]
@Alexander-Miller ah! It's not full screen. It's normal, with menu-bar off.

 I can confirm that above function works fine when I eval it.

FYI

![](http://g.recordit.co/9aDeFsq1jL.gif)

Thank you. hopefully, I see it as part of treemacs soon

**Comment by Alexander-Miller** [comment]
I don't mean emacs being in fullscreen, I mean treemacs being the only open buffer. That shouldn't happen, treemacs is supposed to sit on the side, not use the entire screen.

**Comment by anildigital** [comment]
Sometimes I close the other window accidentally by C-x 0 and that way treemacs become fullscreen.

**Comment by Alexander-Miller** [comment]
Ah, good, that doesn't need fixing.

Patch is pushed. Let me know if it works.

**Comment by Alexander-Miller** [comment]
I assume everything's going well here, so I'll close this.

**Comment by anildigital** [comment]
Yep. Thanks.
