### ISSUE TITLE
I can't move the treemacs to right side

### ISSUE THREAD

**Issue by emadbaqeri** [Alexander-Miller/treemacs#930]
Hey folks, I'm trying to move the `treemacs` window to the right side but it's not working.
```emacs-lisp
(use-package treemacs
  :config
  treemacs-position 'right)
```
any ideas would be appreciated :)

**Comment by Alexander-Miller** [comment]
Unless there is some new use-package syntax I haven't yet heard about the `:config` part must be proper code. Try `(setf treemacs-position 'right)`.

**Comment by emadbaqeri** [comment]
Thanks to @Alexander-Miller, this issue has been solved and I'm going to close this one.
