### ISSUE TITLE
How can I close treemacs buffer upon opening a file?

### ISSUE THREAD

**Issue by npalladino100** [Alexander-Miller/treemacs#932]
How can I close the treemacs buffer automatically after opening a file?

**Comment by Alexander-Miller** [comment]
Use `treemacs-visit-node-close-treemacs`. By default it's bound to `oc`.

**Comment by npalladino100** [comment]
Ok I can use `treemacs-visit-node-close-treemacs`, and `treemacs-visit-node-in-most-recently-used-window`, but how can I use both together?  Thanks
