### ISSUE TITLE
Change icons

### ISSUE THREAD

**Issue by qkweint** [Alexander-Miller/treemacs#937]
How can I change my icons to look more like the gifs in this page :
![image](https://user-images.githubusercontent.com/69873602/166112603-d3e29f6f-9b02-42fe-8bb5-1233b16bc1b3.png)

Rather than the icons I currently have.
![image](https://user-images.githubusercontent.com/69873602/166112614-2acedfe5-8b58-4cc2-beed-87afe89d5f9c.png)

**Comment by Alexander-Miller** [comment]
Those are the old arc-theme icons I used before switching to the current set from vscode-icons. You can get them here:

![root](https://user-images.githubusercontent.com/5951157/166142998-cfe2cc70-e33b-4ab2-ae2a-03de73e0bc17.png) ![dir_closed](https://user-images.githubusercontent.com/5951157/166143011-cde1a3a9-d292-4468-ad1a-a856680362ad.png) ![dir_open](https://user-images.githubusercontent.com/5951157/166143006-9a0c9dfd-e08a-4975-a48d-de4b1b2598d2.png)

Download them and add this to your treemacs config:

```Elisp
(treemacs-create-icon :file "/path/to/root.png" :fallback "X " :extensions (root-open root-closed))
(treemacs-create-icon :file "/path/to/dir_open.png" :fallback "X " :extensions (dir-open))
(treemacs-create-icon :file "/path/to/dir_closed.png" :fallback "X " :extensions (dir-closed))
```
