### ISSUE TITLE
Behavior of treemacs-copy-file

### ISSUE THREAD

**Issue by deb75** [Alexander-Miller/treemacs#940]
Hello,

With latest `treemacs`, I noticed that when I hit `y f` (`treemacs-copy-file`), the new path given is used to
create a new directory in which the file is copied with same name, I was expecting the new path to be used
directly as the name for copied file.

This happens at least on windows 11.

Is there any reasons for this ? Is it possible to make `treemacs` use the given new path as a file name ?
instead of directory name ?

Regards

**Comment by deb75** [comment]
It still happens, any thoughts ?

**Comment by Alexander-Miller** [comment]
Sounds like like the same request as in #967. Try again with the latest version, it should work now.
