### ISSUE TITLE
treemacs-git-mode no longer correctly updates files' git status on refresh

### ISSUE THREAD

**Issue by petergardfjall** [Alexander-Miller/treemacs#944]
I have found that treemacs some time recently stopped properly updating/displaying files' git status on refresh. It seems like it no longer correctly picks up git changes made outside of Emacs.

The current `master` `HEAD` (68fd2ddab926e2a9e3948e64803abfd02d8c40cd) does _not_ work.

The last version I've confirmed to be _working_ is 82ec575b759e68256b359edd8c491bf35f6a4751.

I'll give a quick idea of how to reproduce this in the snippet below:

```bash
# Create a clean git project
mkdir sample ; cd sample
git init 
echo "# About" > README.md
git add README.md && git commit -m "added README"

# Open up the file in emacs and run `M-x treemacs`
emacs README.md &
## edit README.md and refresh treemacs => file correctly displays as modified 

# Commit changes on command-line
git add README.md && git commit -m "updated README"

# Inside emacs: refresh treemacs => file STILL (incorrectly) displays as modified
```

**Comment by Alexander-Miller** [comment]
Bug confirmed, I'm looking into it.

**Comment by GuessWhatBBQ** [comment]
Might be unrelated for me files are still marked as modified even after I've successfully committed changes using magit. I believe I've been observing similar buggy behavior in several use cases but I haven't noted them down unfortunately, except for the one mentioned before which was the most obvious. I can usually manage to fix it by running random git functions using magit such as rebase/merge that forces the treemacs buffer to update and then aborting the rebase/merge which finally shows the true state of files. Maybe it's related to the hooks treemacs is using ?

**Comment by petergardfjall** [comment]
Thanks for the quick response! I tried out faa2d10b894df9df0b6789047ea7ae05434d3030 and it does indeed seem to fix the issue. Nicely done!

I can close this issue, but I'll just take the opportunity to ask if this new API you speak of may have consequences for _automatic_ (git) update highlighting. Things work now when I explicitly do a refresh of the Treemacs buffer, but it seems like my `(treemacs-git-mode 'deferred)` and `(setq treemacs-deferred-git-apply-delay 0.5)` no longer achive this tree refresh automatically. Should I open another issue for that?

**Comment by petergardfjall** [comment]
Okay I _seem_ to have found it. As strange as it may sound, if I comment out the following line from my Treemacs config, it works(!):
```
(treemacs-hide-gitignored-files-mode nil)
```
(This minor-mode appears to be off by default anyway so the above line seems redundant. Still odd that it seems to prevent automatic git updates from displaying properly though!)

**Comment by Alexander-Miller** [comment]
I can reproduce this one as well. Now let's see what this is all about.

**Comment by Alexander-Miller** [comment]
Fun fact: using `nil` as an argument will enable a mode. It's the same as using no argument at all, in which case it'll work as a toggle. Not my fault that's what `define-minor-mode` does. You need `-1` to turn things off.

I've also discovered a bug caused by a change in the way treemacs' git cache works. That might fix your issue. If not I'll have to keep looking.

**Comment by petergardfjall** [comment]
Looks like one of the recent commits on `master` has broken [this](https://github.com/Alexander-Miller/treemacs/issues/944#issue-1253394666) again (the snippet results in the same lack of tree update).

**Comment by Alexander-Miller** [comment]
All right, the next version is up. I should've covered all the edge cases now.

**Comment by petergardfjall** [comment]
I can confirm that e80c3020270720ff114f7a2ad62c85e1fb627678 fixes the original issue in this ticket.

The _automatic_ face update on git status changes (as described [here](https://github.com/Alexander-Miller/treemacs/issues/944#issuecomment-1144010126)) still does not seem to work though. But that's much less of a problem.

**Comment by petergardfjall** [comment]
I can reproduce the issue using the same procedure as [here](https://github.com/Alexander-Miller/treemacs/issues/944#issue-1253394666). I need to expressly trigger a treemacs refresh (pressing `g` when in the treemacs window) to see the file return to "unmodified" state after doing the `git commit` on the command-line. Earlier versions of treemacs have auto-refreshed to achieve that effect by itself.

My `treemacs` config is as follows:

```elisp
(use-package treemacs
  :straight t
  :defer t
  :bind (:map treemacs-mode-map
	      ;; disable treemacs workspace keymap (C-c C-w ..), since it
	      ;; conflicts with hydra-windows
	      ("C-c C-w" . nil))
  :config
  (setq treemacs-collapse-dirs                   3
        treemacs-deferred-git-apply-delay        0.5
	treemacs-file-follow-delay               0.2
	treemacs-hide-dot-git-directory          t
	treemacs-indentation                     2
	treemacs-indentation-string              " "
	treemacs-missing-project-action          'ask
	;; Use textual icons.
	treemacs-no-png-images                   t
	;; If true: keep only current project expanded and all others closed.
        treemacs-project-follow-cleanup nil
	;; Path where workspace state (added projects) is saved. A separate
        ;; treemacs state file is kept for each location where emacs is opened
        ;; (assumed to be project root most of the time):
        ;; ~/.emacs.d/treemacs-persist/<working-dir>
        treemacs-persist-file                    (concat user-emacs-directory "treemacs" (getenv "PWD") "/treemacs-persist")
	treemacs-litter-directories              '("/node_modules" "/.venv" "/.cask")
	treemacs-show-hidden-files               t)
  ;; Default width/height of icons is 22 pixels. If on a Hi-DPI display,
  ;; uncomment to double the icon size.
  ;; (treemacs-resize-icons 44)
  (treemacs-follow-mode t)
  (treemacs-filewatch-mode t)
  (treemacs-fringe-indicator-mode 'always)
  (treemacs-git-mode 'deferred)
  :bind
  (:map global-map
        ;; hide/show treemacs file explorer
        ("<f8>" . my-toggle-treemacs)))
```

**Comment by Alexander-Miller** [comment]
> Earlier versions of treemacs have auto-refreshed to achieve that effect by itself.

I don't think that's right. Treemacs has never supported *commit* changes that happened from the command line. But it used to be a lot less smart about its updates and would refresh entire directories and projects because of a single file. Maybe that's what you saw?

The way things work is that all of its auto-update feature rely on watching the file system for changes. That means all it knows about it files getting created, deleted and modified. Git interactions like committing or staging do none of these things, so treemacs cannot know when they happen. This is the reason the treemacs-magit package exists - with magit I have a elisp interface I can hook into whenever such an event takes place.

To make what you say happen I'd probably have to listen to some internals in the .git directory. That'd be nice to have, but not the kind of niche thing I want to get into with the limited time that I have.

**Comment by petergardfjall** [comment]
That makes a lot of sense. As you say, I must have been fooled by the old, more coarse-grained, way of doing things. 
Sorry about the confusion. I'll close this issue as everything is then working as intended. Thanks a lot for your efforts and a very cool package!
