### ISSUE TITLE
can't use treemacs icons in dired if using dired-filter

### ISSUE THREAD

**Issue by algon-ns** [Alexander-Miller/treemacs#947]
the icon does not show up, until I do a "revert-buffer" command in the dired window
taking dired-filter away, it work as it should, and I cant figure out which filer it is.

**Comment by Alexander-Miller** [comment]
What filter are we talking about here? Closest thing I found is `find-lisp-find-dired-filter` and that didn't seem to do anything.

**Comment by algon-ns** [comment]
It is this
https://github.com/melpa/melpa/blob/master/recipes/dired-hacks-utils

Sendt fra min iPad

**Comment by algon-ns** [comment]
Hello

I figured out that the problem is:
				  (use-package dired-filter
							:hook (dired-mode . (lambda () (dired-filter-group-mode))))
  ;;										(dired-filter-by-garbage)))) <———————————it works OK without this
				  (setq dired-garbage-files-regexp
					  "\\(?:\\.\\(?:aux\\|bak\\|dvi\\|orig\\|rej\\|toc\\|out\\)\\)\\’”)

which is probably one of the fields in the regex, which takeout the icon ads garbage, but I can’t figure out which one….

mvh
Niels


 <applewebdata://C16E7CD6-4255-4C8F-B153-72F32E4AA789>
Niels Søndergaard owner
Algon IT
Mariehøj 236, 2990 Nivå
 <tel:+45%204052%202789>+45 4052 2789 algon.dk <https://algon.dk/> ***@***.*** ***@***.***>
 <https://www.linkedin.com/in/nielssoendergaard/>

**Comment by Alexander-Miller** [comment]
I had to dig deep for this one, and while I've found a solution it's not as clean as I would have liked. Long story short dired-filter calls `revert-buffer` in a very inconvenient spot and pulling things apart is a lot more complicated than one might think, so the simple solution is to make sure that dired-filter goes last with a zero-delay timer:

`(add-hook 'dired-mode-hook (lambda () (run-with-timer 0 nil #'dired-filter-by-garbage)))`
