### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by deb75** [Alexander-Miller/treemacs#951]
Hi,

On windows 11, when using `treemacs` for a while, I usually run into the error "Too many open files".

After this, I can do nothing with `treemacs`.

I guess that when I move, copy files and directory from `treemacs`, this one creates a process with some
file descriptors, which are not closed when the process ends.

Do you know if it is possible to ensure that all file descriptors are closed ?

Regards

**Comment by Alexander-Miller** [comment]
Treemacs only spawns new file descriptors for filewatch-mode, however it only watches the directories you expand, not individual files. It also stops watching the directory, dropping its file descriptor, the moment you close it in treemacs. So the number of descriptors held by treemacs - unless windows has a strange filenotify implementation - is probably somewhere in the low two digit range.

Moving files around does not, to the best of my knowledge, create any new file handles. And even if it did to such a degree as you describe, it would be a general Emacs problem. All treemacs does is call primitive functions implemented in Emacs' C core.

If you want to debug this you can try using treemacs without filewatch-mode, then we'll know if there's something wrong with its file descriptors.

**Comment by mcraveiro** [comment]
Hi,

I use Emacs on Windows daily and I also seem to be having this issue. I did a test this week by not using treemacs and I didn't get the usual error. I will try to use treemacs without follow mode and see if that makes any difference.

**Comment by Alexander-Miller** [comment]
follow-mode is not the problem, filewatch-mode is - treemacs is creating "open files" to watch your directories for changes. 

If you think treemacs is watching something it shouldn't you can run `(maphash (lambda (k _) (message "%s" k)) treemacs--filewatch-index)`. The list this prints should correspond to the open directories in treemacs.

**Comment by mcraveiro** [comment]
Yep this has definitely solved my problem. I recommend not using ```filewatch-mode``` on windows.
