### ISSUE TITLE
How to make treemacs open in the previous window where i left ?

### ISSUE THREAD

**Issue by sofeepokhrel** [Alexander-Miller/treemacs#952]
When i've open 4 5 multiple buffer at the same window. when i toggle and go to treemacs using `alt+0`I want treemacs open the new file in that buffer out of 4 5 buffer in that same window.

Like for example,
Out of `1 2 3 4` buffer opened in same  window with different files, and from `3` i used `Alt+0` goes to treemacs and open an another file, which isnt in that `1 2 3 4` , then i want to open that file in `3` , not in other . 

 
Thank you for helping. :)

**Comment by Alexander-Miller** [comment]
Sounds like you're asking for `or` - `treemacs-visit-node-in-most-recently-used-window`.

**Comment by sofeepokhrel** [comment]
In pressing `or` while i'm in treemacs  it takes me to the buffer i was previously in. 

Thank you exactly what i'm looking for. 
Wishing you good day and happy life .
