### ISSUE TITLE
How can I change the treemacs symbol for non truncated lines?

### ISSUE THREAD

**Issue by apoorv569** [Alexander-Miller/treemacs#954]
Treemacs by default shows `$` sign to indicate that the line is exceeding the visible area. Here is a photo for reference,
https://i.postimg.cc/zG3CJNzt/2022-06-20-17-01.png

Is it possible to change this symbol to something else like `...` or `->`?

**Comment by Alexander-Miller** [comment]
This is not a treemacs feature, but default Emacs behavior. To change it you need to do something like this https://emacs.stackexchange.com/questions/54817/remove-dollar-sign-at-beginning-of-line
