### ISSUE TITLE
Menu bar item

### ISSUE THREAD

**Issue by ylluminarious** [Alexander-Miller/treemacs#96]
Treemacs ought to have a menu bar item for those of us who haven't memorized all the key bindings. At the moment, the only solution for getting a key binding that I can't remember requires something like `C-h b`. This makes things difficult since you have to hunt around to find what you need. It would be much nicer to have a menu bar item. If you'd like a simple reference implementation, you could check out [`paredit-menu.`](https://github.com/phillord/paredit-menu/blob/master/paredit-menu.el)

**Comment by Alexander-Miller** [comment]
>  At the moment, the only solution for getting a key binding that I can't remember requires something like C-h b

Did you read the readme, specifically the Quickstart part for people who don't want to have to read the whole readme (which I admit is pretty damn long) ? The helpful hydra gives you a nicely formatted table of all the keybinds, separated by category, and takes into account any keybind changes you might have made yourself. That does sound like what you're looking for.

I don't use paredit and haven't found any pictures of the menu. Can you show me a screenshot of what the paredit menu looks like? Does it offer anything the helpful hydra does not?

**Comment by ylluminarious** [comment]
@Alexander-Miller Ugh, I feel stupid now... thanks for letting me know about `?`. I guess that must have slipped me when I read the README.

A menu bar still might be helpful, though I actually don't think it's any better than `?` now. This is basically what `paredit-menu` looks like:

---
![paredit1](https://user-images.githubusercontent.com/4912973/32825076-8f87d9a0-c9b1-11e7-81f4-3af7811cfde0.png)
---
![paredit2](https://user-images.githubusercontent.com/4912973/32825084-92a60f44-c9b1-11e7-8433-516372bb60b1.png)

**Comment by Alexander-Miller** [comment]
Interesting idea, but quite awkward since nearly everything in treemacs depends on the position of the cursor.

I do have a plan to add a mouse interface in the future using the same method as yasnippets x-window prompt function.
