### ISSUE TITLE
no icon for the first file or directory 

### ISSUE THREAD

**Issue by yitang** [Alexander-Miller/treemacs#961]
as shown below: 

<img width="208" alt="image" src="https://user-images.githubusercontent.com/6054101/178935176-9f3ae809-2d04-4cb8-835d-1240345d770a.png">

I'm using 

(use-package treemacs-icons-dired
  :hook (dired-mode . treemacs-icons-dired-enable-once)
  :ensure t)

the version is v2.9.5 (installed 2022.02.10) @ Emacs 29.0.50

**Comment by Alexander-Miller** [comment]
What does your dired config look like?
My guess is that you  have some kind of filter that removes lines that treemacs usually skips.

**Comment by Alexander-Miller** [comment]
I've pushed a patch to use a hopefully better method to detect which lines to skip. Try again with the latest version.
