### ISSUE TITLE
Help Requested, User Issue, Use-package (no bug)

### ISSUE THREAD

**Issue by vcg3rd** [Alexander-Miller/treemacs#963]
I apologize if I should go to an Emacs forum, and someone is welcome to close this.  I put it here because it's the most recent instance for me, and I really don't know how to ask on Stack Exchange and have no Reddit account.

I am just a normal guy who has used Emacs and Org for over a decade because it fits so many needs, but not only do I know zero elisp, I don't even know CSS.  I make due, but technical documentation tends to be written by those who know for those who know.

Anyway, I don't use use-package.  Now it seems like documentation assumes one does.  Neotree has served me OK, but treemacs seems like it would be a quantum leap and has features I know I would use, but the configuration instructions are just something I won't grok. 

I may be missing something entirely.  Can one blend use-package configuration with whatever before it is called, that uses setq?  If not, how would I, if possible, configure treemacs without use-package? Sounds like a big ask.  Sorry, again.

**Comment by Alexander-Miller** [comment]
There is nothing special about use-package or treemacs needing it. It's just a useful DSL that also handles downloading and lazy-loading. It's popular, so that's what I put in my readme. Personally I don't use it either.

However you set up neotree, you can do the same thing with treemacs.

**Comment by vcg3rd** [comment]
Bless you!  And thanks for adding the discussion tag!  I'm kinda jazzed about giving it a whirl!  Thanks for developing it!

**Comment by Alexander-Miller** [comment]
And on the topic of Emacs forums - I can recommend reddit's /r/emacs. Plenty of useful information and even a weekly thread for general questions you may have: https://www.reddit.com/r/emacs/comments/w3gx6o/weekly_tips_tricks_c_thread/
