### ISSUE TITLE
Setting the default workspace

### ISSUE THREAD

**Issue by Schievel1** [Alexander-Miller/treemacs#964]
When I delete everything in `treemacs-edit-workspaces` except for one workspace, I close Emacs then restart it, it adds to more workspaces, one called "No Perspective" with a project which is my $home and one called "Perspective 1" with a project that is the emacs binary folder. 
Whenever I restart Emacs it adds those back again and it also selects the "Perspective 1". 

I don't really care that much about those extra workspaces, if I could just make it so that it starts up with a default workspace I choose. 
I tried `treemacs-set-fallback-workspace` on the workspace I want as default already, but that wont do the trick. 

I am running emacs-28.1 on windows 10.

**Comment by Xalares** [comment]
Same issue here, same version of Emacs (28.1) on Arch Linux. A new workspace is added called "No Tabs" with my $HOME directory as workspace, and it uses it as default, instead of the real default.

**Comment by Alexander-Miller** [comment]
>  one called "No Perspective" with a project which is my $home and one called "Perspective 1" with a project that is the emacs binary folder.

Treemacs creates workspaces like that when install treemacs-persp and tell it to use perspectives as the scope for your buffers. This feature needs to be explicitly enabled, somewhere in your config there's a line that looks like this: `(treemacs-set-scope-type 'Perspectives)`. Just remove that part and treemacs should go back to behaving as you want it to.

**Comment by Schievel1** [comment]
I tried with M-x describe-variable and that variable does not seem to exist
