### ISSUE TITLE
Treemacs window is left in erred state after dap-debug is ran.

### ISSUE THREAD

**Issue by simurgh9** [Alexander-Miller/treemacs#965]
Steps to reproduce,

1. Put `test.el` in the current working directory.
```lisp
(package-initialize)
(require 'use-package)
(use-package treemacs)
(use-package lsp-mode)
(use-package dap-mode
  :custom
    (dap-auto-configure-features '(sessions locals controls tooltip repl))
  :config
    (use-package dap-python
      :after python
      :custom
        (dap-auto-configure-mode t)
        (dap-python-debugger 'debugpy) ; pip3 install debugpy
        (dap-python-executable python-shell-interpreter))
  :hook
    (python-mode . dap-ui-mode)
    (python-mode . dap-mode))
```

2. Run `emacs -Q --load test.el`.
3. Run `M-x dap-debug` (dap-python) and choose the file option.
4. Interact with one of the Treemacs windows spawned by `dap-debug` (this is important).
5. Let the debugger finish.
6. Toggle the Treemacs window by `M-x treemacs treemacs`.

Here is a gif,

![treemacs-bug](https://user-images.githubusercontent.com/43047754/171794907-69600c44-d2f8-40ad-8cfb-875efdfe898e.gif)

Other information,

- `[Treemacs] v2.9.5 (installed 2022.05.19) @ Emacs 29.0.50`
- `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2022-05-16, unofficial emacs-snapshot build: http://emacs.secretsauce.net`
- Debian GNU/Linux bookworm/sid

[Link to the Dap mode's Github repository](https://github.com/emacs-lsp/dap-mode)

**Comment by simurgh9** [comment]
_puts the issue in refrigerator_

**Comment by Alexander-Miller** [comment]
No need to grab the fridge, I'm still here :x

I could reproduce the problem, but only with your recipe, not using my own config, which makes debugging difficult, to put it mildly.

I'm not sure where to start either, so let's try asking the other side. @yyoncho what do you think of this?

**Comment by yyoncho** [comment]
@simurgh9 can you test with clean install(delete elpa dir, restart emacs install them again)?

**Comment by simurgh9** [comment]
I recently had to switch computers so I reinstalled emacs and packages anyways. I tried and the same behaviour occurs. @Alexander-Miller I am not sure about your config, but does this not happen if you swap your `use-package` declaration with the one I provided (assuming you are using `use-package`)?

**Comment by yyoncho** [comment]
> I'm not sure where to start either, so let's try asking the other side. @yyoncho what do you think of this?

To me actually sounds like initializing extension before treemacs is run breaks somehow treemacs. Maybe your config preloads something?

**Comment by simurgh9** [comment]
beep bop

**Comment by Alexander-Miller** [comment]
Try again with the latest treemacs. I've pushed an important fix recently and couldn't reproduce
the problem with your recipe anymore.
