### ISSUE TITLE
[help] changing color of selected file

### ISSUE THREAD

**Issue by philiparvidsson** [Alexander-Miller/treemacs#969]
how do I set `treemacs-hl-line-face`?

I'm setting it like this: `(set-face-background 'treemacs-hl-line-face "orange")`

I'm only getting "Invalid face" when doing it, and nothing changes. This is using Doom Emacs. I can't figure out a way to change the selected file color which makes it impossible to see which file is selected, because hl-line uses the same color as the window background...

**Comment by Alexander-Miller** [comment]
> I'm setting it like this: (set-face-background 'treemacs-hl-line-face "orange")

There's no such face in treemacs, unless doom added one.

Anyway you can use `treemacs-window-background-color` to customize how treemacs looks, like this:

`(setf treemacs-window-background-color '("black" . "orange"))`

You'll need to kill the treemacs buffer for the changes to take effect.

**Comment by philiparvidsson** [comment]
Thanks. According to the readme file it's there, but I figured it's a typo or something:

https://github.com/Alexander-Miller/treemacs/commit/e9f439c2ad18b6c9cb3ef962b57f932a9a14b362#diff-ecbc1aa90e9ff97a00b0b2aab1551bceee0c4d21993146bdcb1af4de31c9cac6R638

I found this somewhere on the web:

```
(defface custom-line-highlight '((t (:background "#a49da5" :extend t))) "")
(add-hook
 'treemacs-mode-hook
 (defun channge-hl-line-mode ()
   (setq-local hl-line-face 'custom-line-highlight)
   (overlay-put hl-line-overlay 'face hl-line-face)
   (treemacs--setup-icon-background-colors)))
```

Which works and is what I'm using right now. Could I do something similar using the method you provided (i.e., not touch the window background color - only the selected file background)?

**Comment by Alexander-Miller** [comment]
> Thanks. According to the readme file it's there, but I figured it's a typo or something:

That face only appears in the readme and I'll remove it now. I guess that it's a WIP idea that never went beyond the initial documentation.

> Could I do something similar using the method you provided (i.e., not touch the window background color - only the selected file background)?

You can use nil instead of a color so it won't be changed - `'(nil . "orange")`.
