### ISSUE TITLE
Can't select parent directory

### ISSUE THREAD

**Issue by NikhilRajPandey** [Alexander-Miller/treemacs#972]
Suppose that I have selected in `/home/master/Documents` by calling `treemacs-select-directory` in treemacs then if i select `/home/master` then it returned on messages
`
treemacs--consolidate-projects: Wrong type argument: arrayp, nil

and instead of selecting that parent folder it will add it as workspace.

**Comment by Alexander-Miller** [comment]
Should be fixed now. Let me now if anything else is amiss.

**Comment by Alexander-Miller** [comment]
BTW shifting your project up and down one level can also be done with `M-H treemacs-root-up` & `M-L treemacs-root-down`.

**Comment by NikhilRajPandey** [comment]
Thanks for working on

**Comment by NikhilRajPandey** [comment]
> BTW shifting your project up and down one level can also be done with `M-H treemacs-root-up` & `M-L treemacs-root-down`.

Thanks for telling but back then unitl you hav'nt fixed that I was using

`(defun mine-treemacs-select-directory(arg)
  (interactive (list (read-file-name "Open directory:")))
  (treemacs-kill-buffer)
  (treemacs--show-single-project arg "abc")
)`
