### ISSUE TITLE
Treemacs not recognized as window anymore

### ISSUE THREAD

**Issue by ITler** [Alexander-Miller/treemacs#973]
[Treemacs] v2.9.5 (installed 2022.09.02) @ Emacs 28.1

### faulty situation since reinstalling doom emacs fresh
1. opening treemacs works as usual, i.e. `SPC o p`, treemacs gets focus
2. jumping out of treemacs window(?) using i.e. `evil-window-right` works as usual
3. trying to jump back into the treemacs window with `evil-window-left` does not work anymore.

However, mouse clicking into treemacs sets focus correctly.

Also, there was no change in my doom emacs config. I update doom and packages on a regular basis. However, today doom emacs itself and all packages where installed fresh.

I would appreciate any advise.

**Comment by ITler** [comment]
Works again.

**Comment by Alexander-Miller** [comment]
Treemacs has the flag `treemacs-is-never-other-window` which would have the effect you describe - make it invisible to anything using `other-window`, like evil's navigation. Maybe doom decided to enable it temporarily?

Other than that I recommend `treemacs-select-window` that will let you select treemacs from anywhere, without moving between neighbouring windows. It can also let you move back to where you came from, depending on the value of `treemacs-select-when-already-in-treemacs`.
