### ISSUE TITLE
Change all treemacs faces

### ISSUE THREAD

**Issue by heeh** [Alexander-Miller/treemacs#976]
Is there a simple way to change `all faces of treemacs`? I do not want to override `emacs default face`.

**Comment by Alexander-Miller** [comment]
Treemacs defines close to 30 faces. Many of them inherit their looks from the basic syntax highlighting colors, but not all of them. So if you want to change many faces of treemacs you'll have to go through each one you want changed using something like this:

```Elisp
(custom-set-faces
 '(treemacs-directory-face ((t (:background "green" :foreground "yellow"))))
 '(treemacs-root-face      ((t (:background "blue"  :foreground "red")))))
```

The `describe-char` command can tell you which face is active at your cursor (which you can make visible with `treemacs-show-cursor`).
