### ISSUE TITLE
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'

### ISSUE THREAD

**Issue by harveyraja** [Alexander-Miller/treemacs#978]
Receiving these messages when executing dap-debug on a golang project. The visual side affect appears to be the dap local variables buffer is unable to expand and show all local variables. The expandable node seems to repeat itself (visually) upon ui click to expand the node. The error message reported by treemacs makes me correlate the log message below and the visual side affects. 

Let me know what other info you need.

Log messages:

[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [2 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [3 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [4 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [5 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [6 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [7 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [8 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [9 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [10 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [11 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [12 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [13 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [14 times]
[Treemacs] No RET action defined for node of type treemacs-generic-open-state.
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [16 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [17 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [18 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [19 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [42 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [23 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [24 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [25 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [26 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [27 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [28 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [60 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [32 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [33 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [34 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [35 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-closed-state'. [114 times]
[Treemacs] This function cannot expand a node of type 'treemacs-generic-open-state'. [41 times]

Relevant Installed packages:
  treemacs-tab-bar               20220221.2038  installed             Tab bar integration for treemacs
  lsp-treemacs                   20220502.459   dependency            LSP treemacs
  treemacs                       20220914.1421  dependency            A tree style file explorer package

**Comment by Alexander-Miller** [comment]
The treemacs extension api has recently undergone a thorough - and very necessary - rewrite. Unfortunately the changes are not backwards compatible. @yyoncho and I are currently handling the migration of lsp related packages in #677. In the meantime you can stick with the latest pre-rewrite version of treemacs - `2.11`, commit `938c2678dc29817f57871445bc25699da0df076d`.
Sorry about the inconvenience.

**Comment by harveyraja** [comment]
Thanks for the update @Alexander-Miller. Is there an emacs package manager friendly way to roll back to that version?

**Comment by Alexander-Miller** [comment]
Do you have use-package? If yes you can clone treemacs, checkout the commit and give use-package a `:load-path` argument pointing to treemacs' `/src/elisp` directory.

**Comment by harveyraja** [comment]
Considering #677  is now closed does this mean I should expect treemacs, lsp & dap to work now?
