### ISSUE TITLE
No such file or directory treemacs-treelib

### ISSUE THREAD

**Issue by rubin55** [Alexander-Miller/treemacs#979]
I updated Doom Emacs today, and I'm getting the following error message when opening files:

```
File mode specification error: (file-missing Cannot open load file No such file or directory treemacs-treelib)
```

Full message log:

```
Doom loaded 339 packages across 67 modules in 2.289s
Package cl is deprecated
No matches [3 times]
Changed directory to ’~/Syncthing/Documents/Rubin/Courses/Exercism/ruby/hello-world/’
Loading /home/rubin/.emacs.d/.local/cache/recentf...done
markdown-mode math support enabled
Note: standard-indent, tab-width, evil-shift-width adjusted to 4
Analyzing the buffer...done
Guessing...done
Nothing to change
Note: ruby-indent-level, tab-width, evil-shift-width adjusted to 2
File mode specification error: (file-missing Cannot open load file No such file or directory treemacs-treelib)
mouse-minibuffer-check: Minibuffer window is not active
```

I can't find other references on the internet w/regards to `treemacs-treelib` and it seems to be a relatively recent thing, so I thought it might be a bug in treemacs.

**Comment by nqminhuit** [comment]
Here is my work around in case you are blocked: https://github.com/doomemacs/doomemacs/pull/6812#issuecomment-1250615580

**Comment by Alexander-Miller** [comment]
Don't know about doom, but that treelib module is the new version of the extension api. Doom should probably use treemacs v2.11 until the breaking changes have been smoothed over.
