### ISSUE TITLE
'error in process sentinel: Args out of range: "", -1' when save org files

### ISSUE THREAD

**Issue by binbowang1987** [Alexander-Miller/treemacs#981]
version: emacs 28.1
OS: Windows 11

If the org files are listed in treemacs project, when I edit the org files and save, this error will happen.
![image](https://user-images.githubusercontent.com/8586061/192242860-9a95679f-84df-4517-8058-825f94631820.png)

**Comment by Alexander-Miller** [comment]
What is the output of running `python /treemacs/install/location/treemacs-single-file-git-status.py /path/to/your/org/file NONE`?

**Comment by binbowang1987** [comment]
There is nothing output after run the command `python elpa\treemacs-20220917.1219\treemacs-single-file-git-status.py E:\test\test.org NONE`
![image](https://user-images.githubusercontent.com/8586061/192408341-4a6c3c64-7dde-480c-8d7e-e7c461b5f76b.png)

**Comment by binbowang1987** [comment]
The problem was found.  
On my OS, `C:\Users\hua'wei\AppData\Local\Microsoft\WindowsApps` was added to user's PATH, and there is a `python.exe`, which cause emacs invoke error.

![image](https://user-images.githubusercontent.com/8586061/192413378-064b3f34-d4d7-4146-b5bd-41c39e611baa.png)

I removed  `C:\Users\hua'wei\AppData\Local\Microsoft\WindowsApps`  from users's PATH, this issue was gone.  
Thanks @Alexander-Miller for your help.
