### ISSUE TITLE
Eager macro-expansion failure error.

### ISSUE THREAD

**Issue by zw963** [Alexander-Miller/treemacs#986]
Following is the error message when start emacs daemon.

--------------
Eager macro-expansion failure: (wrong-number-of-arguments ((cl-struct-treemacs-extension-tags t) (extension &rest --cl-rest--) "Initialise an external buffer for use with the given EXTENSION.

EXTENSION is the same symbol that was passed as a `:key' argument
to `treemacs-define-variadic-entry-node-type'.

WITH-EXPAND-DEPTH indicates the number of nodes that should be expanded *in
addition* to the default.  If a value is given that is not a number then
treemacs will assume that *all* possible nodes should be expanded.

AND-DO can be used to set up buffer-local variables after the buffer has
switched over to `treemacs-mode'.

(fn EXTENSION &key (WITH-EXPAND-DEPTH 0) AND-DO)" (let* ((with-expand-depth (car (cdr (or (plist-member --cl-rest-- ':with-expand-depth) '(nil 0))))) (and-do (car (cdr (plist-member --cl-rest-- ':and-do))))) (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((memq (car --cl-keys--) '(:with-expand-depth :and-do :allow-other-keys)) (setq --cl-keys-- (cdr (cdr --cl-keys--)))) ((car (cdr (memq ':allow-other-keys --cl-rest--))) (setq --cl-keys-- nil)) (t (error "Keyword argument %s not one of (:with-expand-depth :and-do)" (car --cl-keys--)))))) (cons 'progn (cons '(treemacs--disable-fringe-indicator) (cons '(treemacs-with-writable-buffer (erase-buffer)) (cons '(let ((treemacs-fringe-indicator-mode nil) (treemacs--in-this-buffer t)) (treemacs-mode)) (cons '(setq-local treemacs-space-between-root-nodes nil) (cons '(setq-local treemacs--in-this-buffer :extension) (cons and-do (cons (list 'treemacs--render-extension (cons 'let (cons (list (list 'instance (list 'treemacs--ext-symbol-to-instance (list 'quote extension)))) (cons (list 'treemacs-static-assert '(and instance (treemacs-extension->variadic\? instance)) "%s is not a variadic extension" extension) '(instance)))) (cons 'if (cons (list 'numberp with-expand-depth) (cons with-expand-depth '(999))))) '((goto-char 1) (treemacs--evade-image))))))))))))) 0)

--------

And, this issue probably relative to #982  and https://github.com/emacs-lsp/dap-mode/issues/673

**Comment by zw963** [comment]
because this should be fix by lsp/dap-mode, close now.

**Comment by MPE2016** [comment]
Hi there, 

I seem to have this exact seem same problem, and it causes my treemacs (3.1) to no longer work. I have no idea what to do now, however. Can someone help me out with that?

Thanks in advance!

All the best,

MPE

**Comment by zw963** [comment]
> Hi there,
> 
> I seem to have this exact seem same problem, and it causes my treemacs (3.1) to no longer work. I have no idea what to do now, however. Can someone help me out with that?
> 
> Thanks in advance!
> 
> All the best,
> 
> MPE

You need `(require 'treemacs-extensions)` to workaround this.
