### ISSUE TITLE
File mode specification error: (void-function treemacs-define-leaf-node)

### ISSUE THREAD

**Issue by JakeRess** [Alexander-Miller/treemacs#988]
Eager macro-expansion failure: (wrong-number-of-arguments (1 . 1) 0)
File mode specification error: (void-function treemacs-define-leaf-node)

**Comment by JakeRess** [comment]
Debugger entered--Lisp error: (void-function treemacs-define-leaf-node)
  (treemacs-define-leaf-node metals-leaf 'dynamic-icon :ret-action #'lsp-metals-treeview--exec-node-action :mouse1-action #'(lambda (&rest args) (interactive) (lsp-metals-treeview--exec-node-action args)))
  load-with-code-conversion("/Users/rhyme/.emacs.d/elpa/28.2/develop/lsp-metals..." "/Users/rhyme/.emacs.d/elpa/28.2/develop/lsp-metals..." nil t)
  require(lsp-metals-treeview)
  byte-code("\305\306!\210\305\307!\210\305\310!\210\305\311!\210\305\312!\210\305\313!\210\314\315\316\317\320\306\321\322\323\324&\11\210\325\303\326\327\330DD\331\320\315\332\333\323..." [lsp-metals-coursier-download-url lsp-metals-coursier-store-path lsp-metals-coursier-decompress lsp-metals-server-command lsp-metals-metals-store-path require lsp-mode dap-mode lsp-lens lsp-metals-protocol lsp-metals-treeview view custom-declare-group lsp-metals nil "LSP support for Scala, using Metals." :group :link (url-link "https://scalameta.org/metals") :package-version (lsp-metals . "1.0") custom-declare-variable funcall function #f(compiled-function () #<bytecode 0x1f40e8cab7314>) "The command to launch the Scala language server." :type file (lsp-metals . "1.0") lsp-metals-server-args #f(compiled-function () #<bytecode 0x1f400016fe914>) "Extra arguments for the Scala language server." (repeat string) (lsp-metals . "1.0") lsp-metals-server-install-dir #f(compiled-function () #<bytecode -0x1c0691efc7d5ff44>) "Installation directory for Metals server." directory (lsp-metals . "1.2") #f(compiled-function () #<bytecode -0x1008f25fb16b75ff>) "The path where Coursier will be stored." (lsp-metals . "1.2") #f(compiled-function () #<bytecode -0x1c069cec94b823c4>) "The path where Metals will be stored." (lsp-metals . "1.2") #f(compiled-function () #<bytecode 0x16d0f3e7f9dd505e>) "Download url for coursier." string (lsp-metals . "1.2") #f(compiled-function () #<bytecode -0x1df073503092ccfa>) ...] 12)
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_338>(lsp-metals)
  mapc(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_338> (ccls lsp-actionscript lsp-ada lsp-angular lsp-ansible lsp-bash lsp-beancount lsp-clangd lsp-clojure lsp-cmake lsp-crystal lsp-csharp lsp-css lsp-d lsp-dart lsp-dhall lsp-docker lsp-dockerfile lsp-elm lsp-elixir lsp-emmet lsp-erlang lsp-eslint lsp-fortran lsp-fsharp lsp-gdscript lsp-go lsp-gleam lsp-graphql lsp-hack lsp-grammarly lsp-groovy lsp-haskell lsp-haxe lsp-idris lsp-java lsp-javascript lsp-json lsp-kotlin lsp-latex lsp-ltex lsp-lua lsp-markdown lsp-marksman lsp-mint lsp-nginx lsp-nim lsp-nix lsp-magik lsp-metals ...))
  seq-do(#<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_338> (ccls lsp-actionscript lsp-ada lsp-angular lsp-ansible lsp-bash lsp-beancount lsp-clangd lsp-clojure lsp-cmake lsp-crystal lsp-csharp lsp-css lsp-d lsp-dart lsp-dhall lsp-docker lsp-dockerfile lsp-elm lsp-elixir lsp-emmet lsp-erlang lsp-eslint lsp-fortran lsp-fsharp lsp-gdscript lsp-go lsp-gleam lsp-graphql lsp-hack lsp-grammarly lsp-groovy lsp-haskell lsp-haxe lsp-idris lsp-java lsp-javascript lsp-json lsp-kotlin lsp-latex lsp-ltex lsp-lua lsp-markdown lsp-marksman lsp-mint lsp-nginx lsp-nim lsp-nix lsp-magik lsp-metals ...))
  lsp--require-packages()
  lsp()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook scala-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook scala-mode-hook))
  run-mode-hooks(scala-mode-hook)
  scala-mode()
  set-auto-mode-0(scala-mode nil)
  set-auto-mode--apply-alist((("\\.tsx\\'" . typescript-tsx-mode) ("\\.vue\\'" . vue-mode) ("Procfile\\'" . yaml-mode) ("\\.\\(yml\\|yaml\\)\\'" . yaml-mode) ("\\.djhtml\\'" . web-mode) ("\\.ctp\\'" . web-mode) ("\\.svelte\\'" . web-mode) ("\\.ejs\\'" . web-mode) ("\\.eco\\'" . web-mode) ("\\.hbs\\'" . web-mode) ("\\.handlebars\\'" . web-mode) ("\\.mustache\\'" . web-mode) ("\\.erb\\'" . web-mode) ("\\.eex\\'" . web-mode) ("\\.as[cp]x?\\'" . web-mode) ("\\.[gj]sp\\'" . web-mode) ("\\.htm\\'" . web-mode) ("\\.html\\'" . web-mode) ("\\.xml\\'" . web-mode) ("\\.twig\\'" . web-mode) ("\\.tpl\\.php\\'" . web-mode) ("\\.phtml\\'" . web-mode) ("\\.sc\\'" . scala-mode) ("\\.pug$" . pug-mode) ("\\.mdx\\'" . markdown-mode) ("\\.mdk\\'" . markdown-mode) ("\\.mkd\\'" . markdown-mode) ("Cask\\'" . emacs-lisp-mode) ("\\*.el\\'" . emacs-lisp-mode) ("\\.plist\\'" . nxml-mode) ("\\.[cm]?js\\'" . js2-mode) ("\\.\\(e?ya?\\|ra\\)ml\\'" . yaml-mode) ("\\.ts\\'" . typescript-mode) ("\\.slim\\'" . slim-mode) ("\\.sass\\'" . sass-mode) ("\\.\\(?:jade\\|pug\\)\\'" . pug-mode) ("\\.\\(scala\\|sbt\\|worksheet\\.sc\\)\\'" . scala-mode) ("\\(?:\\(?:\\.\\(?:b\\(?:\\(?:abel\\|ower\\)rc\\)\\|json\\(?:l..." . json-mode) ("\\.haml\\'" . haml-mode) ("/Jenkinsfile\\'" . groovy-mode) ("\\.g\\(?:ant\\|roovy\\|radle\\)\\'" . groovy-mode) ("/git/ignore\\'" . gitignore-mode) ("/info/exclude\\'" . gitignore-mode) ("/\\.gitignore\\'" . gitignore-mode) ("/etc/gitconfig\\'" . gitconfig-mode) ("/\\.gitmodules\\'" . gitconfig-mode) ("/git/config\\'" . gitconfig-mode) ("/modules/.*/config\\'" . gitconfig-mode) ("/\\.git/config\\'" . gitconfig-mode) ("/\\.gitconfig\\'" . gitconfig-mode) ...) nil nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer MedicalSubmitService.scala> "~/Documents/Dev/Projects/Drip/drip-zd/zd-monorepo/..." nil nil "~/Documents/Dev/Projects/Drip/drip-zd/zd-monorepo/..." (282300766 16777224))
  #<subr find-file-noselect>("/Users/rhyme/Documents/Dev/Projects/Drip/drip-zd/z..." nil nil nil)
  apply(#<subr find-file-noselect> "/Users/rhyme/Documents/Dev/Projects/Drip/drip-zd/z..." (nil nil nil))
  editorconfig--advice-find-file-noselect(#<subr find-file-noselect> "/Users/rhyme/Documents/Dev/Projects/Drip/drip-zd/z..." nil nil nil)
  apply(editorconfig--advice-find-file-noselect #<subr find-file-noselect> ("/Users/rhyme/Documents/Dev/Projects/Drip/drip-zd/z..." nil nil nil))
  find-file-noselect("/Users/rhyme/Documents/Dev/Projects/Drip/drip-zd/z..." nil nil nil)
  find-file("/Users/rhyme/Documents/Dev/Projects/Drip/drip-zd/z...")
  projectile--find-file(nil)
  projectile-find-file()
  projectile-switch-project-by-name("~/Documents/Dev/Projects/Drip/drip-zd/zd-monorepo/" nil)
  #f(compiled-function (project) #<bytecode 0x6a7cf74bac005ad>)("~/Documents/Dev/Projects/Drip/drip-zd/zd-monorepo/")
  projectile-completing-read("Switch to project: " ("~/Documents/Dev/Projects/Rhyme/BackStore/" "~/Documents/Dev/Projects/Drip/drip-zd/zd-monorepo/" "~/.emacs.d/" "~/Documents/Dev/Projects/Drip/drip-zd/zd-monorepo/...") :action #f(compiled-function (project) #<bytecode 0x6a7cf74bac005ad>))
  projectile-switch-project(nil)
  funcall-interactively(projectile-switch-project nil)
  command-execute(projectile-switch-project)

**Comment by eamonnsullivan** [comment]
I have opened a similar issue against lsp-metals, where I noticed it, but this might be the main cause.

**Comment by eamonnsullivan** [comment]
Almost certainly [this commit](https://github.com/Alexander-Miller/treemacs/commit/75ba10f4a4cd841aff33e702716300e2b0ad791c) as that removes the whole module where that macro lives. Probably intentional.

**Comment by Alexander-Miller** [comment]
Very much intentional. A rewrite of the extensions api has been in the works for years now, and has dropped a few weeks ago. As annoying as that breaking change must be for you, for me it means an api that is no longer terrible to maintain and that supports long requested features like async extensions, so there is nothing I can do here but close this ticket.

You can still stick to treemacs v2.11 until lsp-metals can update.
