### ISSUE TITLE
Improper handling of `git status` output in "simple" treemacs-git-mode

### ISSUE THREAD

**Issue by eeowaa** [Alexander-Miller/treemacs#991]
When `treemacs-git-mode` is operating in `simple` mode and is displaying a git project containing modified, untracked, and ignored paths, the following messages are frequently logged to the `*Messages*` buffer:

```
Invalid face reference: M
Invalid face reference: ?
Invalid face reference: !
```

It appears that status codes output by the following command (see function `treemacs--git-status-process-simple` and **git-status(1)**) are eventually being taken as font references, potentially by `treemacs-do-update-single-file-git-state`:

```
GIT_OPTIONAL_LOCKS=0 git status --porcelain --ignored=matching -z .
```

On my system, the above command outputs lines like this (note that I have replaced the `NUL` characters with newlines for readability):

```
 M <modified-path>
?? <untracked-path>
!! <ignored-path>
```

Local system information:

- Treemacs v3.0
- GNU Emacs 28.1
- Git 2.38.1
- Fedora Linux 36 / 37

**Comment by Alexander-Miller** [comment]
Sounds like the bug that was fixed in https://github.com/Alexander-Miller/treemacs/commit/358b1cddd6294e1ebd96958a244b243a06c1ca17. Try again with the latest version.

**Comment by eeowaa** [comment]
Thanks, Alexander! That fixed the problem for me!
