### ISSUE TITLE
How to display workspace name at the bottom of treemacs buffer?

### ISSUE THREAD

**Issue by grafov** [Alexander-Miller/treemacs#993]
This is a question, not a bug. By default the mode line of directory with files tree shows message "treemacs" as in the picture below (the line just above the minibuffer):
![screenshot-2022-12-03-17-45-51](https://user-images.githubusercontent.com/607056/205446794-cba1435c-b63a-4cab-a0e8-aa02f349e3d9.png)

How to display something useful instead of "treemacs" word, for example name of the current workspace? I've not found any appropriate variable for customizing this message.

**Comment by Alexander-Miller** [comment]
If you don't see the workspace name then you are using a package to manage your modeline. Treemacs supports a few, without explicitly depending on them, so all you get with them is a basic string.

You can use `treemacs-user-mode-line-format` to set your own modeline like this:

```Elisp
(setf treemacs-user-mode-line-format
      '(:eval (format " Treemacs: %s"
                      (treemacs-workspace->name (treemacs-current-workspace)))))
```

**Comment by grafov** [comment]
Really it was overwrited with custom defun `treemacs--setup-mode-line ()`. I just copypasted your recipe into it and got the right result. Thank you very much for the advice! And for the package too of course :)
