### ISSUE TITLE
wrong-type-argument commandp treemacs-create-dir

### ISSUE THREAD

**Issue by binbowang1987** [Alexander-Miller/treemacs#997]
I removed all other packages, but the error still exists when use `c d` to create directory.

![image](https://user-images.githubusercontent.com/8586061/206831886-0b36586d-8313-433f-91e3-89b419478be2.png)

**Comment by Alexander-Miller** [comment]
The error looks like there is something wrong with your autoloads - to save on startup time the file management commands are not loaded alongside treemacs, but are instead lazy-loaded on demand. 

Installing with use-package should have auto-created all the necessary setup for you, so I cannot say what went wrong, your config looks correct to me (except that you cannot disable a minor mode by changing a variable, you need to call `(treemacs-filewatch-mode -1)`).

Try adding this line:
`(autoload 'treemacs-create-dir "treemacs-file-management" nil t nil)`

If the command is usable afterwards then we know for sure that there is something wrong with your install.

**Comment by binbowang1987** [comment]
after update to `20221221.1301`, the problem is missed.

**Comment by ldeck** [comment]
@Alexander-Miller I'm facing this issue also using `use-package`. 

The above fix works when done for both treemacs-create-dir and treemacs-create-file, but will start getting a little painful if needing to do this for every autoloaded function in every elisp file for treemacs.

Are you aware of any better way to do this using use-package that would make treemacs and lsp-treemacs fully functional

**Comment by ldeck** [comment]
Nevermind. This for me was caused for me by autoloads not firing.
https://github.com/NixOS/nixpkgs/pull/168954
