### ISSUE TITLE
[QUESTION] org-narrow-to-subtree equivalent in treemacs

### ISSUE THREAD

**Issue by colinet-nathan** [Alexander-Miller/treemacs#999]
I was wondering if there's an equivalent to org-narrow-to-subtree in treemacs for a directory in treemacs. So the chosen directory would become the toplevel one until widen is called to get back to the normal dir structure. I think it might be quiet handy on deeply nested projects.

**Comment by Alexander-Miller** [comment]
No such feature exists, though there are some that may close.

I tried some experiments with narrowing some time ago, and while it seems useful in some cases a potentially narrowed buffer in treemacs will break a lot of its assumptions about buffer state and would need adjustments and workarounds in many places. Given the utility of such a feature vs its complexity and the amount of time I have it's just not worth the cost.

Instead you can try some of the following for your workflow:
- `treemacs-project-follow-mode` to auto-focus the current project
- `treemacs-display-current-project-exclusively` to manually the current project
- `treemacs-select-directory` to manually select a directory to focus as the current project
- `treemacs-create-workspace-from-project` to create a new workspace containing just the current project (requires update, I've only uploaded it today)
- `treemacs-root-up` & `treemacs-root-down` to manually move the root of your project.

The latter in particular sounds like what you want (though it only works when there's only one project in your workspace).

**Comment by colinet-nathan** [comment]
> Given the utility of such a feature vs its complexity and the amount of time I have it's just not worth the cost.

yes, that’s understandable. Thank you for your reply.
